set cmd="git describe --long  --dirty "
FOR /F "tokens=*" %%i IN (' %cmd% ') DO SET X=%%i

set cmdY="git config remote.origin.url"
FOR /F "tokens=*" %%j IN (' %cmdY% ') DO SET Y=%%j

echo #if  !defined(_KKBGitVersionNum_)              >  KKBGitVersionNum.h
echo #define _KKBGitVersionNum_                     >> KKBGitVersionNum.h
echo // Generated by Pre-Build-Event                >> KKBGitVersionNum.h
echo namespace KKB                                  >> KKBGitVersionNum.h
echo ^{                                             >> KKBGitVersionNum.h
echo   const char* GitVersionNum      () noexcept;  >> KKBGitVersionNum.h
echo   const char* GitRemoteOriginURL () noexcept;  >> KKBGitVersionNum.h
echo ^}                                             >> KKBGitVersionNum.h
echo #endif                                         >> KKBGitVersionNum.h
echo // Generated by Pre-Build-Event                >  KKBGitVersionNum.cpp
echo #include ^"KKBGitVersionNum.h^"                >> KKBGitVersionNum.cpp
echo namespace KKB                                  >> KKBGitVersionNum.cpp
echo ^{                                             >> KKBGitVersionNum.cpp
echo   const char*  GitVersionNum () noexcept       >> KKBGitVersionNum.cpp
echo   ^{                                           >> KKBGitVersionNum.cpp
echo      return ^"%X%^";                           >> KKBGitVersionNum.cpp
echo   ^}                                           >> KKBGitVersionNum.cpp
echo   //                                           >> KKBGitVersionNum.cpp
echo   const char* GitRemoteOriginURL () noexcept   >> KKBGitVersionNum.cpp
echo   ^{                                           >> KKBGitVersionNum.cpp
echo      return ^"%Y%^";                           >> KKBGitVersionNum.cpp
echo   ^}                                           >> KKBGitVersionNum.cpp
echo ^}                                             >> KKBGitVersionNum.cpp
