C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Configuration.cpp File Reference
#include `FirstIncludes.h`
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string>
*
#include <iostream>
*
#include <fstream>
*
#include <vector>
*
#include `MemoryDebug.h`
*
#include <windows.h>
*
#include `Configuration.h`
*
#include `KKQueue.h`
*
#include `OSservices.h`
*
#include `RunLog.h`
*
Classes
class KKB::Configuration::ConfSection
class KKB::Configuration::ConfSectionList
class KKB::Configuration::Setting
class KKB::Configuration::SettingList
Namespaces
 KKB
KKB The namespace for KKBase Library supporting general functionality needed by almost any application.
Functions
void StripOutAnyComments (KKStr &line)
Function Documentation
void StripOutAnyComments (KKStr & line)
Definition at line 359 of file Configuration.cpp.
References KKB::KKStr::Len(), KKB::KKStr::operator=(), KKB::KKStr::operator[](), and KKB::KKStr::SubStrPart().
{
  bool found = false;
  kkint32 len = line.Len ();
  kkint32 x = 0;
 
  while ((x < (len - 1)) && (!found))
  {
    if ((line[x] == '/') &&
         (line[x + 1] == '/'))
      found = true;
    else
      x++;
  }
  if (found)
  {
    if (x == 0)
      line = "";
    else
      line = line.SubStrPart (0, x - 1);
  }
} /* StripOutAnyComments */