C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ConfusionMatrix2.cpp File Reference
#include `FirstIncludes.h`
*
#include <stdio.h>
*
#include <iomanip>
*
#include <string>
*
#include <iostream>
*
#include <fstream>
*
#include <map>
*
#include <vector>
*
#include `MemoryDebug.h`
*
#include `KKBaseTypes.h`
*
#include `OSservices.h`
*
#include `RunLog.h`
*
#include `ConfusionMatrix2.h`
*
Functions
template<typename T >
KKStr ArrayToDelimitedDelimitedStr (T *_array, kkint32 _count, char _delimiter)
template<typename T >
KKStr ArrayToDelimitedDelimitedStr (const vector< T > &v, char delimiter)
void DelimitedStrToArray (vector< kkint32 > &v, kkint32 minSize, const KKStr &l, char delimiter)
void DelimitedStrToArray (vector< double > &v, kkint32 minSize, const KKStr &l, char delimiter)
void DelimitedStrToArray (kkint32 *_array, kkint32 _count, const KKStr &_l, char _delimiter)
void DelimitedStrToArray (double *_array, kkint32 _count, const KKStr &_l, char _delimiter)
double PercentOf (double x, double y)
KKStr StripOutInvalidLatexCaracters (const KKStr &src)
Function Documentation
template<typename T > KKStr ArrayToDelimitedDelimitedStr (T * _array, kkint32 _count, char _delimiter)
Definition at line 2871 of file ConfusionMatrix2.cpp.
{
  kkint32 x = _count * 10;
  KKStr s (x);
  for (kkint32 x = 0; x < _count; x++)
  {
    if (x > 0)
      s.Append (_delimiter);
    s << _array[x];
  }
  return s;
} /* ArrayToDelimitedDelimitedStr */
template<typename T > KKStr ArrayToDelimitedDelimitedStr (const vector< T > & v, char delimiter)
Definition at line 2891 of file ConfusionMatrix2.cpp.
{
  KKStr s (v.size () * 10);
  for (kkuint32 x = 0; x < v.size (); x++)
  {
    if (x > 0) s.Append (delimiter);
    s << v[x];
  }
  return s;
} /* ArrayToDelimitedDelimitedStr */
void DelimitedStrToArray (vector< kkint32 > & v, kkint32 minSize, const KKStr & l, char delimiter)
Definition at line 2909 of file ConfusionMatrix2.cpp.
References KKB::KKStr::Split().
{
  v.clear ();
  VectorKKStr fields = l.Split (delimiter);
  kkint32 lastField = (kkint32)fields.size ();
  for (kkint32 idx = 0; idx < lastField; ++idx)
    v.push_back (fields[idx].ToInt32 ());
  while (v.size () < (kkuint32)minSize)
    v.push_back ((kkint32)0);
} /* DelimitedStrToArray */
void DelimitedStrToArray (vector< double > & v, kkint32 minSize, const KKStr & l, char delimiter)
Definition at line 2926 of file ConfusionMatrix2.cpp.
References KKB::KKStr::Split().
{
  v.clear ();
  VectorKKStr fields = l.Split (delimiter);
  kkint32 lastField = (kkint32)fields.size ();
  for (kkint32 idx = 0; idx < lastField; idx++)
    v.push_back (fields[idx].ToDouble ());
  while (v.size () < (kkuint32)minSize)
    v.push_back ((double)0);
} /* DelimitedStrToArray */
void DelimitedStrToArray (kkint32 * _array, kkint32 _count, const KKStr & _l, char _delimiter)
Definition at line 2945 of file ConfusionMatrix2.cpp.
References KKB::KKStr::Split().
{
  VectorKKStr fields = _l.Split (_delimiter);
  kkint32 lastField = Min ((kkint32)fields.size (), _count);
  for (kkint32 idx = 0; idx < lastField; idx++)
    _array[idx] = fields[idx].ToInt ();
} /* DelimitedStrToArray */
void DelimitedStrToArray (double * _array, kkint32 _count, const KKStr & _l, char _delimiter)
Definition at line 2960 of file ConfusionMatrix2.cpp.
References KKB::KKStr::Split().
{
  VectorKKStr fields = _l.Split (_delimiter);
  kkint32 lastField = Min ((kkint32)fields.size (), _count);
  for (kkint32 idx = 0; idx < lastField; idx++)
    _array[idx] = fields[idx].ToDouble ();
} /* DelimitedStrToArray */
double PercentOf (double x, double y)
Definition at line 1670 of file ConfusionMatrix2.cpp.
{
  double total = x + y;
  if (total == 0.0)
    return 0.0;
  else
    return 100.0 * x / total;
}
KKStr StripOutInvalidLatexCaracters (const KKStr & src)
Definition at line 473 of file ConfusionMatrix2.cpp.
References KKB::KKStr::Append(), KKB::KKStr::Concat(), KKB::KKStr::KKStr(), KKB::KKStr::Len(), and KKB::KKStr::operator[]().
{
  kkuint32 newLen = (kkint32)(src.Len () * 1.3);
  KKStr result (newLen);
  for (kkuint32 x = 0; x < src.Len (); x++)
  {
    char ch = src[x];
    switch (ch)
    {
      case '#': result << "\\#";
                  break;
      case '$': result << "\\$";
                  break;
      case '&': result << "\\&";
                  break;
      case '_': result << "\\_";
                  break;
      case '%': result << "\\%";
                  break;
      case '{': result << "\\{";
                  break;
      case '}': result << "\\}";
                  break;
        default: result.Append (ch);
                  break;
    }
  }
  return result;
} /* StripOutInvalidLatexCaracters */