C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVector.cpp File Reference
#include `FirstIncludes.h`
*
#include <ctype.h>
*
#include <time.h>
*
#include <string>
*
#include <iostream>
*
#include <fstream>
*
#include <math.h>
*
#include <vector>
*
#include `MemoryDebug.h`
*
#include `KKBaseTypes.h`
*
#include `DateTime.h`
*
#include `KKException.h`
*
#include `OSservices.h`
*
#include `RunLog.h`
*
#include `KKStr.h`
*
#include `FeatureVector.h`
*
#include `ClassProb.h`
*
#include `DuplicateImages.h`
*
#include `FeatureNumList.h`
*
#include `FeatureFileIO.h`
*
#include `MLClass.h`
*
Classes
class KKMLL::FeatureVectorList::BreakTieComparison
class KKMLL::FeatureVectorList::BreakTieComparisonReversed
class KKMLL::FeatureVectorList::ClassNameComparrison
class KKMLL::FeatureVectorList::ClassNameComparrisonReversed
class KKMLL::FeatureVectorList::ImageFileNameComparison
class KKMLL::FeatureVectorList::ImageFileNameComparisonReversed
class KKMLL::FeatureVectorList::ProbabilityComparison
class KKMLL::FeatureVectorList::ProbabilityComparisonReversed
class KKMLL::FeatureVectorList::RootNameComparrison
class KKMLL::FeatureVectorList::RootNameComparrisonReversed
Functions
KKStr GetClassNameByHierarchyLevel (KKStr className, kkint32 level)
void SplitImagesAmongstFolds (kkint32 numOfFolds, kkint32 maxImagesPerClass, FeatureVectorListPtr *folds, FeatureVectorListPtr src)
Function Documentation
KKStr GetClassNameByHierarchyLevel (KKStr className, kkint32 level)
Definition at line 1770 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::KKStr::ExtractToken(), and KKB::KKStr::operator=().
{
  kkint32 curLevel = 0;
  KKStr fullLevelName = "";
  KKStr nextLevelName = className.ExtractToken ("_");
  while ((curLevel < level) && (!nextLevelName.Empty ()))
  {
    curLevel++;
    if (!fullLevelName.Empty ())
      fullLevelName << "_";
    fullLevelName << nextLevelName;
    nextLevelName = className.ExtractToken ("_");
  }
  return fullLevelName;
} /* GetClassNameByHierarchyLevel */
void SplitImagesAmongstFolds (kkint32 numOfFolds, kkint32 maxImagesPerClass, FeatureVectorListPtr * folds, FeatureVectorListPtr src)
Definition at line 1268 of file FeatureVector.cpp.
Referenced by KKMLL::FeatureVectorList::StratifyAmoungstClasses().
{
  src->RandomizeOrder ();
  src->RandomizeOrder ();
  kkint32 imagesInThisList = src->QueueSize ();
  if (maxImagesPerClass > 0)
    imagesInThisList = Min (imagesInThisList, maxImagesPerClass);
  kkint32 x;
  for (x = 0; x < imagesInThisList; x++)
  {
    folds[x % numOfFolds]->AddSingleExample (src->IdxToPtr (x));
  }
} /* SplitImagesAmongstFolds */