C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKThread.cpp File Reference
#include `FirstIncludes.h`
*
#include <fstream>
*
#include <iostream>
*
#include <map>
*
#include <ostream>
*
#include <string>
*
#include <vector>
*
#include `MemoryDebug.h`
*
#include `KKBaseTypes.h`
*
#include <windows.h>
*
#include `KKException.h`
*
#include `MsgQueue.h`
*
#include `OSservices.h`
*
#include `KKThread.h`
*
Classes
struct tagTHREADNAME_INFO
Macros
#define MS_VC_EXCEPTION 0x406D1388
Typedefs
typedef struct tagTHREADNAME_INFO THREADNAME_INFO
Functions
unsigned int ThreadStartCallBack (void *param)
Macro Definition Documentation
#define MS_VC_EXCEPTION 0x406D1388
Definition at line 35 of file KKThread.cpp.
Typedef Documentation
typedef struct tagTHREADNAME_INFO THREADNAME_INFO
Function Documentation
unsigned int ThreadStartCallBack (void * param)
Definition at line 280 of file KKThread.cpp.
References KKB::KKStr::Concat(), KKB::KKThread::Crashed(), KKB::KKThread::ExceptionText(), KKB::KKThread::Run(), KKB::KKThread::Starting, KKB::KKThread::Status(), KKB::KKThread::Stopped, and KKB::KKException::ToString().
  {
    KKThreadPtr tp = (KKThreadPtr)param;
    tp->Status (KKThread::ThreadStatus::Starting);
    try
    {
      tp->Run ();
    }
    catch (const KKException& e1)
    {
      tp->Crashed (true);
      tp->ExceptionText (e1.ToString ());
    }
    catch (const std::exception e2)
    {
      tp->Crashed (true);
      const char* e2What = e2.what ();
      KKStr msg (30 + strlen (e2What));
      msg << "std::exception: " << e2What;
      tp->ExceptionText (msg);
    }
    catch (...)
    {
      tp->Crashed (true);
      tp->ExceptionText ("exception(...) trapped.");
    }
    tp->Status (KKThread::ThreadStatus::Stopped);
    return 0;
  }