C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStr.cpp File Reference
#include `FirstIncludes.h`
*
#include <ctype.h>
*
#include <limits.h>
*
#include <math.h>
*
#include <stdio.h>
*
#include <iostream>
*
#include <memory>
*
#include <sstream>
*
#include <string>
*
#include <vector>
*
#include <string.h>
*
#include `MemoryDebug.h`
*
#include `KKQueue.h`
*
#include `KKStr.h`
*
#include `KKException.h`
*
#include `KKStrParser.h`
*
#include `RunLog.h`
*
#include `XmlStream.h`
*
Classes
class KKB::KKStrList::StringComparison
Functions
kkint32 LocateLastOccurrence (const char *str, char ch)
kkint32 MemCompare (const char *s1, const char *s2, kkint32 s1Idx, kkint32 s2Idx, kkint32 len)
kkint32 SearchStr (const char *src, kkint32 srcLen, kkint32 startPos, const char *srchStr, kkint32 srchStrLen)
void Test2 (ostream &x1, const char *x2)
Function Documentation
kkint32 LocateLastOccurrence (const char * str, char ch)
Definition at line 4791 of file KKStr.cpp.
Referenced by KKB::StrFormatDouble().
{
  if (!str)
    return -1;
  bool found = false;
  size_t len = strlen (str);
  size_t idx = len - 1;
  while ((idx >= 0) && (!found))
  {
    if (str[idx] == ch)
      found = true;
    else
      idx--;
  }
  if (found)
    return (kkint32)idx;
  else
    return -1;
} /* LocateLastOccurrence */
kkint32 MemCompare (const char * s1, const char * s2, kkint32 s1Idx, kkint32 s2Idx, kkint32 len)
Definition at line 2063 of file KKStr.cpp.
Referenced by KKB::KKStr::LocateStr().
{
  for (kkint32 x = 0; x < len; x++)
  {
    if (s1[s1Idx] < s2[s2Idx])
      return -1;
    
    else if (s1[s1Idx] > s2[s2Idx])
      return 1;
    s1Idx++;
    s2Idx++;
  }
  return 0;
} /* MemCompare */
kkint32 SearchStr (const char * src, kkint32 srcLen, kkint32 startPos, const char * srchStr, kkint32 srchStrLen)
Definition at line 3907 of file KKStr.cpp.
Referenced by KKB::KKStr::Find().
{
  if ((!src) || (!srchStr))
    return -1;
  kkint32 numIter = (srcLen - (startPos + srchStrLen - 1));
  const char* startCh = src + startPos;
  kkint32 x;
  for (x = 0; x < numIter; ++x, ++startCh)
  {
    if (strncmp (startCh, srchStr, srchStrLen) == 0)
      return startPos + x;
  }
  return -1;
}
void Test2 (ostream & x1, const char * x2)
Definition at line 4268 of file KKStr.cpp.
References KKB::operator<<().
{
  x1 << x2;
}