C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Matrix.cpp File Reference
#include `FirstIncludes.h`
*
#include <stdlib.h>
*
#include <string.h>
*
#include <stdio.h>
*
#include <math.h>
*
#include <fstream>
*
#include <iostream>
*
#include <ostream>
*
#include <vector>
*
#include `MemoryDebug.h`
*
#include `Matrix.h`
*
#include `KKException.h`
*
#include `OSservices.h`
*
#include `KKStr.h`
*
Macros
#define DBL_EPSILON 2.2204460492503131e-016
#define SQR(X) ((X) * (X))
Functions
ostream & operator<< (ostream &os, const Matrix &matrix)
template<class T >
const T SIGN (const T &a, const T &b)
Macro Definition Documentation
#define DBL_EPSILON 2.2204460492503131e-016
Definition at line 902 of file Matrix.cpp.
#define SQR(X) ((X) * (X))
Definition at line 1218 of file Matrix.cpp.
Function Documentation
ostream& operator<< (ostream & os, const Matrix & matrix)
Definition at line 853 of file Matrix.cpp.
References KKB::Matrix::NumOfCols(), KKB::Matrix::NumOfRows(), and KKB::operator<<().
{
  kkint32 col;
  kkint32 row;
  os << "[" << matrix.NumOfRows () << "," << matrix.NumOfCols () << "]" <<
      std::endl;
  os << "[";
  for (row = 0; row < matrix.NumOfRows (); row++)
  {
    if (row > 0)
      os << " ";
    os << "[";
    for (col = 0; col < matrix.NumOfCols (); col++)
    {
      if (col > 0)
        os << ", ";
      os.width (8);
      os.precision (6);
      os << matrix[row][col];
    }
    os << "]" << std::endl;
  }
  os << "]" << std::endl;
  return os;
} /* operator<< */
template<class T > const T SIGN (const T & a, const T & b) [inline]
Definition at line 1196 of file Matrix.cpp.
{
  if (b >= 0)
  {
    if (a >= 0)
      return a;
    else
      return -a;
  }
  else
  {
    if (a >- 0)
      return -a;
    else
      return a;
  }
} /* SIGN */