C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Raster.cpp File Reference
#include `FirstIncludes.h`
*
#include <memory>
*
#include <math.h>
*
#include <limits.h>
*
#include <fstream>
*
#include <map>
*
#include <string.h>
*
#include <string>
*
#include <iostream>
*
#include <vector>
*
#include `MemoryDebug.h`
*
#include `kku_fftw.h`
*
#include `Raster.h`
*
#include `KKBaseTypes.h`
*
#include `Blob.h`
*
#include `BMPImage.h`
*
#include `Compressor.h`
*
#include `ConvexHull.h`
*
#include `EigenVector.h`
*
#include `GoalKeeper.h`
*
#include `Histogram.h`
*
#include `ImageIO.h`
*
#include `KKException.h`
*
#include `Matrix.h`
*
#include `MorphOpBinarize.h`
*
#include `MorphOpDilation.h`
*
#include `MorphOpErosion.h`
*
#include `MorphOpStretcher.h`
*
#include `OSservices.h`
*
#include `SimpleCompressor.h`
*
#include `MorphOpSobel.h`
*
Functions
float DeltaAngle (float ang1, float ang2)
Returns the difference between two angles in degrees.
template<typename T >
T FindKthValue (T *values, kkint32 arraySize, kkint32 Kth)
bool k_ThinningCheckTransitions (uchar m_Matrix22[][3])
bool k_ThinningStep1cdTests (uchar m_Matrix22[][3])
bool k_ThinningStep2cdTests (uchar m_Matrix22[][3])
kkint32 Max6 (kkint32 x1, kkint32 x2, kkint32 x3, kkint32 x4, kkint32 x5, kkint32 x6)
kkint32 Max9 (kkint32 x1, kkint32 x2, kkint32 x3, kkint32 x4, kkint32 x5, kkint32 x6, kkint32 x7, kkint32 x8, kkint32 x9)
uchar MergeAlpfaBeta (float alpha, uchar alphaPixel, float beta, uchar betaPixel)
kkint32 Min (kkint32 x1, kkint32 x2)
Variables
kkint32 freqHist16BucketIdx [256]
kkint32 freqHistBucketIdx [256]
const MovDir movements [8]
Function Documentation
float DeltaAngle (float ang1, float ang2)
Returns the difference between two angles in degrees.
Given two angles, will determine the angular distance between them, going from the ang1 to ang2. A positive delta indicates that ang2 is in front of ang1, negative means it is behind ang1. The result can be from -180 to +180 degrees.
Definition at line 5328 of file Raster.cpp.
{
  float deltaAng = ang2 - ang1;
  while (deltaAng > 180.0)
    deltaAng = deltaAng - (float)360.0;
  if (deltaAng < -180.0)
    deltaAng = deltaAng + (float)360;
  return deltaAng;
} /* DeltaAngle */
template<typename T > T FindKthValue (T * values, kkint32 arraySize, kkint32 Kth)
Definition at line 7175 of file Raster.cpp.
{
  T pv;
  kkint32 left = 0;
  kkint32 right = arraySize - 1;
  kkint32 pivotIndex = right;
  kkint32 partitionIndex = -1;
  T temp;
  while (partitionIndex != Kth)
  {
    pv = values[pivotIndex];
    
    partitionIndex = left;
    for (kkint32 i = left; i < right; i++)
    {
      if (values[i] <= pv)
      {
        if (i != partitionIndex)
        {
          temp = values[i];
          values[i] = values[partitionIndex];
          values[partitionIndex] = temp;
        }
        partitionIndex = partitionIndex + 1;
      }
    }
    temp = values[partitionIndex];
    values[partitionIndex] = values[right];
    values[right] = temp;
    if (Kth < partitionIndex)
      right = partitionIndex - 1;
    else
      left = partitionIndex + 1;
    pivotIndex = right;
  }
  return values[Kth];
} /* FindKthValue */
bool k_ThinningCheckTransitions (uchar m_Matrix22[][3])
Definition at line 8520 of file Raster.cpp.
Referenced by KKB::Raster::ThinContour().
{
  kkint32 iTransitions=0;
  if ((m_Matrix22[0][0]==1) && (m_Matrix22[1][0]==0)){
    ++iTransitions;}
  if ((m_Matrix22[1][0]==1) && (m_Matrix22[2][0]==0)){
    ++iTransitions;}
  if ((m_Matrix22[2][0]==1) && (m_Matrix22[2][1]==0)){
    ++iTransitions;}
  if ((m_Matrix22[2][1]==1) && (m_Matrix22[2][2]==0)){
    ++iTransitions;}
  
  if ((m_Matrix22[2][2]==1) && (m_Matrix22[1][2]==0)){
    ++iTransitions;}
  
  if ((m_Matrix22[1][2]==1) && (m_Matrix22[0][2]==0)){
    ++iTransitions;}
  if ((m_Matrix22[0][2]==1) && (m_Matrix22[0][1]==0)){
    ++iTransitions;}
  
  if ((m_Matrix22[0][1]==1) && (m_Matrix22[0][0]==0)){
    ++iTransitions;}
  if (iTransitions==1)
    return true;
  else
    return false;
} /* k_ThinningCheckTransitions */
bool k_ThinningStep1cdTests (uchar m_Matrix22[][3])
Definition at line 8507 of file Raster.cpp.
Referenced by KKB::Raster::ThinContour().
{
  if ((m_Matrix22[1][0] + m_Matrix22[2][1] + m_Matrix22[1][2]) &&
      (m_Matrix22[2][1] + m_Matrix22[1][2] + m_Matrix22[0][1])
     )
    return true;
  else
    return false;
}
bool k_ThinningStep2cdTests (uchar m_Matrix22[][3])
Definition at line 8493 of file Raster.cpp.
Referenced by KKB::Raster::ThinContour().
{
  if ((m_Matrix22[1][0] + m_Matrix22[2][1] + m_Matrix22[0][1]) &&
      (m_Matrix22[1][0] + m_Matrix22[1][2] + m_Matrix22[0][1])
     )
    return true;
  else
    return false;
}
kkint32 Max6 (kkint32 x1, kkint32 x2, kkint32 x3, kkint32 x4, kkint32 x5, kkint32 x6) [inline]
Definition at line 240 of file Raster.cpp.
{
  kkint32 r;
  
  if (x1 > x2)
    r = x1;
  else
    r = x2;
  if (x3 > r) r = x3;
  if (x4 > r) r = x4;
  if (x5 > r) r = x5;
  if (x6 > r) r = x6;
  return r;
} /* Max6 */
kkint32 Max9 (kkint32 x1, kkint32 x2, kkint32 x3, kkint32 x4, kkint32 x5, kkint32 x6, kkint32 x7, kkint32 x8, kkint32 x9) [inline]
Definition at line 262 of file Raster.cpp.
{
  kkint32 r;
  
  if (x1 > x2)
    r = x1;
  else
    r = x2;
  if (x3 > r) r = x3;
  if (x4 > r) r = x4;
  if (x5 > r) r = x5;
  if (x6 > r) r = x6;
  if (x7 > r) r = x7;
  if (x8 > r) r = x8;
  if (x9 > r) r = x9;
  return r;
} /* Max9 */
uchar MergeAlpfaBeta (float alpha, uchar alphaPixel, float beta, uchar betaPixel)
Definition at line 6419 of file Raster.cpp.
Referenced by KKB::Raster::DrawLine().
{
  int newPixelValue = (int)(0.5f + alpha * (float)alphaPixel + beta * (float)betaPixel);
  if (newPixelValue > 255)
    newPixelValue = 255;
  return (uchar)newPixelValue;
}
kkint32 Min (kkint32 x1, kkint32 x2) [inline]
Definition at line 229 of file Raster.cpp.
{
  if (x1 < x2)
    return x1;
  else
    return x2;
}
Variable Documentation
kkint32 freqHist16BucketIdx[256]
Initial value:
=
          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1,
           2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3,
           4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5,
           6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7,
           8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9,
           10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11,
      11, 11, 11, 11, 11, 11, 11, 11,
           12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13,
      13, 13, 13, 13, 13, 13, 13, 13,
           14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15,
      15, 15, 15, 15, 15, 15, 15, 15
          }
Definition at line 215 of file Raster.cpp.
Referenced by KKB::Raster::CalcAreaAndIntensityFeatures16().
kkint32 freqHistBucketIdx[256]
Initial value:
=
          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
           3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
           4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
           5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
           6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
           7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7
          }
Definition at line 204 of file Raster.cpp.
Referenced by KKB::Raster::CalcAreaAndIntensityFeatures(), KKB::Raster::CalcAreaAndIntensityHistogram(), and KKB::Raster::CalcAreaAndIntensityHistogramWhite().
const MovDir movements[8]
Initial value:
= {{-1, 0},
                          {-1, 1},
                          { 0, 1},
                          { 1, 1},
                          { 1, 0},
                          { 1, -1},
                          { 0, -1},
                          {-1, -1}
                         }
Definition at line 5346 of file Raster.cpp.
Referenced by KKB::Raster::FollowContour().