C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp File Reference
#include `FirstIncludes.h`
*
#include <stdio.h>
*
#include <fstream>
*
#include <string.h>
*
#include <string>
*
#include <iostream>
*
#include <ostream>
*
#include <vector>
*
#include `MemoryDebug.h`
*
#include `BitString.h`
*
#include `GlobalGoalKeeper.h`
*
#include `KKBaseTypes.h`
*
#include `KKException.h`
*
#include `KKStrParser.h`
*
#include `XmlTokenizer.h`
*
#include `XmlStream.h`
*
Classes
class XmlFactoryArrayDouble
class XmlFactoryArrayFloat
class XmlFactoryArrayFloat2D
class XmlFactoryArrayFloat2DVarying
class XmlFactoryArrayInt32
class XmlFactoryArrayUint16
class XmlFactoryBool
class XmlFactoryDateTime
class XmlFactoryDouble
class XmlFactoryFloat
class XmlFactoryInt32
class XmlFactoryInt64
class XmlFactoryKeyValuePairs
class XmlFactoryKKStr
class XmlFactoryKKStrList
class XmlFactoryKKStrListIndexed
class XmlFactoryUnKnown
class XmlFactoryVectorFloat
class XmlFactoryVectorInt32
class XmlFactoryVectorKKStr
Macros
#define XmlElementArray2DBody(T, TypeName, XmlElementToUse)
#define XmlElementArrayBody(T, TypeName, ParserNextTokenMethod)
#define XmlElementBuiltInTypeBody(T, TypeName, ParseMethod)
#define XmlElementVectorBody(T, TypeName, ParserNextTokenMethod)
Functions
void ExtractAttribute (KKStr &tagStr, KKStr &attributeName, KKStr &attributeValue)
void ReadWholeTag (istream &i, KKStr &tagStr)
Variables
kkint32 xmlLevel = 0
Macro Definition Documentation
#define XmlElementArray2DBody(T, TypeName, XmlElementToUse)
Works with corresponding macro (XmlElementArray2DHeader) defined in header file `XmlStream.h`
Parameters
T The Built-In type, examples: float, kkint32, double, ...
TypeName The name we give the type ex: `Int32`, `Float`, ....
XmlElementToUse the XmlElement derived class that will be used to process each row in the matrix.
Definition at line 1613 of file XmlStream.cpp.
#define XmlElementArrayBody(T, TypeName, ParserNextTokenMethod)
Definition at line 1496 of file XmlStream.cpp.
#define XmlElementBuiltInTypeBody(T, TypeName, ParseMethod)
Works with matching Marco (XmlElementBuiltInTypeHeader) defined in XmlStream.h
Definition at line 1438 of file XmlStream.cpp.
#define XmlElementVectorBody(T, TypeName, ParserNextTokenMethod)
Definition at line 1758 of file XmlStream.cpp.
Function Documentation
void ExtractAttribute (KKStr & tagStr, KKStr & attributeName, KKStr & attributeValue)
Definition at line 412 of file XmlStream.cpp.
References KKB::KKStr::Len(), KKB::KKStr::operator=(), KKB::KKStr::operator[](), and KKB::KKStr::SubStrPart().
{
  kkint32 startIdx = 0;
  kkint32 len = tagStr.Len ();
  attributeName = "";
  attributeValue = "";
  // Skip over leading spaces
  while (startIdx < len)
  {
    if (strchr ("\n\t\r ", tagStr[startIdx]) == NULL)
      break;
    startIdx++;
  }
  if (startIdx >= len)
  {
    tagStr = "";
    return;
  }
  kkint32 idx = startIdx;
  // Skip until we find the '=' character.
  while (idx < len)
  {
    if (tagStr[idx] == '=')
      break;
    ++idx;
  }
  if (idx >= len)
  {
    tagStr = "";
    return;
  }
  attributeName = tagStr.SubStrPart (startIdx, idx - 1);
  ++idx; // Skip past '=' character.
  
  // Skip over leading spaces
  while (idx < len)
  {
    if (strchr ("\n\t\r ", tagStr[idx]) == NULL)
      break;
    ++idx;
  }
  if (idx >= len)
  {
    tagStr = "";
    return;
  }
  int valueStartIdx = idx;
  while (idx < len)
  {
    if (strchr ("\n\t\r ", tagStr[idx]) != NULL)
      break;
    ++idx;
  }
  attributeValue = tagStr.SubStrPart (valueStartIdx, idx - 1);
  tagStr = tagStr.SubStrPart (idx + 1);
  return;
} /* ExtractAttribute */
void ReadWholeTag (istream & i, KKStr & tagStr)
Definition at line 390 of file XmlStream.cpp.
References KKB::KKStr::operator=().
{
  tagStr = "";
  while (!i.eof ())
  {
    char nextCh = i.get ();
    if (nextCh != 0)
      tagStr.Append (nextCh);
    if (nextCh == '>')
      break;
  }
  return;
} /* ReadWholeTag */
Variable Documentation
kkint32 xmlLevel = 0
Definition at line 720 of file XmlStream.cpp.
Referenced by KKB::XmlTag::WriteXML().