KKMLL::FeatureVector Class Reference
Represents a Feature Vector of a single example, labeled or unlabeled.
#include <FeatureVector.h>
Public Types
typedef FeatureVector * FeatureVectorPtr
typedef float FVFloat
Public Member Functions
FeatureVector (kkint32 _numOfFeatures)
FeatureVector (const FeatureVector &_example)
virtual ~FeatureVector ()
void AddFeatureData (kkint32 _featureNum, float _featureData)
void BreakTie (float _breakTie)
Update the BreakTie value.
float BreakTie () const
The difference in probability between the two most likely classes.
const KKStr & ClassName () const
Name of class that this example is assigned to.
virtual FeatureVectorPtr Duplicate () const
void ExampleFileName (const KKStr &_exampleFileName)
Name of source of feature vector, ex: file name of image that the feature vector was computed from.
const KKStr & ExampleFileName () const
Name of file that this FeatureVector was computed from.
void FeatureData (kkint32 _featureNum, float _featureValue)
Assign a value to a specific feature number for the feature vector.
float FeatureData (kkint32 featureNum) const
const float * FeatureData () const
Returns as a pointer to the feature data itself.
float * FeatureDataAlter ()
Same as 'FeatureData() except you can modify the data.
const float * FeatureDataConst () const
bool FeatureDataValid ()
virtual kkint32 MemoryConsumedEstimated () const
void MissingData (bool _missingData)
True indicates that not all the feature data was present when this example was loaded from a data file.
bool MissingData () const
True indicates that one or more features were missing.
void MLClass (MLClassPtr _mlClass)
Assign a class to this example.
MLClassPtr MLClass () const
Class that is example is assigned to.
const KKStr & MLClassName () const
Name of class that this example is assigned to.
kkint32 NumOfFeatures () const
Number of features in this FeatureVector.
bool operator== (FeatureVector &other_example) const
void OrigSize (float _origSize)
The value of Feature[0] before normalization.
float OrigSize () const
The value of Feature[0] before normalization.
void PredictedClass (MLClassPtr _predictedClass)
MLClassPtr PredictedClass () const
const KKStr & PredictedClassName () const
void Probability (float _probability)
Assign a prediction probability to this example.
float Probability () const
The probability assigned by classifier to the predicted class.
void ResetNumOfFeatures (kkint32 newNumOfFeatures)
float TotalOfFeatureData () const
Returns the total of all Feature Attributes for this feature vector.
void TrainWeight (float _trainWeight)
Assign a specific example a higher weight for training purposes.
float TrainWeight () const
void Validated (bool _validated)
Indicated whether an expert has validated the class assignment.
bool Validated () const
void Version (kkint16 _version)
kkint16 Version () const
Protected Member Functions
void AllocateFeatureDataArray ()
Used by container classes such as 'FeatureVectorList'. This way they can determine real underlying class.
Protected Attributes
float * featureData
kkint32 numOfFeatures
Detailed Description
Represents a Feature Vector of a single example, labeled or unlabeled.
Author
Kurt Kramer
Used for the representation of a Single example. You create an instance of this object for each single feature vector. You can subclass from this Class to make a specialized FeatureVector as in the PostLarvaeFV class. Besides keeping track of feature data this class will also track other fields such as ExampleFileName which should indicate where the FeatureVector was derived from, probability, breakTie, and others.
See also
FeatureVectorList
PostLarvaeFV
FeatureFileIO
Used for the representation of a Single example. You create an instance of this object for each single feature vector. You can subclass from this Class to make a specialized FeatureVector as in the PostLarvaeFV class. Besides keeping track of feature data this class will also track other fields such as ExampleFileName which should indicate where the FeatureVector was derived from, probability, breakTie, and others.
See also
FeatureVectorList
PostLarvaeFV
FeatureFileIO
Definition at line 59 of file FeatureVector.h.
Member Typedef Documentation
typedef FeatureVector* KKMLL::FeatureVector::FeatureVectorPtr
Definition at line 63 of file FeatureVector.h.
typedef float KKMLL::FeatureVector::FVFloat
Definition at line 62 of file FeatureVector.h.
Constructor & Destructor Documentation
FeatureVector::FeatureVector (kkint32 _numOfFeatures)
Definition at line 30 of file FeatureVector.cpp.
References AllocateFeatureDataArray(), featureData, KKB::KKStr::KKStr(), and numOfFeatures.
Referenced by KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector(), KKMLL::FeatureEncoder::CreateEncodedFeatureVector(), KKMLL::FeatureEncoder2::EncodeAExample(), KKMLL::FeatureEncoder::EncodeAExample(), KKMLL::GrayScaleImagesFV::GrayScaleImagesFV(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOColumn::LoadFile(), KKMLL::FeatureFileIOUCI::LoadFile(), KKMLL::FeatureFileIOC45::LoadFile(), and KKMLL::FactoryFVProducer::ManufacturFeatureVector().
                                                    :
        featureData (NULL),
        numOfFeatures (_numOfFeatures),
        breakTie (0.0f),
        mlClass (NULL),
        exampleFileName (),
        missingData (false),
        origSize (0.0f),
        predictedClass (NULL),
        probability (-1.0),
        trainWeight (1.0f),
        validated (false),
        version (-1)
{
  AllocateFeatureDataArray ();
}
FeatureVector::FeatureVector (const FeatureVector & _example)
Definition at line 50 of file FeatureVector.cpp.
References AllocateFeatureDataArray(), featureData, KKB::KKStr::KKStr(), and numOfFeatures.
Referenced by Duplicate(), KKMLL::FeatureVectorList::DuplicateListAndContents(), KKMLL::FeatureVectorList::ExtractExamplesForHierarchyLevel(), KKMLL::GrayScaleImagesFV::GrayScaleImagesFV(), and KKMLL::NormalizationParms::ToNormalized().
                                                           :
  featureData (NULL),
  numOfFeatures (_example.numOfFeatures),
  breakTie (_example.breakTie),
  mlClass (_example.mlClass),
  exampleFileName (_example.exampleFileName),
  missingData (false),
  origSize (_example.origSize),
  predictedClass (_example.predictedClass),
  probability (_example.probability),
  trainWeight (_example.trainWeight),
  validated (_example.validated),
  version (-1)
{
  if (_example.featureData)
  {
    AllocateFeatureDataArray ();
    for (kkint32 x = 0; x < numOfFeatures; x++)
      featureData[x] = _example.featureData[x];
  }
}
FeatureVector::~FeatureVector () [virtual]
Definition at line 74 of file FeatureVector.cpp.
References featureData.
{
  delete[] featureData; featureData = NULL;
}
Member Function Documentation
void FeatureVector::AddFeatureData (kkint32 _featureNum, float _featureData)
Parameters
_featureNum Indicates which feature number to update.
_featureData New value to assign to '_featureNum'.
Definition at line 216 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), featureData, KKB::KKException::KKException(), KKB::KKStr::KKStr(), and numOfFeatures.
Referenced by KKMLL::FeatureEncoder::CreateEncodedFeatureVector(), KKMLL::FeatureEncoder2::EncodeAExample(), KKMLL::FeatureEncoder::EncodeAExample(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOC45::LoadFile(), and KKMLL::FeatureVectorList::ReSyncSymbolicData().
{
  if ((_featureNum < 0) || (_featureNum >= numOfFeatures))
  {
    KKStr errMsg (128);
    errMsg << "FeatureVector::AddFeatureData ***ERROR*** FeatureNum[" << _featureNum << "] exceeds
       maximum allowed Feature Number["<< numOfFeatures << "].";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  featureData[_featureNum] = _featureData;
} /* AddFeatureData */
void FeatureVector::AllocateFeatureDataArray () [protected]
Used by container classes such as 'FeatureVectorList'. This way they can determine real underlying class.
Definition at line 129 of file FeatureVector.cpp.
References featureData, and numOfFeatures.
Referenced by FeatureVector().
{
  if (featureData)
    delete featureData;
  featureData = new float [numOfFeatures];
  kkint32 x;
  for (x = 0; x < numOfFeatures; x++)
    featureData[x] = 0;
} /* AllocateFeatureDataArray */
void KKMLL::FeatureVector::BreakTie (float _breakTie) [inline]
Update the BreakTie value.
Definition at line 73 of file FeatureVector.h.
float KKMLL::FeatureVector::BreakTie () const [inline]
The difference in probability between the two most likely classes.
Definition at line 112 of file FeatureVector.h.
Referenced by KKMLL::FeatureVectorList::BreakTieComparison::operator()(), and KKMLL::FeatureVectorList::BreakTieComparisonReversed::operator()().
const KKStr & FeatureVector::ClassName () const
Name of class that this example is assigned to.
Definition at line 192 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), and KKMLL::MLClass::Name().
Referenced by KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::FeatureFileIOUCI::SaveFile(), KKMLL::FeatureFileIOC45::SaveFile(), and KKMLL::FeatureFileIOSparse::SaveFile().
{
  static const
  KKStr imageFeaturesClassNameInvalid = "*INVALID*";
  if (!mlClass)
  {
    cerr << endl
         << "FeatureVector::ClassName *** ERROR ***" << endl
         << endl
         << " Attempt to get ClassName, But not pointing to valid MLClass Object" <<
      endl
         << endl;
    return imageFeaturesClassNameInvalid;
  }
  else
  {
    return mlClass->Name ();
  }
} /* ClassName */
FeatureVectorPtr FeatureVector::Duplicate () const [virtual]
Reimplemented in KKMLL::GrayScaleImagesFV.
Definition at line 94 of file FeatureVector.cpp.
References FeatureVector().
{
  return new FeatureVector (*this);
}
void KKMLL::FeatureVector::ExampleFileName (const KKStr & _exampleFileName) [inline]
Name of source of feature vector, ex: file name of image that the feature vector was computed from.
Definition at line 75 of file FeatureVector.h.
References KKB::KKStr::operator=().
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOColumn::LoadFile(), KKMLL::FeatureFileIOUCI::LoadFile(), KKMLL::FeatureFileIOC45::LoadFile(), and KKMLL::FeatureFileIO::LoadInSubDirectoryTree().
const KKStr& KKMLL::FeatureVector::ExampleFileName () const [inline]
Name of file that this FeatureVector was computed from.
Definition at line 116 of file FeatureVector.h.
Referenced by KKMLL::DuplicateImages::AddSingleExample(), KKMLL::FeatureVectorList::BinarySearchByName(), KKMLL::DuplicateImage::ExampleWithSmallestScanLine(), KKMLL::FeatureVectorList::ExtractDuplicatesByRootImageFileName(), KKMLL::ExtractExampleFileName::ExtractKey(), KKMLL::FeatureFileIO::LoadInSubDirectoryTree(), KKMLL::FeatureVectorList::LookUpByRootName(), KKMLL::FeatureVectorList::ImageFileNameComparison::operator()(), KKMLL::FeatureVectorList::ImageFileNameComparisonReversed::operator()(), KKMLL::FeatureVectorList::RootNameComparrison::operator()(), KKMLL::FeatureVectorList::RootNameComparrisonReversed::operator()(), KKMLL::FeatureVectorList::ClassNameComparrison::operator()(), KKMLL::FeatureVectorList::ClassNameComparrisonReversed::operator()(), KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree(), SVM289_BFS::svm_model::Write(), and SVM289_MFS::Svm_Model::WriteXML().
void FeatureVector::FeatureData (kkint32 _featureNum, float _featureValue)
Assign a value to a specific feature number for the feature vector.
This method will validate that '_featureNum' is not out of range (0 - 'numOfFeatures'). This will prevent the caller from corrupting memory.
Parameters
in _featureNum Feature Number to assign '_featureValue' to.
in _featureValue Value to assign to feature '_featureNum'.
Definition at line 161 of file FeatureVector.cpp.
References featureData, and NumOfFeatures().
Referenced by KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
{
  if ((_featureNum < 0) || (_featureNum >= NumOfFeatures ()))
  {
    cerr << endl
         << endl
         << "*** ERROR *** FeatureVector::FeatureData(" << _featureNum << ") Index out of bounds, no
       value set." << endl
         << endl;
    return;
  }
  featureData[_featureNum] = _featureValue;
} /* FeatureData */
float FeatureVector::FeatureData (kkint32 featureNum) const
Returns
The value of 'featureNum'
Definition at line 145 of file FeatureVector.cpp.
References featureData, and NumOfFeatures().
Referenced by KKMLL::FeatureVectorList::CalcStatsForFeatureNum(), KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree(), KKMLL::FeatureVectorList::ReSyncSymbolicData(), KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::FeatureFileIOC45::SaveFile(), KKMLL::FeatureFileIOSparse::SaveFile(), and SVM289_MFS::Svm_Model::WriteXML().
{
  if ((featureNum < 0) || (featureNum >= NumOfFeatures ()))
  {
    cerr << endl
         << "*** ERROR *** FeatureVector::FeatureData(" << featureNum << ") Index out of bounds." <<
      endl
         << endl;
    return 0.0f;
  }
  return featureData[featureNum];
} /* FeatureData */
const float* KKMLL::FeatureVector::FeatureData () const [inline]
Returns as a pointer to the feature data itself.
Definition at line 128 of file FeatureVector.h.
References featureData.
Referenced by SVM289_MFS::Kernel::DotStatic(), SVM289_BFS::Kernel::DotStatic(), KKMLL::FeatureEncoder2::EncodeAExample(), KKMLL::FeatureEncoder::EncodeAExample(), SVM289_MFS::Kernel::k_function(), and SVM289_BFS::Kernel::k_function().
float* KKMLL::FeatureVector::FeatureDataAlter () [inline]
Same as 'FeatureData() except you can modify the data.
Definition at line 129 of file FeatureVector.h.
References featureData.
Referenced by KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector(), KKMLL::NormalizationParms::NormalizeAExample(), and KKMLL::NormalizationParms::ToNormalized().
const float* KKMLL::FeatureVector::FeatureDataConst () const [inline]
Definition at line 131 of file FeatureVector.h.
References featureData.
Referenced by KKMLL::ImageFeaturesNodeKey::CompareTwoExamples(), and KKMLL::FeatureVectorList::ExtractMeanFeatureValues().
{return featureData;}
bool FeatureVector::FeatureDataValid ()
Definition at line 234 of file FeatureVector.cpp.
References featureData, KKB::FloatMax, KKB::FloatMin, and numOfFeatures.
{
  kkint32 featureNum;
  for (featureNum = 0; featureNum < numOfFeatures; featureNum++)
  {
    if ((featureData[featureNum] == KKB::FloatMin) || (
      featureData[featureNum] == KKB::FloatMax))
      return false;
  }
  return true;
} /* FeatureDataValid */
kkint32 FeatureVector::MemoryConsumedEstimated () const [virtual]
Definition at line 81 of file FeatureVector.cpp.
References featureData, KKB::KKStr::MemoryConsumedEstimated(), and numOfFeatures.
Referenced by KKMLL::FeatureVectorList::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = sizeof (FeatureVector)
    + exampleFileName.MemoryConsumedEstimated ();
  if (featureData)
    memoryConsumedEstimated += sizeof (float) * numOfFeatures;
  
  return memoryConsumedEstimated;
} /* MemoryConsumedEstimated */
void KKMLL::FeatureVector::MissingData (bool _missingData) [inline]
True indicates that not all the feature data was present when this example was loaded from a data file.
Definition at line 76 of file FeatureVector.h.
Referenced by KKMLL::FeatureFileIOC45::LoadFile().
bool KKMLL::FeatureVector::MissingData () const [inline]
True indicates that one or more features were missing.
Definition at line 117 of file FeatureVector.h.
Referenced by KKMLL::FeatureVectorList::MissingData().
void KKMLL::FeatureVector::MLClass (MLClassPtr _mlClass) [inline]
Assign a class to this example.
Definition at line 74 of file FeatureVector.h.
Referenced by KKMLL::Classifier2::ClassifyAExample(), KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector(), KKMLL::FeatureEncoder::CreateEncodedFeatureVector(), KKMLL::FeatureEncoder2::EncodeAExample(), KKMLL::FeatureEncoder::EncodeAExample(), KKMLL::FeatureEncoder2::EncodedFeatureVectorList(), KKMLL::FeatureVectorList::ExtractExamplesForHierarchyLevel(), KKMLL::FeatureFileIO::FeatureDataReSink(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOColumn::LoadFile(), KKMLL::FeatureFileIOUCI::LoadFile(), and KKMLL::FeatureFileIOC45::LoadFile().
MLClassPtr KKMLL::FeatureVector::MLClass () const [inline]
Class that is example is assigned to.
Definition at line 114 of file FeatureVector.h.
Referenced by KKMLL::Classifier2::ClassifyAExample(), KKMLL::FeatureEncoder::CreateEncodedFeatureVector(), KKMLL::FeatureEncoder2::EncodeAExample(), KKMLL::FeatureEncoder::EncodeAExample(), KKMLL::FeatureEncoder2::EncodedFeatureVectorList(), KKMLL::FeatureEncoder::EncodeIntoSparseMatrix(), KKMLL::FeatureVectorList::ExtractExamplesForAGivenClass(), KKMLL::FeatureVectorList::ExtractExamplesForHierarchyLevel(), KKMLL::FeatureVectorList::ExtractListOfClasses(), KKMLL::FeatureFileIO::FeatureDataReSink(), KKMLL::FeatureVectorList::GetClassStatistics(), KKMLL::FeatureVectorList::ClassNameComparrison::operator()(), KKMLL::FeatureVectorList::ClassNameComparrisonReversed::operator()(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
const KKStr & FeatureVector::MLClassName () const
Name of class that this example is assigned to.
Definition at line 262 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), and KKMLL::MLClass::Name().
{
  if (mlClass)
    return mlClass->Name ();
  else
    return KKStr::EmptyStr ();
} /* MLClassName */
kkint32 KKMLL::FeatureVector::NumOfFeatures () const [inline]
Number of features in this FeatureVector.
Definition at line 118 of file FeatureVector.h.
References numOfFeatures.
Referenced by KKMLL::ImageFeaturesNodeKey::CompareTwoExamples(), FeatureData(), KKMLL::FeatureVectorList::PushOnBack(), KKMLL::FeatureVectorList::PushOnFront(), TotalOfFeatureData(), and SVM289_MFS::Svm_Model::WriteXML().
bool FeatureVector::operator== (FeatureVector & other_example) const
Definition at line 273 of file FeatureVector.cpp.
References featureData, and numOfFeatures.
{
  if (numOfFeatures != other_image.numOfFeatures)
    return false;
  for (kkint32 i = 0; i < numOfFeatures; i++)
  {
    if (featureData[i] != other_image.featureData[i])
    {
      return false;
    }
  }
  return true;
} /* operator== */
void KKMLL::FeatureVector::OrigSize (float _origSize) [inline]
The value of Feature[0] before normalization.
Definition at line 77 of file FeatureVector.h.
Referenced by KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
float KKMLL::FeatureVector::OrigSize () const [inline]
The value of Feature[0] before normalization.
Definition at line 119 of file FeatureVector.h.
Referenced by KKMLL::FeatureVectorList::ExtractExamplesForAGivenClass(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
void KKMLL::FeatureVector::PredictedClass (MLClassPtr _predictedClass) [inline]
Definition at line 78 of file FeatureVector.h.
Referenced by KKMLL::FeatureEncoder2::EncodeAExample(), and KKMLL::FeatureEncoder::EncodeAExample().
{predictedClass = _predictedClass;}
MLClassPtr KKMLL::FeatureVector::PredictedClass () const [inline]
Definition at line 120 of file FeatureVector.h.
Referenced by KKMLL::FeatureEncoder2::EncodeAExample(), and KKMLL::FeatureEncoder::EncodeAExample().
{return predictedClass;}
const KKStr & FeatureVector::PredictedClassName () const
Definition at line 251 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), and KKMLL::MLClass::Name().
{
  if (predictedClass)
    return predictedClass->Name ();
  else
    return KKStr::EmptyStr ();
} /* PredictedClasseName */
void KKMLL::FeatureVector::Probability (float _probability) [inline]
Assign a prediction probability to this example.
Definition at line 79 of file FeatureVector.h.
float KKMLL::FeatureVector::Probability () const [inline]
The probability assigned by classifier to the predicted class.
Definition at line 122 of file FeatureVector.h.
Referenced by KKMLL::FeatureVectorList::ProbabilityComparison::operator()(), and KKMLL::FeatureVectorList::ProbabilityComparisonReversed::operator()().
void FeatureVector::ResetNumOfFeatures (kkint32 newNumOfFeatures)
Used to reallocate memory for feature data.
Definition at line 102 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), featureData, KKB::KKException::KKException(), KKB::KKStr::KKStr(), and numOfFeatures.
Referenced by KKMLL::FeatureVectorList::ResetFileDesc(), and KKMLL::FeatureVectorList::ResetNumOfFeaturs().
{
  if (newNumOfFeatures < 1)
  {
    KKStr errMsg (128);
    errMsg << "FeatureVector::ResetNumOfFeatures ***ERROR*** NewNumOfFeatures[" << newNumOfFeatures <<
      "] is invalid.";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  kkint32 x;
  float* newFeatureData = new float[newNumOfFeatures];
  for (x = 0; x < newNumOfFeatures; x++)
  {
    if (x < numOfFeatures)
      newFeatureData[x] = featureData[x];
    else
      newFeatureData[x] = 0.0f;
  }
  delete featureData;
  featureData = newFeatureData;
  numOfFeatures = newNumOfFeatures;
} /* ResetNumOfFeatures */
float FeatureVector::TotalOfFeatureData () const
Returns the total of all Feature Attributes for this feature vector.
Definition at line 180 of file FeatureVector.cpp.
References featureData, and NumOfFeatures().
{
  float totalOfFeatureData = 0.0f;
  for (int x = 0; x < NumOfFeatures (); ++x)
    totalOfFeatureData += featureData[x];
  return totalOfFeatureData;
}
void KKMLL::FeatureVector::TrainWeight (float _trainWeight) [inline]
Assign a specific example a higher weight for training purposes.
The SVM will multiply the cost parameter by this amount when training the classifier for this specific example.
Definition at line 105 of file FeatureVector.h.
Referenced by KKMLL::FeatureEncoder2::EncodeAExample(), and KKMLL::FeatureEncoder::EncodeAExample().
{trainWeight = _trainWeight;}
float KKMLL::FeatureVector::TrainWeight () const [inline]
Definition at line 123 of file FeatureVector.h.
Referenced by KKMLL::FeatureEncoder2::EncodeAExample(), KKMLL::FeatureEncoder::EncodeAExample(), and KKMLL::FeatureEncoder::EncodeIntoSparseMatrix().
{return trainWeight;}
void KKMLL::FeatureVector::Validated (bool _validated) [inline]
Indicated whether an expert has validated the class assignment.
Definition at line 109 of file FeatureVector.h.
{validated = _validated;}
bool KKMLL::FeatureVector::Validated () const [inline]
Definition at line 124 of file FeatureVector.h.
{return validated;}
void KKMLL::FeatureVector::Version (kkint16 _version) [inline]
Definition at line 80 of file FeatureVector.h.
Referenced by KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
{version = _version;}
kkint16 KKMLL::FeatureVector::Version () const [inline]
Definition at line 125 of file FeatureVector.h.
Referenced by KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
{return version;}
Member Data Documentation
float* KKMLL::FeatureVector::featureData [protected]
Definition at line 150 of file FeatureVector.h.
Referenced by AddFeatureData(), AllocateFeatureDataArray(), FeatureData(), FeatureDataAlter(), FeatureDataConst(), FeatureDataValid(), FeatureVector(), MemoryConsumedEstimated(), operator==(), ResetNumOfFeatures(), TotalOfFeatureData(), and ~FeatureVector().
kkint32 KKMLL::FeatureVector::numOfFeatures [protected]
Definition at line 151 of file FeatureVector.h.
Referenced by AddFeatureData(), AllocateFeatureDataArray(), FeatureDataValid(), FeatureVector(), MemoryConsumedEstimated(), NumOfFeatures(), operator==(), and ResetNumOfFeatures().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVector.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVector.cpp