KKLSC::ScannerFile4BitEncoded Class Reference
Implements a 4 bit Encoded format.
#include <ScannerFile4BitEncoded.h>
Classes
union OpRec
struct OpRecEndOfScanLine
struct OpRecInstrumentDataWord1
struct OpRecInstrumentDataWord2
struct OpRecInstrumentDataWord3
struct OpRecRaw1Pixel
struct OpRecRaw32Pixels
struct OpRecRaw513Pixels1
struct OpRecRaw513Pixels2
struct OpRecRun256Len1
struct OpRecRun256Len2
struct OpRecRunLen
struct OpRecTextBlock1
struct OpRecTextBlock2
struct RawPixelRec
Public Types
typedef ScannerFile4BitEncoded * ScannerFile4BitEncodedPtr
Public Member Functions
ScannerFile4BitEncoded (const KKStr &_fileName, RunLog &_log)
ScannerFile4BitEncoded (const KKStr &_fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog &_log)
virtual ~ScannerFile4BitEncoded ()
virtual Format FileFormat () const
virtual void ScanRate (float _scanRate)
virtual void WriteTextBlock (const uchar *txtBlock, kkuint32 txtBlockLen)
Static Public Member Functions
static const uchar * CompensationTable ()
Protected Member Functions
kkuint32 ReadBufferFrame ()
Writes a 32 bit number into the Scanner File Stream at current location.
virtual kkint64 SkipToNextFrame ()
Skip to start of next frame returning back byte offset of that frame.
virtual void WriteBufferFrame ()
Write the contents of 'frameBuffer' to he end of the scanner file.
Additional Inherited Members
Detailed Description
Implements a 4 bit Encoded format.
This is a very simple implementation of run-length compression only background pixels (0) will be compressed by groups of 4. All pixels will be translated from 8 bit to 3 bit.
  1) Records are or varying length.
  2) Each record starts with a 4 bit Op-Code.
  3) Records contain either Text or Imagery
  4) Imagery records can be either Run-Length (Same Pixel repeating) or Raw-String(A sequence of pixels).
   Summary of Op-Codes:
   --------------------------------------------------------------------
   0: End-Of-Line: Indicates that end of Scan-Line reached.
   1: Text-Block:
   2: InsrumentData
   3: Unused
   4: Run-Length (2 Pixels).
   5: Run-Length (3 Pixels).
   6: Run-Length (4 Pixels).
   7: Run-Length (5 Pixels).
   8: Run-Length (6 Pixels).
   9: Run-Length (7 Pixels).
  10: Run-Length (1 thru 256 Pixels).
  11: Raw-String (1 Pixel Length).
  12: Raw-String (Even length 2 thru 32).
  13: Raw-String (Odd Length 1 thru 513).
  14: Unused.
  15: Unused.
  Bits
  =====
  0 - 3: OP-Code (Values 0 thru 15)
----------------------------------------------------------
  Op-Code = 0 end of line
  4 - 7: Ignore
----------------------------------------------------------
  Op-Code 1: Test Block.
  4 - 4: End of text block.
  5 - 7: TextBlock Len HighEnd.
  8 - 15: TextBlock Len LowEnd
    Text-Block-Len = HighEnd * 256 + LowEnd.
  Followed by 'Text-Block-Len' bytes.
----------------------------------------------------------
  Op-Code 2: InstrumentData
  4 - 7: InstrumentId
  8 - 39: Scan-Line Number.
 40 - 71: Instrument Data.
----------------------------------------------------------
  Op-Code = 4 thru 9: Short-Run-Len
                       RunLen = OpCode - 2
  4 - 7: Pixel Value being repeated.
----------------------------------------------------------
 Op-Code = 10: Run-length of range "1" thru "256"
                 Since there are no run-lengths of '0'; '0' will decode to Run-Length = 1;
  4 - 7: Pixel Value being repeated.
  8 - 15: Run-length 0=1, 1=2, 2=3,... 254=255, 255=256
----------------------------------------------------------
 Op-Code = 11: One Pixel Raw String.
  4 - 7: PixelValue.
----------------------------------------------------------
 Op-Code = 12 Raw Pixel String of even length ranging from 2 to 32
                because each byte can fit two pixels it is best that Raw String lengths
                always be multiples of 2.
  4 - 7: Len; Num-Raw-Pixels = (Len + 1) * 2
              Len 0=(2 raw Pixels), 1=(4 raw pixels), 2=(6 raw pixels),,, 15=(32 raw pixels)
              Number of following bytes = (Len + 1).
----------------------------------------------------------
 Op-Code = 13 Odd number of raw pixels up to length of 513 pixels.
               We use the other 4 bits in the 1st byte to represent the high order bits of the length
               and the 1st 4 bits in the second byte for the low order; that leaves room for one
               pixel in the second byte. This is why odd length stings are supported.
   8 - 7: LenHigh String Length = 1 + 2 * (LenHigh * 16 + LenLow);
   8 - 11: LenLow
  12 - 15: First Raw Pixel. Will be followed by ((LenHigh * 16 + LenLow) bytes with two pixels
                                in each one.
           Translation Tables
  ======================================
  4 8 4
  Bit Bit 8-Bit Range Bit
  === === ============ ===
  0 0 (0 - 15): 0
  1 17 (16 - 31): 1
  2 34 (32 - 47): 2
  3 51 (48 - 63): 3
  4 68 (64 - 79): 4
  5 85 (80 - 95): 5
  6 102 (96 - 111): 6
  7 119 (112 - 127): 7
  8 136 (128 - 143): 8
  9 153 (144 - 159): 9
  10 170 (160 - 175): 10
  11 187 (176 - 191): 11
  12 204 (192 - 207): 12
  13 221 (208 - 223): 13
  14 238 (224 - 239): 14
  15 255 (240 - 255): 15
Definition at line 129 of file ScannerFile4BitEncoded.h.
Member Typedef Documentation
typedef ScannerFile4BitEncoded* KKLSC::ScannerFile4BitEncoded::ScannerFile4BitEncodedPtr
Definition at line 132 of file ScannerFile4BitEncoded.h.
Constructor & Destructor Documentation
ScannerFile4BitEncoded::ScannerFile4BitEncoded (const KKStr & _fileName, RunLog & _log)
Definition at line 192 of file ScannerFile4BitEncoded.cpp.
References KKLSC::ScannerFile::ScannerFile().
                                                :
  ScannerFile (_fileName, _log),
  rawPixelRecBuffer (NULL),
  rawPixelRecBufferSize (0),
  rawPixelRecBufferLen (0),
  encodedBuff (NULL),
  encodedBuffLen (0),
  encodedBuffNext (NULL),
  encodedBuffSize (0),
  rawStr (NULL),
  rawStrLen (0),
  rawStrSize (0),
  runLen (0),
  runLenChar (0),
  curCompStatus (csNull)
{
  BuildConversionTables ();
  PrintSizeInfo ();
}
ScannerFile4BitEncoded::ScannerFile4BitEncoded (const KKStr & _fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog & _log)
Definition at line 219 of file ScannerFile4BitEncoded.cpp.
References KKLSC::ScannerFile::ScannerFile().
                                                :
  ScannerFile (_fileName, _pixelsPerScanLine, _frameHeight, _log),
  rawPixelRecBuffer (NULL),
  rawPixelRecBufferSize (0),
  rawPixelRecBufferLen (0),
  encodedBuff (NULL),
  encodedBuffLen (0),
  encodedBuffNext (NULL),
  encodedBuffSize (0),
  rawStr (NULL),
  rawStrLen (0),
  rawStrSize (0),
  runLen (0),
  runLenChar (0),
  curCompStatus (csNull)
{
  BuildConversionTables ();
  AllocateEncodedBuff ();
  AllocateRawStr (_pixelsPerScanLine + 100);
}
ScannerFile4BitEncoded::~ScannerFile4BitEncoded (void) [virtual]
Definition at line 282 of file ScannerFile4BitEncoded.cpp.
{
  if (opened)
    Close ();
  delete encodedBuff; encodedBuff = NULL;
  delete rawPixelRecBuffer; rawPixelRecBuffer = NULL;
  delete rawStr; rawStr = NULL;
}
Member Function Documentation
const uchar * ScannerFile4BitEncoded::CompensationTable () [static]
Definition at line 396 of file ScannerFile4BitEncoded.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKLSC::ScannerFile::ConpensationTable().
{
  GlobalGoalKeeper::StartBlock ();
  if (!compensationTable)
    BuildConversionTables ();
  GlobalGoalKeeper::EndBlock ();
  return compensationTable;
} /* CompensationTable */
virtual Format KKLSC::ScannerFile4BitEncoded::FileFormat () const [inline], [virtual]
Reimplemented from KKLSC::ScannerFile.
Definition at line 149 of file ScannerFile4BitEncoded.h.
References KKLSC::ScannerFile::sf4BitEncoded.
{return Format::sf4BitEncoded;}
kkuint32 ScannerFile4BitEncoded::ReadBufferFrame () [protected], [virtual]
Writes a 32 bit number into the Scanner File Stream at current location.
Parameters
in idNum nNumber that identifies Instrument data, ex: 0 is reserved for Flow Meter Count.
in dataWord 32 bit number being written.Read in one Scanner File Frame.
Implements KKLSC::ScannerFile.
Definition at line 433 of file ScannerFile4BitEncoded.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::frameBuffer, KKLSC::ScannerFile::frameBufferFileOffsetLast, KKLSC::ScannerFile::frameBufferFileOffsetNext, KKLSC::ScannerFile::frameBufferLen, KKLSC::ScannerFile::frameBufferNextLine, and KKB::osFTELL().
{
  frameBufferLen = 0;
  frameBufferNextLine = 0;
  if (feof (file) != 0)
  {
    memset (frameBuffer, 0, frameBufferSize);
    return 0;
  }
  frameBufferFileOffsetLast = osFTELL (file);
  kkuint32 numScanLinesReadThisFrameBuffer = 0;
  uchar* buffPtr = frameBuffer;
  while ((feof (file) == 0) && (numScanLinesReadThisFrameBuffer <
      frameHeight))
  {
    GetNextScanLine (buffPtr, pixelsPerScanLine);
    frameBufferLen += pixelsPerScanLine;
    buffPtr += pixelsPerScanLine;
    ++numScanLinesReadThisFrameBuffer;
  }
  frameBufferFileOffsetNext = osFTELL (file);
  frameBufferNextLine = 0;
  return numScanLinesReadThisFrameBuffer;
} /* ReadBufferFrame */
void ScannerFile4BitEncoded::ScanRate (float _scanRate) [virtual]
Reimplemented from KKLSC::ScannerFile.
Definition at line 421 of file ScannerFile4BitEncoded.cpp.
{
  ScannerFile::ScanRate (_scanRate);
}
kkint64 ScannerFile4BitEncoded::SkipToNextFrame () [protected], [virtual]
Skip to start of next frame returning back byte offset of that frame.
This will be called by the 'UpdateFrameOffset' and 'DetermineFrameOffsetForFrame' methods used to build the 'frameOffsets' table. It is important that the implementation of this method NOT update the frameBuffer fields; such as 'frameBuffer', 'frameBufferNextLine', etc .....
Implements KKLSC::ScannerFile.
Definition at line 461 of file ScannerFile4BitEncoded.cpp.
References KKLSC::ScannerFile::pixelsPerScanLine.
{
  uchar* scanLine = new uchar[pixelsPerScanLine];
  kkuint32 numScanLinesReadThisFrameBuffer = 0;
  while ((feof (file) == 0) && (numScanLinesReadThisFrameBuffer <
      frameHeight))
  {
    GetNextScanLine (scanLine, pixelsPerScanLine);
    ++numScanLinesReadThisFrameBuffer;
  }
  delete[] scanLine;
  scanLine = NULL;
  if (feof (file) != 0)
    return -1;
  else
    return osFTELL (file);
} /* SkipToNextFrame */
void ScannerFile4BitEncoded::WriteBufferFrame () [protected], [virtual]
Write the contents of 'frameBuffer' to he end of the scanner file.
Implements KKLSC::ScannerFile.
Definition at line 706 of file ScannerFile4BitEncoded.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::fileSizeInBytes, KKLSC::ScannerFile::frameBuffer, KKLSC::ScannerFile::frameBufferFileOffsetLast, KKLSC::ScannerFile::frameBufferFileOffsetNext, KKLSC::ScannerFile::frameBufferNextLine, KKB::osFTELL(), and KKLSC::ScannerFile::pixelsPerScanLine.
{
  frameBufferFileOffsetLast = osFTELL (file);
  //nextScanLineOffset = osFTELL (file);
  kkuint32 frameRow = 0;
  uchar* framePtr = frameBuffer;
  while (frameRow < frameBufferNextLine)
  {
    WriteNextScanLine (framePtr, pixelsPerScanLine);
    framePtr += pixelsPerScanLine;
    ++frameRow;
  }
  frameBufferFileOffsetNext = osFTELL (file);
  fileSizeInBytes = frameBufferFileOffsetNext;
} /* WriteBufferFrame*/
void ScannerFile4BitEncoded::WriteTextBlock (const uchar * txtBlock, kkuint32 txtBlockLen) [virtual]
Implements KKLSC::ScannerFile.
Definition at line 969 of file ScannerFile4BitEncoded.cpp.
References KKLSC::ScannerFile4BitEncoded::OpRecTextBlock1::endOfText, KKLSC::ScannerFile::file, KKLSC::ScannerFile::fileSizeInBytes, KKLSC::ScannerFile4BitEncoded::OpRecTextBlock1::lenHighBits, KKLSC::ScannerFile4BitEncoded::OpRecTextBlock2::lenLowBits, KKLSC::ScannerFile4BitEncoded::OpRecTextBlock1::opCode, KKB::osFTELL(), KKLSC::ScannerFile4BitEncoded::OpRec::textBlock1, and KKLSC::ScannerFile4BitEncoded::OpRec::textBlock2.
{
  if (txtBlockLen > (encodedBuffSize - 10))
  {
    kkuint32 newEncodedBuffSise = txtBlockLen + 10;
    ReSizeEncodedBuff (newEncodedBuffSise);
  }
  encodedBuffNext = encodedBuff;
  encodedBuffLen = 0;
  kkint32 charsLeft = txtBlockLen;
  const uchar* txtBlockPtr = txtBlock;
  while (charsLeft > 0)
  {
    kkint32 charsToWrite = Min (2048, charsLeft);
    OpRec rec;
    rec.textBlock1.opCode = 1;
    rec.textBlock1.endOfText = (charsToWrite < charsLeft) ? 0 : 1;
    rec.textBlock1.lenHighBits = charsToWrite / 256;
    *encodedBuffNext = rec;
    ++encodedBuffNext;
    encodedBuffNext->textBlock2.lenLowBits = charsToWrite % 256;
    ++encodedBuffNext;
    memcpy (encodedBuffNext, txtBlockPtr, charsToWrite);
    charsLeft -= charsToWrite;
    txtBlockPtr += charsToWrite;
    encodedBuffNext += charsToWrite;
  }
  fwrite (encodedBuff, sizeof (OpRec), encodedBuffLen, file);
  fileSizeInBytes = osFTELL (file);
} /* WriteTextBlock */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFile4BitEncoded.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFile4BitEncoded.cpp