SVM289_BFS::QMatrix Class Reference
Public Member Functions
virtual ~QMatrix ()
virtual Qfloat * get_Q (kkint32 column, kkint32 len) const =0
virtual Qfloat * get_QD () const =0
virtual void swap_index (kkint32 i, kkint32 j)=0
Detailed Description
Definition at line 835 of file svm289_BFS.cpp.
Constructor & Destructor Documentation
virtual SVM289_BFS::QMatrix::~QMatrix () [inline], [virtual]
Definition at line 841 of file svm289_BFS.cpp.
{}
Member Function Documentation
virtual Qfloat* SVM289_BFS::QMatrix::get_Q (kkint32 column, kkint32 len) const [pure virtual]
Implemented in SVM289_BFS::SVR_Q, SVM289_BFS::ONE_CLASS_Q, SVM289_BFS::SVC_Q, and SVM289_BFS::Kernel.
Referenced by SVM289_BFS::Solver::reconstruct_gradient(), SVM289_BFS::Solver::select_working_set(), and SVM289_BFS::Solver::Solve().
virtual Qfloat* SVM289_BFS::QMatrix::get_QD () const [pure virtual]
Implemented in SVM289_BFS::SVR_Q, SVM289_BFS::ONE_CLASS_Q, SVM289_BFS::SVC_Q, and SVM289_BFS::Kernel.
Referenced by SVM289_BFS::Solver::Solve().
virtual void SVM289_BFS::QMatrix::swap_index (kkint32 i, kkint32 j) [pure virtual]
Implemented in SVM289_BFS::SVR_Q, SVM289_BFS::ONE_CLASS_Q, SVM289_BFS::SVC_Q, and SVM289_BFS::Kernel.
Referenced by SVM289_BFS::Solver::swap_index().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm289_BFS.cpp