KKB::CmdLineExpander Class Reference
Expands command line parameters, by parsing for special parameters and expanding them to their full value.
#include <CmdLineExpander.h>
Public Member Functions
CmdLineExpander (const KKStr &_applicationName, RunLog &_log, kkint32 argc, char **argv)
Constructor using the parameters passed through on the command line into main().
CmdLineExpander (const KKStr &_applicationName, RunLog &_log, const KKStr &_cmdLine)
Pass in the command line as a single string. Will parse first before processing.
~CmdLineExpander ()
void ExpandCmdLine (kkint32 argc, char **argv)
const vector< KKStrPair > & ExpandedParameterPairs () const
const VectorKKStr & ExpandedParameters () const
const KKStr & LogFileName () const
bool ParmsGood () const
Detailed Description
Expands command line parameters, by parsing for special parameters and expanding them to their full value.
A couple of parameters are specifically searched for and processed. The `-log` and `-CmdFile` parameters. The `-log` parameter is provides the name of a file where logging messages are to be written to via the `RunLog` class. The `-CmdFile` parameter provides the name of a text file that contains more command-line parameters that are to be processed along with all other parameters; the text in this file will be inserted where the original -`CmdLine` parameter appeared.
Author
Kurt Kramer
Definition at line 31 of file CmdLineExpander.h.
Constructor & Destructor Documentation
CmdLineExpander::CmdLineExpander (const KKStr & _applicationName, RunLog & _log, kkint32 argc, char ** argv)
Constructor using the parameters passed through on the command line into main().
Definition at line 38 of file CmdLineExpander.cpp.
References ExpandCmdLine(), and KKB::KKStr::KKStr().
                                  :
  applicationName (_applicationName),
  log (_log)
{
  ExpandCmdLine (argc, argv);
}
CmdLineExpander::CmdLineExpander (const KKStr & _applicationName, RunLog & _log, const KKStr & _cmdLine)
Pass in the command line as a single string. Will parse first before processing.
Definition at line 54 of file CmdLineExpander.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::KKStr::ExtractQuotedStr(), KKB::KKStr::KKStr(), KKB::KKStr::TrimLeft(), and KKB::KKStr::TrimRight().
                                  :
  applicationName (_applicationName),
  log (_log)
{
  VectorKKStr initialParameters;
  KKStr cmdLine (_cmdLine);
  cmdLine.TrimLeft ();
  while (!cmdLine.Empty ())
  {
    KKStr nextField = cmdLine.ExtractQuotedStr ("\n\r\t ", false); // false = Do not
       decode escape characters
    nextField.TrimRight ();
    if (!nextField.Empty ())
      initialParameters.push_back (nextField);
    cmdLine.TrimLeft ();
  }
  BuildCmdLineParameters (initialParameters);
  BuildExpandedParameterPairs ();
}
CmdLineExpander::~CmdLineExpander ()
Definition at line 84 of file CmdLineExpander.cpp.
{
}
Member Function Documentation
void CmdLineExpander::ExpandCmdLine (kkint32 argc, char ** argv)
Definition at line 92 of file CmdLineExpander.cpp.
Referenced by CmdLineExpander().
{
  parmsGood = true;
  
  VectorKKStr initialParameters;
  {
    kkint32 y;
    for (y = 1; y < argc; y++)
      initialParameters.push_back (argv[y]);
  }
  BuildCmdLineParameters (initialParameters);
  BuildExpandedParameterPairs ();
  return;
} /* ExpandCmdLine */
const vector<KKStrPair>& KKB::CmdLineExpander::ExpandedParameterPairs () const [inline]
Definition at line 59 of file CmdLineExpander.h.
{return expandedParameterPairs;}
const VectorKKStr& KKB::CmdLineExpander::ExpandedParameters () const [inline]
Definition at line 58 of file CmdLineExpander.h.
{return expandedParameters;}
const KKStr& KKB::CmdLineExpander::LogFileName () const [inline]
Definition at line 60 of file CmdLineExpander.h.
{return logFileName;}
bool KKB::CmdLineExpander::ParmsGood () const [inline]
Definition at line 61 of file CmdLineExpander.h.
{return parmsGood;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/CmdLineExpander.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/CmdLineExpander.cpp