XmlFactoryModelOldSVM Class Reference
Public Member Functions
XmlFactoryModelOldSVM ()
virtual XmlElementModelOldSVM * ManufatureXmlElement (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
Static Public Member Functions
static XmlFactoryModelOldSVM * FactoryInstance ()
Static Public Attributes
static XmlFactoryModelOldSVM * factoryInstance = XmlFactoryModelOldSVM::FactoryInstance ()
Detailed Description
Definition at line 645 of file ModelOldSVM.cpp.
Constructor & Destructor Documentation
XmlFactoryModelOldSVM::XmlFactoryModelOldSVM () [inline]
Definition at line 648 of file ModelOldSVM.cpp.
References KKB::XmlFactory::XmlFactory().
Referenced by FactoryInstance().
: XmlFactory ("ModelOldSVM") {}
Member Function Documentation
static XmlFactoryModelOldSVM* XmlFactoryModelOldSVM::FactoryInstance () [inline], [static]
Definition at line 661 of file ModelOldSVM.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), factoryInstance, KKB::XmlFactory::RegisterFactory(), KKB::GlobalGoalKeeper::StartBlock(), and XmlFactoryModelOldSVM().
  {
    if (factoryInstance == NULL)
    {
      GlobalGoalKeeper::StartBlock ();
      if (!factoryInstance)
      {
        factoryInstance = new XmlFactoryModelOldSVM ();
        XmlFactory::RegisterFactory (factoryInstance);
      }
      GlobalGoalKeeper::EndBlock ();
     }
    return factoryInstance;
  }
virtual XmlElementModelOldSVM* XmlFactoryModelOldSVM::ManufatureXmlElement (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log) [inline], [virtual]
Implements KKB::XmlFactory.
Definition at line 650 of file ModelOldSVM.cpp.
  {
    return new XmlElementModelOldSVM(tag, s, cancelFlag, log);
  }
Member Data Documentation
XmlFactoryModelOldSVM * XmlFactoryModelOldSVM::factoryInstance = XmlFactoryModelOldSVM::FactoryInstance () [static]
Definition at line 659 of file ModelOldSVM.cpp.
Referenced by FactoryInstance().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelOldSVM.cpp