KKB::MorphOpMaskExclude Class Reference
#include <MorphOpMaskExclude.h>
Public Member Functions
MorphOpMaskExclude (MaskTypes _mask)
virtual ~MorphOpMaskExclude ()
kkint32 MemoryConsumedEstimated ()
virtual OperationType Operation () const
virtual RasterPtr PerformOperation (RasterConstPtr _image)
Additional Inherited Members
Detailed Description
Definition at line 35 of file MorphOpMaskExclude.h.
Constructor & Destructor Documentation
MorphOpMaskExclude::MorphOpMaskExclude (MaskTypes _mask)
Definition at line 22 of file MorphOpMaskExclude.cpp.
References KKB::MorphOp::MorphOp().
                                                       :
    MorphOp (),
    mask (_mask)
{
}
MorphOpMaskExclude::~MorphOpMaskExclude () [virtual]
Definition at line 30 of file MorphOpMaskExclude.cpp.
{
}
Member Function Documentation
kkint32 MorphOpMaskExclude::MemoryConsumedEstimated ()
Definition at line 36 of file MorphOpMaskExclude.cpp.
{
  kkint32 result = sizeof (*this);
  return result;
}
virtual OperationType KKB::MorphOpMaskExclude::Operation () const [inline], [virtual]
Implements KKB::MorphOp.
Definition at line 42 of file MorphOpMaskExclude.h.
References KKB::MorphOp::MaskExclude.
{return OperationType::MaskExclude;}
RasterPtr MorphOpMaskExclude::PerformOperation (RasterConstPtr _image) [virtual]
Definition at line 44 of file MorphOpMaskExclude.cpp.
References KKB::Raster::BlueArea(), KKB::Raster::Dilation(), KKB::Raster::GreenArea(), KKB::Raster::Opening(), KKB::Raster::Raster(), KKB::Raster::RedArea(), KKB::MorphOp::SetSrcRaster(), KKB::MorphOp::srcBlueArea, KKB::MorphOp::srcColor, KKB::MorphOp::srcGreenArea, KKB::MorphOp::srcHeight, KKB::MorphOp::srcRedArea, and KKB::MorphOp::srcWidth.
{
  SetSrcRaster (_image);
  kkint32 totalPixels = srcHeight * srcWidth;
  RasterPtr maskImage = new Raster (*_image);
  maskImage->Opening ((KKB::MaskTypes)mask);
  //maskImage->ConnectedComponent();
  maskImage->Dilation ((KKB::MaskTypes)mask);
  RasterPtr result = new Raster (srcHeight, srcWidth,
      srcColor);
  uchar const* srcImageRedPtr = srcRedArea;
  uchar const* srcImageGreenPtr = srcGreenArea;
  uchar const* srcImageBluePtr = srcBlueArea;
  uchar* resultRedPtr = result->RedArea ();
  uchar* resultGreenPtr = result->GreenArea ();
  uchar* resultBluePtr = result->BlueArea ();
  uchar* maskPtr = maskImage->GreenArea ();
  for (kkint32 x = 0; x < totalPixels; ++x)
  {
    if (*maskPtr == 0)
    {
      *resultGreenPtr = *srcImageGreenPtr;
      if (srcColor)
      {
        *resultRedPtr = *srcImageRedPtr;
        *resultBluePtr = *srcImageBluePtr;
      }
    }
    ++maskPtr;
    ++srcImageGreenPtr;
    ++resultGreenPtr;
    if (srcColor)
    {
      ++srcImageRedPtr;
      ++resultRedPtr;
      ++srcImageBluePtr;
      ++resultBluePtr;
    }
  }
  delete maskImage;
  maskImage = NULL;
  return result;
} /* PerformOperation */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpMaskExclude.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpMaskExclude.cpp