KKB::XmlFactory Class Reference
#include <XmlStream.h>
Public Member Functions
XmlFactory (const KKStr &_clasName)
virtual const KKStr & ClassName () const
virtual XmlElementPtr ManufatureXmlElement (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)=0
Static Public Member Functions
static XmlFactory * FactoryLookUp (const KKStr &className)
static void FinalCleanUp ()
static void RegisterFactory (XmlFactory *factory)
Static Public Attributes
static XmlFactoryManagerPtr globalXmlFactoryManager = NULL
Detailed Description
Definition at line 382 of file XmlStream.h.
Constructor & Destructor Documentation
XmlFactory::XmlFactory (const KKStr & _clasName)
Definition at line 931 of file XmlStream.cpp.
References KKB::KKStr::KKStr().
Referenced by XmlFactoryModelOldSVM::XmlFactoryModelOldSVM(), and XmlFactoryTrainingClass::XmlFactoryTrainingClass().
                                              :
   className (_clasName)
{
}
Member Function Documentation
virtual const KKStr& KKB::XmlFactory::ClassName () const [inline], [virtual]
Definition at line 387 of file XmlStream.h.
Referenced by KKB::XmlFactoryManager::RegisterFactory().
{return className;}
XmlFactory * XmlFactory::FactoryLookUp (const KKStr & className) [static]
summary>Register a instance of a Derives Factory class for the Global XmlFactoryManager.
param name = 'factory'> The instance that is being registered; factories will take ownership and the method 'XmlStream' will be responsible for deleting upon application shutdown.
Definition at line 879 of file XmlStream.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), KKB::XmlFactoryManager::FactoryLookUp(), globalXmlFactoryManager, KKB::GlobalGoalKeeper::StartBlock(), and KKB::XmlFactoryManager::XmlFactoryManager().
Referenced by KKB::XmlStream::GetNextToken().
{
  GlobalGoalKeeper::StartBlock ();
  if (globalXmlFactoryManager == NULL)
  {
    globalXmlFactoryManager = new XmlFactoryManager ("
      globalXmlFactoryManager");
    atexit (FinalCleanUp);
  }
  XmlFactory* factory = globalXmlFactoryManager->
      FactoryLookUp (className);
  GlobalGoalKeeper::EndBlock ();
  return factory;
} /* FactoryLookUp */
void XmlFactory::FinalCleanUp () [static]
Definition at line 921 of file XmlStream.cpp.
References globalXmlFactoryManager.
{
  if (globalXmlFactoryManager)
    delete globalXmlFactoryManager;
  globalXmlFactoryManager = NULL;
}
virtual XmlElementPtr KKB::XmlFactory::ManufatureXmlElement (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log) [pure virtual]
Implemented in XmlFactoryVectorFloat, XmlFactoryVectorInt32, XmlFactoryArrayFloat2D, XmlFactoryArrayFloat, XmlFactoryArrayDouble, XmlFactoryArrayInt32, XmlFactoryArrayUint16, XmlFactoryDouble, XmlFactoryFloat, XmlFactoryInt64, XmlFactoryInt32, XmlFactoryKKStrListIndexed, XmlFactoryKKStrList, XmlFactoryVectorKKStr, XmlFactoryKKStr, XmlFactoryArrayFloat2DVarying, XmlFactoryKeyValuePairs, XmlFactoryDateTime, XmlFactoryUnKnown, XmlFactoryBool, XmlFactoryBitString, XmlFactoryModelOldSVM, and XmlFactoryTrainingClass.
Referenced by KKB::XmlStream::GetNextToken().
void XmlFactory::RegisterFactory (XmlFactory * factory) [static]
Definition at line 897 of file XmlStream.cpp.
References KKB::KKStr::Concat(), KKB::GlobalGoalKeeper::EndBlock(), globalXmlFactoryManager, KKB::KKException::KKException(), KKB::XmlFactoryManager::RegisterFactory(), KKB::GlobalGoalKeeper::StartBlock(), and KKB::XmlFactoryManager::XmlFactoryManager().
Referenced by XmlFactoryTrainingClass::FactoryInstance(), and XmlFactoryModelOldSVM::FactoryInstance().
{
  if (!factory)
  {
    KKStr errMsg = "XmlStream::RegisterFactory ***ERROR*** (factory == NULL).";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  GlobalGoalKeeper::StartBlock ();
  if (!globalXmlFactoryManager)
  {
    globalXmlFactoryManager = new XmlFactoryManager ("
      globalXmlFactoryManager");
    atexit (FinalCleanUp);
  }
  globalXmlFactoryManager->RegisterFactory (factory);
  GlobalGoalKeeper::EndBlock ();
}
Member Data Documentation
XmlFactoryManagerPtr XmlFactory::globalXmlFactoryManager = NULL [static]
Definition at line 402 of file XmlStream.h.
Referenced by FactoryLookUp(), FinalCleanUp(), and RegisterFactory().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp