KKB::MorphOpBinarize Class Reference
#include <MorphOpBinarize.h>
Public Member Functions
MorphOpBinarize (kkuint16 _pixelValueMin, kkuint16 _pixelValueMax)
virtual ~MorphOpBinarize ()
kkint32 MemoryConsumedEstimated ()
virtual OperationType Operation () const
virtual RasterPtr PerformOperation (RasterConstPtr _image)
Additional Inherited Members
Detailed Description
Definition at line 24 of file MorphOpBinarize.h.
Constructor & Destructor Documentation
MorphOpBinarize::MorphOpBinarize (kkuint16 _pixelValueMin, kkuint16 _pixelValueMax)
Definition at line 22 of file MorphOpBinarize.cpp.
References KKB::MorphOp::MorphOp().
Referenced by KKB::Raster::BinarizeByThreshold().
                                  :
  MorphOp (),
  pixelValueMin (_pixelValueMin),
  pixelValueMax (_pixelValueMax)
{
}
MorphOpBinarize::~MorphOpBinarize () [virtual]
Definition at line 33 of file MorphOpBinarize.cpp.
{
}
Member Function Documentation
kkint32 MorphOpBinarize::MemoryConsumedEstimated ()
Definition at line 39 of file MorphOpBinarize.cpp.
{
  return sizeof (*this);
}
virtual OperationType KKB::MorphOpBinarize::Operation () const [inline], [virtual]
Implements KKB::MorphOp.
Definition at line 33 of file MorphOpBinarize.h.
References KKB::MorphOp::Binarize.
{return OperationType::Binarize;}
RasterPtr MorphOpBinarize::PerformOperation (RasterConstPtr _image) [virtual]
Definition at line 62 of file MorphOpBinarize.cpp.
References KKB::Raster::BackgroundPixelValue(), KKB::Raster::ForegroundPixelCount(), KKB::Raster::Green(), KKB::Raster::Height(), KKB::Raster::Raster(), KKB::MorphOp::SetSrcRaster(), KKB::MorphOp::srcGreen, KKB::MorphOp::srcHeight, KKB::MorphOp::srcRaster, KKB::MorphOp::srcWidth, and KKB::Raster::Width().
Referenced by KKB::Raster::BinarizeByThreshold().
{
  SetSrcRaster (_image);
  kkint32 r = 0;
  kkint32 c = 0;
  kkint32 binarizedForegroundPixelCount = 0;
  RasterPtr binarizedRaster = new Raster (srcRaster->Height (),
      srcRaster->Width ());
  uchar* srcRow = NULL;
  uchar** destGreen = binarizedRaster->Green ();
  uchar* destRow = NULL;
  uchar backgroundPixelValue = srcRaster->BackgroundPixelValue ();
  for (r = 0; r < srcHeight; r++)
  {
    destRow = destGreen[r];
    srcRow = srcGreen[r];
    for (c = 0; c < srcWidth; c++)
    {
      uchar srcCh = srcRow[c];
      if ((srcCh >= pixelValueMin) && (srcCh <= pixelValueMax))
      {
        destRow[c] = srcCh;
        ++binarizedForegroundPixelCount;
      }
      else
      {
        destRow[c] = backgroundPixelValue;
      }
    } /* for (c) */
  } /* for (r) */
  binarizedRaster->ForegroundPixelCount (binarizedForegroundPixelCount);
  return binarizedRaster;
} /* PerformOperation */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpBinarize.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpBinarize.cpp