KKB::XmlElementUnKnown Class Reference
XmlElement derived class that will be used when there is no Factory defined for the element.
#include <XmlStream.h>
Public Member Functions
XmlElementUnKnown (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
virtual ~XmlElementUnKnown ()
std::deque< XmlTokenPtr > * TakeOwnership ()
std::deque< XmlTokenPtr > * Value () const
Additional Inherited Members
Detailed Description
XmlElement derived class that will be used when there is no Factory defined for the element.
remarks>All sub-elements and content will be saved in value which will be a list of XmlEemenst and content.
Definition at line 471 of file XmlStream.h.
Constructor & Destructor Documentation
XmlElementUnKnown::XmlElementUnKnown (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log)
Definition at line 1051 of file XmlStream.cpp.
References KKB::XmlStream::GetNextToken(), KKB::XmlElement::XmlElement(), and XmlElementUnKnown().
Referenced by XmlElementUnKnown().
                                      :
    XmlElement (tag, s, log),
    value (new deque<XmlTokenPtr> ())
{
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t != NULL)
  {
    value->push_back (t);
    t = s.GetNextToken (cancelFlag, log);
  }
}
XmlElementUnKnown::~XmlElementUnKnown () [virtual]
Definition at line 1068 of file XmlStream.cpp.
{
  if (value)
  {
    for (auto idx: *value)
      delete idx;
    delete value;
    value = NULL;
  }
}
Member Function Documentation
deque< XmlTokenPtr > * XmlElementUnKnown::TakeOwnership ()
Definition at line 1080 of file XmlStream.cpp.
{
  deque<XmlTokenPtr>* v = value;
  value = NULL;
  return v;
}
std::deque<XmlTokenPtr>* KKB::XmlElementUnKnown::Value () const [inline]
Definition at line 482 of file XmlStream.h.
{return value;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp