KKB::KKObserver Class Reference
The base class to be used by Observer classes.
#include <KKObserver.h>
Public Types
typedef KKObserver * KKObserverPtr
Public Member Functions
KKObserver (const KKStr &_name)
virtual ~KKObserver ()
kkint32 MemoryConsumedEstimated ()
const KKStr & Name () const
virtual void Notify (KKObservablePtr obj)
Friends
class KKObservable
Detailed Description
The base class to be used by Observer classes.
And application would register instances of a Observer
Definition at line 25 of file KKObserver.h.
Member Typedef Documentation
typedef KKObserver* KKB::KKObserver::KKObserverPtr
Definition at line 28 of file KKObserver.h.
Constructor & Destructor Documentation
KKObserver::KKObserver (const KKStr & _name)
Definition at line 32 of file KKObserver.cpp.
References KKB::KKStr::KKStr().
                                          :
   name (_name)
{
}
KKObserver::~KKObserver () [virtual]
Definition at line 40 of file KKObserver.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), KKB::GlobalGoalKeeper::StartBlock(), and KKB::KKObservable::UnRegisterObserver().
{
  // Let KKObservable instances know that we are not observing them anymore.
  GlobalGoalKeeper::StartBlock ();
  for (observablesIdx = observables.begin (); observablesIdx != observables.end (); ++observablesIdx)
  {
    KKObservablePtr p = observablesIdx->first;
    p->UnRegisterObserver (this);
  }
  GlobalGoalKeeper::EndBlock ();
}
Member Function Documentation
kkint32 KKObserver::MemoryConsumedEstimated ()
Definition at line 55 of file KKObserver.cpp.
{
  return sizeof (*this);
}
const KKStr& KKB::KKObserver::Name () const [inline]
Definition at line 39 of file KKObserver.h.
{return name;}
void KKObserver::Notify (KKObservablePtr obj) [virtual]
Definition at line 85 of file KKObserver.cpp.
{
} /* Notify */
Friends And Related Function Documentation
friend class KKObservable [friend]
Definition at line 54 of file KKObserver.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKObserver.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKObserver.cpp