KKB::Row Class Reference
#include <Matrix.h>
Public Member Functions
Row ()
Row (kkint32 _numOfCols, double *_cells)
Row (const Row &_row)
~Row ()
double * Cols ()
void Define (kkint32 _numOfCols, double *_cells)
double & operator[] (kkint32 idx)
Detailed Description
Definition at line 183 of file Matrix.h.
Constructor & Destructor Documentation
Row::Row ()
Definition at line 26 of file Matrix.cpp.
          :
  cells (NULL),
  numOfCols (-1)
{
}
Row::Row (kkint32 _numOfCols, double * _cells)
Definition at line 34 of file Matrix.cpp.
References KKB::KKStr::Concat(), and KKB::KKException::KKException().
           :
  cells (_cells),
  numOfCols (_numOfCols)
{
  if (_numOfCols < 0)
  {
    KKStr msg;
    msg << "Row::Row **** ERROR **** Invalid Dimension[" << _numOfCols << "].";
    cerr << std::endl << msg << std::endl << std::endl;
    throw KKException (msg);
  }
}
Row::Row (const Row & _row)
Definition at line 51 of file Matrix.cpp.
                         :
  cells (_row.cells),
  numOfCols (_row.numOfCols)
{
}
Row::~Row ()
Definition at line 59 of file Matrix.cpp.
{
  cells = NULL;
}
Member Function Documentation
double* KKB::Row::Cols () [inline]
Definition at line 197 of file Matrix.h.
{return cells;}
void Row::Define (kkint32 _numOfCols, double * _cells)
Definition at line 66 of file Matrix.cpp.
{
  numOfCols = _numOfCols;
  cells = _cells;
}
double & Row::operator[] (kkint32 idx)
Definition at line 76 of file Matrix.cpp.
References KKB::osWaitForEnter().
Referenced by KKB::Raster::BuildGaussian2dKernel(), KKB::Matrix::CalcCoFactorMatrix(), KKB::Matrix::Covariance(), KKB::Raster::CreateGrayScaleKLT(), KKB::Raster::CreateGrayScaleKLTOnMaskedArea(), KKMLL::ClassificationBiasMatrix::PerformAdjustmnts(), and KKMLL::ClassificationBiasMatrix::PrintBiasMatrix().
{
  if ((idx < 0) || (idx >= numOfCols))
  {
    cerr << std::endl
         << "Row::operator[] **** ERROR ****, Index["
         << idx << "] out of range of [0-" << numOfCols << "]."
         << std::endl;
    osWaitForEnter ();
    exit (1);
  }
  return cells[idx];
} /* Row::operator[] */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Matrix.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Matrix.cpp