KKB::KKStrList Class Reference
#include <KKStr.h>
Classes
class StringComparison
Public Types
typedef KKStrList * KKStrListPtr
Public Member Functions
KKStrList ()
KKStrList (bool owner)
KKStrList (const char *s[])
void AddString (KKStrPtr str)
KKStrPtr BinarySearch (const KKStr &searchStr)
KKStrListPtr DuplicateListAndContents () const
kkint32 MemoryConsumedEstimated () const
void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
void Sort (bool _reversedOrder)
bool StringInList (KKStr &str)
void WriteXML (const KKStr &varName, std::ostream &o) const
Static Public Member Functions
static KKStrListPtr ParseDelimitedString (const KKStr &str, const char *delChars=`,\t\n\r`)
Additional Inherited Members
Detailed Description
Definition at line 770 of file KKStr.h.
Member Typedef Documentation
typedef KKStrList* KKB::KKStrList::KKStrListPtr
Definition at line 773 of file KKStr.h.
Constructor & Destructor Documentation
KKStrList::KKStrList ()
Definition at line 4478 of file KKStr.cpp.
References KKStrList().
Referenced by KKB::MsgQueue::GetAllMsgs(), and KKStrList().
                     :
  KKQueue<KKStr> (false),
  sorted (false)
{
}
KKStrList::KKStrList (bool owner)
summary> Creates a list from a array of NULL terminated strings; the last entry in the list has to be NULL. Example: const char* zed[] = {`This`, `is`, `a`, `test`, NULL}; KKStrList wordList (zed); /summary>
Definition at line 4485 of file KKStr.cpp.
References KKStrList().
Referenced by KKB::KKStrMatrix::AddRow(), KKB::ImageDirTree::Directories(), DuplicateListAndContents(), KKMLL::FeatureVectorList::ExtractDuplicatesByExampleFileName(), KKB::KKThread::GetMsgs(), KKB::Tokenizer::GetNextTokens(), KKB::XmlTokenizer::GetNextTokens(), KKStrList(), KKB::osGetListOfDirectories(), KKB::osGetListOfFiles(), KKB::osGetListOfImageFiles(), osParseSearchSpec(), KKB::osValidFileNameErrors(), and ParseDelimitedString().
                                 :
  KKQueue<KKStr> (owner),
  sorted (false)
{
}
KKStrList::KKStrList (const char * s[])
Definition at line 4493 of file KKStr.cpp.
References KKStrList().
Referenced by KKStrList().
                                     :
    KKQueue<KKStr> (true),
    sorted (false)
{
  if (s == NULL)
    return;
  int x = 0;
  while (s[x] != NULL)
  {
    PushOnBack (new KKStr (s[x]));
    ++x;
  }
}
Member Function Documentation
void KKStrList::AddString (KKStrPtr str)
Definition at line 4651 of file KKStr.cpp.
{
  PushOnBack (str);
  sorted = false;
}
KKStrPtr KKStrList::BinarySearch (const KKStr & searchStr)
Definition at line 4607 of file KKStr.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKB::KKStr::operator<(), and KKB::KKStr::operator>().
{
  if (!sorted)
  {
    KKStr errMsg = "KKStrList::BinarySearch **** ERROR **** KKStr List is Not Sorted";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  
  kkint32 low = 0;
  kkint32 high = QueueSize () - 1;
  kkint32 mid;
  KKStrPtr str = NULL;
  while (low <= high)
  {
    mid = (low + high) / 2;
    str = IdxToPtr (mid);
    if (*str < searchStr)
    {
      low = mid + 1;
    }
    else if (*str > searchStr)
    {
      high = mid - 1;
    }
    else
    {
      return str;
    }
  }
  return NULL;
} /* BinarySearch */
KKStrListPtr KKStrList::DuplicateListAndContents () const
Definition at line 4779 of file KKStr.cpp.
References KKStrList().
{
  KKStrListPtr newList = new KKStrList (true);
  KKStrList::const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
    newList->PushOnBack (new KKStr (*(*idx)));
  return newList;
} /* DuplicateListAndContents */
kkint32 KKStrList::MemoryConsumedEstimated () const
Definition at line 4511 of file KKStr.cpp.
{
  kkint32 memoryConsumedEstimated = sizeof (KKStrList);
  KKStrList::const_iterator idx;
  for (idx = this->begin (); idx != this->end (); ++idx)
    memoryConsumedEstimated += (*idx)->MemoryConsumedEstimated ();
  return memoryConsumedEstimated;
}
KKStrListPtr KKStrList::ParseDelimitedString (const KKStr & str, const char * delChars = `,\t\n\r`) [static]
Definition at line 4659 of file KKStr.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), KKStrList(), and KKB::KKStr::TrimRight().
{
  KKStrListPtr parms = new KKStrList (true);
# ifdef USE_SECURE_FUNCS
    char* workStr = _strdup (str.Str ());
# else
    char* workStr = strdup (str.Str ());
# endif
  char* nextChar = workStr;
  while (*nextChar)
  {
    // Skip Past Leading Blanks
    while ((*nextChar) && (*nextChar == ' '))
    {
      nextChar++;
    }
    if (*nextChar == 0)
      break;
    const char* startOfToken = nextChar;
    while ((*nextChar) && (strchr (delChars, *nextChar) == NULL))
    {
      nextChar++;
    }
    if (*nextChar != 0)
    {
      *nextChar = 0;
      nextChar++;
    }
    KKStrPtr token = new KKStr (startOfToken);
    token->TrimRight ();
    parms->PushOnBack (token);
  }
  delete [] workStr;
  return parms;
} /* ParseDelimitedString */
void KKStrList::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 4537 of file KKStr.cpp.
References KKB::XmlTag::AttributeValueInt32(), KKB::KKStr::Concat(), KKB::XmlContent::Content(), KKB::KKStrParser::GetNextToken(), KKB::XmlStream::GetNextToken(), KKB::KKStrParser::KKStrParser(), KKB::KKStrParser::MoreTokens(), KKB::XmlToken::tokContent, KKB::XmlToken::TokenType(), and KKB::KKStrParser::TrimWhiteSpace().
{
  kkuint32 count = (kkuint32)tag->AttributeValueInt32 ("Count");
  DeleteContents ();
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (t->TokenType () == XmlToken::TokenTypes::tokContent)
    {
      XmlContentPtr c = dynamic_cast<XmlContentPtr>(t);
      if ((c != NULL) && (c->Content () != NULL))
      {
        KKStrParser parser (*(c->Content ()));
        parser.TrimWhiteSpace (" ");
        while (parser.MoreTokens ())
        {
          KKStr field = parser.GetNextToken ("\t");
          PushOnBack (new KKStr (field));
        }
      }
    }
    delete t;
    if (cancelFlag)
      t = NULL;
    else
      t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
} /* ReadXML */
void KKStrList::Sort (bool _reversedOrder)
Definition at line 4770 of file KKStr.cpp.
References KKB::KKStrList::StringComparison::StringComparison().
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink().
{
  StringComparison stringComparison (_reversedOrder);
  sort (begin (), end (), stringComparison);
  if (!_reversedOrder)
    sorted = true;
}
bool KKStrList::StringInList (KKStr & str)
Definition at line 4522 of file KKStr.cpp.
{
  bool found = false;
  kkint32 idx;
  kkint32 qSize = QueueSize ();
  for (idx = 0; ((idx < qSize) && (!found)); idx++)
    found = (str == (*IdxToPtr (idx)));
  return found;
}
void KKStrList::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 4577 of file KKStr.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::operator<<(), KKB::KKStr::QuotedStr(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), KKB::XmlContent::WriteXml(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("KKStrList", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.AddAtribute ("Count", (kkint32)size ());
  startTag.WriteXML (o);
  const_iterator idx;
  kkuint32 x = 0;
  for (idx = begin (); idx != end (); ++idx, ++x)
  {
    KKStrPtr sp = *idx;
    if (x > 0) o << "\t";
    XmlContent::WriteXml (sp->QuotedStr (), o);
  }
  XmlTag endTag ("KKStrList", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStr.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStr.cpp