KKB::MsgQueue Class Reference
Will manage a buffer that will allow multiple threads to add and remove messages to a queue.
#include <MsgQueue.h>
Public Types
typedef MsgQueue * MsgQueuePtr
Public Member Functions
MsgQueue (const KKStr &_name)
~MsgQueue ()
void AddMsg (KKStrPtr msg)
Take ownership of 'msg' and add to end of the queue.
void AddMsg (const KKStr &msg)
void AddMsgs (const KKStrListPtr msgs, bool takeOwnership)
Adds the contents of 'msgs' to the message queue and depending on 'takeOwnership' will either assume that its owns (taking ownership) the KKStr instances or create duplicates.
KKStrListPtr GetAllMsgs ()
Returns all messages that are currently in the queue.
KKStrPtr GetCopyOfLastMsg ()
Returns a duplicate of the last string added to the message queue.
KKStrPtr GetNextMsg ()
Removes from the queue the oldest message added to the queue that has not been removed.
kkint32 MemoryConsumedEstimated ()
Returns an estimate of the amount of memory consumed in bytes by this instance.
Detailed Description
Will manage a buffer that will allow multiple threads to add and remove messages to a queue.
A 'GoalKeepeer' object 'gateKeeper' will be used to enforce integrity in the Multi-Threaded environment. It will guarantee that only one thread at a time can access the Queue.
Definition at line 19 of file MsgQueue.h.
Member Typedef Documentation
typedef MsgQueue* KKB::MsgQueue::MsgQueuePtr
Definition at line 22 of file MsgQueue.h.
Constructor & Destructor Documentation
MsgQueue::MsgQueue (const KKStr & _name)
Definition at line 29 of file MsgQueue.cpp.
References KKB::GoalKeeperSimple::Create(), KKB::KKStr::KKStr(), KKB::GoalKeeperSimple::MemoryConsumedEstimated(), MsgQueue(), and KKB::operator+().
Referenced by MsgQueue().
                                      : /* Name of buffer, must be unique */
    gateKeeper (NULL),
    memoryConsumed (0),
    name (_name),
    queue ()
{
  GoalKeeperSimple::Create ("MsgQueue_" + name, gateKeeper);
  memoryConsumed = sizeof (MsgQueue) + gateKeeper->
      MemoryConsumedEstimated ();
}
MsgQueue::~MsgQueue ()
Definition at line 41 of file MsgQueue.cpp.
References KKB::GoalKeeperSimple::Destroy().
{
  while (this->queue.size () > 0)
  {
    KKStrPtr m = this->queue.front ();
    this->queue.pop ();
    delete m;
    m = NULL;
  }
  GoalKeeperSimple::Destroy (gateKeeper);
  gateKeeper = NULL;
}
Member Function Documentation
void MsgQueue::AddMsg (KKStrPtr msg)
Take ownership of 'msg' and add to end of the queue.
Parameters
in msg Pointer to message that is to be added to end of queue. The caller will pass ownership of this string to this instance of MsgQueue.Taking ownership of 'msg'
Definition at line 58 of file MsgQueue.cpp.
References KKB::KKStr::Concat(), KKB::GoalKeeperSimple::EndBlock(), KKB::KKException::KKException(), KKB::KKStr::MemoryConsumedEstimated(), and KKB::GoalKeeperSimple::StartBlock().
Referenced by KKB::KKThread::AddMsg().
{
  if (msg == NULL)
  {
    KKStr errMsg;
    errMsg << "MsgQueue::AddMsg == NULL";
    cerr << std::endl << std::endl << errMsg << std::endl <<
      std::endl;
    throw KKException (errMsg);
  }
  gateKeeper->StartBlock ();
  queue.push (msg);
  memoryConsumed = memoryConsumed + msg->MemoryConsumedEstimated ();
  gateKeeper->EndBlock ();
} /* AddFrame */
void MsgQueue::AddMsg (const KKStr & msg)
Definition at line 76 of file MsgQueue.cpp.
References KKB::GoalKeeperSimple::EndBlock(), KKB::KKStr::MemoryConsumedEstimated(), and KKB::GoalKeeperSimple::StartBlock().
Referenced by KKB::KKThread::AddMsg(), and KKB::RunLog::WriteLine().
{
  gateKeeper->StartBlock ();
  queue.push (new KKStr (msg));
  memoryConsumed = memoryConsumed + msg.MemoryConsumedEstimated ();
  gateKeeper->EndBlock ();
} /* AddFrame */
void MsgQueue::AddMsgs (const KKStrListPtr msgs, bool takeOwnership)
Adds the contents of 'msgs' to the message queue and depending on 'takeOwnership' will either assume that its owns (taking ownership) the KKStr instances or create duplicates.
If 'takeOwnership' is true will and the KKStr instances in 'msgs' to the queue otherwise it will make duplicates of the KKStr instances. It is up to the caller to make sure that they set the Owner flag on the 'msgs' instance; for example if 'takeOwnership' is 'true' then caller should set 'msgs.Owner (false);'.
Definition at line 86 of file MsgQueue.cpp.
References KKB::GoalKeeperSimple::EndBlock(), KKB::KKStr::MemoryConsumedEstimated(), and KKB::GoalKeeperSimple::StartBlock().
{
  gateKeeper->StartBlock ();
  KKStrList::iterator idx;
  for (idx = msgs->begin (); idx != msgs->end (); ++idx)
  {
    KKStrPtr msg = *idx;
    if (takeOwnership)
      queue.push (msg);
    else
      queue.push (new KKStr (*msg));
    memoryConsumed = memoryConsumed + msg->MemoryConsumedEstimated ();
  }
  gateKeeper->EndBlock ();
}
KKStrListPtr MsgQueue::GetAllMsgs ()
Returns all messages that are currently in the queue.
Definition at line 125 of file MsgQueue.cpp.
References KKB::GoalKeeperSimple::EndBlock(), KKB::KKStrList::KKStrList(), and KKB::GoalKeeperSimple::StartBlock().
{
  KKStrListPtr result = new KKStrList ();
  gateKeeper->StartBlock ();
  KKStrPtr msg = NULL;
  while (queue.size () > 0)
  {
    msg = queue.front ();
    queue.pop ();
    result->PushOnBack (msg);
    memoryConsumed = memoryConsumed - msg->MemoryConsumedEstimated ();
  }
  gateKeeper->EndBlock ();
  return result;
} /* GetAllMsgs */
KKStrPtr MsgQueue::GetCopyOfLastMsg ()
Returns a duplicate of the last string added to the message queue.
This will not effect the current copy of the message queue. The returned string will be owned by the caller who will be responsible for deleting it.
Definition at line 157 of file MsgQueue.cpp.
References KKB::GoalKeeperSimple::EndBlock(), and KKB::GoalKeeperSimple::StartBlock().
{
  KKStrPtr msg = NULL;
  gateKeeper->StartBlock ();
  if (queue.size () > 0)
  {
    msg = new KKStr (*(queue.back ()));
  }
  gateKeeper->EndBlock ();
  return msg;
}
KKStrPtr MsgQueue::GetNextMsg ()
Removes from the queue the oldest message added to the queue that has not been removed.
The caller will get ownership of the string and be responsible for deleting it.
Definition at line 107 of file MsgQueue.cpp.
References KKB::GoalKeeperSimple::EndBlock(), and KKB::GoalKeeperSimple::StartBlock().
Referenced by KKB::KKThread::GetMsgs().
{
  gateKeeper->StartBlock ();
  KKStrPtr msg = NULL;
  if (queue.size () > 0)
  {
    msg = queue.front ();
    queue.pop ();
    memoryConsumed = memoryConsumed - msg->MemoryConsumedEstimated ();
  }
  gateKeeper->EndBlock ();
  return msg;
} /* GetNextMsg */
kkint32 MsgQueue::MemoryConsumedEstimated ()
Returns an estimate of the amount of memory consumed in bytes by this instance.
This will help managed objects keep track of how much memory they are using in the unmanaged world.
Definition at line 146 of file MsgQueue.cpp.
References KKB::GoalKeeperSimple::EndBlock(), and KKB::GoalKeeperSimple::StartBlock().
Referenced by KKB::KKThread::MemoryConsumedEstimated().
{
  kkint32 result = 0;
  gateKeeper->StartBlock ();
  result = memoryConsumed;
  gateKeeper->EndBlock ();
  return result;
} /* MemoryConsumedEstimated */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MsgQueue.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MsgQueue.cpp