KKMLL::XmlElementMLClass Class Reference
#include <MLClass.h>
Public Member Functions
XmlElementMLClass (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
virtual ~XmlElementMLClass ()
MLClassPtr TakeOwnership ()
MLClassPtr Value () const
Static Public Member Functions
static void WriteXML (const MLClass &mlClass, const KKStr &varName, std::ostream &o)
Additional Inherited Members
Detailed Description
Because a MLClass instance can only be created through the static method `MLClass::CreateNewMLClass` the `XmlElementTemplate` template can not be used.
Definition at line 549 of file MLClass.h.
Constructor & Destructor Documentation
XmlElementMLClass::XmlElementMLClass (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log)
Definition at line 481 of file MLClass.cpp.
References KKB::XmlTag::AttributeCount(), KKB::XmlTag::AttributeNameByIndex(), KKB::XmlTag::AttributeValueByIndex(), KKB::XmlTag::AttributeValueByName(), KKMLL::MLClass::CountFactor(), KKMLL::MLClass::CreateNewMLClass(), KKMLL::MLClass::Description(), KKB::KKStr::Empty(), KKB::KKStr::EqualIgnoreCase(), KKB::XmlStream::GetNextToken(), KKMLL::MLClass::Mandatory(), KKMLL::MLClass::Parent(), KKMLL::MLClass::StoredOnDataBase(), KKMLL::MLClass::Summarize(), KKB::KKStr::ToBool(), KKB::KKStr::ToFloat(), and KKB::XmlElement::XmlElement().
                                      :
  XmlElement (tag, s, log),
  value (NULL)
{
  KKStrConstPtr className = tag->AttributeValueByName ("Name");
  if (!className)
  {
    // We are missing a mandatory field.
    value = NULL;
    return;
  }
  value = MLClass::CreateNewMLClass (*className);
  kkint32 c = tag->AttributeCount ();
  for (kkint32 x = 0; x < c; ++x)
  {
    KKStrConstPtr n = tag->AttributeNameByIndex (x);
    KKStrConstPtr v = tag->AttributeValueByIndex (x);
    if (v != NULL)
    {
      if ((n->EqualIgnoreCase ("Parent")) && (!v->Empty ()))
        value->Parent (MLClass::CreateNewMLClass (*v));
      else if (n->EqualIgnoreCase ("CountFactor"))
        value->CountFactor (v->ToFloat ());
      else if (n->EqualIgnoreCase ("Description"))
        value->Description (*v);
      else if (n->EqualIgnoreCase ("Mandatory"))
        value->Mandatory (v->ToBool ());
      else if (n->EqualIgnoreCase ("StoredOnDataBase"))
        value->StoredOnDataBase (v->ToBool ());
      else if (n->EqualIgnoreCase ("Summarize"))
        value->Summarize (v->ToBool ());
    }
  }
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
    t = s.GetNextToken (cancelFlag, log);
}
XmlElementMLClass::~XmlElementMLClass () [virtual]
Definition at line 534 of file MLClass.cpp.
{
  value = NULL;
}
Member Function Documentation
MLClassPtr KKMLL::XmlElementMLClass::TakeOwnership ()
MLClassPtr XmlElementMLClass::Value () const
Definition at line 540 of file MLClass.cpp.
Referenced by KKMLL::ModelParamDual::ReadXML().
{
  return value;
}
void XmlElementMLClass::WriteXML (const MLClass & mlClass, const KKStr & varName, std::ostream & o) [static]
Definition at line 547 of file MLClass.cpp.
References KKMLL::MLClass::WriteXML().
{
  mlClass.WriteXML (varName, o);
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.cpp