SVM289_MFS::SVC_Q Class Reference
Public Member Functions
SVC_Q (const svm_problem &prob, const svm_parameter &param, const schar *y_, RunLog &_log)
~SVC_Q ()
Qfloat * get_Q (kkint32 i, kkint32 len) const
Qfloat * get_QD () const
void swap_index (kkint32 i, kkint32 j)
Additional Inherited Members
Detailed Description
Definition at line 2157 of file svm2.cpp.
Constructor & Destructor Documentation
SVM289_MFS::SVC_Q::SVC_Q (const svm_problem & prob, const svm_parameter & param, const schar * y_, RunLog & _log) [inline]
Definition at line 2160 of file svm2.cpp.
References SVM289_MFS::Cache::Cache(), SVM289_MFS::svm_parameter::cache_size, SVM289_MFS::Kernel::kernel_function, SVM289_MFS::svm_problem::numTrainExamples, and SVC_Q().
Referenced by SVM289_MFS::solve_c_svc(), SVM289_MFS::solve_nu_svc(), and SVC_Q().
         :
  Kernel (prob.x, prob.selFeatures, param, _log)
  {
    clone (y, y_, prob.numTrainExamples);
    cache = new Cache (prob.numTrainExamples,
                       (kkint32)(param.cache_size * (1 << 20))
                      );
    QD = new Qfloat[prob.numTrainExamples];
    for (kkint32 i = 0; i < prob.numTrainExamples; ++i)
      QD[i] = (Qfloat)(this->*kernel_function)(i, i);
  }
SVM289_MFS::SVC_Q::~SVC_Q () [inline]
Definition at line 2209 of file svm2.cpp.
  {
    delete[] y;
    delete cache;
    delete[] QD;
  }
Member Function Documentation
Qfloat* SVM289_MFS::SVC_Q::get_Q (kkint32 i, kkint32 len) const [inline], [virtual]
Implements SVM289_MFS::Kernel.
Definition at line 2180 of file svm2.cpp.
References SVM289_MFS::Cache::get_data(), and SVM289_MFS::Kernel::kernel_function.
  {
    Qfloat *data;
    kkint32 start, j;
    if ((start = cache->get_data(i,&data,len)) < len)
    {
      for (j = start; j < len; j++)
        data[j] = (Qfloat)(y[i] * y[j] * (this->*kernel_function)(i, j));
    }
    return data;
  }
Qfloat* SVM289_MFS::SVC_Q::get_QD () const [inline], [virtual]
Implements SVM289_MFS::Kernel.
Definition at line 2193 of file svm2.cpp.
  {
    return QD;
  }
void SVM289_MFS::SVC_Q::swap_index (kkint32 i, kkint32 j) [inline], [virtual]
Reimplemented from SVM289_MFS::Kernel.
Definition at line 2200 of file svm2.cpp.
References SVM289_MFS::Cache::swap_index(), and SVM289_MFS::Kernel::swap_index().
  {
    cache->swap_index(i,j);
    Kernel::swap_index(i,j);
    SVM289_MFS::swap (y[i],y[j]);
    SVM289_MFS::swap (QD[i],QD[j]);
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm2.cpp