KKMLL::FeatureVectorList::RootNameComparrisonReversed Class Reference
Public Member Functions
RootNameComparrisonReversed ()
bool operator() (FeatureVectorPtr p1, FeatureVectorPtr p2)
Detailed Description
Definition at line 1981 of file FeatureVector.cpp.
Constructor & Destructor Documentation
KKMLL::FeatureVectorList::RootNameComparrisonReversed::RootNameComparrisonReversed () [inline]
Definition at line 1984 of file FeatureVector.cpp.
{}
Member Function Documentation
bool KKMLL::FeatureVectorList::RootNameComparrisonReversed::operator() (FeatureVectorPtr p1, FeatureVectorPtr p2) [inline]
Definition at line 1986 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), KKMLL::FeatureVector::ExampleFileName(), KKB::KKStr::operator>(), and KKB::osGetRootName().
  {
    KKStr root1 = osGetRootName (p1->ExampleFileName ());
    KKStr root2 = osGetRootName (p2->ExampleFileName ());
    return root1 > root2;
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVector.cpp