KKMLL::MLClassIndexList Class Reference
Maintains a list of classes and their associated integer index.
#include <MLClass.h>
Public Types
typedef MLClassIndexList * MLClassIndexListPtr
Public Member Functions
MLClassIndexList ()
MLClassIndexList (const MLClassIndexList &_list)
MLClassIndexList (const MLClassList &_classes)
virtual ~MLClassIndexList ()
void AddClass (MLClassPtr _ic, bool &_dupEntry)
void AddClassIndexAssignment (MLClassPtr _ic, kkint16 _classIndex, bool &_dupEntry)
virtual void Clear ()
kkint16 GetClassIndex (MLClassPtr c)
Returns the corresponding index to the class 'c'; if not in list will return -1.
MLClassPtr GetMLClass (kkint16 classIndex)
Locates the MLClass that was assigned classIndex.
kkint32 MemoryConsumedEstimated () const
void ParseClassIndexList (const KKStr &s, RunLog &log)
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
KKStr ToCommaDelString () const
Returns string consisting of all contained classes indicating ClassIndex assigned to each class.
virtual void WriteXML (const KKStr &varName, std::ostream &o) const
Detailed Description
Maintains a list of classes and their associated integer index.
Multiple Classes can have the same index but a class may only appear once in the list. The primary purpose of this class is to allow the quick access to classes by numerical indexes. This comes in useful when communicating with another library that does not recognize alpha numeric strings for class names such libSVM which only uses integers class names.
See also
KKMLL::Model
KKMLL::FeatureEncoder2::compress
Definition at line 459 of file MLClass.h.
Member Typedef Documentation
typedef MLClassIndexList* KKMLL::MLClassIndexList::MLClassIndexListPtr
Definition at line 462 of file MLClass.h.
Constructor & Destructor Documentation
KKMLL::MLClassIndexList::MLClassIndexList ()
MLClassIndexList::MLClassIndexList (const MLClassIndexList & _list)
Definition at line 1532 of file MLClass.cpp.
Referenced by KKMLL::Model::Model().
{
  const_iterator idx;
  bool dupEntry = false;
  for (idx = _list.begin (); idx != _list.end (); idx++)
  {
    AddClassIndexAssignment (idx->first, idx->second, dupEntry);
  }
}
MLClassIndexList::MLClassIndexList (const MLClassList & _classes)
Definition at line 1544 of file MLClass.cpp.
Referenced by KKMLL::FeatureVectorList::FeatureVectorList(), and KKMLL::Model::TrainModel().
                                                              :
    largestIndex(-1)
{
  MLClassList::const_iterator idx;
  for (idx = classes.begin (); idx != classes.end (); idx++)
  {
    largestIndex++;
    insert (pair<MLClassPtr, kkint16> (*idx, largestIndex));
    shortIdx.insert (pair<kkint16, MLClassPtr> (largestIndex, *idx));
  }
}
virtual KKMLL::MLClassIndexList::~MLClassIndexList () [inline], [virtual]
Definition at line 468 of file MLClass.h.
{}
Member Function Documentation
void MLClassIndexList::AddClass (MLClassPtr _ic, bool & _dupEntry)
Definition at line 1576 of file MLClass.cpp.
{
  _dupEntry = false;
  map<MLClassPtr, kkint16>::iterator p;
  p = find (_ic);
  if (p != end ())
  {
    _dupEntry = true;
    return;
  }
  kkint32 index = largestIndex + 1;
  largestIndex = index;
  insert (pair<MLClassPtr, kkint16> (_ic, index));
  shortIdx.insert (pair<kkint16, MLClassPtr> (index, _ic));
} /* AddClass */
void MLClassIndexList::AddClassIndexAssignment (MLClassPtr _ic, kkint16 _classIndex, bool & _dupEntry)
Definition at line 1598 of file MLClass.cpp.
Referenced by ParseClassIndexList().
{
  _dupEntry = false;
  map<MLClassPtr, kkint16>::iterator p;
  p = find (_ic);
  if (p != end ())
  {
    _dupEntry = true;
    return;
  }
  insert (pair<MLClassPtr, kkint16> (_ic, _classIndex));
  shortIdx.insert (pair<kkint16, MLClassPtr> (_classIndex, _ic));
  if (_classIndex > largestIndex)
    largestIndex = _classIndex;
} /* AddClassIndexAssignment */
void MLClassIndexList::Clear () [virtual]
Definition at line 1558 of file MLClass.cpp.
Referenced by ParseClassIndexList().
{
  clear ();
  shortIdx.clear ();
  largestIndex = 0;
}
kkint16 MLClassIndexList::GetClassIndex (MLClassPtr c)
Returns the corresponding index to the class 'c'; if not in list will return -1.
Definition at line 1621 of file MLClass.cpp.
Referenced by KKMLL::ModelSvmBase::Predict(), KKMLL::ModelSvmBase::ProbabilitiesByClass(), and KKMLL::ModelSvmBase::RetrieveCrossProbTable().
{
  kkint32 index = -1;
  map<MLClassPtr, kkint16>::iterator p;
  p = find (c);
  if (p == end ())
    index = -1;
  else
    index = p->second;
  return index;
} /* GetClassIndex */
MLClassPtr MLClassIndexList::GetMLClass (kkint16 classIndex)
Locates the MLClass that was assigned classIndex.
If not found then returns NULL. If more than one class has the same classIndex will return the first one added.
Definition at line 1636 of file MLClass.cpp.
Referenced by KKMLL::ModelSvmBase::Predict(), KKMLL::ModelKnn::ProbabilitiesByClass(), and KKMLL::ModelSvmBase::ProbabilitiesByClass().
{
  map<kkint16, MLClassPtr>::iterator p;
  p = shortIdx.find (classIndex);
  if (p == shortIdx.end ())
    return NULL;
  else
    return p->second;
} /* GetMLClass */
kkint32 MLClassIndexList::MemoryConsumedEstimated () const
Definition at line 1569 of file MLClass.cpp.
Referenced by KKMLL::Model::MemoryConsumedEstimated().
{
  return sizeof (MLClassIndexList) + (shortIdx.size () * (sizeof (
      kkint16) + sizeof (MLClassPtr) + 10)); // added 10- bytes per entry for overhead.
}
void MLClassIndexList::ParseClassIndexList (const KKStr & s, RunLog & log)
Definition at line 1649 of file MLClass.cpp.
References AddClassIndexAssignment(), Clear(), KKB::KKStr::Concat(), KKMLL::MLClass::CreateNewMLClass(), KKB::KKStrParser::GetNextToken(), KKB::KKStrParser::KKStrParser(), KKB::KKStrParser::LastDelimiter(), KKB::KKStrParser::MoreTokens(), KKB::KKStr::ToInt16(), and KKB::KKStrParser::TrimWhiteSpace().
Referenced by ReadXML().
{
  Clear ();
  largestIndex = -1;
  KKStrParser parser (s);
  parser.TrimWhiteSpace (" ");
  while (parser.MoreTokens ())
  {
    kkint32 classIndex = -1;
    KKStr className = parser.GetNextToken (",:");
    if (parser.LastDelimiter () == ',')
    {
      // we should have encountered a ':' character but came across a ',' instead; we are missing the
       Index Assignment
      classIndex = -1;
      log.Level (-1) << endl
        << "MLClassIndexList::ParseClassIndexList ***ERROR*** Missing index for Class: " << className <
      < endl
        << endl;
    }
    else
    {
      classIndex = parser.GetNextToken (",").ToInt16 ();
    }
    bool duplicate = false;
    AddClassIndexAssignment (MLClass::CreateNewMLClass (
      className), classIndex, duplicate);
    if (duplicate)
    {
      log.Level (-1) << endl
        << "MLClassIndexList::ParseClassIndexList ***ERROR*** Duplicate ClassIndex[" << classIndex << "
      ] specified for class[" << className << "]" << endl
        << endl;
    }
  }
} /* ParseClassIndexList */
void MLClassIndexList::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) [virtual]
Definition at line 1703 of file MLClass.cpp.
References KKB::XmlContent::Content(), KKB::XmlStream::GetNextToken(), and ParseClassIndexList().
{
  largestIndex = -1;
  shortIdx.clear ();
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (typeid (*t) == typeid (XmlContent))
    {
      XmlContentPtr c = dynamic_cast<XmlContentPtr> (t);
      if (c && c->Content ())
      {
        KKStrConstPtr text = c->Content ();
        ParseClassIndexList (*text, log);
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
} /* ReadXML */
KKStr MLClassIndexList::ToCommaDelString () const
Returns string consisting of all contained classes indicating ClassIndex assigned to each class.
Each class will be separated by a comma(`,`) delimiter character and each class will consist of `ClassName` and associated `ClassIndex` separated by colon(`:`) character. The class names will be enclosed in quotes(`). The method `ParseClassIndexList` will be able to decode this string to
 repopulate an instance of `MLClassIndexList`.
@see `KKStr::QuotedStr`
 Example String: `Copepod`:1,`Doliolid`:2,`Larvacean":3
Definition at line 1689 of file MLClass.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), and KKB::KKStr::KKStr().
Referenced by WriteXML().
{
  KKStr delStr (255);
  map<kkint16, MLClassPtr>::const_iterator idx;
  for (idx = shortIdx.begin (); idx != shortIdx.end (); idx++)
  {
    if (!delStr.Empty ())
      delStr << ",";
    delStr << idx->second->Name ().QuotedStr () << ":" << idx->first;
  }
  return delStr;
} /* ToCommaDelString */
void MLClassIndexList::WriteXML (const KKStr & varName, std::ostream & o) const [virtual]
Definition at line 1733 of file MLClass.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, ToCommaDelString(), KKB::XmlTag::WriteXML(), KKB::XmlContent::WriteXml(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::Model::WriteModelXMLFields().
{
  XmlTag startTag ("MLClassIndexList", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  XmlContent::WriteXml (ToCommaDelString (), o);
  XmlTag endTag ("MLClassIndexList", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.cpp