KKB::VectorKKStr Class Reference
#include <KKStr.h>
Public Member Functions
VectorKKStr ()
VectorKKStr (const VectorKKStr &v)
void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
void WriteXML (const KKStr &varName, std::ostream &o) const
Detailed Description
summary> A string class providing safe runtime management; strings can be used as stream and StringBuilder objects. Simple token parsing is supported as well as various translations to other formats such as 'int', 'double', and others. Allocation is done dynamically increasing as needs warrant. All methods ensure that there is no accessing outside the bounds of the allocated string. /summary> todo> Should subclass the class from the stl class 'string'. </todo>
Definition at line 54 of file KKStr.h.
Constructor & Destructor Documentation
VectorKKStr::VectorKKStr ()
Definition at line 5264 of file KKStr.cpp.
References VectorKKStr().
Referenced by KKMLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), KKMLL::TrainingProcess2::ConfigFileFormatErrors(), KKB::Configuration::Configuration(), KKMLL::TrainingClass::TrainingClass(), VectorKKStr(), and KKB::XmlStream::XmlStream().
                         :
  vector<KKStr> ()
{
}
VectorKKStr::VectorKKStr (const VectorKKStr & v)
Definition at line 5270 of file KKStr.cpp.
References VectorKKStr().
Referenced by KKB::Configuration::Configuration(), KKMLL::TrainingClass::TrainingClass(), and VectorKKStr().
                                              :
  vector<KKStr> (v)
{
}
Member Function Documentation
void VectorKKStr::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 5277 of file KKStr.cpp.
References KKB::XmlTag::AttributeValueInt32(), KKB::KKStr::Concat(), KKB::XmlContent::Content(), KKB::KKStrParser::GetNextToken(), KKB::XmlStream::GetNextToken(), KKB::KKStrParser::KKStrParser(), KKB::KKStrParser::MoreTokens(), KKB::XmlToken::tokContent, KKB::XmlToken::TokenType(), and KKB::KKStrParser::TrimWhiteSpace().
{
  kkuint32 count = (kkuint32)tag->AttributeValueInt32 ("Count");
  clear ();
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (t->TokenType () == XmlToken::TokenTypes::tokContent)
    {
      XmlContentPtr c = dynamic_cast<XmlContentPtr>(t);
      if ((c != NULL) && (c->Content () != NULL))
      {
        KKStrParser parser (*(c->Content ()));
        parser.TrimWhiteSpace (" ");
        while (parser.MoreTokens ())
        {
          KKStr field = parser.GetNextToken ("\t");
          push_back (field);
        }
      }
    }
    delete t;
    if (cancelFlag)
      t = NULL;
    else
      t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
} /* ReadXML */
void VectorKKStr::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 5319 of file KKStr.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::operator<<(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::Attribute::WriteXML().
{
  XmlTag startTag ("VectorKKStr", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.AddAtribute ("Count", (kkint32)size ());
  startTag.WriteXML (o);
  const_iterator idx;
  kkuint32 x = 0;
  for (idx = begin (); idx != end (); ++idx, ++x)
  {
    if (x > 0) o << "\t";
    XmlContent::WriteXml (idx->QuotedStr (), o);
  }
  XmlTag endTag ("VectorKKStr", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStr.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStr.cpp