KKB::MorphOp Class Reference
Base class for all Morphological operations.
#include <MorphOp.h>
Public Types
enum MaskTypes : int {
*
MaskTypes::CROSS3 = 0,
MaskTypes::CROSS5 = 1,
MaskTypes::SQUARE3 = 2,
MaskTypes::SQUARE5 = 3,
*
MaskTypes::SQUARE7 = 4,
MaskTypes::SQUARE9 = 5,
MaskTypes::SQUARE11 = 6
 }
enum OperationType {
*
OperationType::Null,
OperationType::Binarize,
OperationType::BmiFiltering,
OperationType::ConvexHull,
*
OperationType::Dilation,
OperationType::Erosion,
OperationType::MaskExclude,
OperationType::SobelEdgeDetection,
*
OperationType::Stretcher
 }
enum StructureType : int { StructureType::Null,
StructureType::stCross,
StructureType::stSquare
 }
Public Member Functions
MorphOp ()
virtual ~MorphOp ()
virtual OperationType Operation () const =0
OperationType OperationTypeFromStr (const KKB::KKStr &_operationStr)
KKB::KKStr OperationTypeToStr (OperationType _operation)
virtual RasterPtr PerformOperation (Raster const *_image)=0
Static Public Member Functions
static kkint32 Biases (MaskTypes mt)
static StructureType MaskShapes (MaskTypes mt)
Protected Member Functions
bool BackgroundPixel (uchar pixel) const
bool BackgroundPixel (kkint32 row, kkint32 col) const
bool ForegroundPixel (uchar pixel) const
bool ForegroundPixel (kkint32 row, kkint32 col) const
void SetSrcRaster (RasterConstPtr _srcRaster)
Protected Attributes
uchar backgroundPixelTH
uchar backgroundPixelValue
uchar *const * srcBlue
uchar const * srcBlueArea
bool srcColor
uchar *const * srcGreen
uchar const * srcGreenArea
kkint32 srcHeight
RasterConstPtr srcRaster
uchar *const * srcRed
uchar const * srcRedArea
kkint32 srcWidth
Static Protected Attributes
static kkint32 biases []
static StructureType maskShapes []
Detailed Description
Base class for all Morphological operations.
Creates a image where the only pixels that are passed thru are the ones that would be removed by the specified mask when a Open-Dilatation operation are performed.
Meant to be the base class to all Morphological operators.
It is assumed that all morphologocal operations will be working with a source image and returning a new modified image; the atcual operation is to be perfomed by the `PerformOperation` metho where you pass in a poiter to the source Image/ Raster. The the derived class would then call `SetSrcRaster` to intialize the base class `MorphOp` with pointers to the source image.
See also
KKB::Raster
Definition at line 44 of file MorphOp.h.
Member Enumeration Documentation
enum KKB::MorphOp::MaskTypes : int [strong]
Enumerator
CROSS3
CROSS5
SQUARE3
SQUARE5
SQUARE7
SQUARE9
SQUARE11
Definition at line 72 of file MorphOp.h.
                         : int
    {
      CROSS3 = 0,
      CROSS5 = 1,
      SQUARE3 = 2,
      SQUARE5 = 3,
      SQUARE7 = 4,
      SQUARE9 = 5,
      SQUARE11 = 6
    };
enum KKB::MorphOp::OperationType [strong]
Enumerator
Null
Binarize
BmiFiltering
ConvexHull
Dilation
Erosion
MaskExclude
SobelEdgeDetection
Stretcher
Definition at line 47 of file MorphOp.h.
    {
      Null,
      Binarize,
      BmiFiltering,
      ConvexHull,
      Dilation,
      Erosion,
      MaskExclude,
      SobelEdgeDetection,
      Stretcher
    };
enum KKB::MorphOp::StructureType : int [strong]
Enumerator
Null
stCross
stSquare
Definition at line 64 of file MorphOp.h.
                             : int
    {
       Null,
       stCross,
       stSquare
    };
Constructor & Destructor Documentation
MorphOp::MorphOp ()
Definition at line 73 of file MorphOp.cpp.
References backgroundPixelTH, backgroundPixelValue, srcBlue, srcBlueArea, srcColor, srcGreen, srcGreenArea, srcHeight, srcRaster, srcRed, srcRedArea, and srcWidth.
Referenced by KKB::ConvexHull::ConvexHull(), KKB::MorphOpBinarize::MorphOpBinarize(), KKB::MorphOpBmiFiltering::MorphOpBmiFiltering(), KKB::MorphOpMaskExclude::MorphOpMaskExclude(), KKB::MorphOpStretcher::MorphOpStretcher(), and KKB::MorphOpStruct::MorphOpStruct().
                 :
    backgroundPixelTH (31),
    backgroundPixelValue (0),
    srcRaster (NULL),
    srcRedArea (NULL),
    srcGreenArea (NULL),
    srcBlueArea (NULL),
    srcRed (NULL),
    srcGreen (NULL),
    srcBlue (NULL),
    srcColor (false),
    srcHeight (0),
    srcWidth (0)
{
}
MorphOp::~MorphOp () [virtual]
Definition at line 91 of file MorphOp.cpp.
{
}
Member Function Documentation
bool MorphOp::BackgroundPixel (uchar pixel) const [protected]
Definition at line 171 of file MorphOp.cpp.
References backgroundPixelTH.
Referenced by KKB::MorphOpStruct::Fit(), KKB::MorphOpStruct::FitBackgroundCount(), and KKB::MorphOpDilation::PerformOperation().
{
  return (pixel <= backgroundPixelTH);
} /* BackgroundPixel */
bool MorphOp::BackgroundPixel (kkint32 row, kkint32 col) const [protected]
Definition at line 178 of file MorphOp.cpp.
References backgroundPixelTH, srcGreen, srcHeight, and srcWidth.
{
  if ((row < 0) ||
       (row >= srcHeight) ||
       (col < 0) ||
       (col >= srcWidth) ||
       (srcGreen == NULL)
      )
    return false;
  return (srcGreen[row][col] <= backgroundPixelTH);
} /* BackgroundPixel */
kkint32 MorphOp::Biases (MaskTypes mt) [static]
Definition at line 44 of file MorphOp.cpp.
References biases, CROSS3, and SQUARE9.
Referenced by KKB::Raster::Erosion(), KKB::Raster::ErosionBoundary(), KKB::Raster::ErosionChanged(), KKB::Raster::ErosionChanged1(), and KKB::Raster::Raster().
{
  if (mt < MaskTypes::CROSS3)
    mt = MaskTypes::CROSS3;
  else if (mt > MaskTypes::SQUARE9)
    mt = MaskTypes::SQUARE9;
  return biases[(int)mt];
}
bool MorphOp::ForegroundPixel (uchar pixel) const [protected]
Definition at line 195 of file MorphOp.cpp.
References backgroundPixelTH.
Referenced by KKB::MorphOpStruct::HitForegroundCount(), KKB::MorphOpDilation::PerformOperation(), and KKB::MorphOpErosion::PerformOperation().
{
  return (pixel > backgroundPixelTH);
} /* ForegroundPixel */
bool MorphOp::ForegroundPixel (kkint32 row, kkint32 col) const [protected]
Definition at line 202 of file MorphOp.cpp.
References backgroundPixelTH, srcGreen, srcHeight, and srcWidth.
Referenced by KKB::ConvexHull::Store().
{
  if ((row < 0) ||
       (row >= srcHeight) ||
       (col < 0) ||
       (col >= srcWidth) ||
       (srcGreen == NULL)
      )
    return false;
  return (srcGreen[row][col] > backgroundPixelTH);
} /* ForegroundPixel */
StructureType MorphOp::MaskShapes (MaskTypes mt) [static]
Definition at line 57 of file MorphOp.cpp.
References CROSS3, maskShapes, and SQUARE9.
Referenced by KKB::Raster::Erosion(), KKB::Raster::ErosionBoundary(), KKB::Raster::ErosionChanged(), and KKB::Raster::ErosionChanged1().
{
  if (mt < MaskTypes::CROSS3)
    mt = MaskTypes::CROSS3;
  else if (mt > MaskTypes::SQUARE9)
    mt = MaskTypes::SQUARE9;
  return maskShapes[(int)mt];
}
virtual OperationType KKB::MorphOp::Operation () const [pure virtual]
Implemented in KKB::ConvexHull, KKB::MorphOpMaskExclude, KKB::MorphOpStretcher, KKB::MorphOpBinarize, KKB::MorphOpStruct, KKB::MorphOpDilation, KKB::MorphOpErosion, KKB::MorphOpBmiFiltering, and KKB::MorphOpSobel.
MorphOp::OperationType MorphOp::OperationTypeFromStr (const KKB::KKStr & _operationStr)
Definition at line 123 of file MorphOp.cpp.
References Binarize, BmiFiltering, ConvexHull, KKB::KKStr::EqualIgnoreCase(), Erosion, MaskExclude, Null, and Stretcher.
{
  if (_operationStr.EqualIgnoreCase ("Stretcher"))
    return OperationType::Stretcher;
  else if (_operationStr.EqualIgnoreCase ("Binarize"))
    return OperationType::Binarize;
  else if (_operationStr.EqualIgnoreCase ("BmiFiltering"))
    return OperationType::BmiFiltering;
  else if (_operationStr.EqualIgnoreCase ("ConvexHull"))
    return OperationType::ConvexHull;
  else if (_operationStr.EqualIgnoreCase ("Erosion"))
    return OperationType::Erosion;
  else if (_operationStr.EqualIgnoreCase ("MaskExclude"))
    return OperationType::MaskExclude;
  else
    return OperationType::Null;
}
KKB::KKStr MorphOp::OperationTypeToStr (OperationType _operation)
Definition at line 97 of file MorphOp.cpp.
References BmiFiltering, ConvexHull, Dilation, Erosion, MaskExclude, and Stretcher.
{
  if (_operation == OperationType::Stretcher)
    return "Stretcher";
  else if (_operation == OperationType::BmiFiltering)
    return "BmiFiltering";
  else if (_operation == OperationType::ConvexHull)
    return "ConvexHull";
  else if (_operation == OperationType::Dilation)
    return "Dilation";
  else if (_operation == OperationType::Erosion)
    return "Erosion";
  else if (_operation == OperationType::MaskExclude)
    return "MaskExclude";
  else
    return "NULL";
}
virtual RasterPtr KKB::MorphOp::PerformOperation (Raster const * _image) [pure virtual]
Implemented in KKB::MorphOpSobel.
void MorphOp::SetSrcRaster (RasterConstPtr _srcRaster) [protected]
Definition at line 149 of file MorphOp.cpp.
References backgroundPixelTH, KKB::Raster::BackgroundPixelTH(), backgroundPixelValue, KKB::Raster::BackgroundPixelValue(), KKB::Raster::Blue(), KKB::Raster::BlueArea(), KKB::Raster::Color(), KKB::Raster::Green(), KKB::Raster::GreenArea(), KKB::Raster::Height(), KKB::Raster::Red(), KKB::Raster::RedArea(), srcBlue, srcBlueArea, srcColor, srcGreen, srcGreenArea, srcHeight, srcRaster, srcRed, srcRedArea, srcWidth, and KKB::Raster::Width().
Referenced by KKB::ConvexHull::Filter(), KKB::MorphOpSobel::PerformOperation(), KKB::MorphOpBmiFiltering::PerformOperation(), KKB::MorphOpDilation::PerformOperation(), KKB::MorphOpErosion::PerformOperation(), KKB::MorphOpBinarize::PerformOperation(), KKB::MorphOpStretcher::PerformOperation(), KKB::MorphOpMaskExclude::PerformOperation(), and KKB::ConvexHull::PerformOperation().
{
  srcRaster = _srcRaster;
  srcColor = srcRaster->Color ();
  srcHeight = srcRaster->Height ();
  srcWidth = srcRaster->Width ();
  backgroundPixelTH = srcRaster->BackgroundPixelTH ();
  backgroundPixelValue = srcRaster->BackgroundPixelValue ();
  srcRedArea = srcRaster->RedArea ();
  srcGreenArea = srcRaster->GreenArea ();
  srcBlueArea = srcRaster->BlueArea ();
  srcRed = srcRaster->Red ();
  srcGreen = srcRaster->Green ();
  srcBlue = srcRaster->Blue ();
} /* SetSrcRaster */
Member Data Documentation
uchar KKB::MorphOp::backgroundPixelTH [protected]
Definition at line 109 of file MorphOp.h.
Referenced by BackgroundPixel(), ForegroundPixel(), MorphOp(), and SetSrcRaster().
uchar KKB::MorphOp::backgroundPixelValue [protected]
Definition at line 110 of file MorphOp.h.
Referenced by MorphOp(), and SetSrcRaster().
kkint32 MorphOp::biases [static], [protected]
Initial value:
= {1,
                              2,
                              1,
                              2,
                              3,
                              4,
                              5
                             }
Definition at line 126 of file MorphOp.h.
Referenced by Biases().
StructureType MorphOp::maskShapes [static], [protected]
Initial value:
= {StructureType::stCross,
                                        StructureType::stCross,
                                        StructureType::stSquare,
                                        StructureType::stSquare,
                                        StructureType::stSquare,
                                        StructureType::stSquare,
                                        StructureType::stSquare
                                       }
Definition at line 127 of file MorphOp.h.
Referenced by MaskShapes().
uchar* const* KKB::MorphOp::srcBlue [protected]
Definition at line 120 of file MorphOp.h.
Referenced by MorphOp(), KKB::MorphOpStretcher::PerformOperation(), and SetSrcRaster().
uchar const* KKB::MorphOp::srcBlueArea [protected]
Definition at line 116 of file MorphOp.h.
Referenced by MorphOp(), KKB::MorphOpMaskExclude::PerformOperation(), and SetSrcRaster().
bool KKB::MorphOp::srcColor [protected]
Definition at line 122 of file MorphOp.h.
Referenced by MorphOp(), KKB::MorphOpMaskExclude::PerformOperation(), and SetSrcRaster().
uchar* const* KKB::MorphOp::srcGreen [protected]
Definition at line 119 of file MorphOp.h.
Referenced by BackgroundPixel(), KKB::MorphOpStruct::Fit(), KKB::MorphOpStruct::FitBackgroundCount(), ForegroundPixel(), KKB::MorphOpStruct::HitForegroundCount(), MorphOp(), KKB::MorphOpDilation::PerformOperation(), KKB::MorphOpBinarize::PerformOperation(), KKB::MorphOpErosion::PerformOperation(), KKB::MorphOpStretcher::PerformOperation(), and SetSrcRaster().
uchar const* KKB::MorphOp::srcGreenArea [protected]
Definition at line 115 of file MorphOp.h.
Referenced by MorphOp(), KKB::MorphOpMaskExclude::PerformOperation(), and SetSrcRaster().
kkint32 KKB::MorphOp::srcHeight [protected]
Definition at line 123 of file MorphOp.h.
Referenced by BackgroundPixel(), KKB::ConvexHull::Filter(), KKB::MorphOpStruct::Fit(), KKB::MorphOpStruct::FitBackgroundCount(), ForegroundPixel(), KKB::MorphOpStruct::HitForegroundCount(), MorphOp(), KKB::MorphOpErosion::PerformOperation(), KKB::MorphOpBinarize::PerformOperation(), KKB::MorphOpDilation::PerformOperation(), KKB::MorphOpStretcher::PerformOperation(), KKB::MorphOpMaskExclude::PerformOperation(), and SetSrcRaster().
RasterConstPtr KKB::MorphOp::srcRaster [protected]
Definition at line 112 of file MorphOp.h.
Referenced by MorphOp(), KKB::MorphOpBmiFiltering::PerformOperation(), KKB::MorphOpErosion::PerformOperation(), KKB::MorphOpBinarize::PerformOperation(), KKB::MorphOpDilation::PerformOperation(), KKB::ConvexHull::PerformOperation(), and SetSrcRaster().
uchar* const* KKB::MorphOp::srcRed [protected]
Definition at line 118 of file MorphOp.h.
Referenced by MorphOp(), KKB::MorphOpStretcher::PerformOperation(), and SetSrcRaster().
uchar const* KKB::MorphOp::srcRedArea [protected]
Definition at line 114 of file MorphOp.h.
Referenced by MorphOp(), KKB::MorphOpMaskExclude::PerformOperation(), and SetSrcRaster().
kkint32 KKB::MorphOp::srcWidth [protected]
Definition at line 124 of file MorphOp.h.
Referenced by BackgroundPixel(), KKB::ConvexHull::Filter(), KKB::MorphOpStruct::Fit(), KKB::MorphOpStruct::FitBackgroundCount(), ForegroundPixel(), KKB::MorphOpStruct::HitForegroundCount(), MorphOp(), KKB::MorphOpErosion::PerformOperation(), KKB::MorphOpBinarize::PerformOperation(), KKB::MorphOpDilation::PerformOperation(), KKB::MorphOpStretcher::PerformOperation(), KKB::MorphOpMaskExclude::PerformOperation(), and SetSrcRaster().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOp.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOp.cpp