KKB::XmlTag Class Reference
#include <XmlStream.h>
Public Types
enum TagTypes { TagTypes::tagNULL,
TagTypes::tagStart,
TagTypes::tagEnd,
TagTypes::tagEmpty
 }
typedef XmlTag * XmlTagPtr
Public Member Functions
XmlTag (const KKStrConstPtr tagStr)
XmlTag (const KKStr &_name, TagTypes _tagType)
XmlTag (std::istream &i)
virtual ~XmlTag ()
void AddAtribute (const KKStr &attributeName, const KKStr &attributeValue)
void AddAtribute (const KKStr &attributeName, bool attributeValue)
void AddAtribute (const KKStr &attributeName, kkint32 attributeValue)
void AddAtribute (const KKStr &attributeName, kkint64 attributeValue)
void AddAtribute (const KKStr &attributeName, double attributeValue)
void AddAtribute (const KKStr &attributeName, const DateTime &attributeValue)
kkint32 AttributeCount () const
KKStrConstPtr AttributeNameByIndex (kkuint32 index) const
const XmlAttributeList & Attributes () const
KKStrConstPtr AttributeValueByIndex (kkuint32 index) const
KKStrConstPtr AttributeValueByName (const KKStr &name) const
DateTime AttributeValueDateTime (const KKStr &attributeName) const
kkint32 AttributeValueInt32 (const KKStr &attributeName) const
const KKStr & AttributeValueKKStr (const KKStr &name) const
const KKStr & Name () const
TagTypes TagType () const
KKStr ToString () const
void WriteXML (std::ostream &o)
Detailed Description
Definition at line 172 of file XmlStream.h.
Member Typedef Documentation
typedef XmlTag* KKB::XmlTag::XmlTagPtr
Definition at line 175 of file XmlStream.h.
Member Enumeration Documentation
enum KKB::XmlTag::TagTypes [strong]
Enumerator
tagNULL
tagStart
tagEnd
tagEmpty
Definition at line 176 of file XmlStream.h.
{tagNULL, tagStart, tagEnd, tagEmpty};
Constructor & Destructor Documentation
XmlTag::XmlTag (const KKStrConstPtr tagStr)
Definition at line 543 of file XmlStream.cpp.
References KKB::KKStr::Concat(), KKB::KKStrParser::GetLastChar(), KKB::KKStrParser::GetNextChar(), KKB::KKStrParser::GetNextToken(), KKB::KKStr::KKStr(), KKB::KKStrParser::KKStrParser(), KKB::KKStrParser::MoreTokens(), KKB::KKStr::operator=(), KKB::KKStrParser::PeekLastChar(), KKB::KKStrParser::PeekNextChar(), KKB::KKStrParser::SkipWhiteSpace(), tagEmpty, tagEnd, tagNULL, tagStart, KKB::KKStrParser::TrimWhiteSpace(), and XmlTag().
Referenced by KKB::XmlStream::GetNextToken(), and XmlTag().
                                          :
   attributes (true),
   name (),
   tagType (TagTypes::tagNULL)
{
  KKStrParser parser(*tagStr);
  parser.TrimWhiteSpace (" ");
  if (parser.PeekNextChar () == '<')
    parser.GetNextChar ();
  if (parser.PeekLastChar () == '>')
    parser.GetLastChar ();
  if (parser.PeekNextChar () == '/')
  {
    parser.GetNextChar ();
    tagType = XmlTag::TagTypes::tagEnd;
  }
  else if (parser.PeekLastChar () == '/')
  {
    parser.GetLastChar ();
    tagType = XmlTag::TagTypes::tagEmpty;
  }
  else
  {
    tagType = XmlTag::TagTypes::tagStart;
  }
  name = parser.GetNextToken ();
  parser.SkipWhiteSpace ();
  while (parser.MoreTokens ())
  {
    KKStr attributeName = parser.GetNextToken ("=");
    KKStr attributeValue = parser.GetNextToken (" \t\n\r");
    attributes.AddAttribute (attributeName, attributeValue);
  }
} /* XmlTag::XmlTag (const KKStrConstPtr tagStr) */
XmlTag::XmlTag (const KKStr & _name, TagTypes _tagType)
Definition at line 586 of file XmlStream.cpp.
References KKB::KKStr::KKStr(), and XmlTag().
Referenced by KKMLL::ModelParamKnn::WriteXML(), KKMLL::AttributeTypeVector::WriteXML(), KKB::VectorKKStr::WriteXML(), KKMLL::ModelParamSvmBase::WriteXML(), KKMLL::ModelParamUsfCasCor::WriteXML(), KKMLL::ModelParamDual::WriteXML(), KKMLL::NormalizationParms::WriteXML(), KKMLL::ModelKnn::WriteXML(), KKMLL::ClassProbList::WriteXML(), KKMLL::FeatureEncoder::WriteXML(), KKB::BitString::WriteXML(), KKMLL::ModelUsfCasCor::WriteXML(), KKMLL::ModelSvmBase::WriteXML(), KKMLL::Attribute::WriteXML(), KKMLL::ModelParamOldSVM::WriteXML(), KKMLL::TrainingClassList::WriteXML(), KKMLL::MLClass::WriteXML(), KKMLL::AttributeList::WriteXML(), SVM233::SvmModel233::WriteXML(), SVM289_MFS::Svm_Model::WriteXML(), KKMLL::ModelDual::WriteXML(), KKMLL::FeatureNumList::WriteXML(), KKMLL::SVMparam::WriteXML(), KKMLL::FileDesc::WriteXML(), KKMLL::ModelOldSVM::WriteXML(), KKMLL::SVMModel::WriteXML(), KKMLL::TrainingProcess2::WriteXML(), KKMLL::TrainingConfiguration2::WriteXML(), KKMLL::MLClassList::WriteXML(), KKB::XmlElementBool::WriteXML(), KKMLL::MLClassIndexList::WriteXML(), KKB::XmlElementDateTime::WriteXML(), KKB::KKStr::WriteXML(), KKMLL::XmlElementMLClassNameList::WriteXML(), KKB::XmlElementKeyValuePairs::WriteXML(), KKB::XmlElementArrayFloat2DVarying::WriteXML(), KKB::KKStrList::WriteXML(), KKB::KKStrListIndexed::WriteXML(), KKB::XmlElement::XmlElement(), and XmlTag().
                :
   attributes (true),
   name (_name),
   tagType (_tagType)
{
}
XmlTag::~XmlTag () [virtual]
summary>Will construct a generic XML tag from the following characters in the stream.
remarks> It is assumed that the next character read from the input stream i will be <; if not then it is assumed that the next character is the one immediately following the <. /remarks>
Definition at line 596 of file XmlStream.cpp.
{
}
KKB::XmlTag::XmlTag (std::istream & i)
Member Function Documentation
void XmlTag::AddAtribute (const KKStr & attributeName, const KKStr & attributeValue)
Definition at line 602 of file XmlStream.cpp.
Referenced by KKMLL::ModelParamKnn::WriteXML(), KKMLL::AttributeTypeVector::WriteXML(), KKB::VectorKKStr::WriteXML(), KKMLL::ModelParamSvmBase::WriteXML(), KKMLL::ModelParamUsfCasCor::WriteXML(), KKMLL::ModelParamDual::WriteXML(), KKMLL::ModelKnn::WriteXML(), KKMLL::NormalizationParms::WriteXML(), KKMLL::ClassProbList::WriteXML(), KKMLL::FeatureEncoder::WriteXML(), KKB::BitString::WriteXML(), KKMLL::ModelUsfCasCor::WriteXML(), KKMLL::ModelSvmBase::WriteXML(), KKMLL::Attribute::WriteXML(), KKMLL::ModelParamOldSVM::WriteXML(), KKMLL::TrainingClassList::WriteXML(), KKMLL::MLClass::WriteXML(), KKMLL::AttributeList::WriteXML(), SVM233::SvmModel233::WriteXML(), SVM289_MFS::Svm_Model::WriteXML(), KKMLL::ModelDual::WriteXML(), KKMLL::FeatureNumList::WriteXML(), KKMLL::SVMparam::WriteXML(), KKMLL::FileDesc::WriteXML(), KKMLL::ModelOldSVM::WriteXML(), KKMLL::SVMModel::WriteXML(), KKMLL::TrainingProcess2::WriteXML(), KKMLL::TrainingConfiguration2::WriteXML(), KKMLL::MLClassList::WriteXML(), KKB::XmlElementBool::WriteXML(), KKMLL::MLClassIndexList::WriteXML(), KKB::XmlElementDateTime::WriteXML(), KKB::KKStr::WriteXML(), KKMLL::XmlElementMLClassNameList::WriteXML(), KKB::XmlElementKeyValuePairs::WriteXML(), KKB::XmlElementArrayFloat2DVarying::WriteXML(), KKB::KKStrList::WriteXML(), and KKB::KKStrListIndexed::WriteXML().
{
  attributes.AddAttribute (attributeName, attributeValue);
}
void XmlTag::AddAtribute (const KKStr & attributeName, bool attributeValue)
Definition at line 611 of file XmlStream.cpp.
Referenced by KKMLL::MLClass::WriteXML(), KKB::XmlElementBool::WriteXML(), and KKB::KKStrListIndexed::WriteXML().
{
  attributes.AddAttribute (attributeName, (attributeValue ? "Yes" : "No"));
}
void XmlTag::AddAtribute (const KKStr & attributeName, kkint32 attributeValue)
Definition at line 620 of file XmlStream.cpp.
Referenced by KKMLL::Attribute::WriteXML(), KKMLL::MLClass::WriteXML(), KKMLL::FeatureNumList::WriteXML(), KKB::KKStr::WriteXML(), and KKB::XmlElementArrayFloat2DVarying::WriteXML().
{
  attributes.AddAttribute (attributeName, StrFromInt32 (attributeValue));
}
void XmlTag::AddAtribute (const KKStr & attributeName, kkint64 attributeValue)
Definition at line 629 of file XmlStream.cpp.
{
  attributes.AddAttribute (attributeName, StrFromInt64 (attributeValue));
}
void XmlTag::AddAtribute (const KKStr & attributeName, double attributeValue)
Definition at line 638 of file XmlStream.cpp.
References KKB::KKStr::Concat(), and KKB::KKStr::KKStr().
Referenced by KKMLL::MLClass::WriteXML().
{
  KKStr s (20);
  s << attributeValue;
  attributes.AddAttribute (attributeName, s);
}
void XmlTag::AddAtribute (const KKStr & attributeName, const DateTime & attributeValue)
Definition at line 649 of file XmlStream.cpp.
{
  attributes.AddAttribute (attributeName, attributeValue.
      YYYY_MM_DD_HH_MM_SS ());
}
kkint32 KKB::XmlTag::AttributeCount () const [inline]
Definition at line 196 of file XmlStream.h.
Referenced by KKMLL::XmlElementMLClass::XmlElementMLClass().
{return (kkint32)attributes.size ();}
KKStrConstPtr XmlTag::AttributeNameByIndex (kkuint32 index) const
Definition at line 670 of file XmlStream.cpp.
Referenced by KKMLL::XmlElementMLClass::XmlElementMLClass().
{
  return attributes.AttributeNameByIndex (index);
}
const XmlAttributeList& KKB::XmlTag::Attributes () const [inline]
Definition at line 198 of file XmlStream.h.
{return attributes;}
KKStrConstPtr XmlTag::AttributeValueByIndex (kkuint32 index) const
Definition at line 664 of file XmlStream.cpp.
Referenced by KKMLL::XmlElementMLClass::XmlElementMLClass().
{
  return attributes.AttributeValueByIndex (index);
}
KKStrConstPtr XmlTag::AttributeValueByName (const KKStr & name) const
Definition at line 658 of file XmlStream.cpp.
Referenced by KKB::XmlElement::AttributeValue(), KKB::KKStrListIndexed::ReadXML(), KKB::XmlElement::VarName(), KKB::XmlElementBool::XmlElementBool(), and KKMLL::XmlElementMLClass::XmlElementMLClass().
{
  return attributes.AttributeValueByName (name);
}
DateTime XmlTag::AttributeValueDateTime (const KKStr & attributeName) const
Definition at line 682 of file XmlStream.cpp.
Referenced by KKB::XmlElementDateTime::XmlElementDateTime().
{
 return this->attributes.AttributeValueDateTime (attributeName);
}
kkint32 XmlTag::AttributeValueInt32 (const KKStr & attributeName) const
Definition at line 676 of file XmlStream.cpp.
Referenced by KKMLL::AttributeTypeVector::ReadXML(), KKB::VectorKKStr::ReadXML(), KKMLL::Attribute::ReadXML(), KKMLL::FeatureNumList::ReadXML(), KKB::KKStr::ReadXML(), KKB::KKStrList::ReadXML(), and KKB::XmlElementArrayFloat2DVarying::XmlElementArrayFloat2DVarying().
{
 return this->attributes.AttributeValueInt32 (attributeName);
}
const KKStr & XmlTag::AttributeValueKKStr (const KKStr & name) const
Definition at line 688 of file XmlStream.cpp.
Referenced by KKMLL::Attribute::ReadXML().
{
 return attributes.AttributeValueKKStr (attributeName);
}
const KKStr& KKB::XmlTag::Name () const [inline]
Definition at line 193 of file XmlStream.h.
Referenced by KKB::XmlStream::GetNextToken(), and KKB::XmlElement::SectionName().
{return name;}
TagTypes KKB::XmlTag::TagType () const [inline]
Definition at line 194 of file XmlStream.h.
Referenced by KKB::XmlStream::GetNextToken(), and WriteXML().
{return tagType;}
KKStr XmlTag::ToString () const
Definition at line 694 of file XmlStream.cpp.
References KKB::KKStr::Concat(), KKB::XmlAttribute::Name(), KKB::KKStr::QuotedStr(), tagEmpty, tagEnd, and KKB::XmlAttribute::Value().
Referenced by KKB::XmlElement::NameTagStr(), KKB::XmlElement::ToKKStr(), and WriteXML().
{
  KKStr s (name.Len () + attributes.size () * 30);
  s << "<";
  
  if (tagType == TagTypes::tagEnd)
    s << "/";
  s << name;
  XmlAttributeList::const_iterator idx;
  for (idx = attributes.begin(); idx != attributes.end (); ++idx)
  {
    XmlAttributePtr a = *idx;
    s << " " << a->Name () << "=" << a->Value ().QuotedStr ();
  }
  if (tagType == TagTypes::tagEmpty)
    s << "/";
   s << ">";
   return s;
}
void XmlTag::WriteXML (std::ostream & o)
Definition at line 723 of file XmlStream.cpp.
References KKB::operator<<(), tagEnd, tagStart, TagType(), ToString(), and xmlLevel.
Referenced by KKMLL::ModelParamKnn::WriteXML(), KKMLL::AttributeTypeVector::WriteXML(), KKB::VectorKKStr::WriteXML(), KKMLL::ModelParamSvmBase::WriteXML(), KKMLL::ModelParamUsfCasCor::WriteXML(), KKMLL::ModelParamDual::WriteXML(), KKMLL::ModelKnn::WriteXML(), KKMLL::NormalizationParms::WriteXML(), KKMLL::ClassProbList::WriteXML(), KKMLL::FeatureEncoder::WriteXML(), KKB::BitString::WriteXML(), KKMLL::ModelUsfCasCor::WriteXML(), KKMLL::ModelSvmBase::WriteXML(), KKMLL::Attribute::WriteXML(), KKMLL::ModelParamOldSVM::WriteXML(), KKMLL::TrainingClassList::WriteXML(), KKMLL::MLClass::WriteXML(), KKMLL::AttributeList::WriteXML(), SVM233::SvmModel233::WriteXML(), SVM289_MFS::Svm_Model::WriteXML(), KKMLL::ModelDual::WriteXML(), KKMLL::FeatureNumList::WriteXML(), KKMLL::SVMparam::WriteXML(), KKMLL::FileDesc::WriteXML(), KKMLL::ModelOldSVM::WriteXML(), KKMLL::SVMModel::WriteXML(), KKMLL::TrainingProcess2::WriteXML(), KKMLL::TrainingConfiguration2::WriteXML(), KKMLL::MLClassList::WriteXML(), KKB::XmlElementBool::WriteXML(), KKMLL::MLClassIndexList::WriteXML(), KKB::XmlElementDateTime::WriteXML(), KKB::KKStr::WriteXML(), KKMLL::XmlElementMLClassNameList::WriteXML(), KKB::XmlElementKeyValuePairs::WriteXML(), KKB::XmlElementArrayFloat2DVarying::WriteXML(), KKB::KKStrList::WriteXML(), and KKB::KKStrListIndexed::WriteXML().
{
  if (TagType () == TagTypes::tagEnd)
    --xmlLevel;
  for (kkint32 x = 0; x < xmlLevel; ++x)
    o << " ";
  o << ToString ();
  if (this->TagType () == TagTypes::tagStart)
    ++xmlLevel;
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp