KKMLL::KKMLVariables Class Reference
#include <KKMLVariables.h>
Public Member Functions
KKMLVariables ()
~KKMLVariables ()
Static Public Member Functions
static void SetMachineLearninigHomeDir (const KKStr &_machineLearningHomeDir)
static KKStr TempDir ()
static KKStr TrainingLibrariesDir ()
static KKStr TrainingModelsDir ()
Detailed Description
Definition at line 22 of file KKMLVariables.h.
Constructor & Destructor Documentation
KKMLVariables::KKMLVariables ()
Definition at line 18 of file KKMLVariables.cpp.
{
}
KKMLVariables::~KKMLVariables ()
Definition at line 24 of file KKMLVariables.cpp.
{
}
Member Function Documentation
void KKMLVariables::SetMachineLearninigHomeDir (const KKStr & _machineLearningHomeDir) [static]
Definition at line 61 of file KKMLVariables.cpp.
References KKB::KKStr::operator=().
{
  machineLearningHomeDir = _machineLearningHomeDir;
}
KKStr KKMLVariables::TempDir () [static]
Directory where we can put temporary files into.
Definition at line 68 of file KKMLVariables.cpp.
References KKB::KKStr::operator+(), and KKB::osAddSlash().
{
  return osAddSlash (MachineLearningHomeDir ()) + "Temp";
}
KKStr KKMLVariables::TrainingLibrariesDir () [static]
Directory where training library directories will be under.
Definition at line 75 of file KKMLVariables.cpp.
References KKB::KKStr::operator+(), and KKB::osAddSlash().
{
  return osAddSlash (MachineLearningHomeDir ()) + "TrainingLibraries";
}
KKStr KKMLVariables::TrainingModelsDir () [static]
Directory where all Training Model Configuration files are stored.
Definition at line 82 of file KKMLVariables.cpp.
References KKB::KKStr::operator+(), and KKB::osAddSlash().
Referenced by KKMLL::TrainingConfiguration2::CreateFromDirectoryStructure(), and KKMLL::TrainingConfiguration2::GetEffectiveConfigFileName().
{
  return osAddSlash (MachineLearningHomeDir ()) + "TrainingModels";
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/KKMLVariables.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/KKMLVariables.cpp