KKMLL::XmlElementFileDesc Class Reference
#include <FileDesc.h>
Public Member Functions
XmlElementFileDesc (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
virtual ~XmlElementFileDesc ()
FileDescPtr TakeOwnership ()
FileDescPtr Value () const
Static Public Member Functions
static void WriteXML (const FileDesc &fileDesc, const KKStr &varName, std::ostream &o)
Additional Inherited Members
Detailed Description
Definition at line 314 of file FileDesc.h.
Constructor & Destructor Documentation
XmlElementFileDesc::XmlElementFileDesc (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log)
Definition at line 925 of file FileDesc.cpp.
References KKMLL::FileDesc::FileDesc(), KKMLL::FileDesc::GetExistingFileDesc(), KKMLL::FileDesc::ReadXML(), and KKB::XmlElement::XmlElement().
                                        :
  XmlElement (tag, s, log),
  value (NULL)
{
  value = new FileDesc ();
  value->ReadXML (s, tag, cancelFlag, log);
  value = FileDesc::GetExistingFileDesc (value);
}
XmlElementFileDesc::~XmlElementFileDesc () [virtual]
Definition at line 940 of file FileDesc.cpp.
{
  // You can not delete an instance of FileDesc.
  value = NULL;
}
Member Function Documentation
FileDescPtr XmlElementFileDesc::TakeOwnership ()
Definition at line 953 of file FileDesc.cpp.
{
  FileDescPtr v = value;
  value = NULL;
  return v;
}
FileDescPtr XmlElementFileDesc::Value () const
Definition at line 947 of file FileDesc.cpp.
Referenced by KKMLL::NormalizationParms::ReadXML(), KKMLL::FeatureEncoder::ReadXML(), SVM289_MFS::Svm_Model::ReadXML(), and KKMLL::SVMModel::ReadXML().
{
  return value;
}
void XmlElementFileDesc::WriteXML (const FileDesc & fileDesc, const KKStr & varName, std::ostream & o) [static]
Definition at line 962 of file FileDesc.cpp.
References KKMLL::FileDesc::WriteXML().
Referenced by KKMLL::NormalizationParms::WriteXML().
{
  fileDesc.WriteXML (varName, o);
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FileDesc.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FileDesc.cpp