KKB::KKStrParser Class Reference
Class that manages the extraction of tokens from a String without being destructive to the original string.
#include <KKStrParser.h>
Public Member Functions
KKStrParser (const KKStrParser &_strParser)
KKStrParser (const char *_str)
KKStrParser (const KKStr &_str)
KKStrParser (KKStr &&_str)
~KKStrParser ()
char GetLastChar ()
char GetNextChar ()
KKStr GetNextToken (const char *delStr=`\n\t\r `)
Extract next Token from string, tokens will be separated by delimiter characters.
bool GetNextTokenBool (const char *delStr=`\n\t\r `)
char GetNextTokenChar (const char *delStr=`\n\t\r `)
KKB::DateTime GetNextTokenDateTime (const char *delStr=`\n\t\r `)
double GetNextTokenDouble (const char *delStr=`\n\t\r `)
float GetNextTokenFloat (const char *delStr=`\n\t\r `)
kkint32 GetNextTokenInt (const char *delStr=`\n\t\r `)
long GetNextTokenLong (const char *delStr=`\n\t\r `)
kkuint32 GetNextTokenUint (const char *delStr=`\n\t\r `)
KKStr GetRestOfLine ()
KKStr GetRestOfStr ()
char LastDelimiter () const
bool MoreTokens () const
char PeekLastChar () const
char PeekNextChar () const
KKStr PeekNextToken (const char *delStr=`\n\t\r `) const
Will use the same rules as `GetNextToken` to retrieve the next token n the string but will not advance the next character pointer.
void Reset ()
void SkipWhiteSpace (const char *whiteSpace=` `)
Advances the next-character pointer to the next NOT white space character.
VectorKKStr Split (const char *delStr=`\n\t\r `)
const char * Str () const
KKStr SubStrPart (kkuint32 firstChar, kkuint32 lastChar) const
void TrimWhiteSpace (const char *_whiteSpace=` `)
After this call all leading and trailing whitespace will be trimmed from tokens.
Detailed Description
Class that manages the extraction of tokens from a String without being destructive to the original string.
Definition at line 18 of file KKStrParser.h.
Constructor & Destructor Documentation
KKStrParser::KKStrParser (const KKStrParser & _strParser)
Definition at line 28 of file KKStrParser.cpp.
References KKStrParser(), and KKB::STRDUP().
Referenced by KKStrParser().
                                                       :
    len ((kkuint32)strlen (_strParser.str)),
    nextPos (_strParser.nextPos),
    str (_strParser.str),
    trimWhiteSpace (_strParser.trimWhiteSpace),
    weOwnStr (false),
    whiteSpace (NULL)
{
  if (_strParser.whiteSpace)
    whiteSpace = STRDUP (_strParser.whiteSpace);
}
KKStrParser::KKStrParser (const char * _str)
Definition at line 54 of file KKStrParser.cpp.
References KKStrParser().
Referenced by KKStrParser(), and KKB::KKStr::ToVectorInt32().
                                          :
    len ((kkuint16)strlen (_str)),
    nextPos (0),
    str (_str),
    trimWhiteSpace (false),
    weOwnStr (false),
    whiteSpace (NULL)
{
}
KKStrParser::KKStrParser (const KKStr & _str)
Definition at line 42 of file KKStrParser.cpp.
References KKB::KKStr::Len(), and KKB::KKStr::Str().
Referenced by KKB::DateTime::DateTime(), KKMLL::MLClassIndexList::ParseClassIndexList(), KKMLL::AttributeTypeVector::ReadXML(), KKB::VectorKKStr::ReadXML(), KKMLL::ClassProbList::ReadXML(), SVM233::SvmModel233::ReadXML(), KKB::KKStrList::ReadXML(), KKB::KKStrListIndexed::ReadXML(), KKB::XmlElementKeyValuePairs::XmlElementKeyValuePairs(), KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList(), and KKB::XmlTag::XmlTag().
                                           :
    len (_str.Len ()),
    nextPos (0),
    str (_str.Str ()),
    trimWhiteSpace (false),
    weOwnStr (false),
    whiteSpace (NULL)
{
}
KKStrParser::KKStrParser (KKStr && _str)
Definition at line 66 of file KKStrParser.cpp.
References KKB::KKStr::Len(), KKB::KKStr::Str(), and KKB::STRDUP().
                                      :
    len (_str.Len ()),
    nextPos (0),
    str (_str.Str ()),
    trimWhiteSpace (false),
    weOwnStr (true),
    whiteSpace (NULL)
{
  str = KKB::STRDUP (_str.Str ());
  weOwnStr = true;
}
KKStrParser::~KKStrParser ()
Definition at line 82 of file KKStrParser.cpp.
{
  delete whiteSpace;
  if (weOwnStr)
  {
    delete str;
    str = NULL;
  }
}
Member Function Documentation
char KKStrParser::GetLastChar ()
Definition at line 350 of file KKStrParser.cpp.
Referenced by KKB::XmlTag::XmlTag().
{
  char lastChar = 0;
  if (nextPos < len)
  {
    --len;
    lastChar = str[len];
  }
  return lastChar;
}
char KKStrParser::GetNextChar ()
Definition at line 337 of file KKStrParser.cpp.
Referenced by KKB::XmlTag::XmlTag().
{
  char nextChar = 0;
  if (nextPos < len)
  {
    nextChar = str[nextPos];
    ++nextPos;
  }
  return nextChar;
}
KKStr KKStrParser::GetNextToken (const char * delStr = `\n\t\r `)
Extract next Token from string, tokens will be separated by delimiter characters.
Removes next Token from string. The token will be terminated by end of string or the first occurrence of a delimiter character. If no more tokens left will return a Empty KKStr. If you want to remove leading and trailing whitespace characters you need to call the `TrimWhiteSpace` method.
Quoted Strings will be treated differently. If the first character in the token is a quote(") or apostrophe(') character then the token will include all characters until the matching quote character. The quote characters will be NOT be included in the token. The next character pointer will be set to the following delimiter character. The quote characters must match. That is if the first quote character was (') then the terminating quote character also be ('). The special escape sequences (`\t`, `\n`, `\r`, `\\`, '"', and `\'` will be translated into (tab), (line-feed), (carriage-return), (back-slash), (quote), and (apostrophe).
Parameters
in delStr List of delimiter characters.
Returns
Extracted Token.
Definition at line 131 of file KKStrParser.cpp.
References KKB::KKStr::Append(), KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), and KKB::KKStr::KKStr().
Referenced by KKB::DateTime::DateTime(), GetNextTokenBool(), GetNextTokenChar(), GetNextTokenDateTime(), GetNextTokenDouble(), GetNextTokenFloat(), GetNextTokenInt(), GetNextTokenLong(), GetNextTokenUint(), KKMLL::MLClassIndexList::ParseClassIndexList(), KKMLL::AttributeTypeVector::ReadXML(), KKB::VectorKKStr::ReadXML(), KKMLL::ClassProbList::ReadXML(), SVM233::SvmModel233::ReadXML(), KKB::KKStrList::ReadXML(), KKB::KKStrListIndexed::ReadXML(), KKB::KKStr::ToVectorInt32(), KKB::XmlElementKeyValuePairs::XmlElementKeyValuePairs(), KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList(), and KKB::XmlTag::XmlTag().
{
  lastDelimiter = 0;
  if (trimWhiteSpace)
  {
    while ((nextPos < len) && (strchr (whiteSpace, str[nextPos]) != NULL))
      nextPos++;
  }
  if (nextPos >= len)
    return KKStr::EmptyStr ();
  kkuint32 startPos = nextPos;
  kkuint32 endPos = startPos;
  char ch = str[endPos];
  if ((ch == '\'') || (ch == '"'))
  {
    KKStr token (30);
    // Token is a string
    char quoteChar = ch;
    // We have a quoted String need to skip to end of quote.
    ++endPos; // Skipped past initial quote character.
    while (endPos < len)
    {
      ch = str[endPos];
      if (ch == quoteChar)
        break;
      if ((ch == '\\') && (endPos < (len - 1)))
      {
        ++endPos;
        char ec = str[endPos];
        switch (ec)
        {
        case '\\': ch = '\\'; break;
        case '"': ch = '"'; break;
        case 'r': ch = '\r'; break;
        case 'n': ch = '\n'; break;
        case 't': ch = '\t'; break;
        }
      }
      token.Append (ch);
      ++endPos;
    }
    if (endPos >= len)
    {
      nextPos = len;
    }
    else
    {
      // Now that we are at the end of the quoted String we need set the next character pointer to just
       past the following delimiter character.
      nextPos = endPos + 1;
      if (trimWhiteSpace)
      {
        while ((nextPos < len) && (strchr (whiteSpace, str[nextPos]) != NULL))
          nextPos++;
      }
      if ((nextPos < len) && (strchr (delStr, str[nextPos]) != NULL))
      {
        lastDelimiter = str[nextPos];
        ++nextPos;
      }
    }
    return token;
  }
  else
  {
    // scan until end of string or next delimiter
    kkuint32 delimeterIdx = 0;
    bool delimeterFound = false;
    while (endPos < len)
    {
      ch = str[endPos];
      if (strchr (delStr, ch) != NULL)
      {
        lastDelimiter = ch;
        delimeterFound = true;
        delimeterIdx = endPos;
        break;
      }
      ++endPos;
    }
    endPos--; // Move endPos back to last character in token.
    if (trimWhiteSpace)
    {
      while ((endPos >= startPos) && (strchr (whiteSpace, str[endPos]) != NULL))
        endPos--;
    }
    if (delimeterFound)
      nextPos = delimeterIdx + 1;
    else if (endPos >= len)
      nextPos = len;
    else
      nextPos = endPos + 1;
    if (trimWhiteSpace)
    {
      while ((nextPos < len) && (strchr (whiteSpace, str[nextPos]) != NULL))
        ++nextPos;
    }
    return KKStr (str, startPos, endPos);
  }
} /* GetNextToken */
bool KKStrParser::GetNextTokenBool (const char * delStr = `\n\t\r `)
Definition at line 438 of file KKStrParser.cpp.
References GetNextToken(), and KKB::KKStr::ToBool().
{
  return GetNextToken (delStr).ToBool ();
}
char KKStrParser::GetNextTokenChar (const char * delStr = `\n\t\r `)
Definition at line 388 of file KKStrParser.cpp.
References KKB::KKStr::Concat(), GetNextToken(), and KKB::KKStr::operator[]().
{
  KKStr nextToken = GetNextToken (delStr);
  char nextTokenChar = nextToken[0];
  return nextTokenChar;
}
KKB::DateTime KKStrParser::GetNextTokenDateTime (const char * delStr = `\n\t\r `)
Definition at line 396 of file KKStrParser.cpp.
References KKB::DateTime::DateTime(), and GetNextToken().
{
  return KKB::DateTime (GetNextToken (delStr));
}
double KKStrParser::GetNextTokenDouble (const char * delStr = `\n\t\r `)
Definition at line 418 of file KKStrParser.cpp.
References GetNextToken(), and KKB::KKStr::ToDouble().
Referenced by KKMLL::ClassProbList::ReadXML(), and SVM233::SvmModel233::ReadXML().
{
  return GetNextToken (delStr).ToDouble ();
}
float KKStrParser::GetNextTokenFloat (const char * delStr = `\n\t\r `)
Definition at line 424 of file KKStrParser.cpp.
References GetNextToken(), and KKB::KKStr::ToFloat().
Referenced by KKMLL::ClassProbList::ReadXML().
{
  return GetNextToken (delStr).ToFloat ();
}
kkint32 KKStrParser::GetNextTokenInt (const char * delStr = `\n\t\r `)
Definition at line 404 of file KKStrParser.cpp.
References GetNextToken(), and KKB::KKStr::ToInt().
Referenced by KKMLL::AttributeTypeVector::ReadXML(), and SVM233::SvmModel233::ReadXML().
{
  return GetNextToken (delStr).ToInt ();
}
long KKStrParser::GetNextTokenLong (const char * delStr = `\n\t\r `)
Definition at line 411 of file KKStrParser.cpp.
References GetNextToken(), and KKB::KKStr::ToLong().
{
  return GetNextToken (delStr).ToLong ();
}
kkuint32 KKStrParser::GetNextTokenUint (const char * delStr = `\n\t\r `)
Definition at line 431 of file KKStrParser.cpp.
References GetNextToken(), and KKB::KKStr::ToUint().
{
  return GetNextToken (delStr).ToUint ();
}
KKStr KKStrParser::GetRestOfLine ()
Definition at line 445 of file KKStrParser.cpp.
References KKB::KKStr::Append(), KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), KKB::KKStr::KKStr(), and KKB::KKStr::TrimRight().
{
  if (trimWhiteSpace)
  {
    while ((nextPos < len) && (strchr (whiteSpace, str[nextPos]) != NULL))
      nextPos++;
  }
  if (nextPos >= len)
    return KKStr::EmptyStr ();
  KKStr result (1 + len - nextPos);
  char lastChar = 0;
  while (nextPos < len)
  {
    lastChar = str[nextPos];
    if (lastChar == '\n')
      break;
    else if (lastChar == '\r')
      break;
    result.Append (lastChar);
    nextPos++;
  }
  if (nextPos < len)
  {
    if (lastChar == '\n')
    {
      if (str[nextPos] == '\r')
        nextPos++;
    }
    else if (lastChar == '\r')
    {
      if (str[nextPos] == '\n')
        nextPos ++;
    }
  }
  if (trimWhiteSpace)
    result.TrimRight (whiteSpace);
  return result;
} /* GetRestOfLine */
KKStr KKStrParser::GetRestOfStr ()
Definition at line 494 of file KKStrParser.cpp.
References KKB::KKStr::Append(), KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), KKB::KKStr::KKStr(), and KKB::KKStr::TrimRight().
Referenced by KKB::DateTime::DateTime().
{
  if (trimWhiteSpace)
  {
    while ((nextPos < len) && (strchr (whiteSpace, str[nextPos]) != NULL))
      nextPos++;
  }
  if (nextPos >= len)
    return KKStr::EmptyStr ();
  KKStr result (1 + len - nextPos);
  while (nextPos < len)
  {
    result.Append (str[nextPos]);
    nextPos++;
  }
  if (trimWhiteSpace)
    result.TrimRight (whiteSpace);
  return result;
} /* GetRestOfStr */
char KKB::KKStrParser::LastDelimiter () const [inline]
Definition at line 72 of file KKStrParser.h.
Referenced by KKMLL::MLClassIndexList::ParseClassIndexList().
{return lastDelimiter;}
bool KKB::KKStrParser::MoreTokens () const [inline]
Definition at line 74 of file KKStrParser.h.
Referenced by KKMLL::MLClassIndexList::ParseClassIndexList(), KKMLL::AttributeTypeVector::ReadXML(), KKB::VectorKKStr::ReadXML(), SVM233::SvmModel233::ReadXML(), KKB::KKStrList::ReadXML(), KKB::KKStrListIndexed::ReadXML(), KKB::XmlElementKeyValuePairs::XmlElementKeyValuePairs(), KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList(), and KKB::XmlTag::XmlTag().
{return (nextPos < len);}
char KKStrParser::PeekLastChar () const
Definition at line 375 of file KKStrParser.cpp.
Referenced by KKB::XmlTag::XmlTag().
{
  char lastChar = 0;
  if (nextPos < len)
  {
    lastChar = str[len - 1];
  }
  return lastChar;
}
char KKStrParser::PeekNextChar () const
Definition at line 363 of file KKStrParser.cpp.
Referenced by KKB::XmlTag::XmlTag().
{
  char nextChar = 0;
  if (nextPos < len)
  {
    nextChar = str[nextPos];
  }
  return nextChar;
}
KKStr KKStrParser::PeekNextToken (const char * delStr = `\n\t\r `) const
Will use the same rules as `GetNextToken` to retrieve the next token n the string but will not advance the next character pointer.
Returns what the next token that 'GetNextToken' will without updating the position in the string buffer.
Allows you to see what the token would be without updating the KKStrParser instance.
Parameters
in delStr List of delimiting characters.
Returns
Next Token to be returned by 'GetNextToken'.
Definition at line 258 of file KKStrParser.cpp.
References KKB::KKStr::Append(), KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), and KKB::KKStr::KKStr().
{
  kkuint32 nextPosP = nextPos;
  if (trimWhiteSpace)
  {
    while ((nextPos < len) && (strchr (whiteSpace, str[nextPosP]) != NULL))
      nextPosP++;
  }
  if (nextPosP >= len)
    return KKStr::EmptyStr ();
  kkuint32 startPos = nextPosP;
  kkuint32 endPos = startPos;
  char ch = str[endPos];
  if ((ch == '\'') || (ch == '"'))
  {
    KKStr token (30);
    // Token is a string
    char quoteChar = ch;
    // We have a quoted String need to skip to end of quote.
    ++endPos;
    while (endPos < len)
    {
      ch = str[endPos];
      if (ch == quoteChar)
      {
        ++endPos;
        break;
      }
      if ((ch == '\\') && (endPos < (len - 1)))
      {
        ++endPos;
        char ec = str[endPos];
        switch (ec)
        {
        case '"': ch = '"'; break;
        case '\\': ch = '\\'; break;
        case 'r': ch = '\r'; break;
        case 'n': ch = '\n'; break;
        case 't': ch = '\t'; break;
        }
      }
      token.Append (ch);
      ++endPos;
    }
    return token;
  }
  else
  {
    // scan until end of string or next delimiter
    while (endPos < len)
    {
      ch = str[endPos];
      if (strchr (delStr, ch) != NULL)
      {
        break;
      }
      ++endPos;
    }
    endPos--; // Move endPos back to last character in token.
    if (trimWhiteSpace)
    {
      while ((endPos >= startPos) && (strchr (whiteSpace, str[endPos]) != NULL))
        endPos--;
    }
    return KKStr (str, startPos, endPos);
  }
} /* PeekNextToken */
void KKStrParser::Reset ()
Definition at line 520 of file KKStrParser.cpp.
{
  nextPos = 0;
}
void KKStrParser::SkipWhiteSpace (const char * whiteSpace = ` `)
Advances the next-character pointer to the next NOT white space character.
Definition at line 111 of file KKStrParser.cpp.
Referenced by TrimWhiteSpace(), and KKB::XmlTag::XmlTag().
{
  while ((nextPos < len) && (strchr (whiteSpace, str[nextPos]) != NULL))
    nextPos++;
} /* SkipWhiteSpce */
VectorKKStr KKStrParser::Split (const char * delStr = `\n\t\r `)
Definition at line 119 of file KKStrParser.cpp.
{
  VectorKKStr tokens;
  while (MoreTokens ())
   tokens.push_back (this->GetNextToken (delStr));
  return tokens;
}
const char* KKB::KKStrParser::Str () const [inline]
Definition at line 96 of file KKStrParser.h.
{return str;}
KKStr KKStrParser::SubStrPart (kkuint32 firstChar, kkuint32 lastChar) const
Definition at line 528 of file KKStrParser.cpp.
References KKB::KKStr::Append(), KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), and KKB::KKStr::KKStr().
{
  if (lastChar < firstChar)
    return KKStr::EmptyStr ();
  kkuint32 subStrLen = (1 + lastChar - firstChar);
  KKStr result (subStrLen + 1);
  if (lastChar >= len)
    lastChar = len - 1;
  kkuint32 idx = 0;
  for (idx = firstChar; idx <= lastChar; idx++)
    result.Append (str[idx]);
  return result;
}
void KKStrParser::TrimWhiteSpace (const char * _whiteSpace = ` `)
After this call all leading and trailing whitespace will be trimmed from tokens.
The next character pointer will be advanced to the next NON whitespace character.
Definition at line 95 of file KKStrParser.cpp.
References SkipWhiteSpace(), and KKB::STRDUP().
Referenced by KKMLL::MLClassIndexList::ParseClassIndexList(), KKMLL::AttributeTypeVector::ReadXML(), KKB::VectorKKStr::ReadXML(), KKMLL::ClassProbList::ReadXML(), SVM233::SvmModel233::ReadXML(), KKB::KKStrList::ReadXML(), KKB::XmlElementKeyValuePairs::XmlElementKeyValuePairs(), KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList(), and KKB::XmlTag::XmlTag().
{
  delete whiteSpace;
  whiteSpace = NULL;
  trimWhiteSpace = true;
  if (_whiteSpace)
    whiteSpace = STRDUP (_whiteSpace);
  else
    whiteSpace = STRDUP (" ");
  SkipWhiteSpace (whiteSpace);
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStrParser.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStrParser.cpp