KKMLL::CrossValidationMxN Class Reference
#include <CrossValidationMxN.h>
Public Member Functions
CrossValidationMxN (TrainingConfiguration2Ptr _comfig, kkuint32 _numOfOrderings, kkuint32 _numOfFolds, FeatureVectorListPtr _data, bool &_cancelFlag, RunLog &_log)
CrossValidationMxN (TrainingConfiguration2Ptr _comfig, OrderingsPtr _data, bool &_cancelFlag, RunLog &_log)
~CrossValidationMxN ()
const VectorFloat & Accuracies () const
float AccuracyMean () const
float AccuracyStdDev () const
const ConfusionMatrix2Ptr ConfussionMatrix () const
kkint32 NumOfFolds () const
kkint32 NumOfOrderings () const
void RunTrainAndTest (kkint32 numExamplsToUseForTraining, RunLog &log)
Will run M number of Train then Test passes.
void RunValidations (RunLog &log)
const VectorFloat & SupportPoints () const
float SupportPointsMean () const
float SupportPointsStdDev () const
double TestTimeMean () const
const VectorDouble & TestTimes () const
double TestTimeStdDev () const
double TrainingTimeMean () const
const VectorDouble & TrainingTimes () const
double TrainingTimeStdDev () const
Detailed Description
Definition at line 69 of file CrossValidationMxN.h.
Constructor & Destructor Documentation
KKMLL::CrossValidationMxN::CrossValidationMxN (TrainingConfiguration2Ptr _comfig, kkuint32 _numOfOrderings, kkuint32 _numOfFolds, FeatureVectorListPtr _data, bool & _cancelFlag, RunLog & _log)
KKMLL::CrossValidationMxN::CrossValidationMxN (TrainingConfiguration2Ptr _comfig, OrderingsPtr _data, bool & _cancelFlag, RunLog & _log)
CrossValidationMxN::~CrossValidationMxN ()
Definition at line 90 of file CrossValidationMxN.cpp.
{
  CleanUpMemory ();
  if (weOwnOrderings)
    delete orderings;
  orderings = NULL;
}
Member Function Documentation
const VectorFloat& KKMLL::CrossValidationMxN::Accuracies () const [inline]
Definition at line 101 of file CrossValidationMxN.h.
{return accuracies;}
float KKMLL::CrossValidationMxN::AccuracyMean () const [inline]
Definition at line 102 of file CrossValidationMxN.h.
{return accuracyMean;}
float KKMLL::CrossValidationMxN::AccuracyStdDev () const [inline]
Definition at line 103 of file CrossValidationMxN.h.
{return accuracyStdDev;}
const ConfusionMatrix2Ptr CrossValidationMxN::ConfussionMatrix () const
Definition at line 254 of file CrossValidationMxN.cpp.
{
  return meanConfusionMatrix;
} /* ConfussionMatrix */
kkint32 KKMLL::CrossValidationMxN::NumOfFolds () const [inline]
Definition at line 99 of file CrossValidationMxN.h.
{return numOfOrderings;}
kkint32 KKMLL::CrossValidationMxN::NumOfOrderings () const [inline]
Definition at line 98 of file CrossValidationMxN.h.
{return numOfOrderings;}
void CrossValidationMxN::RunTrainAndTest (kkint32 numExamplsToUseForTraining, RunLog & log)
Will run M number of Train then Test passes.
Parameters
in numExamplsToUseForTraining The number examples in each ordering(group) that are to be used for training, the remaining examples will be used as test data.
Definition at line 185 of file CrossValidationMxN.cpp.
References KKMLL::ConfusionMatrix2::AddIn(), KKMLL::ConfusionMatrix2::ConfusionMatrix2(), KKMLL::CrossValidation::ConfussionMatrix(), KKMLL::CrossValidation::CrossValidation(), KKMLL::ConfusionMatrix2::FactorCounts(), KKMLL::FeatureVectorList::FeatureVectorList(), KKMLL::Orderings::MLClasses(), KKMLL::Orderings::Ordering(), and KKMLL::CrossValidation::RunValidationOnly().
{
  CleanUpMemory ();
  meanConfusionMatrix = new ConfusionMatrix2 (*(orderings->
      MLClasses ()));
  kkuint32 cvIDX = 0;
  MLClassListPtr mlClasses = orderings->MLClasses ();
  for (cvIDX = 0; cvIDX < numOfOrderings; cvIDX++)
  {
    FeatureVectorListPtr data = orderings->Ordering (cvIDX);
    FeatureVectorList trainingData (fileDesc, false);
    FeatureVectorList testData (fileDesc, false);
    FeatureVectorList::iterator fvIDX;
    for (fvIDX = data->begin (); fvIDX != data->end (); fvIDX++)
    {
      FeatureVectorPtr example = *fvIDX;
      if (trainingData.QueueSize () < numExamplsToUseForTraining)
        trainingData.PushOnBack (example);
      else
        testData.PushOnBack (example);
    }
    CrossValidationPtr cv = new CrossValidation (config,
                                                  &trainingData,
                                                  mlClasses,
                                                  numOfFolds,
                                                  false,
                                                  fileDesc,
                                                  log,
                                                  cancelFlag
                                                 );
    cv->RunValidationOnly (&testData,
                           NULL, // No McNemars test going to be performed.
                           log
                          );
    accuracies.push_back (cv->Accuracy ());
    supportPoints.push_back ((float)cv->NumOfSupportVectors ());
    trainingTimes.push_back (cv->TrainTimeTotal ());
    testTimes.push_back (cv->TestTimeTotal ());
    meanConfusionMatrix->AddIn (*(cv->ConfussionMatrix ()), log);
    delete cv;
  }
  CalcMeanAndStdDev (accuracies, accuracyMean, accuracyStdDev);
  CalcMeanAndStdDev (supportPoints, supportPointsMean, supportPointsStdDev);
  CalcMeanAndStdDev (trainingTimes, trainingTimeMean, trainingTimeStdDev);
  CalcMeanAndStdDev (testTimes, testTimeMean, testTimeStdDev);
  double factor = 1.0 / (double)numOfOrderings;
  meanConfusionMatrix->FactorCounts (factor);
} /* RunTrainAndTest */
void CrossValidationMxN::RunValidations (RunLog & log)
Definition at line 129 of file CrossValidationMxN.cpp.
References KKMLL::ConfusionMatrix2::AddIn(), KKMLL::ConfusionMatrix2::ConfusionMatrix2(), KKMLL::CrossValidation::ConfussionMatrix(), KKMLL::CrossValidation::CrossValidation(), KKMLL::ConfusionMatrix2::FactorCounts(), KKMLL::Orderings::MLClasses(), KKMLL::Orderings::Ordering(), and KKMLL::CrossValidation::RunCrossValidation().
{
  CleanUpMemory ();
  meanConfusionMatrix = new ConfusionMatrix2 (*(orderings->
      MLClasses ()));
  kkuint32 cvIDX = 0;
  MLClassListPtr mlClasses = orderings->MLClasses ();
  for (cvIDX = 0; cvIDX < numOfOrderings; cvIDX++)
  {
    FeatureVectorListPtr data = orderings->Ordering (cvIDX);
    CrossValidationPtr cv = new CrossValidation (config,
                                                  data,
                                                  mlClasses,
                                                  numOfFolds,
                                                  false,
                                                  fileDesc,
                                                  log,
                                                  cancelFlag
                                                 );
    cv->RunCrossValidation (log);
    accuracies.push_back (cv->Accuracy ());
    supportPoints.push_back ((float)cv->NumOfSupportVectors ());
    trainingTimes.push_back (cv->TrainTimeTotal ());
    testTimes.push_back (cv->TestTimeTotal ());
    meanConfusionMatrix->AddIn (*(cv->ConfussionMatrix ()), log);
    delete cv;
  }
  CalcMeanAndStdDev (accuracies, accuracyMean, accuracyStdDev);
  CalcMeanAndStdDev (supportPoints, supportPointsMean, supportPointsStdDev);
  CalcMeanAndStdDev (trainingTimes, trainingTimeMean, trainingTimeStdDev);
  CalcMeanAndStdDev (testTimes, testTimeMean, testTimeStdDev);
  double factor = 1.0 / (double)numOfOrderings;
  meanConfusionMatrix->FactorCounts (factor);
} /* RunValidations */
const VectorFloat& KKMLL::CrossValidationMxN::SupportPoints () const [inline]
Definition at line 105 of file CrossValidationMxN.h.
{return supportPoints;}
float KKMLL::CrossValidationMxN::SupportPointsMean () const [inline]
Definition at line 106 of file CrossValidationMxN.h.
{return supportPointsMean;}
float KKMLL::CrossValidationMxN::SupportPointsStdDev () const [inline]
Definition at line 107 of file CrossValidationMxN.h.
{return supportPointsStdDev;}
double KKMLL::CrossValidationMxN::TestTimeMean () const [inline]
Definition at line 110 of file CrossValidationMxN.h.
{return testTimeMean;}
const VectorDouble& KKMLL::CrossValidationMxN::TestTimes () const [inline]
Definition at line 109 of file CrossValidationMxN.h.
{return testTimes;}
double KKMLL::CrossValidationMxN::TestTimeStdDev () const [inline]
Definition at line 111 of file CrossValidationMxN.h.
{return testTimeStdDev;}
double KKMLL::CrossValidationMxN::TrainingTimeMean () const [inline]
Definition at line 114 of file CrossValidationMxN.h.
{return trainingTimeMean;}
const VectorDouble& KKMLL::CrossValidationMxN::TrainingTimes () const [inline]
Definition at line 113 of file CrossValidationMxN.h.
{return trainingTimes;}
double KKMLL::CrossValidationMxN::TrainingTimeStdDev () const [inline]
Definition at line 115 of file CrossValidationMxN.h.
{return trainingTimeStdDev;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/CrossValidationMxN.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/CrossValidationMxN.cpp