KKB::KKObservable Class Reference
The base class to be used by Observer classes.
#include <KKObservable.h>
Public Types
typedef KKObservable * KKObservablePtr
Public Member Functions
KKObservable ()
virtual ~KKObservable ()
kkint32 MemoryConsumedEstimated ()
virtual void NotifyObservers ()
virtual void RegisterObserver (KKObserverPtr observer)
virtual void UnRegisterObserver (KKObserverPtr observer)
Friends
class KKObserver
Detailed Description
The base class to be used by Observer classes.
Definition at line 25 of file KKObservable.h.
Member Typedef Documentation
typedef KKObservable* KKB::KKObservable::KKObservablePtr
Definition at line 28 of file KKObservable.h.
Constructor & Destructor Documentation
KKObservable::KKObservable ()
Definition at line 29 of file KKObservable.cpp.
{
}
KKObservable::~KKObservable () [virtual]
Definition at line 35 of file KKObservable.cpp.
{
}
Member Function Documentation
kkint32 KKObservable::MemoryConsumedEstimated ()
Definition at line 41 of file KKObservable.cpp.
{
  return sizeof (*this);
}
void KKObservable::NotifyObservers () [virtual]
Definition at line 76 of file KKObservable.cpp.
{
  for (observersIdx = observers.begin (); observersIdx != observers.end (); ++observersIdx)
    observersIdx->first->Notify (this);
}
void KKObservable::RegisterObserver (KKObserverPtr observer) [virtual]
Definition at line 48 of file KKObservable.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
{
  GlobalGoalKeeper::StartBlock ();
  observers.insert (pair<KKObserverPtr,KKObserverPtr>(observer, observer));
  observer->RegisterObservable (this);
  GlobalGoalKeeper::EndBlock ();
} /* RegisterObserver */
void KKObservable::UnRegisterObserver (KKObserverPtr observer) [virtual]
Definition at line 60 of file KKObservable.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKB::KKObserver::~KKObserver().
{
  GlobalGoalKeeper::StartBlock ();
 
  observersIdx = observers.find (observer);
  if (observersIdx != observers.end ())
    observers.erase (observersIdx);
  observer->UnRegisterObservable (this);
  GlobalGoalKeeper::EndBlock ();
} /* RegisterObserver */
Friends And Related Function Documentation
friend class KKObserver [friend]
Definition at line 46 of file KKObservable.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKObservable.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKObservable.cpp