KKMLL::ImageDataTreeEntry Class Reference
#include <ImageFeaturesDataIndexed.h>
Public Member Functions
ImageDataTreeEntry (FeatureVectorPtr _example)
FeatureVectorPtr Example ()
const ImageFeaturesNodeKey & NodeKey () const
Detailed Description
Definition at line 73 of file ImageFeaturesDataIndexed.h.
Constructor & Destructor Documentation
ImageDataTreeEntry::ImageDataTreeEntry (FeatureVectorPtr _example)
Definition at line 81 of file ImageFeaturesDataIndexed.cpp.
References KKMLL::ImageFeaturesNodeKey::ImageFeaturesNodeKey().
Referenced by KKMLL::ImageFeaturesDataIndexed::GetEqual().
                                                                 :
         example (_example),
         nodeKey (_example)
{
}
Member Function Documentation
FeatureVectorPtr KKMLL::ImageDataTreeEntry::Example () [inline]
Definition at line 80 of file ImageFeaturesDataIndexed.h.
Referenced by KKMLL::ImageFeaturesDataIndexed::GetEqual().
{return example;}
const ImageFeaturesNodeKey& KKMLL::ImageDataTreeEntry::NodeKey () const [inline]
Definition at line 78 of file ImageFeaturesDataIndexed.h.
Referenced by KKMLL::ExtractFeatureData::ExtractKey().
{return nodeKey;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ImageFeaturesDataIndexed.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ImageFeaturesDataIndexed.cpp