KKMLL::TrainingConfiguration2List Class Reference
#include <TrainingConfiguration2.h>
Public Member Functions
TrainingConfiguration2List (bool _owner)
~TrainingConfiguration2List ()
TrainingConfiguration2Ptr LookUp (const KKStr &rootName) const
Returns the instance that has the same root name as 'rootName' if none found returns NULL.
Additional Inherited Members
Detailed Description
Definition at line 568 of file TrainingConfiguration2.h.
Constructor & Destructor Documentation
KKMLL::TrainingConfiguration2List::TrainingConfiguration2List (bool _owner) [inline]
Definition at line 571 of file TrainingConfiguration2.h.
References TrainingConfiguration2List().
Referenced by KKMLL::TrainingConfiguration2::TrainingConfiguration2(), and TrainingConfiguration2List().
                                            :
        KKQueue<TrainingConfiguration2> (_owner)
        {}
KKMLL::TrainingConfiguration2List::~TrainingConfiguration2List () [inline]
Definition at line 575 of file TrainingConfiguration2.h.
        {}
Member Function Documentation
TrainingConfiguration2Ptr TrainingConfiguration2List::LookUp (const KKStr & rootName) const
Returns the instance that has the same root name as 'rootName' if none found returns NULL.
Definition at line 2394 of file TrainingConfiguration2.cpp.
References KKB::KKStr::Concat(), KKMLL::TrainingConfiguration2::ConfigRootName(), KKB::KKStr::EqualIgnoreCase(), and KKB::osGetRootName().
{
  KKStr rootName = KKB::osGetRootName (configFileName);
  TrainingConfiguration2List::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    TrainingConfiguration2Ptr c = *idx;
    if (c->ConfigRootName ().EqualIgnoreCase (rootName))
      return c;
  }
  return NULL;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/TrainingConfiguration2.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/TrainingConfiguration2.cpp