KKMLL::FeatureVectorList::ClassNameComparrison Class Reference
Public Member Functions
ClassNameComparrison ()
bool operator() (FeatureVectorPtr p1, FeatureVectorPtr p2)
Detailed Description
Definition at line 2001 of file FeatureVector.cpp.
Constructor & Destructor Documentation
KKMLL::FeatureVectorList::ClassNameComparrison::ClassNameComparrison () [inline]
Definition at line 2004 of file FeatureVector.cpp.
{}
Member Function Documentation
bool KKMLL::FeatureVectorList::ClassNameComparrison::operator() (FeatureVectorPtr p1, FeatureVectorPtr p2) [inline]
Definition at line 2006 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVector::MLClass(), KKB::KKStr::operator<(), KKB::KKStr::operator>(), and KKMLL::MLClass::UpperName().
  {
    if (p1->MLClass () == NULL)
    {
      if (p2->MLClass () != NULL)
        return true;
    }
    else if (p2->MLClass () != NULL)
    {
      const KKStr& n1 = p1->MLClass ()->UpperName ();
      const KKStr& n2 = p2->MLClass ()->UpperName ();
      if (n1 < n2)
        return true;
      else if (n1 > n2)
        return false;
    }
    return p1->ExampleFileName () < p2->ExampleFileName ();
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVector.cpp