KKJobManagment::KKJob Class Reference
#include <KKJob.h>
Public Types
typedef map< KKStr, ConstructorPtr > ConstructorIndex
typedef KKJobPtr(* ConstructorPtr) (JobManagerPtr _manager)
enum JobStatus {
*
jsNULL,
jsOpen,
jsStarted,
jsDone,
*
jsExpanded
 }
enum JobTypes { jtNULL,
jtBinaryCombo,
jtMultiClass,
jtRandomSplit
 }
typedef KKJob * KKJobPtr
Public Member Functions
KKJob (const KKJob &j)
KKJob (JobManagerPtr _manager, kkint32 _jobId, kkint32 _parentId, kkint32 _numPorcessesAllowed, RunLog &_log)
KKJob (JobManagerPtr _manager)
~KKJob ()
void AddPrerequisites (kkint32 _prerequisite)
void AddPrerequisites (VectorInt _prerequisites)
virtual void CompletedJobDataRead (istream &i)
Works with 'WriteCompletedJobData'; You use this to load in data written by 'WriteCompletedJobData'.
virtual void CompletedJobDataWrite (ostream &o)
Write out completed job results to status file.
virtual KKJobPtr Duplicate () const
bool InPrerequisites (kkint32 _jobId)
kkint32 JobId () const
void JobId (kkint32 _jobId)
virtual const char * JobType () const
RunLog & Log ()
JobManagerPtr Manager () const
kkint32 ParentId () const
const VectorInt & Prerequisites () const
virtual void ProcessNode ()
virtual void ProcessStatusField (const KKStr &fieldName, const KKStr &fieldValue)
Imjpelmentation specific field processing.
virtual void ReFresh (KKJob &j)
JobStatus Status () const
void Status (JobStatus _status)
KKStr StatusStr () const
virtual KKStr ToStatusStr ()
Static Public Member Functions
static KKJobPtr CallAppropriateConstructor (JobManagerPtr _manager, const KKStr &_jobTypeName, const KKStr &_statusStr)
static JobStatus JobStatusFromStr (const KKStr &statusStr)
static KKStr JobStatusToStr (JobStatus status)
static void JobTypeFromStr (const KKStr &s)
static KKStr JobTypeToStr (JobTypes jt)
static void RegisterConstructor (const KKStr &_name, ConstructorPtr _constructor)
Public Attributes
RunLog & log
Static Public Attributes
static ConstructorIndex registeredConstructors
Protected Member Functions
void PrerequisitesFromStr (const KKStr &s)
KKStr PrerequisitesToStr () const
void ProcessStatusStr (const KKStr &statusStr)
Protected Attributes
kkint32 jobId
JobManagerPtr manager
kkint32 numPorcessesAllowed
kkint32 numProcessors
kkint32 parentId
VectorInt prerequisites
JobStatus status
Detailed Description
Definition at line 68 of file KKJob.h.
Member Typedef Documentation
typedef map<KKStr, ConstructorPtr> KKJobManagment::KKJob::ConstructorIndex
Definition at line 98 of file KKJob.h.
typedef KKJobPtr(* KKJobManagment::KKJob::ConstructorPtr) (JobManagerPtr _manager)
Definition at line 96 of file KKJob.h.
typedef KKJob* KKJobManagment::KKJob::KKJobPtr
Definition at line 75 of file KKJob.h.
Member Enumeration Documentation
enum KKJobManagment::KKJob::JobStatus
Enumerator
jsNULL
jsOpen
jsStarted
jsDone
jsExpanded
Definition at line 71 of file KKJob.h.
{jsNULL, jsOpen, jsStarted, jsDone, jsExpanded}
      JobStatus;
enum KKJobManagment::KKJob::JobTypes
Enumerator
jtNULL
jtBinaryCombo
jtMultiClass
jtRandomSplit
Definition at line 73 of file KKJob.h.
{jtNULL, jtBinaryCombo, jtMultiClass,
      jtRandomSplit} JobTypes;
Constructor & Destructor Documentation
KKJob::KKJob (const KKJob & j)
Definition at line 42 of file KKJob.cpp.
References jobId, log, manager, numPorcessesAllowed, numProcessors, parentId, prerequisites, and status.
Referenced by Duplicate(), and KKJobManagment::KKJobManager::KKJobManager().
                            :
  log (j.log),
  manager (j.manager),
  jobId (j.jobId),
  parentId (j.parentId),
  numProcessors (j.numProcessors),
  numPorcessesAllowed (j.numPorcessesAllowed),
  prerequisites (j.prerequisites),
  status (j.status)
{
}
KKJobManagment::KKJob::KKJob (JobManagerPtr _manager, kkint32 _jobId, kkint32 _parentId, kkint32 _numPorcessesAllowed, RunLog & _log)
KKJob::KKJob (JobManagerPtr _manager)
Definition at line 82 of file KKJob.cpp.
References jobId, jsNULL, Log(), log, manager, numPorcessesAllowed, numProcessors, parentId, prerequisites, and status.
                                    :
  manager (_manager),
  jobId (-1),
  parentId (-1),
  numProcessors (0),
  numPorcessesAllowed (1),
  prerequisites (),
  status (jsNULL),
  log (_manager->Log ())
{
}
KKJob::~KKJob ()
Definition at line 97 of file KKJob.cpp.
{
}
Member Function Documentation
void KKJobManagment::KKJob::AddPrerequisites (kkint32 _prerequisite)
void KKJobManagment::KKJob::AddPrerequisites (VectorInt _prerequisites)
Referenced by KKJobManagment::KKJobList::AllPrequisitesDone(), KKJobManagment::KKJobList::AreAllJobsDone(), Duplicate(), KKJobManagment::KKJobList::JobsStillRunning(), KKJobManagment::KKJobManager::KKJobManager(), KKJobManagment::KKJobList::LocateOpenJob(), KKJobManagment::KKJobManager::Run(), KKJobManagment::KKJobManager::StatusFileProcessLine(), KKJobManagment::KKJobManager::StatusFileProcessLineJobStatusChange(), and KKJobManagment::KKJobManager::ToStatusStr().
KKJobPtr KKJob::CallAppropriateConstructor (JobManagerPtr _manager, const KKStr & _jobTypeName, const KKStr & _statusStr) [static]
Definition at line 145 of file KKJob.cpp.
References ProcessStatusStr().
Referenced by KKJobManagment::KKJobManager::StatusFileProcessLine().
{
  ConstructorIndex::iterator idx;
  idx = registeredConstructors.find (_jobTypeName);
  if (idx == registeredConstructors.end ())
    return NULL;
  KKJobPtr j = idx->second (_manager);
  j->ProcessStatusStr (_statusStr);
  return j;
} /* CallAppropriateConstructor */
void KKJob::CompletedJobDataRead (istream & i) [virtual]
Works with 'WriteCompletedJobData'; You use this to load in data written by 'WriteCompletedJobData'.
@
Definition at line 351 of file KKJob.cpp.
{
}
void KKJob::CompletedJobDataWrite (ostream & o) [virtual]
Write out completed job results to status file.
This method will get called right after the `KKJob` status line gets written when a KKJob is completed. See 'KKJobManager::GetNextSetOfJobs'. If a job needs to write more data to the Status file then you want to put on a single status line this is where you would do it. You write all the text in a format that you want to support. 'KKJobManager' will bracket it with <KKJob jobtype=`KKJob::JobType,` jobid=`####`> and </KKJob>
 ex:
<RandomSplitJob>
    KKJob Data;
    KKJob Data,
    etc. etc. etc.
</RandomSplitJob>
Definition at line 344 of file KKJob.cpp.
{
}
KKJobPtr KKJob::Duplicate () const [virtual]
Create a duplicate instance.
Reimplemented in KKJobManagment::KKJobManager.
Definition at line 112 of file KKJob.cpp.
References AddPrerequisites(), and KKJob().
Referenced by KKJobManagment::KKJobManager::Run().
{
  return new KKJob (*this);
}
bool KKJobManagment::KKJob::InPrerequisites (kkint32 _jobId)
kkint32 KKJobManagment::KKJob::JobId () const [inline]
Definition at line 118 of file KKJob.h.
References jobId.
Referenced by KKJobManagment::KKJobManager::StatusFileProcessLine().
{return jobId;}
void KKJobManagment::KKJob::JobId (kkint32 _jobId) [inline]
Definition at line 126 of file KKJob.h.
References jobId.
{jobId = _jobId;}
KKJob::JobStatus KKJob::JobStatusFromStr (const KKStr & statusStr) [static]
Definition at line 198 of file KKJob.cpp.
References KKB::KKStr::CompareIgnoreCase(), jsDone, jsExpanded, jsNULL, jsOpen, and jsStarted.
Referenced by KKJobManagment::KKJobManager::StatusFileProcessLine(), and KKJobManagment::KKJobManager::StatusFileProcessLineJobStatusChange().
{
  if (statusStr.CompareIgnoreCase ("OPEN") == 0)
    return jsOpen;
  if (statusStr.CompareIgnoreCase ("STARTED") == 0)
    return jsStarted;
  if (statusStr.CompareIgnoreCase ("DONE") == 0)
    return jsDone;
  if (statusStr.CompareIgnoreCase ("Expanded") == 0)
    return jsExpanded;
  return jsNULL;
} /* JobStatusToStr */
KKStr KKJob::JobStatusToStr (JobStatus status) [static]
Definition at line 178 of file KKJob.cpp.
References jsDone, jsExpanded, jsOpen, and jsStarted.
Referenced by StatusStr(), and KKJobManagment::KKJobManager::ToStatusStr().
{
  if (status == jsOpen)
    return "Open";
  if (status == jsStarted)
    return "Started";
  if (status == jsDone)
    return "Done";
  if (status == jsExpanded)
    return "Expanded";
  return "";
} /* JobStatusToStr */
const char * KKJob::JobType () const [virtual]
This will allow us to know which specific implementaion of 'KKJob' an instance really is.
Reimplemented in KKJobManagment::KKJobManager.
Definition at line 104 of file KKJob.cpp.
{
  return "KKJob";
}
static void KKJobManagment::KKJob::JobTypeFromStr (const KKStr & s) [static]
static KKStr KKJobManagment::KKJob::JobTypeToStr (JobTypes jt) [static]
RunLog& KKJobManagment::KKJob::Log () [inline]
Definition at line 122 of file KKJob.h.
References log.
Referenced by KKJob(), and KKJobManagment::KKJobList::KKJobList().
{return log;}
JobManagerPtr KKJobManagment::KKJob::Manager () const [inline]
Definition at line 120 of file KKJob.h.
References manager.
{return manager;}
kkint32 KKJobManagment::KKJob::ParentId () const [inline]
Definition at line 119 of file KKJob.h.
References parentId.
{return parentId;}
const VectorInt& KKJobManagment::KKJob::Prerequisites () const [inline]
Definition at line 121 of file KKJob.h.
References prerequisites.
Referenced by KKJobManagment::KKJobList::AllPrequisitesDone().
{return prerequisites;}
void KKJob::PrerequisitesFromStr (const KKStr & s) [protected]
Definition at line 243 of file KKJob.cpp.
References KKB::KKStr::CompareIgnoreCase(), and KKB::KKStr::Split().
{
  prerequisites.clear ();
  if (s.CompareIgnoreCase ("None") != 0)
  {
    VectorKKStr fields = s.Split (',');
    for (kkuint32 x = 0; x < fields.size (); ++x)
    {
      kkint32 p = fields[x].ToInt ();
      prerequisites.push_back (p);
    }
  }
} /* PrerequisitesFromStr */
KKStr KKJob::PrerequisitesToStr () const [protected]
Definition at line 225 of file KKJob.cpp.
References KKB::KKStr::Concat().
Referenced by ToStatusStr().
{
  if (prerequisites.size () < 1)
    return "None";
  KKStr s (5 + prerequisites.size () * 5);
  for (kkuint32 x = 0; x < prerequisites.size (); ++x)
  {
    if (x > 0)
      s << ",";
    s << prerequisites[x];
  }
  return s;
} /* PrerequisitesToStr */
void KKJob::ProcessNode () [virtual]
Definition at line 119 of file KKJob.cpp.
References KKB::KKException::KKException().
Referenced by KKJobManagment::KKJobManager::Run().
{
  // This metjod should have been overridden by a derived class; if we end up here then
  // no actual work will get done.
  throw KKException ("KKJob::ProcessNode ***ERROR*** ProcessNode was not defined
       bydecendent class.");
}
void KKJob::ProcessStatusField (const KKStr & fieldName, const KKStr & fieldValue) [virtual]
Imjpelmentation specific field processing.
Any SubClass of KKJob needs to define this method. Whenever the 'ProcessStatusStr' method can not identify a field it will call this method to let the child Class process the field.
Definition at line 334 of file KKJob.cpp.
{
   log.Level (-1) << "KKJob::ProcessStatusField Invalid Field Name[" << fieldName << "]." <<
      endl;
} /* ProcessStatusField */
void KKJob::ProcessStatusStr (const KKStr & statusStr) [protected]
Definition at line 278 of file KKJob.cpp.
References KKB::KKStr::Concat(), and KKB::KKStr::Split().
Referenced by CallAppropriateConstructor().
{
  log.Level (30) << "KKJob::ProcessStatusStr[" << statusStr << "]" <<
      endl;
  KKStr fieldName;
  KKStr fieldValue;
  VectorKKStr fields = statusStr.Split ('\t');
  kkuint32 fieldNum = 0;
  while (fieldNum < fields.size ())
  {
    fieldName = fields[fieldNum];
    fieldNum++;
    if (fieldNum < fields.size ())
    {
      fieldValue = fields[fieldNum];
      fieldNum++;
    }
    else
    {
      fieldValue = "";
    }
    fieldName.Upper ();
    fieldValue.TrimLeft ("\n\r\t ");
    fieldValue.TrimRight ("\n\r\t ");
    if (fieldName.CompareIgnoreCase ("JOBID") == 0)
      jobId = atoi (fieldValue.Str ());
    else if (fieldName.CompareIgnoreCase ("PARENTID") == 0)
      parentId = atoi (fieldValue.Str ());
    else if (fieldName.CompareIgnoreCase ("STATUS") == 0)
      status = JobStatusFromStr (fieldValue);
   
    else if (fieldName.CompareIgnoreCase ("NumProcessors") == 0)
      numProcessors = fieldValue.ToInt ();
    else if (fieldName.CompareIgnoreCase ("NumPorcessesAllowed") == 0)
      numPorcessesAllowed = fieldValue.ToInt ();
    else if (fieldName.CompareIgnoreCase ("Prerequisites") == 0)
      PrerequisitesFromStr (fieldValue);
      
    else
    {
      ProcessStatusField (fieldName, fieldValue);
    }
  }
} /* ProcessStatusStr */
void KKJob::ReFresh (KKJob & j) [virtual]
Definition at line 163 of file KKJob.cpp.
References jobId, manager, numPorcessesAllowed, numProcessors, parentId, prerequisites, and status.
Referenced by KKJobManagment::KKJobManager::StatusFileProcessLine().
{
  jobId = j.jobId;
  parentId = j.parentId;
  manager = j.manager;
  status = j.status;
  numProcessors = j.numProcessors;
  numPorcessesAllowed = j.numPorcessesAllowed;
  prerequisites = j.prerequisites;
  status = j.status;
} /* ReFresh */
void KKJob::RegisterConstructor (const KKStr & _name, ConstructorPtr _constructor) [static]
Definition at line 135 of file KKJob.cpp.
{
  registeredConstructors.insert (pair<KKStr, ConstructorPtr>(_name, _constructor));
}
JobStatus KKJobManagment::KKJob::Status () const [inline]
Definition at line 123 of file KKJob.h.
References status.
Referenced by KKJobManagment::KKJobList::AllPrequisitesDone(), KKJobManagment::KKJobList::AreAllJobsDone(), KKJobManagment::KKJobList::JobsStillRunning(), and KKJobManagment::KKJobList::LocateOpenJob().
{return status;}
void KKJobManagment::KKJob::Status (JobStatus _status) [inline]
Definition at line 127 of file KKJob.h.
References status.
Referenced by KKJobManagment::KKJobManager::StatusFileProcessLineJobStatusChange().
{status = _status;}
KKStr KKJob::StatusStr () const
Definition at line 218 of file KKJob.cpp.
References JobStatusToStr(), and status.
Referenced by ToStatusStr().
{
  return JobStatusToStr (status);
} /* StatusStr */
KKStr KKJob::ToStatusStr () [virtual]
Any derived classes that implement this method must call its base class version 1st.
Reimplemented in KKJobManagment::KKJobManager.
Definition at line 261 of file KKJob.cpp.
References KKB::KKStr::Concat(), jobId, KKB::KKStr::KKStr(), numPorcessesAllowed, numProcessors, parentId, PrerequisitesToStr(), and StatusStr().
Referenced by KKJobManagment::KKJobManager::ToStatusStr().
{
  KKStr statusStr (200); // Preallocating 200 bytes.
  statusStr << "JobId" << "\t" << jobId << "\t"
            << "ParentId" << "\t" << parentId << "\t"
            << "Status" << "\t" << StatusStr () << "\t"
            << "NumProcessors" << "\t" << numProcessors << "\t"
            << "NumPorcessesAllowed" << "\t" << numPorcessesAllowed << "\t"
            << "Prerequisites" << "\t" << PrerequisitesToStr ();
  return statusStr;
} /* ToStatusStr */
Member Data Documentation
kkint32 KKJobManagment::KKJob::jobId [protected]
Definition at line 209 of file KKJob.h.
Referenced by JobId(), KKJob(), ReFresh(), and ToStatusStr().
RunLog& KKJobManagment::KKJob::log
Definition at line 200 of file KKJob.h.
Referenced by KKJob(), and Log().
JobManagerPtr KKJobManagment::KKJob::manager [protected]
Definition at line 211 of file KKJob.h.
Referenced by KKJob(), Manager(), and ReFresh().
kkint32 KKJobManagment::KKJob::numPorcessesAllowed [protected]
The number of Processes that are allowd to process at same time. that is ('numPorcessesAllowed' <= 'numActiveProcessors').
Definition at line 216 of file KKJob.h.
Referenced by KKJob(), ReFresh(), and ToStatusStr().
kkint32 KKJobManagment::KKJob::numProcessors [protected]
Number of CPU's that are currently processing this node; That is the number that are currently calling the 'ProcessNode' method.
Definition at line 212 of file KKJob.h.
Referenced by KKJob(), ReFresh(), and ToStatusStr().
kkint32 KKJobManagment::KKJob::parentId [protected]
Definition at line 210 of file KKJob.h.
Referenced by KKJob(), ParentId(), ReFresh(), and ToStatusStr().
VectorInt KKJobManagment::KKJob::prerequisites [protected]
List of JobId's that must complete (jobStatus == jsDone) before this process may be started.
Definition at line 220 of file KKJob.h.
Referenced by KKJob(), Prerequisites(), and ReFresh().
map< KKStr, KKJob::ConstructorPtr > KKJob::registeredConstructors [static]
Track all the different constructors. Will be used to know wich constructor to use when reading the status file.
Definition at line 100 of file KKJob.h.
JobStatus KKJobManagment::KKJob::status [protected]
Definition at line 224 of file KKJob.h.
Referenced by KKJob(), ReFresh(), KKJobManagment::KKJobManager::Run(), Status(), KKJobManagment::KKJobManager::StatusFileProcessLine(), StatusStr(), KKJobManagment::KKJobManager::ToStatusStr(), and KKJobManagment::KKJobManager::Update().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/JobManager/KKJob.h
C:/Users/Kurt/GitHub/KSquareLibraries/JobManager/KKJob.cpp