SVM289_BFS::Cache Class Reference
Public Member Functions
Cache (kkint32 l, kkint32 size)
Kernel Cache.
~Cache ()
kkint32 get_data (const kkint32 index, Qfloat **data, kkint32 len)
Request data [0,len)
void swap_index (kkint32 i, kkint32 j)
Detailed Description
Definition at line 649 of file svm289_BFS.cpp.
Constructor & Destructor Documentation
SVM289_BFS::Cache::Cache (kkint32 l, kkint32 size)
Kernel Cache.
Parameters
in l The number of total data items.
in size The cache size limit in bytes
Definition at line 698 of file svm289_BFS.cpp.
Referenced by SVM289_BFS::ONE_CLASS_Q::ONE_CLASS_Q(), SVM289_BFS::SVC_Q::SVC_Q(), and SVM289_BFS::SVR_Q::SVR_Q().
                          :
      l (l_),
      size (size_)
{
  head = (head_t *)calloc (l, sizeof (head_t)); // initialized to 0
  size /= sizeof (Qfloat);
  size -= l * sizeof (head_t) / sizeof (Qfloat);
  size = Max (size, 2 * (kkint32) l); // cache must be large enough for two columns
  lru_head.next = lru_head.prev = &lru_head;
}
SVM289_BFS::Cache::~Cache ()
Definition at line 713 of file svm289_BFS.cpp.
{
  for (head_t* h = lru_head.next; h != &lru_head; h = h->next)
  {delete (h->data); h->data = NULL;}
  delete head; head = NULL;
}
Member Function Documentation
kkint32 Cache::get_data (const kkint32 index, Qfloat ** data, kkint32 len)
Request data [0,len)
Return some position p where [p,len) need to be filled (p >= len if nothing needs to be filled)
Definition at line 742 of file svm289_BFS.cpp.
Referenced by SVM289_BFS::SVC_Q::get_Q(), SVM289_BFS::ONE_CLASS_Q::get_Q(), and SVM289_BFS::SVR_Q::get_Q().
{
  head_t* h = &head[index];
  if (h->len)
    lru_delete (h);
  kkint32 more = len - h->len;
  if (more > 0)
  {
    // free old space
    while (size < more)
    {
      head_t* old = lru_head.next;
      lru_delete (old);
      delete old->data; old->data = NULL;
      size += old->len;
      old->data = 0;
      old->len = 0;
    }
    // allocate new space
    h->data = (Qfloat *)realloc(h->data, sizeof (Qfloat) * len);
    size -= more;
    SVM289_BFS::swap (h->len, len);
  }
  lru_insert (h);
  *data = h->data;
  return len;
}
void Cache::swap_index (kkint32 i, kkint32 j)
Definition at line 779 of file svm289_BFS.cpp.
Referenced by SVM289_BFS::SVC_Q::swap_index(), and SVM289_BFS::ONE_CLASS_Q::swap_index().
{
  if (i == j)
    return;
  if (head[i].len)
    lru_delete (&head[i]);
  if (head[j].len)
    lru_delete(&head[j]);
  SVM289_BFS::swap (head[i].data, head[j].data);
  SVM289_BFS::swap (head[i].len, head[j].len);
  if (head[i].len)
    lru_insert(&head[i]);
  if (head[j].len)
    lru_insert(&head[j]);
  if (i > j)
    SVM289_BFS::swap(i, j);
  for (head_t* h = lru_head.next; h != &lru_head; h = h->next)
  {
    if (h->len > i)
    {
      if (h->len > j)
      {
        SVM289_BFS::swap (h->data[i], h->data[j]);
      }
      else
      {
        // give up
        lru_delete (h);
        delete h->data; h->data = NULL;
        size += h->len;
        h->data = 0;
        h->len = 0;
      }
    }
  }
} /* swap_index */
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm289_BFS.cpp