KKB::DateTime Class Reference
#include <DateTime.h>
Public Member Functions
DateTime ()
DateTime (const DateTime &dateTime)
DateTime (const DateType &_date, const TimeType &_time)
DateTime (short _year, uchar _month, uchar _day, uchar _hour, uchar _minute, uchar _second)
DateTime (const KKStr &s)
void AddDays (kkint32 _days)
void AddHours (kkint32 _hours)
void AddMinutes (kkint32 _mins)
void AddSeconds (long _secs)
const KKB::DateType & Date () const
uchar Day () const
KKStr HH_MM_SS () const
void HoursAdd (kkint32 hours)
Add _hours to DateTime, will adjust date to accommodate 24 hour clock.
void MinutesAdd (kkint32 _mins)
uchar Month () const
bool operator!= (const DateTime &right) const
DateTime operator+ (const DateTime &right) const
DateTime operator- (const DateTime &right) const
bool operator< (const DateTime &right) const
bool operator<= (const DateTime &right) const
DateTime & operator= (const DateTime &right)
bool operator== (const DateTime &right) const
bool operator> (const DateTime &right) const
bool operator>= (const DateTime &right) const
kkuint64 Seconds () const
void SecondsAdd (long _secs)
const TimeType & Time () const
kkuint32 ToDays () const
double ToHours () const
summary>Number seconds since `0000/01/01 00:00:00`
kkuint64 ToSeconds () const
short Year () const
KKStr YYYY_MM_DD_HH_MM_SS () const
KKStr YYYYMMDDHHMMSS () const
Detailed Description
Definition at line 204 of file DateTime.h.
Constructor & Destructor Documentation
DateTime::DateTime ()
Definition at line 997 of file DateTime.cpp.
References KKB::DateType::DateType(), and KKB::TimeType::TimeType().
Referenced by KKB::XmlAttributeList::AttributeValueDateTime(), KKMLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), KKMLL::FeatureFileIO::FeatureDataReSink(), and KKB::XmlElementDateTime::XmlElementDateTime().
                   :
      date(),
      time ()
{}
DateTime::DateTime (const DateTime & dateTime)
Definition at line 1006 of file DateTime.cpp.
References KKB::DateType::DateType(), and KKB::TimeType::TimeType().
Referenced by KKMLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), and KKJobManagment::KKJobManager::KKJobManager().
                                            :
       date (dateTime.date),
       time (dateTime.time)
{}
DateTime::DateTime (const DateType & _date, const TimeType & _time)
Definition at line 1016 of file DateTime.cpp.
References KKB::DateType::DateType(), and KKB::TimeType::TimeType().
Referenced by operator+(), and operator-().
                    :
       date (_date),
       time (_time)
{}
DateTime::DateTime (short _year, uchar _month, uchar _day, uchar _hour, uchar _minute, uchar _second)
Definition at line 1028 of file DateTime.cpp.
References KKB::DateType::DateType(), and KKB::TimeType::TimeType().
Referenced by KKMLL::TrainingProcess2::TrainingProcess2().
                    :
      date (_year, _month, _day),
      time (_hour, _minute, _second)
{}
DateTime::DateTime (const KKStr & s)
Definition at line 1043 of file DateTime.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::CountInstancesOf(), KKB::DateType::DateType(), KKB::KKStr::Empty(), KKB::KKStrParser::GetNextToken(), KKB::KKStrParser::GetRestOfStr(), KKB::KKStrParser::KKStrParser(), KKB::KKStr::operator+(), KKB::DateType::operator=(), KKB::TimeType::operator=(), and KKB::TimeType::TimeType().
Referenced by KKB::XmlAttributeList::AttributeValueDateTime(), KKB::KKStrParser::GetNextTokenDateTime(), and KKJobManagment::KKJobManager::StatusFileProcessLine().
                                  :
      date(),
      time ()
{
  if (s.Empty ())
    return;
  KKStrParser parser (s);
  if ((s.CountInstancesOf ('-') > 2) && (s.CountInstancesOf ('/') < 1))
  {
    // Looks like the date part is broken up by '-' not '/'
    KKStr datePart1 = parser.GetNextToken ("- ");
    KKStr datePart2 = parser.GetNextToken ("- ");
    KKStr datePart3 = parser.GetNextToken ("- ");
    KKStr timeStr = parser.GetRestOfStr ();
    KKStr dateStr = datePart1 + "/" + datePart2 + "/" + datePart3;
    date = DateType (dateStr);
    time = TimeType (timeStr);
  }
  else
  {
    KKStr field1 = parser.GetNextToken ("- ");
    KKStr field2 = parser.GetNextToken ("- ");
    date = DateType (field1);
    time = TimeType (field2);
  }
}
Member Function Documentation
void DateTime::AddDays (kkint32 _days)
Definition at line 1108 of file DateTime.cpp.
References KKB::DateType::AddDays().
{
  date.AddDays (_days);
}
void DateTime::AddHours (kkint32 _hours)
Definition at line 1114 of file DateTime.cpp.
References KKB::TimeType::Hour(), KKB::DateType::operator+(), KKB::DateType::operator-(), and KKB::DateType::operator=().
Referenced by HoursAdd().
{
  if (_hours < 0)
  {
    kkint32 newHour = time.Hour () + _hours;
    while (newHour < 0)
    {
      date = date - 1;
      newHour += 24;
    }
    time.Hour ((uchar)newHour);
  }
  else
  {
    kkint32 newHour = time.Hour () + _hours;
    while (newHour > 23)
    {
      date = date + 1;
      newHour -= 24;
    }
    time.Hour ((uchar)newHour);
  }
} /* AddHours */
void DateTime::AddMinutes (kkint32 _mins)
Definition at line 1139 of file DateTime.cpp.
References HoursAdd(), and KKB::TimeType::Minute().
Referenced by MinutesAdd().
{
  kkint32 newMins = time.Minute () + _mins;
  while (newMins < 0)
  {
    HoursAdd (-1);
    newMins += 60;
  }
  while (newMins >= 60)
  {
    HoursAdd (1);
    newMins -= 60;
  }
  time.Minute ((uchar)newMins);
} /* AddMinutes */
void DateTime::AddSeconds (long _secs)
Definition at line 1159 of file DateTime.cpp.
References MinutesAdd(), and KKB::TimeType::Second().
Referenced by SecondsAdd().
{
  long newSecs = time.Second () + _secs;
  long minsToAdd = newSecs / 60;
  newSecs = newSecs - (minsToAdd * 60);
  if (minsToAdd != 0)
    MinutesAdd (minsToAdd);
  while (newSecs < 0)
  {
    MinutesAdd (-1);
    newSecs += 60;
  }
  while (newSecs >= 60)
  {
    MinutesAdd (1);
    newSecs -= 60;
  }
  time.Second ((uchar)newSecs);
} /* AddSeconds */
const KKB::DateType& KKB::DateTime::Date () const [inline]
Definition at line 230 of file DateTime.h.
Referenced by KKB::operator<<().
{return date;}
uchar KKB::DateTime::Day () const [inline]
Definition at line 238 of file DateTime.h.
References KKB::DateType::Day().
{return date.Day ();}
KKStr DateTime::HH_MM_SS () const
The date part will be converted into hours.
Definition at line 1222 of file DateTime.cpp.
References KKB::TimeType::Hour(), KKB::TimeType::Minute(), KKB::KKStr::operator+(), KKB::TimeType::Second(), KKB::StrFormatInt(), and KKB::DateType::ToHours().
{
  return StrFormatInt ((date.ToHours () + time.Hour ()), "###00") + ":" +
          StrFormatInt (time.Minute (), "00") + ":" +
          StrFormatInt (time.Second (), "00");
}
void DateTime::HoursAdd (kkint32 hours)
Add _hours to DateTime, will adjust date to accommodate 24 hour clock.
Definition at line 1186 of file DateTime.cpp.
References AddHours().
Referenced by AddMinutes().
{
  AddHours (_hours);
} /* HoursAdd */
void DateTime::MinutesAdd (kkint32 _mins)
Definition at line 1194 of file DateTime.cpp.
References AddMinutes().
Referenced by AddSeconds().
{
  AddMinutes (_mins);
} /* MinutesAdd */
uchar KKB::DateTime::Month () const [inline]
Definition at line 237 of file DateTime.h.
References KKB::DateType::Month().
{return date.Month ();}
bool DateTime::operator!= (const DateTime & right) const
Definition at line 1248 of file DateTime.cpp.
{
  return Compare (right) != 0;
}
DateTime DateTime::operator+ (const DateTime & right) const
Definition at line 1281 of file DateTime.cpp.
References DateTime(), KKB::DateType::DateType(), KKB::DateType::Days(), KKB::TimeType::Seconds(), and KKB::TimeType::TimeType().
{
  kkint32 netDays = date.Days () + right.date.Days ();
  kkint32 netSecs = time.Seconds () + right.time.Seconds ();
  netSecs = netSecs % 86400;
  return DateTime (DateType (netDays), TimeType (netSecs));
}
DateTime DateTime::operator- (const DateTime & right) const
Definition at line 1293 of file DateTime.cpp.
References DateTime(), KKB::DateType::DateType(), KKB::DateType::Days(), KKB::TimeType::Seconds(), and KKB::TimeType::TimeType().
{
  kkint32 netDays = date.Days () - right.date.Days ();
  kkint32 leftSecs = time.Seconds ();
  kkint32 rightSecs = right.time.Seconds ();
  while (rightSecs > leftSecs)
  {
    netDays--;
    leftSecs = leftSecs + 86400;
  }
  kkint32 netSecs = leftSecs - rightSecs;
  kkint32 numOfDaysInSecs = netSecs / 86400;
  netSecs = netSecs % 86400;
  return DateTime (DateType (netDays + numOfDaysInSecs),
      TimeType (netSecs));
}
bool DateTime::operator< (const DateTime & right) const
Definition at line 1268 of file DateTime.cpp.
Referenced by KKMLL::TrainingProcess2::CreateTrainingProcess().
{
  return Compare (right) < 0;
}
bool DateTime::operator<= (const DateTime & right) const
Definition at line 1274 of file DateTime.cpp.
{
  return Compare (right) <= 0;
}
DateTime & DateTime::operator= (const DateTime & right)
Definition at line 1231 of file DateTime.cpp.
References KKB::DateType::operator=(), and KKB::TimeType::operator=().
Referenced by KKMLL::TrainingProcess2::CreateModelsFromTrainingData(), KKMLL::TrainingProcess2::ExtractTrainingClassFeatures(), KKMLL::FeatureFileIO::FeatureDataReSink(), KKMLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), KKMLL::TrainingProcess2::ReadXML(), KKJobManagment::KKJobManager::StatusFileProcessLine(), and KKB::XmlElementDateTime::XmlElementDateTime().
{
  date = right.date;
  time = right.time;
  return *this;
}
bool DateTime::operator== (const DateTime & right) const
Definition at line 1241 of file DateTime.cpp.
{
  return Compare (right) == 0;
}
bool DateTime::operator> (const DateTime & right) const
Definition at line 1255 of file DateTime.cpp.
Referenced by KKMLL::TrainingProcess2::ExtractTrainingClassFeatures(), and KKMLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries().
{
  return Compare (right) > 0;
}
bool DateTime::operator>= (const DateTime & right) const
Definition at line 1262 of file DateTime.cpp.
{
  return Compare (right) >= 0;
}
kkuint64 DateTime::Seconds () const
Definition at line 1092 of file DateTime.cpp.
References KKB::DateType::Seconds(), and KKB::TimeType::Seconds().
Referenced by KKB::XmlElementDateTime::ToBool(), KKB::XmlElementDateTime::ToDouble(), KKB::XmlElementDateTime::ToFloat(), and KKB::KKThread::WaitForThreadToStop().
{
  kkuint64 secsInDate = (kkuint64)date.Seconds ();
  kkuint64 secsInTime = (kkuint64)time.Seconds ();
  return secsInDate + secsInTime;
}
void DateTime::SecondsAdd (long _secs)
Definition at line 1202 of file DateTime.cpp.
References AddSeconds().
{
  AddSeconds (_secs);
} /* SecondsAdd */
const TimeType& KKB::DateTime::Time () const [inline]
Definition at line 232 of file DateTime.h.
Referenced by KKB::KKThread::AddMsg(), and KKB::operator<<().
{return time;}
kkuint32 DateTime::ToDays () const
Definition at line 1100 of file DateTime.cpp.
References KKB::DateType::Days().
Referenced by KKB::XmlElementDateTime::ToInt32().
{return date.Days ();}
double DateTime::ToHours () const
summary>Number seconds since `0000/01/01 00:00:00`
Definition at line 1101 of file DateTime.cpp.
References KKB::DateType::Days(), and KKB::TimeType::ToHours().
kkuint64 DateTime::ToSeconds () const
Number seconds since `0000/01/01 00:00:00`
Definition at line 1105 of file DateTime.cpp.
References KKB::DateType::Days(), and KKB::TimeType::Seconds().
{return (kkuint64)(date.Days ()) * (kkuint64)86400 + time.
      Seconds ();};
short KKB::DateTime::Year () const [inline]
Definition at line 236 of file DateTime.h.
References KKB::DateType::Year().
{return date.Year ();}
KKStr DateTime::YYYY_MM_DD_HH_MM_SS () const
Definition at line 1216 of file DateTime.cpp.
References KKB::TimeType::HH_MM_SS(), KKB::KKStr::operator+(), and KKB::DateType::YYYY_MM_DD().
Referenced by KKB::XmlElementKeyValuePairs::Add(), KKB::XmlElementDateTime::ToKKStr(), KKMLL::Model::WriteModelXMLFields(), and KKB::XmlElementDateTime::WriteXML().
{
  return date.YYYY_MM_DD () + "-" + time.HH_MM_SS ();
}
KKStr DateTime::YYYYMMDDHHMMSS () const
Definition at line 1209 of file DateTime.cpp.
References KKB::TimeType::HHMMSS(), KKB::KKStr::operator+(), and KKB::DateType::YYYYMMDD().
{
  return date.YYYYMMDD () + time.HHMMSS ();
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/DateTime.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/DateTime.cpp