SVM233::Cache Class Reference
Public Member Functions
Cache (kkint32 l, kkint32 size)
~Cache ()
kkint32 get_data (const kkint32 index, Qfloat **data, kkint32 len)
void swap_index (kkint32 i, kkint32 j)
Detailed Description
Definition at line 1361 of file svm.cpp.
Constructor & Destructor Documentation
SVM233::Cache::Cache (kkint32 l, kkint32 size)
Definition at line 1400 of file svm.cpp.
Referenced by SVM233::ONE_CLASS_Q::ONE_CLASS_Q(), SVM233::SVC_Q::SVC_Q(), and SVM233::SVR_Q::SVR_Q().
                      :
l (l_),
size (size_)
{
  head = (head_t *)calloc (l, sizeof (head_t)); // initialized to 0
  size /= sizeof (Qfloat);
  size -= l * sizeof (head_t) / sizeof (Qfloat);
  lru_head.next = lru_head.prev = &lru_head;
}
SVM233::Cache::~Cache ()
Definition at line 1416 of file svm.cpp.
{
  for (head_t *h = lru_head.next; h != &lru_head; h = h->next)
    free(h->data);
  free(head);
}
Member Function Documentation
kkint32 SVM233::Cache::get_data (const kkint32 index, Qfloat ** data, kkint32 len)
Definition at line 1445 of file svm.cpp.
Referenced by SVM233::SVC_Q::get_Q(), SVM233::ONE_CLASS_Q::get_Q(), and SVM233::SVR_Q::get_Q().
{
  head_t *h = &head[index];
  if (h->len)
    lru_delete(h);
  kkint32 more = len - h->len;
  if (more > 0)
  {
    // free old space
    while(size < more)
    {
      head_t *old = lru_head.next;
      lru_delete(old);
      free(old->data);
      size += old->len;
      old->data = 0;
      old->len = 0;
    }
    // allocate new space
    h->data = (Qfloat *)realloc(h->data,sizeof(Qfloat)*len);
    size -= more;
    Swap(h->len, len);
  }
  lru_insert (h);
  *data = h->data;
  return len;
}
void SVM233::Cache::swap_index (kkint32 i, kkint32 j)
Definition at line 1483 of file svm.cpp.
Referenced by SVM233::SVC_Q::swap_index(), and SVM233::ONE_CLASS_Q::swap_index().
{
  if(i==j) return;
  if(head[i].len) lru_delete(&head[i]);
  if(head[j].len) lru_delete(&head[j]);
  Swap(head[i].data,head[j].data);
  Swap(head[i].len,head[j].len);
  if(head[i].len) lru_insert(&head[i]);
  if(head[j].len) lru_insert(&head[j]);
  if(i>j) Swap(i,j);
  for(head_t *h = lru_head.next; h!=&lru_head; h=h->next)
  {
    if(h->len > i)
    {
      if(h->len > j)
        Swap(h->data[i],h->data[j]);
      else
      {
        // give up
        lru_delete(h);
        free(h->data);
        size += h->len;
        h->data = 0;
        h->len = 0;
      }
    }
  }
}
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm.cpp