KKLSC::StartStopPointList Class Reference
#include <StartStopPoint.h>
Public Types
typedef StartStopPointList * StartStopPointListPtr
Public Member Functions
StartStopPointList ()
~StartStopPointList ()
StartStopPointPtr AddEntry (kkint32 _scanLineNum, StartStopPoint::StartStopType _type)
StartStopPointPtr AddEntry (StartStopPointPtr &_entry)
void Clear ()
void DeleteEntry (kkint32 _scanLineNum)
kkint32 MemoryConsumedEstimated () const
StartStopPointPtr NearestEntry (kkint32 _scanLineNum) const
StartStopPointPtr PrevEntry (kkint32 _scanLineNum) const
StartStopPointPtr SuccEntry (kkint32 _scanLineNum) const
Detailed Description
Definition at line 79 of file StartStopPoint.h.
Member Typedef Documentation
typedef StartStopPointList* KKLSC::StartStopPointList::StartStopPointListPtr
Definition at line 82 of file StartStopPoint.h.
Constructor & Destructor Documentation
StartStopPointList::StartStopPointList ()
Definition at line 109 of file StartStopPoint.cpp.
References StartStopPointList().
Referenced by StartStopPointList().
                                       :
    vector<StartStopPointPtr> ()
{
}
StartStopPointList::~StartStopPointList ()
Definition at line 115 of file StartStopPoint.cpp.
References Clear().
{
  Clear ();
}
Member Function Documentation
StartStopPointPtr StartStopPointList::AddEntry (kkint32 _scanLineNum, StartStopPoint::StartStopType _type)
Definition at line 152 of file StartStopPoint.cpp.
References AddEntry(), and KKLSC::StartStopPoint::StartStopPoint().
{
  StartStopPointPtr newEntry = new StartStopPoint (_scanLineNum, _type);
  return AddEntry (newEntry);
} /* AddEntry */
StartStopPointPtr StartStopPointList::AddEntry (StartStopPointPtr & _entry)
Definition at line 162 of file StartStopPoint.cpp.
References KKLSC::StartStopPoint::ScanLineNum(), and KKLSC::StartStopPoint::Type().
Referenced by AddEntry().
{
  if (size () < 1)
  {
    push_back (_entry);
    return _entry;
  }
  StartStopPointPtr entryAdded = _entry;
  kkint32 m = FindGreaterOrEqual (_entry->ScanLineNum ());
  if (m < 0)
    push_back (_entry);
  else
  {
    StartStopPointPtr existingEntry = (*this)[m];
    if (existingEntry->ScanLineNum () == _entry->ScanLineNum ())
    {
      entryAdded = existingEntry;
      existingEntry->Type (_entry->Type ());
      delete _entry;
      _entry = NULL;
    }
    else
    {
      entryAdded = _entry;
      idx = begin () + m;
      insert (idx, _entry);
    }
  }
  return entryAdded;
} /* AddEntry */
void StartStopPointList::Clear ()
Clears all existing entries.
Definition at line 121 of file StartStopPoint.cpp.
Referenced by ~StartStopPointList().
{
  while (size () > 0)
  {
    StartStopPointPtr e = back ();
    pop_back ();
    delete e;
    e = NULL;
  }
}
void StartStopPointList::DeleteEntry (kkint32 _scanLineNum)
Definition at line 199 of file StartStopPoint.cpp.
{
  kkint32 m = FindEqual (_scanLineNum);
  if (m < 0)
    return;
  StartStopPointPtr entry = (*this)[m];
  erase (begin () + m);
  delete entry;
}
kkint32 StartStopPointList::MemoryConsumedEstimated () const
Definition at line 134 of file StartStopPoint.cpp.
References KKLSC::StartStopPoint::MemoryConsumedEstimated().
{
  const_iterator idx2;
  kkint32 mem = sizeof (*this);
  for (idx2 = begin (); idx2 != end (); ++idx2)
  {
    StartStopPointPtr sp = *idx2;
    mem += sp->MemoryConsumedEstimated ();
  }
  return mem;
}
StartStopPointPtr StartStopPointList::NearestEntry (kkint32 _scanLineNum) const
Definition at line 350 of file StartStopPoint.cpp.
{
  if (size () < 1)
    return NULL;
  else if (size () == 1)
    return (*this)[0];
  kkint32 m = FindLessOrEqual (_scanLineNum);
  if (m < 0)
    return (*this)[0];
  if (m >= ((kkint32)size () - 1))
    return (*this)[m];
  kkint32 deltaBefore = (_scanLineNum - (*this)[m]->ScanLineNum ());
  kkint32 deltaAfter = (*this)[m + 1]->ScanLineNum () - _scanLineNum;
  if (deltaBefore <= deltaAfter)
    return (*this)[m];
  else
    return (*this)[m + 1];
}
StartStopPointPtr StartStopPointList::PrevEntry (kkint32 _scanLineNum) const
Definition at line 328 of file StartStopPoint.cpp.
{
  kkint32 m = FindLessOrEqual (_scanLineNum);
  if (m >= 0)
    return (*this)[m];
  else
    return NULL;
} /* PrevEntry */
StartStopPointPtr StartStopPointList::SuccEntry (kkint32 _scanLineNum) const
Definition at line 339 of file StartStopPoint.cpp.
{
  kkint32 m = FindGreaterOrEqual (_scanLineNum);
  if (m >= 0)
    return (*this)[m];
  else
    return NULL;
} /* SuccEntry */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/StartStopPoint.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/StartStopPoint.cpp