KKB::Histogram Class Reference
Used to manage the construction of a Histogram.
#include <Histogram.h>
Public Member Functions
Histogram (float _minValue, kkint32 _numOfBuckets, float _bucketSize, bool _wrapArround)
~Histogram ()
kkint32 AreaInRange (kkint32 minBucket, kkint32 maxBucket) const
float AreaInRangePercent (kkint32 minBucket, kkint32 maxBucket) const
float AverageOfMaxBucket () const
float AverageOfMaxBucketExcludingRange (kkint32 minBucket, kkint32 maxBucket) const
float AverageOfMaxBucketInRange (kkint32 firstBucket, kkint32 lastBucket) const
float AverageOfMinBucketInRange (kkint32 minBucket, kkint32 maxBucket) const
float Bucket (kkint32 bucket) const
float BucketSize () const
void CalculatePeaks (kkint32 threshold)
float CountOfMaxBucket () const
RasterPtr CreateGraph () const
RasterPtr CreateGraph (kkint32 barSize) const
Histogram * Equalized ()
kkint32 * EqualizedMapTable ()
float GetPeakAvgByHighestOrder (kkint32 peakNum)
kkint32 GetPeakBucket (kkint32 peakNum)
kkint32 GetPeakByHighestOrder (kkint32 peakNum)
void GetStats (float &min, float &max, float &mean, float &variance)
void Increment (float val)
bool IsBucketAPeak (kkint32 bucket, kkint32 tolerance) const
kkint32 MaxBucketIdx () const
float MinValue () const
kkint32 NumOfBuckets () const
void PrintTable (ostream &o)
void Save (KKStr fileName) const
void SaveGraphImage (const KKStr &fileName) const
void SaveGraphImage (const KKStr &fileName, kkint32 barSize) const
Histogram * Smooth (kkint32 smoothWidth)
float TotalCount () const
Detailed Description
Used to manage the construction of a Histogram.
Definition at line 24 of file Histogram.h.
Constructor & Destructor Documentation
Histogram::Histogram (float _minValue, kkint32 _numOfBuckets, float _bucketSize, bool _wrapArround)
Definition at line 24 of file Histogram.cpp.
Referenced by Equalized(), KKB::Raster::Histogram(), KKB::Raster::HistogramGrayscale(), and Smooth().
                      :
  bucketSize (_bucketSize),
  buckets (NULL),
  equalizedMapTable (NULL),
  minValue (_minValue),
  numOfBuckets (_numOfBuckets),
  totalCount (0.0),
  totalVal (0.0),
  wrapArround (_wrapArround)
{
  if (numOfBuckets < 1)
  {
    cerr << std::endl
         << "*** ERROR *** Histogram, Negative numOfBuckets[" << numOfBuckets << "." <<
      std::endl
         << std::endl;
    exit (-1);
  }
  range = bucketSize * numOfBuckets;
  buckets = new float[numOfBuckets];
  bucketTotals = new float[numOfBuckets];
  for (kkint32 x = 0; x < numOfBuckets; x++)
  {
    buckets [x] = (float)0.0;
    bucketTotals[x] = (float)0.0;
  }
}
Histogram::~Histogram ()
Definition at line 64 of file Histogram.cpp.
{
  delete buckets;
  delete bucketTotals;
  if (equalizedMapTable)
    delete equalizedMapTable;
}
Member Function Documentation
kkint32 Histogram::AreaInRange (kkint32 minBucket, kkint32 maxBucket) const
Definition at line 1010 of file Histogram.cpp.
Referenced by AreaInRangePercent().
{
  if ((minBucket < 0) || (minBucket >= numOfBuckets) ||
       (maxBucket < 0) || (maxBucket >= numOfBuckets) ||
       (minBucket > maxBucket)
      )
  {
    cerr << std::endl;
    cerr << "Histogram::AreaInRange *** ERROR *** Invalid Parameters" <<
      std::endl;
    cerr << "NumOfBuckets[" << numOfBuckets << "] MinBucket[" << minBucket << "] MaxBucket[" <<
      maxBucket << "]" << std::endl;
    exit (-1);
  }
  float area = (float)0.0;
  for (kkint32 b = minBucket; b <= maxBucket; b++)
  {
    area += buckets[b];
  }
  return (kkint32)(area + (float)0.5);
} /* AreaInRange */
float Histogram::AreaInRangePercent (kkint32 minBucket, kkint32 maxBucket) const
Definition at line 1036 of file Histogram.cpp.
References AreaInRange().
{
  if (totalCount <= (float)0.0)
    return (float)0.0;
  return (float)100.0 * (float)((float)AreaInRange (minBucket, maxBucket) / totalCount);
}
float Histogram::AverageOfMaxBucket () const
Definition at line 98 of file Histogram.cpp.
References MaxBucketIdx().
{
  kkint32 idx = MaxBucketIdx ();
  if (buckets[idx] <= (float)0.0)
    return (float)0.0;
  else
    return bucketTotals[idx] / buckets[idx];
} /* AverageOfMaxBucket */
float Histogram::AverageOfMaxBucketExcludingRange (kkint32 minBucket, kkint32 maxBucket) const
Definition at line 967 of file Histogram.cpp.
{
  if ((minBucket < 0) || (minBucket >= numOfBuckets) ||
       (maxBucket < 0) || (maxBucket >= numOfBuckets) ||
       (minBucket > maxBucket)
      )
  {
    cerr << std::endl;
    cerr << "Histogram::AverageOfMaxBucketExcludingRange *** ERROR *** Invalid Parameters" <<
      std::endl;
    cerr << "NumOfBuckets[" << numOfBuckets << "] MinBucket[" << minBucket << "] MaxBucket[" <<
      maxBucket << "]" << std::endl;
    exit (-1);
  }
  
  kkint32 b;
  kkint32 maxBucketIDX = -1;
  float maxBucketVal = 0;
  for (b = 0; b < numOfBuckets; b++)
  {
    if ((b < minBucket) || (b > maxBucket))
    {
      if (buckets[b] > maxBucketVal)
      {
        maxBucketIDX = b;
        maxBucketVal = buckets[b];
      }
    }
  }
  if (maxBucketIDX < 0)
    return 0;
  if (maxBucketVal > (float)0.0)
    return bucketTotals[maxBucketIDX] / buckets[maxBucketIDX];
  else
    return (float)0.0;
} /* AverageOfMaxBucketExcludingRange */
float Histogram::AverageOfMaxBucketInRange (kkint32 firstBucket, kkint32 lastBucket) const
Definition at line 891 of file Histogram.cpp.
Referenced by KKB::Raster::SegmentImage().
{
  if ((minBucket < 0) || (minBucket >= numOfBuckets) ||
       (maxBucket < 0) || (maxBucket >= numOfBuckets) ||
       (minBucket > maxBucket)
      )
  {
    cerr << std::endl;
    cerr << "Histogram::AverageOfMaxBucketInRange *** ERROR *** Invalid Parameters" <<
      std::endl;
    cerr << "NumOfBuckets[" << numOfBuckets << "] MinBucket[" << minBucket << "] MaxBucket[" <<
      maxBucket << "]" << std::endl;
    exit (-1);
  }
  
  kkint32 b;
  kkint32 maxBucketIDX = minBucket;
  float maxBucketVal = buckets[minBucket];
  for (b = minBucket; b <= maxBucket; b++)
  {
    if (buckets[b] > maxBucketVal)
    {
      maxBucketIDX = b;
      maxBucketVal = buckets[b];
    }
  }
  if (maxBucketVal > (float)0.0)
    return bucketTotals[maxBucketIDX] / buckets[maxBucketIDX];
  else
    return (float)0.0;
} /* AverageOfMaxBucketInRange */
float Histogram::AverageOfMinBucketInRange (kkint32 minBucket, kkint32 maxBucket) const
Definition at line 930 of file Histogram.cpp.
{
  if ((firstBucket < 0) || (firstBucket >= numOfBuckets) ||
       (lastBucket < 0) || (lastBucket >= numOfBuckets) ||
       (firstBucket > lastBucket)
      )
  {
    cerr << std::endl;
    cerr << "Histogram::AverageOfMaxBucketInRange *** ERROR *** Invalid Parameters" <<
      std::endl;
    cerr << "NumOfBuckets[" << numOfBuckets << "] FirstBucket[" << firstBucket << "] LastBucket[" <<
      lastBucket << "]" << std::endl;
    exit (-1);
  }
  
  kkint32 b;
  kkint32 minBucketIDX = firstBucket;
  float minBucketVal = buckets[firstBucket];
  for (b = firstBucket; b <= lastBucket; b++)
  {
    if (buckets[b] <= minBucketVal)
    {
      minBucketIDX = b;
      minBucketVal = buckets[b];
    }
  }
  if (minBucketVal > 0)
    return bucketTotals[minBucketIDX] / buckets[minBucketIDX];
  else
    return (float)0.0;
} /* AverageOfMaxBucketInRange */
float Histogram::Bucket (kkint32 bucket) const
Definition at line 122 of file Histogram.cpp.
{
  if ((bucket < 0) || (bucket >= numOfBuckets))
  {
    cerr << std::endl
         << "*** ERROR *** Histogram::Bucket, Bucket[" << bucket << "] is out of range." <<
      std::endl
         << std::endl;
    exit (-1);
  }
  return buckets[bucket];
} /* Bucket */
float KKB::Histogram::BucketSize () const [inline]
Definition at line 60 of file Histogram.h.
{return bucketSize;}
void Histogram::CalculatePeaks (kkint32 threshold)
Definition at line 756 of file Histogram.cpp.
{
  kkint32 bucket;
  peaks.erase (peaks.begin (), peaks.end ());
  for (bucket = 0; bucket < numOfBuckets; bucket++)
  {
    if (IsBucketAPeak (bucket, threshold))
      peaks.push_back (bucket);
  }
} /* CalculatePeaks */
float Histogram::CountOfMaxBucket () const
Definition at line 113 of file Histogram.cpp.
References MaxBucketIdx().
{
  kkint32 idx = MaxBucketIdx ();
  return buckets[idx];
} /* CountOfMaxBucket */
RasterPtr Histogram::CreateGraph () const
Definition at line 162 of file Histogram.cpp.
References KKB::Raster::DrawLine(), IsBucketAPeak(), KKB::Raster::Raster(), KKB::Raster::ReverseImage(), and KKB::Raster::SetPixelValue().
Referenced by KKB::Raster::HistogramGrayscaleImage(), KKB::Raster::HistogramImage(), and SaveGraphImage().
{
  kkint32 bucket = 0;
  kkint32 col = 10;
  kkint32 barWidth = 2;
  kkint32 interBarWidth = 5;
  kkint32 colHeight = 0;
  float maxCount = (float)0.0;
  kkint32 row = 0;
  kkint32 x;
  kkint32 y;
  uchar borderColor = 100;
  uchar colorAxis = 150;
  uchar colorBar = 200;
  uchar colorBarMax = 255;
  uchar colorBarPeak = 255;
  uchar gridColor = 180;
  uchar hashColor = 70;
  uchar hashColor2 = 45;
  kkint32 graphWidth = numOfBuckets * (barWidth + interBarWidth) + 20; // 3 pixels per bar, +
                                                                       // 3 pixels space +
                                                                       // 10 pixel Padding on both sides.
  // Set up where Grid lines should go
  bool* vertGridLines = new bool[numOfBuckets];
  bool* peakBarLines = new bool[numOfBuckets];
  for (x = 0; x < numOfBuckets; x++)
  {
    vertGridLines[x] = false;
    peakBarLines [x] = IsBucketAPeak (x, 2); // Make sure that we are greater than
                                              // our 2 left and right neighbors
  }
  // Look for the Zero Grid Line should go
  kkint32 middleIdx = 0;
  if (minValue < 0)
  {
    kkint32 numOfBucketsToZero = (kkint32)(0.5 + fabs (minValue) / bucketSize);
    if (numOfBucketsToZero < numOfBuckets)
      middleIdx = numOfBucketsToZero;
  }
  x = middleIdx;
  while (x < numOfBuckets)
  {
    vertGridLines[x] = true;
    x += 100;
  }
  x = middleIdx;
  while (x > 0)
  {
    vertGridLines[x] = true;
    x -= 100;
  }
  for (bucket = 0; bucket < numOfBuckets; bucket++)
  {
    if (buckets[bucket] > maxCount)
      maxCount = buckets[bucket];
  }
  kkint32 maxColHeight = Min ((kkint32)(maxCount * (barWidth + interBarWidth) + (float)0.
      5), (kkint32)512);
  kkint32 graphHeight = maxColHeight + 20;
  RasterPtr graph = new Raster (graphHeight, graphWidth);
  graph->DrawLine (10, 10, 10, graphWidth - 10,
      borderColor); // TopLeft -> TopRight
  graph->DrawLine (10, graphWidth - 10, graphHeight - 10, graphWidth - 10,
      borderColor); // TopRight -> BotRight
  graph->DrawLine (graphHeight - 10, graphWidth - 10, graphHeight - 10, 10,
      borderColor); // BotRight -> BotLeft
  graph->DrawLine (graphHeight - 10, 10, 10, 10,
      borderColor); // BotLeft -> TopLeft
  x = 0;
  row = graphHeight - 10;
  
  // Draw Y Axis
  while (x < maxColHeight)
  {
    if ((x % 10) == 0)
    {
      if ((x % 50) == 0)
      {
        graph->SetPixelValue (row, 4, hashColor2);
        graph->SetPixelValue (row, 5, hashColor2);
        graph->SetPixelValue (row, 6, hashColor2);
        if ((x % 100) == 0)
        {
          graph->DrawLine (row, 9, row, graphWidth - 11, gridColor);
        }
      }
      graph->SetPixelValue (row, 7, hashColor);
      graph->SetPixelValue (row, 8, hashColor);
      graph->SetPixelValue (row, 9, hashColor);
    }
    graph->SetPixelValue (row, 9, colorAxis);
    row--;
    x++;
  }
  col = 10;
  for (bucket = 0; bucket < numOfBuckets; bucket++)
  {
    for (x = 0; x < (barWidth + interBarWidth); x++)
    {
      graph->SetPixelValue (graphHeight - 9, col + x, colorAxis);
    }
    if ((bucket % 10) == 0)
    {
      // Lets add a Hash Mark
      graph->SetPixelValue (graphHeight - 8, col + 1, hashColor);
      graph->SetPixelValue (graphHeight - 7, col + 1, hashColor);
      graph->SetPixelValue (graphHeight - 6, col + 1, hashColor);
      graph->SetPixelValue (graphHeight - 5, col + 1, hashColor);
    }
    if (vertGridLines[bucket] == true)
    {
      graph->DrawLine (graphHeight - 10, col + 1, 10, col + 1, gridColor);
    }
    colHeight = (kkint32)ceil ((((float)maxColHeight * buckets[bucket]) / maxCount));
    if ((colHeight < 1) && (buckets[bucket] > (float)0.0))
    {
      cout << "I want to know about this." << std::endl;
    }
    row = graphHeight - 10;
    uchar barCodeToUse = colorBar;
    if (buckets[bucket] >= maxCount)
      barCodeToUse = colorBarMax;
    else if (peakBarLines[bucket])
      barCodeToUse = colorBarPeak;
    for (kkint32 x = 0; x < colHeight; x++)
    {
      for (y = 0; y < barWidth; y++)
      {
        graph->SetPixelValue (row, col + y, barCodeToUse);
      }
      row--;
    }
    col += (barWidth + interBarWidth);
  }
  delete[] peakBarLines;
  delete[] vertGridLines;
  graph->ReverseImage ();
  return graph;
} /* CreateGraph */
RasterPtr Histogram::CreateGraph (kkint32 barSize) const
Definition at line 337 of file Histogram.cpp.
References KKB::Raster::DrawLine(), IsBucketAPeak(), KKB::Raster::Raster(), KKB::Raster::ReverseImage(), and KKB::Raster::SetPixelValue().
Referenced by SaveGraphImage().
{
  kkint32 bucket = 0;
  kkint32 col = 10;
  kkint32 barWidth = 2;
  kkint32 interBarWidth = 5;
  kkint32 colHeight = 0;
  float maxCount = (float)0.0;
  kkint32 row = 0;
  kkint32 x;
  kkint32 y;
  uchar borderColor = 100;
  uchar colorAxis = 150;
  uchar colorBar = 200;
  uchar colorBarMax = 255;
  uchar colorBarPeak = 255;
  uchar gridColor = 180;
  uchar hashColor = 70;
  uchar hashColor2 = 45;
  kkint32 graphWidth = numOfBuckets * (barWidth + interBarWidth) + 20; // 3 pixels per bar, +
                                                                       // 3 pixels space +
                                                                       // 10 pixels Padding on both sides.
  // Set up where Grid lines should go
  bool* vertGridLines = new bool[numOfBuckets];
  bool* peakBarLines = new bool[numOfBuckets];
  for (x = 0; x < numOfBuckets; x++)
  {
    vertGridLines[x] = false;
    peakBarLines [x] = IsBucketAPeak (x, 2); // Make sure that we are greater than
                                              // our 2 left and right neighbors
  }
  // Look for the Zero Grid Line should go
  kkint32 middleIdx = 0;
  if (minValue < 0)
  {
    kkint32 numOfBucketsToZero = (kkint32)(0.5 + fabs (minValue) / bucketSize);
    if (numOfBucketsToZero < numOfBuckets)
      middleIdx = numOfBucketsToZero;
  }
  x = middleIdx;
  while (x < numOfBuckets)
  {
    vertGridLines[x] = true;
    x += 100;
  }
  x = middleIdx;
  while (x > 0)
  {
    vertGridLines[x] = true;
    x -= 100;
  }
  
  for (bucket = 0; bucket < numOfBuckets; bucket++)
  {
    if (buckets[bucket] > maxCount)
      maxCount = buckets[bucket];
  }
  kkint32 maxColHeight = Min ((kkint32)(maxCount * (barWidth + interBarWidth) + (float)0.
      5), (kkint32)512);
  kkint32 graphHeight = maxColHeight + 20;
  RasterPtr graph = new Raster (graphHeight, graphWidth);
  graph->DrawLine (10, 10, 10, graphWidth - 10,
      borderColor); // TopLeft -> TopRight
  graph->DrawLine (10, graphWidth - 10, graphHeight - 10, graphWidth - 10,
      borderColor); // TopRight -> BotRight
  graph->DrawLine (graphHeight - 10, graphWidth - 10, graphHeight - 10, 10,
      borderColor); // BotRight -> BotLeft
  graph->DrawLine (graphHeight - 10, 10, 10, 10,
      borderColor); // BotLeft -> TopLeft
  x = 0;
  row = graphHeight - 10;
  // Draw Y Axis
  while (x < maxColHeight)
  {
    if ((x % 10) == 0)
    {
      if ((x % 50) == 0)
      {
        graph->SetPixelValue (row, 4, hashColor2);
        graph->SetPixelValue (row, 5, hashColor2);
        graph->SetPixelValue (row, 6, hashColor2);
        if ((x % 100) == 0)
        {
          graph->DrawLine (row, 9, row, graphWidth - 11, gridColor);
        }
      }
      graph->SetPixelValue (row, 7, hashColor);
      graph->SetPixelValue (row, 8, hashColor);
      graph->SetPixelValue (row, 9, hashColor);
    }
    graph->SetPixelValue (row, 9, colorAxis);
    row--;
    x++;
  }
  col = 10;
  for (bucket = 0; bucket < numOfBuckets; bucket++)
  {
    for (x = 0; x < (barWidth + interBarWidth); x++)
    {
      graph->SetPixelValue (graphHeight - 9, col + x, colorAxis);
    }
    if ((bucket % 10) == 0)
    {
      // Lets add a Hash Mark
      graph->SetPixelValue (graphHeight - 8, col + 1, hashColor);
      graph->SetPixelValue (graphHeight - 7, col + 1, hashColor);
      graph->SetPixelValue (graphHeight - 6, col + 1, hashColor);
      graph->SetPixelValue (graphHeight - 5, col + 1, hashColor);
    }
    if (vertGridLines[bucket] == true)
    {
      graph->DrawLine (graphHeight - 10, col + 1, 10, col + 1, gridColor);
    }
    colHeight = (kkint32)ceil ((((float)maxColHeight * buckets[bucket]) / maxCount));
    if ((colHeight < 1) && (buckets[bucket] > (float)0.0))
    {
      cout << "I want to know about this." << std::endl;
    }
    row = graphHeight - 10;
    uchar barCodeToUse = colorBar;
    if (buckets[bucket] >= maxCount)
      barCodeToUse = colorBarMax;
    else if (peakBarLines[bucket])
      barCodeToUse = colorBarPeak;
    for (kkint32 x = 0; x < colHeight; x++)
    {
      for (y = 0; y < barWidth; y++)
      {
        graph->SetPixelValue (row, col + y, barCodeToUse);
      }
      row--;
    }
    col += (barWidth + interBarWidth);
  }
  delete[] peakBarLines;
  delete[] vertGridLines;
  graph->ReverseImage ();
  return graph;
} /* CreateGraph */
HistogramPtr Histogram::Equalized ()
Definition at line 848 of file Histogram.cpp.
References Histogram().
Referenced by KKB::Raster::HistogramEqualizedImage().
{
  float* histSumTable = new float[numOfBuckets];
  kkint32 idx;
  HistogramPtr newHist = new Histogram (minValue, numOfBuckets, bucketSize,
      wrapArround);
  kkint32 x;
  newHist->equalizedMapTable = new kkint32[numOfBuckets];
  float accumulatedCount = (float)0.0;
  for (x = 0; x < numOfBuckets; x++)
  {
    accumulatedCount += buckets[x];
    histSumTable[x] = accumulatedCount;
  }
 
  for (x = 0; x < numOfBuckets; x++)
  {
    idx = (kkint32)((float)0.5 + (((float)(histSumTable[x] * (numOfBuckets - 1)) / totalCount)));
    if (idx >= numOfBuckets)
      idx = numOfBuckets - 1;
    newHist->equalizedMapTable[x] = idx;
    newHist->buckets[idx] += buckets[x];
    newHist->bucketTotals[idx] += bucketTotals[x];
  }
  newHist->totalCount = totalCount;
  newHist->totalVal = totalVal;
  delete[] histSumTable;
  return newHist;
} /* Equalize */
kkint32* KKB::Histogram::EqualizedMapTable () [inline]
Definition at line 72 of file Histogram.h.
Referenced by KKB::Raster::HistogramEqualizedImage().
{return equalizedMapTable;}
float Histogram::GetPeakAvgByHighestOrder (kkint32 peakNum)
Definition at line 820 of file Histogram.cpp.
References GetPeakByHighestOrder().
{
  kkint32 x = GetPeakByHighestOrder (peakNum);
  if (x < 0)
  {
    cout << std::endl;
    cout << "GetPeakAvgByHighestOrder GetPeakByHighestOrder returned[" << x << "]" <<
      std::endl;
    return 0;
  }
  if (x >= this->numOfBuckets)
  {
    cout << std::endl;
    cout << "GetPeakAvgByHighestOrder GetPeakByHighestOrder returned[" << x << "]" <<
      std::endl;
    x = 1;
    return 0;
  }
  if (buckets[x] <= (float)0.0)
    return 0.0;
  return (bucketTotals[x] / buckets[x]);
} /* GetPeakAvgByHighestOrder */
kkint32 Histogram::GetPeakBucket (kkint32 peakNum)
Definition at line 771 of file Histogram.cpp.
{
  if (peaks.empty ())
    CalculatePeaks (2);
  if (peakNum > (kkint32)peaks.size ())
    return -1;
  else
    return peaks[peakNum];
}
kkint32 Histogram::GetPeakByHighestOrder (kkint32 peakNum)
Definition at line 785 of file Histogram.cpp.
Referenced by GetPeakAvgByHighestOrder().
{
  if (peaks.empty ())
    CalculatePeaks (2);
  if (peakNum > (kkint32)peaks.size ())
    return -1;
  kkint32 t;
  kkint32 x;
  kkint32 y;
  VectorInt32 sortedPeaks (peaks);
  for (x = 1; x < (kkint32)sortedPeaks.size (); x++)
  {
    for (y = x; y > 0; y--)
    {
      if (buckets[sortedPeaks[y - 1]] < buckets[sortedPeaks[y]])
      {
        t = sortedPeaks[y];
        sortedPeaks[y] = sortedPeaks[y - 1];
        sortedPeaks[y - 1] = t;
      }
    }
  }
  kkint32 returnIdxNum = sortedPeaks[peakNum];
  
  return returnIdxNum;
  
} /* GetPeakByHighestOrder */
void Histogram::GetStats (float & min, float & max, float & mean, float & variance)
Definition at line 1071 of file Histogram.cpp.
{
  min = FLT_MAX;
  max = FLT_MIN;
  mean = totalCount / numOfBuckets;
  variance = 0.0f;
  float deltaSquareTotal = 0.0f;
  for (kkint32 idx = 0; idx < numOfBuckets; idx++)
  {
    if (buckets[idx] < min) min = buckets[idx];
    if (buckets[idx] > max) max = buckets[idx];
    float delta = buckets[idx] - mean;
    float deltaSquare = delta * delta;
    deltaSquareTotal += deltaSquare;
  }
  variance = deltaSquareTotal / (float)numOfBuckets;
} /* GetStats */
void Histogram::Increment (float val)
Definition at line 137 of file Histogram.cpp.
Referenced by KKB::Raster::Histogram(), and KKB::Raster::HistogramGrayscale().
{
  if (val < minValue)
  {
    cerr << std::endl
         << "*** ERROR *** val[" << val << "] is out of range [" << minValue << "]." <<
      std::endl
         << std::endl;
    exit (-1);
  }
  kkint32 bucket = (kkint32) ((val - minValue) / bucketSize);
  if (bucket >= numOfBuckets)
    bucket = numOfBuckets - 1;
  else if (bucket < 0)
    bucket = 0;
  buckets[bucket] = buckets[bucket] + (float)1.0;
  bucketTotals[bucket] += val;
  totalCount += (float)1.0;
  totalVal += val;
} /* Increment */
bool Histogram::IsBucketAPeak (kkint32 bucket, kkint32 tolerance) const
Definition at line 703 of file Histogram.cpp.
Referenced by CreateGraph().
{
  kkint32 beforeIDX = bucket;
  kkint32 afterIDX = bucket;
  kkint32 lastBeforeIDX = bucket;
  kkint32 lastAfterIDX = bucket;
  if (buckets[bucket] == (float)0.0)
    return false;
  for (kkint32 x = 1; x <= tolerance; x++)
  {
    beforeIDX--;
    afterIDX++;
    if (beforeIDX < 0)
    {
      if (wrapArround)
        beforeIDX = beforeIDX + numOfBuckets;
    }
    if (afterIDX < 0)
    {
      if (wrapArround)
        afterIDX = afterIDX - numOfBuckets;
    }
    if (beforeIDX >= 0)
    {
      if (buckets [beforeIDX] > buckets[lastBeforeIDX])
        return false;
    }
    if (afterIDX < numOfBuckets)
    {
      if (buckets [afterIDX] > buckets[lastAfterIDX])
        return false;
    }
    lastBeforeIDX = beforeIDX;
    lastAfterIDX = afterIDX;
  }
  return true;
} /* IsBucketAPeak */
kkint32 Histogram::MaxBucketIdx () const
Definition at line 76 of file Histogram.cpp.
Referenced by AverageOfMaxBucket(), and CountOfMaxBucket().
{
  kkint32 idx;
  float maxCount = -1;
  kkint32 maxIdx = -1;
  for (idx = 0; idx < numOfBuckets; idx++)
  {
    if (buckets[idx] > maxCount)
    {
      maxCount = buckets[idx];
      maxIdx = idx;
    }
  }
  return maxIdx;
} /* MaxBucketIdx */
float KKB::Histogram::MinValue () const [inline]
Definition at line 94 of file Histogram.h.
{return minValue;}
kkint32 KKB::Histogram::NumOfBuckets () const [inline]
Definition at line 96 of file Histogram.h.
Referenced by KKB::Raster::HistogramEqualizedImage().
{return numOfBuckets;}
void Histogram::PrintTable (ostream & o)
Definition at line 1048 of file Histogram.cpp.
References KKB::operator<<().
{
  kkint32 x;
  float l = minValue;
  
  o << l;
  for (x = 1; x < numOfBuckets; x++)
  {
    l += bucketSize;
    o << "\t" << l;
  }
  o << std::endl;
  
  o << buckets[0];
  for (x = 1; x < numOfBuckets; x++)
  {
    o << "\t" << buckets[x];
  }
  o << std::endl;
} /* PrintTable */
void Histogram::Save (KKStr fileName) const
Definition at line 529 of file Histogram.cpp.
Referenced by KKB::Raster::SegmentImage().
{
  ofstream o (fileName.Str ());
  kkint32 bucketIDX;
  float avgVal = totalVal / totalCount;
  o << "MinValue" << "\t" << "\t" << "BucketSize" << "\t" << "NumOfBuckets" << "\t" << "TotalCount" << "
      \t" << "Average" << std::endl;
  o << minValue << "\t" << "\t" << bucketSize << "\t" << numOfBuckets << "\t" << totalCount << "
      \t" << avgVal << std::endl;
  o << std::endl;
  o << std::endl;
  float avg;
  float percentage;
  float bucketVal = minValue + bucketSize;
  o << "BucketValue" << "\t"
    << "Count" << "\t"
    << "AvgValue" << "\t"
    << "%OfTotalCount"
    << std::endl
    << std::endl;
  for (bucketIDX = 0; bucketIDX < numOfBuckets; bucketIDX++)
  {
    o << bucketVal;
    o << "\t" << buckets[bucketIDX];
    if (buckets[bucketIDX] > (float)0.0)
      avg = bucketTotals[bucketIDX] / buckets[bucketIDX];
    else
      avg = 0.0;
    o << "\t" << avg;
    percentage = (float)100.0 * buckets[bucketIDX] / totalCount;
    o << "\t" << percentage << "%";
    bucketVal += bucketSize;
    o << std::endl;
  }
  o << std::endl;
  o << std::endl;
  o.close ();
} /* Save */
void Histogram::SaveGraphImage (const KKStr & fileName) const
Definition at line 510 of file Histogram.cpp.
References CreateGraph(), and KKB::SaveImage().
Referenced by KKB::Raster::SegmentImage().
{
  RasterPtr graphImage = CreateGraph ();
  SaveImage (*graphImage, fileName);
  delete graphImage;
} /* SaveGraphImage */
void Histogram::SaveGraphImage (const KKStr & fileName, kkint32 barSize) const
Definition at line 518 of file Histogram.cpp.
References CreateGraph(), and KKB::SaveImage().
{
  RasterPtr graphImage = CreateGraph (barSize);
  SaveImage (*graphImage, fileName);
  delete graphImage;
}
HistogramPtr Histogram::Smooth (kkint32 smoothWidth)
Definition at line 585 of file Histogram.cpp.
References Histogram().
Referenced by KKB::Raster::SegmentImage().
{
  kkint32 bucket;
  kkint32 endBuckOffset;
  kkint32 startBuckOffset;
  float sumOfbuckets = (float)0.0;
  float sumOfBucketTotals = (float)0.0;
  HistogramPtr hist = new Histogram (minValue,
                                     numOfBuckets,
                                     bucketSize,
                                     wrapArround
                                    );
  if (wrapArround)
  {
    startBuckOffset = numOfBuckets - (smoothWidth / 2);
    endBuckOffset = startBuckOffset + smoothWidth - 1 - numOfBuckets;
    // Lets Build Initial Totals
    bucket = startBuckOffset;
    while (true)
    {
      sumOfbuckets += buckets [bucket];
      sumOfBucketTotals += bucketTotals [bucket];
      if (bucket == endBuckOffset)
        break;
      bucket++;
      if (bucket >= numOfBuckets)
        bucket = bucket - numOfBuckets;
    }
    for (bucket = 0; bucket < numOfBuckets; bucket++)
    {
      hist->buckets [bucket] = sumOfbuckets / (float)smoothWidth;
      hist->bucketTotals [bucket] = sumOfBucketTotals / (float)smoothWidth;
      sumOfbuckets -= buckets [startBuckOffset];
      sumOfBucketTotals -= bucketTotals [startBuckOffset];
      startBuckOffset++;
      if (startBuckOffset >= numOfBuckets)
        startBuckOffset = startBuckOffset - numOfBuckets;
      endBuckOffset++;
      if (endBuckOffset >= numOfBuckets)
        endBuckOffset = endBuckOffset - numOfBuckets;
      sumOfbuckets += buckets [endBuckOffset];
      sumOfBucketTotals += bucketTotals [endBuckOffset];
    }
  } /* End of WrapArround Version */
  else
  {
    // No WrapArround.
    startBuckOffset = -(smoothWidth / 2);
    endBuckOffset = startBuckOffset + smoothWidth - 1;
    kkint32 spreadSize = endBuckOffset + 1;
    // Lets Build Initial Totals
    for (bucket = 0; bucket <= endBuckOffset; bucket++)
    {
      sumOfbuckets += buckets [bucket];
      sumOfBucketTotals += bucketTotals [bucket];
    }
    for (bucket = 0; bucket < numOfBuckets; bucket++)
    {
      hist->buckets [bucket] = sumOfbuckets / (float)spreadSize;
      if (sumOfbuckets > (float)0.0)
      {
        hist->bucketTotals [bucket] = hist->buckets [bucket] * sumOfBucketTotals / sumOfbuckets;
      }
      else
      {
        hist->bucketTotals [bucket] = (float)0.0;
      }
      if (startBuckOffset >= 0)
      {
        sumOfbuckets = sumOfbuckets - buckets [startBuckOffset];
        sumOfBucketTotals = sumOfBucketTotals - bucketTotals [startBuckOffset];
        spreadSize--;
      }
      startBuckOffset++;
      endBuckOffset++;
      if (endBuckOffset < numOfBuckets)
      {
        sumOfbuckets = sumOfbuckets + buckets [endBuckOffset];
        sumOfBucketTotals = sumOfBucketTotals + bucketTotals [endBuckOffset];
        spreadSize++;
      }
    }
  }
  hist->totalCount = totalCount;
  hist->totalVal = totalVal;
  return hist;
} /* Smooth */
float KKB::Histogram::TotalCount () const [inline]
Definition at line 110 of file Histogram.h.
{return totalCount;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Histogram.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Histogram.cpp