KKMLL::TrainingProcess2List Class Reference
#include <TrainingProcess2.h>
Public Member Functions
TrainingProcess2List (bool _owner)
virtual ~TrainingProcess2List ()
kkint32 MemoryConsumedEstimated () const
Additional Inherited Members
Detailed Description
Definition at line 409 of file TrainingProcess2.h.
Constructor & Destructor Documentation
KKMLL::TrainingProcess2List::TrainingProcess2List (bool _owner)
Referenced by XmlFactoryMacro().
TrainingProcess2List::~TrainingProcess2List () [virtual]
Definition at line 1431 of file TrainingProcess2.cpp.
{
}
Member Function Documentation
kkint32 TrainingProcess2List::MemoryConsumedEstimated () const
Definition at line 1437 of file TrainingProcess2.cpp.
References KKMLL::TrainingProcess2::MemoryConsumedEstimated().
Referenced by KKMLL::TrainingProcess2::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = 0;
  TrainingProcess2List::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    TrainingProcess2Ptr tp = *idx;
    if (tp)
      memoryConsumedEstimated += tp->MemoryConsumedEstimated ();
  }
  return memoryConsumedEstimated;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/TrainingProcess2.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/TrainingProcess2.cpp