KKMLL::MLClass Class Reference
Represents a `Class` in the Machine Learning Sense.
#include <MLClass.h>
Public Member Functions
kkint32 ClassId () const
void ClassId (kkint32 _classId)
float CountFactor () const
void CountFactor (float _countFactor)
const KKStr & Description () const
void Description (const KKStr &_description)
bool IsAnAncestor (MLClassPtr c) const
bool Mandatory () const
void Mandatory (bool _mandatory)
MLClassPtr MLClassForGivenHierarchialLevel (KKB::kkuint16 level) const
const KKStr & Name () const
kkuint16 NumHierarchialLevels () const
MLClassPtr Parent () const
void Parent (MLClassPtr _parent)
const KKStr & ParentName () const
bool StoredOnDataBase () const
void StoredOnDataBase (bool _storedOnDataBase)
bool Summarize () const
void Summarize (bool _summarize)
KKStr ToString () const
bool UnDefined () const
void UnDefined (bool _unDefined)
const KKStr & UpperName () const
void WriteXML (const KKStr &varName, std::ostream &o) const
Static Public Member Functions
static MLClassListPtr BuildListOfDecendents (MLClassPtr parent)
static void ChangeNameOfClass (MLClassPtr mlClass, const KKStr &newName, bool &changeSuccessful)
Changes the name of an existing class verifying that a duplicate does not get created.
static MLClassPtr CreateNewMLClass (const KKStr &_name, kkint32 _classId=-1)
Static method used to create a new instance of a MLClass object.
static void FinalCleanUp ()
Call this as the last thing the application does, will delete all existing instances of 'MLClass'.
static MLClassPtr GetByClassId (kkint32 _classId)
static KKStr GetClassNameFromDirName (const KKStr &subDir)
static MLClassPtr GetUnKnownClassStatic ()
static MLClassListPtr GlobalClassList ()
static void ResetAllParentsToAllClasses ()
Friends
class KKQueue< MLClass >
class MLClassList
Detailed Description
Represents a `Class` in the Machine Learning Sense.
Author
Kurt Kramer
Each instance of this class represents a single Class as used in Machine Learning sense. Each instance of 'FeatureVector' class will point to an instance of this class. There can only be one instance of each Class in memory. Specifically the 'name' field will be unique. This is enforced by making the constructor and destructor private. The only way to create a new instance of a 'MLClass' object is to call one of the static methods of 'CreateNewMLClass'. These methods will look for a instance of 'MLClass' that already exists. If one does not they will then create a new one.
Please refer to MLClassList at bottom of file. That class is the object you will most be using when dealing with Images. classes.
UmiClass and PicesClass There is a special relationship between this class and a class called 'UmiClass' and 'PicesClass in the 'UnManagedInterface' and PicesInterface libraries, ".net' Managed libraries'. These managed c++ versions of this class. There is a one-to-one correspondence between the two classes. When ever a instance of 'UmiClass' or 'PicesClass' get created they will automatic- ally call the static method 'MLClass::CreateNewMLClass' to get the unmanaged version of the class.
See also
KKMLL::MLClassList, KKMLL::FeatureVector, UnManagedInterface::UmiClass, MLL::PicesClass
Definition at line 52 of file MLClass.h.
Member Function Documentation
MLClassListPtr MLClass::BuildListOfDecendents (MLClassPtr parent) [static]
Definition at line 145 of file MLClass.cpp.
References GlobalClassList(), KKMLL::MLClassList::MLClassList(), and KKMLL::MLClassList::PushOnBack().
{
  if (parent == NULL)
    return NULL;
  GlobalClassList (); // Make sure that 'existingMLClasses' exists.
  MLClassListPtr results = new MLClassList ();
  results->PushOnBack (parent);
  MLClassPtr startingAncestor = NULL;
  for (auto existingMLClass: *existingMLClasses)
  {
    if (!existingMLClass)
      continue;
    startingAncestor = existingMLClass;
    MLClassPtr ancestor = startingAncestor->Parent ();
    while (ancestor != NULL)
    {
      if (ancestor == parent)
      {
        results->PushOnBack (startingAncestor);
        break;
      }
      ancestor = ancestor->Parent ();
      if (ancestor == startingAncestor)
        break;
    }
  }
  return results;
} /* BuildListOfDecendents */
void MLClass::ChangeNameOfClass (MLClassPtr mlClass, const KKStr & newName, bool & changeSuccessful) [static]
Changes the name of an existing class verifying that a duplicate does not get created.
Since the class name can not be duplicated and there is a nameIndex structure maintained by each 'MLClassList' instances we need to make sure the name is not already in use by another instance of 'mlClass'. This is done by first trying to update the 'nameIndex' in 'existingMLClasses' (list of all 'inageClass' instances in existence); if this is successful will then change the name in 'mlClass' and update all existing 'MLClassList' instances 'nameIndex' structures.
Parameters
in,out mlClass Class having its name changed; upon entry should contain its original name; if no other class already has its name it will be updated to the value in 'newName'.
in newName The new name that 'mlClass' is to receive.
out changeSuccessful Returns 'true' if name was changed; if set to false then the 'name' field in 'mlClass' will not be changed.
Definition at line 181 of file MLClass.cpp.
References KKB::KKStr::Concat(), KKB::GoalKeeper::EndBlock(), Name(), and KKB::GoalKeeper::StartBlock().
{
  successful = true;
  KKStr oldName = mlClass->Name();
  if (!blocker)
    CreateBlocker ();
  blocker->StartBlock ();
  existingMLClasses->ChangeNameOfClass (mlClass, oldName, newName, successful);
  if (!successful)
  {
    cerr << endl
         << "MLClass::ChangeNameOfClass 'existingMLClasses' failed to vahne name." <<
      endl
         << " NewName[" << newName << "]" << endl
         << " OldName[" << mlClass->Name () << "]" <<
      endl
         << endl;
    successful = false;
  }
  else
  {
    // It is okay to change the name; we will also need to inform all
    // instances of MLClassList that the name changed so they can
    // update their nameIndex structures.
    mlClass->Name (newName);
    map<MLClassListPtr,MLClassListPtr>::iterator idx;
    for (idx = existingClassLists.begin (); idx != existingClassLists.end (); ++idx)
  {
      MLClassListPtr list = idx->first;
      kkuint32 classInList = list->PtrToIdx (mlClass);
      if (classInList >= 0)
      {
        bool nameChangedInList = false;
        list->ChangeNameOfClass (mlClass, oldName, newName, nameChangedInList);
      }
    }
  }
  blocker->EndBlock ();
  return;
} /* ChangeNameOfClass */
kkint32 KKMLL::MLClass::ClassId () const [inline]
From MySQL table Classes, '-1' indicates that not loaded from mysql table.
Definition at line 136 of file MLClass.h.
Referenced by CreateNewMLClass(), and KKMLL::MLClassList::LookUpByClassId().
void KKMLL::MLClass::ClassId (kkint32 _classId) [inline]
Definition at line 137 of file MLClass.h.
Referenced by CreateNewMLClass().
{classId = _classId;}
float KKMLL::MLClass::CountFactor () const [inline]
Definition at line 139 of file MLClass.h.
{return countFactor;}
void KKMLL::MLClass::CountFactor (float _countFactor) [inline]
Definition at line 140 of file MLClass.h.
Referenced by KKMLL::TrainingClass::TrainingClass(), and KKMLL::XmlElementMLClass::XmlElementMLClass().
{countFactor = _countFactor;}
MLClassPtr MLClass::CreateNewMLClass (const KKStr & _name, kkint32 _classId = -1) [static]
Static method used to create a new instance of a MLClass object.
Used to get pointer to existing MLClass object that already exists in 'existingMLClasses'. If one does not exist then a new MLClass object with this name will be created.
This is the only method that can actually create a MLClass instance. The idea is that there is only one MLClass object ever created for each class. All MLClassList container objects will point to
Parameters
in _name Name of class to be created.
Returns
Pointer to an instance of 'MLClass' that will have the name '_name'.
Definition at line 100 of file MLClass.cpp.
References KKMLL::MLClassList::AddMLClass(), ClassId(), KKB::KKStr::Concat(), KKB::GoalKeeper::EndBlock(), GlobalClassList(), KKMLL::MLClassList::LookUpByName(), KKB::GoalKeeper::StartBlock(), and KKB::KKStr::ToUpper().
Referenced by KKMLL::BinaryClassParms::CreateFromTabDelStr(), KKMLL::ClassProbList::CreateFromXMLStream(), KKMLL::MLClassList::GetMLClassPtr(), KKMLL::MLClassList::GetUnKnownClass(), GetUnKnownClassStatic(), KKMLL::MLClassList::Load(), MLClassForGivenHierarchialLevel(), KKMLL::MLClassIndexList::ParseClassIndexList(), KKMLL::ClassAssignments::ParseToString(), KKMLL::ClassProbList::ReadXML(), KKMLL::FeatureEncoder::ReadXML(), KKMLL::ModelDual::ReconcilePredictions(), KKMLL::XmlElementMLClass::XmlElementMLClass(), and KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList().
{
  KKStr upperName = _name.ToUpper ();
  MLClassListPtr globalList = existingMLClasses;
  if (!globalList)
    globalList = GlobalClassList ();
  MLClassPtr mlClass = globalList->LookUpByName (_name);
  if (mlClass == NULL)
  {
    if (!blocker)
      CreateBlocker ();
    blocker->StartBlock ();
    mlClass = globalList->LookUpByName (_name);
    if (mlClass == NULL)
    {
      MLClassPtr temp = new MLClass (_name);
      temp->ClassId (_classId);
      existingMLClasses->AddMLClass (temp);
      mlClass = temp;
    }
    blocker->EndBlock ();
  }
  if ((mlClass->ClassId () < 0) && (_classId >= 0))
    ((MLClassPtr)mlClass)->ClassId (_classId);
  return mlClass;
} /* CreateNewMLClass */
const KKStr& KKMLL::MLClass::Description () const [inline]
Definition at line 142 of file MLClass.h.
{return description;}
void KKMLL::MLClass::Description (const KKStr & _description) [inline]
Definition at line 143 of file MLClass.h.
References KKB::KKStr::operator=().
Referenced by KKMLL::XmlElementMLClass::XmlElementMLClass().
{description = _description;}
void MLClass::FinalCleanUp () [static]
Call this as the last thing the application does, will delete all existing instances of 'MLClass'.
Call this at very end of program to clean up existingMLClasses.
Definition at line 269 of file MLClass.cpp.
References KKB::GoalKeeper::Destroy(), KKB::GoalKeeper::EndBlock(), KKMLL::FileDesc::FinalCleanUp(), KKMLL::FileDesc::FinalCleanUpRanAlready(), and KKB::GoalKeeper::StartBlock().
{
  if (!needToRunFinalCleanUp)
    return;
  blocker->StartBlock ();
  if (needToRunFinalCleanUp)
  {
    if (!FileDesc::FinalCleanUpRanAlready ())
    {
      //cerr << endl << "MLClass::FinalCleanUp ***ERROR*** Need to run MLClass::FinalCleanUp before
       FileDesc::FinalCleanUp" << endl << endl;
      FileDesc::FinalCleanUp ();
    }
    if (existingMLClasses)
    {
      delete existingMLClasses;
      existingMLClasses = NULL;
    }
    needToRunFinalCleanUp = false;
  }
  blocker->EndBlock ();
  GoalKeeper::Destroy (blocker);
  blocker = NULL;
} /* FinalCleanUp */
MLClassPtr MLClass::GetByClassId (kkint32 _classId) [static]
Definition at line 137 of file MLClass.cpp.
References GlobalClassList(), and KKMLL::MLClassList::LookUpByClassId().
{
  return GlobalClassList ()->LookUpByClassId (_classId);
} /* GetByClassId */
KKStr MLClass::GetClassNameFromDirName (const KKStr & subDir) [static]
Definition at line 372 of file MLClass.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Len(), KKB::KKStr::LocateLastOccurrence(), KKB::KKStr::operator=(), KKB::KKStr::operator[](), KKB::osGetRootNameOfDirectory(), and KKB::KKStr::SubStrPart().
Referenced by KKMLL::FeatureFileIO::LoadInSubDirectoryTree().
{
  KKStr className = osGetRootNameOfDirectory (subDir);
  kkint32 x = className.LocateLastOccurrence ('_');
  if (x > 0)
  {
    // Now lets eliminate any sequence number in name
    // We are assuming that a underscore{"_") character separates the class name from the sequence number.
    // So if there is an underscore character, and all the characters to the right of it are
    // numeric characters, then we will remove the underscore and the following numbers.
    kkuint32 y = x + 1;
    bool allFollowingCharsAreNumeric = true;
    while ((y < className.Len ()) && (allFollowingCharsAreNumeric))
    {
      char ch = className[y];
      allFollowingCharsAreNumeric = ((ch >= '0') && (ch <= '9'));
      y++;
    }
    if (allFollowingCharsAreNumeric)
    {
      className = className.SubStrPart (0, x - 1);
    }
  }
  return className;
} /* GetClassNameFromDirName */
MLClassPtr MLClass::GetUnKnownClassStatic () [static]
Definition at line 261 of file MLClass.cpp.
References CreateNewMLClass().
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink(), and KKMLL::SizeDistribution::Increment().
{
  return CreateNewMLClass ("UNKNOWN");
} /* GetUnKnownClassStatic */
MLClassListPtr MLClass::GlobalClassList () [static]
Definition at line 50 of file MLClass.cpp.
References KKB::GoalKeeper::EndBlock(), KKMLL::MLClassList::MLClassList(), and KKB::GoalKeeper::StartBlock().
Referenced by BuildListOfDecendents(), CreateNewMLClass(), GetByClassId(), and ResetAllParentsToAllClasses().
{
  if (!existingMLClasses)
  {
    CreateBlocker ();
    blocker->StartBlock ();
    if (!existingMLClasses)
    {
      existingMLClasses = new MLClassList ();
    existingMLClasses->Owner (true);
    }
    blocker->EndBlock ();
  }
  return existingMLClasses;
} /* GlobalClassList */
bool MLClass::IsAnAncestor (MLClassPtr c) const
Returns true if 'c' is an ancestor
Definition at line 405 of file MLClass.cpp.
References IsAnAncestor().
Referenced by IsAnAncestor().
{
  if (c == this)
    return true;
  if (parent == NULL)
    return false;
  return parent->IsAnAncestor (c);
}
bool KKMLL::MLClass::Mandatory () const [inline]
Definition at line 149 of file MLClass.h.
{return mandatory;}
void KKMLL::MLClass::Mandatory (bool _mandatory) [inline]
Definition at line 150 of file MLClass.h.
Referenced by KKMLL::XmlElementMLClass::XmlElementMLClass().
{mandatory = _mandatory;}
MLClassPtr MLClass::MLClassForGivenHierarchialLevel (KKB::kkuint16 level) const
Definition at line 427 of file MLClass.cpp.
References KKB::KKStr::Concat(), CreateNewMLClass(), and KKB::KKStr::Split().
Referenced by KKMLL::FeatureVectorList::ExtractExamplesForHierarchyLevel(), KKMLL::TrainingConfiguration2::ExtractListOfClassesForAGivenHierarchialLevel(), KKMLL::MLClassList::ExtractListOfClassesForAGivenHierarchialLevel(), and KKMLL::TrainingConfiguration2::GenerateAConfiguraionForAHierarchialLevel().
{
  VectorKKStr levelNames = name.Split ('_');
  KKStr fullLevelName = "";
  kkuint16 curLevel = 0;
  while ((curLevel < level) && (curLevel < levelNames.size ()))
  {
    if (curLevel < 1)
      fullLevelName = levelNames[curLevel];
    else
      fullLevelName << "_" << levelNames[curLevel];
    curLevel++;
  }
  return MLClass::CreateNewMLClass (fullLevelName);
} /* MLClassForGivenHierarchialLevel*/
const KKStr& KKMLL::MLClass::Name () const [inline]
Definition at line 154 of file MLClass.h.
Referenced by KKMLL::ConfusionMatrix2::AccuracyStr(), KKMLL::TrainingConfiguration2::AddATrainingClass(), KKMLL::MLClassList::AddMLClass(), ChangeNameOfClass(), KKMLL::BinaryClassParms::Class1Name(), KKMLL::BinaryClassParms::Class2Name(), KKMLL::FeatureVector::ClassName(), KKMLL::TrainingClass::ExpandedDirectory(), KKMLL::MLClassList::ExtractHTMLTableHeader(), KKMLL::FeatureFileIO::FeatureDataReSink(), KKMLL::ConfusionMatrix2::FMeasure(), KKMLL::TrainingConfiguration2::GenerateAConfiguraionForAHierarchialLevel(), KKMLL::SizeDistribution::Increment(), KKMLL::TrainingConfiguration2::LoadOtherClasssExamples(), KKMLL::FeatureVector::MLClassName(), KKMLL::ClassStatistic::Name(), KKMLL::TrainingClass::Name(), KKMLL::MLClassList::operator==(), ParentName(), KKMLL::FeatureVector::PredictedClassName(), KKMLL::SizeDistribution::PrintByClassCollumns(), KKMLL::ModelSvmBase::ProbabilitiesByClass(), KKMLL::ClassProbList::PushOnBack(), KKMLL::MLClassList::PushOnBack(), KKMLL::ClassProbList::PushOnFront(), KKMLL::MLClassList::PushOnFront(), KKMLL::ModelDual::ReconcilePredictions(), KKMLL::ModelDual::ReconcileProbAndVotes(), KKMLL::ModelSvmBase::RetrieveCrossProbTable(), KKMLL::ModelParamDual::ToCmdLineStr(), KKMLL::TrainingConfiguration2::TrainingConfiguration2(), KKMLL::FeatureEncoder::WriteXML(), and WriteXML().
{return name;}
kkuint16 MLClass::NumHierarchialLevels () const
Definition at line 419 of file MLClass.cpp.
References KKB::KKStr::InstancesOfChar().
{
  return (kkuint16)name.InstancesOfChar ('_') + 1;
}
MLClassPtr KKMLL::MLClass::Parent () const [inline]
Definition at line 157 of file MLClass.h.
{return parent;}
void KKMLL::MLClass::Parent (MLClassPtr _parent) [inline]
Definition at line 158 of file MLClass.h.
Referenced by ResetAllParentsToAllClasses(), and KKMLL::XmlElementMLClass::XmlElementMLClass().
{parent = _parent;}
const KKStr & MLClass::ParentName () const
Definition at line 354 of file MLClass.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), and Name().
{
  if (parent)
    return parent->Name ();
  return KKStr::EmptyStr ();
}
void MLClass::ResetAllParentsToAllClasses () [static]
Definition at line 229 of file MLClass.cpp.
References KKB::GoalKeeper::EndBlock(), GlobalClassList(), KKMLL::MLClassList::LookUpByName(), Parent(), and KKB::GoalKeeper::StartBlock().
{
  CreateBlocker ();
  blocker->StartBlock ();
  
  MLClassListPtr globalClassList = GlobalClassList ();
  MLClassPtr allClasses = globalClassList->LookUpByName ("AllClasses");
  MLClassList::iterator idx;
  for (idx = globalClassList->begin (); idx != globalClassList->end (); ++idx)
  {
    MLClassPtr ic = *idx;
    if (ic == allClasses)
      ic->Parent (NULL);
    else
      ic->Parent (allClasses);
  }
  blocker->EndBlock ();
} /* ResetAllParentsToNull */
bool KKMLL::MLClass::StoredOnDataBase () const [inline]
Definition at line 167 of file MLClass.h.
{return storedOnDataBase;}
void KKMLL::MLClass::StoredOnDataBase (bool _storedOnDataBase) [inline]
Definition at line 169 of file MLClass.h.
Referenced by KKMLL::XmlElementMLClass::XmlElementMLClass().
{storedOnDataBase = _storedOnDataBase;}
bool KKMLL::MLClass::Summarize () const [inline]
Indicates that Classification report should produce a summary column for the family of classes decedent from this class. Example classes that would set this field true are 'Protist', 'Phyto', 'Crustacean', etc....
Definition at line 171 of file MLClass.h.
void KKMLL::MLClass::Summarize (bool _summarize) [inline]
Definition at line 177 of file MLClass.h.
Referenced by KKMLL::XmlElementMLClass::XmlElementMLClass().
{summarize = _summarize;}
KKStr MLClass::ToString () const
Returns a KKStr representing this instance.
This string will later be written to a file.
Definition at line 364 of file MLClass.cpp.
References KKB::KKStr::Concat(), and KKB::KKStr::KKStr().
{
  KKStr str (name);
  return str;
}
bool KKMLL::MLClass::UnDefined () const [inline]
Definition at line 183 of file MLClass.h.
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink(), and KKMLL::MLClassList::Load().
{return unDefined;}
void KKMLL::MLClass::UnDefined (bool _unDefined) [inline]
Definition at line 184 of file MLClass.h.
{unDefined = _unDefined;}
const KKStr& KKMLL::MLClass::UpperName () const [inline]
Returns name capitalized.
Definition at line 155 of file MLClass.h.
Referenced by KKMLL::ClassStatisticList::ClassStatisticSortComparrison::operator()(), KKMLL::ClassStatisticList::ClassStatSortByCount::operator()(), KKMLL::MLClassList::MLClassNameComparison::operator()(), KKMLL::FeatureVectorList::ClassNameComparrison::operator()(), and KKMLL::FeatureVectorList::ClassNameComparrisonReversed::operator()().
void MLClass::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 448 of file MLClass.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), Name(), KKB::XmlTag::tagEmpty, KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::ModelParamDual::WriteXML(), KKMLL::MLClassList::WriteXML(), and KKMLL::XmlElementMLClass::WriteXML().
{
  XmlTag startTag ("MLClass", XmlTag::TagTypes::tagEmpty);
  if (!varName.Empty())
    startTag.AddAtribute ("VarName", varName);
  
  startTag.AddAtribute ("Name", name);
  if (parent != NULL)
    startTag.AddAtribute ("Parent", parent->Name ());
  if (classId >= 0)
    startTag.AddAtribute ("ClassId", classId);
  if (countFactor != 0.0f)
    startTag.AddAtribute ("CountFactor", countFactor);
  if (description.Empty ())
    startTag.AddAtribute ("Description", description);
  startTag.AddAtribute ("Mandatory", mandatory);
  startTag.AddAtribute ("StoredOnDataBase", storedOnDataBase);
  startTag.AddAtribute ("Summarize", summarize);
  startTag.WriteXML (o);
  o << endl;
} /* WriteXML */
Friends And Related Function Documentation
friend class KKQueue< MLClass > [friend]
Definition at line 118 of file MLClass.h.
friend class MLClassList [friend]
Definition at line 119 of file MLClass.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.cpp