KKMLL::FeatureVectorList Class Reference
Container class for FeatureVector derived objects.
#include <FeatureVector.h>
Classes
class BreakTieComparison
class BreakTieComparisonReversed
class ClassNameComparrison
class ClassNameComparrisonReversed
class ImageFileNameComparison
class ImageFileNameComparisonReversed
class ProbabilityComparison
class ProbabilityComparisonReversed
class RootNameComparrison
class RootNameComparrisonReversed
Public Types
typedef FeatureVectorList * FeatureVectorListPtr
typedef float FVFloat
enum IFL_SortOrder {
*
IFL_SortOrder::IFL_UnSorted,
IFL_SortOrder::IFL_ByName,
IFL_SortOrder::IFL_ByProbability,
IFL_SortOrder::IFL_ByBreakTie,
*
IFL_SortOrder::IFL_ByRootName,
IFL_SortOrder::IFL_ByClassName
 }
Represents the different orders that a list of FeatureVector instances in a FeatureVectorList object can be in.
Public Member Functions
FeatureVectorList ()
FeatureVectorList (FileDescPtr _fileDesc, bool _owner)
Will create a new empty list of FeatureVector's.
FeatureVectorList (const FeatureVectorList &examples, bool _owner)
Create a duplicate list, depending on the '_owner' parameter may also duplicate the contents.
FeatureVectorList (MLClassList &_mlClasses, FeatureVectorList &_examples)
Will create a list of consisting of the subset of examples in '_examples' which are members of ImagesClasses.
virtual ~FeatureVectorList ()
void AddQueue (const FeatureVectorList &examplesToAdd)
Add the contents of 'examplesToAdd' to the end of this list.
void AddSingleExample (FeatureVectorPtr _imageFeatures)
Same as PushOnBack.
FeatureNumList AllFeatures ()
Will return a FeatureNumList instance with all features selected.
bool AllFieldsAreNumeric () const
Returns true if all fields are numeric, no nominal fields.
void AppendToFile (KKStr _fileName, FeatureFileIOPtr _driver, const FeatureNumList &_selFeatures)
FeatureVectorPtr BinarySearchByName (const KKStr &_imageFileName) const
Will search for the example with the same name as '_imageFileName'.
void CalcStatsForFeatureNum (kkint32 _featureNum, kkint32 &_count, float &_total, float &_mean, float &_var, float &_stdDev)
KKStr ClassStatisticsStr () const
KKMLL::AttributeTypeVector CreateAttributeTypeTable () const
vector< kkint32 > CreateCardinalityTable () const
FeatureVectorListPtr CreateListForAGivenLevel (kkint32 level)
Will create a list of FeatureVectors where the class assignment will reflect the specified Hierarchy level specified by 'level'.
IFL_SortOrder CurSortOrder () const
virtual FeatureVectorListPtr Duplicate (bool _owner) const
Creates a duplicate of list using the same container.
virtual FeatureVectorListPtr DuplicateListAndContents () const
Creates a duplicate of list and also duplicates it contents.
KKStrListPtr ExtractDuplicatesByExampleFileName ()
FeatureVectorListPtr ExtractDuplicatesByRootImageFileName ()
Returns: a list of 'FeatureVector' objects that have duplicate root file names.
FeatureVectorListPtr ExtractExamplesForAGivenClass (MLClassPtr _mlClass, kkint32 _maxToExtract=-1, float _minSize=-1.0f) const
FeatureVectorListPtr ExtractExamplesForClassList (MLClassListPtr classes)
FeatureVectorListPtr ExtractExamplesForHierarchyLevel (kkuint32 level)
Will create a list of FeatureVectors where the class assignment will reflect the specified Hierarchy level specified by 'level'.
MLClassListPtr ExtractListOfClasses () const
VectorDouble ExtractMeanFeatureValues ()
FeatureVectorListPtr ExtractRandomSampling (float percentage, kkint32 minClassCount)
Will return a random sampling by class of our FeatureVector's; with a minimum per class of 'minClassCount'.
kkint32 FeatureCardinality (kkint32 featureNum) const
Returns the number of values defined for a Nominal Field.
kkint32 FeatureCount () const
KKMLL::AttributeType FeatureType (kkint32 featureNum) const
Returns the type of attribute for specified 'featureNum'.
KKStr FeatureTypeStr (kkint32 featureNum) const
const KKStr & FieldName (kkint32 featureNum) const
Returns name of Attribute Field.
const FileDescPtr FileDesc () const
const KKStr & FileName () const
void FileName (const KKStr &_fileName)
kkint32 GetClassCount (MLClassPtr c) const
Returns number of examples for a specific Class (MLClass).
ClassProbListPtr GetClassDistribution () const
ClassStatisticListPtr GetClassStatistics () const
Returns the number of FeatureVectors per class.
FeatureVectorPtr LookUpByImageFileName (const KKStr &_imageFileName) const
Returns a pointer to the FeatureVector which has '_imageFileName'.
FeatureVectorPtr LookUpByRootName (const KKStr &_rootName)
Returns a pointer to the FeatureVector who's ExampleFileName rootname = _rootName *.
float MajorityClassFraction () const
virtual FeatureVectorListPtr ManufactureEmptyList (bool _owner) const
Creates an instance of a Empty FeatureVectorList.
virtual kkint32 MemoryConsumedEstimated () const
bool MissingData () const
kkint32 NumEntriesOfAGivenClass (MLClassPtr mlClass) const
kkint32 NumOfFeatures () const
FeatureVectorListPtr OrderUsingNamesFromAFile (const KKStr &fileName, RunLog &log)
Using list of ImageFileNames in a file('fileName') create a new FeatureVectorList instance with examples in order based off contents of file. If error occurs will return NULL.
void PrintClassStatistics (std::ostream &o) const
void PrintClassStatisticsHTML (std::ostream &o) const
void PrintFeatureStatisticsByClass (std::ostream &o) const
void PushOnBack (FeatureVectorPtr image)
Overloading the PushOnBack function in KKQueue so we can monitor the Version and Sort Order.
void PushOnFront (FeatureVectorPtr image)
Overloading the PushOnFront function in KKQueue so we can monitor the Version and Sort Order.
void RemoveDuplicateEntries (bool allowDupsInSameClass, RunLog &runLog)
void RemoveEntriesWithMissingFeatures (RunLog &log)
void ResetFileDesc (FileDescPtr newFileDesc)
void ResetNumOfFeaturs (kkint32 newNumOfFeatures)
void ReSyncSymbolicData (FileDescPtr newFileDesc)
bool SameExceptForSymbolicData (const FeatureVectorList &otherData, RunLog &log) const
void SaveOrderingOfImages (const KKStr &fileName, bool &successful)
Will save into a file the current ordering of FeatureVector instances in list.
void SortByBreakTie (bool reversedOrder=false)
void SortByClass (bool reversedOrder=false)
void SortByImageFileName (bool reversedOrder=false)
void SortByProbability (bool reversedOrder=false)
void SortByRootName (bool reversedOrder=false)
FeatureVectorListPtr StratifyAmoungstClasses (kkint32 numOfFolds, RunLog &log)
FeatureVectorListPtr StratifyAmoungstClasses (MLClassListPtr mlClasses, kkint32 maxImagesPerClass, kkint32 numOfFolds, RunLog &log)
void SynchronizeSymbolicData (FeatureVectorList &otherData, RunLog &log)
kkint16 Version () const
void Version (kkint16 _version)
Additional Inherited Members
Detailed Description
Container class for FeatureVector derived objects.
Supports various functions with respect to maintaining a list of FeatureVector's. These include randomizing there order creating a stratified list by class, extracting a list of classes, sorting by various criteria.
Definition at line 205 of file FeatureVector.h.
Member Typedef Documentation
typedef FeatureVectorList* KKMLL::FeatureVectorList::FeatureVectorListPtr
Definition at line 210 of file FeatureVector.h.
typedef float KKMLL::FeatureVectorList::FVFloat
Definition at line 208 of file FeatureVector.h.
Member Enumeration Documentation
enum KKMLL::FeatureVectorList::IFL_SortOrder [strong]
Represents the different orders that a list of FeatureVector instances in a FeatureVectorList object can be in.
Enumerator
IFL_UnSorted
IFL_ByName
IFL_ByProbability
IFL_ByBreakTie
IFL_ByRootName
IFL_ByClassName
Definition at line 269 of file FeatureVector.h.
             {IFL_UnSorted,
              IFL_ByName,
              IFL_ByProbability,
              IFL_ByBreakTie,
              IFL_ByRootName,
              IFL_ByClassName
             };
Constructor & Destructor Documentation
FeatureVectorList::FeatureVectorList ()
When you use this constructor you need to define immediately provide the appropriate FileDesc instance via calling `ResetFileDesc` method.
Definition at line 291 of file FeatureVector.cpp.
References FeatureVectorList(), IFL_UnSorted, and KKB::KKStr::KKStr().
Referenced by FeatureVectorList().
                                     :
  KKQueue<FeatureVector> (true),
  curSortOrder (IFL_SortOrder::IFL_UnSorted),
  fileDesc (NULL),
  fileName (),
  numOfFeatures (0),
  version (-1)
{
}
FeatureVectorList::FeatureVectorList (FileDescPtr _fileDesc, bool _owner)
Will create a new empty list of FeatureVector's.
Parameters
in _fileDesc Describes the feature data such as number of features and their attributes.
in _owner True indicates that this list will own its contents and when this list is deleted it will call the destructor for all its contents.
out _log Log file to send messages to.
Definition at line 303 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), FeatureVectorList(), IFL_UnSorted, KKB::KKException::KKException(), KKB::KKStr::KKStr(), and KKMLL::FileDesc::NumOfFields().
Referenced by KKMLL::FeatureEncoder::CreateEncodedFeatureVector(), KKMLL::FeatureEncoder2::EncodeAllExamples(), KKMLL::FeatureEncoder::EncodeAllExamples(), KKMLL::FeatureEncoder2::EncodedFeatureVectorList(), FeatureVectorList(), KKMLL::GrayScaleImagesFVList::GrayScaleImagesFVList(), KKMLL::DuplicateImages::ListOfExamplesToDelete(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOColumn::LoadFile(), KKMLL::FeatureFileIOUCI::LoadFile(), KKMLL::FeatureFileIOC45::LoadFile(), KKMLL::FeatureFileIOSparse::LoadFile(), ManufactureEmptyList(), KKMLL::GrayScaleImagesFVProducer::ManufacturFeatureVectorList(), KKMLL::FactoryFVProducer::ManufacturFeatureVectorList(), KKMLL::GrayScaleImagesFVProducerFactory::ManufacturFeatureVectorList(), KKMLL::CrossValidationMxN::RunTrainAndTest(), SVM289_BFS::svm_train(), and SVM289_MFS::svm_train().
                                      :
  KKQueue<FeatureVector> (_owner),
  curSortOrder (IFL_SortOrder::IFL_UnSorted),
  fileDesc (_fileDesc),
  fileName (),
  numOfFeatures (0),
  version (-1)
{
  if (!fileDesc)
  {
    KKStr errMsg = "FeatureVectorList::FeatureVectorList *** ERROR *** FileDesc == NULL";
    cerr << endl << errMsg << endl <<endl;
    throw KKException (errMsg);
  }
  numOfFeatures = fileDesc->NumOfFields ();
}
FeatureVectorList::FeatureVectorList (const FeatureVectorList & examples, bool _owner)
Create a duplicate list, depending on the '_owner' parameter may also duplicate the contents.
Constructor that create a duplicate list of FeatureVectors;.
If '_owner' = true will create new instances of contents and own them. If 'owner' = false, will copy over pointers to existing instances.
Parameters
in examples Existing list of examples that we are going to copy.
in _owner If set to true will make a duplicate of the FeatureVectors in 'examples' and own then otherwise will just point to the same existing examples and not own them.
if (owner == true) then will also
duplicate the contents; that is each example in the list will be duplicated by calling the copy constructor.
And the new list will own these newly created examples.
Definition at line 347 of file FeatureVector.cpp.
References FeatureVectorList(), IFL_UnSorted, and KKB::KKStr::KKStr().
Referenced by Duplicate(), ExtractDuplicatesByRootImageFileName(), FeatureVectorList(), SVM289_MFS::Kernel::Kernel(), SVM289_BFS::Kernel::Kernel(), and KKMLL::Orderings::Orderings().
                                      :
   KKQueue<FeatureVector> (examples, _owner),
   curSortOrder (IFL_SortOrder::IFL_UnSorted),
   fileDesc (examples.fileDesc),
   fileName (examples.fileName),
   numOfFeatures (examples.numOfFeatures),
   version (examples.version)
{
}
FeatureVectorList::FeatureVectorList (MLClassList & _mlClasses, FeatureVectorList & _examples)
Will create a list of consisting of the subset of examples in '_examples' which are members of ImagesClasses.
Constructs a list of examples that are a subset of the ones in _examples as dictated by _mlClasses.
Will not own the contents; it will just point to the existing examples that were in '_examples'.
Parameters
in _mlClasses List of classes that we want to include.
in _examples Source of feature Vectors to extract from.
out _log Log file to send messages to.
The subset will consist of the examples who's mlClass is one of the ones in mlClasses. The new instance created will not own the contents; it will just point to the existing examples that were in '_examples'.
Parameters
in _mlClasses List of classes that the subset of examples will come from.
in _examples Examples that the subset will be derived from.
Definition at line 372 of file FeatureVector.cpp.
References FeatureVectorList(), IFL_UnSorted, KKB::KKStr::KKStr(), and KKMLL::MLClassIndexList::MLClassIndexList().
Referenced by FeatureVectorList().
                                      :
  KKQueue<FeatureVector> (false),
  curSortOrder (IFL_SortOrder::IFL_UnSorted),
  fileDesc (_examples.fileDesc),
  fileName (_examples.fileName),
  numOfFeatures (_examples.numOfFeatures),
  version (_examples.version)
{
  MLClassIndexListPtr classIdx = new MLClassIndexList (_mlClasses);
  for (auto idx: _examples)
  {
    if (classIdx->GetClassIndex (idx->MLClass ()) >= 0)
      PushOnBack (idx);
  }
  delete classIdx;
  classIdx = NULL;
}
FeatureVectorList::~FeatureVectorList () [virtual]
Definition at line 395 of file FeatureVector.cpp.
{
}
Member Function Documentation
void FeatureVectorList::AddQueue (const FeatureVectorList & examplesToAdd)
Add the contents of 'examplesToAdd' to the end of this list.
Definition at line 683 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), and NumOfFeatures().
Referenced by KKMLL::FeatureEncoder::CompressExamples(), KKMLL::TrainingProcess2::ExtractTrainingClassFeatures(), KKMLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), KKMLL::FeatureFileIO::LoadInSubDirectoryTree(), and StratifyAmoungstClasses().
{
  if (numOfFeatures != examplesToAdd.NumOfFeatures ())
  {
    KKStr errMsg = "FeatureVectorList::AddQueue ***ERROR*** 'examplesToAdd' has different
       'NumOfFeatures'.";
    errMsg << endl << " numOfFeatures [" << numOfFeatures << "]" <<
      endl
                   << " examplesToAdd.numOfFeatures[" << examplesToAdd.numOfFeatures << "]";
    cerr << endl << errMsg << endl << endl;
    throw errMsg;
  }
  if (QueueSize () < 1)
  {
    // Since we don't have any examples in the existing queue then the version number
    // of the queue that we are adding will be our version number.
    Version (examplesToAdd.Version ());
  }
  else
  {
    // Since there are examples in both queues, then they should have the same version number
    // otherwise the version number of the resulting KKQueue will be undefined (-1).
    if (examplesToAdd.Version () != Version ())
      Version (-1);
  }
  KKQueue<FeatureVector>::AddQueue (examplesToAdd);
} /* AddQueue */
void FeatureVectorList::AddSingleExample (FeatureVectorPtr _imageFeatures)
Same as PushOnBack.
Definition at line 665 of file FeatureVector.cpp.
References IFL_UnSorted, and PushOnBack().
Referenced by DuplicateListAndContents(), and ExtractExamplesForAGivenClass().
{
  PushOnBack (_imageFeatures);
  curSortOrder = IFL_SortOrder::IFL_UnSorted;
}
FeatureNumList FeatureVectorList::AllFeatures ()
Will return a FeatureNumList instance with all features selected.
Definition at line 554 of file FeatureVector.cpp.
References KKMLL::FeatureNumList::AllFeatures().
Referenced by KKMLL::TrainingConfiguration2::CreateFromFeatureVectorList(), and KKMLL::FeatureFileIO::LoadInSubDirectoryTree().
{
  return FeatureNumList::AllFeatures (fileDesc);
}
bool FeatureVectorList::AllFieldsAreNumeric () const
Returns true if all fields are numeric, no nominal fields.
Definition at line 493 of file FeatureVector.cpp.
References KKMLL::FileDesc::AllFieldsAreNumeric().
Referenced by KKMLL::FeatureEncoder::CreateEncodedFeatureVector(), and KKMLL::FeatureEncoder2::EncodedFeatureVectorList().
{
  return fileDesc->AllFieldsAreNumeric ();
}
void KKMLL::FeatureVectorList::AppendToFile (KKStr _fileName, FeatureFileIOPtr _driver, const FeatureNumList & _selFeatures)
FeatureVectorPtr FeatureVectorList::BinarySearchByName (const KKStr & _imageFileName) const
Will search for the example with the same name as '_imageFileName'.
If the list is already sorted in name order will use a Binary Search otherwise a linear search. The method 'SortByImageFileName' will set a flag 'curSortOrder' indicating if the examples are sorted. The idea is that if you know that will be doing many searches then for performance reasons you should call 'SortByImageFileName' first. The methods 'PushOnBack', 'PushOnFront', and 'AddSingleExample' will reset 'curSortOrder' to unsorted.
Definition at line 866 of file FeatureVector.cpp.
References KKMLL::FeatureVector::ExampleFileName(), IFL_ByName, IFL_ByRootName, KKB::KKStr::operator<(), KKB::KKStr::operator>(), and KKB::osDisplayWarning().
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink(), and LookUpByImageFileName().
{
  if ((curSortOrder != IFL_SortOrder::IFL_ByName) &&
       (curSortOrder != IFL_SortOrder::IFL_ByRootName)
      )
  {
    cerr << endl
         << "FeatureVectorList::BinarySearchByName **** ERROR ****" << endl
         << endl
         << " List is Not sorted in ExampleFileName Order" <<
      endl
         << endl;
    osDisplayWarning ("FeatureVectorList::BinarySearchByName Invalid Sort Order.");
    exit (-1);
  }
  kkint32 low = 0;
  kkint32 high = QueueSize () - 1;
  kkint32 mid;
  FeatureVectorPtr example = NULL;
  while (low <= high)
  {
    mid = (low + high) / 2;
    example = IdxToPtr (mid);
    if (example->ExampleFileName () < _imageFileName)
    {
      low = mid + 1;
    }
    else if (example->ExampleFileName () > _imageFileName)
    {
      high = mid - 1;
    }
    else
    {
      return example;
    }
  }
  return NULL;
} /* BinarySearchByName */
void FeatureVectorList::CalcStatsForFeatureNum (kkint32 _featureNum, kkint32 & _count, float & _total, float & _mean, float & _var, float & _stdDev)
Definition at line 1292 of file FeatureVector.cpp.
References KKMLL::FeatureVector::FeatureData(), and NumOfFeatures().
Referenced by PrintFeatureStatisticsByClass().
{
  _count = 0;
  _total = 0.0f;
  _mean = 0.0f;
  _var = 0.0f;
  _stdDev = 0.0f;
  if ((_featureNum < 0) || (_featureNum >= NumOfFeatures ()))
  {
    cerr << endl
         << "FeatureVectorList::CalcStatsForFeatureNum *** ERROR *** Invalid FeatureNum[" <<
      _featureNum << "]" << endl
         << " FeatureNum [" << _featureNum << "]" <<
      endl
         << " NumOfFeatures[" <<
      NumOfFeatures () << "]" << endl
         << endl;
    _count = -1;
    return;
  }
  if (QueueSize () == 0)
    return;
    
  iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    FeatureVectorPtr i = *idx;
    _total += i->FeatureData (_featureNum);
    _count++;
  }
  if (_count < 1)
  {
    _mean = 0.0f;
    _var = 0.0f;
    _stdDev = 0.0f;
    return;
  }
  _mean = _total / (float)_count;
  float totalSquareDelta = 0.0f;
  for (idx = begin (); idx != end (); idx++)
  {
    FeatureVectorPtr i = *idx;
    float delta = i->FeatureData (_featureNum) - _mean;
    totalSquareDelta += delta * delta;
  }
  _var = totalSquareDelta / _count;
  _stdDev = sqrt (_var);
} /* CalcStatsForFeatureNum */
KKStr FeatureVectorList::ClassStatisticsStr () const
Definition at line 1111 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), and GetClassStatistics().
{
  ClassStatisticListPtr stats = GetClassStatistics ();
  KKStr s (stats->QueueSize () * 30 + 100);
  s << "Total_Images\t" << QueueSize () << endl;
  s << endl;
  s << "Total_Classes\t" << stats->QueueSize () << endl;
  s << endl;
  s << "Class_Name" << "\t" << "Count" << endl;
  ClassStatisticList::iterator statsIDX;
  for (statsIDX = stats->begin (); statsIDX != stats->end (); statsIDX++)
  {
    ClassStatisticPtr cs = *statsIDX;
    s << cs->Name () << "\t" << cs->Count () << endl;
  }
  delete stats;
  return s;
} /* ClassStatisticsStr */
AttributeTypeVector FeatureVectorList::CreateAttributeTypeTable () const
Definition at line 535 of file FeatureVector.cpp.
References KKMLL::FileDesc::CreateAttributeTypeTable().
{
  ValidateFileDescAndFieldNum (0, "CreateAttributeTypeTable");
  return fileDesc->CreateAttributeTypeTable ();
} /* CreateAttributeTypeTable */
vector< kkint32 > FeatureVectorList::CreateCardinalityTable () const
Definition at line 544 of file FeatureVector.cpp.
References KKMLL::FileDesc::CreateCardinalityTable().
{
  ValidateFileDescAndFieldNum (0, "CreateCardinalityTable");
  return fileDesc->CreateCardinalityTable ();
} /* CreateAttributeTypeTable */
FeatureVectorListPtr FeatureVectorList::CreateListForAGivenLevel (kkint32 level)
Will create a list of FeatureVectors where the class assignment will reflect the specified Hierarchy level specified by 'level'.
The hierarchy of a given class will be indicated by underscore characters in the class name.
ex: Level 1: gelatinous
      Level 2: gelatinous_hydromedusae
      Level 3: gelatinous_hydromedusae_solmundella
If the 'level' parameter is set to 1 then all FeatureVectors who's class name starts with 'gelatinous' will
       be grouped
together under the class name 'gelatinous_hydromedusae'.
Definition at line 1791 of file FeatureVector.cpp.
References ExtractListOfClasses(), ManufactureEmptyList(), and KKMLL::MLClassList::SortByName().
{
  FeatureVectorListPtr examplesLabeledForAppropriateLevel =
      ManufactureEmptyList (true);
  MLClassListPtr allClasses = ExtractListOfClasses ();
  allClasses->SortByName ();
  MLClassList::iterator idx;
  idx = allClasses->begin ();
  while (idx != allClasses->end ())
  {
    MLClassPtr curClass = *idx;
    KKStr curClassNameForThisLevel = GetClassNameByHierarchyLevel (
      curClass->Name (), level);
    if (curClassNameForThisLevel.Empty ())
    {
      idx++;
      continue;
    }
    else
    {
      MLClassPtr curClassForThisLevel = MLClass::CreateNewMLClass (
      curClassNameForThisLevel);
      MLClassPtr nextClassForThisLevel = curClassForThisLevel;
      while ((idx != allClasses->end ()) && (nextClassForThisLevel == curClassForThisLevel))
      {
        {
          FeatureVectorListPtr examplesForCurClass =
      ExtractExamplesForAGivenClass (curClass);
          FeatureVectorListPtr reLabeledExamples = examplesForCurClass->
      DuplicateListAndContents ();
          delete examplesForCurClass; examplesForCurClass = NULL;
          FeatureVectorList::iterator idx2;
          for (idx2 = reLabeledExamples->begin (); idx2 != reLabeledExamples->end (); idx2++)
          {
            FeatureVectorPtr fv = *idx2;
            fv->MLClass (curClassForThisLevel);
          }
          examplesLabeledForAppropriateLevel->AddQueue (*reLabeledExamples);
          reLabeledExamples->Owner (false);
          delete reLabeledExamples; reLabeledExamples = NULL;
        }
        // Get next Class to process.
        idx++;
        if (idx != allClasses->end ())
        {
          curClass = *idx;
          curClassNameForThisLevel = GetClassNameByHierarchyLevel (curClass->
      Name (), level);
          nextClassForThisLevel = MLClass::CreateNewMLClass (
      curClassNameForThisLevel);
        }
      }
    }
  }
  delete allClasses; allClasses = NULL;
  return examplesLabeledForAppropriateLevel;
} /* CreateListForAGivenLevel */
IFL_SortOrder KKMLL::FeatureVectorList::CurSortOrder () const [inline]
Definition at line 283 of file FeatureVector.h.
{return curSortOrder;}
FeatureVectorListPtr FeatureVectorList::Duplicate (bool _owner) const [virtual]
Creates a duplicate of list using the same container.
Reimplemented in KKMLL::GrayScaleImagesFVList.
Definition at line 416 of file FeatureVector.cpp.
References FeatureVectorList().
Referenced by KKMLL::Model::TrainModel().
{
  return new FeatureVectorList (*this, _owner);
}
FeatureVectorListPtr FeatureVectorList::DuplicateListAndContents () const [virtual]
Creates a duplicate of list and also duplicates it contents.
Returns
Duplicated list with hard-copy of its contents.
Duplicated list with hard copy of its contents.
Reimplemented in KKMLL::GrayScaleImagesFVList.
Definition at line 1095 of file FeatureVector.cpp.
References AddSingleExample(), KKMLL::FeatureVector::FeatureVector(), and ManufactureEmptyList().
Referenced by KKMLL::FeatureEncoder::CreateEncodedFeatureVector(), KKMLL::FeatureEncoder2::EncodedFeatureVectorList(), KKMLL::CrossValidationVoting::RunValidationOnly(), and KKMLL::CrossValidation::RunValidationOnly().
{
  FeatureVectorListPtr copyiedList = ManufactureEmptyList (true);
  for (kkint32 idx = 0; idx < QueueSize (); idx++)
  {
    FeatureVectorPtr curImage = IdxToPtr (idx);
    copyiedList->AddSingleExample (new FeatureVector (*curImage));
  }
  
  return copyiedList;
} /* DuplicateListAndContents */
KKStrListPtr FeatureVectorList::ExtractDuplicatesByExampleFileName ()
Definition at line 810 of file FeatureVector.cpp.
References KKB::KKStrList::KKStrList(), and SortByImageFileName().
{
  SortByImageFileName ();
  KKStrListPtr duplicateExamples = new KKStrList (true);
  if (QueueSize () < 2)
    return duplicateExamples;
  FeatureVectorList::iterator iIDX = this->begin ();
  while (iIDX != end ())
  {
    FeatureVectorPtr example = *iIDX; ++iIDX;
    if (!example)
      continue;
    KKStr lastFileName = example->ExampleFileName ();
    if (example->ExampleFileName () == lastFileName)
    {
      duplicateExamples->PushOnBack (new KKStr (example->
      ExampleFileName ()));
      if (iIDX != end ())
      {
        example = *iIDX;
        ++iIDX;
      }
      else
      {
        example = NULL;
      }
      while ((example != NULL) && (example->ExampleFileName () == lastFileName))
      {
        if (iIDX != end ())
        {
          example = *iIDX;
          ++iIDX;
        }
        else
        {
          example = NULL;
        }
      }
    }
  }
  return duplicateExamples;
} /* ExtractDuplicateImageFileNames */
FeatureVectorListPtr FeatureVectorList::ExtractDuplicatesByRootImageFileName ()
Returns: a list of 'FeatureVector' objects that have duplicate root file names.
The returned list will not own these items. All instances of the duplicate objects will be returned. Ex: if three instances have the same ExampleFileName all three will be returned.
Definition at line 1201 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), KKMLL::FeatureVector::ExampleFileName(), FeatureVectorList(), ManufactureEmptyList(), KKB::KKStr::operator!=(), KKB::KKStr::operator=(), KKB::KKStr::operator==(), KKB::osGetRootName(), PushOnBack(), and SortByRootName().
{
  FeatureVectorListPtr duplicateList = this->
      ManufactureEmptyList (false);
  if (QueueSize () < 2)
  {
    // Since there are less than 2 elements in the list,
    // There is no way that there can be any duplicates in the list.
    return duplicateList;
  }
  FeatureVectorList workList (*this,
                               false // owner = false, only create a list of pointers to existing
       instances
                              ); //
  workList.SortByRootName (false);
  
  FeatureVectorList::iterator idx;
  idx = workList.begin ();
  FeatureVectorPtr lastExample = *idx; ++idx;
  FeatureVectorPtr example = *idx; ++idx;
  KKStr lastRootName = osGetRootName (lastExample->
      ExampleFileName ());
  KKStr rootName;
  while (example)
  {
    rootName = osGetRootName (example->ExampleFileName ());
    if (rootName != lastRootName)
    {
      lastRootName = rootName;
      lastExample = example;
      if (idx == workList.end ())
        example = NULL;
      else
      {
        example = *idx;
        ++idx;
      }
    }
    else
    {
      duplicateList->PushOnBack (lastExample);
      while ((example != NULL) && (rootName == lastRootName))
      {
        duplicateList->PushOnBack (example);
        if (idx == workList.end ())
          example = NULL;
        else
        {
          example = *idx;
          ++idx;
        }
        if (example)
          rootName = osGetRootName (example->ExampleFileName ());
      }
    }
  }
  return duplicateList;
} /* ExtractDuplicatesByRootImageFileName */
FeatureVectorListPtr FeatureVectorList::ExtractExamplesForAGivenClass (MLClassPtr _mlClass, kkint32 _maxToExtract = -1, float _minSize = -1.0f) const
Definition at line 750 of file FeatureVector.cpp.
References AddSingleExample(), KKB::KKStr::Concat(), ManufactureEmptyList(), KKMLL::FeatureVector::MLClass(), KKMLL::FeatureVector::OrigSize(), and KKB::osDisplayWarning().
Referenced by ExtractRandomSampling(), PrintFeatureStatisticsByClass(), KKMLL::Model::ReduceTrainExamples(), and StratifyAmoungstClasses().
{
  kkint32 idx;
  kkint32 qSize = QueueSize ();
  FeatureVectorPtr example;
  kkint32 numExtracted = 0;
  if (_maxToExtract < 1)
    _maxToExtract = QueueSize ();
  // Create a new list structure that does not own the Images it contains. This way when
  // this structure is deleted. The example it contains are not deleted.
  FeatureVectorListPtr extractedImages = this->
      ManufactureEmptyList (false);
  if (!extractedImages)
  {
    KKStr err = "***ERROR***, ExtractExamplesForAGivenClass, Could not allocate more space.";
    cerr << endl << err << endl;
    osDisplayWarning (err);
    exit (-1);
  }
  for (idx = 0; ((idx < qSize)); idx++)
  {
    example = IdxToPtr (idx);
    if (((example->MLClass () == _mlClass) || (!_mlClass)))
    {
      if (example->OrigSize () >= _minSize)
      {
        extractedImages->AddSingleExample (example);
        numExtracted++;
        if (numExtracted >= _maxToExtract)
          break;
      }
    }
  }
  return extractedImages;
} /* ExtractExamplesForAGivenClass */
FeatureVectorListPtr FeatureVectorList::ExtractExamplesForClassList (MLClassListPtr classes)
Definition at line 795 of file FeatureVector.cpp.
References ManufactureEmptyList().
Referenced by KKMLL::CrossValidation::CrossValidation(), and KKMLL::CrossValidationVoting::CrossValidationVoting().
{
  FeatureVectorListPtr subSetForClassList =
      ManufactureEmptyList (false);
  for (auto idx: *classes)
  {
    FeatureVectorListPtr examplesForClass =
      ExtractExamplesForAGivenClass (idx);
    if (examplesForClass)
      subSetForClassList->AddQueue (*examplesForClass);
  }
  return subSetForClassList;
} /* ExtractExamplesForClassList */
FeatureVectorListPtr FeatureVectorList::ExtractExamplesForHierarchyLevel (kkuint32 level)
Will create a list of FeatureVectors where the class assignment will reflect the specified Hierarchy level specified by 'level'.
The hierarchy of a given class will be indicated by underscore characters in the class name.
ex: Level 1: gelatinous
      Level 2: gelatinous_hydromedusae
      Level 3: gelatinous_hydromedusae_solmundella
If the 'level' parameter is set to 1 then all FeatureVectors who's class name starts with 'gelatinous' will
       be
grouped together under the class name 'gelatinous_hydromedusae'.
Bug
Bug This method appears to be a duplicate of 'CreateListForAGivenLevel'; We should verify this and get rid of one of them.
Definition at line 730 of file FeatureVector.cpp.
References KKMLL::FeatureVector::FeatureVector(), ManufactureEmptyList(), KKMLL::FeatureVector::MLClass(), KKMLL::MLClass::MLClassForGivenHierarchialLevel(), and PushOnBack().
Referenced by KKMLL::TrainingProcess2::CreateTrainingProcessForLevel().
{
  FeatureVectorListPtr examples = ManufactureEmptyList (true);
  FeatureVectorList::const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    const FeatureVectorPtr fv = *idx;
    FeatureVectorPtr newFV = new FeatureVector (*fv);
    newFV->MLClass (fv->MLClass ()->MLClassForGivenHierarchialLevel (level));
    examples->PushOnBack (newFV);
  }
  return examples;
} /* ExtractExamplesForHierarchyLevel */
MLClassListPtr FeatureVectorList::ExtractListOfClasses () const
Definition at line 632 of file FeatureVector.cpp.
References KKMLL::FeatureVector::MLClass(), and KKMLL::MLClassList::MLClassList().
Referenced by KKMLL::TrainingConfiguration2::CreateFromFeatureVectorList(), CreateListForAGivenLevel(), ExtractRandomSampling(), KKMLL::Orderings::Orderings(), PrintFeatureStatisticsByClass(), KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::FeatureFileIOC45::SaveFile(), StratifyAmoungstClasses(), KKMLL::ModelOldSVM::TrainModel(), and KKMLL::Model::TrainModel().
{
  MLClassPtr lastClass = NULL;
  map<MLClassPtr,MLClassPtr> ptrIndex;
  map<MLClassPtr,MLClassPtr>::iterator ptrIndexItr;
  FeatureVectorList::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    FeatureVectorPtr example = *idx;
    MLClassPtr newClass = example->MLClass ();
    if (newClass == lastClass)
      continue;
    lastClass = newClass;
    ptrIndexItr = ptrIndex.find (newClass);
    if (ptrIndexItr == ptrIndex.end ())
    {
      lastClass = newClass;
      ptrIndex.insert (pair<MLClassPtr,MLClassPtr> (newClass, newClass));
    }
  }
  MLClassListPtr classes = new MLClassList ();
  for (ptrIndexItr = ptrIndex.begin (); ptrIndexItr != ptrIndex.end (); ++ptrIndexItr)
    classes->PushOnBack (ptrIndexItr->first);
  return classes;
} /* ExtractListOfClasses */
VectorDouble FeatureVectorList::ExtractMeanFeatureValues ()
Definition at line 1604 of file FeatureVector.cpp.
References KKMLL::FeatureVector::FeatureDataConst().
{
  kkint32 fn = 0;
  FeatureVectorList::const_iterator idx;
  VectorDouble totals (this->NumOfFeatures (), 0.0);
  VectorDouble means (this->NumOfFeatures (), 0.0);
  for (idx = begin (); idx != end (); idx++)
  {
    const FeatureVectorPtr fv = *idx;
    const float* fd = fv->FeatureDataConst ();
    for (fn = 0; fn < NumOfFeatures (); fn++)
      totals[fn] += fd[fn];
  }
  for (fn = 0; fn < NumOfFeatures (); fn++)
    means[fn] = totals[fn] / (double)this->QueueSize ();
  return means;
} /* ExtractMeanFeatureValues */
FeatureVectorListPtr FeatureVectorList::ExtractRandomSampling (float percentage, kkint32 minClassCount)
Will return a random sampling by class of our FeatureVector's; with a minimum per class of 'minClassCount'.
Parameters
in percentage The percentage between 0.0 and 100.0 of each class to randomly sample.
in minClassCount The minimum per class to keep.
Parameters
percentage A percentage between 0.0 and 100.0
Definition at line 1629 of file FeatureVector.cpp.
References ExtractExamplesForAGivenClass(), ExtractListOfClasses(), ManufactureEmptyList(), and KKMLL::MLClassList::SortByName().
{
  if (percentage <= 0.0f)
  {
    percentage = 0.0f;
  }
  if (percentage > 100.0f)
  {
    percentage = 1.0f;
  }
  kkint32 newSize = (kkint32)(0.5f + (float)QueueSize () * percentage / 100.0f);
  FeatureVectorListPtr randomSampled = ManufactureEmptyList (false
      );
  MLClassListPtr classes = ExtractListOfClasses ();
  classes->SortByName ();
  MLClassList::iterator idx;
  for (idx = classes->begin (); idx != classes->end (); idx++)
  {
    MLClassPtr ic = *idx;
    FeatureVectorListPtr examplesThisClass =
      ExtractExamplesForAGivenClass (ic);
    examplesThisClass->RandomizeOrder ();
    kkint32 numExamplesThisClass = Max (minClassCount, ((kkint32)(0.5f + (float)(
      examplesThisClass->QueueSize ()) * percentage / 100.0f)));
    if (numExamplesThisClass > examplesThisClass->QueueSize ())
      numExamplesThisClass = examplesThisClass->QueueSize ();
    for (kkint32 zed = 0; zed < numExamplesThisClass; zed++)
      randomSampled->PushOnBack (examplesThisClass->IdxToPtr (zed));
    delete examplesThisClass; examplesThisClass = NULL;
  }
  delete classes; classes = NULL;
  randomSampled->RandomizeOrder ();
  return randomSampled;
} /* ExtractRandomSampling */
kkint32 FeatureVectorList::FeatureCardinality (kkint32 featureNum) const
Returns the number of values defined for a Nominal Field.
See also
FileDesc::Cardinality
Definition at line 526 of file FeatureVector.cpp.
References KKMLL::FileDesc::Cardinality().
{
  ValidateFileDescAndFieldNum (featureNum, "FeatureCardinality");
  return fileDesc->Cardinality (featureNum);
}
kkint32 KKMLL::FeatureVectorList::FeatureCount () const [inline]
Definition at line 284 of file FeatureVector.h.
{return numOfFeatures;}
AttributeType FeatureVectorList::FeatureType (kkint32 featureNum) const
Returns the type of attribute for specified 'featureNum'.
See also
FileDesc
Definition at line 509 of file FeatureVector.cpp.
References KKMLL::FileDesc::Type().
{
  ValidateFileDescAndFieldNum (featureNum, "FeatureType");
  return fileDesc->Type (featureNum);
} /* FeatureType */
KKStr FeatureVectorList::FeatureTypeStr (kkint32 featureNum) const
Definition at line 518 of file FeatureVector.cpp.
References KKMLL::AttributeTypeToStr(), and KKMLL::FileDesc::Type().
{
  ValidateFileDescAndFieldNum (featureNum, "FeatureTypeStr");
  return AttributeTypeToStr (fileDesc->Type (featureNum));
} /* FeatureType */
const KKStr & FeatureVectorList::FieldName (kkint32 featureNum) const
Returns name of Attribute Field.
Definition at line 500 of file FeatureVector.cpp.
References KKMLL::FileDesc::FieldName().
{
  ValidateFileDescAndFieldNum (featureNum, "FieldName");
  return fileDesc->FieldName (featureNum);
} /* FeatureName */
const FileDescPtr KKMLL::FeatureVectorList::FileDesc () const [inline]
Definition at line 285 of file FeatureVector.h.
Referenced by KKMLL::FeatureFileIO::AppendToFile(), KKMLL::SVMparam::AvgNumOfFeatures(), KKMLL::TrainingConfiguration2::CreateFromFeatureVectorList(), KKMLL::TrainingProcess2::CreateTrainingProcessForLevel(), KKMLL::DuplicateImages::DuplicateImages(), KKMLL::FeatureFileIO::FeatureDataReSink(), KKMLL::GrayScaleImagesFVList::GrayScaleImagesFVList(), KKMLL::NormalizationParms::NormalizationParms(), KKMLL::Orderings::Orderings(), SameExceptForSymbolicData(), KKMLL::FeatureFileIO::SaveFeatureFile(), KKMLL::FeatureFileIOColumn::SaveFile(), KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::FeatureFileIOUCI::SaveFile(), KKMLL::FeatureFileIOC45::SaveFile(), KKMLL::FeatureFileIOSparse::SaveFile(), SynchronizeSymbolicData(), and KKMLL::ModelOldSVM::TrainModel().
{return fileDesc;}
const KKStr& KKMLL::FeatureVectorList::FileName () const [inline]
Definition at line 286 of file FeatureVector.h.
Referenced by KKMLL::Orderings::CreateOrderingsObjFromFileIfAvaliable(), and KKMLL::Orderings::Orderings().
{return fileName;}
void KKMLL::FeatureVectorList::FileName (const KKStr & _fileName) [inline]
Definition at line 292 of file FeatureVector.h.
References KKB::KKStr::operator=().
{fileName = _fileName;}
kkint32 FeatureVectorList::GetClassCount (MLClassPtr c) const
Returns number of examples for a specific Class (MLClass).
Definition at line 714 of file FeatureVector.cpp.
Referenced by NumEntriesOfAGivenClass().
{
  kkint32 count =0;
  FeatureVectorList::const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    if ((*idx)->MLClass () == c)
      count++;
  }
  return count;
} /* GetClassCount */
ClassProbListPtr FeatureVectorList::GetClassDistribution () const
Definition at line 1170 of file FeatureVector.cpp.
References KKMLL::ClassProb::ClassProb(), KKMLL::ClassProbList::ClassProbList(), KKMLL::ClassStatistic::Count(), GetClassStatistics(), KKMLL::ClassStatistic::MLClass(), and KKMLL::ClassProbList::PushOnBack().
Referenced by KKMLL::TrainingProcess2::CreateModelsFromTrainingData().
{
  ClassStatisticListPtr stats = GetClassStatistics ();
  ClassProbListPtr distribution = new ClassProbList (true);
  kkuint32 countTotal = 0;
  ClassStatisticList::const_iterator idx;
  for (idx = stats->begin (); idx != stats->end (); ++idx)
  {
    ClassStatisticPtr cs = *idx;
    countTotal += cs->Count ();
  }
  if (countTotal > 0)
  {
    for (idx = stats->begin (); idx != stats->end (); ++idx)
    {
      ClassStatisticPtr cs = *idx;
      distribution->PushOnBack (new ClassProb (cs->MLClass (), ((float)(cs->
      Count ()) / (float)countTotal), 0));
    }
  }
  delete stats;
  stats = NULL;
  return distribution;
} /* GetClassDistribution */
ClassStatisticListPtr FeatureVectorList::GetClassStatistics () const
Returns the number of FeatureVectors per class.
See also
ClassStatisticList
Definition at line 1138 of file FeatureVector.cpp.
References KKMLL::ClassStatistic::ClassStatistic(), KKMLL::ClassStatisticList::ClassStatisticList(), KKMLL::ClassStatistic::Increment(), KKMLL::ClassStatisticList::LookUpByMLClass(), KKMLL::FeatureVector::MLClass(), KKMLL::ClassStatisticList::PushOnBack(), and KKMLL::ClassStatisticList::SortByClassName().
Referenced by KKMLL::SVMparam::AvgNumOfFeatures(), ClassStatisticsStr(), GetClassDistribution(), MajorityClassFraction(), PrintClassStatistics(), PrintClassStatisticsHTML(), KKMLL::Model::ReduceTrainExamples(), and KKMLL::FeatureFileIOC45::SaveFile().
{
  ClassStatisticListPtr classStatistics = new
      ClassStatisticList (true);
  MLClassPtr mlClass = NULL;
  FeatureVectorPtr example = NULL;
  FeatureVectorList::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    example = *idx;
    mlClass = example->MLClass ();
    
    ClassStatisticPtr classStatistic = classStatistics->
      LookUpByMLClass (mlClass);
    if (classStatistic == NULL)
    {
      classStatistic = new ClassStatistic (mlClass, 0);
      classStatistics->PushOnBack (classStatistic);
    }
    classStatistic->Increment ();
  }
  classStatistics->SortByClassName ();
  return classStatistics;
} /* GetClassStatistics */
FeatureVectorPtr FeatureVectorList::LookUpByImageFileName (const KKStr & _imageFileName) const
Returns a pointer to the FeatureVector which has '_imageFileName'.
If the list is currently sorted by ExampleFileName (curSortOrder == IFL_ByName) then a Binary Search is performed otherwise a sequential search is performed.
Definition at line 974 of file FeatureVector.cpp.
References BinarySearchByName(), and IFL_ByName.
{
  if (curSortOrder == IFL_SortOrder::IFL_ByName)
    return BinarySearchByName (_imageFileName);
  else
  {
    FeatureVectorPtr example = NULL;
    for (auto tempExample: *this)
    {
      if (tempExample->ExampleFileName () == _imageFileName)
         example = tempExample;
    }
    return example;
  }
} /* LookUpByImageFileName */
FeatureVectorPtr FeatureVectorList::LookUpByRootName (const KKStr & _rootName)
Returns a pointer to the FeatureVector who's ExampleFileName rootname = _rootName *.
If the list is currently sorted by ExampleFileName (curSortOrder == IFL_ByRootName) then a Binary Search is performed otherwise a sequential search is performed. The parameter _rootName is assumed to be just the root name of the file. that is you used osGetRootName to et the root part.
Definition at line 916 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), KKMLL::FeatureVector::ExampleFileName(), IFL_ByRootName, KKB::KKStr::operator<(), KKB::KKStr::operator==(), KKB::KKStr::operator>(), and KKB::osGetRootName().
{
  FeatureVectorPtr example = NULL;
  if (curSortOrder != IFL_SortOrder::IFL_ByRootName)
  {
    cerr << endl
         << "FeatureVectorList::LookUpByRootName ***WARNING*** List is NOT SORTED by RootName." <<
      endl
         << endl;
    FeatureVectorList::iterator idx;
    for (idx = begin (); idx != end (); idx++)
    {
      example = *idx;
      if (_rootName == osGetRootName (example->ExampleFileName ()))
        return example;
    }
    return NULL;
  }
  else
  {
    kkint32 low = 0;
    kkint32 high = QueueSize () - 1;
    kkint32 mid;
    while (low <= high)
    {
      mid = (low + high) / 2;
      example = IdxToPtr (mid);
      KKStr tempName = osGetRootName (example->
      ExampleFileName ());
      if (tempName < _rootName)
      {
        low = mid + 1;
      }
      else if (tempName > _rootName)
      {
        high = mid - 1;
      }
      else
      {
        return example;
      }
    }
  }
  return NULL;
} /* LookUpByRootName */
float FeatureVectorList::MajorityClassFraction () const
Return's the fraction that the majority class makes up in this list.
Definition at line 1441 of file FeatureVector.cpp.
References KKMLL::ClassStatistic::Count(), and GetClassStatistics().
{
  ClassStatisticListPtr classStats = GetClassStatistics ();
  if (!classStats)
    return 0.0f;
  ClassStatisticPtr largestClassStat = NULL;
  kkuint32 largestClassSize = 0;
  ClassStatisticList::const_iterator idx;
  for (idx = classStats->begin (); idx != classStats->end (); idx++)
  {
    ClassStatisticPtr classStats = *idx;
    if (classStats->Count () > largestClassSize)
    {
      largestClassSize = classStats->Count ();
      largestClassStat = classStats;
    }
  }
  float fraction = float (largestClassSize) / float (size ());
  delete classStats;
  return fraction;
} /* MajorityClassFraction */
FeatureVectorListPtr FeatureVectorList::ManufactureEmptyList (bool _owner) const [virtual]
Creates an instance of a Empty FeatureVectorList.
Reimplemented in KKMLL::GrayScaleImagesFVList.
Definition at line 423 of file FeatureVector.cpp.
References FeatureVectorList().
Referenced by CreateListForAGivenLevel(), DuplicateListAndContents(), ExtractDuplicatesByRootImageFileName(), ExtractExamplesForAGivenClass(), ExtractExamplesForClassList(), ExtractExamplesForHierarchyLevel(), ExtractRandomSampling(), OrderUsingNamesFromAFile(), KKMLL::Model::ReduceTrainExamples(), KKMLL::CrossValidationVoting::RunCrossValidation(), KKMLL::CrossValidation::RunCrossValidation(), and StratifyAmoungstClasses().
{
  return new FeatureVectorList (fileDesc, _owner);
}
kkint32 FeatureVectorList::MemoryConsumedEstimated () const [virtual]
Definition at line 401 of file FeatureVector.cpp.
References KKMLL::FeatureVector::MemoryConsumedEstimated(), and KKB::KKStr::MemoryConsumedEstimated().
Referenced by KKMLL::Model::MemoryConsumedEstimated(), and KKMLL::TrainingProcess2::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = sizeof (FeatureVectorList) + fileName.
      MemoryConsumedEstimated ();
  FeatureVectorList::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    FeatureVectorPtr fv = *idx;
    memoryConsumedEstimated += fv->MemoryConsumedEstimated ();
  }
  return memoryConsumedEstimated;
} /* MemoryConsumedEstimated */
bool FeatureVectorList::MissingData () const
Returns true if 1 or more entries have missing data.
Definition at line 1674 of file FeatureVector.cpp.
References KKMLL::FeatureVector::MissingData().
{
  FeatureVectorList::const_iterator idx;
  FeatureVectorPtr i = NULL;
  for (idx = begin (); idx != end (); idx++)
  {
    i = *idx;
    if (i->MissingData ())
      return true;
  }
  return false;
} /* MissingData */
kkint32 KKMLL::FeatureVectorList::NumEntriesOfAGivenClass (MLClassPtr mlClass) const [inline]
Definition at line 452 of file FeatureVector.h.
References GetClassCount().
{return GetClassCount (mlClass);}
kkint32 KKMLL::FeatureVectorList::NumOfFeatures () const [inline]
Definition at line 287 of file FeatureVector.h.
Referenced by AddQueue(), CalcStatsForFeatureNum(), KKMLL::NormalizationParms::NormalizationParms(), KKMLL::NormalizationParms::NormalizeExamples(), and PrintFeatureStatisticsByClass().
{return numOfFeatures;}
FeatureVectorListPtr FeatureVectorList::OrderUsingNamesFromAFile (const KKStr & fileName, RunLog & log)
Using list of ImageFileNames in a file('fileName') create a new FeatureVectorList instance with examples in order based off contents of file. If error occurs will return NULL.
Parameters
in fileName Name of file that contains a list of ExampleFileName's with one entry per line.
Returns
A new list of FeatureVector instances in the order dictated by 'fileName'.
Definition at line 991 of file FeatureVector.cpp.
References ManufactureEmptyList(), KKB::osFOPEN(), and KKB::KKStr::Str().
{
  FILE* in = osFOPEN (fileName.Str (), "r");
  if (!in)
  {
    log.Level (-1) << endl
                   << "FeatureVectorList::OrderUsingNamesFromAFile *** ERROR ***" <<
      endl
                   << " Could not open file[" << fileName << "]." <<
      endl
                   << endl;
    return NULL;
  }
  FeatureVectorPtr example = NULL;
  FeatureVectorListPtr orderedImages = ManufactureEmptyList (false
      );
  char buff[1024];
  while (fgets (buff, sizeof (buff), in))
  {
    KKStr txtLine (buff);
    if (txtLine.SubStrPart (0, 1) == "//")
    {
      // Comment line, will ignore.
      continue;
    }
    KKStr exampleFileName = txtLine.ExtractToken ("\n\r\t");
    if (orderedImages->LookUpByImageFileName (exampleFileName))
    {
      // Image file name used more than once, will treat as error
      log.Level (-1) << endl
                     << "FeatureVectorList::OrderUsingNamesFromAFile *** ERROR ***" <<
      endl
                     << " ExampleFileName[" << exampleFileName << "] occurred more
       than once in file." << endl
                     << endl;
      fclose (in);
      delete orderedImages;
      return NULL;
    }
    example = LookUpByImageFileName (exampleFileName);
    if (!example)
    {
      // Image file name not in list, will treat as error.
      log.Level (-1) << endl
                     << "FeatureVectorList::OrderUsingNamesFromAFile *** ERROR ***" <<
      endl
                     << " ExampleFileName[" << exampleFileName << "] Not in list." <<
      endl
                     << endl;
      fclose (in);
      delete orderedImages;
      return NULL;
    }
    orderedImages->PushOnBack (example);
  }
  fclose (in);
  return orderedImages;
} /* OrderUsingNamesFromAFile */
void FeatureVectorList::PrintClassStatistics (std::ostream & o) const
Definition at line 1473 of file FeatureVector.cpp.
References GetClassStatistics().
Referenced by KKMLL::TrainingProcess2::ReportTraningClassStatistics().
{
  ClassStatisticListPtr stats = GetClassStatistics ();
  o << "Total_Images\t" << QueueSize () << endl;
  o << endl;
  o << "Total_Classes\t" << stats->QueueSize () << endl;
  o << endl;
  ClassStatisticList::const_iterator statsIDX;
  kkint32 index = 0;
  o << "Class_Name" << "\t" << "Index" << "\t" << "Count" << endl;
  for (statsIDX = stats->begin (); statsIDX != stats->end (); ++statsIDX)
  {
    o << (*statsIDX)->Name () << "\t" << index << "\t" << (*statsIDX)->Count () <<
      endl;
    index++;
  }
  delete stats;
  stats = NULL;
  return;
} /* PrintClassStatistics */
void FeatureVectorList::PrintClassStatisticsHTML (std::ostream & o) const
Definition at line 1499 of file FeatureVector.cpp.
References GetClassStatistics().
{
  ClassStatisticListPtr stats = GetClassStatistics ();
  o << "<table align=\"center\" border=\"2\" cellpadding=\"4\">" << endl
    << "<thead>" << endl;
  o << "<tr>"
    << "<th align=\"left\">Class<br />Name</th>"
    << "<th align=\"center\">Index</th>"
    << "<th align=\"center\">Count</th>"
    << "</tr>"
    << endl
    << "</thead>" << endl;
  o << "<tbody>" << endl;
  ClassStatisticList::iterator statsIDX;
  kkint32 index = 0;
  for (statsIDX = stats->begin (); statsIDX != stats->end (); statsIDX++)
  {
    ClassStatistic& statistic = **statsIDX;
    o << "<tr>"
      << "<td align=\"left\">" << statistic.Name () << "</td>"
      << "<td align=\"center\">" << index << "</td>"
      << "<td align=\"center\">" << statistic.Count () << "</td>"
      << "</tr>"
      << endl;
    index++;
  }
  o << "<tr>"
    << "<td align=\"left\">" << "Total" << "</td>"
    << "<td align=\"center\">" << "&nbsp" << "</td>"
    << "<td align=\"center\">" << QueueSize () << "</td>"
    << "</tr>"
    << endl;
  o << "</tbody>" << endl;
  o << "</table>" << endl;
  delete stats;
  return;
} /* PrintClassStatisticsHTML */
void FeatureVectorList::PrintFeatureStatisticsByClass (std::ostream & o) const
Definition at line 1547 of file FeatureVector.cpp.
References CalcStatsForFeatureNum(), ExtractExamplesForAGivenClass(), ExtractListOfClasses(), and NumOfFeatures().
{
  o << "Class" << "\t"
    << "ClassIdx" << "\t"
    << "FeatureNum" << "\t"
    << "FieldName" << "\t"
    << "Type" << "\t"
    << "Count" << "\t"
    << "Total" << "\t"
    << "Mean" << "\t"
    << "Var" << "\t"
    << "StdDev"
    << endl;
  MLClassListPtr mlClasses = ExtractListOfClasses ();
  MLClassList::const_iterator cIDX;
  kkint32 classIdx = 0;
  for (cIDX = mlClasses->begin (); cIDX != mlClasses->end (); cIDX++)
  {
    MLClassPtr mlClass = *cIDX;
    FeatureVectorListPtr imagesThisClass =
      ExtractExamplesForAGivenClass (mlClass);
      
    kkint32 featureNum;
    for (featureNum = 0; featureNum < imagesThisClass->NumOfFeatures (); featureNum++)
    {
      kkint32 count;
      float total, mean, var, stdDev;
      imagesThisClass->CalcStatsForFeatureNum (featureNum, count, total, mean, var,
      stdDev);
      o << mlClass->Name () << "\t"
        << classIdx << "\t"
        << featureNum << "\t"
        << FieldName (featureNum) << "\t"
        << FeatureTypeStr (featureNum) << "\t"
        << count << "\t"
        << total << "\t"
        << mean << "\t"
        << var << "\t"
        << stdDev
        << endl;
    }
    delete imagesThisClass;
    o << endl;
    classIdx++;
  }
  delete mlClasses;
  mlClasses = NULL;
} /* PrintFeatureStatisticsByClass */
void FeatureVectorList::PushOnBack (FeatureVectorPtr image)
Overloading the PushOnBack function in KKQueue so we can monitor the Version and Sort Order.
Definition at line 598 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), IFL_UnSorted, KKB::KKException::KKException(), KKB::KKStr::KKStr(), and KKMLL::FeatureVector::NumOfFeatures().
Referenced by AddSingleExample(), KKMLL::FeatureEncoder::CreateEncodedFeatureVector(), KKMLL::FeatureEncoder2::EncodeAllExamples(), KKMLL::FeatureEncoder::EncodeAllExamples(), KKMLL::FeatureEncoder2::EncodedFeatureVectorList(), ExtractDuplicatesByRootImageFileName(), ExtractExamplesForHierarchyLevel(), KKMLL::FeatureFileIO::FeatureDataReSink(), KKMLL::DuplicateImages::ListOfExamplesToDelete(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOColumn::LoadFile(), KKMLL::FeatureFileIOUCI::LoadFile(), KKMLL::FeatureFileIOC45::LoadFile(), KKMLL::CrossValidationVoting::RunCrossValidation(), KKMLL::CrossValidation::RunCrossValidation(), and svm_binary_svc_probability().
{
  if (example->NumOfFeatures () != numOfFeatures)
  {
    KKStr errMsg (150);
    errMsg << "FeatureVectorList::PushOnBack ***ERROR*** Mismatch numOfFeatures[" << numOfFeatures <<
      "] example->NumOfFeaturess[" << example->NumOfFeatures () << "]";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  KKQueue<FeatureVector>::PushOnBack (example);
  curSortOrder = IFL_SortOrder::IFL_UnSorted;
} /* Push On Back */
void FeatureVectorList::PushOnFront (FeatureVectorPtr image)
Overloading the PushOnFront function in KKQueue so we can monitor the Version and Sort Order.
Definition at line 615 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), IFL_UnSorted, KKB::KKException::KKException(), KKB::KKStr::KKStr(), and KKMLL::FeatureVector::NumOfFeatures().
{
  if (example->NumOfFeatures () != numOfFeatures)
  {
    KKStr errMsg (150);
    errMsg << "FeatureVectorList::PushOnFront ***ERROR*** Mismatch numOfFeatures[" << numOfFeatures <<
       "] example->NumOfFeaturess[" << example->NumOfFeatures () << "]";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  KKQueue<FeatureVector>::PushOnFront (example);
  curSortOrder = IFL_SortOrder::IFL_UnSorted;
} /* PushOnFront */
void FeatureVectorList::RemoveDuplicateEntries (bool allowDupsInSameClass, RunLog & runLog)
Definition at line 673 of file FeatureVector.cpp.
References KKMLL::DuplicateImages::DuplicateImages(), and KKMLL::DuplicateImages::PurgeDuplicates().
{
  DuplicateImages dupDetector (this, runLog);
  dupDetector.PurgeDuplicates (this, allowDupsInSameClass, NULL);
} /* RemoveDuplicateEntries */
void FeatureVectorList::RemoveEntriesWithMissingFeatures (RunLog & log)
Will delete entries from list that have missing data.
Definition at line 445 of file FeatureVector.cpp.
{
  log.Level (50) << "FeatureVectorList::RemoveEntriesWithMissingFeatures" <<
      endl;
  vector<FeatureVectorPtr> entriesToBeDeleted;
  for (iterator idx = begin (); idx != end (); idx++)
  {
    FeatureVectorPtr example = *idx;
    if (example->MissingData ())
      entriesToBeDeleted.push_back (example);
  }
  for (kkint32 x = 0; x < (kkint32)entriesToBeDeleted.size (); x++)
  {
    FeatureVectorPtr example = entriesToBeDeleted[x];
    DeleteEntry (example);
    if (Owner ())
      delete example;
  }
} /* RemoveEntriesWithMissingFeatures */
void FeatureVectorList::ResetFileDesc (FileDescPtr newFileDesc)
You would use this if youRecalc all the data to a newer version of the file.
Definition at line 575 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKMLL::FileDesc::NumOfFields(), and KKMLL::FeatureVector::ResetNumOfFeatures().
{
  if (!newFileDesc)
  {
    KKStr errMsg = "FeatureVector::ResetFileDesc ***ERROR*** newFileDesc == NULL.";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  fileDesc = newFileDesc;
  numOfFeatures = fileDesc->NumOfFields ();
  for (iterator idx = begin (); idx != end (); idx++)
  {
    FeatureVectorPtr i = *idx;
    i->ResetNumOfFeatures (numOfFeatures);
  }
} /* ResetFileDesc */
void FeatureVectorList::ResetNumOfFeaturs (kkint32 newNumOfFeatures)
Definition at line 561 of file FeatureVector.cpp.
References KKMLL::FeatureVector::ResetNumOfFeatures().
{
  numOfFeatures = newNumOfFeatures;
  for (iterator idx = begin (); idx != end (); idx++)
  {
    FeatureVectorPtr i = *idx;
    i->ResetNumOfFeatures (newNumOfFeatures);
  }
} /* ResetNumOfFeaturs */
void FeatureVectorList::ReSyncSymbolicData (FileDescPtr newFileDesc)
Definition at line 1694 of file FeatureVector.cpp.
References KKMLL::FeatureVector::AddFeatureData(), KKMLL::FileDesc::Cardinality(), KKB::KKStr::Concat(), KKMLL::FeatureVector::FeatureData(), KKMLL::FileDesc::FieldName(), KKMLL::FileDesc::GetNominalValue(), KKB::KKException::KKException(), KKMLL::FileDesc::LookUpNominalCode(), KKMLL::FileDesc::NumOfFields(), KKB::operator<<(), KKMLL::Symbolic, and KKMLL::FileDesc::Type().
Referenced by SynchronizeSymbolicData().
{
  kkint32 fieldNum;
  VectorInt symbolicFields;
  vector<VectorInt> lookUpTables;
  for (fieldNum = 0; fieldNum < (kkint32)newFileDesc->NumOfFields (); fieldNum++)
  {
    if (newFileDesc->Type (fieldNum) == AttributeType::Symbolic)
    {
      symbolicFields.push_back (fieldNum);
      VectorInt lookUpTable;
      kkint32 x;
      for (x = 0; x < fileDesc->Cardinality (fieldNum); x++)
      {
        const KKStr& nominalValue = fileDesc->GetNominalValue (fieldNum, x);
        kkint32 newCd = newFileDesc->LookUpNominalCode (fieldNum, nominalValue);
        if (newCd < 0)
        {
          KKStr errMsg;
          errMsg << "FeatureVectorList::ReSyncSymbolicData ***ERROR*** FieldNum[" << fieldNum << "]
       FieldName[" << newFileDesc->FieldName (fieldNum) << "] Nominal Value[" << nominalValue << "] is
       missing.";
          cerr << errMsg;
          throw KKException (errMsg);
        }
        lookUpTable.push_back (newCd);
      }
      lookUpTables.push_back (lookUpTable);
    }
  }
  FeatureVectorList::iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    FeatureVectorPtr i = *idx;
    kkuint32 x;
    for (x = 0; x < symbolicFields.size (); x++)
    {
      fieldNum = symbolicFields[x];
      kkint32 oldCode = kkint32 (0.5f + i->FeatureData (fieldNum));
      kkint32 newCode = lookUpTables[x][oldCode];
      i->AddFeatureData (fieldNum, float (newCode));
    }
  }
  fileDesc = newFileDesc;
} /* ReSyncSymbolicData */
bool FeatureVectorList::SameExceptForSymbolicData (const FeatureVectorList & otherData, RunLog & log) const
Determines if the other FeatreVectorList has the same underlining layout; that is each field is of the same type and meaning. This way we can determine if one list contains Apples while the other contains Oranges.
Definition at line 436 of file FeatureVector.cpp.
References FileDesc(), and KKMLL::FileDesc::SameExceptForSymbolicData().
{
  return fileDesc->SameExceptForSymbolicData (*(otherData.
      FileDesc ()), log);
}
void FeatureVectorList::SaveOrderingOfImages (const KKStr & fileName, bool & successful)
Will save into a file the current ordering of FeatureVector instances in list.
This file can then be used at a later time to reproduce the exact same ordering of FeatureVector objects from a file.
See also
OrderUsingNamesFromAFile
Parameters
in fileName Name of file where ImagFileNames will be written to.
out successful Indicates if list is successfully written.
Definition at line 1056 of file FeatureVector.cpp.
{
  _successful = true;
  ofstream o (_fileName.Str ());
  if (!o.is_open ())
  {
    _successful = false;
    return;
  }
  o << "// " << "Time Written [" << osGetLocalDateTime () << "]" <<
      endl;
  o << "// " << "File Name [" << _fileName << "]" << endl;
  o << "// " << "Size [" << QueueSize () << "]" <<
      endl;
  o << "//" << endl;
  FeatureVectorList::iterator idx;
  for (idx = begin (); idx != end (); idx++)
    o << (*idx)->ExampleFileName () << endl;
  o.close ();
  return;
} /* OrderUsingNamesFormAFile */
void FeatureVectorList::SortByBreakTie (bool reversedOrder = false)
Definition at line 2132 of file FeatureVector.cpp.
References IFL_ByBreakTie.
{
  if (!reversedOrder)
  {
    BreakTieComparison c;
    sort (begin (), end (), c);
  }
  else
  {
    BreakTieComparisonReversed c;
    sort (begin (), end (), c);
  }
  curSortOrder = IFL_SortOrder::IFL_ByBreakTie;
} /* SortByProbability */
void FeatureVectorList::SortByClass (bool reversedOrder = false)
Definition at line 2093 of file FeatureVector.cpp.
References IFL_ByClassName.
{
 if (!reversedOrder)
  {
    ClassNameComparrison c;
    sort (begin (), end (), c);
  }
  else
  {
    ClassNameComparrisonReversed c;
    sort (begin (), end (), c);
  }
  curSortOrder = IFL_SortOrder::IFL_ByClassName;
} /* SortByClass */
void FeatureVectorList::SortByImageFileName (bool reversedOrder = false)
Definition at line 2152 of file FeatureVector.cpp.
References IFL_ByName.
Referenced by ExtractDuplicatesByExampleFileName().
{
  if (!reversedOrder)
  {
    ImageFileNameComparison c;
    sort (begin (), end (), c);
  }
  else
  {
    ImageFileNameComparisonReversed c;
    sort (begin (), end (), c);
  }
  curSortOrder = IFL_SortOrder::IFL_ByName;
} /* SortByImageFileName */
void FeatureVectorList::SortByProbability (bool reversedOrder = false)
Definition at line 2113 of file FeatureVector.cpp.
References IFL_ByProbability.
{
  if (!reversedOrder)
  {
    ProbabilityComparison c;
    sort (begin (), end (), c);
  }
  else
  {
    ProbabilityComparisonReversed c;
    sort (begin (), end (), c);
  }
  curSortOrder = IFL_SortOrder::IFL_ByProbability;
} /* SortByProbability */
void FeatureVectorList::SortByRootName (bool reversedOrder = false)
Definition at line 2075 of file FeatureVector.cpp.
References IFL_ByRootName.
Referenced by ExtractDuplicatesByRootImageFileName(), and KKMLL::FeatureFileIO::FeatureDataReSink().
{
 if (!reversedOrder)
  {
    RootNameComparrison c;
    sort (begin (), end (), c);
  }
  else
  {
    RootNameComparrisonReversed c;
    sort (begin (), end (), c);
  }
  curSortOrder = IFL_SortOrder::IFL_ByRootName;
} /* SortByRootName */
FeatureVectorListPtr FeatureVectorList::StratifyAmoungstClasses (kkint32 numOfFolds, RunLog & log)
Definition at line 1354 of file FeatureVector.cpp.
References ExtractListOfClasses(), and StratifyAmoungstClasses().
{
  MLClassListPtr classes = ExtractListOfClasses ();
  FeatureVectorListPtr stratifiedExamples =
      StratifyAmoungstClasses (classes, -1, numOfFolds, log);
  delete classes; classes = NULL;
  return stratifiedExamples;
} /* StratifyAmoungstClasses */
FeatureVectorListPtr FeatureVectorList::StratifyAmoungstClasses (MLClassListPtr mlClasses, kkint32 maxImagesPerClass, kkint32 numOfFolds, RunLog & log)
Definition at line 1370 of file FeatureVector.cpp.
References AddQueue(), ExtractExamplesForAGivenClass(), ManufactureEmptyList(), and SplitImagesAmongstFolds().
Referenced by StratifyAmoungstClasses().
{
  log.Level (10) << "FeatureVectorList::StratifyAmoungstClasses" << endl;
  kkint32 foldNum;
  kkint32 x;
  FeatureVectorListPtr* folds = new FeatureVectorListPtr[
      numOfFolds];
  for (x = 0; x < numOfFolds; x++)
    folds[x] = ManufactureEmptyList (false);
  MLClassPtr mlClass = NULL;
  MLClassList::iterator icIDX;
  for (icIDX = mlClasses->begin (); icIDX != mlClasses->end (); ++icIDX)
  {
    mlClass = *icIDX;
    FeatureVectorListPtr imagesInClass =
      ExtractExamplesForAGivenClass (mlClass);
    if (imagesInClass->QueueSize () < numOfFolds)
    {
      log.Level (-1) << endl
                     << "FeatureVectorList::DistributesImagesRandomlyWithInFolds ***ERROR***" <<
      endl
                     << endl
                     << "*** ERROR ***, Not enough examples to split amongst the different folds." <<
      endl
                     << " Class [" << mlClass->Name () << "]." <<
      endl
                     << " Number of Images[" << imagesInClass->
      QueueSize () << "]." << endl
                     << " Number of Folds [" << numOfFolds << "]." <<
      endl
                     << endl;
    
      KKStr msg;
      msg << "Not enough Images[" << imagesInClass->QueueSize () << "] "
          << "for Class[" << mlClass->Name () << "] "
          << "to distribute in Folds.";
      if (!osIsBackGroundProcess ())
      osDisplayWarning (msg);
    }
    imagesInClass->RandomizeOrder ();
    imagesInClass->RandomizeOrder ();
    SplitImagesAmongstFolds (numOfFolds, maxImagesPerClass, folds, imagesInClass);
    delete imagesInClass;
    imagesInClass = NULL;
  }
  FeatureVectorListPtr stratafiedImages =
      ManufactureEmptyList (false);
  for (foldNum = 0; foldNum < numOfFolds; foldNum++)
  {
    folds[foldNum]->RandomizeOrder ();
    folds[foldNum]->RandomizeOrder ();
    stratafiedImages->AddQueue (*folds[foldNum]);
    delete folds[foldNum];
    folds[foldNum] = NULL;
  }
  delete[] folds;
  folds = NULL;
  return stratafiedImages;
} /* StratifyAmoungstClasses */
void FeatureVectorList::SynchronizeSymbolicData (FeatureVectorList & otherData, RunLog & log)
Definition at line 1750 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), FileDesc(), KKB::KKException::KKException(), KKMLL::FileDesc::MergeSymbolicFields(), KKB::KKStr::operator=(), ReSyncSymbolicData(), and KKMLL::FileDesc::SameExceptForSymbolicData().
{
  if (!fileDesc->SameExceptForSymbolicData (*(otherData.
      FileDesc ()), log))
  {
    KKStr errMsg;
    errMsg = "FeatureVectorList::SynchronizeSymbolicData ***ERROR*** The two datasets have more than
       SymbolicData differences.";
    log.Level (-1) << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  FileDescPtr newFileDesc = FileDesc::MergeSymbolicFields (*
      fileDesc, *(otherData.FileDesc ()), log);
  ReSyncSymbolicData (newFileDesc);
  otherData.ReSyncSymbolicData (newFileDesc);
} /* SynchronizeSymbolicData */
kkint16 KKMLL::FeatureVectorList::Version () const [inline]
Definition at line 288 of file FeatureVector.h.
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink().
{return version;}
void KKMLL::FeatureVectorList::Version (kkint16 _version) [inline]
Definition at line 293 of file FeatureVector.h.
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink().
{version = _version;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVector.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVector.cpp