KKMLL::FeatureVectorProducer Class Reference
A abstract class that is meant to compute a FeatureVector from a source image.
#include <FeatureVectorProducer.h>
Public Types
typedef FeatureVectorProducer * FeatureVectorProducerPtr
Public Member Functions
FeatureVectorProducer (const KKStr &_name, FactoryFVProducerPtr _factory)
virtual ~FeatureVectorProducer ()
virtual FeatureVectorPtr ComputeFeatureVector (const Raster &image, const MLClassPtr knownClass, RasterListPtr intermediateImages, float priorReductionFactor, RunLog &runLog)=0
Compute a FeatureVector for the supplied 'image'.
virtual FeatureVectorPtr ComputeFeatureVectorFromImage (const KKStr &fileName, const MLClassPtr knownClass, RasterListPtr intermediateImages, RunLog &runLog)
Compute a FeatureVector from the image file specified by 'fileName'.
FactoryFVProducerPtr Factory () const
Returns pointer to factory that instantiated this instance.
kkuint32 FeatureCount () const
const KKStr & FeatureName (kkuint32 fieldNum) const
virtual const type_info * FeatureVectorListTypeId () const =0
Returns the 'type_info' of the FeatureVectorList derived class that can contain instances in 'FeatureVector' instances created by this producer.
virtual const type_info * FeatureVectorTypeId () const =0
Returns the 'type_info' of the FeatureVector that this instance of 'FeatureVectorProducer' creates.
FileDescConstPtr FileDesc () const
Returns back a `FileDesc` instance that describes the features that this instance of 'FeatureVectorProducer' creates. The class derived form this class is responsible for creating the FileDesc instance. When this method is called if `fileDesc` equals NULL then will call `DefineFileDesc`, which is a pure virtual method that will be implemented by the derived class, to instantiate a new instance.
virtual FeatureVectorListPtr ManufacturFeatureVectorList (bool owner, RunLog &runLog) const =0
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors by this FeatureVectorProducer.
kkuint32 MaxNumOfFeatures ()
const KKStr & Name () const
Returns a kkint16 description of the FeatureVector which can be used as part/all of a File or Directory name.
virtual kkint16 Version () const =0
Protected Member Functions
virtual FileDescPtr DefineFileDesc () const =0
Detailed Description
A abstract class that is meant to compute a FeatureVector from a source image.
Applications that want to utilize this library will either use one of the provided `FeatureVectorProducer` derived classes or supply their own. This class will be responsible for computing a FeatureVector from a supplied Image.
Each FeatureVectorProducer derived class will need to have a unique name that will be supplied when constructed. This name will be used later when it is required to locate the appropriate FeatureVectorProducer to utilize.
See also
FeatureVectorList
PostLarvaeFV
FeatureFileIO
Definition at line 60 of file FeatureVectorProducer.h.
Member Typedef Documentation
typedef FeatureVectorProducer* KKMLL::FeatureVectorProducer::FeatureVectorProducerPtr
Definition at line 63 of file FeatureVectorProducer.h.
Constructor & Destructor Documentation
FeatureVectorProducer::FeatureVectorProducer (const KKStr & _name, FactoryFVProducerPtr _factory)
Parameters
_factory Pointer to factory that instantiated this instance.
Definition at line 28 of file FeatureVectorProducer.cpp.
References KKB::KKStr::KKStr().
Referenced by KKMLL::GrayScaleImagesFVProducer::GrayScaleImagesFVProducer().
                                               :
    factory (_factory),
    fileDesc (NULL),
    name (_name)
{
}
FeatureVectorProducer::~FeatureVectorProducer () [virtual]
Definition at line 40 of file FeatureVectorProducer.cpp.
{
}
Member Function Documentation
virtual FeatureVectorPtr KKMLL::FeatureVectorProducer::ComputeFeatureVector (const Raster & image, const MLClassPtr knownClass, RasterListPtr intermediateImages, float priorReductionFactor, RunLog & runLog) [pure virtual]
Compute a FeatureVector for the supplied 'image'.
Parameters
in image
in knownClass The class label that will be assigned to this Feature vector.
in,out intermediateImages If not NULL will save a copy of the intermediate images created during Feature Computation; the call will own the list and its contents.
in priorReductionFactor The reduction that was done to the image prior to calling this routine; if no size change was made then set this field to 1.0. The FeaureVector computation routines will use this field to adjust SizeDependent features appropriately. the value of this parameter represents the number of pixels that were reduced to 1 pixel. A value of 3 indicates (3 x 3) pixels were reduced to 1 pixel.
in log Logging file.
Returns
The resultant Feature vector computed.
Implemented in KKMLL::GrayScaleImagesFVProducer.
Referenced by ComputeFeatureVectorFromImage(), KKMLL::FeatureFileIO::FeatureDataReSink(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
FeatureVectorPtr FeatureVectorProducer::ComputeFeatureVectorFromImage (const KKStr & fileName, const MLClassPtr knownClass, RasterListPtr intermediateImages, RunLog & runLog) [virtual]
Compute a FeatureVector from the image file specified by 'fileName'.
Parameters
in image
in knownClass The class label that will be assigned to this Feature vector.
in,out intermediateImages If not NULL will save a copy of the intermediate images created during Feature Computation; the call will own the list and its contents.
in log Logging file.
Returns
The resultant Feature vector computed.
Definition at line 47 of file FeatureVectorProducer.cpp.
References ComputeFeatureVector(), and KKB::ReadImage().
{
  FeatureVectorPtr fv = NULL;
  RasterPtr i = KKB::ReadImage (fileName);
  if (i == NULL)
  {
    runLog.Level (-1) << "FeatureVectorProducer::ComputeFeatureVectorFromImage ***ERROR*** Error
       loading ImageFile: " << fileName << endl << endl;
  }
  else
  {
    fv = ComputeFeatureVector (*i, knownClass, intermediateImages, 1.0f, runLog);
    delete i;
    i = NULL;
  }
  return fv;
} /* ComputeFeatureVectorFromImage */
virtual FileDescPtr KKMLL::FeatureVectorProducer::DefineFileDesc () const [protected], [pure virtual]
Implemented in KKMLL::GrayScaleImagesFVProducer.
Referenced by FileDesc().
FactoryFVProducerPtr KKMLL::FeatureVectorProducer::Factory () const [inline]
Returns pointer to factory that instantiated this instance.
Definition at line 122 of file FeatureVectorProducer.h.
{return factory;}
kkuint32 FeatureVectorProducer::FeatureCount () const
Definition at line 93 of file FeatureVectorProducer.cpp.
References KKMLL::FileDesc::NumOfFields().
Referenced by MaxNumOfFeatures().
{
  if (!fileDesc)
    return 0;
  else
    return fileDesc->NumOfFields ();
}
const KKStr & FeatureVectorProducer::FeatureName (kkuint32 fieldNum) const
Definition at line 103 of file FeatureVectorProducer.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), KKMLL::FileDesc::FieldName(), and KKMLL::FileDesc::NumOfFields().
{
  if (fileDesc == NULL)
    return KKStr::EmptyStr ();
  if (fieldNum >= fileDesc->NumOfFields ())
    return KKStr::EmptyStr ();
  else
    return fileDesc->FieldName (fieldNum);
}
virtual const type_info* KKMLL::FeatureVectorProducer::FeatureVectorListTypeId () const [pure virtual]
Returns the 'type_info' of the FeatureVectorList derived class that can contain instances in 'FeatureVector' instances created by this producer.
Implemented in KKMLL::GrayScaleImagesFVProducer.
virtual const type_info* KKMLL::FeatureVectorProducer::FeatureVectorTypeId () const [pure virtual]
Returns the 'type_info' of the FeatureVector that this instance of 'FeatureVectorProducer' creates.
Implemented in KKMLL::GrayScaleImagesFVProducer.
FileDescConstPtr FeatureVectorProducer::FileDesc () const
Returns back a `FileDesc` instance that describes the features that this instance of 'FeatureVectorProducer' creates. The class derived form this class is responsible for creating the FileDesc instance. When this method is called if `fileDesc` equals NULL then will call `DefineFileDesc`, which is a pure virtual method that will be implemented by the derived class, to instantiate a new instance.
Definition at line 74 of file FeatureVectorProducer.cpp.
References DefineFileDesc(), KKB::GlobalGoalKeeper::EndBlock(), KKMLL::FileDesc::GetExistingFileDesc(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKMLL::GrayScaleImagesFVProducer::ManufacturFeatureVectorList().
{
  if (!fileDesc)
  {
    GlobalGoalKeeper::StartBlock ();
    if (!fileDesc)
    {
      fileDesc = DefineFileDesc ();
      fileDesc = FileDesc::GetExistingFileDesc (fileDesc);
    }
    GlobalGoalKeeper::EndBlock ();
  }
  return fileDesc;
}
virtual FeatureVectorListPtr KKMLL::FeatureVectorProducer::ManufacturFeatureVectorList (bool owner, RunLog & runLog) const [pure virtual]
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors by this FeatureVectorProducer.
Implemented in KKMLL::GrayScaleImagesFVProducer.
kkuint32 KKMLL::FeatureVectorProducer::MaxNumOfFeatures () [inline]
Same as FeatureCount
Definition at line 145 of file FeatureVectorProducer.h.
References FeatureCount().
const KKStr& KKMLL::FeatureVectorProducer::Name () const [inline]
Returns a kkint16 description of the FeatureVector which can be used as part/all of a File or Directory name.
Definition at line 135 of file FeatureVectorProducer.h.
{return name;};
virtual kkint16 KKMLL::FeatureVectorProducer::Version () const [pure virtual]
The version number of the FeatureVector that is going to be computed.
Implemented in KKMLL::GrayScaleImagesFVProducer.
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVectorProducer.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVectorProducer.cpp