KKMLL::BinaryClassParmsList Class Reference
#include <BinaryClassParms.h>
Public Types
typedef BinaryClassParmsList * BinaryClassParmsListPtr
Public Member Functions
BinaryClassParmsList ()
BinaryClassParmsList (bool _owner)
BinaryClassParmsList (const BinaryClassParmsList &binaryClassList, bool _owner)
~BinaryClassParmsList ()
BinaryClassParmsList * DuplicateListAndContents () const
float FeatureCountNet (FileDescPtr fileDesc) const
Returns the Average number of selected features.
BinaryClassParmsPtr LookUp (MLClassPtr _class1, MLClassPtr _class2) const
kkint32 MemoryConsumedEstimated () const
virtual void PushOnBack (BinaryClassParmsPtr binaryParms)
virtual void PushOnFront (BinaryClassParmsPtr binaryParms)
void ReadXML (FILE *i, FileDescPtr fileDesc, RunLog &log)
void ReadXML (std::istream &i, FileDescPtr fileDesc, RunLog &log)
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
void WriteXML (std::ostream &o) const
virtual void WriteXML (const KKStr &varName, std::ostream &o) const
Static Public Member Functions
static BinaryClassParmsListPtr CreateFromXML (std::istream &i, FileDescPtr fileDesc, RunLog &log)
static BinaryClassParmsListPtr CreateFromXML (std::FILE *i, FileDescPtr fileDesc, RunLog &log)
Additional Inherited Members
Detailed Description
Definition at line 124 of file BinaryClassParms.h.
Member Typedef Documentation
typedef BinaryClassParmsList* KKMLL::BinaryClassParmsList::BinaryClassParmsListPtr
Definition at line 127 of file BinaryClassParms.h.
Constructor & Destructor Documentation
BinaryClassParmsList::BinaryClassParmsList ()
Definition at line 197 of file BinaryClassParms.cpp.
References BinaryClassParmsList().
Referenced by BinaryClassParmsList().
                                           :
        KKQueue<BinaryClassParms> (true)
{
}
BinaryClassParmsList::BinaryClassParmsList (bool _owner)
Definition at line 204 of file BinaryClassParms.cpp.
References BinaryClassParmsList().
Referenced by KKMLL::SVMparam::AddBinaryClassParms(), BinaryClassParmsList(), DuplicateListAndContents(), and KKMLL::SVMparam::GetParamtersToUseFor2ClassCombo().
                                                       :
        KKQueue<BinaryClassParms> (_owner)
{
}
BinaryClassParmsList::BinaryClassParmsList (const BinaryClassParmsList & binaryClassList, bool _owner)
Definition at line 218 of file BinaryClassParms.cpp.
References BinaryClassParmsList().
Referenced by BinaryClassParmsList().
                                            :
        KKQueue<BinaryClassParms> (binaryClassList, _owner)
{
}
BinaryClassParmsList::~BinaryClassParmsList ()
Definition at line 227 of file BinaryClassParms.cpp.
{
}
Member Function Documentation
static BinaryClassParmsListPtr KKMLL::BinaryClassParmsList::CreateFromXML (std::istream & i, FileDescPtr fileDesc, RunLog & log) [static]
static BinaryClassParmsListPtr KKMLL::BinaryClassParmsList::CreateFromXML (std::FILE * i, FileDescPtr fileDesc, RunLog & log) [static]
BinaryClassParmsListPtr BinaryClassParmsList::DuplicateListAndContents () const
Definition at line 316 of file BinaryClassParms.cpp.
References KKMLL::BinaryClassParms::BinaryClassParms(), BinaryClassParmsList(), and PushOnBack().
Referenced by KKMLL::SVMparam::SVMparam().
{
  BinaryClassParmsListPtr duplicatedQueue = new
      BinaryClassParmsList (true);
  for (const_iterator idx = begin (); idx != end (); idx++)
  {
    BinaryClassParmsPtr e = *idx;
    duplicatedQueue->PushOnBack (new BinaryClassParms (*e));
  }
  
  return duplicatedQueue;
} /* DuplicateListAndContents */
float BinaryClassParmsList::FeatureCountNet (FileDescPtr fileDesc) const
Returns the Average number of selected features.
Definition at line 272 of file BinaryClassParms.cpp.
References KKMLL::BinaryClassParms::NumOfFeatures().
Referenced by KKMLL::SVMparam::AvgMumOfFeatures().
{
  if (size () < 1)
    return 0.0f;
  const_iterator idx;
  kkuint32 featureCountTotal = 0;
  for (idx = begin (); idx != end (); idx++)
  {
    const BinaryClassParmsPtr bcp = *idx;
    featureCountTotal += bcp->NumOfFeatures (fileDesc);
  }
  return (float)featureCountTotal / (float)size ();
}
BinaryClassParmsPtr BinaryClassParmsList::LookUp (MLClassPtr _class1, MLClassPtr _class2) const
Definition at line 293 of file BinaryClassParms.cpp.
Referenced by KKMLL::ModelParamOldSVM::C_Param(), KKMLL::SVMparam::C_Param(), KKMLL::SVMparam::GetBinaryClassParms(), KKMLL::SVMparam::GetFeatureNums(), KKMLL::SVMparam::GetParamtersToUseFor2ClassCombo(), KKMLL::SVMparam::ProbClassPairsInitialize(), PushOnBack(), PushOnFront(), KKMLL::SVMparam::SetBinaryClassFields(), and KKMLL::SVMparam::SetFeatureNums().
{
  KeyField kf (_class1, _class2);
  ClassIndexType::const_iterator idx;
  idx = classIndex.find (kf);
  if (idx == classIndex.end ())
  {
    kf.class1 = _class2;
    kf.class2 = _class1;
    idx = classIndex.find (kf);
  }
  if (idx == classIndex.end ())
    return NULL;
  else
    return idx->second;
} /* LookUp */
kkint32 BinaryClassParmsList::MemoryConsumedEstimated () const
Definition at line 233 of file BinaryClassParms.cpp.
Referenced by KKMLL::SVMparam::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = sizeof (BinaryClassParmsList);
  BinaryClassParmsList::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx)
    memoryConsumedEstimated += (*idx)->MemoryConsumedEstimated ();
  return memoryConsumedEstimated;
}
void BinaryClassParmsList::PushOnBack (BinaryClassParmsPtr binaryParms) [virtual]
Definition at line 416 of file BinaryClassParms.cpp.
References KKMLL::BinaryClassParms::Class1(), KKMLL::BinaryClassParms::Class2(), KKB::KKStr::Concat(), KKB::KKException::KKException(), KKB::KKStr::KKStr(), and LookUp().
Referenced by KKMLL::SVMparam::AddBinaryClassParms(), DuplicateListAndContents(), KKMLL::SVMparam::GetParamtersToUseFor2ClassCombo(), and ReadXML().
{
  BinaryClassParmsPtr existingEntry = LookUp (binaryParms->
      Class1 (), binaryParms->Class2 ());
  if (existingEntry)
  {
    // We have a duplicate entry
    KKStr errMsg (128);
    errMsg << "BinaryClassParmsList::PushOnBack ***ERROR*** Duplicate Entry " << binaryParms->
      Class1Name () << "\t" << binaryParms->Class2Name () << endl;
    cerr << errMsg << endl;
    throw KKException (errMsg);
  }
  KKQueue<BinaryClassParms>::PushOnBack (binaryParms);
  KeyField kf (binaryParms->Class1 (), binaryParms->Class2 ());
  classIndex.insert(ClassIndexPair (kf, binaryParms));
} /* PushOnBack */
void BinaryClassParmsList::PushOnFront (BinaryClassParmsPtr binaryParms) [virtual]
Definition at line 436 of file BinaryClassParms.cpp.
References KKMLL::BinaryClassParms::Class1(), KKMLL::BinaryClassParms::Class2(), KKB::KKStr::Concat(), KKB::KKException::KKException(), KKB::KKStr::KKStr(), and LookUp().
{
  BinaryClassParmsPtr existingEntry = LookUp (binaryParms->
      Class1 (), binaryParms->Class2 ());
  if (existingEntry)
  {
    // We have a duplicate entry
    KKStr errMsg (128);
    errMsg << "BinaryClassParmsList::PushOnFront ***ERROR*** Duplicate Entry " << binaryParms->
      Class1Name () << "\t" << binaryParms->Class2Name () << endl;
    cerr << errMsg << endl;
    throw KKException (errMsg);
  }
  KKQueue<BinaryClassParms>::PushOnFront (binaryParms);
  KeyField kf (binaryParms->Class1 (), binaryParms->Class2 ());
  classIndex.insert(ClassIndexPair (kf, binaryParms));
} /* PushOnFront */
void BinaryClassParmsList::ReadXML (FILE * i, FileDescPtr fileDesc, RunLog & log)
Definition at line 351 of file BinaryClassParms.cpp.
{
  DeleteContents ();
  char buff [10240];
  while (fgets (buff, sizeof (buff), i))
  {
    KKStr ln (buff);
    KKStr field = ln.ExtractQuotedStr ("\n\r\t", true);
    field.Upper ();
    if (field == "</BINARYCLASSPARMSLIST>")
    {
      break;
    }
    else if (field == "<BINARYCLASSPARMS>")
    {
      KKStr binaryClassParmsStr = ln.ExtractQuotedStr ("\n\r\t", true);
      PushOnBack (BinaryClassParms::CreateFromTabDelStr (
      binaryClassParmsStr, log));
    }
  }
} /* ReadXML */
void KKMLL::BinaryClassParmsList::ReadXML (std::istream & i, FileDescPtr fileDesc, RunLog & log)
void BinaryClassParmsList::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) [virtual]
Definition at line 516 of file BinaryClassParms.cpp.
References KKB::XmlContent::Content(), KKMLL::BinaryClassParms::CreateFromTabDelStr(), KKB::XmlStream::GetNextToken(), PushOnBack(), KKB::XmlToken::tokContent, and KKB::XmlToken::TokenType().
{
  DeleteContents ();
  classIndex.clear ();
  bool errorsFound = false;
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag) && (!errorsFound))
  {
    if (t->TokenType () == XmlToken::TokenTypes::tokContent)
    {
      XmlContentPtr content = dynamic_cast<XmlContentPtr> (t);
      if (content && (content->Content ()))
      {
        BinaryClassParmsPtr bcp =
      BinaryClassParms::CreateFromTabDelStr (*(content->
      Content ()), log);
        if (bcp)
          PushOnBack (bcp);
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
} /* ReadXML */
void KKMLL::BinaryClassParmsList::WriteXML (std::ostream & o) const
virtual void KKMLL::BinaryClassParmsList::WriteXML (const KKStr & varName, std::ostream & o) const [virtual]
Referenced by KKMLL::SVMparam::WriteXML().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/BinaryClassParms.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/BinaryClassParms.cpp