KKMLL::ModelUsfCasCor Class Reference
#include <ModelUsfCasCor.h>
Public Types
typedef ModelUsfCasCor * ModelUsfCasCorPtr
Public Member Functions
ModelUsfCasCor ()
ModelUsfCasCor (FactoryFVProducerPtr _factoryFVProducer)
ModelUsfCasCor (const KKStr &_name, const ModelParamUsfCasCor &_param, FactoryFVProducerPtr _factoryFVProducer)
ModelUsfCasCor (const ModelUsfCasCor &_model)
virtual ~ModelUsfCasCor ()
Frees any memory allocated by, and owned by the ModelUsfCasCor.
virtual ModelUsfCasCorPtr Duplicate () const
virtual kkint32 MemoryConsumedEstimated () const
virtual ModelTypes ModelType () const
virtual kkint32 NumOfSupportVectors () const
ModelParamUsfCasCorPtr Param ()
virtual MLClassPtr Predict (FeatureVectorPtr example, RunLog &log)
virtual void Predict (FeatureVectorPtr example, MLClassPtr knownClass, MLClassPtr &predClass1, MLClassPtr &predClass2, kkint32 &predClass1Votes, kkint32 &predClass2Votes, double &probOfKnownClass, double &predClass1Prob, double &predClass2Prob, kkint32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie, RunLog &log)
virtual ClassProbListPtr ProbabilitiesByClass (FeatureVectorPtr example, RunLog &log)
virtual void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassList &_mlClasses, kkint32 *_votes, double *_probabilities, RunLog &log)
virtual void ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassList &_mlClasses, double *_probabilities, RunLog &log)
Derives predicted probabilities by class.
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
To be implemented by derived classes; the parent classes fields will be updated by the derived class calling ReadXMLModelToken.
virtual void TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership, VolConstBool &_cancelFlag, RunLog &_log)
Performs operations such as FeatureEncoding, and Normalization. The actual training of models occurs in the specific derived implementation of 'Model'.
virtual void WriteXML (const KKStr &varName, ostream &o) const
Protected Attributes
ModelParamUsfCasCorPtr param
UsfCasCorPtr usfCasCorClassifier
Additional Inherited Members
Detailed Description
Definition at line 23 of file ModelUsfCasCor.h.
Member Typedef Documentation
typedef ModelUsfCasCor* KKMLL::ModelUsfCasCor::ModelUsfCasCorPtr
Definition at line 27 of file ModelUsfCasCor.h.
Constructor & Destructor Documentation
ModelUsfCasCor::ModelUsfCasCor ()
Definition at line 34 of file ModelUsfCasCor.cpp.
References KKMLL::Model::Model(), param, and usfCasCorClassifier.
                               :
  Model (),
  param (NULL),
  usfCasCorClassifier (NULL)
{
}
ModelUsfCasCor::ModelUsfCasCor (FactoryFVProducerPtr _factoryFVProducer)
Definition at line 43 of file ModelUsfCasCor.cpp.
References KKMLL::Model::Model(), param, and usfCasCorClassifier.
                                                                       :
  Model (_factoryFVProducer),
  param (NULL),
  usfCasCorClassifier (NULL)
{
}
ModelUsfCasCor::ModelUsfCasCor (const KKStr & _name, const ModelParamUsfCasCor & _param, FactoryFVProducerPtr _factoryFVProducer)
Definition at line 51 of file ModelUsfCasCor.cpp.
References KKMLL::Model::Model(), param, KKMLL::Model::param, and usfCasCorClassifier.
Referenced by KKMLL::Model::CreateAModel().
                                :
  Model (_name, _param, _factoryFVProducer),
  param (NULL),
  usfCasCorClassifier (NULL)
{
  param = dynamic_cast<ModelParamUsfCasCorPtr> (
      Model::param);
}
ModelUsfCasCor::ModelUsfCasCor (const ModelUsfCasCor & _model)
Definition at line 65 of file ModelUsfCasCor.cpp.
References KKMLL::Model::Model(), param, KKMLL::Model::param, and usfCasCorClassifier.
Referenced by Duplicate().
                                                             :
  Model (_model),
  param (NULL),
  usfCasCorClassifier (NULL)
{
  param = dynamic_cast<ModelParamUsfCasCorPtr> (
      Model::param);
  if (_model.usfCasCorClassifier)
  {
    usfCasCorClassifier = new UsfCasCor (*_model.
      usfCasCorClassifier);
  }
}
ModelUsfCasCor::~ModelUsfCasCor () [virtual]
Frees any memory allocated by, and owned by the ModelUsfCasCor.
Definition at line 81 of file ModelUsfCasCor.cpp.
References usfCasCorClassifier.
{
  // The base class owns param, so we do not delete it.
  // delete param;
  if (usfCasCorClassifier)
  {
    delete usfCasCorClassifier;
    usfCasCorClassifier = NULL;
  }
}
Member Function Documentation
ModelUsfCasCorPtr ModelUsfCasCor::Duplicate () const [virtual]
Implements KKMLL::Model.
Definition at line 106 of file ModelUsfCasCor.cpp.
References ModelUsfCasCor().
{
  return new ModelUsfCasCor (*this);
}
kkint32 ModelUsfCasCor::MemoryConsumedEstimated () const [virtual]
Reimplemented from KKMLL::Model.
Definition at line 93 of file ModelUsfCasCor.cpp.
References KKMLL::Model::MemoryConsumedEstimated(), and usfCasCorClassifier.
{
  kkint32 memoryConsumedEstimated = Model::MemoryConsumedEstimated ()
       +
                                   sizeof (usfCasCorClassifier);
  if (usfCasCorClassifier)
    memoryConsumedEstimated += usfCasCorClassifier->MemoryConsumedEstimated ();
  return memoryConsumedEstimated;
}
virtual ModelTypes KKMLL::ModelUsfCasCor::ModelType () const [inline], [virtual]
Implements KKMLL::Model.
Definition at line 48 of file ModelUsfCasCor.h.
References KKMLL::Model::UsfCasCor.
{return ModelTypes::UsfCasCor;}
kkint32 ModelUsfCasCor::NumOfSupportVectors () const [virtual]
Definition at line 456 of file ModelUsfCasCor.cpp.
{
  return 0;
} /* NumOfSupportVectors */
ModelParamUsfCasCorPtr ModelUsfCasCor::Param ()
Definition at line 113 of file ModelUsfCasCor.cpp.
References param.
{
  return param;
}
MLClassPtr ModelUsfCasCor::Predict (FeatureVectorPtr example, RunLog & log) [virtual]
Implements KKMLL::Model.
Definition at line 200 of file ModelUsfCasCor.cpp.
References KKMLL::Model::PrepExampleForPrediction(), and usfCasCorClassifier.
{
  if (!usfCasCorClassifier)
  {
    log.Level (-1) << endl << endl << "ModelUsfCasCor::Predict ***ERROR***
       (usfCasCorClassifier == NULL)" << endl << endl;
    return NULL;
  }
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      example, newExampleCreated);
  MLClassPtr predictedClass = usfCasCorClassifier->PredictClass (
      encodedExample);
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  return predictedClass;
} /* Predict */
[Predict(FeatureVectorPtr example, MLClassPtr knownClass, MLClassPtr predClass1, MLClassPtr predClass2, kkint32 predClass1Votes, kkint32 predClass2Votes, double probOfKnownClass, double predClass1Prob, double predClass2Prob, kkint32 numOfWinners, bool knownClassOneOfTheWinners, double breakTie, RunLog log)]void ModelUsfCasCor::Predict (FeatureVectorPtr example, MLClassPtr knownClass, MLClassPtr & predClass1, MLClassPtr & predClass2, kkint32 & predClass1Votes, kkint32 & predClass2Votes, double & probOfKnownClass, double & predClass1Prob, double & predClass2Prob, kkint32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie, RunLog & log) [virtual]
Implements KKMLL::Model.
Definition at line 225 of file ModelUsfCasCor.cpp.
References KKMLL::Model::classes, KKB::KKStr::Concat(), KKB::KKException::KKException(), KKMLL::Model::PrepExampleForPrediction(), and usfCasCorClassifier.
{
  if (!usfCasCorClassifier)
  {
    KKStr errMsg = "ModelUsfCasCor::Predict ***ERROR*** (usfCasCorClassifier == NULL)";
    log.Level (-1) << endl << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  VectorFloat probabilities;
  float pc1p = 0.0f;
  float pc2p = 0.0f;
  float kcp = 0.0f;
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      example, newExampleCreated);
  usfCasCorClassifier->PredictConfidences (encodedExample,
                                           knownClass,
                                           predClass1, pc1p,
                                           predClass2, pc2p,
                                           kcp,
                                           *classes,
                                           probabilities
                                          );
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  predClass1Prob = pc1p;
  predClass2Prob = pc2p;
  probOfKnownClass = kcp;
  breakTie = pc1p - pc2p;
  numOfWinners = 1;
  knownClassOneOfTheWinners = (predClass1 == knownClass);
  return;
} /* Predict */
ClassProbListPtr ModelUsfCasCor::ProbabilitiesByClass (FeatureVectorPtr example, RunLog & log) [virtual]
Implements KKMLL::Model.
Definition at line 287 of file ModelUsfCasCor.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKMLL::Model::PrepExampleForPrediction(), KKMLL::ClassProbList::SortByProbability(), and usfCasCorClassifier.
{
  if (!usfCasCorClassifier)
  {
    KKStr errMsg = "ModelUsfCasCor::ProbabilitiesByClass ***ERROR*** (usfCasCorClassifier ==
       NULL)";
    log.Level (-1) << endl << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      example, newExampleCreated);
  ClassProbListPtr results = usfCasCorClassifier->
      PredictClassConfidences (encodedExample);
  results->SortByProbability (true); // 'true' = Sort High to Low.
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  return results;
} /* ProbabilitiesByClass */
void ModelUsfCasCor::ProbabilitiesByClass (FeatureVectorPtr example, const MLClassList & _mlClasses, kkint32 * _votes, double * _probabilities, RunLog & log) [virtual]
Implements KKMLL::Model.
Definition at line 317 of file ModelUsfCasCor.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKMLL::Model::PrepExampleForPrediction(), and usfCasCorClassifier.
{
  if (!usfCasCorClassifier)
  {
    KKStr errMsg = "ModelUsfCasCor::ProbabilitiesByClass ***ERROR*** (usfCasCorClassifier ==
       NULL)";
    log.Level (-1) << endl << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  VectorFloat probabilities;
  MLClassPtr pc1 = NULL;
  MLClassPtr pc2 = NULL;
  MLClassPtr kc = NULL;
  float pc1p = 0.0f;
  float pc2p = 0.0f;
  float kcp = 0.0f;
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      example, newExampleCreated);
  usfCasCorClassifier->PredictConfidences (encodedExample,
                                           kc,
                                           pc1, pc1p,
                                           pc2, pc2p,
                                           kcp,
                                           _mlClasses,
                                           probabilities
                                          );
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  if (_mlClasses.size () != probabilities.size ())
  {
    log.Level (-1) << endl << "ModelUsfCasCor::ProbabilitiesByClass ***ERROR***" <<
      endl
      << "\"_mlClasses.size () != probabilities.size ()\" This should not ever be able to happen." <<
      endl
      << endl;
    for (int x = 0; x < _mlClasses.QueueSize (); ++x)
    {
      _votes[x] = 0;
      _probabilities[x] = 0.0;
    }
  }
  else
  {
    float highProb = -9999.99f;
    int highProbIdx = -1;
    for (kkuint32 x = 0; x < probabilities.size (); ++x)
    {
      float p = probabilities[x];
      _votes[x] = 0;
      _probabilities[x] = p;
      if (p > highProb)
      {
        highProbIdx = x;
        highProb = p;
      }
    }
    if (highProbIdx >= 0)
      votes[highProbIdx] = 1;
  }
  return;
} /* ProbabilitiesByClass */
void ModelUsfCasCor::ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassList & _mlClasses, double * _probabilities, RunLog & log) [virtual]
Derives predicted probabilities by class.
Will get the probabilities assigned to each class by the classifier. The '_mlClasses' parameter dictates the order of the classes. That is the probabilities for any given index in '_probabilities' will be for the class specified in the same index in '_mlClasses'.
Parameters
in _example FeatureVector object to calculate predicted probabilities for.
in _mlClasses List classes that caller is aware of. This should be the same list that was used when constructing this Model object. The list must be the same but not necessarily in the same order as when Model was 1st constructed.
out _probabilities An array that must be as big as the number of classes as in mlClasses. The probability of class in mlClasses[x] will be returned in probabilities[x].
Implements KKMLL::Model.
Definition at line 394 of file ModelUsfCasCor.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKMLL::Model::PrepExampleForPrediction(), and usfCasCorClassifier.
{
  if (!usfCasCorClassifier)
  {
    KKStr errMsg = "ModelUsfCasCor::ProbabilitiesByClass ***ERROR*** (usfCasCorClassifier ==
       NULL)";
    _log.Level (-1) << endl << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  VectorFloat probabilities;
  MLClassPtr pc1 = NULL;
  MLClassPtr pc2 = NULL;
  MLClassPtr kc = NULL;
  float pc1p = 0.0f;
  float pc2p = 0.0f;
  float kcp = 0.0f;
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      _example, newExampleCreated);
  usfCasCorClassifier->PredictConfidences (encodedExample,
                                           kc,
                                           pc1, pc1p,
                                           pc2, pc2p,
                                           kcp,
                                           _mlClasses,
                                           probabilities
                                          );
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  if (_mlClasses.size () != probabilities.size ())
  {
    _log.Level (-1) << endl << "ModelUsfCasCor::ProbabilitiesByClass ***ERROR***" <<
      endl
      << "\"_mlClasses.size () != probabilities.size ()\" This should not ever be able to happen." <<
      endl
      << endl;
    for (int x = 0; x < _mlClasses.QueueSize (); ++x)
    {
      _probabilities[x] = 0.0;
    }
  }
  else
  {
    for (kkuint32 x = 0; x < probabilities.size (); ++x)
      _probabilities[x] = probabilities[x];
  }
  return;
} /* ProbabilitiesByClass */
void ModelUsfCasCor::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) [virtual]
To be implemented by derived classes; the parent classes fields will be updated by the derived class calling ReadXMLModelToken.
Implements KKMLL::Model.
Definition at line 489 of file ModelUsfCasCor.cpp.
References KKMLL::Model::AddErrorMsg(), KKB::KKStr::Concat(), KKB::XmlStream::GetNextToken(), KKB::KKStr::KKStr(), KKMLL::ModelParam::ModelParamTypeStr(), param, KKMLL::Model::param, KKMLL::Model::ReadXMLModelPost(), KKMLL::Model::ReadXMLModelToken(), and usfCasCorClassifier.
{
  delete usfCasCorClassifier;
  usfCasCorClassifier = NULL;
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    t = ReadXMLModelToken (t, log);
    if (t)
    {
      if (t->VarName ().EqualIgnoreCase ("UsfCasCorClassifier") && (typeid (*t) ==
       typeid(XmlElementUsfCasCor)))
      {
        delete usfCasCorClassifier;
        usfCasCorClassifier = dynamic_cast<XmlElementUsfCasCorPtr>(t)->TakeOwnership ();
      }
      else
      {
        KKStr errMsg (128);
        errMsg << "ModelUsfCasCor::ReadXML ***ERROR*** Unexpected Element: Section: " << t->
      SectionName () << " VarName:" << t->VarName ();
        log.Level (-1) << endl << errMsg << endl << endl;
        AddErrorMsg (errMsg, 0);
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
  if (!cancelFlag)
  {
    if (!param)
      param = dynamic_cast<ModelParamUsfCasCorPtr> (
      Model::param);
    if (Model::param == NULL)
    {
      KKStr errMsg (128);
      errMsg << "ModelUsfCasCor::ReadXML ***ERROR*** Base class 'Model' does not have 'param' defined.";
      AddErrorMsg (errMsg, 0);
      log.Level (-1) << endl << errMsg << endl << endl;
    }
    else if (typeid (*Model::param) != typeid(ModelParamUsfCasCor))
    {
      KKStr errMsg (128);
      errMsg << "ModelUsfCasCor::ReadXML ***ERROR*** Base class 'Model' param parameter is of the wrong
       type; found: " << Model::param->ModelParamTypeStr ();
      AddErrorMsg (errMsg, 0);
      log.Level (-1) << endl << errMsg << endl << endl;
    }
    else
    {
      param = dynamic_cast<ModelParamUsfCasCorPtr> (
      Model::param);
    }
    ReadXMLModelPost (log);
  }
} /* ReadXML */
void ModelUsfCasCor::TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership, VolConstBool & _cancelFlag, RunLog & _log) [virtual]
Performs operations such as FeatureEncoding, and Normalization. The actual training of models occurs in the specific derived implementation of 'Model'.
Performs operations such as FeatureEncoding, and Normalization; the actual training of models occurs in the specific implementation of 'Model'.
Parameters
in _trainExamples Training data that classifier will be built from. If the examples need to be normalized or encoded and we are not taking ownership then a duplicate list of examples will be created that this method and class will be free to modify.
in _alreadyNormalized Indicates if contents of '_trainExamples' are normalized already; if not they will be normalized.
in _takeOwnership This instance of Model will take ownership of '_examples' and is free to modify its contents.
Parameters
_takeOwnership Model will take ownership of these examples
Reimplemented from KKMLL::Model.
Definition at line 120 of file ModelUsfCasCor.cpp.
References KKB::KKStr::Concat(), KKMLL::ModelParamUsfCasCor::In_limit(), KKB::KKException::KKException(), KKMLL::ModelParamUsfCasCor::Number_of_rounds(), KKMLL::ModelParamUsfCasCor::Number_of_trials(), KKMLL::ModelParamUsfCasCor::Out_limit(), param, KKMLL::ModelParamUsfCasCor::Random_seed(), KKMLL::Model::SelectedFeatures(), KKMLL::Model::trainExamples, KKMLL::Model::TrainingTimeEnd(), KKMLL::Model::TrainingTimeStart(), KKMLL::Model::TrainModel(), KKMLL::ModelParamUsfCasCor::UseCache(), usfCasCorClassifier, and KKMLL::Model::validModel.
{
  _log.Level (10) << "ModelUsfCasCor::TrainModel[" << Name () << "]." <<
      endl;
  if (param == NULL)
  {
    validModel = false;
    KKStr errMsg = "ModelUsfCasCor::TrainModel (param == NULL)";
    _log.Level (-1) << endl << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  if (usfCasCorClassifier)
  {
    delete usfCasCorClassifier;
    usfCasCorClassifier = NULL;
  }
  try
  {
    Model::TrainModel (_trainExamples, _alreadyNormalized, _takeOwnership, _cancelFlag,
      _log);
  }
  catch (const KKException& e)
  {
    validModel = false;
    KKStr errMsg = "ModelUsfCasCor::TrainModel ***ERROR*** Exception occurred calling
       'Model::TrainModel'.";
    _log.Level (-1) << endl << errMsg << endl << e.ToString () <<
      endl << endl;
    throw KKException (errMsg, e);
  }
  catch (const exception& e2)
  {
    validModel = false;
    KKStr errMsg = "ModelUsfCasCor::TrainModel ***ERROR*** Exception occurred calling
       'Model::TrainModel'.";
    _log.Level (-1) << endl << endl << errMsg << endl << e2.what () <<
      endl << endl;
    throw KKException (errMsg, e2);
  }
  catch (...)
  {
    validModel = false;
    KKStr errMsg = "ModelUsfCasCor::TrainModel ***ERROR*** Exception occurred calling
       'Model::TrainModel'.";
    _log.Level (-1) << endl << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  // 'Model::TrainModel' Will have performed any BitReduction and Feature Encoding
  // that needed to be done.
  // Also the data structures 'classes', 'encoder', and 'fileDesc' will have been built.
  // 'classes' will already be sorted in name order.
  // The Prediction variables 'probabilities', 'votes', and 'crossClassProbTable' will
  // have been built.
  TrainingTimeStart ();
  usfCasCorClassifier = new UsfCasCor ();
  usfCasCorClassifier->TrainNewClassifier (param->
      In_limit (),
                                           param->Out_limit (),
                                           param->Number_of_rounds (),
                                           param->Number_of_trials (),
                                           param->Random_seed (),
                                           param->UseCache (),
                                           trainExamples,
                                           SelectedFeatures (),
                                           _cancelFlag,
                                           _log
                                          );
  TrainingTimeEnd ();
  _log.Level (10) << "ModelUsfCasCor::TrainModel Completed." << endl;
} /* TrainModel */
void ModelUsfCasCor::WriteXML (const KKStr & varName, ostream & o) const [virtual]
Definition at line 466 of file ModelUsfCasCor.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, usfCasCorClassifier, KKMLL::Model::WriteModelXMLFields(), KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("ModelUsfCasCor", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  WriteModelXMLFields (o); // Write the base class data fields 1st.
  usfCasCorClassifier->WriteXML ("UsfCasCorClassifier", o);
  XmlTag endTag ("ModelUsfCasCor", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
} /* WriteXML */
Member Data Documentation
ModelParamUsfCasCorPtr KKMLL::ModelUsfCasCor::param [protected]
We will NOT own this instance. It will point to same instance defined in parent class Model.
Definition at line 138 of file ModelUsfCasCor.h.
Referenced by ModelUsfCasCor(), Param(), ReadXML(), and TrainModel().
UsfCasCorPtr KKMLL::ModelUsfCasCor::usfCasCorClassifier [protected]
Definition at line 137 of file ModelUsfCasCor.h.
Referenced by MemoryConsumedEstimated(), ModelUsfCasCor(), Predict(), ProbabilitiesByClass(), ReadXML(), TrainModel(), WriteXML(), and ~ModelUsfCasCor().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelUsfCasCor.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelUsfCasCor.cpp