KKB::XmlStream Class Reference
Manages the reading and writing of objects in a simple XML format. For a class to be supported by XmlStream it must implement:
#include <XmlStream.h>
Public Types
typedef XmlStream * XmlStreamPtr
Public Member Functions
XmlStream (XmlTokenizerPtr _tokenStream)
XmlStream (const KKStr &_fileName, RunLog &_log)
virtual ~XmlStream ()
virtual XmlContentPtr GetNextContent (RunLog &log)
virtual XmlTokenPtr GetNextToken (VolConstBool &cancelFlag, RunLog &log)
void RegisterFactory (XmlFactoryPtr factory)
Registers a Factory at the current hierarchy that is being processed.
Detailed Description
Manages the reading and writing of objects in a simple XML format. For a class to be supported by XmlStream it must implement:
Default constructor.
Helper Class derived form XmlElement
Helper Class derived from XmlFactory
Method XmlRead
Method XmlWrite
Definition at line 46 of file XmlStream.h.
Member Typedef Documentation
typedef XmlStream* KKB::XmlStream::XmlStreamPtr
Definition at line 49 of file XmlStream.h.
Constructor & Destructor Documentation
XmlStream::XmlStream (XmlTokenizerPtr _tokenStream)
Definition at line 29 of file XmlStream.cpp.
References KKB::KKStr::KKStr(), and KKB::VectorKKStr::VectorKKStr().
                                                 :
    endOfElementTagNames (),
    endOfElemenReached (false),
    fileName (),
    nameOfLastEndTag (),
    tokenStream (_tokenStream),
    weOwnTokenStream (false)
{
}
XmlStream::XmlStream (const KKStr & _fileName, RunLog & _log)
Definition at line 41 of file XmlStream.cpp.
References KKB::KKStr::KKStr(), KKB::VectorKKStr::VectorKKStr(), and KKB::XmlTokenizer::XmlTokenizer().
Referenced by KKMLL::TrainingProcess2::LoadExistingTrainingProcess(), and KKMLL::NormalizationParms::ReadFromFile().
                                                          :
    endOfElementTagNames (),
    endOfElemenReached (false),
    fileName (_fileName),
    nameOfLastEndTag (),
    tokenStream (NULL),
    weOwnTokenStream (false)
{
  bool fileOpened = false;
  tokenStream = new XmlTokenizer (fileName, fileOpened);
  weOwnTokenStream = true;
}
XmlStream::~XmlStream () [virtual]
Definition at line 56 of file XmlStream.cpp.
{
  delete tokenStream;
  tokenStream = NULL;
}
Member Function Documentation
XmlContentPtr XmlStream::GetNextContent (RunLog & log) [virtual]
Will return any content that may exist before the next tag; if there is no content before the next tag will return NULL
Definition at line 210 of file XmlStream.cpp.
References KKB::KKStr::FirstChar(), KKB::XmlTokenizer::GetNextToken(), KKB::XmlTokenizer::Peek(), and KKB::XmlContent::XmlContent().
{
  if (!tokenStream)
    return NULL;
  KKStrConstPtr peekNext = tokenStream->Peek (0);
  if (!peekNext)
    return NULL;
  if (peekNext->FirstChar () == '<')
    return NULL;
  else
  {
    KKStrPtr ts = tokenStream->GetNextToken ();
    if (ts)
      return new XmlContent (ts);
    else
      return NULL;
  }
}
XmlTokenPtr XmlStream::GetNextToken (VolConstBool & cancelFlag, RunLog & log) [virtual]
Will return either a XmlElement or a XmlContent which ever is next; If we are at the end of the element then NULL will be returned.
Definition at line 116 of file XmlStream.cpp.
References KKB::KKStr::Concat(), KKB::XmlFactory::FactoryLookUp(), KKB::KKStr::FirstChar(), KKB::XmlTokenizer::GetNextToken(), GetNextToken(), KKB::XmlFactory::ManufatureXmlElement(), KKB::XmlTag::Name(), KKB::XmlTag::tagEmpty, KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::TagType(), KKB::XmlContent::XmlContent(), KKB::XmlElementUnKnownFactoryInstance(), and KKB::XmlTag::XmlTag().
Referenced by GetNextToken(), KKMLL::TrainingProcess2::LoadExistingTrainingProcess(), KKMLL::NormalizationParms::ReadFromFile(), KKMLL::ModelParamKnn::ReadXML(), KKMLL::AttributeTypeVector::ReadXML(), KKB::VectorKKStr::ReadXML(), KKMLL::ModelParamSvmBase::ReadXML(), KKMLL::ModelParamUsfCasCor::ReadXML(), KKMLL::ModelParamDual::ReadXML(), KKMLL::TrainingClass::ReadXML(), KKMLL::NormalizationParms::ReadXML(), KKMLL::ModelKnn::ReadXML(), KKMLL::ClassProbList::ReadXML(), KKMLL::FeatureEncoder::ReadXML(), KKB::BitString::ReadXML(), KKMLL::ModelUsfCasCor::ReadXML(), KKMLL::Attribute::ReadXML(), KKMLL::ModelSvmBase::ReadXML(), KKMLL::ModelParamOldSVM::ReadXML(), KKMLL::FeatureNumList::ReadXML(), KKMLL::TrainingClassList::ReadXML(), KKMLL::AttributeList::ReadXML(), KKMLL::BinaryClassParmsList::ReadXML(), SVM233::SvmModel233::ReadXML(), SVM289_MFS::Svm_Model::ReadXML(), KKMLL::ModelDual::ReadXML(), KKMLL::FileDesc::ReadXML(), KKMLL::SVMparam::ReadXML(), KKMLL::ModelOldSVM::ReadXML(), KKMLL::SVMModel::ReadXML(), KKMLL::TrainingConfiguration2::ReadXML(), KKMLL::TrainingProcess2::ReadXML(), KKB::KKStr::ReadXML(), KKMLL::MLClassIndexList::ReadXML(), KKB::KKStrList::ReadXML(), KKB::KKStrListIndexed::ReadXML(), KKB::XmlElementArrayFloat2DVarying::XmlElementArrayFloat2DVarying(), KKB::XmlElementBool::XmlElementBool(), KKB::XmlElementKeyValuePairs::XmlElementKeyValuePairs(), KKMLL::XmlElementMLClass::XmlElementMLClass(), KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList(), and KKB::XmlElementUnKnown::XmlElementUnKnown().
{
  if (endOfElemenReached || cancelFlag)
    return NULL;
  XmlTokenPtr token = NULL;
  KKStrPtr t = tokenStream->GetNextToken ();
  if (t == NULL)
    return NULL;
  if (t->FirstChar () == '<')
  {
    XmlTagPtr tag = new XmlTag (t);
    delete t;
    t = NULL;
    if (tag->TagType () == XmlTag::TagTypes::tagStart)
    {
      XmlFactoryPtr factory = TrackDownFactory (tag->Name ());
      if (!factory)
        factory = XmlElementUnKnownFactoryInstance ();
      else
        int zed =100;
      log.Level (50) << "XmlStream::GetNextToken Factory Selected: " << factory->
      ClassName () << endl;
      PushXmlElementLevel (tag->Name ());
      token = factory->ManufatureXmlElement (tag, *this, cancelFlag, log);
      KKStr endTagName = endOfElementTagNames.back ();
      PopXmlElementLevel ();
      endOfElemenReached = false;
    }
    else if (tag->TagType () == XmlTag::TagTypes::tagEmpty)
    {
      XmlFactoryPtr factory = XmlFactory::FactoryLookUp (tag->
      Name ());
      if (!factory)
        factory = XmlElementUnKnownFactoryInstance ();
      PushXmlElementLevel (tag->Name ());
      endOfElemenReached = true;
      token = factory->ManufatureXmlElement (tag, *this, cancelFlag, log);
      if ((!endOfElemenReached) && (tag->TagType () ==
      XmlTag::TagTypes::tagStart))
      {
        // The element that we just read did not finish consuming all its components.
        log.Level (-1) << "XmlStream::GetNextToken ***WARNING*** The element just read[" << tag->
      Name () << "] Did not consume all its elements." << endl;
        XmlTokenPtr t = GetNextToken (cancelFlag, log);
        while (t)
        {
          delete t;
          t = GetNextToken (cancelFlag, log);
        }
      }
      endOfElemenReached = false;
      PopXmlElementLevel ();
    }
    else if (tag->TagType () == XmlTag::TagTypes::tagEnd)
    {
      if (endOfElementTagNames.size () < 1)
      {
        // end tag with no matching start tag.
        log.Level (-1) << endl
            << "XmlStream::GetNextToken ***ERROR*** Encountered end-tag </" << tag->
      Name () << "> with no matching start-tag." << endl
            << endl;
      }
      else
      {
        endOfElemenReached = true;
        nameOfLastEndTag = tag->Name ();
        if (!endOfElementTagNames.back ().EqualIgnoreCase (nameOfLastEndTag))
        {
          log.Level (-1) << endl
            << "XmlStream::GetNextToken ***ERROR*** Encountered end-tag </" << nameOfLastEndTag << ">
       does not match StartTag <" << endOfElementTagNames.back () << ">." << endl
            << endl;
          // </End-Tag> does not match <Start-Tag> we will put back on token stream assuming that we are
       missing a </End-Tag>
          // We will end the current element here.
          tokenStream->PushTokenOnFront (new KKStr ("<" + tag->
      Name () + " />"));
        }
      }
      delete tag;
      tag = NULL;
    }
  }
  else
  {
    token = new XmlContent (t);
  }
  return token;
} /* GetNextToken */
void XmlStream::RegisterFactory (XmlFactoryPtr factory)
Registers a Factory at the current hierarchy that is being processed.
Definition at line 67 of file XmlStream.cpp.
{
  if (factoryManagers.size () > 0)
    factoryManagers.back ()->RegisterFactory (factory);
  else
    XmlFactory::RegisterFactory (factory);
} /* RegisterFactory */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp