KKMLL::FeatureFileIOUCI Class Reference
Supports the reading and writing of Feature data from a file format commonly used by many dataset's in the UCI repository.
#include <FeatureFileIOUCI.h>
Public Types
typedef FeatureFileIOUCI * FeatureFileIOUCIPtr
Public Member Functions
FeatureFileIOUCI ()
~FeatureFileIOUCI ()
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, istream &_in, MLClassListPtr _classList, kkint32 &_estSize, KKStr &_errorMessage, RunLog &_log)
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassList &_classes, istream &_in, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, FeatureNumListConst &_selFeatures, ostream &_out, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)
Static Public Member Functions
static FeatureFileIOUCIPtr Driver ()
Additional Inherited Members
Detailed Description
Supports the reading and writing of Feature data from a file format commonly used by many dataset's in the UCI repository.
************************************************************************************************
* FeatureFileIOUCI Sub-classed from FeatureFileIO. It supports the reading
      and writing *
* of many of the files found in the UCI repository. *
* *
* 1) One example per row. *
* 2) Each field is separated by comma. *
* 3) Each row has the same number of fields. *
* 4) The last field is the ClassName. *
* 5) Each field is numeric except the last one which is the ClassName *
************************************************************************************************
See also
FeatureFileIO
Definition at line 28 of file FeatureFileIOUCI.h.
Member Typedef Documentation
typedef FeatureFileIOUCI* KKMLL::FeatureFileIOUCI::FeatureFileIOUCIPtr
Definition at line 35 of file FeatureFileIOUCI.h.
Constructor & Destructor Documentation
FeatureFileIOUCI::FeatureFileIOUCI ()
Definition at line 35 of file FeatureFileIOUCI.cpp.
References KKMLL::FeatureFileIO::FeatureFileIO().
                                   :
  FeatureFileIO ("UCI", true, true)
{
}
FeatureFileIOUCI::~FeatureFileIOUCI ()
Definition at line 42 of file FeatureFileIOUCI.cpp.
{
}
Member Function Documentation
static FeatureFileIOUCIPtr KKMLL::FeatureFileIOUCI::Driver () [inline], [static]
Definition at line 37 of file FeatureFileIOUCI.h.
{return &driver;}
FileDescPtr FeatureFileIOUCI::GetFileDesc (const KKStr & _fileName, istream & _in, MLClassListPtr _classList, kkint32 & _estSize, KKStr & _errorMessage, RunLog & _log) [virtual]
Definition at line 48 of file FeatureFileIOUCI.cpp.
References KKMLL::FileDesc::AddAAttribute(), KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::KKStr::ExtractToken(), KKMLL::FileDesc::FileDesc(), KKMLL::FeatureFileIO::GetLine(), KKMLL::MLClassList::GetMLClassPtr(), KKMLL::Numeric, KKB::KKStr::operator!=(), KKB::operator+(), KKB::KKStr::operator=(), KKB::StrFormatInt(), KKB::KKStr::SubStrPart(), KKB::KKStr::TrimLeft(), and KKB::KKStr::TrimRight().
{
  _log.Level (20) << "FeatureFileIOUCI::GetFileDesc FileName[" << _fileName << "]." <<
      endl;
  // We are just going to read the first few lines to determine number of fields, etc
 
  kkint32 numOfFields = 0;
  kkint32 numFieldsThisLine = 0;
  KKStr ln;
  bool eof;
  _estSize = 0;
  GetLine (_in, ln, eof);
  while (!eof)
  {
    ln.TrimLeft ();
    ln.TrimRight ();
    if ((ln.SubStrPart (0, 1) != "//") && (!ln.Empty ()))
    {
      numFieldsThisLine = 0;
      KKStr className = ln.ExtractToken (" ,\n\r\t");
      while (!ln.Empty ())
      {
        numFieldsThisLine++;
        className = ln.ExtractToken (" ,\n\r\t");
      }
      if (className.Empty ())
        className = "UnKnown";
      // make sure that 'className' exists in '_classes'.
      _classes->GetMLClassPtr (className);
      numOfFields = Max (numOfFields, numFieldsThisLine);
      _estSize++;
    }
    GetLine (_in, ln, eof);
  }
  bool alreadyExists = false;
  kkint32 fieldNum = 0;
  FileDescPtr fileDesc = new FileDesc ();
  for (fieldNum = 0; fieldNum < numOfFields; fieldNum++)
  {
    fileDesc->AddAAttribute ("Field_" + StrFormatInt (fieldNum, "ZZZZ0"),
      AttributeType::Numeric, alreadyExists);
  }
  return fileDesc;
} /* GetFileDesc */
FeatureVectorListPtr FeatureFileIOUCI::LoadFile (const KKStr & _fileName, const FileDescPtr _fileDesc, MLClassList & _classes, istream & _in, kkint32 _maxCount, VolConstBool & _cancelFlag, bool & _changesMade, KKStr & _errorMessage, RunLog & _log) [virtual]
Definition at line 116 of file FeatureFileIOUCI.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKMLL::FeatureVector::ExampleFileName(), KKB::KKStr::ExtractToken(), KKMLL::FeatureVector::FeatureVector(), KKMLL::FeatureVectorList::FeatureVectorList(), KKMLL::FeatureFileIO::GetLine(), KKMLL::MLClassList::GetMLClassPtr(), KKB::KKStr::KKStr(), KKMLL::FeatureVector::MLClass(), KKMLL::FileDesc::NumOfFields(), KKB::KKStr::operator!=(), KKB::KKStr::operator+(), KKB::osGetRootName(), KKMLL::FeatureVectorList::PushOnBack(), KKB::StrFormatInt(), KKB::KKStr::SubStrPart(), KKB::KKStr::TrimLeft(), and KKB::KKStr::TrimRight().
{
  _log.Level (20) << "FeatureFileIOUCI::LoadFile FileName[" << _fileName << "]" <<
      endl;
  KKStr rootName = osGetRootName (_fileName);
  kkint32 numOfFeatures = _fileDesc->NumOfFields ();
  kkint32 lineCount = 0;
  KKStr ln (256);
  bool eof;
  FeatureVectorListPtr examples = new FeatureVectorList (_fileDesc,
      true);
  GetLine (_in, ln, eof);
  while (!eof)
  {
    ln.TrimLeft ();
    ln.TrimRight ();
    if ((ln.SubStrPart (0, 1) != "//") && (!ln.Empty ()))
    {
      kkint32 featureNum = 0;
      FeatureVectorPtr example = new FeatureVector (numOfFeatures);
  
      for (featureNum = 0; featureNum < numOfFeatures; featureNum++)
      {
        KKStr featureStr = ln.ExtractToken (" ,\n\r\t");
        example->AddFeatureData (featureNum, (float)atof (featureStr.
      Str ()));
      }
      KKStr className = ln.ExtractToken (" ,\n\r\t");
      MLClassPtr mlClass = _classes.GetMLClassPtr (className);
      example->MLClass (mlClass);
      KKStr imageFileName = rootName + "_" + StrFormatInt (lineCount, "ZZZZZZ0");
      example->ExampleFileName (imageFileName);
      examples->PushOnBack (example);
      lineCount++;
    }
    GetLine (_in, ln, eof);
  }
  return examples;
} /* LoadFile */
void FeatureFileIOUCI::SaveFile (FeatureVectorList & _data, const KKStr & _fileName, FeatureNumListConst & _selFeatures, ostream & _out, kkuint32 & _numExamplesWritten, VolConstBool & _cancelFlag, bool & _successful, KKStr & _errorMessage, RunLog & _log) [virtual]
Definition at line 181 of file FeatureFileIOUCI.cpp.
References KKMLL::FeatureVector::ClassName(), KKMLL::FeatureVectorList::FileDesc(), KKMLL::FeatureNumList::NumOfFeatures(), KKB::operator<<(), and KKMLL::FeatureNumList::operator[]().
{
  FeatureVectorPtr example = NULL;
  _numExamplesWritten = 0;
  kkint32 idx;
  kkint32 x;
  FileDescPtr fileDesc = _data.FileDesc ();
  _out << "ExampleFileName";
  for (x = 0; x < _selFeatures.NumOfFeatures (); x++)
  {
    kkint32 featureNum = _selFeatures[x];
    _out << "," << fileDesc->FieldName (featureNum);
  }
  _out << "," << "ClassLabel" << endl;
  for (idx = 0; idx < _data.QueueSize (); idx++)
  {
    example = _data.IdxToPtr (idx);
    _out << ("Train_" + KKB::osGetRootName (example->
      ExampleFileName ())) << ",";
    for (x = 0; x < _selFeatures.NumOfFeatures (); x++)
    {
      kkint32 featureNum = _selFeatures[x];
      _out << example->FeatureData (featureNum) << ",";
    }
    _out << example->ClassName ();
    _out << endl;
    _numExamplesWritten++;
  }
  _successful = true;
  return;
} /* WriteUCIFile */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIOUCI.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIOUCI.cpp