KKB::RasterBuffer Class Reference
Will manage a buffer that will allow multiple threads to add and remove instances of 'Raster' objects.
#include <RasterBuffer.h>
Public Types
typedef RasterBuffer * RasterBufferPtr
Public Member Functions
RasterBuffer (const KKStr &_name, kkint32 _maxNumOfBuffers)
Constructor.
~RasterBuffer ()
void AddRaster (RasterPtr raster)
Adds 'raster' to the end of the queue giving the queue ownership of the instance.
RasterPtr GetCopyOfLastImage ()
Returns a copy of the last Raster instance added to the queue; if buffer is empty will return NULL.
RasterPtr GetNextRaster ()
Removes from the buffer the oldest instance of 'Raster' and returns it to caller; if buffer is empty will return NULL.
kkint32 MaxNumOfBuffers () const
void MaxNumOfBuffers (kkint32 _maxNumOfBuffers)
kkint32 MemoryConsumedEstimated ()
Returns an estimate of the amount of memory consumed in bytes.
kkint32 NumAvailable () const
The number of entries that are left in the buffer before 'maxNumOfBuffers' is reached.
kkint32 NumPopulated () const
kkint32 RastersDropped () const
Returns the number of 'Raster' instances that had to be deleted because the size of the queue had reached 'maxNumOfBuffers'.
Detailed Description
Will manage a buffer that will allow multiple threads to add and remove instances of 'Raster' objects.
A 'GoalKeepeer' object 'gateKeeper' will be used to enforce integrity in the Multi-Threaded environment. It will guarantee that only one thread at a time can access the Raster Queue. This queue will take ownership of 'Raster' instances added to it via 'AddRaster'. It will pass ownership of the 'Raster' instances when it returns them in GetNextRaster. When a 'RasterBuffer' instance is deleted it will delete all the 'Raster' instances it still contains.
Definition at line 34 of file RasterBuffer.h.
Member Typedef Documentation
typedef RasterBuffer* KKB::RasterBuffer::RasterBufferPtr
Definition at line 37 of file RasterBuffer.h.
Constructor & Destructor Documentation
RasterBuffer::RasterBuffer (const KKStr & _name, kkint32 _maxNumOfBuffers)
Constructor.
Parameters
in _name Name of the buffer; this will be used by the associated 'GateKeeper' instance; should be unique.
in _maxNumOfBuffers The maximum number of raster instances that can be added to this buffer. When this limit has been reached the oldest entries in the list will be deleted when a new one is added (AddRaster).
Definition at line 39 of file RasterBuffer.cpp.
References KKB::GoalKeeper::Create(), KKB::KKStr::KKStr(), KKB::GoalKeeper::MemoryConsumedEstimated(), KKB::operator+(), and RasterBuffer().
Referenced by RasterBuffer().
                            :
  
    buffer (),
    gateKeeper (NULL),
    maxNumOfBuffers (_maxNumOfBuffers),
    memoryConsumed (0),
    name (_name),
    rastersDropped (0)
{
  GoalKeeper::Create ("RasterBuffer_" + name, gateKeeper);
  memoryConsumed = sizeof (RasterBuffer) + gateKeeper->
      MemoryConsumedEstimated ();
}
RasterBuffer::~RasterBuffer ()
Definition at line 56 of file RasterBuffer.cpp.
References KKB::GoalKeeper::Destroy().
{
  while (buffer.size () > 0)
  {
    RasterPtr r = buffer.front ();
    buffer.pop ();
    delete r;
    r = NULL;
  }
  GoalKeeper::Destroy (gateKeeper);
  gateKeeper = NULL;
}
Member Function Documentation
void RasterBuffer::AddRaster (RasterPtr raster)
Adds 'raster' to the end of the queue giving the queue ownership of the instance.
If the number of entries in the queue are already equal or greater than 'MaxNumOfBuffers' specified then the oldest instances in the queue(back of the queue) will be removed and deleted until the size of the queue is less than 'MaxNumOfBuffers' before adding this new instance.
Definition at line 105 of file RasterBuffer.cpp.
References KKB::KKStr::Concat(), KKB::GoalKeeper::EndBlock(), KKB::KKException::KKException(), KKB::Raster::MemoryConsumedEstimated(), and KKB::GoalKeeper::StartBlock().
{
  if (raster == NULL)
  {
    KKStr errMsg;
    errMsg << "RasterBuffer::AddRaster raster == NULL";
    cerr << std::endl << std::endl << errMsg << std::endl <<
      std::endl;
    throw KKException (errMsg);
  }
  gateKeeper->StartBlock ();
  while (buffer.size () >= (kkuint32)maxNumOfBuffers)
    ThrowOutOldestOccupiedBuffer ();
  buffer.push (raster);
  memoryConsumed = memoryConsumed + raster->MemoryConsumedEstimated ();
  gateKeeper->EndBlock ();
} /* AddFrame */
RasterPtr RasterBuffer::GetCopyOfLastImage ()
Returns a copy of the last Raster instance added to the queue; if buffer is empty will return NULL.
Caller will get ownership and be responsible for deleting it.
Definition at line 158 of file RasterBuffer.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
{
  RasterPtr result = NULL;
  gateKeeper->StartBlock ();
  if (buffer.size () > 0)
  {
    result = new Raster (*(buffer.back ()));
  }
  gateKeeper->EndBlock ();
  return result;
}
RasterPtr RasterBuffer::GetNextRaster ()
Removes from the buffer the oldest instance of 'Raster' and returns it to caller; if buffer is empty will return NULL.
Definition at line 128 of file RasterBuffer.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
{
  RasterPtr result = NULL;
  gateKeeper->StartBlock ();
  if (buffer.size () > 0)
  {
    result = buffer.front ();
    buffer.pop ();
    memoryConsumed = memoryConsumed - result->MemoryConsumedEstimated ();
  }
  gateKeeper->EndBlock ();
  return result;
} /* GetNextRaster */
kkint32 KKB::RasterBuffer::MaxNumOfBuffers () const [inline]
Definition at line 55 of file RasterBuffer.h.
{return maxNumOfBuffers;}
void KKB::RasterBuffer::MaxNumOfBuffers (kkint32 _maxNumOfBuffers) [inline]
Definition at line 69 of file RasterBuffer.h.
{maxNumOfBuffers = _maxNumOfBuffers;}
kkint32 RasterBuffer::MemoryConsumedEstimated ()
Returns an estimate of the amount of memory consumed in bytes.
This will help managed objects keep track of how much memory they are using in the unmanaged world.
Definition at line 147 of file RasterBuffer.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
{
  kkint32 result = 0;
  gateKeeper->StartBlock ();
  result = memoryConsumed;
  gateKeeper->EndBlock ();
  return result;
} /* MemoryConsumedEstimated */
kkint32 RasterBuffer::NumAvailable () const
The number of entries that are left in the buffer before 'maxNumOfBuffers' is reached.
Definition at line 93 of file RasterBuffer.cpp.
{
  return maxNumOfBuffers - (kkint32)buffer.size ();
}
kkint32 RasterBuffer::NumPopulated () const
Definition at line 99 of file RasterBuffer.cpp.
{
  return (kkint32)buffer.size ();
}
kkint32 KKB::RasterBuffer::RastersDropped () const [inline]
Returns the number of 'Raster' instances that had to be deleted because the size of the queue had reached 'maxNumOfBuffers'.
Definition at line 53 of file RasterBuffer.h.
{return rastersDropped;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/RasterBuffer.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/RasterBuffer.cpp