KKMLL::AttributeList Class Reference
#include <Attribute.h>
Public Member Functions
AttributeList ()
AttributeList (bool owner)
~AttributeList ()
AttributeTypeVectorPtr CreateAttributeTypeVector () const
const AttributePtr LookUpByName (const KKStr &attributeName) const
kkint32 MemoryConsumedEstimated () const
bool operator!= (const AttributeList &right) const
Determines if two different attribute lists are different; compares each respective attribute, name and type.
bool operator== (const AttributeList &right) const
Determines if two different attribute lists are the same; compares each respective attribute, name and type.
void PushOnBack (AttributePtr attribute)
void PushOnFront (AttributePtr attribute)
void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
void WriteXML (const KKStr &varName, std::ostream &o) const
Additional Inherited Members
Detailed Description
Definition at line 159 of file Attribute.h.
Constructor & Destructor Documentation
AttributeList::AttributeList ()
Definition at line 325 of file Attribute.cpp.
References AttributeList().
Referenced by AttributeList().
                             :
  KKQueue<Attribute> (true)
{
}
AttributeList::AttributeList (bool owner)
Definition at line 334 of file Attribute.cpp.
References AttributeList().
Referenced by AttributeList().
                                        :
  KKQueue<Attribute> (_owner)
{
}
AttributeList::~AttributeList ()
Definition at line 341 of file Attribute.cpp.
{
}
Member Function Documentation
AttributeTypeVectorPtr AttributeList::CreateAttributeTypeVector () const
Definition at line 406 of file Attribute.cpp.
References KKMLL::AttributeTypeVector::AttributeTypeVector().
{
  AttributeTypeVectorPtr v = new AttributeTypeVector ();
  const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    v->push_back ((*idx)->Type ());
  }
  return v;
} /* CreateAttributeTypeVector */
const AttributePtr AttributeList::LookUpByName (const KKStr & attributeName) const
Definition at line 370 of file Attribute.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), and KKB::KKStr::Upper().
{
  KKStr nameUpper (name);
  nameUpper.Upper ();
  map<KKStr, AttributePtr>::const_iterator p;
  p = nameIndex.find (nameUpper);
  if (p == nameIndex.end ())
    return NULL;
  return p->second;
} /* LookUpByName */
kkint32 AttributeList::MemoryConsumedEstimated () const
Definition at line 346 of file Attribute.cpp.
{
  kkint32 memoryConsumedEstimated = sizeof (AttributeList) + nameIndex.size ();
  
  {
    std::map<KKStr, AttributePtr>::const_iterator idx;
    for (idx = nameIndex.begin (); idx != nameIndex.end (); ++idx)
      memoryConsumedEstimated += (sizeof (AttributePtr) + idx->first.MemoryConsumedEstimated ()
      );
  }
  {
    AttributeList::const_iterator idx;
    for (idx = begin (); idx != end (); ++idx)
    {
      memoryConsumedEstimated += (*idx)->MemoryConsumedEstimated ();
    }
  }
  return memoryConsumedEstimated;
} /* MemoryConsumedEstimated */
bool AttributeList::operator!= (const AttributeList & right) const
Determines if two different attribute lists are different; compares each respective attribute, name and type.
Definition at line 494 of file Attribute.cpp.
References operator==().
{
  return !(*this == right);
} /* operator!= */
bool AttributeList::operator== (const AttributeList & right) const
Determines if two different attribute lists are the same; compares each respective attribute, name and type.
Definition at line 466 of file Attribute.cpp.
Referenced by operator!=().
{
  if (size () != right.size ())
    return false;
  AttributeList::const_iterator idxL;
  AttributeList::const_iterator idxR;
  idxL = begin ();
  idxR = right.begin ();
  while (idxL != end ())
  {
    AttributePtr leftAttribute = *idxL;
    AttributePtr rightAttribute = *idxR;
    if ((*leftAttribute) != (*rightAttribute))
      return false;
    ++idxL;
    ++idxR;
  }
  return true;
} /* operator== */
void AttributeList::PushOnBack (AttributePtr attribute)
Definition at line 384 of file Attribute.cpp.
{
  AddToNameIndex (attribute);
  KKQueue<Attribute>::PushOnBack (attribute);
}
void AttributeList::PushOnFront (AttributePtr attribute)
Definition at line 391 of file Attribute.cpp.
{
  AddToNameIndex (attribute);
  KKQueue<Attribute>::PushOnFront (attribute);
}
void AttributeList::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 527 of file Attribute.cpp.
References KKB::XmlStream::GetNextToken().
{
  DeleteContents ();
  Owner (true);
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (typeid (*t) == typeid(XmlElementAttribute))
    {
      XmlElementAttributePtr attrToken = dynamic_cast<
      XmlElementAttributePtr> (t);
      if (attrToken->Value ())
        PushOnBack (attrToken->TakeOwnership ());
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
}
void AttributeList::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 501 of file Attribute.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKMLL::Attribute::WriteXML(), KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("AttributeList", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  AttributeList::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    AttributePtr attribute = *idx;
    attribute->WriteXML ("", o);
  }
  XmlTag endTag ("AttributeList", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/Attribute.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/Attribute.cpp