SVM289_MFS::Solver_NU Class Reference
Public Member Functions
Solver_NU ()
void Solve (kkint32 l, QMatrix &Q, const double *p, const schar *y, double *alpha, double Cp, double Cn, double eps, SolutionInfo *si, kkint32 shrinking)
Additional Inherited Members
Detailed Description
Definition at line 1837 of file svm2.cpp.
Constructor & Destructor Documentation
SVM289_MFS::Solver_NU::Solver_NU () [inline]
Definition at line 1840 of file svm2.cpp.
{}
Member Function Documentation
void SVM289_MFS::Solver_NU::Solve (kkint32 l, QMatrix & Q, const double * p, const schar * y, double * alpha, double Cp, double Cn, double eps, SolutionInfo * si, kkint32 shrinking) [inline]
Definition at line 1842 of file svm2.cpp.
References SVM289_MFS::Solver::Solve().
Referenced by SVM289_MFS::solve_nu_svc(), and solve_nu_svr().
  {
    this->si = si;
    Solver::Solve (l, Q, p, y, alpha, Cp, Cn, eps, si, shrinking);
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm2.cpp