KKMLL::DuplicateImageList Class Reference
#include <DuplicateImages.h>
Public Member Functions
DuplicateImageList (bool _owner)
~DuplicateImageList ()
DuplicateImagePtr LocateByImage (FeatureVectorPtr example)
Additional Inherited Members
Detailed Description
Definition at line 163 of file DuplicateImages.h.
Constructor & Destructor Documentation
DuplicateImageList::DuplicateImageList (bool _owner)
Definition at line 480 of file DuplicateImages.cpp.
References DuplicateImageList().
Referenced by DuplicateImageList(), and KKMLL::DuplicateImages::DuplicateImages().
                                                  :
  KKQueue<DuplicateImage> (_owner)
{
}
DuplicateImageList::~DuplicateImageList ()
Definition at line 487 of file DuplicateImages.cpp.
{
}
Member Function Documentation
DuplicateImagePtr DuplicateImageList::LocateByImage (FeatureVectorPtr example)
Definition at line 493 of file DuplicateImages.cpp.
References KKMLL::DuplicateImage::AlreadyHaveExample().
Referenced by KKMLL::DuplicateImages::AddSingleExample().
{
  for (DuplicateImageList::iterator idx = begin (); idx != end (); idx++)
  {
    DuplicateImagePtr dupExampleSet = *idx;
    if (dupExampleSet->AlreadyHaveExample (example))
      return dupExampleSet;
  }
  return NULL;
} /* LocateByImage */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/DuplicateImages.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/DuplicateImages.cpp