KKMLL::FactoryFVProducer Class Reference
Responsible for creating a FeatureFectorProducer instance.
#include <FactoryFVProducer.h>
Public Types
typedef FactoryFVProducer * FactoryFVProducerPtr
Public Member Functions
FactoryFVProducer (const KKStr &_name, const KKStr &_fvClassName, const KKStr &_description)
virtual FeatureFileIOPtr DefaultFeatureFileIO () const =0
const KKStr & Description () const
virtual const type_info * FeatureVectorListTypeId () const =0
Returns the 'type_info' of the FeatureVectorList that this instance of 'FactoryFVProducer' will create.
virtual const type_info * FeatureVectorTypeId () const =0
Returns the 'type_info' of the FeatureVector that this instance of 'FactoryFVProducer' works with.
virtual FileDescPtr FileDesc () const =0
const KKStr & FvClassName () const
virtual FeatureVectorProducerPtr ManufactureInstance (RunLog &runLog)=0
Derived classes will instantiate appropriate instances of 'FeatureVectorProducer'.
virtual FeatureVectorPtr ManufacturFeatureVector (kkint32 numOfFeatires, RunLog &runLog)
Manufactures a instance of a derived 'FeatureVector' class that is appropriate for containing instances of FeatureVectors produced by the associated FeatureVectorProducer.
virtual FeatureVectorListPtr ManufacturFeatureVectorList (bool owner, RunLog &runLog) const
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors produced by the associated FeatureVectorProducer.
virtual TrainingConfiguration2Ptr ManufacturTrainingConfiguration () const
Returns a 'TrainingConfiguration2' derived instance.
const KKStr & Name () const
Static Public Member Functions
static FactoryFVProducerPtr LookUpFactory (const KKStr &name)
Returns pointer to existing instance of 'FactoryFVProducer' that was previously registered with 'name'.
static FeatureVectorProducerPtr ManufactureInstance (const KKStr &name, RunLog &runLog)
Will instantiate a new instance of the appropriate 'FeatureVectorProducer' class given the supplied name.
static void RegisterFactory (FactoryFVProducerPtr factory, RunLog *runLog)
This is where you register newly instantiated instances of 'FactoryFVProducer' derived classes.
Protected Member Functions
virtual ~FactoryFVProducer ()
A Factory can near be deleted until the application terminates; the atexit method will perform the deletes.
Detailed Description
Responsible for creating a FeatureFectorProducer instance.
To make the 'KKMLL' library independent of the actual details of the FeatureVetir computations and their underlying source data a Factory - Producer strategy was implemented. For every FeatureVector derived class there will be at least one 'FeatureVectorProducer' derived class and one 'FactoryFVProducer' derived class.
-FeatureVectorProducer Responsible for computing instances of 'FeatureVector' derived classes from source data such as a `Raster` instance. -FactoryFVProducer Responsible for creating new instances of the 'FeatureVectorProducer' derived classes. Will also provide the appropriate 'FileDesc' instance that describes the features computed and Instantiate new `FeatureVectorList` derived instances for containing the produced FeatureFevtor derived instances.
New FeatureVector instances will be computed by a instance of the 'FeatureVectorProducer' class. The appropriate 'FeatureVectorProducer' derived class will be manufactured by a corresponding 'FactoryFVProducer' class. This class(FactoryFVProducer) will maintain a list of all 'FactoryFVProducer' derived classes created in the 'factories' static data member.
The idea is for each class derived from FeatureVector there will be a corresponding 'FeatureVectorProducer' and 'FactoryFVProducer'. The 'FeatureVectorProducer' will be responsible for generating 'FeatureVector' instances from source data(Images) and the 'FactoryFVProducer' class will generate the correct 'FactoryFVProducer' to do these computations. Other functions of this class are to return the corresponding `FileDesc` instance, that describes the features that are going to be computed, and the appropriate 'FeatureFectorList' derived container.
Definition at line 72 of file FactoryFVProducer.h.
Member Typedef Documentation
typedef FactoryFVProducer* KKMLL::FactoryFVProducer::FactoryFVProducerPtr
Definition at line 75 of file FactoryFVProducer.h.
Constructor & Destructor Documentation
FactoryFVProducer::FactoryFVProducer (const KKStr & _name, const KKStr & _fvClassName, const KKStr & _description)
Definition at line 32 of file FactoryFVProducer.cpp.
References KKB::KKStr::KKStr().
                                      :
     description (_description),
     fvClassName (_fvClassName),
     name (_name)
{
}
FactoryFVProducer::~FactoryFVProducer () [protected], [virtual]
A Factory can near be deleted until the application terminates; the atexit method will perform the deletes.
Definition at line 45 of file FactoryFVProducer.cpp.
{
}
Member Function Documentation
virtual FeatureFileIOPtr KKMLL::FactoryFVProducer::DefaultFeatureFileIO () const [pure virtual]
Implemented in KKMLL::GrayScaleImagesFVProducerFactory.
Referenced by KKMLL::TrainingConfiguration2::LoadOtherClasssExamples().
const KKStr& KKMLL::FactoryFVProducer::Description () const [inline]
Definition at line 89 of file FactoryFVProducer.h.
{return description;}
virtual const type_info* KKMLL::FactoryFVProducer::FeatureVectorListTypeId () const [pure virtual]
Returns the 'type_info' of the FeatureVectorList that this instance of 'FactoryFVProducer' will create.
Implemented in KKMLL::GrayScaleImagesFVProducerFactory.
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink().
virtual const type_info* KKMLL::FactoryFVProducer::FeatureVectorTypeId () const [pure virtual]
Returns the 'type_info' of the FeatureVector that this instance of 'FactoryFVProducer' works with.
Implemented in KKMLL::GrayScaleImagesFVProducerFactory.
virtual FileDescPtr KKMLL::FactoryFVProducer::FileDesc () const [pure virtual]
Implemented in KKMLL::GrayScaleImagesFVProducerFactory.
Referenced by KKMLL::TrainingProcess2::CreateModelsFromTrainingData(), KKMLL::FeatureFileIO::FeatureDataReSink(), KKMLL::GrayScaleImagesFVList::GrayScaleImagesFVList(), KKMLL::FeatureFileIO::LoadInSubDirectoryTree(), ManufacturFeatureVectorList(), KKMLL::Model::Model(), KKMLL::TrainingProcess2::ReadXML(), KKMLL::TrainingConfiguration2::ReadXMLPost(), and KKMLL::TrainingConfiguration2::TrainingConfiguration2().
const KKStr& KKMLL::FactoryFVProducer::FvClassName () const [inline]
Definition at line 90 of file FactoryFVProducer.h.
{return fvClassName;}
FactoryFVProducerPtr FactoryFVProducer::LookUpFactory (const KKStr & name) [static]
Returns pointer to existing instance of 'FactoryFVProducer' that was previously registered with 'name'.
Parameters
in name The name of the 'FactoryFVProducer' that you are locking for; this is the same name as would have been passed to the constructor.
Returns
The existing 'FactoryFVProducer' instance of found otherwise NULL.
Definition at line 89 of file FactoryFVProducer.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKMLL::TrainingProcess2::ReadXML().
{
  FactoryFVProducerPtr factory = NULL;
  GlobalGoalKeeper::StartBlock ();
  if (!factories)
  {
    factories = new FactoryMap ();
    atexit (FactoryFVProducer::FinaleCleanUp);
    atExitDefined = true;
  }
  FactoryMap::iterator idx;
  idx = factories->find (_name);
  if (idx != factories->end ())
    factory = idx->second;
  GlobalGoalKeeper::EndBlock ();
  return factory;
} /* LookUpFactory */
virtual FeatureVectorProducerPtr KKMLL::FactoryFVProducer::ManufactureInstance (RunLog & runLog) [pure virtual]
Derived classes will instantiate appropriate instances of 'FeatureVectorProducer'.
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
static FeatureVectorProducerPtr KKMLL::FactoryFVProducer::ManufactureInstance (const KKStr & name, RunLog & runLog) [static]
Will instantiate a new instance of the appropriate 'FeatureVectorProducer' class given the supplied name.
Parameters
in name The name given the 'FactoryFVProducer' instance when originally instantiated; this will typically be the name of the 'FeatureVector' derived Class.
in runLog reference to the logger where messages will be written to.
Returns
returns a new instance of 'FeatureVectorProducer' that will be generated by registered 'FactoryFVProducer'; If 'name' is not found will return NULL.
FeatureVectorPtr FactoryFVProducer::ManufacturFeatureVector (kkint32 numOfFeatires, RunLog & runLog) [virtual]
Manufactures a instance of a derived 'FeatureVector' class that is appropriate for containing instances of FeatureVectors produced by the associated FeatureVectorProducer.
Definition at line 50 of file FactoryFVProducer.cpp.
References KKMLL::FeatureVector::FeatureVector().
{
  return new FeatureVector (numOfFeatires);
}
FeatureVectorListPtr FactoryFVProducer::ManufacturFeatureVectorList (bool owner, RunLog & runLog) const [virtual]
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors produced by the associated FeatureVectorProducer.
Definition at line 58 of file FactoryFVProducer.cpp.
References KKMLL::FeatureVectorList::FeatureVectorList(), and FileDesc().
Referenced by KKMLL::TrainingProcess2::ExtractTrainingClassFeatures(), KKMLL::FeatureFileIO::FeatureDataReSink(), KKMLL::TrainingConfiguration2::LoadFeatureDataFromTrainingLibraries(), and KKMLL::FeatureFileIO::LoadInSubDirectoryTree().
{
  return new FeatureVectorList (FileDesc (), owner);
}
TrainingConfiguration2Ptr FactoryFVProducer::ManufacturTrainingConfiguration () const [virtual]
Returns a 'TrainingConfiguration2' derived instance.
Definition at line 68 of file FactoryFVProducer.cpp.
References KKMLL::TrainingConfiguration2::TrainingConfiguration2().
Referenced by KKMLL::TrainingConfiguration2::CreateFromDirectoryStructure(), and KKMLL::ModelDual::TrainModel().
{
  return new TrainingConfiguration2 ();
}
const KKStr& KKMLL::FactoryFVProducer::Name () const [inline]
Definition at line 91 of file FactoryFVProducer.h.
Referenced by KKMLL::TrainingProcess2::WriteXML().
{return name;}
void FactoryFVProducer::RegisterFactory (FactoryFVProducerPtr factory, RunLog * runLog) [static]
This is where you register newly instantiated instances of 'FactoryFVProducer' derived classes.
The instance will be added to a list of existing factories `FactoryFVProducer::factories`. This list is a map structure indexed by `FactoryFVProducer::Name()`. If an instance with the same name already exists a appropriate error message will be written to the `runLog` and will not be added to `FactoryFVProducer::factories`.
Parameters
in factory The newly created instance of a `FactoryFVProducer` derived class that you want to register.
in runLog Pointer to logger; if equal NULL will write messages to temp created instance.
Definition at line 116 of file FactoryFVProducer.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), KKB::RunLog::RunLog(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKMLL::GrayScaleImagesFVProducerFactory::Factory().
{
  bool weOwnRunLog = false;
  if (runLog == NULL)
  {
    runLog = new RunLog ();
    weOwnRunLog = true;
  }
  if (factory == NULL)
  {
    runLog->Level (-1) << "FactoryFVProducer::RegisterFactory ***ERROR*** factory==NULL" <<
      endl;
  }
  else
  {
    GlobalGoalKeeper::StartBlock ();
    runLog->Level (30) << "FactoryFVProducer::RegisterFactory Name: " << factory->
      Name () << " Description: " << factory->Description () << endl;
    if (!factories)
    {
      factories = new FactoryMap ();
      atexit (FactoryFVProducer::FinaleCleanUp);
      atExitDefined = true;
    }
    FactoryMap::iterator idx;
    idx = factories->find (factory->Name ());
    if (idx != factories->end ())
    {
      runLog->Level (-1) << "FactoryFVProducer::RegisterFactory ***ERROR*** Factory With Name: " <
      < factory->Name () << " already defined." << endl;
    }
    else
    {
      factories->insert (pair<KKStr,FactoryFVProducerPtr> (factory->Name (), factory));
    }
    GlobalGoalKeeper::EndBlock ();
  }
  if (weOwnRunLog)
  {
    delete runLog;
    runLog = NULL;
  }
  return;
} /* RegisterFactory */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FactoryFVProducer.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FactoryFVProducer.cpp