KKMLL::ImageFeaturesNameIndexed Class Reference
#include <ImageFeaturesNameIndexed.h>
Public Member Functions
ImageFeaturesNameIndexed ()
ImageFeaturesNameIndexed (const FeatureVectorList &images)
Additional Inherited Members
Detailed Description
Definition at line 27 of file ImageFeaturesNameIndexed.h.
Constructor & Destructor Documentation
ImageFeaturesNameIndexed::ImageFeaturesNameIndexed ()
Definition at line 33 of file ImageFeaturesNameIndexed.cpp.
References ImageFeaturesNameIndexed().
Referenced by KKMLL::DuplicateImages::DuplicateImages(), and ImageFeaturesNameIndexed().
                                                   :
   RBTree<FeatureVector, ExtractExampleFileName, KKStr>
       (extractImageFileName, false)
{
}
ImageFeaturesNameIndexed::ImageFeaturesNameIndexed (const FeatureVectorList & images)
Definition at line 40 of file ImageFeaturesNameIndexed.cpp.
References ImageFeaturesNameIndexed().
Referenced by ImageFeaturesNameIndexed().
                                                                                     :
   RBTree<FeatureVector, ExtractExampleFileName, KKStr>
       (extractImageFileName, false)
{
  FeatureVectorPtr example = NULL;
  for (auto idx: examples)
  {
    example = idx;
    RBInsert (example);
  }
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ImageFeaturesNameIndexed.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ImageFeaturesNameIndexed.cpp