KKMLL::ClassAssignments Class Reference
Binds MLClass objects to the appropriate number that the Learning Algorithm expects.
#include <ClassAssignments.h>
Public Member Functions
ClassAssignments ()
ClassAssignments (const MLClassList &classes)
Creates assignment for all classes in 'classes.
void AddMLClass (MLClassPtr mlClass, kkint16 num, RunLog &log)
MLClassPtr GetMLClass (kkint16 num) const
MLClassPtr GetMLClassByIndex (size_t idx)
MLClassList GetMLClasses (kkint16 num) const
kkint16 GetNumForClass (MLClassPtr mlClass) const
VectorShort GetUniqueListOfAssignments () const
kkint32 MemoryConsumedEstimated () const
void ParseToString (const KKStr &_toString, RunLog &_log)
Loads class assignments from string that was originally generated by ToString.
void Save (const KKStr &fileName, bool &successful)
KKStr ToString () const
Detailed Description
Binds MLClass objects to the appropriate number that the Learning Algorithm expects.
Author
Kurt Kramer
This class will bind MLClass objects to the appropriate number that the learning algorithm knows for this class. When originally implementing this system, this info was kept in the MLClass object. This would cause problems when doing multilevel classification. The same MLClass might be known to the L.A. as one number in one level and another number in a different level. This caused us to have to maintain a separate instantiation of these classes on the SvmModel objects.
It is sub-classed from multimap<kkint16, MLClassPtr>. This allows for fast lookup by number. There is also a secondary index by MLClass. This allows us to do a fast lookup by class.
Definition at line 36 of file ClassAssignments.h.
Constructor & Destructor Documentation
ClassAssignments::ClassAssignments ()
Definition at line 25 of file ClassAssignments.cpp.
References ClassAssignments().
Referenced by ClassAssignments(), KKMLL::ModelOldSVM::ReadXML(), and KKMLL::SVMModel::SVMModel().
                                   :
    multimap<kkint16, MLClassPtr> ()
{
}
ClassAssignments::ClassAssignments (const MLClassList & classes)
Creates assignment for all classes in 'classes.
Constructs a list assigning a number to each class sequentially from 'classes'. Use this constructor if each class is treated uniquely by the learning algorithm.
Parameters
in classes,List of classes to make assignments for.
in,out _log,Run log to write messages to
Definition at line 32 of file ClassAssignments.cpp.
References ClassAssignments().
Referenced by ClassAssignments(), and KKMLL::ModelOldSVM::TrainModel().
                                                              :
    multimap<kkint16, MLClassPtr> ()
{
  kkint32 x = 0;
  for (MLClassList::const_iterator idx = classes.begin (); idx != classes.end
      (); idx++)
  {
   insert (pair<kkint16, MLClassPtr> (x, *idx));
   classLookUp.insert (pair<MLClassPtr, kkint16> (*idx, x));
   x++;
  }
}
Member Function Documentation
void ClassAssignments::AddMLClass (MLClassPtr mlClass, kkint16 num, RunLog & log)
Definition at line 56 of file ClassAssignments.cpp.
Referenced by ParseToString().
{
  ClassLookUpIterator idx;
  idx = classLookUp.find (mlClass);
  if (idx != classLookUp.end ())
  {
    log.Level (-1) << endl << endl
                   << "ClassAssignments::AddMLClass ***ERROR*** Duplicate Class Being Added[" <<
      mlClass->Name () << "]." << endl
                   << " Num Found [" << idx->second << "]" <<
      endl
                   << " New Num Being Added [" << num <<
      endl
                   << endl;
    return;
  }
  insert (pair<kkint16, MLClassPtr> (num, mlClass));
  classLookUp.insert (pair<MLClassPtr, kkint16> (mlClass, num));
} /* AddMLClass */
MLClassPtr ClassAssignments::GetMLClass (kkint16 num) const
Definition at line 81 of file ClassAssignments.cpp.
Referenced by KKMLL::SVMModel::Predict(), KKMLL::SVMModel::PredictRaw(), KKMLL::SVMModel::ProbabilitiesByClass(), and KKMLL::SVMparam::ProbClassPairsInitialize().
{
  multimap<kkint16, MLClassPtr>::const_iterator p;
  p = find (num);
  if (p == end ())
    return NULL;
  return p->second;
} /* GetMLClass */
MLClassPtr ClassAssignments::GetMLClassByIndex (size_t idx)
Definition at line 144 of file ClassAssignments.cpp.
{
  if ((idx < 0) || (idx >= (size_t)size ()))
  {
    cerr << endl
         << endl
         << "ClassAssignments::GetMLClassByIndex *** ERROR ***" << endl
         << " idx[" << idx << "] is out of range." <<
      endl
         << endl;
    return NULL;
  }
  iterator i = begin ();
  for (size_t x = 0; x < idx; x++)
    i++;
  return i->second;
} /* GetMLClassByIndex */
MLClassList ClassAssignments::GetMLClasses (kkint16 num) const
Definition at line 94 of file ClassAssignments.cpp.
{
  ClassAssignments::const_iterator idx;
  MLClassList results;
  for (idx = begin (); idx != end (); idx++)
  {
    if (idx->first == num)
      results.PushOnBack (idx->second);
  }
  return results;
} /* GetMLClasses */
kkint16 ClassAssignments::GetNumForClass (MLClassPtr mlClass) const
Definition at line 167 of file ClassAssignments.cpp.
Referenced by KKMLL::FeatureEncoder::EncodeIntoSparseMatrix(), and KKMLL::SVMModel::Predict().
{
  ClassLookUp::const_iterator idx;
  idx = classLookUp.find (mlClass);
  if (idx == classLookUp.end ())
    return -1;
  else
    return idx->second;
} /* GetNumForClass */
VectorShort ClassAssignments::GetUniqueListOfAssignments () const
Definition at line 111 of file ClassAssignments.cpp.
{
  VectorShort nums;
  ClassAssignments::const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    nums.push_back (idx->first);
  }
  sort (nums.begin (), nums.end ());
  VectorShort results;
  kkint16 lastNum = -999;
  VectorShort::const_iterator idx2;
  for (idx2 = nums.begin (); idx2 != nums.end (); idx2++)
  {
    if (*idx2 != lastNum)
    {
      lastNum = *idx2;
      results.push_back (lastNum);
    }
  }
  return results;
} /* GetUniqueListOfAssignments */
kkint32 ClassAssignments::MemoryConsumedEstimated () const
Definition at line 46 of file ClassAssignments.cpp.
Referenced by KKMLL::ModelOldSVM::MemoryConsumedEstimated(), and KKMLL::SVMModel::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = sizeof (ClassAssignments)
    + (classLookUp.size () * (sizeof (MLClassPtr) + sizeof (kkint16)));
  return memoryConsumedEstimated;
}
void ClassAssignments::ParseToString (const KKStr & _toString, RunLog & _log)
Loads class assignments from string that was originally generated by ToString.
Parameters
in _toString,KKStr containing class assignments info, will expect to be formated the way ToString() creates them.
Definition at line 222 of file ClassAssignments.cpp.
References AddMLClass(), KKB::KKStr::Concat(), KKMLL::MLClass::CreateNewMLClass(), KKB::KKStr::Empty(), KKB::KKStr::ExtractToken(), KKB::KKStr::ExtractTokenInt(), and KKB::KKStr::KKStr().
{
  erase (begin (), end ());
  KKStr toString (_toString);
  // Remove Class count from string
  toString.ExtractTokenInt ("\t\n\r");
  while (!toString.Empty ())
  {
    kkint32 assignmentNum = toString.ExtractTokenInt ("\t\n\r");
    KKStr className = toString.ExtractToken ("\t\n\r");
    if (!className.Empty ())
    {
      MLClassPtr mlClass = MLClass::CreateNewMLClass (className);
      AddMLClass (mlClass, assignmentNum, _log);
    }
  }
} /* ParseToString */
void ClassAssignments::Save (const KKStr & fileName, bool & successful)
Definition at line 180 of file ClassAssignments.cpp.
{
  ofstream outFile (fileName.Str ());
  for (iterator idx = begin (); idx != end (); idx++)
  {
    outFile << idx->second->Name () << "\t" << idx->first << endl;
  }
  successful = true;
  return;
}
KKStr ClassAssignments::ToString () const
Definition at line 198 of file ClassAssignments.cpp.
References KKB::KKStr::Concat().
Referenced by KKMLL::ModelOldSVM::WriteXML(), and KKMLL::SVMModel::WriteXML().
{
  KKStr result ((kkint32)(size () * 20));
  result << kkint32 (size ());
  ClassAssignments::const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    result << "\t" << idx->first << "\t" << idx->second->Name ();
  }
  return result;
} /* ToString */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ClassAssignments.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ClassAssignments.cpp