KKB::XmlFactoryManager Class Reference
#include <XmlStream.h>
Public Member Functions
XmlFactoryManager (const KKStr &_name)
~XmlFactoryManager ()
summary>Give the FactoryManager instance ownership of this factory; the name of the factory must be unique.
XmlFactory * FactoryLookUp (const KKStr &className) const
void RegisterFactory (XmlFactory *factory)
Detailed Description
Definition at line 357 of file XmlStream.h.
Constructor & Destructor Documentation
XmlFactoryManager::XmlFactoryManager (const KKStr & _name)
Definition at line 939 of file XmlStream.cpp.
References KKB::KKStr::KKStr(), and XmlFactoryManager().
Referenced by KKB::XmlFactory::FactoryLookUp(), KKB::XmlFactory::RegisterFactory(), and XmlFactoryManager().
                                                        :
  factories (),
  name (_name)
{
}
XmlFactoryManager::~XmlFactoryManager ()
summary>Give the FactoryManager instance ownership of this factory; the name of the factory must be unique.
Definition at line 946 of file XmlStream.cpp.
{
  map<KKStr, XmlFactory*>::iterator idx;
  for (idx = factories.begin (); idx != factories.end (); ++idx)
  {
    XmlFactory* f = idx->second;
    delete f;
  }
  factories.clear ();
}
Member Function Documentation
XmlFactory * XmlFactoryManager::FactoryLookUp (const KKStr & className) const
Definition at line 979 of file XmlStream.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKB::XmlFactory::FactoryLookUp(), and RegisterFactory().
{
  GlobalGoalKeeper::StartBlock ();
  XmlFactory* result = NULL;
  map<KKStr, XmlFactory*>::const_iterator idx;
  idx = factories.find (className);
  if (idx == factories.end ())
    result = NULL;
  else
    result = idx->second;
  GlobalGoalKeeper::EndBlock ();
  return result;
} /* FactoryLookUp */
void XmlFactoryManager::RegisterFactory (XmlFactory * factory)
Definition at line 959 of file XmlStream.cpp.
References KKB::XmlFactory::ClassName(), KKB::KKStr::Concat(), KKB::GlobalGoalKeeper::EndBlock(), FactoryLookUp(), KKB::KKException::KKException(), KKB::KKStr::KKStr(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKB::XmlFactory::RegisterFactory().
{
  GlobalGoalKeeper::StartBlock ();
  XmlFactory* existingFactory = FactoryLookUp (factory->
      ClassName ());
  if (existingFactory)
  {
    GlobalGoalKeeper::EndBlock ();
    KKStr errMsg (200);
    errMsg << "XmlFactoryManager::RegisterFactory FactoryManager[" << name << "] Factory[" << factory->
      ClassName () << "] already exists." ;
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  else
  {
    factories.insert (pair<KKStr, XmlFactory*> (factory->ClassName (), factory));
  }
  GlobalGoalKeeper::EndBlock ();
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp