KKMLL::TrainingConfiguration2::Factory Class Reference
#include <TrainingConfiguration2.h>
Public Member Functions
Factory ()
Factory (const KKStr &_className)
virtual const KKStr & ClassName ()
virtual TrainingConfiguration2Ptr Manufacture (const KKStr &_configFileName, bool _validateDirectories, RunLog &_log)
Detailed Description
Will be one TrainingConfiguration2::Factory derived class for each derived class of `TrainingConfiguration2`; they will be responsible for creating an instance of the correct `TrainingConfiguration2` derived instance. The static member `TrainingConfiguration2::registeredFactories` will keep track of all instances of the Factory derived class.
Definition at line 514 of file TrainingConfiguration2.h.
Constructor & Destructor Documentation
KKMLL::TrainingConfiguration2::Factory::Factory () [inline]
Definition at line 517 of file TrainingConfiguration2.h.
References KKB::KKStr::KKStr().
Referenced by KKMLL::TrainingConfiguration2::FactoryInstace().
: className ("TrainingConfiguration2::Factory") {}
KKMLL::TrainingConfiguration2::Factory::Factory (const KKStr & _className) [inline]
Definition at line 518 of file TrainingConfiguration2.h.
References KKB::KKStr::KKStr().
: className (_className) {}
Member Function Documentation
virtual const KKStr& KKMLL::TrainingConfiguration2::Factory::ClassName () [inline], [virtual]
Definition at line 521 of file TrainingConfiguration2.h.
{return className;}
TrainingConfiguration2Ptr TrainingConfiguration2::Factory::Manufacture (const KKStr & _configFileName, bool _validateDirectories, RunLog & _log) [virtual]
Definition at line 2493 of file TrainingConfiguration2.cpp.
References KKMLL::TrainingConfiguration2::Load(), and KKMLL::TrainingConfiguration2::TrainingConfiguration2().
{
  TrainingConfiguration2Ptr config = new
      TrainingConfiguration2 ();
  config->Load (configFileName, validateDirectories, log);
  return config;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/TrainingConfiguration2.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/TrainingConfiguration2.cpp