XmlFactoryTrainingClass Class Reference
Public Member Functions
XmlFactoryTrainingClass ()
virtual XmlElementTrainingClass * ManufatureXmlElement (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
Static Public Member Functions
static XmlFactoryTrainingClass * FactoryInstance ()
Static Public Attributes
static XmlFactoryTrainingClass * factoryInstance = XmlFactoryTrainingClass::FactoryInstance ()
Detailed Description
Definition at line 476 of file TrainingClass.cpp.
Constructor & Destructor Documentation
XmlFactoryTrainingClass::XmlFactoryTrainingClass () [inline]
Definition at line 479 of file TrainingClass.cpp.
References KKB::XmlFactory::XmlFactory().
Referenced by FactoryInstance().
: XmlFactory ("TrainingClass") {}
Member Function Documentation
static XmlFactoryTrainingClass* XmlFactoryTrainingClass::FactoryInstance () [inline], [static]
Definition at line 492 of file TrainingClass.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), factoryInstance, KKB::XmlFactory::RegisterFactory(), KKB::GlobalGoalKeeper::StartBlock(), and XmlFactoryTrainingClass().
    {
      if (factoryInstance == NULL)
      {
        GlobalGoalKeeper::StartBlock ();
        if (!factoryInstance)
        {
          factoryInstance = new XmlFactoryTrainingClass ();
          XmlFactory::RegisterFactory (factoryInstance);
        }
        GlobalGoalKeeper::EndBlock ();
       }
      return factoryInstance;
    }
virtual XmlElementTrainingClass* XmlFactoryTrainingClass::ManufatureXmlElement (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log) [inline], [virtual]
Implements KKB::XmlFactory.
Definition at line 481 of file TrainingClass.cpp.
    {
      return new XmlElementTrainingClass(tag, s, cancelFlag, log);
    }
Member Data Documentation
XmlFactoryTrainingClass * XmlFactoryTrainingClass::factoryInstance = XmlFactoryTrainingClass::FactoryInstance () [static]
Definition at line 490 of file TrainingClass.cpp.
Referenced by FactoryInstance().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/TrainingClass.cpp