KKB::Point Class Reference
Used by Raster class and MorphOp derived classes to denote a single pixel location in Raster image.
#include <Point.h>
Public Member Functions
Point ()
Point (const Point &point)
Point (kkint16 _row, kkint16 _col)
Point (kkint32 _row, kkint32 _col)
Point (float _row, float _col)
kkint32 Col () const
void Col (kkint32 _col)
Point DownOne () const
Point LeftOne () const
bool operator!= (const Point &r) const
Point operator+ (const Point &r) const
Point operator- (const Point &r) const
Point & operator= (const Point &r)
bool operator== (Point &r) const
Point RightOne () const
kkint32 Row () const
void Row (kkint32 _row)
Point UpOne () const
Detailed Description
Used by Raster class and MorphOp derived classes to denote a single pixel location in Raster image.
See also
Raster
MorphOp
Definition at line 20 of file Point.h.
Constructor & Destructor Documentation
Point::Point ()
Definition at line 18 of file Point.cpp.
             :
  row (0),
  col (0)
{
}
Point::Point (const Point & point)
Definition at line 26 of file Point.cpp.
                                :
   row (point.row),
   col (point.col)
{
}
Point::Point (kkint16 _row, kkint16 _col)
Definition at line 34 of file Point.cpp.
Referenced by KKB::Raster::DeriveImageLength().
               :
  row (_row),
  col (_col)
{}
Point::Point (kkint32 _row, kkint32 _col)
Definition at line 43 of file Point.cpp.
Referenced by KKB::Blob::BotRight(), KKB::PointList::CalculateCenterPoint(), KKB::ContourFollower::CreatePointListFromFourier(), DownOne(), KKB::Raster::DrawPointList(), LeftOne(), operator+(), operator-(), RightOne(), KKB::Raster::RotateDerivePreRotatedPoint(), KKB::ConvexHull::Store(), KKB::Raster::ThinContour(), KKB::Blob::TopLeft(), and UpOne().
               :
  row (_row),
  col (_col)
{}
Point::Point (float _row, float _col)
Definition at line 52 of file Point.cpp.
               :
   row ((kkint32)(_row + 0.5)),
   col ((kkint32)(_col + 0.5))
{}
Member Function Documentation
kkint32 KKB::Point::Col () const [inline]
Definition at line 40 of file Point.h.
Referenced by KKB::PointList::BoxCoordinites(), KKB::PointList::CalculateCenterPoint(), KKB::ContourFollower::CreateFourierDescriptorBySampling(), KKB::ContourFollower::CreateFourierFromPointList(), DistanceSquare(), KKB::ConvexHull::Draw(), KKB::Raster::DrawCircle(), KKB::Raster::DrawConnectedPointList(), KKB::Raster::DrawDot(), KKB::Raster::DrawFatLine(), KKB::Raster::DrawLine(), KKB::Raster::DrawPointList(), KKB::ContourFollower::HistogramDistanceFromAPointOfEdge(), KKB::operator<<(), KKB::Raster::RotateDerivePreRotatedPoint(), KKB::Raster::SetPixelValue(), KKB::Raster::ThinContour(), and KKB::PointList::ToDelStr().
{return col;}
void KKB::Point::Col (kkint32 _col) [inline]
Definition at line 43 of file Point.h.
{col = _col;}
Point KKB::Point::DownOne () const [inline]
Definition at line 46 of file Point.h.
References Point().
{return Point (row + 1, col);}
Point KKB::Point::LeftOne () const [inline]
Definition at line 47 of file Point.h.
References Point().
{return Point (row , col - 1);}
bool Point::operator!= (const Point & r) const
Definition at line 66 of file Point.cpp.
{
  return ((row != r.row) || (col != r.col));
}
Point Point::operator+ (const Point & r) const
Definition at line 72 of file Point.cpp.
References Point().
Referenced by KKB::Raster::DrawConnectedPointList().
{
  return Point (row + r.row, col + r.col);
}
Point Point::operator- (const Point & r) const
Definition at line 78 of file Point.cpp.
References Point().
{
  return Point (row - r.row, col - r.col);
}
Point & Point::operator= (const Point & r)
Definition at line 84 of file Point.cpp.
{
  row = r.row;
  col = r.col;
  return *this;
}
bool Point::operator== (Point & r) const
Definition at line 60 of file Point.cpp.
{
  return ((row == r.row) && (col == r.col));
}
Point KKB::Point::RightOne () const [inline]
Definition at line 48 of file Point.h.
References Point().
{return Point (row , col + 1);}
kkint32 KKB::Point::Row () const [inline]
Definition at line 39 of file Point.h.
Referenced by KKB::PointList::BoxCoordinites(), KKB::PointList::CalculateCenterPoint(), KKB::ContourFollower::CreateFourierDescriptorBySampling(), KKB::ContourFollower::CreateFourierFromPointList(), DistanceSquare(), KKB::ConvexHull::Draw(), KKB::Raster::DrawCircle(), KKB::Raster::DrawConnectedPointList(), KKB::Raster::DrawDot(), KKB::Raster::DrawFatLine(), KKB::Raster::DrawLine(), KKB::Raster::DrawPointList(), KKB::ContourFollower::HistogramDistanceFromAPointOfEdge(), KKB::operator<<(), KKB::Raster::RotateDerivePreRotatedPoint(), KKB::Raster::SetPixelValue(), KKB::Raster::ThinContour(), and KKB::PointList::ToDelStr().
{return row;}
void KKB::Point::Row (kkint32 _row) [inline]
Definition at line 42 of file Point.h.
{row = _row;}
Point KKB::Point::UpOne () const [inline]
Definition at line 45 of file Point.h.
References Point().
{return Point (row - 1, col);}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Point.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Point.cpp