KKMLL::XmlElementMLClassNameList Class Reference
Will only write the ClassName rather than complete MLClass instances.
#include <MLClass.h>
Public Member Functions
XmlElementMLClassNameList (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
virtual ~XmlElementMLClassNameList ()
MLClassListPtr TakeOwnership ()
MLClassListPtr Value () const
Static Public Member Functions
static void WriteXML (const MLClassList &mlClassList, const KKStr &varName, std::ostream &o)
Additional Inherited Members
Detailed Description
Will only write the ClassName rather than complete MLClass instances.
Definition at line 580 of file MLClass.h.
Constructor & Destructor Documentation
XmlElementMLClassNameList::XmlElementMLClassNameList (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log)
Definition at line 1438 of file MLClass.cpp.
References KKB::KKStr::Concat(), KKB::XmlContent::Content(), KKMLL::MLClass::CreateNewMLClass(), KKB::KKStr::Empty(), KKB::KKStrParser::GetNextToken(), KKB::XmlStream::GetNextToken(), KKB::KKStrParser::KKStrParser(), KKMLL::MLClassList::MLClassList(), KKB::KKStrParser::MoreTokens(), KKMLL::MLClassList::PushOnBack(), KKB::KKStrParser::TrimWhiteSpace(), and KKB::XmlElement::XmlElement().
                                                      :
    XmlElement (tag, s, log),
    value (NULL)
{
  value = new MLClassList ();
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (typeid (*t) == typeid(XmlContent))
    {
      XmlContentPtr contentToken = dynamic_cast<XmlContentPtr> (t);
      KKStrConstPtr s = contentToken->Content ();
      if (s)
      {
        KKStrParser p (*s);
        p.TrimWhiteSpace (" ");
        while (p.MoreTokens ())
        {
          KKStr className = p.GetNextToken (",\t");
          if (!className.Empty ())
            value->PushOnBack (MLClass::CreateNewMLClass (className));
        }
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
}
XmlElementMLClassNameList::~XmlElementMLClassNameList () [virtual]
Definition at line 1476 of file MLClass.cpp.
{
  delete value;
  value = NULL;
}
Member Function Documentation
MLClassListPtr XmlElementMLClassNameList::TakeOwnership ()
Definition at line 1491 of file MLClass.cpp.
Referenced by KKMLL::TrainingProcess2::ReadXML(), KKMLL::TrainingConfiguration2::ReadXMLBaseToken(), and KKMLL::Model::ReadXMLModelToken().
{
  MLClassListPtr v = value;
  value = NULL;
  return v;
}
MLClassListPtr XmlElementMLClassNameList::Value () const
Definition at line 1484 of file MLClass.cpp.
Referenced by KKMLL::FileDesc::ReadXML().
{
  return value;
}
void XmlElementMLClassNameList::WriteXML (const MLClassList & mlClassList, const KKStr & varName, std::ostream & o) [static]
Definition at line 1499 of file MLClass.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKMLL::MLClassList::ToCommaDelimitedQuotedStr(), KKB::XmlTag::WriteXML(), KKB::XmlContent::WriteXml(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::Model::WriteModelXMLFields(), KKMLL::TrainingProcess2::WriteXML(), and KKMLL::TrainingConfiguration2::WriteXMLFields().
{
  XmlTag startTag ("MLClassNameList", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  XmlContent::WriteXml (mlClassList.ToCommaDelimitedQuotedStr (), o);
  XmlTag endTag ("MLClassNameList", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.cpp