KKMLL::GrayScaleImagesFVList::const_iterator Class Reference
#include <GrayScaleImagesFV.h>
Public Member Functions
const_iterator ()
const_iterator (const const_iterator &ivConst_Iterator)
const_iterator (const FeatureVectorList::const_iterator &fvConst_Iterator)
const_iterator (const FeatureVectorList::iterator &fvIterator)
bool operator!= (const const_iterator &right) const
bool operator!= (const FeatureVectorList::iterator &right) const
bool operator!= (const FeatureVectorList::const_iterator &right) const
const GrayScaleImagesFVPtr operator* ()
const_iterator & operator++ (int x)
const_iterator & operator= (const const_iterator &right)
const_iterator & operator= (const FeatureVectorList::iterator &right)
const_iterator & operator= (const FeatureVectorList::const_iterator &right)
bool operator== (const const_iterator &right) const
bool operator== (const FeatureVectorList::iterator &right) const
Detailed Description
Definition at line 296 of file GrayScaleImagesFV.h.
Constructor & Destructor Documentation
KKMLL::GrayScaleImagesFVList::const_iterator::const_iterator () [inline]
Definition at line 302 of file GrayScaleImagesFV.h.
References const_iterator().
Referenced by const_iterator().
                       :
          idx ()
      {
      }
KKMLL::GrayScaleImagesFVList::const_iterator::const_iterator (const const_iterator & ivConst_Iterator) [inline]
Definition at line 308 of file GrayScaleImagesFV.h.
References const_iterator().
Referenced by const_iterator().
                                                              :
          idx (ivConst_Iterator.idx)
      {
      }
KKMLL::GrayScaleImagesFVList::const_iterator::const_iterator (const FeatureVectorList::const_iterator & fvConst_Iterator) [inline]
Definition at line 314 of file GrayScaleImagesFV.h.
References operator==().
                                                                               :
          idx (fvConst_Iterator)
      {
      }
KKMLL::GrayScaleImagesFVList::const_iterator::const_iterator (const FeatureVectorList::iterator & fvIterator) [inline]
Definition at line 320 of file GrayScaleImagesFV.h.
References operator==().
                                                                   :
          idx (fvIterator)
      {
      }
Member Function Documentation
bool KKMLL::GrayScaleImagesFVList::const_iterator::operator!= (const const_iterator & right) const [inline]
Definition at line 354 of file GrayScaleImagesFV.h.
      {
        return idx != right.idx;
      }
bool KKMLL::GrayScaleImagesFVList::const_iterator::operator!= (const FeatureVectorList::iterator & right) const [inline]
Definition at line 360 of file GrayScaleImagesFV.h.
References operator==().
      {
        return idx != (FeatureVectorList::const_iterator)right;
      }
bool KKMLL::GrayScaleImagesFVList::const_iterator::operator!= (const FeatureVectorList::const_iterator & right) const [inline]
Definition at line 366 of file GrayScaleImagesFV.h.
References operator==().
      {
        return idx != right;
      }
const GrayScaleImagesFVPtr KKMLL::GrayScaleImagesFVList::const_iterator::operator* () [inline]
Definition at line 326 of file GrayScaleImagesFV.h.
Referenced by KKMLL::GrayScaleImagesFVList::GrayScaleImagesFVList().
      {
        return (const GrayScaleImagesFVPtr)*idx;
      }
const_iterator& KKMLL::GrayScaleImagesFVList::const_iterator::operator++ (int x) [inline]
Definition at line 384 of file GrayScaleImagesFV.h.
Referenced by KKMLL::GrayScaleImagesFVList::GrayScaleImagesFVList().
      {
        idx++;
        return *this;
      }
const_iterator& KKMLL::GrayScaleImagesFVList::const_iterator::operator= (const const_iterator & right) [inline]
Definition at line 332 of file GrayScaleImagesFV.h.
      {
        idx = right.idx;
        return *this;
      }
const_iterator& KKMLL::GrayScaleImagesFVList::const_iterator::operator= (const FeatureVectorList::iterator & right) [inline]
Definition at line 340 of file GrayScaleImagesFV.h.
References operator==().
      {
        idx = right;
        return *this;
      }
const_iterator& KKMLL::GrayScaleImagesFVList::const_iterator::operator= (const FeatureVectorList::const_iterator & right) [inline]
Definition at line 347 of file GrayScaleImagesFV.h.
References operator==().
      {
        idx = right;
        return *this;
      }
bool KKMLL::GrayScaleImagesFVList::const_iterator::operator== (const const_iterator & right) const [inline]
Definition at line 372 of file GrayScaleImagesFV.h.
      {
        return idx == right.idx;
      }
bool KKMLL::GrayScaleImagesFVList::const_iterator::operator== (const FeatureVectorList::iterator & right) const [inline]
Definition at line 378 of file GrayScaleImagesFV.h.
References operator==().
Referenced by const_iterator(), KKMLL::GrayScaleImagesFVList::GrayScaleImagesFVList(), operator!=(), operator=(), and operator==().
      {
        return (idx == right);
      }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFV.h