KKB::MorphOpStretcher Class Reference
#include <MorphOpStretcher.h>
Classes
class CellFactor
Public Member Functions
MorphOpStretcher (float _rowFactor, float _colFactor)
virtual ~MorphOpStretcher ()
float ColFactor () const
kkint32 MemoryConsumedEstimated ()
virtual OperationType Operation () const
virtual RasterPtr PerformOperation (RasterConstPtr _image)
float RowFactor () const
Additional Inherited Members
Detailed Description
Definition at line 26 of file MorphOpStretcher.h.
Constructor & Destructor Documentation
MorphOpStretcher::MorphOpStretcher (float _rowFactor, float _colFactor)
Definition at line 81 of file MorphOpStretcher.cpp.
References KKB::MorphOp::MorphOp().
Referenced by KKB::Raster::StreatchImage().
                                    :
    MorphOp (),
    rowFactor (_rowFactor),
    colFactor (_colFactor),
    rowFactorsCount (0),
    rowFactors (NULL),
    colFactorsCount (0),
    colFactors (NULL)
{
}
MorphOpStretcher::~MorphOpStretcher () [virtual]
Definition at line 96 of file MorphOpStretcher.cpp.
{
  delete[] rowFactors; rowFactors = NULL;
  delete[] colFactors; colFactors = NULL;
}
Member Function Documentation
float KKB::MorphOpStretcher::ColFactor () const [inline]
Definition at line 35 of file MorphOpStretcher.h.
{return colFactor;}
kkint32 MorphOpStretcher::MemoryConsumedEstimated ()
Definition at line 104 of file MorphOpStretcher.cpp.
{
  kkint32 result = sizeof (*this) +
         (kkint32)(rowFactorsCount * sizeof (CellFactor) * rowFactor) +
         (kkint32)(colFactorsCount * sizeof (CellFactor) * colFactor);
  return result;
}
virtual OperationType KKB::MorphOpStretcher::Operation () const [inline], [virtual]
Implements KKB::MorphOp.
Definition at line 38 of file MorphOpStretcher.h.
References KKB::MorphOp::Stretcher.
{return OperationType::Stretcher;}
RasterPtr MorphOpStretcher::PerformOperation (RasterConstPtr _image) [virtual]
Definition at line 114 of file MorphOpStretcher.cpp.
References KKB::Raster::BackgroundPixelTH(), KKB::Raster::BackgroundPixelValue(), KKB::Raster::Blue(), KKB::Raster::Color(), KKB::MorphOpStretcher::CellFactor::destCellCount, KKB::MorphOpStretcher::CellFactor::destCellFracts, KKB::MorphOpStretcher::CellFactor::destCellIdxs, KKB::Raster::ForegroundPixelValue(), KKB::Raster::Green(), KKB::Raster::Raster(), KKB::Raster::Red(), KKB::MorphOp::SetSrcRaster(), KKB::MorphOp::srcBlue, KKB::MorphOp::srcGreen, KKB::MorphOp::srcHeight, KKB::MorphOp::srcRed, and KKB::MorphOp::srcWidth.
Referenced by KKB::Raster::StreatchImage().
{
  this->SetSrcRaster (_image);
  kkuint32 destHeight = (kkuint32)ceil (0.5f + (float)srcHeight * rowFactor);
  kkuint32 destWidth = (kkuint32)ceil (0.5f + (float)srcWidth * colFactor);
  bool color = _image->Color ();
  UpdateFactors (srcHeight, srcWidth);
  RasterPtr result = new Raster (destHeight, destWidth, color);
  result->BackgroundPixelTH (_image->BackgroundPixelTH ());
  result->BackgroundPixelValue (_image->BackgroundPixelValue ());
  result->ForegroundPixelValue (_image->ForegroundPixelValue ());
  uchar** destRed = result->Red ();
  uchar** destGreen = result->Green ();
  uchar** destBlue = result->Blue ();
  for (kkint32 srcRow = 0; srcRow < srcHeight; ++srcRow)
  {
    uchar* srcRedRow = NULL;
    uchar* srcGreenRow = srcGreen[srcRow];
    uchar* srcBlueRow = NULL;
    if (color)
    {
      srcRedRow = srcRed [srcRow];
      srcBlueRow = srcBlue[srcRow];
    }
    CellFactor& rowFactor = rowFactors[srcRow];
    for (kkuint32 rowFactorIdx = 0; rowFactorIdx < rowFactor.destCellCount; ++rowFactorIdx)
    {
      kkuint32 destRow = rowFactor.destCellIdxs [rowFactorIdx];
      float destRowFract = rowFactor.destCellFracts[rowFactorIdx];
      for (kkint32 srcCol = 0; srcCol < srcWidth; ++srcCol)
      {
        uchar srcPixelRed = 0;
        uchar srcPixelGreen = srcGreenRow[srcCol];
        uchar srcPixelBlue = 0;
        if (color)
        {
          srcPixelRed = srcRedRow [srcCol];
          srcPixelBlue = srcBlueRow[srcCol];
        }
        CellFactor& colFactor = colFactors[srcCol];
        for (kkuint32 colFactorIdx = 0; colFactorIdx < colFactor.destCellCount; ++colFactorIdx)
        {
          kkuint32 destCol = colFactor.destCellIdxs [colFactorIdx];
          float destColFract = colFactor.destCellFracts[colFactorIdx];
          destGreen[destRow][destCol] += (uchar)Min (255.0f, srcPixelGreen * destRowFract *
      destColFract);
          if (color)
          {
            destRed [destRow][destCol] += (uchar)Min (255.0f, srcPixelRed * destRowFract *
      destColFract);
            destBlue[destRow][destCol] += (uchar)Min (255.0f, srcPixelBlue * destRowFract *
      destColFract);
          }
        }
      }
    }
  }
  return result;
} /* PerformOperation */
float KKB::MorphOpStretcher::RowFactor () const [inline]
Definition at line 36 of file MorphOpStretcher.h.
{return rowFactor;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpStretcher.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpStretcher.cpp