KKB::XmlAttribute Class Reference
#include <XmlStream.h>
Public Member Functions
XmlAttribute (const KKStr &_name, const KKStr &_value)
const KKStr & Name () const
const KKStr & Value () const
Detailed Description
Definition at line 112 of file XmlStream.h.
Constructor & Destructor Documentation
KKB::XmlAttribute::XmlAttribute (const KKStr & _name, const KKStr & _value) [inline]
Definition at line 115 of file XmlStream.h.
References KKB::KKStr::KKStr().
Referenced by KKB::XmlAttributeList::AddAttribute().
                  :
        name (_name),
        value (_value)
    {}
Member Function Documentation
const KKStr& KKB::XmlAttribute::Name () const [inline]
Definition at line 122 of file XmlStream.h.
Referenced by KKB::XmlTag::ToString().
{return name;}
const KKStr& KKB::XmlAttribute::Value () const [inline]
Definition at line 123 of file XmlStream.h.
Referenced by KKB::XmlAttributeList::AttributeValueByName(), and KKB::XmlTag::ToString().
{return value;}
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h