KKMLL::AttributeTypeVector Class Reference
#include <Attribute.h>
Public Member Functions
AttributeTypeVector ()
AttributeTypeVector (kkuint32 initialSize, AttributeType initialValue)
void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
void WriteXML (const KKStr &varName, std::ostream &o) const
Detailed Description
Definition at line 52 of file Attribute.h.
Constructor & Destructor Documentation
AttributeTypeVector::AttributeTypeVector ()
Definition at line 552 of file Attribute.cpp.
References AttributeTypeVector().
Referenced by AttributeTypeVector(), KKMLL::AttributeList::CreateAttributeTypeVector(), and KKMLL::SVMModel::SVMModel().
                                          :
   vector<AttributeType> ()
{
}
AttributeTypeVector::AttributeTypeVector (kkuint32 initialSize, AttributeType initialValue)
Definition at line 558 of file Attribute.cpp.
References AttributeTypeVector().
Referenced by AttributeTypeVector().
                                          :
   vector<AttributeType> (initialSize, initialValue)
{
}
Member Function Documentation
void AttributeTypeVector::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 599 of file Attribute.cpp.
References KKB::XmlTag::AttributeValueInt32(), KKB::KKStr::Concat(), KKB::XmlContent::Content(), KKB::KKStr::EqualIgnoreCase(), KKB::KKStrParser::GetNextToken(), KKB::XmlStream::GetNextToken(), KKB::KKStrParser::GetNextTokenInt(), KKB::KKStrParser::KKStrParser(), KKB::KKStrParser::MoreTokens(), KKB::KKStr::operator=(), and KKB::KKStrParser::TrimWhiteSpace().
{
  clear ();
  kkuint32 expectedLen = (kkuint32)tag->AttributeValueInt32 ("Size");
  AttributeTypeVector decodeTable;
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (typeid (*t) == typeid (XmlContent))
    {
      KKStrParser p (*(dynamic_cast<XmlContentPtr> (t)->Content ()));
      p.TrimWhiteSpace (" ");
      KKStr lineName =p.GetNextToken ();
      if (lineName.EqualIgnoreCase ("CodeTable"))
      {
        KKStr fieldName = p.GetNextToken ();
        while (p.MoreTokens ())
        {
          if (!fieldName.Empty ())
            decodeTable.push_back (AttributeTypeFromStr (fieldName));
          fieldName = p.GetNextToken ();
        }
      }
      else if (lineName.EqualIgnoreCase ("CodedAttributeValues"))
      {
        kkint32 x = p.GetNextTokenInt ();
        if ((x < 0) || (x >= (kkint32)decodeTable.size ()))
        {
          log.Level (-1) << endl << "AttributeTypeVector::ReadXML ***ERROR*** Invalid Code
       Value[" << x << "]" << endl << endl;
          push_back (AttributeType::NULLAttribute);
        }
        else
        {
          push_back ((AttributeType)x);
        }
        
      }
    }
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
}
void AttributeTypeVector::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 572 of file Attribute.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
{
  XmlTag tagStart ("AttributeTypeVector", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    tagStart.AddAtribute ("VarName", varName);
  tagStart.AddAtribute ("Size", (kkint32)size ());
  tagStart.WriteXML (o);
  o << endl;
  o << "CodeTable";
  for (AttributeType zed = AttributeType::NULLAttribute; zed <=
       AttributeType::Symbolic; ++zed)
    o << "\t" << AttributeTypeToStr (zed);
  o << endl;
  o << "CodedAttributeValues";
  for (auto idx: *this)
    o << "\t" << (int)idx;
  o << endl;
  XmlTag tagEnd ("AttributeTypeVector", XmlTag::TagTypes::tagEnd);
  tagEnd.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/Attribute.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/Attribute.cpp