KKB::Configuration::SettingList Class Reference
Public Member Functions
SettingList ()
SettingList (const SettingList &sl)
void AddSetting (SettingPtr setting)
void AddSetting (const KKStr &_name, const KKStr &_value, kkint32 _lineNum)
SettingPtr LookUp (const KKStr &name)
kkint32 LookUpLineNum (const KKStr &name) const
kkint32 MemoryConsumedEstimated () const
Additional Inherited Members
Detailed Description
Definition at line 63 of file Configuration.cpp.
Constructor & Destructor Documentation
KKB::Configuration::SettingList::SettingList () [inline]
Definition at line 66 of file Configuration.cpp.
: KKQueue<Setting> (true) {}
KKB::Configuration::SettingList::SettingList (const SettingList & sl) [inline]
Definition at line 68 of file Configuration.cpp.
References SettingList().
Referenced by SettingList().
                                         :
        KKQueue<Setting> (true)
    {
      kkuint32 x;
      for (x = 0; x < sl.size (); x++)
      {
        SettingPtr setting = sl.IdxToPtr (x);
        PushOnBack (new Configuration::Setting (*setting));
      }
    }
Member Function Documentation
void KKB::Configuration::SettingList::AddSetting (SettingPtr setting) [inline]
Definition at line 117 of file Configuration.cpp.
    {
      PushOnBack (setting);
    }
void KKB::Configuration::SettingList::AddSetting (const KKStr & _name, const KKStr & _value, kkint32 _lineNum) [inline]
Definition at line 123 of file Configuration.cpp.
    {
      PushOnBack (new Setting (_name, _value, _lineNum));
    }
SettingPtr KKB::Configuration::SettingList::LookUp (const KKStr & name) [inline]
Definition at line 89 of file Configuration.cpp.
References KKB::KKStr::EqualIgnoreCase(), and KKB::Configuration::Setting::Name().
    {
      kkint32 idx;
      kkint32 qSize = QueueSize ();
      for (idx = 0; idx < qSize; idx++)
      {
        SettingPtr setting = IdxToPtr (idx);
        if (name.EqualIgnoreCase (setting->Name ()))
          return setting;
      }
      return NULL;
    } /* LookUp */
kkint32 KKB::Configuration::SettingList::LookUpLineNum (const KKStr & name) const [inline]
Definition at line 104 of file Configuration.cpp.
References KKB::KKStr::EqualIgnoreCase(), KKB::Configuration::Setting::LineNum(), and KKB::Configuration::Setting::Name().
    {
      const_iterator idx;
      for (idx = begin (); idx != end (); idx++)
      {
        SettingPtr s = *idx;
        if (s->Name ()->EqualIgnoreCase (name))
          return s->LineNum ();
      }
      return -1;
    } /* LookUpLineNum */
kkint32 KKB::Configuration::SettingList::MemoryConsumedEstimated () const [inline]
Definition at line 79 of file Configuration.cpp.
    {
      kkint32 memoryConsumedEstimated = sizeof (SettingList);
      SettingList::const_iterator idx;
      for (idx = begin (); idx != end (); ++idx)
        memoryConsumedEstimated += (*idx)->MemoryConsumedEstimated ();
      return memoryConsumedEstimated;
    }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Configuration.cpp