KKJobManagment::KKJobList Class Reference
#include <KKJob.h>
Public Types
typedef KKJobList * KKJobListPtr
Public Member Functions
KKJobList (const KKJobList &jobs)
KKJobList (JobManagerPtr _manager)
KKJobList (JobManagerPtr _manager, KKStr _fileName)
bool AllPrequisitesDone (KKJobPtr job)
bool AreAllJobsDone ()
bool JobsStillRunning ()
KKJobPtr LocateOpenJob ()
RunLog & Log ()
KKJobPtr LookUpByJobId (kkint32 jobId)
void PushOnBack (KKJobPtr j)
Detailed Description
Definition at line 235 of file KKJob.h.
Member Typedef Documentation
typedef KKJobList* KKJobManagment::KKJobList::KKJobListPtr
Definition at line 238 of file KKJob.h.
Constructor & Destructor Documentation
KKJobList::KKJobList (const KKJobList & jobs)
Definition at line 370 of file KKJob.cpp.
References KKJobList().
Referenced by KKJobList(), and KKJobManagment::KKJobManager::KKJobManager().
                                           :
     KKQueue<KKJob> (jobs.Owner ()),
     jobIdLookUpTable (),
     jobIdLookUpTableIdx (),
     log (jobs.log),
     manager (jobs.manager)
  
{
  KKJobList::const_iterator idx;
  for (idx = jobs.begin (); idx != jobs.end (); idx++)
  {
    KKJobPtr j = *idx;
    if (Owner ())
      PushOnBack (j->Duplicate ());
    else
      PushOnBack (j);
  }
}
KKJobList::KKJobList (JobManagerPtr _manager)
Definition at line 359 of file KKJob.cpp.
References KKJobList(), and KKJobManagment::KKJob::Log().
Referenced by KKJobList(), and KKJobManagment::KKJobManager::Run().
                                            :
   KKQueue<KKJob> (true),
   log (_manager->Log ()),
   manager (_manager)
{
}
KKJobManagment::KKJobList::KKJobList (JobManagerPtr _manager, KKStr _fileName)
Member Function Documentation
bool KKJobList::AllPrequisitesDone (KKJobPtr job)
Definition at line 404 of file KKJob.cpp.
References KKJobManagment::KKJob::AddPrerequisites(), KKJobManagment::KKJob::jsDone, KKJobManagment::KKJob::jsExpanded, LookUpByJobId(), KKJobManagment::KKJob::Prerequisites(), and KKJobManagment::KKJob::Status().
{
  const VectorInt& p = job->Prerequisites ();
  for (kkuint32 z = 0; z < p.size (); ++z)
  {
    kkint32 jobId = p[z];
    KKJobPtr pj = LookUpByJobId (jobId);
    if ((pj->Status () != KKJob::jsDone) && (pj->Status () !=
      KKJob::jsExpanded))
      return false;
  }
  return true;
} /* AllPrequisitesDone */
bool KKJobList::AreAllJobsDone ()
Definition at line 436 of file KKJob.cpp.
References KKJobManagment::KKJob::AddPrerequisites(), KKJobManagment::KKJob::jsDone, KKJobManagment::KKJob::jsExpanded, and KKJobManagment::KKJob::Status().
Referenced by KKJobManagment::KKJobManager::AreAllJobsDone().
{
  kkint32 x;
  for (x = 0; x < QueueSize (); ++x)
  {
    KKJobPtr j = IdxToPtr (x);
    if ((j->Status () != KKJob::jsDone) && (j->Status () !=
      KKJob::jsExpanded))
      return false;
  }
  return true;
} /* AreAllJobsAreDone */
bool KKJobList::JobsStillRunning ()
Definition at line 482 of file KKJob.cpp.
References KKJobManagment::KKJob::AddPrerequisites(), KKJobManagment::KKJob::jsStarted, and KKJobManagment::KKJob::Status().
Referenced by KKJobManagment::KKJobManager::Run().
{
  KKJobList::iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    KKJobPtr j = *idx;
    if (j->Status () == KKJob::jsStarted)
      return true;
  }
  return false;
} /* JobsStillRunning */
KKJobPtr KKJobList::LocateOpenJob ()
Definition at line 420 of file KKJob.cpp.
References KKJobManagment::KKJob::AddPrerequisites(), KKJobManagment::KKJob::jsOpen, and KKJobManagment::KKJob::Status().
{
  kkint32 x;
  for (x = 0; x < QueueSize (); x++)
  {
    KKJobPtr j = IdxToPtr (x);
    if (j->Status () == KKJob::jsOpen)
      return j;
  }
  return NULL;
} /* LocateOpenJob */
RunLog& KKJobManagment::KKJobList::Log () [inline]
Definition at line 256 of file KKJob.h.
{return log;}
KKJobPtr KKJobList::LookUpByJobId (kkint32 jobId)
Definition at line 391 of file KKJob.cpp.
Referenced by AllPrequisitesDone(), KKJobManagment::KKJobManager::StatusFileProcessLine(), and KKJobManagment::KKJobManager::StatusFileProcessLineJobStatusChange().
{
  jobIdLookUpTableIdx = jobIdLookUpTable.find (jobId);
  if (jobIdLookUpTableIdx == jobIdLookUpTable.end ())
    return NULL;
  return jobIdLookUpTableIdx->second;
} /* LookUpByJobId */
void KKJobList::PushOnBack (KKJobPtr j)
Definition at line 456 of file KKJob.cpp.
Referenced by KKJobManagment::KKJobManager::Run(), and KKJobManagment::KKJobManager::StatusFileProcessLine().
{
  jobIdLookUpTableIdx = jobIdLookUpTable.find (j->JobId ());
  if (jobIdLookUpTableIdx != jobIdLookUpTable.end ())
  {
    log.Level (-1) << endl
                   << endl
                   << "KKJobList::PushOnBack ***ERROR***" << endl
                   << endl
                   << "KKJobList::PushOnBack Duplicate JobId[" << j->
      JobId () << "]" << endl
                   << endl;
    osWaitForEnter ();
    exit (-1);
  }
  KKQueue<KKJob>::PushOnBack (j);
  jobIdLookUpTable.insert (JobIdLookUpTablePair (j->JobId (), j));
  return;
} /* PushOnBack */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/JobManager/KKJob.h
C:/Users/Kurt/GitHub/KSquareLibraries/JobManager/KKJob.cpp