KKMLL::Classifier2List Class Reference
#include <Classifier2.h>
Public Member Functions
Classifier2List (bool _owner)
virtual ~Classifier2List ()
Classifier2Ptr LookUpByName (const KKStr &rootName) const
Additional Inherited Members
Detailed Description
Definition at line 291 of file Classifier2.h.
Constructor & Destructor Documentation
Classifier2List::Classifier2List (bool _owner)
Definition at line 789 of file Classifier2.cpp.
References Classifier2List().
Referenced by Classifier2List().
                                            :
    KKQueue<Classifier2> (_owner)
{
}
Classifier2List::~Classifier2List () [virtual]
Definition at line 796 of file Classifier2.cpp.
{
}
Member Function Documentation
Classifier2Ptr Classifier2List::LookUpByName (const KKStr & rootName) const
Definition at line 802 of file Classifier2.cpp.
References KKMLL::Classifier2::ConfigRootName(), and KKB::KKStr::EqualIgnoreCase().
{
  Classifier2List::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    Classifier2Ptr c = *idx;
    if (c->ConfigRootName ().EqualIgnoreCase (rootName))
      return c;
  }
  return NULL;
} /* LookUpByName */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/Classifier2.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/Classifier2.cpp