KKLSC::Variables Class Reference
Variables that specify where we can locate Camera Application directories and files.
#include <Variables.h>
Public Member Functions
Variables ()
~Variables ()
Static Public Member Functions
static KKStr ConfigurationDir ()
static KKStr HomeDir ()
static KKStr ScannerFilesDefaultDir ()
static void SetHomeDir (const KKStr &_homeDir)
static KKStr SubstituteInEnvironmentVariables (const KKStr &src)
Expands the supplied string by substituting in Environment variable values.
Detailed Description
Variables that specify where we can locate Camera Application directories and files.
All methods and applications are to use these variables to locate files and directories that they need. This way all the knowledge or where to locate things is kept in this one class.
Definition at line 21 of file Variables.h.
Constructor & Destructor Documentation
Variables::Variables ()
Definition at line 23 of file Variables.cpp.
{
}
Variables::~Variables ()
Definition at line 29 of file Variables.cpp.
{
}
Member Function Documentation
KKStr Variables::ConfigurationDir () [static]
Where application configuration files go; NOT training models.
Definition at line 71 of file Variables.cpp.
References KKB::KKStr::Concat(), HomeDir(), KKB::KKStr::operator+(), and KKB::osAddSlash().
{
  KKStr configDir = osAddSlash (osAddSlash (HomeDir ()) + "Configurations"
      );
  return configDir;
}
KKStr Variables::HomeDir () [static]
Home Directory. All other directories will be off this directory.
Definition at line 44 of file Variables.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), and KKB::osGetEnvVariable().
Referenced by ConfigurationDir(), ScannerFilesDefaultDir(), and SubstituteInEnvironmentVariables().
{
  if (!homeDir.Empty ())
    return homeDir;
  KKStrPtr homeDirEnvVar = osGetEnvVariable ("HomeDir");
  if (!homeDirEnvVar)
  {
    #ifdef WIN32
      return "C:\\Scs";
    #else
      return "~/Scs";
    #endif
  }
  else
  {
    KKStr tempHomeDir = *homeDirEnvVar;
    delete homeDirEnvVar;
    homeDirEnvVar = NULL;
    return tempHomeDir;
  }
    
  return homeDir;
} /* HomeDir */
KKStr Variables::ScannerFilesDefaultDir () [static]
Definition at line 80 of file Variables.cpp.
References KKB::KKStr::Concat(), HomeDir(), KKB::KKStr::operator+(), and KKB::osAddSlash().
{
  KKStr scsFilesDefaultDir = osAddSlash (HomeDir ()) + "ScannerFiles";
  return scsFilesDefaultDir;
}
void Variables::SetHomeDir (const KKStr & _homeDir) [static]
Definition at line 37 of file Variables.cpp.
References KKB::KKStr::operator=().
{
  homeDir = _homeDir;
}
KKStr Variables::SubstituteInEnvironmentVariables (const KKStr & src) [static]
Expands the supplied string by substituting in Environment variable values.
Similar to the 'osSubstituteInEvironmentVariables' method defined in 'osServices' except that if 'HomeDir' is not defined then the string 'c:\Temp' will be used. If a environment variable other than `HomeDir` is not defined then the original string will be returned. ex: '\TrainingLibraries\Shrimp9G' will expand to: 'SCS\TrainingLibraries\Shrimp9G'
Parameters
in src String that is to be search for environment variables and expanded.
Returns
returns the expanded string.
Definition at line 116 of file Variables.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EqualIgnoreCase(), HomeDir(), KKB::KKStr::KKStr(), KKB::KKStr::LocateCharacter(), KKB::KKStr::operator+(), KKB::KKStr::operator=(), KKB::KKStr::operator[](), KKB::osGetEnvVariable(), and KKB::KKStr::SubStrPart().
{
  kkint32 x = LocateEnvStrStart (src);
  if (x < 0)
    return src;
  char startChar = src[x + 1];
  char endChar = ')';
  if (startChar == '(')
    endChar = ')';
  else if (startChar == '{')
    endChar = '}';
  else if (startChar == '[')
    endChar = ']';
  KKStr str (src);
  while (x >= 0)
  {
    KKStr beforeEnvStr = str.SubStrPart (0, x - 1);
    str = str.SubStrPart (x + 2);
    x = str.LocateCharacter (endChar);
    if (x < 0)
      return src;
    KKStr envStrName = str.SubStrPart (0, x - 1);
    KKStr afterStrName = str.SubStrPart (x + 1);
    KKStrPtr envStrValue = osGetEnvVariable (envStrName);
    if (envStrValue == NULL)
    {
      if (envStrName.EqualIgnoreCase ("HomeDir"))
        envStrValue = new KKStr (Variables::HomeDir ());
    }
    if (envStrValue == NULL)
      return src;
    str = beforeEnvStr + (*envStrValue) + afterStrName;
    delete envStrValue;
    x = LocateEnvStrStart (str);
  }
  return str;
} /* SubstituteInEnvironmentVariables */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/Variables.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/Variables.cpp