KKMLL::ClassProbList Class Reference
#include <ClassProb.h>
Classes
class ProbabilityComparer
class VotesComparer
Public Types
typedef ClassProbList * ClassProbListPtr
Public Member Functions
ClassProbList ()
ClassProbList (bool owner)
ClassProbList (const ClassProbList &pairList)
void AddIn (const ClassProbListPtr otherPredictions)
Adds the contents of 'otherPredictions' to this list.
virtual void DeleteEntry (ClassProbPtr cp)
virtual void DeleteEntry (kkuint32 idx)
const ClassProbPtr LookUp (MLClassPtr targetClass) const
kkint32 LookUpPlace (MLClassPtr targetClass) const
Returns the position that 'targetClass' has in the order; good time to use would be after sorting by probability.
kkint32 MemoryConsumedEstimated () const
void MergeIn (const ClassProbPtr cp)
Adds the Prediction in 'cp' into this list.
void MergeIn (MLClassPtr target, double probability, float votes)
Adds the prediction of 'target' with 'probability' into this list.
void MergeIn (MLClassPtr target, const ClassProbListPtr subPredictions)
Merges in the predictions in 'subPredictions' by replacing the entry in our list with label 'target' with contents of 'subPredictions'.
void NormalizeToOne ()
Will normalize the list of predictions such that the total probability will equal 1.0 and total votes will = (N)(N-1)/2 where N = number of predictions.
virtual void PushOnBack (ClassProbPtr cp)
virtual void PushOnFront (ClassProbPtr cp)
void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
void SortByClassName ()
void SortByProbability (bool highToLow=true)
void SortByVotes (bool highToLow=true)
void WriteXML (const KKStr &varName, std::ostream &o) const
Static Public Member Functions
static ClassProbListPtr CreateFromXMLStream (std::istream &i)
Additional Inherited Members
Detailed Description
Definition at line 44 of file ClassProb.h.
Member Typedef Documentation
typedef ClassProbList* KKMLL::ClassProbList::ClassProbListPtr
Definition at line 47 of file ClassProb.h.
Constructor & Destructor Documentation
ClassProbList::ClassProbList ()
Definition at line 42 of file ClassProb.cpp.
References ClassProbList().
Referenced by ClassProbList(), KKMLL::ModelKnn::ProbabilitiesByClass(), KKMLL::ModelSvmBase::ProbabilitiesByClass(), and KKMLL::ModelOldSVM::ProbabilitiesByClass().
                             :
   KKQueue<ClassProb> (true)
{
}
ClassProbList::ClassProbList (bool owner)
Definition at line 48 of file ClassProb.cpp.
References ClassProbList().
Referenced by ClassProbList(), CreateFromXMLStream(), and KKMLL::FeatureVectorList::GetClassDistribution().
                                       :
   KKQueue<ClassProb> (owner)
{
}
ClassProbList::ClassProbList (const ClassProbList & pairList)
Definition at line 55 of file ClassProb.cpp.
References ClassProbList().
Referenced by ClassProbList(), and KKMLL::Model::ProbabilitiesByClassDual().
                                                           :
   KKQueue<ClassProb> (pairList.Owner ())
{
  for (auto idx: pairList)
  {
    if (Owner ())
      PushOnBack (new ClassProb (*idx));
    else
      PushOnBack (idx);
  }
}
Member Function Documentation
void ClassProbList::AddIn (const ClassProbListPtr otherPredictions)
Adds the contents of 'otherPredictions' to this list.
there os not assumption that this list or 'otherPredictions' sum up to `1.0`.
Definition at line 246 of file ClassProb.cpp.
References MergeIn().
Referenced by KKMLL::ModelDual::ProbabilitiesByClass().
{
  if (!otherPredictions)
    return;
  ClassProbList::const_iterator idx;
  for (idx = otherPredictions->begin (); idx != otherPredictions->end (); ++idx)
  {
    const ClassProbPtr otherPrediction = *idx;
    MergeIn (otherPrediction);
  }
} /* AddIn */
ClassProbListPtr ClassProbList::CreateFromXMLStream (std::istream & i) [static]
Definition at line 362 of file ClassProb.cpp.
References KKMLL::ClassProb::ClassProb(), ClassProbList(), KKB::KKStr::Concat(), KKMLL::MLClass::CreateNewMLClass(), KKB::KKStr::Empty(), KKB::KKStr::ExtractToken2(), KKB::KKStr::ExtractTokenDouble(), KKB::KKStr::operator=(), KKB::osReadRestOfLine2(), PushOnBack(), and KKB::KKStr::StartsWith().
{
  ClassProbListPtr result = new ClassProbList (true);
  bool eof = false;
  KKStr line = osReadRestOfLine2 (i, eof);
  while (!eof)
  {
    if (line.StartsWith ("</ClassProbList>"))
      break;
    if (line.StartsWith ("<ClassProbList"))
      continue;
    KKStr className = line.ExtractToken2 ("\n\r\t");
    double prob = line.ExtractTokenDouble ("\t\n\r");
    double votes = line.ExtractTokenDouble ("\t\n\r");
    if (!className.Empty ())
    {
      MLClassPtr c = MLClass::CreateNewMLClass (className, -1);
      result->PushOnBack (new ClassProb (c, prob, (float)votes));
    }
    line = osReadRestOfLine2 (i, eof);
  }
  return result;
} /* CreateFromXMLStream */
void ClassProbList::DeleteEntry (ClassProbPtr cp) [virtual]
Definition at line 187 of file ClassProb.cpp.
Referenced by MergeIn().
{
  MLClassIndexType::const_iterator idx;
  idx = classIndex.find (cp->classLabel);
  if (idx != classIndex.end ())
    classIndex.erase (idx);
  KKQueue<ClassProb>::DeleteEntry (cp);
}
void ClassProbList::DeleteEntry (kkuint32 idx) [virtual]
Definition at line 198 of file ClassProb.cpp.
{
  if (idx >= size ())
  {
    KKStr errMsg = "ClassProbList::DeleteEntry ***ERROR*** idx [" +
      StrFormatInt (idx, "#,###,##0") + "]";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  DeleteEntry (IdxToPtr (idx));
}
const ClassProbPtr ClassProbList::LookUp (MLClassPtr targetClass) const
Definition at line 160 of file ClassProb.cpp.
Referenced by MergeIn(), KKMLL::ModelDual::ProbabilitiesByClass(), and KKMLL::Classifier2::ProbabilitiesByClass().
{
  MLClassIndexType::const_iterator idx;
  idx = classIndex.find (targetClass);
  if (idx == classIndex.end ())
    return NULL;
  else
    return idx->second;
} /* LookUp */
kkint32 ClassProbList::LookUpPlace (MLClassPtr targetClass) const
Returns the position that 'targetClass' has in the order; good time to use would be after sorting by probability.
Definition at line 174 of file ClassProb.cpp.
{
  for (kkint32 x = 0; x < (kkint32)size (); ++x)
  {
    if (IdxToPtr (x)->classLabel == targetClass)
      return x;
  }
  return -1;
} /* LookUpPlace */
kkint32 ClassProbList::MemoryConsumedEstimated () const
Definition at line 68 of file ClassProb.cpp.
Referenced by KKMLL::TrainingProcess2::MemoryConsumedEstimated().
{
  return ((kkint32)size ()) * sizeof(ClassProb);
} /* MemoryConsumedEstimated */
void ClassProbList::MergeIn (const ClassProbPtr cp)
Adds the Prediction in 'cp' into this list.
If the class indicated by 'cp->classLabel' already exist in this list will then add to existing entry otherwise will create a new entry for the class.
Definition at line 268 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel, MergeIn(), KKMLL::ClassProb::probability, and KKMLL::ClassProb::votes.
Referenced by AddIn(), and KKMLL::ModelDual::ProbabilitiesByClass().
{
  MergeIn (cp->classLabel, cp->probability, cp->
      votes);
} /* MergeIn */
void ClassProbList::MergeIn (MLClassPtr target, double probability, float votes)
Adds the prediction of 'target' with 'probability' into this list.
If the class indicated by 'target' already exist in this list will then add to existing entry otherwise will create a new entry for the class.
Definition at line 276 of file ClassProb.cpp.
References KKMLL::ClassProb::ClassProb(), LookUp(), KKMLL::ClassProb::probability, PushOnBack(), and KKMLL::ClassProb::votes.
Referenced by MergeIn().
{
  ClassProbPtr existingEntry = LookUp (target);
  if (existingEntry)
  {
    existingEntry->probability += probability;
    existingEntry->votes += votes;
  }
  else
  {
    PushOnBack (new ClassProb (target, probability, votes));
  }
} /* MergeIn */
void ClassProbList::MergeIn (MLClassPtr target, const ClassProbListPtr subPredictions)
Merges in the predictions in 'subPredictions' by replacing the entry in our list with label 'target' with contents of 'subPredictions'.
It is assumed that the sum of probabilities of 'subPredictions' is equal to 1.0.
Definition at line 301 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel, DeleteEntry(), LookUp(), MergeIn(), KKMLL::ClassProb::probability, and KKMLL::ClassProb::votes.
{
  ClassProbPtr existingEntry = LookUp (target);
  if (existingEntry)
  {
    DeleteEntry (existingEntry);
    float totalSubVotes = (float)(subPredictions->size () - 1);
    double baseProb = existingEntry->probability;
    float baseVotes = existingEntry->votes;
    ClassProbList::const_iterator idx;
    for (idx = subPredictions->begin (); idx != subPredictions->end (); ++idx)
    {
      const ClassProbPtr subPrediction = *idx;
      double subProbability = baseProb * subPrediction->probability;
      float subVotes = baseVotes * (subPrediction->votes / totalSubVotes);
      MergeIn (subPrediction->classLabel, subProbability, subVotes);
    }
  }
  else
  {
  ClassProbList::const_iterator idx;
    for (idx = subPredictions->begin (); idx != subPredictions->end (); ++idx)
    {
      const ClassProbPtr subPrediction = *idx;
      MergeIn (subPrediction->classLabel, subPrediction->
      probability, subPrediction->votes);
    }
  }
} /* MergeIn */
void ClassProbList::NormalizeToOne ()
Will normalize the list of predictions such that the total probability will equal 1.0 and total votes will = (N)(N-1)/2 where N = number of predictions.
Definition at line 336 of file ClassProb.cpp.
References KKMLL::ClassProb::probability, and KKMLL::ClassProb::votes.
Referenced by KKMLL::ModelDual::ProbabilitiesByClass().
{
  double totalProb = 0.0;
  float totalVotes = 0.0f;
  float expectedTotalNumOfVotes = (float)(size () * (size () - 1) / 2);
  iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    ClassProbPtr cp = *idx;
    totalProb += cp->probability;
    totalVotes += cp->votes;
  }
  for (idx = begin (); idx != end (); ++idx)
  {
    ClassProbPtr cp = *idx;
    cp->probability = cp->probability / totalProb;
    cp->votes = (cp->votes / totalVotes) * expectedTotalNumOfVotes;
  }
} /* NormalizeToOne */
void ClassProbList::PushOnBack (ClassProbPtr cp) [virtual]
Definition at line 212 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel, KKB::KKStr::Concat(), KKB::KKException::KKException(), KKMLL::MLClass::Name(), KKB::KKStr::operator+(), and KKB::operator+().
Referenced by CreateFromXMLStream(), KKMLL::FeatureVectorList::GetClassDistribution(), MergeIn(), KKMLL::ModelKnn::ProbabilitiesByClass(), KKMLL::ModelSvmBase::ProbabilitiesByClass(), KKMLL::ModelOldSVM::ProbabilitiesByClass(), and ReadXML().
{
  try
  {
    classIndex.insert (MLClassIndexPair (cp->classLabel, cp));
  }
  catch (const std::exception&)
  {
    KKStr errMsg = "ClassProbList::PushOnBack ***ERROR*** Exception occurred adding Class[" + cp->
      classLabel->Name () + "]";
    cerr << errMsg << endl;
    throw KKException (errMsg);
  }
  KKQueue<ClassProb>::PushOnBack (cp);
}
void ClassProbList::PushOnFront (ClassProbPtr cp) [virtual]
Definition at line 229 of file ClassProb.cpp.
References KKMLL::ClassProb::classLabel, KKB::KKStr::Concat(), KKB::KKException::KKException(), KKMLL::MLClass::Name(), KKB::KKStr::operator+(), and KKB::operator+().
{
  try
  {
    classIndex.insert (MLClassIndexPair (cp->classLabel, cp));
  }
  catch (const std::exception&)
  {
    KKStr errMsg = "ClassProbList::PushOnFront ***ERROR*** Exception occurred adding Class[" + cp->
      classLabel->Name () + "]";
    cerr << errMsg << endl;
    throw KKException (errMsg);
  }
  KKQueue<ClassProb>::PushOnFront (cp);
}
void ClassProbList::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 423 of file ClassProb.cpp.
References KKMLL::ClassProb::ClassProb(), KKB::KKStr::Concat(), KKB::XmlContent::Content(), KKMLL::MLClass::CreateNewMLClass(), KKB::KKStr::Empty(), KKB::KKStrParser::GetNextToken(), KKB::XmlStream::GetNextToken(), KKB::KKStrParser::GetNextTokenDouble(), KKB::KKStrParser::GetNextTokenFloat(), KKB::KKStrParser::KKStrParser(), PushOnBack(), and KKB::KKStrParser::TrimWhiteSpace().
{
  XmlTokenPtr t = NULL;
  while (true && (!cancelFlag))
  {
    delete t;
    t = s.GetNextToken (cancelFlag, log);
    if (!t) break;
    if (typeid (*t) != typeid (XmlContent))
      continue;
    XmlContentPtr content = dynamic_cast<XmlContentPtr> (t);
    if ((content == NULL) || (content->Content () == NULL) || (content->
      Content ()->Empty ()))
      continue;
    KKStrParser p (*(content->Content ()));
    p.TrimWhiteSpace (" ");
    KKStr className = p.GetNextToken ("\t");
    double probability = p.GetNextTokenDouble ("\t");
    float votes = p.GetNextTokenFloat ("\t");
    if (className.Empty ())
      continue;
    if ((probability < 0.0f) || (probability > 1.0f))
    {
      log.Level (-1)
        << "ClassProbList::ReadXML ***ERROR*** Probability: " << probability << " is out of range for
       Class: " << className << endl
        << endl;
    }
    PushOnBack (new ClassProb (MLClass::CreateNewMLClass (
      className), probability, votes));
  }
  delete t;
  t = NULL;
} /* ReadXML */
void ClassProbList::SortByClassName ()
Definition at line 84 of file ClassProb.cpp.
{
  sort (begin (), end (), CompairByClassName);
}
void ClassProbList::SortByProbability (bool highToLow = true)
Definition at line 143 of file ClassProb.cpp.
References KKMLL::ClassProbList::ProbabilityComparer::ProbabilityComparer().
Referenced by KKMLL::ModelUsfCasCor::ProbabilitiesByClass(), and KKMLL::ModelOldSVM::ProbabilitiesByClass().
{
  ProbabilityComparer comparator (highToLow);
  sort (begin (), end (), comparator);
} /* SortByProbability */
void ClassProbList::SortByVotes (bool highToLow = true)
Definition at line 151 of file ClassProb.cpp.
References KKMLL::ClassProbList::VotesComparer::VotesComparer().
Referenced by KKMLL::ModelSvmBase::ProbabilitiesByClass(), and KKMLL::ModelOldSVM::ProbabilitiesByClass().
{
  VotesComparer comparator (highToLow);
  sort (begin (), end (), comparator);
} /* SortByVotes */
void ClassProbList::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 400 of file ClassProb.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::TrainingProcess2::WriteXML().
{
  XmlTag startTag ("ClassProbList", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  for (auto idx: *this)
  {
    ClassProbPtr cp = idx;
    o << cp->classLabel->Name () << "\t" << cp->probability << "\t" << cp->
      votes << endl;
  }
  
  XmlTag endTag ("ClassProbList", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ClassProb.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ClassProb.cpp