SVM233::SVR_Q Class Reference
Public Member Functions
SVR_Q (const svm_problem &prob, const svm_parameter &param)
~SVR_Q ()
Qfloat * get_Q (kkint32 i, kkint32 len) const
void swap_index (kkint32 i, kkint32 j) const
Additional Inherited Members
Detailed Description
Definition at line 2738 of file svm.cpp.
Constructor & Destructor Documentation
SVM233::SVR_Q::SVR_Q (const svm_problem & prob, const svm_parameter & param) [inline]
Definition at line 2741 of file svm.cpp.
References SVM233::Cache::Cache(), SVM233::svm_parameter::cache_size, SVM233::Kernel::Kernel(), SVM233::svm_problem::l, and SVM233::svm_problem::x.
Referenced by SVM233::solve_epsilon_svr(), and SVM233::solve_nu_svr().
    :Kernel (prob.l, prob.x, param)
  {
    l = prob.l;
    cache = new Cache(l,(kkint32)(param.cache_size*(1<<20)));
    sign = new schar[2*l];
    index = new kkint32[2*l];
    for(kkint32 k=0;k<l;k++)
    {
      sign[k] = 1;
      sign[k+l] = -1;
      index[k] = k;
      index[k+l] = k;
    }
    buffer[0] = new Qfloat[2*l];
    buffer[1] = new Qfloat[2*l];
    next_buffer = 0;
  }
SVM233::SVR_Q::~SVR_Q () [inline]
Definition at line 2788 of file svm.cpp.
  {
    delete cache;
    delete[] sign;
    delete[] index;
    delete[] buffer[0];
    delete[] buffer[1];
  }
Member Function Documentation
Qfloat* SVM233::SVR_Q::get_Q (kkint32 i, kkint32 len) const [inline], [virtual]
Implements SVM233::Kernel.
Definition at line 2769 of file svm.cpp.
References SVM233::Cache::get_data(), and SVM233::Kernel::kernel_function.
  {
    Qfloat *data;
    kkint32 real_i = index[i];
    if(cache->get_data(real_i,&data,l) < l)
    {
      for(kkint32 j=0;j<l;j++)
        data[j] = (Qfloat)(this->*kernel_function)(real_i,j);
    }
    // reorder and copy
    Qfloat *buf = buffer[next_buffer];
    next_buffer = 1 - next_buffer;
    schar si = sign[i];
    for(kkint32 j=0;j<len;j++)
      buf[j] = si * sign[j] * data[index[j]];
    return buf;
  }
void SVM233::SVR_Q::swap_index (kkint32 i, kkint32 j) const [inline], [virtual]
Reimplemented from SVM233::Kernel.
Definition at line 2762 of file svm.cpp.
  {
    Swap(sign[i],sign[j]);
    Swap(index[i],index[j]);
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm.cpp