KKMLL::FileDescList Class Reference
Container class file 'FileDesc' instances.
Public Member Functions
FileDescList (bool _owner)
~FileDescList ()
Additional Inherited Members
Detailed Description
Container class file 'FileDesc' instances.
The class definition is not in the header file because there is no reason for any other entity other than FileDesc to access a list of FileDesc instances.
Definition at line 42 of file FileDesc.cpp.
Constructor & Destructor Documentation
FileDescList::FileDescList (bool _owner)
Definition at line 911 of file FileDesc.cpp.
References FileDescList().
Referenced by FileDescList(), and KKMLL::FileDesc::GetExistingFileDesc().
                                       :
  KKQueue<FileDesc> (_owner)
{
}
FileDescList::~FileDescList ()
Definition at line 918 of file FileDesc.cpp.
{
}
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FileDesc.cpp