KKB::HTMLReport Class Reference
#include <HTMLReport.h>
Public Types
enum AlignmentType { AlignmentType::Left,
AlignmentType::Center,
AlignmentType::Right
 }
typedef HTMLReport * HTMLReportPtr
Public Member Functions
HTMLReport (KKStr _fileName, KKStr _title, AlignmentType _alignment)
~HTMLReport ()
void Append (const char *str)
void Close ()
ostream & OStream ()
Friends
HTMLReport & endl (HTMLReport &_outs)
HTMLReport & operator<< (HTMLReport &htmlReport, kkint32 right)
HTMLReport & operator<< (HTMLReport &htmlReport, kkuint32 right)
HTMLReport & operator<< (HTMLReport &htmlReport, kkint64 right)
HTMLReport & operator<< (HTMLReport &htmlReport, kkuint64 right)
HTMLReport & operator<< (HTMLReport &htmlReport, double right)
HTMLReport & operator<< (HTMLReport &htmlReport, char right)
HTMLReport & operator<< (HTMLReport &htmlReport, const char *right)
HTMLReport & operator<< (HTMLReport &htmlReport, const KKStr &right)
HTMLReport & operator<< (HTMLReport &htmlReport, KKStrConstPtr right)
HTMLReport & operator<< (HTMLReport &htmlReport, const DateTime &dateTime)
Detailed Description
Definition at line 17 of file HTMLReport.h.
Member Typedef Documentation
typedef HTMLReport* KKB::HTMLReport::HTMLReportPtr
Definition at line 20 of file HTMLReport.h.
Member Enumeration Documentation
enum KKB::HTMLReport::AlignmentType [strong]
Enumerator
Left
Center
Right
Definition at line 21 of file HTMLReport.h.
{Left, Center, Right};
Constructor & Destructor Documentation
HTMLReport::HTMLReport (KKStr _fileName, KKStr _title, AlignmentType _alignment)
Definition at line 35 of file HTMLReport.cpp.
References HTMLReport(), and KKB::KKStr::KKStr().
Referenced by HTMLReport().
                        :
  curAlignment (_alignment),
  fileName (_fileName),
  opened (false),
  r (),
  title (_title)
{
  r.open (fileName.Str (), std::ios_base::out);
  opened = true;
  r << "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">" <<
      std::endl
    << "<html xmlns=\"http://www.w3.org/1999/xhtml\">" <<
      std::endl
    << "<head>" <<
      std::endl
    << "<title>" << title << "</title>" <<
      std::endl
    << "</head>" <<
      std::endl
    << "<body " << CurStyleStr () << ">" <<
      std::endl;
}
HTMLReport::~HTMLReport (void)
Definition at line 80 of file HTMLReport.cpp.
References Close().
{
  if (opened)
    Close ();
}
Member Function Documentation
void HTMLReport::Append (const char * str)
Definition at line 88 of file HTMLReport.cpp.
Referenced by KKB::endl(), and KKB::operator<<().
{
  r << str;
}
void HTMLReport::Close ()
Definition at line 95 of file HTMLReport.cpp.
Referenced by ~HTMLReport().
{
  if (opened)
  {
    r.close ();
    opened = false;
  }
}
ostream& KKB::HTMLReport::OStream () [inline]
Definition at line 34 of file HTMLReport.h.
{return r;}
Friends And Related Function Documentation
HTMLReport& endl (HTMLReport & _outs) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, kkint32 right) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, kkuint32 right) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, kkint64 right) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, kkuint64 right) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, double right) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, char right) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, const char * right) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, const KKStr & right) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, KKStrConstPtr right) [friend]
HTMLReport& operator<< (HTMLReport & htmlReport, const DateTime & dateTime) [friend]
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/HTMLReport.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/HTMLReport.cpp