KKMLL::ModelParamOldSVM Class Reference
#include <ModelParamOldSVM.h>
Public Types
typedef ModelParamOldSVM * ModelParamOldSVMPtr
typedef SVM233::svm_parameter svm_parameter
Public Member Functions
ModelParamOldSVM ()
ModelParamOldSVM (const ModelParamOldSVM &_param)
virtual ~ModelParamOldSVM ()
virtual float A_Param () const
virtual void A_Param (float _A)
void AddBinaryClassParms (BinaryClassParmsPtr binaryClassParms)
void AddBinaryClassParms (MLClassPtr class1, MLClassPtr class2, const svm_parameter &_param, FeatureNumListConstPtr _selectedFeatures, float _weight)
Add a Binary parameters using svm_parametr cmd line str. Typically used by TrainingConfiguration.
virtual float AvgMumOfFeatures (FileDescPtr fileDesc)
const BinaryClassParmsListPtr BinaryParmsList () const
virtual double C_Param () const
virtual double C_Param (MLClassPtr class1, MLClassPtr class2) const
virtual void C_Param (double _CC)
virtual void C_Param (MLClassPtr class1, MLClassPtr class2, double cParam)
virtual ModelParamOldSVMPtr Duplicate () const
virtual void EncodingMethod (SVM_EncodingMethod _encodingMethod)
virtual void EncodingMethod (EncodingMethodType _encodingMethod)
virtual double Gamma () const
virtual void Gamma (double _gamma)
virtual void Gamma_Param (double _gamma)
BinaryClassParmsPtr GetBinaryClassParms (MLClassPtr class1, MLClassPtr class2) const
FeatureNumListConstPtr GetFeatureNums (FileDescPtr fileDesc, MLClassPtr class1, MLClassPtr class2) const
BinaryClassParmsPtr GetParamtersToUseFor2ClassCombo (MLClassPtr class1, MLClassPtr class2)
virtual SVM_KernalType KernalType () const
virtual void KernalType (SVM_KernalType _kernalType)
virtual SVM_MachineType MachineType () const
virtual void MachineType (SVM_MachineType _machineType)
virtual ModelParamTypes ModelParamType () const
virtual kkint32 NumOfFeaturesAfterEncoding (FileDescPtr fileDesc, RunLog &log) const
virtual const svm_parameter & Param () const
void ParseCmdLine (KKStr _cmdLineStr, bool &_validFormat, RunLog &_log)
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
virtual float SamplingRate () const
virtual void SamplingRate (float _samplingRate)
virtual FeatureNumListConstPtr SelectedFeatures () const
virtual void SelectedFeatures (const FeatureNumList &_selectedFeatures)
virtual SVM_SelectionMethod SelectionMethod () const
virtual void SelectionMethod (SVM_SelectionMethod _selectionMethod)
void SetBinaryClassFields (MLClassPtr class1, MLClassPtr class2, const svm_parameter &_param, FeatureNumListConstPtr _features, float _weight)
void SetFeatureNums (MLClassPtr class1, MLClassPtr class2, FeatureNumListConstPtr _features, float _weight=-1)
EncodingMethodType SVM_EncodingMethodToModelParamEncodingMethodType (SVM_EncodingMethod _encodingMethod)
converts Encoding variables from `SVM_EncodingMethod` to `ModelParam::EncodingMethodType`
virtual SVMparamPtr SvmParameters () const
KKStr SvmParamToString (const svm_parameter &_param) const
Convert a svm_parameter struct to a cmdline str.
KKStr ToCmdLineStr () const
Convert all parameters to a command line string.
virtual bool UseProbabilityToBreakTies () const
virtual void WriteXML (const KKStr &varName, std::ostream &o) const
Additional Inherited Members
Detailed Description
this class encapsulates are the information necessary to build a SVMModel class. *
See also
ModelSVM
SVM233
BinaryClassParms
Definition at line 36 of file ModelParamOldSVM.h.
Member Typedef Documentation
typedef ModelParamOldSVM* KKMLL::ModelParamOldSVM::ModelParamOldSVMPtr
Definition at line 39 of file ModelParamOldSVM.h.
typedef SVM233::svm_parameter KKMLL::ModelParamOldSVM::svm_parameter
Definition at line 40 of file ModelParamOldSVM.h.
Constructor & Destructor Documentation
ModelParamOldSVM::ModelParamOldSVM ()
Definition at line 27 of file ModelParamOldSVM.cpp.
References KKMLL::ModelParam::ModelParam(), and KKMLL::SVMparam::SVMparam().
Referenced by KKMLL::TrainingConfiguration2::BuildTrainingClassListFromDirectoryStructure(), and KKMLL::ModelOldSVM::ModelOldSVM().
                                    :
  ModelParam (),
  svmParameters (NULL)
{
  svmParameters = new SVMparam ();
}
ModelParamOldSVM::ModelParamOldSVM (const ModelParamOldSVM & _param)
Definition at line 37 of file ModelParamOldSVM.cpp.
References KKMLL::ModelParam::ModelParam(), and KKMLL::SVMparam::SVMparam().
Referenced by Duplicate().
                                                                   :
  ModelParam (_param),
  svmParameters (NULL)
{
  if (_param.svmParameters)
    svmParameters = new SVMparam (*_param.svmParameters);
}
ModelParamOldSVM::~ModelParamOldSVM () [virtual]
Definition at line 48 of file ModelParamOldSVM.cpp.
{
  delete svmParameters;
  svmParameters = NULL;
}
Member Function Documentation
float ModelParamOldSVM::A_Param () const [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 231 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::A_Param().
{
  return svmParameters->A_Param ();
}
void ModelParamOldSVM::A_Param (float _A) [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 62 of file ModelParamOldSVM.cpp.
References KKMLL::ModelParam::A_Param(), and KKMLL::SVMparam::A_Param().
{
  ModelParam::A_Param (_A);
  svmParameters->A_Param (_A);
}
void ModelParamOldSVM::AddBinaryClassParms (BinaryClassParmsPtr binaryClassParms)
Definition at line 452 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::AddBinaryClassParms().
{
  svmParameters->AddBinaryClassParms (binaryClassParms);
} /* AddBinaryClassParms */
void ModelParamOldSVM::AddBinaryClassParms (MLClassPtr class1, MLClassPtr class2, const svm_parameter & _param, FeatureNumListConstPtr _selectedFeatures, float _weight)
Add a Binary parameters using svm_parametr cmd line str. Typically used by TrainingConfiguration.
Definition at line 500 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::AddBinaryClassParms().
Referenced by C_Param().
{
  svmParameters->AddBinaryClassParms (class1, class2, _param, _selectedFeatures, _weight
      );
} /* AddBinaryClassParms */
float ModelParamOldSVM::AvgMumOfFeatures (FileDescPtr fileDesc) [virtual]
Definition at line 460 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::AvgMumOfFeatures().
{
  return svmParameters->AvgMumOfFeatures (fileDesc);
} /* AvgMumOfFeatures */
const BinaryClassParmsListPtr ModelParamOldSVM::BinaryParmsList () const
Definition at line 70 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::BinaryParmsList().
Referenced by C_Param().
{
  return svmParameters->BinaryParmsList ();
}
double ModelParamOldSVM::C_Param () const [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 238 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::C_Param().
Referenced by C_Param().
{
  return svmParameters->C_Param ();
}
double ModelParamOldSVM::C_Param (MLClassPtr class1, MLClassPtr class2) const [virtual]
Definition at line 114 of file ModelParamOldSVM.cpp.
References BinaryParmsList(), KKMLL::BinaryClassParms::C(), and KKMLL::BinaryClassParmsList::LookUp().
Referenced by KKMLL::TrainingConfiguration2::C_Param().
{
  if (!BinaryParmsList ())
  {
    cerr << endl << endl
      << "ModelParamOldSVM::C_Param ***ERROR*** 'binaryParmsList' is not defined." <<
      endl
      << endl;
    return 0.0;
  }
  BinaryClassParmsPtr binaryParms = BinaryParmsList ()->
      LookUp (class1, class2);
  if (!binaryParms)
  {
    cerr << endl << endl
      << "ModelParamOldSVM::C_Param ***ERROR*** No entry for Class[" << class1->Name () << ", " <<
      class2->Name () << "]" << endl
      << endl;
    return 0.0;
  }
  else
  {
    return binaryParms->C ();
  }
}
void ModelParamOldSVM::C_Param (double _CC) [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 76 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::C_Param(), and KKMLL::ModelParam::Cost().
{
  ModelParam::Cost (_CC);
  svmParameters->C_Param (_CC);
}
void ModelParamOldSVM::C_Param (MLClassPtr class1, MLClassPtr class2, double cParam) [virtual]
Definition at line 85 of file ModelParamOldSVM.cpp.
References AddBinaryClassParms(), BinaryParmsList(), SVM233::svm_parameter::C, KKMLL::BinaryClassParms::C(), C_Param(), KKMLL::BinaryClassParmsList::LookUp(), Param(), and SelectedFeatures().
Referenced by KKMLL::TrainingConfiguration2::C_Param().
{
  if (!this->BinaryParmsList ())
  {
    cerr << endl << endl
      << "ModelParamOldSVM::C_Param ***ERROR*** 'binaryParmsList' is not defined." <<
      endl
      << endl;
    return;
  }
  BinaryClassParmsPtr binaryParms = BinaryParmsList ()->
      LookUp (class1, class2);
  if (!binaryParms)
  {
    svm_parameter binaryParam = this->Param ();
    binaryParam.C = C_Param ();
    AddBinaryClassParms (class1, class2, binaryParam,
      SelectedFeatures (), 1.0f);
  }
  else
  {
    binaryParms->C (cParam);
  }
} /* C_Param */
ModelParamOldSVMPtr ModelParamOldSVM::Duplicate () const [virtual]
Implements KKMLL::ModelParam.
Definition at line 55 of file ModelParamOldSVM.cpp.
References ModelParamOldSVM().
{
  return new ModelParamOldSVM (*this);
}
void ModelParamOldSVM::EncodingMethod (SVM_EncodingMethod _encodingMethod) [virtual]
Definition at line 141 of file ModelParamOldSVM.cpp.
References KKMLL::ModelParam::EncodingMethod(), and KKMLL::SVMparam::EncodingMethod().
{
  svmParameters->EncodingMethod (_encodingMethod);
  ModelParam::EncodingMethod ((EncodingMethodType)
      _encodingMethod);
}
void ModelParamOldSVM::EncodingMethod (EncodingMethodType _encodingMethod) [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 149 of file ModelParamOldSVM.cpp.
References KKMLL::ModelParam::EncodingMethod(), and KKMLL::SVMparam::EncodingMethod().
{
  svmParameters->EncodingMethod ((SVM_EncodingMethod)_encodingMethod);
  ModelParam::EncodingMethod (_encodingMethod);
}
double ModelParamOldSVM::Gamma () const [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 245 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::Gamma().
{
  return svmParameters->Gamma ();
}
void ModelParamOldSVM::Gamma (double _gamma) [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 156 of file ModelParamOldSVM.cpp.
References KKMLL::ModelParam::Gamma(), and KKMLL::SVMparam::Gamma().
{
  ModelParam::Gamma (_gamma);
  svmParameters->Gamma (_gamma);
}
void ModelParamOldSVM::Gamma_Param (double _gamma) [virtual]
Definition at line 164 of file ModelParamOldSVM.cpp.
References KKMLL::ModelParam::Gamma(), and KKMLL::SVMparam::Gamma().
{
  ModelParam::Gamma (_gamma);
  svmParameters->Gamma (_gamma);
}
BinaryClassParmsPtr ModelParamOldSVM::GetBinaryClassParms (MLClassPtr class1, MLClassPtr class2) const
If no entry exists for class pair then NULL will be returned.
Definition at line 423 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::GetBinaryClassParms().
{
  return svmParameters->GetBinaryClassParms (class1, class2);
}
FeatureNumListConstPtr ModelParamOldSVM::GetFeatureNums (FileDescPtr fileDesc, MLClassPtr class1, MLClassPtr class2) const
Definition at line 441 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::GetFeatureNums().
Referenced by KKMLL::TrainingConfiguration2::GetFeatureNums().
{
  return svmParameters->GetFeatureNums (fileDesc, class1, class2);
} /* GetFeatureNums */
BinaryClassParmsPtr ModelParamOldSVM::GetParamtersToUseFor2ClassCombo (MLClassPtr class1, MLClassPtr class2)
If no entry exists for class pair a new one will be created using the global parameters from the underlying 'svmParameters' object.
Definition at line 432 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::GetParamtersToUseFor2ClassCombo().
{
  return svmParameters->GetParamtersToUseFor2ClassCombo (class1, class2);
} /* GetParamtersToUSeFor2ClassCombo */
SVM_KernalType ModelParamOldSVM::KernalType () const [virtual]
Definition at line 259 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::KernalType().
{
  return svmParameters->KernalType ();
}
void ModelParamOldSVM::KernalType (SVM_KernalType _kernalType) [virtual]
Definition at line 171 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::KernalType().
{
  svmParameters->KernalType (_kernalType);
}
SVM_MachineType ModelParamOldSVM::MachineType () const [virtual]
Definition at line 266 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::MachineType().
Referenced by KKMLL::TrainingConfiguration2::MachineType().
{
  return svmParameters->MachineType ();
}
void ModelParamOldSVM::MachineType (SVM_MachineType _machineType) [virtual]
Definition at line 188 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::MachineType().
Referenced by KKMLL::TrainingConfiguration2::MachineType().
{
  svmParameters->MachineType (_machineType);
}
virtual ModelParamTypes KKMLL::ModelParamOldSVM::ModelParamType () const [inline], [virtual]
Implements KKMLL::ModelParam.
Definition at line 53 of file ModelParamOldSVM.h.
References KKMLL::ModelParam::OldSVM.
{return ModelParamTypes::OldSVM;}
kkint32 ModelParamOldSVM::NumOfFeaturesAfterEncoding (FileDescPtr fileDesc, RunLog & log) const [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 179 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::NumOfFeaturesAfterEncoding().
{
  return svmParameters->NumOfFeaturesAfterEncoding (fileDesc, log);
}
const svm_parameter & ModelParamOldSVM::Param () const [virtual]
Definition at line 272 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::Param().
Referenced by C_Param().
{
  return svmParameters->Param ();
}
void ModelParamOldSVM::ParseCmdLine (KKStr _cmdLineStr, bool & _validFormat, RunLog & _log) [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 291 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::A_Param(), KKMLL::ModelParam::A_Param(), KKMLL::ModelParam::C_Param(), KKMLL::SVMparam::C_Param(), KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKMLL::ModelParam::EncodingMethod(), KKMLL::SVMparam::EncodingMethod(), KKB::KKStr::ExtractToken(), KKMLL::ModelParam::Gamma(), KKMLL::SVMparam::Gamma(), KKB::KKStr::KKStr(), KKB::KKStr::Len(), KKB::KKStr::operator=(), KKB::KKStr::operator[](), SVM_EncodingMethodToModelParamEncodingMethodType(), KKB::KKStr::TrimLeft(), KKB::KKStr::Upper(), and KKMLL::ModelParam::ValidParam().
Referenced by KKMLL::TrainingConfiguration2::BuildTrainingClassListFromDirectoryStructure().
{
  _validFormat = true;
  //DecodeParamStr (_cmdLineStr, param);
  KKStr field (_cmdLineStr.ExtractToken (" \t\n\r"));
  KKStr value;
  while (!field.Empty () && _validFormat)
  {
    if (field[0] != '-')
    {
      _log.Level (-1) << "ModelParam::ParseCmdLine *** Invalid Parameter["
        << field << "] ***"
        << endl;
      _validFormat = false;
      break;
    }
    // See if next field is a Switch field or a parameter.
    _cmdLineStr.TrimLeft (" \t\n\r");
    value = "";
    if (_cmdLineStr.Len () > 0)
    {
      if (_cmdLineStr[0] != '-')
        value = _cmdLineStr.ExtractToken (" \t\n\r");
    }
    field.Upper ();
    KKStr valueUpper (value);
    valueUpper.Upper ();
    bool parameterUsed = false;
    ParseCmdLineParameter (field, value, parameterUsed, _log);
    if (!parameterUsed)
    {
      _log.Level (-1) << "ModelParam::ParseCmdLine - Invalid Parameter["
        << field << "] Value[" << value << "]."
        << endl;
      _validFormat = false;
      break;
    }
    field = _cmdLineStr.ExtractToken (" \t\n\r");
  }
  // Since this class is a special case that handles the old SvmParam paradigm we need
  // to update the local Model:: parameters with those that were updated in 'SvmParam'.
  ModelParam::EncodingMethod (
      SVM_EncodingMethodToModelParamEncodingMethodType (
      svmParameters->EncodingMethod ()));
  
  ModelParam::A_Param (svmParameters->A_Param ());
  ModelParam::C_Param (svmParameters->C_Param ());
  ModelParam::Gamma (svmParameters->Gamma ());
  ValidParam (_validFormat);
} /* ParseCmdLine */
void ModelParamOldSVM::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) [virtual]
Implements KKMLL::ModelParam.
Definition at line 537 of file ModelParamOldSVM.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EqualIgnoreCase(), KKB::XmlStream::GetNextToken(), KKB::KKStr::operator=(), KKMLL::ModelParam::ReadXMLModelParamToken(), KKMLL::ModelParam::SelectedFeatures(), KKMLL::SVMparam::SVMparam(), KKB::XmlElement::ToKKStr(), and KKB::XmlToken::VarName().
{
  KKStr svmParametersStr;
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t)
  {
    t = ReadXMLModelParamToken (t);
    if (t)
    {
      const KKStr& varName = t->VarName ();
      XmlElementPtr e = dynamic_cast<XmlElementPtr> (t);
      if (!e)
      {
        log.Level (-1) << endl
          << "ModelParamOldSVM::ReadXML ***ERROR*** Encountered unexpected content: " <<
      endl
          << endl;
      }
      else if (t->VarName ().EqualIgnoreCase ("SvmParameters"))
      {
        svmParametersStr = e->ToKKStr ();
      }
      else
      {
        log.Level (-1) << endl
          << "ModelParamOldSVM::ReadXML ***ERROR*** Encountered unexpected Element: " << e->
      NameTagStr () << endl
          << endl;
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
  if (!cancelFlag)
  {
    FeatureNumListConstPtr selFeatures =
      ModelParam::SelectedFeatures ();
    bool validFormat = false;
    delete svmParameters;
    svmParameters = new SVMparam (svmParametersStr, selFeatures, validFormat, log);
  }
} /* ReadXML */
float ModelParamOldSVM::SamplingRate () const [virtual]
Definition at line 278 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::SamplingRate().
{
  return svmParameters->SamplingRate ();
}
void ModelParamOldSVM::SamplingRate (float _samplingRate) [virtual]
Definition at line 195 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::SamplingRate().
{
  svmParameters->SamplingRate (_samplingRate);
}
FeatureNumListConstPtr ModelParamOldSVM::SelectedFeatures () const [virtual]
Reimplemented from KKMLL::ModelParam.
Definition at line 208 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::SelectedFeatures().
Referenced by C_Param().
{
  if (svmParameters)
    return svmParameters->SelectedFeatures ();
  else
    return NULL;
}
void ModelParamOldSVM::SelectedFeatures (const FeatureNumList & _selectedFeatures) [virtual]
Definition at line 201 of file ModelParamOldSVM.cpp.
References KKMLL::ModelParam::SelectedFeatures(), and KKMLL::SVMparam::SelectedFeatures().
{
  svmParameters->SelectedFeatures (_selectedFeatures);
  ModelParam::SelectedFeatures (_selectedFeatures);
}
SVM_SelectionMethod ModelParamOldSVM::SelectionMethod () const [virtual]
Definition at line 284 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::SelectionMethod().
Referenced by KKMLL::TrainingConfiguration2::SelectionMethod().
{
  return svmParameters->SelectionMethod ();
}
void ModelParamOldSVM::SelectionMethod (SVM_SelectionMethod _selectionMethod) [virtual]
Definition at line 217 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::SelectionMethod().
Referenced by KKMLL::TrainingConfiguration2::SelectionMethod().
{
  svmParameters->SelectionMethod (_selectionMethod);
}
void ModelParamOldSVM::SetBinaryClassFields (MLClassPtr class1, MLClassPtr class2, const svm_parameter & _param, FeatureNumListConstPtr _features, float _weight)
Definition at line 482 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::SetBinaryClassFields().
Referenced by KKMLL::TrainingConfiguration2::SetBinaryClassFields().
{
  svmParameters->SetBinaryClassFields (class1, class2, _param, _features, _weight);
} /* SetBinaryClassFields */
void ModelParamOldSVM::SetFeatureNums (MLClassPtr class1, MLClassPtr class2, FeatureNumListConstPtr _features, float _weight = -1)
Parameters
_weight -1 Indicates use existing value.
Definition at line 469 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::SetFeatureNums().
Referenced by KKMLL::TrainingConfiguration2::SetFeatureNums().
{
  svmParameters->SetFeatureNums (class1, class2, _features, _weight);
} /* SetFeatureNums */
ModelParam::EncodingMethodType ModelParamOldSVM::SVM_EncodingMethodToModelParamEncodingMethodType (SVM_EncodingMethod _encodingMethod)
converts Encoding variables from `SVM_EncodingMethod` to `ModelParam::EncodingMethodType`
Definition at line 359 of file ModelParamOldSVM.cpp.
References KKMLL::Binary, KKMLL::ModelParam::Binary, KKMLL::NoEncoding, KKMLL::ModelParam::NoEncoding, KKMLL::Null, KKMLL::ModelParam::Null, KKMLL::Scaled, and KKMLL::ModelParam::Scaled.
Referenced by ParseCmdLine().
{
  switch (_encodingMethod)
  {
  case SVM_EncodingMethod::Null: return
      ModelParam::EncodingMethodType::Null;
  case SVM_EncodingMethod::NoEncoding: return
      ModelParam::EncodingMethodType::NoEncoding;
  case SVM_EncodingMethod::Binary: return
      ModelParam::EncodingMethodType::Binary;
  case SVM_EncodingMethod::Scaled: return
      ModelParam::EncodingMethodType::Scaled;
  }
  return ModelParam::EncodingMethodType::Null;;
}
SVMparamPtr ModelParamOldSVM::SvmParameters () const [virtual]
Definition at line 224 of file ModelParamOldSVM.cpp.
Referenced by KKMLL::TrainingConfiguration2::SVMparamREF(), and KKMLL::ModelOldSVM::TrainModel().
{
  return svmParameters;
}
KKStr ModelParamOldSVM::SvmParamToString (const svm_parameter & _param) const
Convert a svm_parameter struct to a cmdline str.
Definition at line 397 of file ModelParamOldSVM.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), and SVM233::svm_parameter::ToCmdLineStr().
{
  KKStr cmdStr (300);
  cmdStr << _param.ToCmdLineStr ();
  return cmdStr;
} /* SvmParamToString */
KKStr ModelParamOldSVM::ToCmdLineStr () const [virtual]
Convert all parameters to a command line string.
Reimplemented from KKMLL::ModelParam.
Definition at line 412 of file ModelParamOldSVM.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), KKB::KKStr::operator=(), and KKMLL::SVMparam::ToString().
{
  KKStr cmdStr (300);
  cmdStr = svmParameters->ToString ();
  return cmdStr;
} /* ToString */
bool ModelParamOldSVM::UseProbabilityToBreakTies () const [virtual]
Definition at line 252 of file ModelParamOldSVM.cpp.
References KKMLL::SVMparam::UseProbabilityToBreakTies().
{
  return svmParameters->UseProbabilityToBreakTies ();
}
void ModelParamOldSVM::WriteXML (const KKStr & varName, std::ostream & o) const [virtual]
Implements KKMLL::ModelParam.
Definition at line 514 of file ModelParamOldSVM.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKMLL::SVMparam::ToString(), KKB::XmlTag::WriteXML(), KKB::KKStr::WriteXML(), KKMLL::ModelParam::WriteXMLFields(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("ModelParamOldSVM", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  WriteXMLFields (o);
  svmParameters->ToString ().WriteXML ("SvmParameters", o);
  XmlTag endTag ("ModelParamOldSVM", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelParamOldSVM.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelParamOldSVM.cpp