KKLSC::StartStopRegionList Class Reference
#include <StartStopPoint.h>
Public Member Functions
StartStopRegionList (bool _owner)
StartStopRegionList (const StartStopPointList &startStopPoints)
~StartStopRegionList ()
Additional Inherited Members
Detailed Description
Definition at line 138 of file StartStopPoint.h.
Constructor & Destructor Documentation
StartStopRegionList::StartStopRegionList (bool _owner)
Definition at line 386 of file StartStopPoint.cpp.
References StartStopRegionList().
Referenced by StartStopRegionList().
                                                     :
    KKQueue<StartStopRegion> (_owner)
{
}
StartStopRegionList::StartStopRegionList (const StartStopPointList & startStopPoints)
Definition at line 393 of file StartStopPoint.cpp.
References StartStopRegionList().
Referenced by StartStopRegionList().
                                                                                   :
    KKQueue<StartStopRegion> (true)
{
  if (startStopPoints.size () < 1)
  {
    PushOnBack (new StartStopRegion (0, int32_max));
  }
  else
  {
    kkint32 prevLineNum = 0;
    StartStopPoint::StartStopType prevType =
      StartStopPoint::StartStopType::StartPoint;
    StartStopPointList::const_iterator idx = startStopPoints.begin ();
    while (idx != startStopPoints.end ())
    {
      kkint32 nextLineNum = (*idx)->ScanLineNum ();
      StartStopPoint::StartStopType nextType = (*idx)->Type ();
      if (prevType == StartStopPoint::StartStopType::StartPoint)
      {
        if (nextType == StartStopPoint::StartStopType::StopPoint)
        {
          PushOnBack (new StartStopRegion (prevLineNum, nextLineNum));
          prevType = nextType;
          prevLineNum = nextLineNum;
        }
        else
        {
          // Since we appear to have two start points in a row we will ignore the second one.
        }
      }
      else
      {
        // previous point was StopPoint.
        if (nextType == StartStopPoint::StartStopType::StopPoint)
        {
          // We have two stop points in a row; will ignore
        }
        else
        {
          // We have the beginnings of a new StartStopregion.
          prevType = nextType;
          prevLineNum = nextLineNum;
        }
      }
      ++idx;
    }
    if (prevType == StartStopPoint::StartStopType::StartPoint)
    {
      PushOnBack (new StartStopRegion (prevLineNum,
      int32_max));
    }
  }
}
StartStopRegionList::~StartStopRegionList ()
Definition at line 451 of file StartStopPoint.cpp.
{
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/StartStopPoint.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/StartStopPoint.cpp