KKLSC::FlowMeterTracker Class Reference
Class that keeps track the Flow-Meter-Counter values by scan-lines; using these values it will compute estimated flow rate.
#include <FlowMeterTracker.h>
Public Types
typedef FlowMeterTracker * FlowMeterTrackerPtr
Public Member Functions
FlowMeterTracker ()
FlowMeterTracker (const FlowMeterTracker &entry)
~FlowMeterTracker ()
void AddEntry (kkuint32 _scanLineNum, kkuint32 _counterValue)
float ComputeFlowRateFromFlowRateRatio (float _flowRateRatio)
float ComputeFlowRateRatioFromFlowRate (float _flowRate)
bool FlowMeterPresent () const
float FlowRateDefault () const
float FlowRateInstantaneous ()
float FlowRateRatioDefault () const
void FlowRateRatioDefaultChanged (float _flowRateRatioDefault)
float FlowRateTrend ()
void GetFlowRateInstantaneous (float &flowRate, float &flowRateRatio)
void GetFlowRateTrend (float &flowRate, float &flowRateRatio)
kkint32 HistoryTableSize () const
float ImagingWidthMeters () const
kkint32 ImagingWidthPixels () const
void Initialize (bool _flowMeterPresent, float _flowRateRatioDefault, kkint32 _historyTableSize, float _scanRate, float _imagingWidthMeters, kkint32 _imagingWidthPixels, float _ticsPerMeter)
kkint32 MemoryConsumedEstimated ()
void ScanRateChanged (float _newScanRate)
float TicsPerMeter () const
Detailed Description
Class that keeps track the Flow-Meter-Counter values by scan-lines; using these values it will compute estimated flow rate.
Glossary
FlowRate(FR) = Rate of water flow in (Meters/Sec)
FlowRateRatio(FRR) = Number TemporalPixel's per SpatialPixel with respect to physical distance; aka
      FlowRateFactor. (TP's/SP's)
ScanRate(SR) = Number of camera scan lines captured per second. (ScanLines/Sec) or (TP's/Sec)
SpatialPixel(SP) = From the image chambers width perspective;
TemporalPixel(TP) = One scan line; The physical distance a pixel covers with respect to flow is dependent
                on both scan rate and flow rate. TP = (FRR)(SP).
ChamberWidthSpatialy (CWS) Distance across Imaging Chamber width as measured in meters (m).
ChamberWidthPixels (CWP) Number of pixels imaged across the imaging chamber. (1 + CropLeft - CropRight).
        (SP's)
ChamberWidthTemporal (CWT) Time it would take for Camera to cover same distance in direction of flow.
 FlowRateRatio = ((CWS)(SR)) / ((FR)(CWP)).
 FlowRate = ((CWS)(SR)) / ((FRR)(CWP))
Definition at line 44 of file FlowMeterTracker.h.
Member Typedef Documentation
typedef FlowMeterTracker* KKLSC::FlowMeterTracker::FlowMeterTrackerPtr
Definition at line 47 of file FlowMeterTracker.h.
Constructor & Destructor Documentation
FlowMeterTracker::FlowMeterTracker ()
Definition at line 29 of file FlowMeterTracker.cpp.
                                   :
    flowMeterPresent (false),
    flowRateDefault (1.0f),
    flowRateRatioDefault (1.0f),
    history (NULL),
    historyTableSize (-1),
    historyLastIdxAdded (-1),
    historyOldestIdx (-1),
    imagingWidthMeters (0.0635f),
    imagingWidthPixels (2048),
    scanRate (0.0f),
    ticsPerMeter (10.0f)
{
}
FlowMeterTracker::FlowMeterTracker (const FlowMeterTracker & entry)
Definition at line 46 of file FlowMeterTracker.cpp.
                                                                 :
    flowMeterPresent (entry.flowMeterPresent),
    flowRateDefault (entry.flowRateDefault),
    flowRateRatioDefault (entry.flowRateRatioDefault),
    history (NULL),
    historyTableSize (entry.historyTableSize),
    historyLastIdxAdded (entry.historyLastIdxAdded),
    historyOldestIdx (entry.historyOldestIdx),
    imagingWidthMeters (entry.imagingWidthMeters),
    imagingWidthPixels (entry.imagingWidthPixels),
    scanRate (entry.scanRate),
    ticsPerMeter (entry.ticsPerMeter)
{
  history = new Entry[historyTableSize];
  for (kkint32 x = 0; x < historyTableSize; ++x)
    history[x] = entry.history[x];
}
FlowMeterTracker::~FlowMeterTracker ()
Definition at line 67 of file FlowMeterTracker.cpp.
{
  delete history;
  history = NULL;
}
Member Function Documentation
void FlowMeterTracker::AddEntry (kkuint32 _scanLineNum, kkuint32 _counterValue)
Definition at line 128 of file FlowMeterTracker.cpp.
{
  if (historyLastIdxAdded < 0)
  {
    historyLastIdxAdded = 0;
    historyOldestIdx = 0;
  }
  else
  {
    ++historyLastIdxAdded;
    if (historyLastIdxAdded >= historyTableSize)
      historyLastIdxAdded = 0;
    if (historyLastIdxAdded == historyOldestIdx)
    {
      ++historyOldestIdx;
      if (historyOldestIdx >= historyTableSize)
        historyOldestIdx = 0;
    }
  }
  history[historyLastIdxAdded].scanLineNum = _scanLineNum;
  history[historyLastIdxAdded].counterValue = _counterValue;
} /* AddEntry */
float FlowMeterTracker::ComputeFlowRateFromFlowRateRatio (float _flowRateRatio)
Definition at line 254 of file FlowMeterTracker.cpp.
Referenced by FlowRateRatioDefaultChanged(), Initialize(), and ScanRateChanged().
{
  if ((_flowRateRatio == 0.0f) || (imagingWidthPixels == 0.0f))
    return flowRateDefault;
  //float flowRate = (imagingWidthMeters * scanRate) / (_flowRateRatio * imagingWidthPixels);
  float flowRate = (_flowRateRatio * scanRate * imagingWidthMeters) / imagingWidthPixels;
  return flowRate;
}
float FlowMeterTracker::ComputeFlowRateRatioFromFlowRate (float _flowRate)
Definition at line 267 of file FlowMeterTracker.cpp.
Referenced by GetFlowRateInstantaneous(), and GetFlowRateTrend().
{
  if ((_flowRate == 0.0f) || (imagingWidthPixels == 0.0f))
    return flowRateRatioDefault;
  //float flowRateRatio = (imagingWidthMeters * scanRate) / (_flowRate * imagingWidthPixels);
  float flowRateRatio = (_flowRate * imagingWidthPixels) / (imagingWidthMeters * scanRate);
  return flowRateRatio;
}
bool KKLSC::FlowMeterTracker::FlowMeterPresent () const [inline]
Definition at line 76 of file FlowMeterTracker.h.
{return flowMeterPresent;}
float KKLSC::FlowMeterTracker::FlowRateDefault () const [inline]
Definition at line 77 of file FlowMeterTracker.h.
{return flowRateDefault;}
float FlowMeterTracker::FlowRateInstantaneous ()
Computes flow rate using the two most current count entries.
Definition at line 163 of file FlowMeterTracker.cpp.
Referenced by GetFlowRateInstantaneous().
{
  if ((historyLastIdxAdded == historyOldestIdx) || (ticsPerMeter == 0.0f) || (scanRate == 0.0f))
    return flowRateDefault;
  kkint32 prevIdx = historyLastIdxAdded - 1;
  if (prevIdx < 0)
    prevIdx = historyTableSize - 1;
  EntryPtr lastPtr = history + historyLastIdxAdded;
  EntryPtr prevPtr = history + prevIdx;
 
  kkint32 tics = lastPtr->counterValue - prevPtr->counterValue;
  kkint32 scanLines = lastPtr->scanLineNum - prevPtr->scanLineNum;
  float meters = tics / ticsPerMeter;
  float secs = scanLines / scanRate;
  return meters / secs;
} /* FlowRateInstantaneous */
float KKLSC::FlowMeterTracker::FlowRateRatioDefault () const [inline]
Definition at line 78 of file FlowMeterTracker.h.
{return flowRateRatioDefault;}
void FlowMeterTracker::FlowRateRatioDefaultChanged (float _flowRateRatioDefault)
Definition at line 111 of file FlowMeterTracker.cpp.
References ComputeFlowRateFromFlowRateRatio().
{
  flowRateRatioDefault = _flowRateRatioDefault;
  flowRateDefault = ComputeFlowRateFromFlowRateRatio (flowRateRatioDefault)
      ;
}
float FlowMeterTracker::FlowRateTrend ()
Computes flow rate using full range of history table.
Definition at line 187 of file FlowMeterTracker.cpp.
Referenced by GetFlowRateTrend().
{
  if ((historyLastIdxAdded == historyOldestIdx) || (ticsPerMeter == 0.0f) || (scanRate == 0.0f))
    return flowRateDefault;
  EntryPtr lastPtr = history + historyLastIdxAdded;
  EntryPtr prevPtr = history + historyOldestIdx;
 
  kkint32 tics = lastPtr->counterValue - prevPtr->counterValue;
  kkint32 scanLines = lastPtr->scanLineNum - prevPtr->scanLineNum;
  if ((tics == 0) || (scanLines == 0))
    return 0.0f;
  float meters = tics / ticsPerMeter;
  float secs = scanLines / scanRate;
  return meters / secs;
} /* FlowRateTrend */
void FlowMeterTracker::GetFlowRateInstantaneous (float & flowRate, float & flowRateRatio)
Definition at line 210 of file FlowMeterTracker.cpp.
References ComputeFlowRateRatioFromFlowRate(), and FlowRateInstantaneous().
{
  if (!flowMeterPresent)
  {
    flowRate = flowRateDefault;
    flowRateRatio = flowRateRatioDefault;
    return;
  }
  flowRate = FlowRateInstantaneous ();
  flowRateRatio = ComputeFlowRateRatioFromFlowRate (flowRate);
  return;
}
void FlowMeterTracker::GetFlowRateTrend (float & flowRate, float & flowRateRatio)
Definition at line 228 of file FlowMeterTracker.cpp.
References ComputeFlowRateRatioFromFlowRate(), and FlowRateTrend().
{
  if ((!flowMeterPresent) || (this->historyLastIdxAdded < 0) || (historyLastIdxAdded == this->
      historyOldestIdx))
  {
    flowRate = flowRateDefault;
    flowRateRatio = flowRateRatioDefault;
    return;
  }
  if (!flowMeterPresent)
  {
    flowRate = flowRateDefault;
    flowRateRatio = flowRateRatioDefault;
    return;
  }
  flowRate = FlowRateTrend ();
  flowRateRatio = ComputeFlowRateRatioFromFlowRate (flowRate);
  return;
}
kkint32 KKLSC::FlowMeterTracker::HistoryTableSize () const [inline]
Definition at line 79 of file FlowMeterTracker.h.
{return historyTableSize;}
float KKLSC::FlowMeterTracker::ImagingWidthMeters () const [inline]
Definition at line 80 of file FlowMeterTracker.h.
{return imagingWidthMeters;}
kkint32 KKLSC::FlowMeterTracker::ImagingWidthPixels () const [inline]
Definition at line 81 of file FlowMeterTracker.h.
{return imagingWidthPixels;}
void FlowMeterTracker::Initialize (bool _flowMeterPresent, float _flowRateRatioDefault, kkint32 _historyTableSize, float _scanRate, float _imagingWidthMeters, kkint32 _imagingWidthPixels, float _ticsPerMeter)
Parameters
in _flowMeterPresent Indicates if there is a Flow Meter or will FlowRate and FlowRateRatio be derived from configuration; see _flowRateRatioDefault.
in _flowRateRatioDefault When flow meter s not present or unable to compute FlowRate will utilize this value to return FlowRate and FlowRateRatio.
in _historyTableSize The number of FlowMeter readings that will be tracked.
in _scanRate Scan-Lines per second that camera is operating at.
in _imagingWidthMeters Width in meters that is being imaged.
in _imagingWidthPixels Number of pixels that is being imaged; this is the same as distance refereed to by _imagingWidthMeters.
in _ticsPerMeter The number counter ticks that occur per meter; this value will help compute FlowRate.
Definition at line 74 of file FlowMeterTracker.cpp.
References ComputeFlowRateFromFlowRateRatio().
{
  flowMeterPresent = _flowMeterPresent;
  flowRateRatioDefault = _flowRateRatioDefault;
  scanRate = _scanRate;
  imagingWidthMeters = _imagingWidthMeters;
  imagingWidthPixels = _imagingWidthPixels;
  ticsPerMeter = _ticsPerMeter;
  historyTableSize = _historyTableSize;
  delete history;
  history = new Entry[historyTableSize];
  historyLastIdxAdded = -1;
  historyOldestIdx = -1;
  flowRateDefault = ComputeFlowRateFromFlowRateRatio (flowRateRatioDefault)
      ;
}
kkint32 FlowMeterTracker::MemoryConsumedEstimated ()
Definition at line 101 of file FlowMeterTracker.cpp.
{
  kkint32 mem = sizeof (*this);
  if (historyTableSize > 0)
    mem += sizeof (Entry) * historyTableSize;
  return mem;
}
void FlowMeterTracker::ScanRateChanged (float _newScanRate)
Definition at line 119 of file FlowMeterTracker.cpp.
References ComputeFlowRateFromFlowRateRatio().
{
  scanRate = _newScanRate;
  flowRateDefault = ComputeFlowRateFromFlowRateRatio (flowRateRatioDefault)
      ;
}
float KKLSC::FlowMeterTracker::TicsPerMeter () const [inline]
Definition at line 82 of file FlowMeterTracker.h.
{return ticsPerMeter;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/FlowMeterTracker.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/FlowMeterTracker.cpp