SVM233::ONE_CLASS_Q Class Reference
Public Member Functions
ONE_CLASS_Q (const svm_problem &prob, const svm_parameter &param)
~ONE_CLASS_Q ()
Qfloat * get_Q (kkint32 i, kkint32 len) const
void swap_index (kkint32 i, kkint32 j) const
Additional Inherited Members
Detailed Description
Definition at line 2697 of file svm.cpp.
Constructor & Destructor Documentation
SVM233::ONE_CLASS_Q::ONE_CLASS_Q (const svm_problem & prob, const svm_parameter & param) [inline]
Definition at line 2700 of file svm.cpp.
References SVM233::Cache::Cache(), SVM233::svm_parameter::cache_size, SVM233::Kernel::Kernel(), SVM233::svm_problem::l, and SVM233::svm_problem::x.
Referenced by SVM233::solve_one_class().
    :Kernel (prob.l, prob.x, param)
  {
    cache = new Cache(prob.l,(kkint32)(param.cache_size*(1<<20)));
  }
SVM233::ONE_CLASS_Q::~ONE_CLASS_Q () [inline]
Definition at line 2727 of file svm.cpp.
  {
    delete cache;
  }
Member Function Documentation
Qfloat* SVM233::ONE_CLASS_Q::get_Q (kkint32 i, kkint32 len) const [inline], [virtual]
Implements SVM233::Kernel.
Definition at line 2708 of file svm.cpp.
References SVM233::Cache::get_data(), and SVM233::Kernel::kernel_function.
  {
    Qfloat *data;
    kkint32 start;
    if((start = cache->get_data(i,&data,len)) < len)
    {
      for(kkint32 j=start;j<len;j++)
        data[j] = (Qfloat)(this->*kernel_function)(i,j);
    }
    return data;
  }
void SVM233::ONE_CLASS_Q::swap_index (kkint32 i, kkint32 j) const [inline], [virtual]
Reimplemented from SVM233::Kernel.
Definition at line 2720 of file svm.cpp.
References SVM233::Cache::swap_index(), and SVM233::Kernel::swap_index().
  {
    cache->swap_index(i,j);
    Kernel::swap_index(i,j);
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm.cpp