KKLSC::StartStopPoint Class Reference
Class that keeps track of parameter details of a single scanner file.
#include <StartStopPoint.h>
Public Types
typedef StartStopPoint * StartStopPointPtr
enum StartStopType : int { StartStopType::Null,
StartStopType::StartPoint,
StartStopType::StopPoint,
StartStopType::Invalid
 }
Public Member Functions
StartStopPoint (kkint32 _scanLineNum, StartStopType _type)
StartStopPoint (const StartStopPoint &entry)
StartStopPoint (const KKStr &s)
~StartStopPoint ()
kkint32 MemoryConsumedEstimated () const
void ParseTabDelStr (KKStr parser)
kkint32 ScanLineNum () const
void ScanLineNum (const kkint32 _scanLineNum)
KKStr ToTabDelStr () const
StartStopType Type () const
void Type (StartStopType _type)
const KKStr & TypeStr () const
Static Public Member Functions
static StartStopType StartStopTypeFromStr (const KKStr &s)
static const KKStr & StartStopTypeToStr (StartStopType t)
Detailed Description
Class that keeps track of parameter details of a single scanner file.
Definition at line 28 of file StartStopPoint.h.
Member Typedef Documentation
typedef StartStopPoint* KKLSC::StartStopPoint::StartStopPointPtr
Definition at line 31 of file StartStopPoint.h.
Member Enumeration Documentation
enum KKLSC::StartStopPoint::StartStopType : int [strong]
Enumerator
Null
StartPoint
StopPoint
Invalid
Definition at line 33 of file StartStopPoint.h.
                              : int
                 {Null,
                  StartPoint,
                  StopPoint,
                  Invalid
                 };
Constructor & Destructor Documentation
StartStopPoint::StartStopPoint (kkint32 _scanLineNum, StartStopType _type)
Definition at line 50 of file StartStopPoint.cpp.
Referenced by KKLSC::StartStopPointList::AddEntry().
                                 :
   scanLineNum (_scanLineNum),
   type (_type)
{
}
StartStopPoint::StartStopPoint (const StartStopPoint & entry)
Definition at line 60 of file StartStopPoint.cpp.
                                                           :
   scanLineNum (entry.scanLineNum),
   type (entry.type)
{
}
StartStopPoint::StartStopPoint (const KKStr & s)
Definition at line 68 of file StartStopPoint.cpp.
References Invalid, and ParseTabDelStr().
Referenced by KKLSC::ScannerFile::LoadIndexFile().
                                                 :
   scanLineNum (-1),
   type (StartStopType::Invalid)
{
  ParseTabDelStr (s);
}
StartStopPoint::~StartStopPoint ()
Definition at line 77 of file StartStopPoint.cpp.
{
}
Member Function Documentation
kkint32 StartStopPoint::MemoryConsumedEstimated () const
Definition at line 82 of file StartStopPoint.cpp.
Referenced by KKLSC::StartStopPointList::MemoryConsumedEstimated().
{
  return sizeof (*this);
}
void StartStopPoint::ParseTabDelStr (KKStr parser)
Definition at line 99 of file StartStopPoint.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::ExtractToken2(), KKB::KKStr::ExtractTokenInt(), and StartStopTypeFromStr().
Referenced by StartStopPoint().
{
  scanLineNum = parser.ExtractTokenInt ("\t");
  KKStr typeStr = parser.ExtractToken2 ("\t");
  type = StartStopTypeFromStr (typeStr);
}
kkint32 KKLSC::StartStopPoint::ScanLineNum () const [inline]
Definition at line 56 of file StartStopPoint.h.
Referenced by KKLSC::StartStopPointList::AddEntry().
{return scanLineNum;}
void KKLSC::StartStopPoint::ScanLineNum (const kkint32 _scanLineNum) [inline]
Definition at line 60 of file StartStopPoint.h.
{scanLineNum = _scanLineNum;}
StartStopPoint::StartStopType StartStopPoint::StartStopTypeFromStr (const KKStr & s) [static]
Definition at line 41 of file StartStopPoint.cpp.
References KKB::KKStr::EqualIgnoreCase(), Invalid, and Null.
Referenced by ParseTabDelStr().
{
  for (int x = (int)StartStopType::Null; x < (int)
      StartStopType::Invalid; ++x)
    if (s.EqualIgnoreCase (startStopPointStrs[x]))
      return (StartStopType)x;
  return StartStopType::Null;
}
const KKStr & StartStopPoint::StartStopTypeToStr (StartStopType t) [static]
Definition at line 32 of file StartStopPoint.cpp.
References Invalid, and Null.
Referenced by TypeStr().
{
  if (t <= StartStopType::Null) return (startStopPointStrs[(int)
      StartStopType::Null]);
  if (t >= StartStopType::Invalid) return (startStopPointStrs[(int)
      StartStopType::Invalid]);
  return (startStopPointStrs[(int)t]);
}
KKStr StartStopPoint::ToTabDelStr () const
Definition at line 90 of file StartStopPoint.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), and TypeStr().
{
  KKStr s (48);
  s << scanLineNum << "\t" << TypeStr ();
  return s;
}
StartStopType KKLSC::StartStopPoint::Type () const [inline]
Definition at line 57 of file StartStopPoint.h.
Referenced by KKLSC::StartStopPointList::AddEntry(), and KKLSC::ScannerFile::LoadIndexFile().
{return type;}
void KKLSC::StartStopPoint::Type (StartStopType _type) [inline]
Definition at line 61 of file StartStopPoint.h.
Referenced by KKLSC::StartStopPointList::AddEntry().
{type = _type;}
const KKStr& KKLSC::StartStopPoint::TypeStr () const [inline]
Definition at line 58 of file StartStopPoint.h.
References StartStopTypeToStr().
Referenced by ToTabDelStr().
{return StartStopTypeToStr (type);}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/StartStopPoint.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/StartStopPoint.cpp