KKMLL::GrayScaleImagesFVList Class Reference
#include <GrayScaleImagesFV.h>
Classes
class const_iterator
class iterator
Public Types
typedef GrayScaleImagesFVList * GrayScaleImagesFVListPtr
Public Member Functions
GrayScaleImagesFVList (FileDescPtr _fileDesc, bool _owner)
GrayScaleImagesFVList (const GrayScaleImagesFVList &_examples, bool _owner)
Creates a duplicate List of examples, in the same order, and depending on '_owner' will create new instances or just point to the existing one.
GrayScaleImagesFVList (const FeatureVectorList &featureVectorList, bool _owner)
Creates a duplicate List of examples, in the same order, and depending on '_owner' will create new instances or just point to the existing one.
GrayScaleImagesFVList (FactoryFVProducerPtr _fvProducerFactory, MLClassPtr _mlClass, KKStr _dirName, KKStr _fileName, RunLog &_log)
Constructor that will extract a list of feature vectors for all the image files in the specified directory.
GrayScaleImagesFVList (MLClassList &_mlClasses, GrayScaleImagesFVList &_examples)
constructor that will create a list of examples from _examples that are assigned one of the classes listed in _mlClasses.
GrayScaleImagesFVList (const FeatureVectorList &featureVectorList)
virtual ~GrayScaleImagesFVList ()
void AddQueue (GrayScaleImagesFVList &imagesToAdd)
GrayScaleImagesFVPtr BackOfQueue ()
GrayScaleImagesFVPtr BinarySearchByName (const KKStr &_imageFileName) const
virtual GrayScaleImagesFVListPtr Duplicate (bool _owner) const
Creates a duplicate of list using the same container.
virtual GrayScaleImagesFVListPtr DuplicateListAndContents () const
Creates a duplicate of list and also duplicates it contents.
GrayScaleImagesFVListPtr ExtractDuplicatesByRootImageFileName ()
GrayScaleImagesFVListPtr ExtractExamplesForAGivenClass (MLClassPtr _mlClass, kkint32 _maxToExtract=-1, float _minSize=-1.0f) const
GrayScaleImagesFVPtr IdxToPtr (kkint32 idx) const
GrayScaleImagesFVPtr LookUpByImageFileName (const KKStr &_imageFileName) const
GrayScaleImagesFVPtr LookUpByRootName (const KKStr &_rootName)
virtual GrayScaleImagesFVListPtr ManufactureEmptyList (bool _owner) const
Creates an instance of a Empty FeatureVectorList.
GrayScaleImagesFVListPtr OrderUsingNamesFromAFile (const KKStr &fileName, RunLog &log)
Using list of ImageFileNames in a file('fileName') create a new GrayScaleImagesFVList instance with examples in order based off contents of file. If error occurs will return NULL.
GrayScaleImagesFVPtr PopFromBack ()
void RecalcFeatureValuesFromImagesInDirTree (FactoryFVProducerPtr fvProducerFactory, const KKStr &rootDir, bool &successful, RunLog &log)
GrayScaleImagesFVListPtr StratifyAmoungstClasses (kkint32 numOfFolds, RunLog &log)
GrayScaleImagesFVListPtr StratifyAmoungstClasses (MLClassListPtr mlClasses, kkint32 maxImagesPerClass, kkint32 numOfFolds, RunLog &log)
Additional Inherited Members
Detailed Description
Definition at line 112 of file GrayScaleImagesFV.h.
Member Typedef Documentation
typedef GrayScaleImagesFVList* KKMLL::GrayScaleImagesFVList::GrayScaleImagesFVListPtr
Definition at line 115 of file GrayScaleImagesFV.h.
Constructor & Destructor Documentation
GrayScaleImagesFVList::GrayScaleImagesFVList (FileDescPtr _fileDesc, bool _owner)
Definition at line 115 of file GrayScaleImagesFV.cpp.
References KKMLL::FeatureVectorList::FeatureVectorList().
                                              :
    FeatureVectorList (_fileDesc, _owner)
{
}
GrayScaleImagesFVList::GrayScaleImagesFVList (const GrayScaleImagesFVList & _examples, bool _owner)
Creates a duplicate List of examples, in the same order, and depending on '_owner' will create new instances or just point to the existing one.
If '_owner' = true
   Create new instances of contents and own them.
else if 'owner' = false,
   Copy over pointers to existing instances.
Parameters
in _examples The list of 'GrayScaleImagesFV' that is to be copied.
in _owner If 'true' new instances of 'GrayScaleImagesFV' instances will be created and this new list will own them and if 'false' will just point to the existing instances and not own the.
Definition at line 160 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFVList(), KKMLL::GrayScaleImagesFVList::const_iterator::operator*(), KKMLL::GrayScaleImagesFVList::const_iterator::operator++(), and KKMLL::GrayScaleImagesFVList::const_iterator::operator==().
Referenced by Duplicate(), and GrayScaleImagesFVList().
                                              :
   FeatureVectorList (examples.FileDesc (), _owner)
{
  const_iterator idx;
  for (idx = examples.begin (); idx != examples.end (); idx++)
  {
    const GrayScaleImagesFVPtr imageExample = *idx;
    if (Owner ())
      PushOnBack (new GrayScaleImagesFV (*imageExample));
    else
      PushOnBack (imageExample);
  }
}
GrayScaleImagesFVList::GrayScaleImagesFVList (const FeatureVectorList & featureVectorList, bool _owner)
Creates a duplicate List of examples, in the same order, and depending on '_owner' will create new instances or just point to the existing one.
If '_owner' = true
   Create new instances of contents and own them.
else if 'owner' = false,
   Copy over pointers to existing instances.
 If any of the existing instances do not have an underlying class of GrayScaleImagesFV; the function will throw an exception.
Parameters
in _examples The list of 'GrayScaleImagesFV' that is to be copied.
in _owner If 'true' new instances of 'GrayScaleImagesFV' instances will be created and this new list will own them and if 'false' will just point to the existing instances and not own the.
Definition at line 178 of file GrayScaleImagesFV.cpp.
References KKB::KKStr::Concat(), KKMLL::FeatureVectorList::FeatureVectorList(), KKMLL::FeatureVectorList::FileDesc(), KKMLL::GrayScaleImagesFV::GrayScaleImagesFV(), and KKB::KKException::KKException().
                                              :
  FeatureVectorList (featureVectorList.FileDesc (),
                     _owner
                    )
{
  //if (strcmp (featureVectorList.UnderlyingClass (), "GrayScaleImagesFVList") == 0)
  if (typeid (featureVectorList) == typeid (GrayScaleImagesFVList))
  {
    const GrayScaleImagesFVList& examples = dynamic_cast<const
      GrayScaleImagesFVList&> (featureVectorList);
  }
  if (_owner)
  {
    FeatureVectorList::const_iterator idx;
    for (idx = featureVectorList.begin (); idx != featureVectorList.end (); idx++)
    {
      FeatureVectorPtr featureVector = *idx;
      
      // The constructor below will detect what the underlying type of 'featureVector' is.
      // If (underlying type is a 'GrayScaleImagesFV' object) then
      // | Information that is particular to a 'GrayScaleImagesFV' object will be extracted
      // | from the 'FeatureVector' object being passed in.
      // else
      // | info that is particular to a 'GrayScaleImagesFV' object will be set to
      // | default values.
      GrayScaleImagesFVPtr example = new GrayScaleImagesFV (*
      featureVector);
      PushOnBack (example);
    }
  }
  else
  {
    // Since we will not own the contents but just point to an existing instances we will
    // have to make sure that the existing instances of 'FeatureVector' objects have a
    // underlying type of 'GrayScaleImagesFV'.
    FeatureVectorList::const_iterator idx;
    for (idx = featureVectorList.begin (); idx != featureVectorList.end (); idx++)
    {
      FeatureVectorPtr featureVector = *idx;
      //if (strcmp (featureVector->UnderlyingClass (), "GrayScaleImagesFV") == 0)
      if (typeid (*featureVector) == typeid (GrayScaleImagesFV))
      {
        GrayScaleImagesFVPtr example = dynamic_cast<
      GrayScaleImagesFVPtr>(featureVector);
        PushOnBack (example);
      }
      else
      {
        // **** ERROR ****
        KKStr errMSsg = "GrayScaleImagesFVList One of the elements in 'featureVectorList' is not of
       'GrayScaleImagesFV' type.";
        cerr << endl
             << "GrayScaleImagesFVList::GrayScaleImagesFVList (const FeatureVectorList& featureVectorList)
         ***ERROR***" << endl
             << " " << errMSsg << endl
             << " FileName[" << featureVector->ExampleFileName () << "]" <<
      endl
             << endl;
        throw KKException (errMSsg);
      }
    }
  }
}
GrayScaleImagesFVList::GrayScaleImagesFVList (FactoryFVProducerPtr _fvProducerFactory, MLClassPtr _mlClass, KKStr _dirName, KKStr _fileName, RunLog & _log)
Constructor that will extract a list of feature vectors for all the image files in the specified directory.
Will scan the directory _dirName for any image files. For each image found a new instance of GrayScaleImagesFV will be created who's features will be derived from the image. These GrayScaleImagesFV' objects will be assigned the class specified by '_mlClass'. A new data file containing the extracted features will be saved in fileName.
Parameters
in _fvProducerFactory
in _mlClass Class to assign to new 'GrayScaleImagesFV' objects.
in _dirName Directory to scan for examples.
in _fileName Name of file to contain the extracted feature data. Will be of the Raw format.
in _log Log file to write messages to.
Definition at line 127 of file GrayScaleImagesFV.cpp.
References KKMLL::FeatureVectorList::FeatureVectorList(), and KKMLL::FactoryFVProducer::FileDesc().
                                              :
   FeatureVectorList (_fvProducerFactory->FileDesc (), true)
{
  FeatureExtraction (_fvProducerFactory, _dirName, _fileName, _mlClass, _log);
}
GrayScaleImagesFVList::GrayScaleImagesFVList (MLClassList & _mlClasses, GrayScaleImagesFVList & _examples)
constructor that will create a list of examples from _examples that are assigned one of the classes listed in _mlClasses.
Will Create a list of examples that are a subset of the ones in _examples. The subset will consist of the examples who's mlClass is one of the ones in mlClasses. We will not own any the contents only point to the ones already in _examples.
Parameters
in _mlClasses List of classes that we are interested in.
in _examples Source examples that we want to scan.
Definition at line 254 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFVList().
Referenced by GrayScaleImagesFVList().
                                              :
  FeatureVectorList (_mlClasses, _examples)
  
{
}
GrayScaleImagesFVList::GrayScaleImagesFVList (const FeatureVectorList & featureVectorList)
This constructor is meant to create a list of 'GrayScaleImagesFV' objects from the FeatureVector objects contained in featureVectorList.
If 'featureVectorList' owns its contents (that is 'featureVectorList.Owner () == true' then
   | We will create new Instances of 'GrayScaleImagesFV' objects that we will own.
   | The underlying class of the 'FeatureVector' objects will be converted to a
   | 'GrayScaleImagesFV' class.
else
   | all the 'FeatureVector' objects in 'featureVectorList' must have an underlying class of
   | 'GrayScaleImagesFV'. If one or more do not then the program will halt with a message to
   | the log.
Definition at line 265 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFVList().
Referenced by ExtractDuplicatesByRootImageFileName(), ExtractExamplesForAGivenClass(), GrayScaleImagesFVList(), OrderUsingNamesFromAFile(), and StratifyAmoungstClasses().
                                                                                        :
  FeatureVectorList (featureVectorList.FileDesc (),
                     featureVectorList.Owner ()
                    )
{
  //if (strcmp (featureVectorList.UnderlyingClass (), "GrayScaleImagesFVList") == 0)
  if (typeid (featureVectorList) == typeid (GrayScaleImagesFVList))
  {
    const GrayScaleImagesFVList& examples = dynamic_cast<const
      GrayScaleImagesFVList&> (featureVectorList);
  }
  if (featureVectorList.Owner ())
  {
    FeatureVectorList::const_iterator idx;
    for (idx = featureVectorList.begin (); idx != featureVectorList.end (); idx++)
    {
      FeatureVectorPtr featureVector = *idx;
      
      // The constructor below will detect what the underlying type of 'featureVector' is.
      // If (underlying type is a 'GrayScaleImagesFV' object) then
      // | Information that is particular to a 'GrayScaleImagesFV' object will be extracted
      // | from the 'FeatureVector' object being passed in.
      // else
      // | info that is particular to a 'GrayScaleImagesFV' object will be set to
      // | default values.
      GrayScaleImagesFVPtr example = new GrayScaleImagesFV (*
      featureVector);
      PushOnBack (example);
    }
  }
  else
  {
    // Since we will not own the contents but just point to existing instances we will
    // have to make sure that the existing instances of 'FeatureVector' objects have a
    // underlying type of 'GrayScaleImagesFV'.
    FeatureVectorList::const_iterator idx;
    for (idx = featureVectorList.begin (); idx != featureVectorList.end (); idx++)
    {
      FeatureVectorPtr featureVector = *idx;
      //if (strcmp (featureVector->UnderlyingClass (), "GrayScaleImagesFV") == 0)
      if (typeid (*featureVector) == typeid (GrayScaleImagesFV))
      {
        GrayScaleImagesFVPtr example = dynamic_cast<
      GrayScaleImagesFVPtr>(featureVector);
        PushOnBack (example);
      }
      else
      {
        // **** ERROR ****
        KKStr errMsg;
        errMsg << "GrayScaleImagesFVList ***ERROR*** One of the elements in 'featureVectorList' is not
       of 'GrayScaleImagesFV' type. We can not recast this element"
             << " FileName[" << featureVector->ExampleFileName () << "]";
        cerr << endl << errMsg << endl << endl;
        throw KKException (errMsg);
      }
    }
  }
}
GrayScaleImagesFVList::~GrayScaleImagesFVList () [virtual]
Definition at line 327 of file GrayScaleImagesFV.cpp.
{
}
Member Function Documentation
void GrayScaleImagesFVList::AddQueue (GrayScaleImagesFVList & imagesToAdd)
Definition at line 390 of file GrayScaleImagesFV.cpp.
{
  FeatureVectorList::AddQueue (imagesToAdd);
} /* AddQueue */
GrayScaleImagesFVPtr GrayScaleImagesFVList::BackOfQueue ()
Definition at line 351 of file GrayScaleImagesFV.cpp.
References KKB::KKStr::Concat(), and KKB::KKException::KKException().
{
  if (size () < 1)
    return NULL;
  FeatureVectorPtr fv = back ();
  //if (strcmp (fv->UnderlyingClass (), "GrayScaleImagesFV") == 0)
  if (typeid (*fv) == typeid (GrayScaleImagesFV))
    return dynamic_cast<GrayScaleImagesFVPtr> (fv);
  KKStr errMsg = "GrayScaleImagesFVList::BackOfQueue () ***ERROR*** Entry at back of Queue
       is not a 'GrayScaleImagesFV' object.";
  cerr << endl << errMsg << endl << endl;
  throw KKException (errMsg);
} /* BackOfQueue */
GrayScaleImagesFVPtr GrayScaleImagesFVList::BinarySearchByName (const KKStr & _imageFileName) const
Definition at line 400 of file GrayScaleImagesFV.cpp.
{
  return (GrayScaleImagesFVPtr)
      FeatureVectorList::BinarySearchByName (_imageFileName);
} /* BinarySearchByName */
GrayScaleImagesFVListPtr GrayScaleImagesFVList::Duplicate (bool _owner) const [virtual]
Creates a duplicate of list using the same container.
Reimplemented from KKMLL::FeatureVectorList.
Definition at line 333 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFVList().
{
  return new GrayScaleImagesFVList (*this, _owner);
}
GrayScaleImagesFVListPtr GrayScaleImagesFVList::DuplicateListAndContents () const [virtual]
Creates a duplicate of list and also duplicates it contents.
Returns
Duplicated list with hard copy of its contents.
Reimplemented from KKMLL::FeatureVectorList.
Definition at line 563 of file GrayScaleImagesFV.cpp.
References IdxToPtr().
{
  GrayScaleImagesFVListPtr copyiedList = new
      GrayScaleImagesFVList (FileDesc (), true);
  for (kkint32 idx = 0; idx < QueueSize (); idx++)
  {
    GrayScaleImagesFVPtr curImage = (GrayScaleImagesFVPtr)
      IdxToPtr (idx);
    copyiedList->PushOnBack (new GrayScaleImagesFV (*curImage));
  }
  
  copyiedList->Version (Version ());
  return copyiedList;
} /* DuplicateListAndContents */
GrayScaleImagesFVListPtr GrayScaleImagesFVList::ExtractDuplicatesByRootImageFileName ()
Definition at line 671 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFVList().
{
  FeatureVectorListPtr duplicateFeatureVectorObjects =
      FeatureVectorList::ExtractDuplicatesByRootImageFileName
       ();
  GrayScaleImagesFVListPtr duplicateImageFeaturesObjects = new
      GrayScaleImagesFVList (*duplicateFeatureVectorObjects);
  duplicateFeatureVectorObjects->Owner (false);
  delete duplicateFeatureVectorObjects; duplicateFeatureVectorObjects = NULL;
  return duplicateImageFeaturesObjects;
} /* ExtractDuplicatesByRootImageFileName */
GrayScaleImagesFVListPtr GrayScaleImagesFVList::ExtractExamplesForAGivenClass (MLClassPtr _mlClass, kkint32 _maxToExtract = -1, float _minSize = -1.0f) const
Definition at line 685 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFVList().
{
  FeatureVectorListPtr featureVectorList =
      FeatureVectorList::ExtractExamplesForAGivenClass (_mlClass,
       _maxToExtract, _minSize);
  GrayScaleImagesFVListPtr imageFeaturesList = new
      GrayScaleImagesFVList (*featureVectorList);
  featureVectorList->Owner (false);
  delete featureVectorList; featureVectorList = NULL;
  return imageFeaturesList;
} /* ExtractExamplesForAGivenClass */
GrayScaleImagesFVPtr GrayScaleImagesFVList::IdxToPtr (kkint32 idx) const
Definition at line 342 of file GrayScaleImagesFV.cpp.
Referenced by DuplicateListAndContents().
{
  return (GrayScaleImagesFVPtr)FeatureVectorList::IdxToPtr
      (idx);
} /* IdxToPtr */
GrayScaleImagesFVPtr GrayScaleImagesFVList::LookUpByImageFileName (const KKStr & _imageFileName) const
Definition at line 419 of file GrayScaleImagesFV.cpp.
{
  return (GrayScaleImagesFVPtr)
      FeatureVectorList::LookUpByImageFileName (_imageFileName);
} /* LookUpByImageFileName */
GrayScaleImagesFVPtr GrayScaleImagesFVList::LookUpByRootName (const KKStr & _rootName)
Definition at line 409 of file GrayScaleImagesFV.cpp.
{
  return (GrayScaleImagesFVPtr)
      FeatureVectorList::LookUpByRootName (_rootName);
} /* LookUpByRootName */
GrayScaleImagesFVListPtr GrayScaleImagesFVList::ManufactureEmptyList (bool _owner) const [virtual]
Creates an instance of a Empty FeatureVectorList.
Reimplemented from KKMLL::FeatureVectorList.
Definition at line 427 of file GrayScaleImagesFV.cpp.
{
  return new GrayScaleImagesFVList (FileDesc (), _owner);
}
GrayScaleImagesFVListPtr GrayScaleImagesFVList::OrderUsingNamesFromAFile (const KKStr & fileName, RunLog & log)
Using list of ImageFileNames in a file('fileName') create a new GrayScaleImagesFVList instance with examples in order based off contents of file. If error occurs will return NULL.
Definition at line 435 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFVList().
{
  FeatureVectorListPtr examples =
      FeatureVectorList::OrderUsingNamesFromAFile (fileName, log);
  examples->Owner (false);
  GrayScaleImagesFVListPtr orderedImages = new
      GrayScaleImagesFVList (*examples);
  delete examples;
  return orderedImages;
} /* OrderUsingNamesFromAFile */
GrayScaleImagesFVPtr GrayScaleImagesFVList::PopFromBack () [virtual]
Removes the last element in the container and returns its pointer. If the container is empty will return NULL.
Reimplemented from KKB::KKQueue< FeatureVector >.
Definition at line 369 of file GrayScaleImagesFV.cpp.
References KKB::KKStr::Concat(), and KKB::KKException::KKException().
{
  if (size () < 1) return NULL;
  FeatureVectorPtr fv = back ();
  //if (strcmp (fv->UnderlyingClass (), "GrayScaleImagesFV") != 0)
  if (typeid (*fv) == typeid (GrayScaleImagesFV))
  {
    KKStr errMsg = "GrayScaleImagesFVList::PopFromBack () ***ERROR*** Entry at back of Queue
       is not a 'GrayScaleImagesFV' object.";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  return dynamic_cast<GrayScaleImagesFVPtr> (
      FeatureVectorList::PopFromBack ());
} /* PopFromBack */
void GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree (FactoryFVProducerPtr fvProducerFactory, const KKStr & rootDir, bool & successful, RunLog & log)
Definition at line 583 of file GrayScaleImagesFV.cpp.
References KKMLL::GrayScaleImagesFV::CentroidCol(), KKMLL::GrayScaleImagesFV::CentroidRow(), KKMLL::FeatureVectorProducer::ComputeFeatureVector(), KKB::KKStr::Concat(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVector::FeatureData(), KKB::ImageDirTree::ImageDirTree(), KKMLL::GrayScaleImagesFVList::iterator::iterator(), KKB::KKStr::KKStr(), KKB::ImageDirTree::LocateImage(), KKMLL::FactoryFVProducer::ManufactureInstance(), KKMLL::FeatureVector::MLClass(), KKMLL::GrayScaleImagesFV::NumOfEdgePixels(), KKMLL::GrayScaleImagesFVList::iterator::operator*(), KKMLL::GrayScaleImagesFVList::iterator::operator++(), KKMLL::FeatureVector::OrigSize(), KKB::osAddLastSlash(), KKB::Raster::Raster(), KKB::ImageDirTree::Size(), and KKMLL::FeatureVector::Version().
{
  log.Level (20) << "RecalcFeatureValuesFromImagesInDirTree RootDir[" << rootDir << "]." <<
      endl;
  successful = false;
  ImageDirTree fileDirectory (rootDir);
  if (QueueSize () < 1)
  {
    successful = true;
    return;
  }
  if (fileDirectory.Size () < 1)
  {
    log.Level (10) << "RecalcFeatureValuesFromImagesInDirTree No Image Files in[" << rootDir << "]" <
      < endl;
    return;
  }
  FeatureVectorProducerPtr fvProducer = fvProducerFactory->
      ManufactureInstance (log);
  KKStrConstPtr dirPath = NULL;
  iterator idx;
  GrayScaleImagesFVPtr example = NULL;
  for (idx = begin (); idx != end (); idx++)
  {
    example = *idx;
    dirPath = fileDirectory.LocateImage (example->ExampleFileName ());
    if (!dirPath)
    {
      log.Level (10) << "RecalcFeatureValuesFromImagesInDirTree Could not locate Image[" << example->
      ExampleFileName () << "] in Subdirectory Tree." << endl;
      return;
    }
    KKStr fullFileName (*dirPath);
    osAddLastSlash (fullFileName);
    fullFileName << example->ExampleFileName ();
    bool validFile;
    RasterPtr raster = new Raster (fullFileName, validFile);
    if (!validFile)
    {
      delete raster; raster = NULL;
      log.Level (-1) << "GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree ***ERROR***
       Unable to load image: " << fullFileName << endl << endl;
    }
    else
    {
      FeatureVectorPtr fv = fvProducer->ComputeFeatureVector (*raster,
      example->MLClass (), NULL, 1.0f, log);
      if (fv)
      {
        kkint32 x;
        kkint32 featureCount = Min (fv->NumOfFeatures (), example->
      NumOfFeatures ());
        for (x = 0; x < featureCount; ++x)
          example->FeatureData (x, fv->FeatureData (x));
        example->OrigSize (fv->OrigSize ());
        example->Version (fv->Version ());
        if (typeid(*fv) == typeid(GrayScaleImagesFV))
        {
          GrayScaleImagesFVPtr lfv = dynamic_cast<
      GrayScaleImagesFVPtr>(fv);
          example->CentroidCol (lfv->CentroidCol ());
          example->CentroidRow (lfv->CentroidRow ());
          example->NumOfEdgePixels (lfv->NumOfEdgePixels ());
        }
        delete fv;
        fv = NULL;
      }
      delete raster; raster = NULL;
    }
  }
  delete fvProducer;
  fvProducer = NULL;
} /* RecalcFeatureValuesFromImagesInDirTree */
GrayScaleImagesFVListPtr GrayScaleImagesFVList::StratifyAmoungstClasses (kkint32 numOfFolds, RunLog & log)
Definition at line 717 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFVList().
{
  MLClassListPtr classes = ExtractListOfClasses ();
  FeatureVectorListPtr stratifiedFeatureVectors =
      FeatureVectorList::StratifyAmoungstClasses (classes, -1,
      numOfFolds, log);
  GrayScaleImagesFVListPtr stratifiedImagefeatures = new
      GrayScaleImagesFVList (*stratifiedFeatureVectors);
  
  stratifiedFeatureVectors->Owner (false);
  delete stratifiedFeatureVectors; stratifiedFeatureVectors = NULL;
  delete classes; classes = NULL;
  return stratifiedImagefeatures;
} /* StratifyAmoungstClasses */
GrayScaleImagesFVListPtr GrayScaleImagesFVList::StratifyAmoungstClasses (MLClassListPtr mlClasses, kkint32 maxImagesPerClass, kkint32 numOfFolds, RunLog & log)
Definition at line 701 of file GrayScaleImagesFV.cpp.
References GrayScaleImagesFVList().
{
  FeatureVectorListPtr stratifiedFeatureVectors =
      FeatureVectorList::StratifyAmoungstClasses (mlClasses,
      maxImagesPerClass, numOfFolds, log);
  GrayScaleImagesFVListPtr stratifiedImagefeatures = new
      GrayScaleImagesFVList (*stratifiedFeatureVectors);
  stratifiedFeatureVectors->Owner (false);
  delete stratifiedFeatureVectors; stratifiedFeatureVectors = NULL;
  return stratifiedImagefeatures;
} /* StratifyAmoungstClasses */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFV.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFV.cpp