KKB::RasterList Class Reference
#include <Raster.h>
Public Member Functions
RasterList (bool owner)
RasterList (const RasterList &rasterList, bool _owner)
RasterPtr CreateSmoothedFrame ()
Additional Inherited Members
Detailed Description
Definition at line 1387 of file Raster.h.
Constructor & Destructor Documentation
KKB::RasterList::RasterList (bool owner) [inline]
Definition at line 1390 of file Raster.h.
References RasterList().
Referenced by RasterList(), and KKB::Raster::SplitImageIntoEqualParts().
                            :
        KKQueue<Raster> (owner)
        {}
KKB::RasterList::RasterList (const RasterList & rasterList, bool _owner) [inline]
Definition at line 1400 of file Raster.h.
References RasterList().
Referenced by RasterList().
                :
        KKQueue<Raster> (rasterList, _owner)
        {}
Member Function Documentation
RasterPtr RasterList::CreateSmoothedFrame ()
Definition at line 8950 of file Raster.cpp.
References KKB::Raster::AllocateARasterInstance(), KKB::Raster::BlueArea(), KKB::Raster::Color(), KKB::Raster::GreenArea(), KKB::Raster::Height(), KKB::Raster::RedArea(), and KKB::Raster::Width().
{
  if (QueueSize () < 1)
    return NULL;
  kkint32 x;
  RasterPtr firstRaster = IdxToPtr (0);
  kkint32 height = firstRaster->Height ();
  kkint32 width = firstRaster->Height ();
  kkint32 totPixels = height * width;
  kkuint32* totGreenArea = new kkuint32[totPixels];
  memset (totGreenArea, 0, totPixels * sizeof (kkuint32));
  kkint32 idx = 0;
  kkint32 rastersAdded = 0;
  for (idx = 0; idx < QueueSize (); idx++)
  {
    RasterPtr raster = IdxToPtr (idx);
    if ((raster->Height () != height) ||
         (raster->Width () != width)
        )
    {
      continue;
    }
    if (raster->Color ())
    {
      uchar* redArea = raster->RedArea ();
      uchar* greenArea = raster->GreenArea ();
      uchar* blueArea = raster->BlueArea ();
      for (x = 0; x < totPixels; x++)
      {
        totGreenArea[x] += (kkuint32)((float)redArea[x] * 0.39f +
                                  (float)greenArea[x] * 0.59f +
                                  (float)blueArea[x] * 0.11f +
                                  0.5f
                                 );
      }
    }
    else
    {
      uchar* greenArea = raster->GreenArea ();
      for (x = 0; x < totPixels; x++)
        totGreenArea[x] += greenArea[x];
    }
    rastersAdded++;
  }
  RasterPtr smoothedRaster = firstRaster->AllocateARasterInstance (height,
       width, false);
  uchar* newGreenArea = smoothedRaster->GreenArea ();
  for (x = 0; x < totPixels; x++)
    newGreenArea[x] = (uchar) (totGreenArea[x] / rastersAdded);
  delete[] totGreenArea;
  return smoothedRaster;
} /* CreateSmoothedFrame */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Raster.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Raster.cpp