KKMLL::FileDesc Class Reference
Provides a detailed description of the attributes of a dataset.
#include <FileDesc.h>
Public Types
typedef FileDesc *const FileDescConstPtr
typedef FileDesc * FileDescPtr
Public Member Functions
FileDesc ()
void AddAAttribute (const KKB::KKStr &_name, KKMLL::AttributeType _type, bool &alreadyExists)
void AddAAttribute (const KKMLL::Attribute &attribute)
void AddANominalValue (kkint32 fieldNum, const KKStr &nominalValue, bool &alreadyExist, RunLog &log)
void AddANominalValue (const KKStr &nominalValue, bool &alreadyExist, RunLog &log)
void AddANominalValue (const KKStr &attributeName, const KKStr &nominalValue, bool &alreadyExist, RunLog &log)
void AddAttributes (const KKMLL::AttributeList &attributes)
void AddClasses (const MLClassList &classesToAdd)
bool AllFieldsAreNumeric () const
Allows the user to quickly determine if there are no nominal fields.
const KKMLL::AttributeList & Attributes () const
const AttributeTypeVector & AttributeVector () const
kkint32 Cardinality (kkint32 fieldNum) const
const VectorInt32 & CardinalityVector () const
const MLClassList & Classes () const
const KKStr & ClassNameAttribute () const
void ClassNameAttribute (const KKStr &_classNameAttribute)
const KKMLL::AttributePtr * CreateAAttributeTable () const
AttributeTypeVector CreateAttributeTypeTable () const
VectorInt32 CreateCardinalityTable () const
void DisplayAttributeMappings ()
const KKStr & FieldName (kkint32 fieldNum) const
const KKStr & FileName () const
void FileName (const KKStr &_fileName)
const KKMLL::Attribute & GetAAttribute (kkint32 fieldNum) const
kkint32 GetFieldNumFromAttributeName (const KKStr &attributeName) const
MLClassPtr GetMLClassPtr (const KKStr &className)
const KKStr & GetNominalValue (kkint32 fieldNum, kkint32 code) const
const KKMLL::AttributePtr LookUpByName (const KKStr &attributeName) const
MLClassPtr LookUpMLClassByName (const KKStr &className)
kkint32 LookUpNominalCode (kkint32 fieldNum, const KKStr &nominalValue) const
MLClassPtr LookUpUnKnownMLClass ()
kkint32 MemoryConsumedEstimated () const
kkuint32 NumOfFields () const
bool operator!= (const FileDesc &rightSize) const
Returns true if file description on the right size is NOT identical.
bool operator== (const FileDesc &rightSize) const
Returns true if file description on the right size is identical.
void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
bool SameExceptForSymbolicData (const FileDesc &otherFd, RunLog &log) const
kkint32 SparseMinFeatureNum () const
void SparseMinFeatureNum (kkint32 _sparseMinFeatureNum)
KKMLL::AttributeType Type (kkint32 fieldNum) const
KKStr TypeStr (kkint32 fieldNum) const
kkint16 Version () const
void Version (kkint16 _version)
void WriteXML (const KKStr &varName, std::ostream &o) const
Static Public Member Functions
static void FinalCleanUp ()
Clean up function, call just before exiting the application.
static bool FinalCleanUpRanAlready ()
static FileDescPtr GetExistingFileDesc (FileDescPtr fileDesc)
Returns a pointer to an existing instance of 'fileDesc' if it exists, otherwise will use one being passed in.
static FileDescPtr MergeSymbolicFields (const FileDesc &left, const FileDesc &right, RunLog &log)
Merges the Symbolic fields of two different 'FileDesc' instances producing a new instance of 'FileDesc'.
static FileDescPtr NewContinuousDataOnly (VectorKKStr &_fieldNames)
Creates a simple FileDesc that consists of continuous data only.
Protected Member Functions
~FileDesc ()
Friends
class KKQueue< FileDesc >
Detailed Description
Provides a detailed description of the attributes of a dataset.
Author
Kurt Kramer
Describes the different fields of a dataset. There will be one instance of this class for each type of Dataset that you have in an application. From this object you can get information such as number of attributes, Attribute types, weather they are nominal, continuous. If nominal what are the accepted values. *
Never delete an instance of a FileDesc object.
Only one FileDesc object can exist for any Dataset. Example the Forest-Cover dataset. You can split the data into many files and manage them separately but you will only have one instance of a FileDesc object that they will all refer to. See `GetExistingFileDesc` method below. You would initially create an instance of FileDesc and then use `GetExistingFileDesc` to make sure that it is unique. This typically happens in the FeatureFileIO derived classes.
See also
GetExistingFileDesc
FeatureVectorList
FeatureFileIo
Definition at line 72 of file FileDesc.h.
Member Typedef Documentation
typedef FileDesc* const KKMLL::FileDesc::FileDescConstPtr
Definition at line 77 of file FileDesc.h.
typedef FileDesc* KKMLL::FileDesc::FileDescPtr
Definition at line 75 of file FileDesc.h.
Constructor & Destructor Documentation
FileDesc::FileDesc ()
Definition at line 81 of file FileDesc.cpp.
References FileDesc().
Referenced by KKMLL::FeatureEncoder2::CreateEncodedFileDesc(), KKMLL::FeatureEncoder::CreateEncodedFileDesc(), KKMLL::GrayScaleImagesFVProducer::DefineFileDescStatic(), FileDesc(), KKMLL::FeatureFileIODstWeb::GetFileDesc(), KKMLL::FeatureFileIOColumn::GetFileDesc(), KKMLL::FeatureFileIOC45::GetFileDesc(), KKMLL::FeatureFileIOUCI::GetFileDesc(), KKMLL::FeatureFileIOSparse::GetFileDesc(), MergeSymbolicFields(), NewContinuousDataOnly(), and KKMLL::XmlElementFileDesc::XmlElementFileDesc().
                   :
  attributes (true),
  cardinalityVector (),
  classes (),
  curAttribute (NULL),
  sparseMinFeatureNum (0),
  version (0)
{
}
FileDesc::~FileDesc () [protected]
Definition at line 96 of file FileDesc.cpp.
{
  kkint32 ZED = 7887;
}
Member Function Documentation
void FileDesc::AddAAttribute (const KKB::KKStr & _name, KKMLL::AttributeType _type, bool & alreadyExists)
Definition at line 169 of file FileDesc.cpp.
References KKMLL::Numeric, and KKMLL::Attribute::Type().
Referenced by KKMLL::FeatureEncoder2::CreateEncodedFileDesc(), KKMLL::FeatureEncoder::CreateEncodedFileDesc(), KKMLL::GrayScaleImagesFVProducer::DefineFileDescStatic(), KKMLL::FeatureFileIOColumn::GetFileDesc(), KKMLL::FeatureFileIOUCI::GetFileDesc(), KKMLL::FeatureFileIOSparse::GetFileDesc(), and NewContinuousDataOnly().
{
  alreadyExists = false;
  AttributePtr existingAttribute = attributes.LookUpByName (_name);
  if (existingAttribute)
  {
    // This is a very bad error, it should not be able to happen
    alreadyExists = true;
    return;
  }
  curAttribute = new Attribute (_name, _type, attributes.QueueSize ());
  attributes.PushOnBack (curAttribute);
  attributeVector.push_back (curAttribute->Type ());
  kkint32 card = 0;
  if (curAttribute->Type () == AttributeType::Numeric)
     card = INT_MAX;
  cardinalityVector.push_back (card);
} /* AddAAttribute */
void FileDesc::AddAAttribute (const KKMLL::Attribute & attribute)
Definition at line 140 of file FileDesc.cpp.
References KKMLL::Numeric, and KKMLL::Attribute::Type().
Referenced by MergeSymbolicFields().
{
  attributes.PushOnBack (new Attribute (attribute));
  attributeVector.push_back (attribute.Type ());
  kkint32 card = 0;
  if (attribute.Type () == AttributeType::Numeric)
     card = 999999999;
  cardinalityVector.push_back (card);
} /* AddAAttribute */
void FileDesc::AddANominalValue (kkint32 fieldNum, const KKStr & nominalValue, bool & alreadyExist, RunLog & log)
Definition at line 220 of file FileDesc.cpp.
References KKMLL::Nominal, KKMLL::Symbolic, and Type().
Referenced by MergeSymbolicFields().
{
  ValidateFieldNum (fieldNum, "AddANominalValue");
  AttributeType t = Type (fieldNum);
  if ((t == AttributeType::Nominal) ||
       (t == AttributeType::Symbolic)
      )
  {
    attributes[fieldNum].AddANominalValue (nominalValue, alreadyExist);
    if (!alreadyExist)
      cardinalityVector[fieldNum]++;
  }
} /* AddANominalValue */
void FileDesc::AddANominalValue (const KKStr & nominalValue, bool & alreadyExist, RunLog & log)
Definition at line 242 of file FileDesc.cpp.
References KKMLL::Attribute::AddANominalValue(), KKB::KKStr::Concat(), and KKB::KKException::KKException().
Referenced by AddANominalValue(), and KKMLL::FeatureFileIODstWeb::GetFileDesc().
{
  if (!curAttribute)
  {
    // This should never happen, means that there has not been a nominal feature added yet.
    KKStr errMsg = "FileDesc::AddANominalValue ***ERROR*** No Current Attribute Set.";
    log.Level (-1) << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  
  alreadyExist = false;
  curAttribute->AddANominalValue (nominalValue, alreadyExist);
  if (!alreadyExist)
    cardinalityVector[curAttribute->FieldNum ()]++;
} /* AddANominalValue */
void FileDesc::AddANominalValue (const KKStr & attributeName, const KKStr & nominalValue, bool & alreadyExist, RunLog & log)
Definition at line 264 of file FileDesc.cpp.
References AddANominalValue(), KKB::KKStr::Concat(), KKB::KKException::KKException(), and KKB::KKStr::KKStr().
{
  curAttribute = attributes.LookUpByName (attributeName);
  if (!curAttribute)
  {
    KKStr errMsg (128);
    errMsg << "FileDesc::AddANominalValue ***ERROR***, Invalid Attribute[" << attributeName << "].";
    log.Level (-1) << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  AddANominalValue (nominalValue, alreadyExist, log);
} /* AddANominalValue */
void FileDesc::AddAttributes (const KKMLL::AttributeList & attributes)
Definition at line 156 of file FileDesc.cpp.
{
  AttributeList::const_iterator idx;
  for (idx = attributes.begin (); idx != attributes.end (); ++idx)
  {
    AddAAttribute (**idx);
  }
}
void FileDesc::AddClasses (const MLClassList & classesToAdd)
Definition at line 196 of file FileDesc.cpp.
Referenced by KKMLL::FeatureFileIOC45::GetFileDesc(), and ReadXML().
{
  MLClassList::const_iterator idx;
  for (idx = classesToAdd.begin (); idx != classesToAdd.end (); idx++)
  {
    MLClassPtr ic = *idx;
    if (classes.PtrToIdx (ic) < 0)
      classes.AddMLClass (ic);
  }
} /* AddClasses */
bool FileDesc::AllFieldsAreNumeric () const
Allows the user to quickly determine if there are no nominal fields.
Example use is in CrossValidation application, by using this method it can quickly determine if it is worth while using encoding.
Definition at line 706 of file FileDesc.cpp.
References KKMLL::Ignore, KKMLL::Numeric, NumOfFields(), and Type().
Referenced by KKMLL::FeatureVectorList::AllFieldsAreNumeric().
{
  for (kkint32 fieldNum = 0; fieldNum < (kkint32)NumOfFields (); fieldNum++)
  {
    AttributeType t = Type (fieldNum);
    if ((t != AttributeType::Numeric) && (t !=
      AttributeType::Ignore))
      return false;
  }
  
  return true;
} /* AllFieldsAreNumeric */
const KKMLL::AttributeList& KKMLL::FileDesc::Attributes () const [inline]
Definition at line 114 of file FileDesc.h.
{return attributes;};
const AttributeTypeVector& KKMLL::FileDesc::AttributeVector () const [inline]
Definition at line 115 of file FileDesc.h.
Referenced by KKMLL::FeatureNumList::AllFeatures(), and KKMLL::FeatureEncoder2::FeatureEncoder2().
{return attributeVector;};
kkint32 FileDesc::Cardinality (kkint32 fieldNum) const
Definition at line 341 of file FileDesc.cpp.
References KKMLL::Attribute::Cardinality(), KKB::KKStr::Concat(), KKMLL::Ignore, KKB::KKException::KKException(), KKMLL::Nominal, KKMLL::Numeric, KKB::operator<<(), KKMLL::Symbolic, and KKMLL::Attribute::Type().
Referenced by KKMLL::FeatureVectorList::FeatureCardinality(), MergeSymbolicFields(), KKMLL::ModelParam::NumOfFeaturesAfterEncoding(), KKMLL::SVMparam::NumOfFeaturesAfterEncoding(), and KKMLL::FeatureVectorList::ReSyncSymbolicData().
{
  ValidateFieldNum (fieldNum, "Type");
  AttributePtr a = attributes.IdxToPtr (fieldNum);
  if (!a)
  {
    KKStr errMsg;
    errMsg << "FileDesc::Cardinality ***ERROR*** Could not locate attribute[" << fieldNum << "]";
    cerr << errMsg;
    throw KKException (errMsg);
  }
  switch (a->Type ())
  {
  case AttributeType::Ignore: return a->Cardinality ();
  case AttributeType::Nominal: return a->Cardinality ();
  case AttributeType::Numeric: return INT_MAX;
  case AttributeType::Symbolic: return a->Cardinality ();
  
  default: return INT_MAX;
  }
  return INT_MAX;
} /* Cardinality */
const VectorInt32& KKMLL::FileDesc::CardinalityVector () const [inline]
Definition at line 116 of file FileDesc.h.
Referenced by KKMLL::FeatureEncoder2::FeatureEncoder2().
{return cardinalityVector;}
const MLClassList& KKMLL::FileDesc::Classes () const [inline]
Definition at line 117 of file FileDesc.h.
{return classes;}
const KKStr& KKMLL::FileDesc::ClassNameAttribute () const [inline]
ClassNameAttribute added to support dstWeb data files.
Definition at line 118 of file FileDesc.h.
Referenced by KKMLL::FeatureFileIODstWeb::LoadFile().
void KKMLL::FileDesc::ClassNameAttribute (const KKStr & _classNameAttribute) [inline]
Definition at line 123 of file FileDesc.h.
References KKB::KKStr::operator=().
{classNameAttribute = _classNameAttribute;}
const AttributePtr * FileDesc::CreateAAttributeTable () const
Caller will be responsible for deleting
Definition at line 408 of file FileDesc.cpp.
Referenced by KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOC45::LoadFile(), KKMLL::FeatureFileIORoberts::SaveFile(), and KKMLL::FeatureFileIOC45::SaveFile().
{
  AttributePtr* table = new AttributePtr[attributes.
      QueueSize ()];
  for (kkint32 x = 0; x < attributes.QueueSize (); x++)
    table[x] = attributes.IdxToPtr (x);
  
  return table;
} /* CreateAAttributeTable */
AttributeTypeVector FileDesc::CreateAttributeTypeTable () const
Definition at line 419 of file FileDesc.cpp.
Referenced by KKMLL::FeatureVectorList::CreateAttributeTypeTable(), KKMLL::NormalizationParms::NormalizationParms(), KKMLL::NormalizationParms::ReadXML(), KKMLL::SVMModel::ReadXML(), and KKMLL::SVMModel::SVMModel().
{
  kkint32 x;
  AttributeTypeVector attributeTypes (attributes.size (),
      AttributeType::NULLAttribute);
  for (x = 0; x < attributes.QueueSize (); x++)
    attributeTypes[x] = attributes[x].Type ();
  return attributeTypes;
} /* CreateAttributeTypeTable () */
VectorInt32 FileDesc::CreateCardinalityTable () const
Definition at line 430 of file FileDesc.cpp.
Referenced by KKMLL::FeatureVectorList::CreateCardinalityTable(), KKMLL::SVMModel::ReadXML(), and KKMLL::SVMModel::SVMModel().
{
  kkint32 x;
  VectorInt32 cardinalityTable (attributes.QueueSize (), 0);
  for (x = 0; x < attributes.QueueSize (); x++)
    cardinalityTable[x] = attributes[x].Cardinality ();
  return cardinalityTable;
} /* CreateCardinalityTable */
void FileDesc::DisplayAttributeMappings ()
Definition at line 617 of file FileDesc.cpp.
References KKMLL::Attribute::Cardinality(), KKMLL::Attribute::GetNominalCode(), KKMLL::Attribute::GetNominalValue(), KKMLL::Ignore, KKMLL::Nominal, KKMLL::NULLAttribute, KKMLL::Numeric, NumOfFields(), KKMLL::Ordinal, KKMLL::Symbolic, and KKMLL::Attribute::Type().
{
  kkuint32 i;
  kkint32 j;
  AttributePtr a;
  for (i = 0; i < NumOfFields(); i++)
  {
    a = attributes.IdxToPtr (i);
    cout << i << ": ";
    if (a->Type() == AttributeType::Nominal)
    {
      for (j = 0; j<a->Cardinality (); j++)
      {
        if (j != a->GetNominalCode(a->GetNominalValue(j)))
        {
          cout << " Code does not match ";
        }
        cout << j << ":" << a->GetNominalValue(j) << " ";
      }
    }
    else if (a->Type() == AttributeType::Symbolic)
    {
      cout << "Symbolic (";
      for (j = 0; j<a->Cardinality (); j++)
      {
        if (j != a->GetNominalCode (a->GetNominalValue(j)))
        {
          cout << " Code does not match ";
        }
        cout << j << ":" << a->GetNominalValue(j) << " ";
      }
      cout << ")";
    }
    
    else if (a->Type() == AttributeType::Ignore)
    {
      cout << "ignore";
    }
    else if (a->Type() == AttributeType::Numeric)
    {
      cout << "numeric";
    }
    else if (a->Type() == AttributeType::Ordinal)
    {
      cout << "ordinal";
    }
    else if (a->Type() == AttributeType::NULLAttribute)
    {
      cout << "NULL";
    }
    cout << endl;
  }
} /* DisplayAttributeMappings */
const KKStr & FileDesc::FieldName (kkint32 fieldNum) const
Definition at line 387 of file FileDesc.cpp.
Referenced by KKMLL::FeatureEncoder2::CreateEncodedFileDesc(), KKMLL::FeatureEncoder::CreateEncodedFileDesc(), KKMLL::FeatureVectorProducer::FeatureName(), KKMLL::FeatureVectorList::FieldName(), MergeSymbolicFields(), KKMLL::FeatureVectorList::ReSyncSymbolicData(), and SameExceptForSymbolicData().
{
  ValidateFieldNum (fieldNum, "FieldName");
  return attributes[fieldNum].Name ();
} /* FieldName */
const KKStr& KKMLL::FileDesc::FileName () const [inline]
Definition at line 119 of file FileDesc.h.
Referenced by SameExceptForSymbolicData().
{return fileName;}
void KKMLL::FileDesc::FileName (const KKStr & _fileName) [inline]
Definition at line 124 of file FileDesc.h.
References KKB::KKStr::operator=().
{fileName = _fileName;}
void FileDesc::FinalCleanUp () [static]
Clean up function, call just before exiting the application.
Before you terminate your application you should call this method. It will clean up the FileDesc objects that were created during the runtime of your application.
Definition at line 57 of file FileDesc.cpp.
References KKB::GoalKeeper::Destroy(), KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by KKMLL::MLClass::FinalCleanUp().
{
  if (finalCleanUpRanAlready)
    return;
  FileDesc::CreateBlocker ();
  blocker->StartBlock ();
  if (!finalCleanUpRanAlready)
  {
    if (exisitingDescriptions)
    {
      delete exisitingDescriptions;
      exisitingDescriptions = NULL;
    }
    finalCleanUpRanAlready = true;
  }
  blocker->EndBlock ();
  GoalKeeper::Destroy (blocker); blocker = NULL;
} /* FinalCleanUp */
static bool KKMLL::FileDesc::FinalCleanUpRanAlready () [inline], [static]
Definition at line 88 of file FileDesc.h.
Referenced by KKMLL::MLClass::FinalCleanUp().
{return finalCleanUpRanAlready;}
const Attribute & FileDesc::GetAAttribute (kkint32 fieldNum) const
Definition at line 210 of file FileDesc.cpp.
Referenced by KKMLL::FeatureEncoder::FeatureEncoder(), and MergeSymbolicFields().
{
  ValidateFieldNum (fieldNum, "GetAAttribute");
  const Attribute& a = attributes [fieldNum];
  return a;
} /* GetAAttribute */
FileDescPtr FileDesc::GetExistingFileDesc (FileDescPtr fileDesc) [static]
Returns a pointer to an existing instance of 'fileDesc' if it exists, otherwise will use one being passed in.
First looks to see if a the same FileDesc is already in the existing list
in that case will return back the same pointer.
> Second Will look for a existing FileDesc that is the same as the 'fileDesc'
  being passed in.
  if one is found them
    fileDesc is deleted
    exiting one will be returned.
  else
    fileDesc will be added to existinList (exisitingDescriptions) and returned.
    and returned.
Parameters
in fileDesc Pointer to a FileDesc object that you want to look and see if one that is identical already exists.
Returns
pointer to the 'FileDesc' instance that the caller should be using.
Definition at line 555 of file FileDesc.cpp.
References KKB::KKStr::Concat(), KKB::GoalKeeper::EndBlock(), KKMLL::FileDescList::FileDescList(), KKB::KKException::KKException(), and KKB::GoalKeeper::StartBlock().
Referenced by KKMLL::FeatureEncoder2::CreateEncodedFileDesc(), KKMLL::GrayScaleImagesFVProducer::DefineFileDescStatic(), KKMLL::FeatureVectorProducer::FileDesc(), KKMLL::FeatureFileIOC45::LoadFeatureFile(), KKMLL::FeatureFileIO::LoadFeatureFile(), MergeSymbolicFields(), NewContinuousDataOnly(), and KKMLL::XmlElementFileDesc::XmlElementFileDesc().
{
  if (fileDesc == NULL)
  {
    KKStr errMsg = "FileDesc::GetExistingFileDesc ***ERROR*** (fileDesc == NULL).";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  FileDescPtr result = NULL;
  CreateBlocker ();
  blocker->StartBlock ();
  if (!exisitingDescriptions)
  {
    exisitingDescriptions = new FileDescList (true);
    exisitingDescriptions->PushOnBack (fileDesc);
    result = fileDesc;
    finalCleanUpRanAlready = false;
    atexit (FileDesc::FinalCleanUp);
  }
  else
  {
    for (auto existingFileDesc: *exisitingDescriptions)
    {
      if (existingFileDesc == fileDesc)
      {
        result = existingFileDesc;
        break;
      }
      else if (existingFileDesc == NULL)
      {
        continue;
      }
      else if ((*existingFileDesc) == (*fileDesc))
      {
        // Looks like we already have a compatible "FileDesc" instance.
        // In this case this is the one the user will want.
        delete fileDesc;
        result = existingFileDesc;
        break;
      }
    }
    if (!result)
    {
      exisitingDescriptions->PushOnBack (fileDesc);
      result = fileDesc;
    }
  }
  blocker->EndBlock ();
  return result;
} /* GetExistingFileDesc */
kkint32 FileDesc::GetFieldNumFromAttributeName (const KKStr & attributeName) const
Definition at line 690 of file FileDesc.cpp.
References KKMLL::Attribute::FieldNum().
Referenced by KKMLL::FeatureFileIODstWeb::LoadFile().
{
  AttributePtr a = attributes.LookUpByName (attributeName);
  if (!a)
    return -1;
  else
    return a->FieldNum ();
} /* GetFieldNumFromAttributeName */
MLClassPtr FileDesc::GetMLClassPtr (const KKStr & className)
Definition at line 298 of file FileDesc.cpp.
{
  return classes.GetMLClassPtr (className);
}
const KKStr & FileDesc::GetNominalValue (kkint32 fieldNum, kkint32 code) const
Definition at line 395 of file FileDesc.cpp.
Referenced by KKMLL::FeatureEncoder2::CreateEncodedFileDesc(), KKMLL::FeatureEncoder::CreateEncodedFileDesc(), MergeSymbolicFields(), and KKMLL::FeatureVectorList::ReSyncSymbolicData().
{
  ValidateFieldNum (fieldNum, "GetNominalValue");
  return attributes[fieldNum].GetNominalValue (code);
} /* GetNominalValue */
const AttributePtr FileDesc::LookUpByName (const KKStr & attributeName) const
Definition at line 682 of file FileDesc.cpp.
{
  return attributes.LookUpByName (attributeName);
} /* LookUpByName */
MLClassPtr FileDesc::LookUpMLClassByName (const KKStr & className)
Definition at line 284 of file FileDesc.cpp.
Referenced by KKMLL::FeatureFileIOC45::LoadFile().
{
  return classes.LookUpByName (className);
}
kkint32 FileDesc::LookUpNominalCode (kkint32 fieldNum, const KKStr & nominalValue) const
Definition at line 321 of file FileDesc.cpp.
References KKMLL::Attribute::GetNominalCode(), KKMLL::Nominal, KKMLL::Symbolic, and KKMLL::Attribute::Type().
Referenced by MergeSymbolicFields(), and KKMLL::FeatureVectorList::ReSyncSymbolicData().
{
  ValidateFieldNum (fieldNum, "LookUpNominalCode");
  const Attribute& a = attributes[fieldNum];
  if ((a.Type () != AttributeType::Nominal) &&
       (a.Type () != AttributeType::Symbolic)
      )
  {
    return -1;
  }
  return a.GetNominalCode (nominalValue);
} /* LookUpNominalCode */
MLClassPtr FileDesc::LookUpUnKnownMLClass ()
Definition at line 291 of file FileDesc.cpp.
Referenced by KKMLL::FeatureFileIOC45::LoadFile().
{
  return classes.GetUnKnownClass ();
}
kkint32 FileDesc::MemoryConsumedEstimated () const
Definition at line 102 of file FileDesc.cpp.
{
  kkint32 memoryConsumedEstimated = sizeof (FileDesc) +
         attributes.MemoryConsumedEstimated () +
         sizeof (AttributeType) * attributeVector.size () +
         sizeof (kkint32) * cardinalityVector.size () +
         classes.MemoryConsumedEstimated () +
         classNameAttribute.MemoryConsumedEstimated ();
  return memoryConsumedEstimated;
}
FileDescPtr FileDesc::MergeSymbolicFields (const FileDesc & left, const FileDesc & right, RunLog & log) [static]
Merges the Symbolic fields of two different 'FileDesc' instances producing a new instance of 'FileDesc'.
This method will only work if both instances have the same number of fields, their names must be the same(NOT case sensitive), and each field in both instances must be the same type. If all these conditions are not 'true' will return NULL. The fields that are of 'Symbolic' will have their values merged together.
See also
KKMLL:Attribute
Definition at line 723 of file FileDesc.cpp.
References AddAAttribute(), AddANominalValue(), Cardinality(), KKB::KKStr::Concat(), FieldName(), FileDesc(), GetAAttribute(), GetExistingFileDesc(), GetNominalValue(), LookUpNominalCode(), NumOfFields(), KKB::KKStr::operator!=(), SameExceptForSymbolicData(), KKMLL::Symbolic, and Type().
Referenced by KKMLL::FeatureVectorList::SynchronizeSymbolicData().
{
  if (!left.SameExceptForSymbolicData (right, log))
  {
    log.Level (-1) << endl
                   << "FileDesc::MergeSymbolicFields There are more differences between file descriptions
       besides symbolic data." << endl
                   << " File[" << left.fileName << "] File[" << right.fileName << "]" <<
      endl
                   << endl;
    return NULL;
  }
  FileDescPtr f = new FileDesc ();
  kkint32 numOfFields = left.NumOfFields ();
  kkint32 fieldNum = 0;
  for (fieldNum = 0; fieldNum < numOfFields; fieldNum++)
  {
    const KKStr& lName = left.FieldName (fieldNum);
    const KKStr& rName = right.FieldName (fieldNum);
    if (lName != rName)
    {
      log.Level (-1) << endl
                     << "FileDesc::MergeSymbolicFields Field Name mis-match" <<
      endl
                     << " File[" << left.fileName << "] Name[" << lName << "] File[" << right.
      fileName << "] Name[" << rName << "]" << endl
                     << endl;
      return NULL;
    }
    AttributeType lType = left.Type (fieldNum);
    AttributeType rType = right.Type (fieldNum);
    if (lType != rType)
    {
      log.Level (-1) << endl
                     << "FileDesc::MergeSymbolicFields Field Type mis-match" <<
      endl
                     << " File[" << left.fileName << "] Name[" << lName << "] File[" << right.
      fileName << "] Name[" << rName << "]" << endl
                     << endl;
      return NULL;
    }
    f->AddAAttribute (left.GetAAttribute (fieldNum));
    if (lType != AttributeType::Symbolic)
    {
      continue;
    }
    // We can merge in Nominal Values for this field.
    kkint32 z;
    for (z = 0; z < right.Cardinality (fieldNum); z++)
    {
      const KKStr& rightNomName = right.GetNominalValue (fieldNum, z);
      kkint32 lCode = f->LookUpNominalCode (fieldNum, rightNomName);
      if (lCode < 0)
      {
        bool alreadyExists = false;
        f->AddANominalValue (fieldNum, rightNomName, alreadyExists, log);
        lCode = f->LookUpNominalCode (fieldNum, rightNomName);
      }
    }
  }
  return GetExistingFileDesc (f);
} /* MergeSymbolicFields */
FileDescPtr FileDesc::NewContinuousDataOnly (VectorKKStr & _fieldNames) [static]
Creates a simple FileDesc that consists of continuous data only.
Creates a file description that will consist of continuous fields only. The vector '_fieldNames' will provide the list of field names.
Parameters
in _log Logging file to use.
in _fieldNames Name of fields; one entry for each field.
Definition at line 116 of file FileDesc.cpp.
References AddAAttribute(), KKB::KKStr::Concat(), FileDesc(), GetExistingFileDesc(), KKMLL::Numeric, and KKB::StrFormatInt().
Referenced by KKMLL::FeatureEncoder::FeatureEncoder(), and KKMLL::FeatureEncoder2::FeatureEncoder2().
{
  bool alreadyExists = false;
  FileDescPtr newFileDesc = new FileDesc ();
  for (kkint32 fieldNum = 0; fieldNum < (kkint32)_fieldNames.size (); fieldNum++)
  {
    kkint32 seqNum = 0;
    do
    {
      KKStr fieldName = _fieldNames[fieldNum];
      if (seqNum > 0)
        fieldName << "_" << StrFormatInt (seqNum, "000");
      newFileDesc->AddAAttribute (fieldName, AttributeType::Numeric,
      alreadyExists);
      seqNum++;
    }
      while (alreadyExists);
  }
  return GetExistingFileDesc (newFileDesc);
} /* NewContinuousDataOnly */
kkuint32 KKMLL::FileDesc::NumOfFields () const [inline]
Definition at line 197 of file FileDesc.h.
Referenced by KKMLL::FeatureNumList::AllFeatures(), KKMLL::FeatureNumList::AllFeaturesSelected(), AllFieldsAreNumeric(), DisplayAttributeMappings(), KKMLL::FeatureVectorProducer::FeatureCount(), KKMLL::FeatureVectorProducer::FeatureName(), KKMLL::FeatureNumList::FeatureNumList(), KKMLL::FeatureVectorList::FeatureVectorList(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOColumn::LoadFile(), KKMLL::FeatureFileIOUCI::LoadFile(), KKMLL::FeatureFileIOC45::LoadFile(), KKMLL::FeatureFileIOSparse::LoadFile(), MergeSymbolicFields(), KKMLL::FeatureEncoder2::NumEncodedFeatures(), KKMLL::FeatureVectorList::ResetFileDesc(), KKMLL::FeatureVectorList::ReSyncSymbolicData(), SameExceptForSymbolicData(), and KKMLL::FeatureNumList::ToHexString().
{return (kkuint32)attributes.size ();}
bool FileDesc::operator!= (const FileDesc & rightSize) const
Returns true if file description on the right size is NOT identical.
If both FileDesc instances have different number of fields, or any one of the fields has a different name(NOT case sensitive), or one of the fields is of a different type.
Definition at line 456 of file FileDesc.cpp.
{
  if ((NumOfFields () != rightSide.NumOfFields ()) ||
       (Version () != rightSide.Version ()) ||
       (attributes != rightSide.attributes)
      )
    return true;
  return false;
} /* operator== */
bool FileDesc::operator== (const FileDesc & rightSize) const
Returns true if file description on the right size is identical.
Both FileDesc instances must have the same number of fields, the fields must have the same names(NOT case sensitive), and the fields must have matching types(ex numerical, ordinal, etc).
Definition at line 443 of file FileDesc.cpp.
Referenced by KKMLL::FeatureFileIO::FeatureDataReSink().
{
  if ((NumOfFields () != rightSide.NumOfFields ()) ||
       (Version () != rightSide.Version ()) ||
       (attributes != rightSide.attributes)
      )
    return false;
  return true;
} /* operator== */
void FileDesc::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 800 of file FileDesc.cpp.
References AddClasses(), KKB::KKStr::Concat(), KKB::KKStr::EqualIgnoreCase(), KKB::XmlStream::GetNextToken(), KKB::XmlElement::SectionName(), SparseMinFeatureNum(), KKB::XmlToken::tokElement, KKB::XmlToken::TokenType(), KKMLL::XmlElementMLClassNameList::Value(), KKB::XmlElement::VarName(), and Version().
Referenced by KKMLL::XmlElementFileDesc::XmlElementFileDesc().
{
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (t->TokenType () == XmlToken::TokenTypes::tokElement)
    {
      XmlElementPtr e = dynamic_cast<XmlElementPtr> (t);
      const KKStr& className = e->SectionName ();
      const KKStr& varName = e->VarName ();
      if (varName.EqualIgnoreCase ("FileName"))
      {
        XmlElementKKStrPtr eKKStr = dynamic_cast<
      XmlElementKKStrPtr>(e);
        if (eKKStr)
          FileName (*(eKKStr->Value ()));
      }
      else if (varName.EqualIgnoreCase ("Attributes"))
      {
        XmlElementAttributeListPtr eAttributes = dynamic_cast<
      XmlElementAttributeListPtr>(e);
        if (eAttributes && (eAttributes->Value ()))
          AddAttributes (*(eAttributes->Value ()));
      }
      else if (varName.EqualIgnoreCase ("Classes"))
      {
        XmlElementMLClassNameListPtr eCLasses = dynamic_cast<
      XmlElementMLClassNameListPtr>(e);
        if (eCLasses && (eCLasses->Value ()))
          AddClasses (*(eCLasses->Value ()));
      }
      else if (varName.EqualIgnoreCase ("ClassNameAttribute"))
      {
        XmlElementKKStrPtr eKKStr = dynamic_cast<
      XmlElementKKStrPtr>(e);
        if (eKKStr)
          ClassNameAttribute (*(eKKStr->Value ()));
      }
      else if (varName.EqualIgnoreCase ("Version"))
      {
        XmlElementInt32Ptr eKKInt32 = dynamic_cast<
      XmlElementInt32Ptr>(e);
        if (eKKInt32)
          Version ((kkint16)eKKInt32->Value ());
      }
      else if (varName.EqualIgnoreCase ("SparseMinFeatureNum"))
      {
        XmlElementInt32Ptr eKKInt32 = dynamic_cast<
      XmlElementInt32Ptr>(e);
        if (eKKInt32)
          SparseMinFeatureNum (eKKInt32->Value ());
      }
      else
      {
        log.Level (-1) << endl
          << "XmlElementFileDesc ***ERROR*** Unexpected Element <" << className << ", VarName=" <<
      varName.QuotedStr () << ">" << endl
          << endl;
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
} /* ReadXML */
bool FileDesc::SameExceptForSymbolicData (const FileDesc & otherFd, RunLog & log) const
Definition at line 472 of file FileDesc.cpp.
References KKB::KKStr::Concat(), FieldName(), FileName(), NumOfFields(), KKB::KKStr::operator!=(), and Type().
Referenced by MergeSymbolicFields(), KKMLL::FeatureVectorList::SameExceptForSymbolicData(), and KKMLL::FeatureVectorList::SynchronizeSymbolicData().
{
  bool same = true;
  if (NumOfFields () != otherFd.NumOfFields ())
  {
    log.Level (-1) << endl
                   << "FileDesc::SameExceptForSymbolicData Field count mis-match" <<
      endl
                   << " File[" << fileName << "] count[" << otherFd.
      NumOfFields () << "] File[" << otherFd.fileName << "] Count[" << otherFd.
      NumOfFields () << "]" << endl
                   << endl;
    return false;
  }
  kkint32 numOfFields = NumOfFields ();
  kkint32 fieldNum = 0;
  const KKStr& rightFileName = otherFd.FileName ();
  for (fieldNum = 0; fieldNum < numOfFields; fieldNum++)
  {
    const KKStr& lName = FieldName (fieldNum);
    const KKStr& rName = otherFd.FieldName (fieldNum);
    if (lName != rName)
    {
      log.Level (-1) << endl
                     << "FileDesc::SameExceptForSymbolicData Field Name mis-match" <<
      endl
                     << " File[" << fileName << "] Name[" << lName << "] File[" << rightFileName
      << "] Name[" << rName << "]" << endl
                     << endl;
      same = false;
    }
    else
    {
      AttributeType lType = Type (fieldNum);
      AttributeType rType = otherFd.Type (fieldNum);
      if (lType != rType)
      {
        log.Level (-1) << endl
                       << "FileDesc::SameExceptForSymbolicData Field Type mis-match" <<
      endl
                       << " File[" << fileName << "] Name[" << lName << "] File[" <<
      rightFileName << "] Name[" << rName << "]" << endl
                       << endl;
        same = false;
      }
    }
  }
  return same;
} /* SameExceptForSymbolicData */
kkint32 KKMLL::FileDesc::SparseMinFeatureNum () const [inline]
Definition at line 120 of file FileDesc.h.
Referenced by KKMLL::FeatureFileIOSparse::LoadFile(), and KKMLL::FeatureFileIOSparse::SaveFile().
{return sparseMinFeatureNum;}
void KKMLL::FileDesc::SparseMinFeatureNum (kkint32 _sparseMinFeatureNum) [inline]
Definition at line 125 of file FileDesc.h.
Referenced by KKMLL::FeatureFileIOSparse::GetFileDesc(), and ReadXML().
{sparseMinFeatureNum = _sparseMinFeatureNum;}
AttributeType FileDesc::Type (kkint32 fieldNum) const
Definition at line 370 of file FileDesc.cpp.
Referenced by AddANominalValue(), AllFieldsAreNumeric(), KKMLL::FeatureVectorList::FeatureType(), KKMLL::FeatureVectorList::FeatureTypeStr(), MergeSymbolicFields(), KKMLL::ModelParam::NumOfFeaturesAfterEncoding(), KKMLL::SVMparam::NumOfFeaturesAfterEncoding(), KKMLL::FeatureVectorList::ReSyncSymbolicData(), SameExceptForSymbolicData(), and KKMLL::FeatureNumList::SetAllFeatures().
{
  ValidateFieldNum (fieldNum, "Type");
  return attributes[fieldNum].Type ();
} /* Type */
KKStr FileDesc::TypeStr (kkint32 fieldNum) const
Definition at line 378 of file FileDesc.cpp.
Referenced by KKMLL::FeatureEncoder2::CreateEncodedFileDesc(), and KKMLL::FeatureEncoder::CreateEncodedFileDesc().
{
  ValidateFieldNum (fieldNum, "TypeStr");
  return AttributeTypeToStr (attributes[fieldNum].Type ());
} /* TypeStr */
kkint16 KKMLL::FileDesc::Version () const [inline]
Definition at line 121 of file FileDesc.h.
{return version;}
void KKMLL::FileDesc::Version (kkint16 _version) [inline]
Definition at line 126 of file FileDesc.h.
Referenced by KKMLL::GrayScaleImagesFVProducer::DefineFileDescStatic(), and ReadXML().
{version = _version;}
void FileDesc::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 875 of file FileDesc.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::Model::WriteModelXMLFields(), KKMLL::FeatureEncoder::WriteXML(), SVM289_MFS::Svm_Model::WriteXML(), KKMLL::SVMModel::WriteXML(), and KKMLL::XmlElementFileDesc::WriteXML().
{
  XmlTag startTag ("FileDesc", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  if (!fileName.Empty ())
    XmlElementKKStr::WriteXML (fileName, "FileName", o);
  XmlElementAttributeList::WriteXML (attributes, "Attributes", o);
  XmlElementMLClassNameList::WriteXML (classes, "Classes", o);
  if (!ClassNameAttribute ().Empty ())
    XmlElementKKStr::WriteXML (ClassNameAttribute (), "ClassNameAttribute", o);
  XmlElementInt32::WriteXML (version, "Version", o);
  if (sparseMinFeatureNum != 0)
    XmlElementInt32::WriteXML (sparseMinFeatureNum, "SparseMinFeatureNum", o);
  XmlTag endTag ("FileDesc", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
}
Friends And Related Function Documentation
friend class KKQueue< FileDesc > [friend]
Definition at line 107 of file FileDesc.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FileDesc.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FileDesc.cpp