KKB::KKThreadList Class Reference
#include <KKThread.h>
Public Member Functions
KKThreadList (bool _owner=true)
KKThreadList (const KKThreadList &list)
~KKThreadList ()
kkint32 MemoryConsumedEstimated () const
Additional Inherited Members
Detailed Description
Definition at line 211 of file KKThread.h.
Constructor & Destructor Documentation
KKThreadList::KKThreadList (bool _owner = true)
Definition at line 555 of file KKThread.cpp.
References KKThreadList().
Referenced by KKB::KKThread::AddShutdownPrerequistite(), KKB::KKThread::AddStartPrerequistite(), KKB::KKThreadManager::AddThread(), KKThreadList(), and KKB::KKThreadManager::KKThreadManager().
                                      :
    KKQueue<KKThread> (_owner)
{
}
KKThreadList::KKThreadList (const KKThreadList & list)
Definition at line 562 of file KKThread.cpp.
References KKThreadList().
Referenced by KKThreadList().
                                                    :
    KKQueue<KKThread> (list)
{
}
KKThreadList::~KKThreadList ()
Definition at line 569 of file KKThread.cpp.
{
}
Member Function Documentation
kkint32 KKThreadList::MemoryConsumedEstimated () const
Definition at line 575 of file KKThread.cpp.
References KKB::KKThread::MemoryConsumedEstimated().
Referenced by KKB::KKThread::MemoryConsumedEstimated().
{
  kkint32 memEst = sizeof (KKThreadList);
  KKThreadList::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx)
  {
    KKThreadPtr t = *idx;
    memEst += t->MemoryConsumedEstimated ();
  }
  return memEst;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKThread.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKThread.cpp