KKB::BmpImage::CodedPixels Class Reference
This object is used to help encode the data stored in BMPImage::image into 8 or 4 bit compressed formats used by BMP files. *.
Public Member Functions
CodedPixels (kkint32 _height, kkint32 _width)
~CodedPixels ()
void AddPixel (uchar pixel)
uchar * CreatePixelDataStructure4Bit (kkint32 &len)
uchar * CreatePixelDataStructure8Bit (kkint32 &len)
void EOL ()
Detailed Description
This object is used to help encode the data stored in BMPImage::image into 8 or 4 bit compressed formats used by BMP files. *.
Definition at line 163 of file BMPImage.cpp.
Constructor & Destructor Documentation
KKB::BmpImage::CodedPixels::CodedPixels (kkint32 _height, kkint32 _width)
Definition at line 200 of file BMPImage.cpp.
                                    :
  height (_height),
  width (_width),
  top (NULL)
{
  codesAllocated = height * (width + 4);
  used = 0;
  codes = new CodePair[codesAllocated];
}
KKB::BmpImage::CodedPixels::~CodedPixels ()
Definition at line 215 of file BMPImage.cpp.
{
  delete codes;
}
Member Function Documentation
void KKB::BmpImage::CodedPixels::AddPixel (uchar pixel)
This method is called once for each pixel in the BMP image
Definition at line 223 of file BMPImage.cpp.
References KKB::BmpImage::CodePair::count, and KKB::BmpImage::CodePair::pixel.
Referenced by KKB::BmpImage::SaveGrayscaleInverted4Bit(), and KKB::BmpImage::SaveGrayscaleInverted8Bit().
{
  if (used >= codesAllocated)
  {
    // We are exceeding the codes Size.
    cerr << "CodedPixels::AddPixel *** Error ***, Exceeding codesAllocated." <<
      std::endl;
    return;
  }
  if (!top)
  {
    top = &(codes[0]);
    used++;
    top->count = 1;
    top->pixel = pixel;
  }
  else if ((pixel != top->pixel) || (top->count == 0))
  {
    used++;
    top++;
    top->count = 1;
    top->pixel = pixel;
  }
  else
  {
    if (top->count >= 254)
    {
      used++;
      top++;
      top->count = 1;
      top->pixel = pixel;
    }
    else
    {
      top->count++;
    }
  }
} /* AddPixel */
uchar * KKB::BmpImage::CodedPixels::CreatePixelDataStructure4Bit (kkint32 & len)
Creates the appropriate compressed data structure for the BMP 4-bit compressed file format. The length of the structure created will be returned in the 'len' parameter. The caller will be responsible for deleting the returned data structure.
Definition at line 277 of file BMPImage.cpp.
References KKB::BmpImage::CodePair::count, and KKB::BmpImage::CodePair::pixel.
Referenced by KKB::BmpImage::SaveGrayscaleInverted4Bit().
{
  kkint32 buffSize = codesAllocated;
  uchar* buff = new uchar [buffSize + 4]; // + 4 For Safety
  memset (buff, 0, codesAllocated);
  kkint32 curPair = 0;
  top = &(codes[0]);
  kkint32 bp = 0;
  while (curPair < used)
  {
    if (bp >= buffSize)
    {
      kkint32 newBuffSize = buffSize * 2;
      uchar* newBuff = new uchar[newBuffSize];
      memset (newBuff, 0, newBuffSize);
      memcpy (newBuff, buff, buffSize);
      delete[] buff;
      buff = newBuff;
      newBuff = NULL;
      buffSize = newBuffSize;
    }
    {
      if ((top->count == 0) && (top->pixel == 0))
      {
        // Add End Of Line
        buff[bp] = 0;
        bp++;
        buff[bp] = 0;
        bp++;
        curPair++;
        top++;
      }
      else
      {
        if (top->count > 254)
        {
          buff[bp] = 254;
          bp++;
          buff[bp] = top->pixel * 16 + top->pixel;
          bp++;
          top->count = top->count - 254;
        }
        else
        {
          buff[bp] = top->count;
          bp++;
          buff[bp] = top->pixel * 16 + top->pixel;
          bp++;
          curPair++;
          top++;
        }
      }
    }
  }
  buff[bp] = 0;
  bp++;
  buff[bp] = 1;
  bp++;
  len = bp;
  return buff;
} /* CreatePixelDataStructure */
uchar * KKB::BmpImage::CodedPixels::CreatePixelDataStructure8Bit (kkint32 & len)
Creates the appropriate compressed data structure for the BMP 8-bit compressed file format. The length of the structure created will be returned in the 'len' parameter. The caller will be responsible for deleting the returned data structure.
Definition at line 358 of file BMPImage.cpp.
References KKB::KKStr::Concat(), KKB::BmpImage::CodePair::count, KKB::KKException::KKException(), and KKB::BmpImage::CodePair::pixel.
Referenced by KKB::BmpImage::SaveGrayscaleInverted8Bit().
{
  kkint32 buffSize = codesAllocated;
  uchar* buff = new uchar [buffSize + 4]; // + 4 For Safety
  memset (buff, 0, codesAllocated);
  kkint32 curPair = 0;
  top = &(codes[0]);
  kkint32 bp = 0;
  while (curPair < used)
  {
    if (bp >= (buffSize - 1))
    {
      kkint32 newBuffSize = buffSize * 2;
      uchar* newBuff = new uchar[newBuffSize + 2];
      if (newBuff == NULL)
      {
        KKStr errMsg = "BmpImage::CodedPixels::CreatePixelDataStructure8Bit ***ERROR***
       Allocation of 'newBuff' failed.";
        cerr << std::endl << std::endl << errMsg << std::endl <<
      std::endl;
        throw KKException (errMsg);
      }
      memset (newBuff, 0, newBuffSize);
      memcpy (newBuff, buff, buffSize);
      delete[] buff;
      buff = newBuff;
      newBuff = NULL;
      buffSize = newBuffSize;
    }
    {
      if ((top->count == 0) && (top->pixel == 0))
      {
        // Add End Of Line
        buff[bp] = 0;
        bp++;
        buff[bp] = 0;
        bp++;
        curPair++;
        top++;
      }
      else
      {
        if (top->count > 254)
        {
          buff[bp] = 254;
          bp++;
          buff[bp] = top->pixel;
          bp++;
          top->count = top->count - 254;
        }
        else
        {
          buff[bp] = top->count;
          bp++;
          buff[bp] = top->pixel;
          bp++;
          curPair++;
          top++;
        }
      }
    }
  }
  buff[bp] = 0;
  bp++;
  buff[bp] = 1;
  bp++;
  len = bp;
  return buff;
} /* CreatePixelDataStructure */
void KKB::BmpImage::CodedPixels::EOL ()
This is called once at the end of each row of pixels.
Definition at line 266 of file BMPImage.cpp.
References KKB::BmpImage::CodePair::count, and KKB::BmpImage::CodePair::pixel.
Referenced by KKB::BmpImage::SaveGrayscaleInverted4Bit(), and KKB::BmpImage::SaveGrayscaleInverted8Bit().
{
  used++;
  top++;
  top->count = 0;
  top->pixel = 0;
} /* EOL */
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/BMPImage.cpp