KKB::KKStrListIndexed Class Reference
#include <KKStr.h>
Public Member Functions
KKStrListIndexed ()
KKStrListIndexed (bool _owner, bool _caseSensitive)
KKStrListIndexed (const KKStrListIndexed &list)
~KKStrListIndexed ()
kkint32 Add (KKStrPtr s)
bool CaseSensative () const
kkint32 Delete (KKStr &s)
void DeleteContents ()
kkint32 LookUp (const KKStr &s) const
kkint32 LookUp (KKStrPtr s) const
KKStrConstPtr LookUp (kkuint32 x) const
kkint32 MemoryConsumedEstimated () const
bool operator!= (const KKStrListIndexed &right)
bool operator== (const KKStrListIndexed &right)
void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
kkuint32 size () const
KKStr ToTabDelString () const
Strings will be separated by tab() characters and in order of index.
void WriteXML (const KKStr &varName, std::ostream &o) const
Detailed Description
Definition at line 835 of file KKStr.h.
Constructor & Destructor Documentation
KKStrListIndexed::KKStrListIndexed ()
Definition at line 5366 of file KKStr.cpp.
                                   :
  comparator (true),
  indexIndex (),
  memoryConsumedEstimated (0),
  nextIndex (0),
  owner (true),
  strIndex (NULL)
{
  strIndex = new StrIndex (comparator);
  memoryConsumedEstimated = sizeof (*this);
}
KKStrListIndexed::KKStrListIndexed (bool _owner, bool _caseSensitive)
Definition at line 5381 of file KKStr.cpp.
Referenced by KKMLL::Attribute::Attribute().
                                    :
  comparator (_caseSensitive),
  indexIndex (),
  memoryConsumedEstimated (0),
  nextIndex (0),
  owner (_owner),
  strIndex (NULL)
{
  strIndex = new StrIndex (comparator);
  memoryConsumedEstimated = sizeof (*this);
}
KKStrListIndexed::KKStrListIndexed (const KKStrListIndexed & list)
Definition at line 5397 of file KKStr.cpp.
Referenced by KKMLL::Attribute::Attribute(), and KKMLL::Attribute::operator=().
                                                                :
   comparator (list.comparator),
   indexIndex (),
   memoryConsumedEstimated (0),
   nextIndex (0),
   owner (list.owner),
   strIndex (NULL)
{
  strIndex = new StrIndex (comparator);
  memoryConsumedEstimated = sizeof (*this);
  IndexIndex::const_iterator idx;
  for (idx = list.indexIndex.begin (); idx != list.indexIndex.end (); ++idx)
  {
    if (owner)
      Add (new KKStr (*(idx->second)));
    else
      Add (idx->second);
  }
}
KKStrListIndexed::~KKStrListIndexed ()
summary>Note that if 'owner' flag s set to true will take ownership of the strings added to index.
param name='s'> Will add 's' into the u=index unless another string with the same value already exists.
returns> The index assigned to 's' or -1 if 's' is a duplicate of one already in the list.
Definition at line 5420 of file KKStr.cpp.
References DeleteContents().
{
  DeleteContents ();
  indexIndex.clear ();
  strIndex->clear ();
}
Member Function Documentation
kkint32 KKStrListIndexed::Add (KKStrPtr s)
Definition at line 5506 of file KKStr.cpp.
References KKB::KKStr::MemoryConsumedEstimated().
Referenced by KKMLL::Attribute::AddANominalValue(), and ReadXML().
{
  StrIndex::iterator idx;
  idx = strIndex->find (s);
  if (idx != strIndex->end ())
    return -1;
  kkint32 index = nextIndex;
  ++nextIndex;
  strIndex->insert (StrIndexPair (s, index));
  indexIndex.insert (IndexIndexPair (index, s));
  if (owner)
    memoryConsumedEstimated += s->MemoryConsumedEstimated ();
  memoryConsumedEstimated += 8;
  return index;
} /* Add */
bool KKB::KKStrListIndexed::CaseSensative () const [inline]
Parameters
in s Will add a new instance of 's' to the index unless one with the same value already exists.
Returns
The index assigned to 's' or -1 if 's' is a duplicate of one already in the list.
Definition at line 859 of file KKStr.h.
{return caseSensative;}
kkint32 KKStrListIndexed::Delete (KKStr & s)
Definition at line 5529 of file KKStr.cpp.
References KKB::KKStr::MemoryConsumedEstimated().
{
  StrIndex::iterator idx;
  idx = strIndex->find (&s);
  if (idx == strIndex->end ())
    return -1;
 
  KKStrPtr strIndexStr = idx->first;
  kkint32 index = idx->second;
  strIndex->erase (idx);
  IndexIndex::iterator idx2;
  idx2 = indexIndex.find (index);
  if (idx2 != indexIndex.end ())
    indexIndex.erase (idx2);
  if (owner)
  {
    memoryConsumedEstimated -= strIndexStr->MemoryConsumedEstimated ();
    delete strIndexStr;
    strIndexStr = NULL;
  }
  memoryConsumedEstimated -= 8;
  return index;
} /* Delete */
void KKStrListIndexed::DeleteContents ()
Definition at line 5429 of file KKStr.cpp.
Referenced by ReadXML(), and ~KKStrListIndexed().
{
  if (owner)
  {
    StrIndex::iterator idx;
    for (idx = strIndex->begin (); idx != strIndex->end (); ++idx)
    {
      KKStrPtr s = idx->first;
      delete s;
    }
  }
  delete strIndex;
  strIndex = NULL;
}
kkint32 KKStrListIndexed::LookUp (const KKStr & s) const
Definition at line 5558 of file KKStr.cpp.
References KKB::KKStr::Concat(), and KKB::KKStr::KKStr().
Referenced by KKMLL::Attribute::GetNominalCode().
{
  StrIndex::const_iterator idx;
  KKStr sNotConst (s);
  idx = strIndex->find (&sNotConst);
  if (idx == strIndex->end ())
    return -1;
  else
    return idx->second;
}
kkint32 KKStrListIndexed::LookUp (KKStrPtr s) const
Definition at line 5572 of file KKStr.cpp.
{
  StrIndex::iterator idx;
  idx = strIndex->find (s);
  if (idx == strIndex->end ())
    return -1;
  else
    return idx->second;
}
KKStrConstPtr KKStrListIndexed::LookUp (kkuint32 x) const
Definition at line 5584 of file KKStr.cpp.
Referenced by KKMLL::Attribute::GetNominalValue(), and WriteXML().
{
  IndexIndex::const_iterator idx;
  idx = indexIndex.find (x);
  if (idx == indexIndex.end ())
    return NULL;
  else
    return idx->second;
}
kkint32 KKStrListIndexed::MemoryConsumedEstimated () const
Definition at line 5454 of file KKStr.cpp.
Referenced by KKMLL::Attribute::MemoryConsumedEstimated().
{
  return memoryConsumedEstimated;
} /* MemoryConsumedEstimated */
bool KKStrListIndexed::operator!= (const KKStrListIndexed & right)
Definition at line 5499 of file KKStr.cpp.
References operator==().
Referenced by KKMLL::Attribute::operator==().
{
  return !((*this) == right);
} /* operator!= */
bool KKStrListIndexed::operator== (const KKStrListIndexed & right)
Definition at line 5462 of file KKStr.cpp.
Referenced by operator!=().
{
  if (indexIndex.size () != right.indexIndex.size ())
    return false;
  bool caseSensativeComparison = caseSensative || right.caseSensative;
  IndexIndex::const_iterator idxLeft = indexIndex.begin ();
  IndexIndex::const_iterator idxRight = right.indexIndex.begin ();
  while ((idxLeft != indexIndex.end ()) && (idxRight != right.indexIndex.end ()))
  {
    if (idxLeft->first != idxRight->first)
      return false;
    if (caseSensativeComparison)
    {
      if (idxLeft->second->Compare (*(idxRight->second)) != 0)
        return false;
    }
    else
    {
      if (idxLeft->second->CompareIgnoreCase (*(idxRight->second)) != 0)
        return false;
    }
    if ((*(idxLeft->second)) != (*(idxRight->second)))
    ++idxLeft;
    ++idxRight;
  }
  return true;
} /* operator== */
void KKStrListIndexed::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 5595 of file KKStr.cpp.
References Add(), KKB::XmlTag::AttributeValueByName(), KKB::KKStr::Concat(), KKB::XmlContent::Content(), DeleteContents(), KKB::KKStrParser::GetNextToken(), KKB::XmlStream::GetNextToken(), KKB::KKStr::KKStr(), KKB::KKStrParser::KKStrParser(), KKB::KKStrParser::MoreTokens(), KKB::KKStr::ToBool(), KKB::XmlToken::tokContent, and KKB::XmlToken::TokenType().
{
  DeleteContents ();
  bool caseSensative = tag->AttributeValueByName ("CaseSensative")->ToBool ();
  comparator.caseSensitive = caseSensative;
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (t->TokenType () == XmlToken::TokenTypes::tokContent)
    {
      XmlContentPtr c = dynamic_cast<XmlContentPtr> (t);
      KKStrParser p (*c->Content ());
      while (p.MoreTokens ())
      {
        KKStr s = p.GetNextToken (",\t\n\r");
        Add (new KKStr (s));
      }
    }
    delete t;
    if (cancelFlag)
      t = NULL;
    else
      t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
} /* ReadXML */
kkuint32 KKStrListIndexed::size () const
Definition at line 5447 of file KKStr.cpp.
Referenced by KKMLL::Attribute::Cardinality(), and WriteXML().
{
  return indexIndex.size ();
}
KKStr KKStrListIndexed::ToTabDelString () const
Strings will be separated by tab() characters and in order of index.
Strings will be separated by tab() characters and in order of index.
Definition at line 5631 of file KKStr.cpp.
References KKB::KKStr::Concat(), and KKB::KKStr::Empty().
{
  KKStr s (indexIndex.size () * 20);
  IndexIndex::const_iterator idx;
  for (idx = indexIndex.begin (); idx != indexIndex.end (); ++idx)
  {
    if (!s.Empty ())
      s << "\t";
    s << *(idx->second);
  }
  return s;
}
void KKStrListIndexed::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 5645 of file KKStr.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), LookUp(), KKB::operator<<(), KKB::KKStr::QuotedStr(), size(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), KKB::XmlContent::WriteXml(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("KKStrListIndexed", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.AddAtribute ("CaseSensative", caseSensative);
  startTag.WriteXML (o);
  kkuint32 n = size ();
  for (kkuint32 x = 0; x < n; ++x)
  {
    KKStrConstPtr s = LookUp ((kkint32)x);
    if (x > 0) o << "\t";
    XmlContent::WriteXml (s->QuotedStr (), o);
  }
  XmlTag endTag ("KKStrListIndexed", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStr.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStr.cpp