KKMLL::FeatureNumList Class Reference
Keeps track of selected features.
#include <FeatureNumList.h>
Public Types
typedef FeatureNumList const FeatureNumListConst
typedef FeatureNumListConst * FeatureNumListConstPtr
typedef FeatureNumList * FeatureNumListPtr
typedef FeatureNumList * FeatureNumListPtr
typedef FeatureNumList * FeatureNumListPtr
enum FeatureSelectionType { IncludeFeatureNums,
ExcludeFeatureNums
 }
Public Member Functions
FeatureNumList (const FeatureNumList &featureNumList)
Copy constructor.
FeatureNumList (const FeatureNumList &featureNumList)
Copy constructor.
FeatureNumList ()
FeatureNumList (kkuint32 _maxFeatureNum)
FeatureNumList (FeatureNumListConst &featureNumList)
Copy constructor.
FeatureNumList (FileDescPtr _fileDesc)
FeatureNumList (FeatureNumList &&featureNumList)
Move constructor.
FeatureNumList (kkuint32 _maxFeatureNum)
Constructs an instance with no features selected and expecting a maximum of 'maxFeatureNum'.
FeatureNumList (const BitString &bitString)
Constructs a 'FeatureNumList' instance using the set bits in 'bitString' to indicate which features are selected.
FeatureNumList (FileDescPtr _fileDesc, const BitString &bitString)
Constructs a 'FeatureNumList' instance using the set bits in 'bitString' to indicate which features are selected.
FeatureNumList (FileDescPtr _fileDesc)
FeatureNumList (const BitString &bitString)
Constructs a 'FeatureNumList' instance using the set bits in 'bitString' to indicate which features are selected.
FeatureNumList (const KKStr &_featureListStr, bool &_valid)
Constructs a 'FeatureNumList' instance from a string that contains a list of selected features.
FeatureNumList (FileDescPtr _fileDesc, const KKStr &_featureListStr, bool &_valid)
Constructs a 'FeatureNumList' instance from a string that contains a list of selected features.
FeatureNumList (const KKStr &_featureListStr, bool &_valid)
Constructs a 'FeatureNumList' instance from a string that contains a list of selected features.
FeatureNumList (FileDescPtr _fileDesc, FeatureSelectionType _selectionType, const KKStr &_featureListStr, bool &_valid)
Constructs a 'FeatureNumList' instance from a string where '_selectionType' indicates if the features should be included or excluded.
~FeatureNumList ()
~FeatureNumList ()
~FeatureNumList ()
void AddFeature (kkuint16 featureNum)
Adds 'featureNum' to the list of selected features.
void AddFeature (kkuint16 featureNum)
Adds 'featureNum' to the list of selected features.
void AddFeature (kkuint16 featureNum)
Adds 'featureNum' to the list of selected features. If it is already selected nothing happens.
bool AllFeaturesSelected (FileDescPtr fileDesc) const
Returns true if all features are selected.
bool AllFeaturesSelected (FileDescPtr fileDesc) const
Returns true if all features are selected.
bool AllFeaturesSelected () const
Returns true if all features are selected.
kkint32 Compare (const FeatureNumList &_features) const
Compare with another featureNumList returning -1, 0, and 1 indicating less_than, equal, or greater_than.
kkint32 Compare (const FeatureNumList &_features) const
Compare with another featureNumList returning -1, 0, and 1 indicating less_than, equal, or greater_than.
kkint32 Compare (const FeatureNumList &_features) const
Compare with another featureNumList returning -1, 0, and 1 indicating less_than, equal, or greater_than.
FeatureNumList Complement () const
Perform a complement of selected features. That is if a feature is selected turn it off and if it is not selected then turn it on.
FeatureNumList Complement () const
Perform a complement of selected features. That is if a feature is selected turn it off and if it is not selected then turn it on.
FeatureNumList Complement () const
Perform a complement of selected features. That is if a feature is selected turn it off and if it is not selected then turn it on.
kkuint16 * CreateFeatureNumArray () const
Allocates a array of kkint32's that is a copy of FeatureNums. The caller will own the array and is responsible for deleting it.
kkuint16 * CreateFeatureNumArray () const
Allocates a array of kkint32's that is a copy of FeatureNums. The caller will own the array and is responsible for deleting it.
kkuint16 * CreateFeatureNumArray () const
Allocates a array of kkint32's that is a copy of FeatureNums. The caller will own the array and is responsible for deleting it.
void ExtractFeatureNumsFromStr (KKStr featureListStr, bool &valid)
Will select the features specified in `featureListStr`.
KKMLL::AttributeType FeatureAttributeType (kkint32 idx) const
const kkuint16 * FeatureNums () const
const kkuint16 * FeatureNums () const
const kkuint16 * FeatureNums () const
FileDescPtr FileDesc () const
bool InList (kkuint16 featureNum) const
returns true if '_featureNum' is one of the selected features.
bool InList (kkuint16 featureNum) const
returns true if '_featureNum' is one of the selected features.
bool InList (kkuint16 featureNum) const
returns true if '_featureNum' is one of the selected features.
bool IsSubSet (const FeatureNumList &z)
Returns true if 'z' is a subset of this instance.
bool IsSubSet (const FeatureNumList &z)
Returns true if 'z' is a subset of this instance.
bool IsSubSet (const FeatureNumList &z)
Returns true if 'z' is a subset of this instance.
void Load (const KKStr &_fileName, bool &_successful, RunLog &_log)
void Load (const KKStr &_fileName, bool &_successful, RunLog &_log)
kkint32 MaxFeatureNum () const
kkint32 MaxFeatureNum () const
kkint32 MemoryConsumedEstimated () const
kkint32 MemoryConsumedEstimated () const
kkint32 MemoryConsumedEstimated () const
kkint32 NumOfFeatures () const
kkint32 NumOfFeatures () const
kkint32 NumOfFeatures () const
kkint32 NumSelFeatures () const
kkint32 NumSelFeatures () const
kkint32 NumSelFeatures () const
FeatureNumList operator* (const FeatureNumList &rightSide) const
Returns new instance that is the intersection of features.
FeatureNumList operator* (const FeatureNumList &rightSide) const
Returns new instance that is the intersection of features.
FeatureNumList operator* (const FeatureNumList &rightSide) const
Returns new instance that is the intersection of features.
FeatureNumList operator+ (const FeatureNumList &rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList operator+ (kkuint16 rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList operator+ (const FeatureNumList &rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList operator+ (kkuint16 rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList operator+ (const FeatureNumList &rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList operator+ (kkuint16 rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList & operator+= (const FeatureNumList &rightSide)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList & operator+= (kkuint16 featureNum)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList & operator+= (const FeatureNumList &rightSide)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList & operator+= (kkuint16 featureNum)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList & operator+= (const FeatureNumList &rightSide)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList & operator+= (kkuint16 featureNum)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList operator- (const FeatureNumList &rightSide) const
Returns a new FeatureNumList instance that consists of the left side instance with the selected features in the right side removed.
FeatureNumList operator- (kkuint16 rightSide) const
Returns a new FeatureNumList instance that will consists of the left FeatureNumList instance with 'rightSide' removed from it.
FeatureNumList operator- (const FeatureNumList &rightSide) const
FeatureNumList operator- (kkuint16 rightSide) const
FeatureNumList operator- (const FeatureNumList &rightSide) const
FeatureNumList operator- (kkuint16 rightSide) const
FeatureNumList & operator-= (kkuint16 rightSide)
removes the feature specified on the right side from the FeatureNumList on the left side.
FeatureNumList & operator-= (kkuint16 rightSide)
FeatureNumList & operator-= (kkuint16 rightSide)
bool operator< (const FeatureNumList &_features) const
Indicates if the Left FeatureNumList instances is less than the right one.
bool operator< (const FeatureNumList &_features) const
Indicates if the Left FeatureNumList instances is less than the right one.
bool operator< (const FeatureNumList &_features) const
Indicates if the Left FeatureNumList instances is less than the right one.
FeatureNumList & operator= (const FeatureNumList &_features)
FeatureNumList & operator= (FeatureNumList &&_features)
FeatureNumList & operator= (const FeatureNumListPtr _features)
FeatureNumList & operator= (const FeatureNumList &_features)
FeatureNumList & operator= (const FeatureNumListPtr _features)
FeatureNumList & operator= (const FeatureNumList &_features)
FeatureNumList & operator= (const FeatureNumListPtr _features)
bool operator== (const FeatureNumList &_features) const
Indicates if the two FeatureNumLiost instances have the same features selected.
bool operator== (const FeatureNumList &_features) const
Indicates if the two FeatureNumLiost instances have the same features selected.
bool operator== (const FeatureNumList &_features) const
Indicates if the two FeatureNumLiost instances have the same features selected.
bool operator> (const FeatureNumList &_features) const
Indicates if the Left FeatureNumList instances is greater than the right one.
bool operator> (const FeatureNumList &_features) const
Indicates if the Left FeatureNumList instances is greater than the right one.
bool operator> (const FeatureNumList &_features) const
Indicates if the Left FeatureNumList instances is greater than the right one.
kkuint16 operator[] (kkint32 idx) const
kkuint16 operator[] (kkint32 idx) const
Returns back the selected feature.
kkuint16 operator[] (kkint32 idx) const
Returns back the selected feature.
void ParseToString (const KKStr &_str, bool &_valid)
Will select the features specified in `featureListStr`.
FeatureNumListPtr RandomlySelectFeatures (kkint32 numToKeep) const
Generates a new FeatureNumList object that will select at random 'numToKeep' features from this instance.
FeatureNumListPtr RandomlySelectFeatures (kkint32 numToKeep) const
Generates a new FeatureNumList object that will select at random 'numToKeep' features from this instance.
FeatureNumListPtr RandomlySelectFeatures (kkint32 numToKeep) const
Generates a new FeatureNumList object that will select at random 'numToKeep' features from this instance.
void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
void Save (const KKStr &fileName)
void Save (const KKStr &_fileName, bool &_successful, RunLog &_log)
void Save (std::ostream &o)
void SaveXML (std::ostream &o)
void SetAllFeatures (FileDescPtr fileDesc)
Selects all features except those flagged as 'IgnoreAttribute' in the associated FileDesc.
void SetAllFeatures (FileDescPtr fileDesc)
Selects all features except those flagged as 'Ignore' in the associated FileDesc.
void SetAllFeatures ()
Selects all features except those flagged as 'IgnoreAttribute' in the associated FileDesc.
bool Test (kkuint16 _featureNum) const
Indicates whether feature '_featureNum' is selected.
bool Test (kkuint16 _featureNum) const
Indicates whether feature '_featureNum' is selected.
bool Test (kkuint16 _featureNum) const
Indicates whether feature '_featureNum' is selected.
void ToBitString (BitString &bitStr) const
void ToBitString (BitString &bitStr) const
void ToBitString (BitString &bitStr) const
KKStr ToCommaDelStr () const
KKStr ToCommaDelStr () const
KKStr ToCommaDelStr () const
KKStr ToHexString () const
Uses 'maxFeatureNum to determine length of hex string.
KKStr ToHexString (FileDescPtr fileDesc) const
Uses 'fileDesc' to determine length of hex string.
KKStr ToHexString () const
Uses 'maxFeatureNum to determine length of hex string.
KKStr ToHexString (FileDescPtr fileDesc) const
Uses 'fileDesc' to determine length of hex string.
KKStr ToHexString () const
KKStr ToString () const
Returns comma delimited list of all features selected; will make use of range specification.
KKStr ToString () const
Returns comma delimited list of all features selected; will make use of range specification.
KKStr ToString () const
Returns comma delimited list of all features selected; will make use of range specification.
void UnSet ()
Turns off all features so that no feature is selected.
void UnSet (kkuint16 featureNum)
Turns off specified feature 'featureNum'; if 'featureNum' is not turned on then nothing happens; same as using 'operator-='.
void UnSet ()
Turns off all features so that no feature is selected.
void UnSet (kkuint16 featureNum)
Turns off specified feature 'featureNum'; if 'featureNum' is not turned on then nothing happens; same as using 'operator-='.
void UnSet ()
Turns off all features so that no feature is selected.
void UnSet (kkuint16 featureNum)
Turns off specified feature 'featureNum'; if 'featureNum' is not turned on then nothing happens; same as using 'operator-='.
void WriteXML (const KKStr &varName, std::ostream &o) const
Static Public Member Functions
static FeatureNumList AllFeatures (FileDescPtr fileDesc)
Create a FeatureNumList object where all features are selected, except ones that are flagged as IgnoreAttribute in '__fileDesc'.
static FeatureNumList AllFeatures (FileDescPtr fileDesc)
Create a FeatureNumList object where all features are selected, except ones that are flagged as Ignore in '__fileDesc'.
static FeatureNumList AllFeatures (FileDescPtr fileDesc)
Create a FeatureNumList object where all features are selected, except ones that are flagged as IgnoreAttribute in '__fileDesc'.
static FeatureNumListPtr ExtractFeatureNumsFromStr (const KKStr &featureListStr)
Will select the features specified in `featureListStr`.
Detailed Description
Keeps track of selected features.
Used by SVMModel and the newer 'Model', 'ModelParam' based classes. Each instance of this class will have an associated 'FileDesc' instance. It is meant to keep track of selected features from that instance('FileDesc').
 This class is meant to work with both the FeaureVector, Model, and ModelParm based classes. This will allow us to select specific features from the FeatureVector instances that are to be used.
 At no time are feature numbers that are out of range of the associated FileDesc instance to be selected.
 Two of the constructors allow you to specify a list of features in a string. The list can consist of single features and/or ranges of features. Ranges of features are specified by using the dash('-') character between two numbers. The comma(',') character will be used as a separator. `All` specifies all are to be selected except those that are flagged as 'Ignore' in the associated FileDesc instance. The list should be in ascending order.
Example Strings:
  "1,2,3,10,20" Selects [1,2,3,10, 20].
  "1,4-7,9-12,13" Selects [1,4,,5,6,7,9,10,11,12,13]
  "All" Selects all features that '_fileDesc' includes accept
                   those that are flagged as 'Ignore' in the
                   associated FileDesc instance.
Used by SVMModel and the newer 'Model', 'ModelParam' based classes. Each instance of this class will have an associated 'FileDesc' instance. It is meant to keep track of selected features from that instance('FileDesc').
 This class is meant to work with both the FeaureVector, Model, and ModelParm based classes. This will allow us to select specific features from the FeatureVector instances that are to be used.
 At no time are feature numbers that are out of range of the associated FileDesc instance to be selected.
 Two of the constructors allow you to specify a list of features in a string. The list can consist of single features and/or ranges of features. Ranges of features are specified by using the dash('-') character between two numbers. The comma(',') character will be used as a separator. `All` specifies all are to be selected except those that are flagged as 'IgnoreAttribute' in the associated FileDesc instance. The list should be in ascending order.
Example Strings:
  "1,2,3,10,20" Selects [1,2,3,10, 20].
  "1,4-7,9-12,13" Selects [1,4,,5,6,7,9,10,11,12,13]
  "All" Selects all features that '_fileDesc' includes accept
                   those that are flagged as 'IgnoreAttribute' in the
                   associated FileDesc instance.
Definition at line 54 of file FeatureNumList.h.
Member Typedef Documentation
typedef FeatureNumList const KKMLL::FeatureNumList::FeatureNumListConst
Definition at line 58 of file FeatureNumList.h.
typedef FeatureNumListConst* KKMLL::FeatureNumList::FeatureNumListConstPtr
Definition at line 59 of file FeatureNumList.h.
typedef FeatureNumList* KKMLL::FeatureNumList::FeatureNumListPtr
Definition at line 56 of file FeatureNumList_Old.h.
typedef FeatureNumList* KKMLL::FeatureNumList::FeatureNumListPtr
Definition at line 57 of file FeatureNumList.h.
typedef FeatureNumList* KKMLL::FeatureNumList::FeatureNumListPtr
Definition at line 57 of file FeatureNumList2.h.
Member Enumeration Documentation
enum KKMLL::FeatureNumList::FeatureSelectionType
Enumerator
IncludeFeatureNums
ExcludeFeatureNums
Definition at line 57 of file FeatureNumList_Old.h.
{IncludeFeatureNums, ExcludeFeatureNums}
      FeatureSelectionType;
Constructor & Destructor Documentation
FeatureNumList::FeatureNumList ()
Definition at line 25 of file FeatureNumList.cpp.
                               :
  featureNums (NULL),
  featureNumsAllocatedSize (0),
  maxFeatureNum (0),
  numOfFeatures (0)
{
}
KKMLL::FeatureNumList::FeatureNumList (FeatureNumListConst & featureNumList)
Copy constructor.
FeatureNumList::FeatureNumList (FeatureNumList && featureNumList)
Move constructor.
Definition at line 52 of file FeatureNumList.cpp.
                                                               :
  featureNums (featureNumList.featureNums),
  featureNumsAllocatedSize (featureNumList.featureNumsAllocatedSize),
  maxFeatureNum (featureNumList.maxFeatureNum),
  numOfFeatures (featureNumList.numOfFeatures)
{
  featureNumList.featureNums = NULL;
  featureNumList.featureNumsAllocatedSize = 0;
  featureNumList.maxFeatureNum = 0;
  featureNumList.numOfFeatures = 0;
}
FeatureNumList::FeatureNumList (kkuint32 _maxFeatureNum)
Constructs an instance with no features selected and expecting a maximum of 'maxFeatureNum'.
Definition at line 67 of file FeatureNumList.cpp.
                                                       :
  featureNums (NULL),
  featureNumsAllocatedSize (0),
  maxFeatureNum (_maxFeatureNum),
  numOfFeatures (0)
{
  AllocateArraySize (_maxFeatureNum + 1);
}
FeatureNumList::FeatureNumList (FileDescPtr _fileDesc)
Definition at line 79 of file FeatureNumList.cpp.
References KKMLL::FileDesc::NumOfFields().
                                                     :
  featureNums (NULL),
  featureNumsAllocatedSize (0),
  maxFeatureNum (0),
  numOfFeatures (0)
{
  if (_fileDesc)
    maxFeatureNum = _fileDesc->NumOfFields () - 1;
  AllocateArraySize (10);
}
FeatureNumList::FeatureNumList (const BitString & bitString)
Constructs a 'FeatureNumList' instance using the set bits in 'bitString' to indicate which features are selected.
For each bit position in 'bitString' that is set to '1' the corresponding feature will be selected. So the bit string '0110111' with consists of bits 0, 1, 2, 5, and 6 set to one will cause the features elected to be set to (0, 1, 2, 4, 6). The length of 'bitString' will indicate the maximum features.
Parameters
in bitString A bit string that indicates which features are selected. Bits that are set to 1 indicate that the corresponding feature is selected.
Definition at line 92 of file FeatureNumList.cpp.
References KKB::BitString::BitLen(), and KKB::BitString::ListOfSetBits16().
                                                          :
  featureNums (NULL),
  featureNumsAllocatedSize (0),
  maxFeatureNum (0),
  numOfFeatures (0)
{
  maxFeatureNum = bitString.BitLen () - 1;
  VectorUint16 listOfSelectedFeatures;
  bitString.ListOfSetBits16 (listOfSelectedFeatures);
  AllocateArraySize ((kkuint16)listOfSelectedFeatures.size ());
  for (kkuint32 x = 0; x < listOfSelectedFeatures.size (); x++)
    AddFeature (listOfSelectedFeatures[x]);
}
FeatureNumList::FeatureNumList (const KKStr & _featureListStr, bool & _valid)
Constructs a 'FeatureNumList' instance from a string that contains a list of selected features.
The list can consist of single features and/or ranges of features. Ranges of features are specified by using the dash('-') character between two numbers. The comma(',') character will be used as a separator.
ex's:
  "1,2,3,10,20" Selects [1,2,3,10, 20].
  "1,4-7,9-12,13" Selects [1,4,,5,6,7,9,10,11,12,13]
See also
ParseToString
Parameters
in _featureListStr Comma separated string that contains list of selected features; a range of features can be specified using the dash('-') character. ex: The string `1,3,5-7,9` indicates that features 1,3,5,6,7,9 are selected.
out _valid returns false if '_featureListStr' is not a valid format.
Definition at line 111 of file FeatureNumList.cpp.
References ParseToString().
                                :
  featureNums (NULL),
  featureNumsAllocatedSize (0),
  maxFeatureNum (0),
  numOfFeatures (0)
{
  ParseToString (_featureListStr, _valid);
  return;
}
FeatureNumList::~FeatureNumList ()
Definition at line 128 of file FeatureNumList.cpp.
{
  delete [] featureNums;
}
FeatureNumList::FeatureNumList (const FeatureNumList & featureNumList)
Copy constructor.
Definition at line 36 of file FeatureNumList.cpp.
References AddFeature(), and MaxFeatureNum().
                                                                     :
  featureNums (NULL),
  featureNumsAllocatedSize (0),
  maxFeatureNum (_featureNumList.MaxFeatureNum ()),
  numOfFeatures (0)
{
  kkuint16* otherFeatureNums = _featureNumList.featureNums;
  kkuint16 otherNumOfFeatures = _featureNumList.numOfFeatures;
  AllocateArraySize (_featureNumList.numOfFeatures + 1);
  for (kkuint16 x = 0; x < otherNumOfFeatures; x++)
    AddFeature (otherFeatureNums[x]);
}
KKMLL::FeatureNumList::FeatureNumList (kkuint32 _maxFeatureNum)
Referenced by AllFeatures(), Complement(), ExtractFeatureNumsFromStr(), KKMLL::TrainingConfiguration2::GetFeatureNums(), operator*(), operator-(), and RandomlySelectFeatures().
KKMLL::FeatureNumList::FeatureNumList (const BitString & bitString)
Constructs a 'FeatureNumList' instance using the set bits in 'bitString' to indicate which features are selected.
For each bit position in 'bitString' that is set to '1' the corresponding feature will be selected. So the bit string '0110111' with consists of bits 0, 1, 2, 5, and 6 set to one will cause the features elected to be set to (0, 1, 2, 4, 6). The length of 'bitString' will indicate the maximum features.
Parameters
in bitString A bit string that indicates which features are selected. Bits that are set to 1 indicate that the corresponding feature is selected.
KKMLL::FeatureNumList::FeatureNumList (const KKStr & _featureListStr, bool & _valid)
Constructs a 'FeatureNumList' instance from a string that contains a list of selected features.
The list can consist of single features and/or ranges of features. Ranges of features are specified by using the dash('-') character between two numbers. The comma(',') character will be used as a separator.
ex's:
  "1,2,3,10,20" Selects [1,2,3,10, 20].
  "1,4-7,9-12,13" Selects [1,4,,5,6,7,9,10,11,12,13]
See also
ExtractFeatureNumsFromStr
Parameters
in _featureListStr Comma separated string that contains list of selected features; a range of features can be specified using the dash('-') character. ex: The string `1,3,5-7,9` indicates that features 1,3,5,6,7,9 are selected.
out _valid returns false if '_featureListStr' is not a valid format.
Referenced by KKMLL::BinaryClassParms::CreateFromTabDelStr(), and KKMLL::ModelParam::ParseCmdLine().
KKMLL::FeatureNumList::~FeatureNumList ()
KKMLL::FeatureNumList::FeatureNumList (const FeatureNumList & featureNumList)
Copy constructor.
Referenced by KKMLL::BinaryClassParms::BinaryClassParms(), KKMLL::FeatureEncoder::FeatureEncoder(), KKMLL::ModelParam::ModelParam(), operator+(), operator-(), KKMLL::BinaryClassParms::SelectedFeatures(), KKMLL::ModelParam::SelectedFeatures(), KKMLL::SVMparam::SelectedFeatures(), KKMLL::SVMparam::SetFeatureNums(), SVM289_BFS::svm_model::svm_model(), SVM289_MFS::Svm_Model::Svm_Model(), SVM289_BFS::svm_problem::svm_problem(), SVM289_MFS::svm_problem::svm_problem(), and KKMLL::SVMparam::SVMparam().
KKMLL::FeatureNumList::FeatureNumList (FileDescPtr _fileDesc)
Referenced by KKMLL::TrainingConfiguration2::GetFeatureNums(), KKMLL::ModelParam::NumOfFeaturesAfterEncoding(), KKMLL::SVMparam::SelectedFeatures(), KKMLL::BinaryClassParms::SelectedFeaturesFD(), SVM289_BFS::svm_model::svm_model(), SVM289_MFS::Svm_Model::Svm_Model(), and KKMLL::TrainingConfiguration2::TrainingConfiguration2().
FeatureNumList::FeatureNumList (FileDescPtr _fileDesc, const BitString & bitString)
Constructs a 'FeatureNumList' instance using the set bits in 'bitString' to indicate which features are selected.
For each bit position in 'bitString' that is set to '1' the corresponding feature will be selected. So the bit string '0110111' with consists of bits 0, 1, 2, 5, and 6 set to one will cause the features elected to be set to (0, 1, 2, 4, 6).
 This is a useful constructor when dealing with dataset's that have a large number of features such as DNA based dataset's.
Parameters
in _fileDesc Description of the feature data.
in bitString A bit string that indicates which features are selected. Bits that are set to 1 indicate that the corresponding feature is selected.
Definition at line 43 of file FeatureNumList_Old.cpp.
References FeatureNumList(), and KKB::BitString::ListOfSetBits16().
Referenced by FeatureNumList().
                                :
  featureNums (NULL),
  featureNumsAllocatedSize (0),
  fileDesc (_fileDesc),
  numOfFeatures (0)
{
  if (!fileDesc)
  {
    cerr << endl
         << "FeatureNumList *** ERROR *** No 'FileDesc' object provided." <<
      endl
         << endl;
    osWaitForEnter ();
    exit (-1);
  }
  if (fileDesc->NumOfFields () != kkint32 (bitString.BitLen ()))
  {
    cerr << endl
         << "FeatureNumList *** ERROR ***" << endl
         << endl
         << " BitString.Len[" << bitString.BitLen () << "] is different than
       FileDesc.NumOfFields[" << fileDesc->NumOfFields () << "]" << endl
         << endl;
    osWaitForEnter ();
    exit (-1);
  }
  VectorUint16 listOfBits;
  bitString.ListOfSetBits16 (listOfBits);
  if (kkuint32 (featureNumsAllocatedSize) < listOfBits.size ())
    AllocateArraySize ((kkint32)listOfBits.size ());
  for (kkuint32 x = 0; x < listOfBits.size (); x++)
    AddFeature (listOfBits[x]);
}
FeatureNumList::FeatureNumList (FileDescPtr _fileDesc, const KKStr & _featureListStr, bool & _valid)
Constructs a 'FeatureNumList' instance from a string that contains a list of selected features.
The list can consist of single features and/or ranges of features. Ranges of features are specified by using the dash('-') character between two numbers. The comma(',') character will be used as a separator. `All` specifies all ate to be selected except those that are flagged as 'IgnoreAttribute' in the associated FileDesc instance. The list should be in ascending order.
ex's:
  "1,2,3,10,20" Selects [1,2,3,10, 20].
  "1,4-7,9-12,13" Selects [1,4,,5,6,7,9,10,11,12,13]
  "All" Selects all features that '_fileDesc' includes accept those that are
                   flagged as 'IgnoreAttribute' in the associated FileDesc instance.
See also
ExtractFeatureNumsFromStr
Parameters
in _fileDesc Description of the feature data.
in _featureListStr Comma separated string that contains list of selected features; a range of features can be specified using the dash('-') character. ex: The string `1,3,5-7,9` indicates that features 1,3,5,6,7,9 are selected.
out _valid returns false if '_featureListStr' is not a valid format.
Definition at line 118 of file FeatureNumList_Old.cpp.
References FeatureNumList().
Referenced by FeatureNumList().
                                :
  featureNums (NULL),
  featureNumsAllocatedSize (0),
  fileDesc (_fileDesc),
  numOfFeatures (0)
{
  if (!fileDesc)
  {
    cerr << endl
         << endl
         << "FeatureNumList::FeatureNumList *** ERROR *** fileDesc = NULL" <<
      endl
         << endl;
    osWaitForEnter ();
  }
  AllocateArraySize (fileDesc->NumOfFields ());
  ExtractFeatureNumsFromStr (_featureListStr, _valid);
}
FeatureNumList::FeatureNumList (FileDescPtr _fileDesc, FeatureSelectionType _selectionType, const KKStr & _featureListStr, bool & _valid)
Constructs a 'FeatureNumList' instance from a string where '_selectionType' indicates if the features should be included or excluded.
The list can consist of single features and/or ranges of features. Ranges of features are specified by using the ('-') character between two numbers. The comma(',') character will be used as a separator. The list should be in ascending order. The '_selectionType' parameter specifies weather we are going to select these features or exclude them form the list of all features(complement).
ex's:
  "1,2,3,10,20" Selects [1,2,3,10, 20].
  "1,4-7,9-12,13" Selects [1,4,,5,6,7,9,10,11,12,13]
  "All" Selects all features that '_fileDesc' includes accept those that are
                   flagged as 'IgnoreAttribute' in the associated FileDesc instance.
Parameters
in _fileDesc Description of the feature data.
in _selectionType Specifies whether the features listed in '_featureListStr' should be included (IncludeFeatureNums) or excluded(ExcludeFeatureNums).
in _featureListStr Comma separated string that contains list of features to be included or excluded; a range of features can be specified using the dash('-') character. ex: The string `1,3,5-7,9` indicates that features 1,3,5,6,7,9 are selected.
out _valid returns false if '_featureListStr' is not a valid format.
Definition at line 145 of file FeatureNumList_Old.cpp.
                                :
  featureNums (NULL),
  featureNumsAllocatedSize (0),
  fileDesc (_fileDesc),
  numOfFeatures (0)
{
  if (!fileDesc)
  {
    cerr << endl
         << endl
         << "FeatureNumList::FeatureNumList *** ERROR *** fileDesc = NULL" <<
      endl
         << endl;
    osWaitForEnter ();
  }
  AllocateArraySize (fileDesc->NumOfFields ());
  switch (_selectionType)
  {
    case IncludeFeatureNums:
       ExtractFeatureNumsFromStr (_featureListStr, _valid);
       break;
    
    
    case ExcludeFeatureNums:
       FeatureNumList excludedFeatures (fileDesc, _featureListStr, _valid);
       numOfFeatures = fileDesc->NumOfFields () - excludedFeatures.NumOfFeatures ();
       featureNums = new kkuint16[numOfFeatures];
       featureNumsAllocatedSize = numOfFeatures;
       kkint32 y = 0;
       for (kkuint16 x = 0; x < fileDesc->NumOfFields (); x++)
       {
         if (!excludedFeatures.InList (x))
         {
           featureNums[y] = x;
           y++;
         }
       }
       break;
  } /* End Of Switch */
}
KKMLL::FeatureNumList::~FeatureNumList ()
Member Function Documentation
void KKMLL::FeatureNumList::AddFeature (kkuint16 featureNum)
Adds 'featureNum' to the list of selected features.
If it is already selected nothing happens. If 'featureNum' exceeds the maxFeatureNum then 'maxfeatureNum' will be set to this value.
void FeatureNumList::AddFeature (kkuint16 featureNum)
Adds 'featureNum' to the list of selected features.
If it is already selected nothing happens. If 'featureNum' exceeds the maxFeatureNum then 'maxfeatureNum' will be set to this value.
Definition at line 256 of file FeatureNumList.cpp.
References InList().
{
  if (!featureNums)
  {
    featureNums = new kkuint16[10];
    featureNumsAllocatedSize = 10;
  }
  if (numOfFeatures >= featureNumsAllocatedSize)
  {
    // Expand the featureNums array
    kkint32 newFeatureNumsAllocatedSize = numOfFeatures + 10;
    kkuint16* newFeatureNums = new kkuint16[newFeatureNumsAllocatedSize];
    kkint32 x = 0;
    for (x = 0; x < numOfFeatures; ++x)
      newFeatureNums[x] = featureNums[x];
    while (x < newFeatureNumsAllocatedSize)
    {
      newFeatureNums[x] = 0;
      ++x;
    }
    delete [] featureNums;
    featureNums = newFeatureNums;
    featureNumsAllocatedSize = newFeatureNumsAllocatedSize;
  }
  
  if (numOfFeatures == 0)
  {
    featureNums[0] = featureNum;
    numOfFeatures = 1;
  }
  else
  {
    kkint32 x = numOfFeatures - 1; // Setting x to end of list
    if (featureNums[x] < featureNum)
    {
      // Adding feature to end of list.
      featureNums[numOfFeatures] = featureNum;
      numOfFeatures++;
    }
    else if (!InList (featureNum))
    {
      while ((x >= 0) && (featureNums[x] > featureNum))
      {
        featureNums[x + 1] = featureNums[x];
        featureNums[x] = featureNum;
        x--;
      }
      numOfFeatures++;
    }
  }
  if (featureNum > maxFeatureNum)
    maxFeatureNum = featureNum;
  return;
} /* AddFeature */
void KKMLL::FeatureNumList::AddFeature (kkuint16 featureNum)
Adds 'featureNum' to the list of selected features. If it is already selected nothing happens.
Referenced by Complement(), FeatureNumList(), operator*(), operator+(), operator+=(), operator-(), RandomlySelectFeatures(), and SetAllFeatures().
static FeatureNumList KKMLL::FeatureNumList::AllFeatures (FileDescPtr fileDesc) [static]
Create a FeatureNumList object where all features are selected, except ones that are flagged as IgnoreAttribute in '__fileDesc'.
FeatureNumList FeatureNumList::AllFeatures (FileDescPtr _fileDesc) [static]
Create a FeatureNumList object where all features are selected, except ones that are flagged as Ignore in '__fileDesc'.
A static method that will return a instance of 'FeatureNumList' that will have all non 'Ignore' features in '_fileDesc' selected.
A static method that will return a instance of 'FeatureNumList' that will have all non 'IgnoreAttribute' features in '_fileDesc' selected.
Definition at line 327 of file FeatureNumList.cpp.
References KKMLL::FileDesc::AttributeVector(), FeatureNumList(), and KKMLL::FileDesc::NumOfFields().
{
  kkuint16 maxFeatureNum = _fileDesc->NumOfFields () - 1;
  FeatureNumList features (maxFeatureNum);
  const AttributeTypeVector& attributeTypes = _fileDesc->
      AttributeVector ();
  for (kkuint16 fn = 0; fn <= maxFeatureNum; ++fn)
  {
    if (attributeTypes[fn] != AttributeType::Ignore)
      features.AddFeature (fn);
  }
  return features;
} /* AllFeatures */
static FeatureNumList KKMLL::FeatureNumList::AllFeatures (FileDescPtr fileDesc) [static]
Create a FeatureNumList object where all features are selected, except ones that are flagged as IgnoreAttribute in '__fileDesc'.
Referenced by KKMLL::FeatureVectorList::AllFeatures(), KKMLL::FeatureFileIO::FeatureDataReSink(), and KKMLL::TrainingConfiguration2::GetFeatureNums().
bool KKMLL::FeatureNumList::AllFeaturesSelected (FileDescPtr fileDesc) const
Returns true if all features are selected.
bool FeatureNumList::AllFeaturesSelected (FileDescPtr fileDesc) const
Returns true if all features are selected.
Definition at line 206 of file FeatureNumList.cpp.
References KKMLL::FileDesc::NumOfFields().
{
  if (numOfFeatures >= (kkint32)fileDesc->NumOfFields ())
    return true;
  return false;
} /* AllFeaturesSelected */
bool FeatureNumList::AllFeaturesSelected () const
Returns true if all features are selected.
Definition at line 283 of file FeatureNumList_Old.cpp.
{
  if (numOfFeatures >= (kkint32)fileDesc->NumOfFields ())
    return true;
  return false;
} /* AllFeaturesSelected */
kkint32 KKMLL::FeatureNumList::Compare (const FeatureNumList & _features) const
Compare with another featureNumList returning -1, 0, and 1 indicating less_than, equal, or greater_than.
kkint32 FeatureNumList::Compare (const FeatureNumList & _features) const
Compare with another featureNumList returning -1, 0, and 1 indicating less_than, equal, or greater_than.
Definition at line 696 of file FeatureNumList.cpp.
References NumOfFeatures().
{
  kkint32 x = 0;
  while ((x < numOfFeatures) && (x < _features.NumOfFeatures ()))
  {
    if (featureNums[x] < _features.featureNums[x])
      return -1;
    else if (featureNums[x] > _features.featureNums[x])
      return 1;
    x++;
  }
  if (x < numOfFeatures)
    return 1;
  else if (x < _features.numOfFeatures)
    return -1;
  return 0;
} /* Compare */
kkint32 KKMLL::FeatureNumList::Compare (const FeatureNumList & _features) const
Compare with another featureNumList returning -1, 0, and 1 indicating less_than, equal, or greater_than.
Referenced by operator<(), operator==(), and operator>().
FeatureNumList KKMLL::FeatureNumList::Complement () const
Perform a complement of selected features. That is if a feature is selected turn it off and if it is not selected then turn it on.
FeatureNumList FeatureNumList::Complement () const
Perform a complement of selected features. That is if a feature is selected turn it off and if it is not selected then turn it on.
Definition at line 978 of file FeatureNumList.cpp.
References AddFeature(), and FeatureNumList().
{
  FeatureNumList result (maxFeatureNum);
  kkuint16 x = 0;
  kkuint16 fni = 0;
  while (fni < numOfFeatures)
  {
    while (x < featureNums[fni])
    {
      result.AddFeature (x);
      ++x;
    }
    ++fni;
  }
  while (x < maxFeatureNum)
  {
    result.AddFeature (x);
    ++x;
  }
  return result;
} /* Complement */
FeatureNumList KKMLL::FeatureNumList::Complement () const
Perform a complement of selected features. That is if a feature is selected turn it off and if it is not selected then turn it on.
kkuint16* KKMLL::FeatureNumList::CreateFeatureNumArray () const
Allocates a array of kkint32's that is a copy of FeatureNums. The caller will own the array and is responsible for deleting it.
Returns
A dynamically allocated array that will consist of a list of selected features.
kkuint16 * FeatureNumList::CreateFeatureNumArray () const
Allocates a array of kkint32's that is a copy of FeatureNums. The caller will own the array and is responsible for deleting it.
Returns
A dynamically allocated array that will consist of a list of selected features.
Definition at line 196 of file FeatureNumList.cpp.
{
  kkuint16* newList = new kkuint16[numOfFeatures];
  for (kkint32 x = 0; x < numOfFeatures; x++)
    newList[x] = featureNums[x];
  return newList;
} /* CreateFeatureNumArray */
kkuint16* KKMLL::FeatureNumList::CreateFeatureNumArray () const
Allocates a array of kkint32's that is a copy of FeatureNums. The caller will own the array and is responsible for deleting it.
Returns
A dynamically allocated array that will consist of a list of selected features.
FeatureNumListPtr FeatureNumList::ExtractFeatureNumsFromStr (const KKStr & featureListStr) [static]
Will select the features specified in `featureListStr`.
A static method that will return a new instance 'FeatureNum2List' where the features listed in '_featureListStr' will be turned on. 'maxFeatureNum' will be set to the highest feature number listed in '_featureListStr'.
The format is a comma delimited string, where each number represents a feature, ranges can be specified with a dash(`-`). `All` will select all features that are not flagged as a 'IgnoreAttribute' in the associated FileDesc instance.
ex's: String Selected Features
       "1,2,3,10,20" [1,2,3,10, 20].
       "1,4-7,9-12,23" [1,4,5,6,7,9,10,11,12,23]
       "All" Selects all features that '_fileDesc' includes accept those that are
                        flagged as 'IgnoreAttribute' in the associated FileDesc instance.
Definition at line 524 of file FeatureNumList2.cpp.
References KKB::KKStr::EqualIgnoreCase(), and FeatureNumList().
{
  bool valid = true;
  if (_featureListStr.EqualIgnoreCase ("NONE"))
    return new FeatureNumList (1);
  VectorUint16* list = StrToUInt16Vetor (_featureListStr);
  if (!list)
  {
    delete list;
    list= NULL;
    return NULL;
  }
  if (list->size () < 1)
  {
    delete list;
    list = NULL;
    return new FeatureNumList (1);
  }
  kkuint16 firstNum = (*list)[0];
  kkuint16 lastNum = (*list)[list->size () - 1];
  FeatureNumListPtr result = new FeatureNumList (lastNum);
  VectorUint16::const_iterator idx;
  for (idx = list->begin (); idx != list->end (); ++idx)
    result->AddFeature (*idx);
  delete list;
  list = NULL;
  return result;
} /* ExtractFeatureNumsFromStr */
void FeatureNumList::ExtractFeatureNumsFromStr (KKStr featureListStr, bool & valid)
Will select the features specified in `featureListStr`.
The format is a comma delimited string, where each number represents a feature, ranges can be specified with a dash(`-`). `All` will select all features that are not flagged as a 'IgnoreAttribute' in the associated FileDesc instance.
ex's: String Selected Features
       "1,2,3,10,20" [1,2,3,10, 20].
       "1,4-7,9-12,23" [1,4,5,6,7,9,10,11,12,23]
       "All" Selects all features that '_fileDesc' includes accept those that are
                        flagged as 'IgnoreAttribute' in the associated FileDesc instance.
Definition at line 536 of file FeatureNumList_Old.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::KKStr::ExtractToken(), KKB::KKStr::ExtractTokenInt(), KKB::KKStr::LocateCharacter(), KKB::KKStr::operator=(), KKB::KKStr::operator==(), SetAllFeatures(), KKB::KKStr::TrimLeft(), and KKB::KKStr::Upper().
{
  _valid = true;
  KKStr field;
  kkuint16 featureNum;
  _featureListStr.Upper ();
  numOfFeatures = 0;
  if (_featureListStr == "NONE")
  {
    return;
  }
  if (_featureListStr == "ALL")
  {
    SetAllFeatures ();
    return;
  }
  field = _featureListStr.ExtractToken (", \n\r\t");
  while (!field.Empty ())
  {
    _featureListStr.TrimLeft ();
   
    kkint32 dashPos = field.LocateCharacter ('-');
    if (dashPos < 0)
    {
      // This is not a range
      featureNum = kkuint16 (atoi (field.Str ()));
      //if (field.ValidInt (featureNum))
      {
        if (featureNum >= fileDesc->NumOfFields ())
        {
          _valid = false;
          return;
        }
        else
        {
          bool alreadyInList = InList (featureNum);
          if (!alreadyInList)
            AddFeature (featureNum);
        }
      }
    }
    else
    {
      // We are looking at a range
      kkuint16 startFeatureNum = kkuint16 (field.ExtractTokenInt (" -"));
      kkuint16 endFeatureNum = kkuint16 (field.ExtractTokenInt (" -"));
      if ((startFeatureNum >= fileDesc->NumOfFields ()) ||
           (endFeatureNum >= fileDesc->NumOfFields ()) ||
           (startFeatureNum > endFeatureNum)
          )
      {
         _valid = false;
      }
      else
      {
        for (featureNum = startFeatureNum; featureNum <= endFeatureNum; featureNum++)
        {
          bool alreadyInList = InList (featureNum);
          if (!alreadyInList)
            AddFeature (featureNum);
        }
      }
    }
    field = _featureListStr.ExtractToken (", \n\r\t");
  }
} /* ExtractFeatureNumsFromStr */
AttributeType FeatureNumList::FeatureAttributeType (kkint32 idx) const
Definition at line 1092 of file FeatureNumList_Old.cpp.
{
  if ((idx < 0) || (idx >= numOfFeatures))
  {
    cerr << endl << endl
         << "FeatureNumList::AttributeType *** ERROR ***" << endl
         << endl
         << " Invalid Index[" << idx << "] Valid Range (0.." << (numOfFeatures - 1) << ")"
      << endl
         << endl;
    return NULLAttribute;
  }
  if (!fileDesc)
  {
    KKStr errMsg = "FeatureNumList::AttributeType ***ERROR*** 'fileDesc == NULL' There is a major
       programing flaw.";
    cerr << endl << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  return fileDesc->Type (featureNums[idx]);
} /* FeatureAttributeType */
const kkuint16* KKMLL::FeatureNumList::FeatureNums () const [inline]
Definition at line 105 of file FeatureNumList2.h.
{return featureNums;}
const kkuint16* KKMLL::FeatureNumList::FeatureNums () const [inline]
Definition at line 119 of file FeatureNumList.h.
{return featureNums;}
const kkuint16* KKMLL::FeatureNumList::FeatureNums () const [inline]
Definition at line 146 of file FeatureNumList_Old.h.
Referenced by operator+=().
{return featureNums;}
FileDescPtr KKMLL::FeatureNumList::FileDesc () const [inline]
Definition at line 147 of file FeatureNumList_Old.h.
{return fileDesc;}
bool FeatureNumList::InList (kkuint16 featureNum) const
returns true if '_featureNum' is one of the selected features.
Definition at line 381 of file FeatureNumList.cpp.
{
  bool found = false;
  kkint32 x = 0;
  while ((x < numOfFeatures) && (!found))
  {
    found = (_featureNum == featureNums[x]);
    if (!found)
      x++;
  }
  return found;
} /* InList */
bool KKMLL::FeatureNumList::InList (kkuint16 featureNum) const
returns true if '_featureNum' is one of the selected features.
bool KKMLL::FeatureNumList::InList (kkuint16 featureNum) const
returns true if '_featureNum' is one of the selected features.
Referenced by AddFeature(), IsSubSet(), and Test().
bool FeatureNumList::IsSubSet (const FeatureNumList & z)
Returns true if 'z' is a subset of this instance.
Returns true if the FeatureNumList instance 'z' is a subset of this instance.
brief Returns true if the FeatureNumList 'z' is a subset of myself.
Definition at line 365 of file FeatureNumList.cpp.
References InList(), NumSelFeatures(), and operator[]().
{
  bool isSubSet = true;
  kkint32 idx = 0;
  while ((idx < z.NumSelFeatures ()) && isSubSet)
  {
    kkint32 fn = z[idx];
    isSubSet = InList (fn);
    idx++;
  }
  return isSubSet;
}
bool KKMLL::FeatureNumList::IsSubSet (const FeatureNumList & z)
Returns true if 'z' is a subset of this instance.
bool KKMLL::FeatureNumList::IsSubSet (const FeatureNumList & z)
Returns true if 'z' is a subset of this instance.
void FeatureNumList::Load (const KKStr & _fileName, bool & _successful, RunLog & _log)
Definition at line 564 of file FeatureNumList2.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::osFOPEN(), and KKB::KKStr::Str().
{
  _log.Level (20) << "FeatureNumList::Load - File[" << _fileName << "]." <<
      endl;
  delete featureNums;
  featureNums = NULL;
  featureNumsAllocatedSize = 0;
  numOfFeatures = 0;
  maxFeatureNum = 0;
  FILE* inputFile = osFOPEN (_fileName.Str (), "r");
  if (!inputFile)
  {
    _log.Level (-1) << endl << "FeatureNumList::Load ***ERROR*** Could Not Open File[" <<
      _fileName << "]." << endl << endl;
    _successful = false;
    return;
  }
  kkuint16 mfn = 0;
  kkuint16 nof = 0;
  KKStr featureNumStr = "";
  kkint32 fileDescNumOfFields = 0;
  char buff [102400];
  while (fgets (buff, sizeof (buff), inputFile))
  {
    KKStr line (buff);
    KKStr fieldName = line.ExtractToken2 ("\n\t\r").Trim ();
    if (fieldName.EqualIgnoreCase ("MaxFeatureNum"))
      mfn = (kkuint16)line.ExtractTokenUint ("\t\n\r");
    else if (fieldName.EqualIgnoreCase ("NumOfFeatures"))
      nof = (kkuint16)line.ExtractTokenUint ("\t\n\r");
    else if (fieldName.EqualIgnoreCase ("FeatureNums"))
      featureNumStr = (kkuint16)line.ExtractTokenUint ("\t\n\r");
  }
  fclose (inputFile);
  
  if (mfn < 1)
  {
    _log.Level (-1) << endl << "FeatureNumList::Load ***ERROR*** 'maxFeatureNum' was not defined.
      " << endl << endl;
    _successful = false;
  }
  if (featureNumStr.Empty ())
  {
    _log.Level (-1) << endl << "FeatureNumList::Load ***ERROR*** 'featureNums' was not specified.
      " << endl << endl;
    _successful = false;
    return;
  }
  VectorUint16* list = StrToUInt16Vetor (featureNumStr);
  if (!list)
  {
    _log.Level (-1) << endl << "FeatureNumList::Load ***ERROR*** 'featureNums' included invalid
       features." << endl << endl;
    _successful = false;
    return;
  }
  kkuint16 firstNum = (*list)[0];
  kkuint16 lastNum = (*list)[list->size () - 1];
  if (lastNum > mfn)
  {
    _log.Level (-1) << endl << "FeatureNumList::Load ***ERROR*** 'featureNums' included features[
      " << lastNum << "] which is larger than maxFeaureNum[" << maxFeatureNum << "]" << endl <<
      endl;
    _successful = false;
  }
  else if (list->size () != nof)
  {
    _log.Level (-1) << endl << "FeatureNumList::Load ***ERROR*** numOfFeatures[" << nof << "] did
       not agree with number of features specified in FeatureNums" << endl << endl;
    _successful = false;
  }
  if (_successful)
  {
    maxFeatureNum = mfn;
    AllocateArraySize (nof + 1);
    VectorUint16::const_iterator idx;
    for (idx = list->begin (); idx != list->end (); ++idx)
      AddFeature (*idx);
  }
  delete list;
  list = NULL;
  return;
} /* Load */
void KKMLL::FeatureNumList::Load (const KKStr & _fileName, bool & _successful, RunLog & _log)
kkint32 KKMLL::FeatureNumList::MaxFeatureNum () const [inline]
Definition at line 106 of file FeatureNumList2.h.
Referenced by FeatureNumList(), and operator=().
{return maxFeatureNum;}
kkint32 KKMLL::FeatureNumList::MaxFeatureNum () const [inline]
Definition at line 120 of file FeatureNumList.h.
{return maxFeatureNum;}
kkint32 FeatureNumList::MemoryConsumedEstimated () const
Definition at line 135 of file FeatureNumList.cpp.
{
  kkint32 memoryConsumedEstimated = sizeof (FeatureNumList);
  if (featureNums)
    memoryConsumedEstimated += sizeof (kkuint16) * featureNumsAllocatedSize;
  return memoryConsumedEstimated;
} /* MemoryConsumedEstimated */
kkint32 KKMLL::FeatureNumList::MemoryConsumedEstimated () const
kkint32 KKMLL::FeatureNumList::MemoryConsumedEstimated () const
Referenced by KKMLL::ModelParam::MemoryConsumedEstimated(), KKMLL::BinaryClassParms::MemoryConsumedEstimated(), KKMLL::FeatureEncoder::MemoryConsumedEstimated(), and KKMLL::SVMparam::MemoryConsumedEstimated().
kkint32 KKMLL::FeatureNumList::NumOfFeatures () const [inline]
Definition at line 107 of file FeatureNumList2.h.
{return numOfFeatures;}
kkint32 KKMLL::FeatureNumList::NumOfFeatures () const [inline]
Definition at line 121 of file FeatureNumList.h.
{return numOfFeatures;}
kkint32 KKMLL::FeatureNumList::NumOfFeatures () const [inline]
Definition at line 148 of file FeatureNumList_Old.h.
Referenced by KKMLL::SVMparam::AvgMumOfFeatures(), KKMLL::ModelParam::AvgMumOfFeatures(), KKMLL::SVMparam::AvgNumOfFeatures(), Compare(), KKMLL::FeatureEncoder::FeatureEncoder(), KKMLL::FeatureEncoder2::FeatureEncoder2(), KKMLL::BinaryClassParms::NumOfFeatures(), KKMLL::ModelParam::NumOfFeaturesAfterEncoding(), KKMLL::SVMparam::NumOfFeaturesAfterEncoding(), operator+=(), operator=(), KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::FeatureFileIOUCI::SaveFile(), KKMLL::FeatureFileIOC45::SaveFile(), KKMLL::FeatureFileIOSparse::SaveFile(), and ToBitString().
{return numOfFeatures;}
kkint32 KKMLL::FeatureNumList::NumSelFeatures () const [inline]
Definition at line 108 of file FeatureNumList2.h.
{return numOfFeatures;}
kkint32 KKMLL::FeatureNumList::NumSelFeatures () const [inline]
Definition at line 122 of file FeatureNumList.h.
{return numOfFeatures;}
kkint32 KKMLL::FeatureNumList::NumSelFeatures () const [inline]
Definition at line 149 of file FeatureNumList_Old.h.
Referenced by KKMLL::SVMparam::AvgNumOfFeatures(), SVM289_MFS::Kernel::DotStatic(), SVM289_BFS::Kernel::DotStatic(), IsSubSet(), SVM289_MFS::Kernel::k_function(), SVM289_BFS::Kernel::k_function(), SVM289_MFS::Kernel::Kernel(), SVM289_BFS::Kernel::Kernel(), and KKMLL::FeatureFileIOColumn::SaveFile().
{return numOfFeatures;}
FeatureNumList FeatureNumList::operator* (const FeatureNumList & rightSide) const
Returns new instance that is the intersection of features.
Performs a logical 'AND' operation on the two FeatureNumList instances.
Returns the intersection of the two FeatureNumList instances.
Will return a new FeatureNumList instance that will consist of a list of features that are selected in both the left and right FeatureNumList instances.
Will return a new FeatureNumList instance that will consist of a list of features that are selected in both the left and right FeatureNumList instances. Both FeatureNumList objects must be referencing the same FileDesc instance otherwise an exception will be thrown.
Definition at line 786 of file FeatureNumList.cpp.
References AddFeature(), and FeatureNumList().
{
  kkuint16 mfn = Max (maxFeatureNum, rightSide.MaxFeatureNum ());
  kkuint16 bestCaseNof = Min (numOfFeatures, rightSide.NumOfFeatures ());
  FeatureNumList result (mfn);
  result.AllocateArraySize (bestCaseNof);
  kkint32 l = 0;
  kkint32 r = 0;
  while ((l < numOfFeatures) && (r < rightSide.numOfFeatures))
  {
    if (featureNums[l] < rightSide.featureNums[r])
      l++;
    else if (featureNums[l] > rightSide.featureNums[r])
      r++;
    else
    {
      result.AddFeature (featureNums[l]);
      l++;
      r++;
    }
  }
  return result;
} /* operator* */
FeatureNumList KKMLL::FeatureNumList::operator* (const FeatureNumList & rightSide) const
Returns new instance that is the intersection of features.
FeatureNumList KKMLL::FeatureNumList::operator* (const FeatureNumList & rightSide) const
Returns new instance that is the intersection of features.
FeatureNumList FeatureNumList::operator+ (const FeatureNumList & rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
Performs a logical 'OR' operation on the two FeatureNumList instances.
Will return a new FeatureNumList instance that will consist of a list of features that are in either left and right FeatureNumList instances. Both FeatureNumList objects must be referencing the same FileDesc instance otherwise an exception will be thrown.
Definition at line 824 of file FeatureNumList.cpp.
References AddFeature(), and FeatureNumList().
{
  FeatureNumList result (rightSide);
  kkint32 l = 0;
  for (l = 0; l < numOfFeatures; l++)
    result.AddFeature (featureNums[l]);
  return result;
} /* operator+ */
FeatureNumList FeatureNumList::operator+ (kkuint16 rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
Returns a new FeatureNumList instance that will consists of the left FeatureNumList instance with 'rightSide' feature added in.
Definition at line 867 of file FeatureNumList.cpp.
References AddFeature(), and FeatureNumList().
{
  FeatureNumList result (*this);
  result.AddFeature (rightSide);
  return result;
} /* operator+ */
FeatureNumList KKMLL::FeatureNumList::operator+ (const FeatureNumList & rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList KKMLL::FeatureNumList::operator+ (kkuint16 rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList KKMLL::FeatureNumList::operator+ (const FeatureNumList & rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList KKMLL::FeatureNumList::operator+ (kkuint16 rightSide) const
Returns new FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList & FeatureNumList::operator+= (const FeatureNumList & rightSide)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
Adds the features that are selected in the right FeatureNumList instance to the left instance.
Both FeatureNumList objects must be referencing the same FileDesc instance otherwise an exception will be thrown.
Definition at line 841 of file FeatureNumList.cpp.
References AddFeature(), FeatureNums(), and NumOfFeatures().
{
  const kkuint16* rightFeatureNums = rightSide.FeatureNums ();
  kkuint16 rightNumOfFeatures = rightSide.NumOfFeatures ();
  for (kkuint16 x = 0; x < rightNumOfFeatures; ++x)
    AddFeature (rightFeatureNums[x]);
  return *this;
} /* operator+= */
FeatureNumList & FeatureNumList::operator+= (kkuint16 featureNum)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
Adds the feature 'featureNum' to the selected list of features.
Definition at line 856 of file FeatureNumList.cpp.
References AddFeature().
{
  AddFeature (featureNum);
  return *this;
} /* operator+= */
FeatureNumList& KKMLL::FeatureNumList::operator+= (const FeatureNumList & rightSide)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList& KKMLL::FeatureNumList::operator+= (kkuint16 featureNum)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList& KKMLL::FeatureNumList::operator+= (const FeatureNumList & rightSide)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList& KKMLL::FeatureNumList::operator+= (kkuint16 featureNum)
Returns this FeatureNumList that is a union of this instance and 'rightSide'.
FeatureNumList FeatureNumList::operator- (const FeatureNumList & rightSide) const
Returns a new FeatureNumList instance that consists of the left side instance with the selected features in the right side removed.
Removes features that are selected in 'rightSide' from this instance and returns the result.
Both FeatureNumList objects must be referencing the same FileDesc instance otherwise an exception will be thrown.
Definition at line 893 of file FeatureNumList.cpp.
References AddFeature(), and FeatureNumList().
{
  FeatureNumList result (maxFeatureNum);
  kkint32 l = 0;
  kkint32 r = 0;
  while ((l < numOfFeatures) && (r < rightSide.numOfFeatures))
  {
    if (featureNums[l] < rightSide.featureNums[r])
    {
      result.AddFeature (featureNums[l]);
      l++;
    }
    else if (featureNums[l] > rightSide.featureNums[r])
      r++;
    else
    {
      l++;
      r++;
    }
  }
  return result;
} /* operator- */
FeatureNumList FeatureNumList::operator- (kkuint16 rightSide) const
Returns a new FeatureNumList instance that will consists of the left FeatureNumList instance with 'rightSide' removed from it.
Returns this instance with the feature specified by 'rightSide' removed.
Definition at line 878 of file FeatureNumList.cpp.
References FeatureNumList(), and UnSet().
{
  FeatureNumList result (*this);
  result.UnSet (rightSide);
  return result;
} /* operator- */
FeatureNumList KKMLL::FeatureNumList::operator- (const FeatureNumList & rightSide) const
Removes features that are selected in 'rightSide' from this instance and returns the result.
FeatureNumList KKMLL::FeatureNumList::operator- (kkuint16 rightSide) const
Returns this instance with the feature specified by 'rightSide' removed.
FeatureNumList KKMLL::FeatureNumList::operator- (const FeatureNumList & rightSide) const
Removes features that are selected in 'rightSide' from this instance and returns the result.
FeatureNumList KKMLL::FeatureNumList::operator- (kkuint16 rightSide) const
Returns this instance with the feature specified by 'rightSide' removed.
FeatureNumList & FeatureNumList::operator-= (kkuint16 rightSide)
removes the feature specified on the right side from the FeatureNumList on the left side.
Remove the feature specified by 'rightSide' from this instance.
Definition at line 925 of file FeatureNumList.cpp.
References UnSet().
{
  UnSet (rightSide);
  return *this;
} /* operator-= */
FeatureNumList& KKMLL::FeatureNumList::operator-= (kkuint16 rightSide)
Remove the feature specified by 'rightSide' from this instance.
FeatureNumList& KKMLL::FeatureNumList::operator-= (kkuint16 rightSide)
Remove the feature specified by 'rightSide' from this instance.
bool FeatureNumList::operator< (const FeatureNumList & _features) const
Indicates if the Left FeatureNumList instances is less than the right one.
Indicates if the Left FeatureNumLiost instances is less than the right one.
See also
Compare
Definition at line 741 of file FeatureNumList.cpp.
References Compare().
{
  return Compare (_features) < 0;
} /* operator< */
bool KKMLL::FeatureNumList::operator< (const FeatureNumList & _features) const
Indicates if the Left FeatureNumList instances is less than the right one.
bool KKMLL::FeatureNumList::operator< (const FeatureNumList & _features) const
Indicates if the Left FeatureNumList instances is less than the right one.
FeatureNumList & FeatureNumList::operator= (const FeatureNumList & _features)
Definition at line 648 of file FeatureNumList.cpp.
References MaxFeatureNum(), and NumOfFeatures().
{
  delete featureNums;
  featureNums = NULL;
  numOfFeatures = _features.NumOfFeatures ();
  maxFeatureNum = _features.MaxFeatureNum ();
  featureNums = new kkuint16[numOfFeatures];
  featureNumsAllocatedSize = numOfFeatures;
  for (kkint32 x = 0; x < numOfFeatures; ++x)
    featureNums[x] = _features.featureNums[x];
  return *this;
} /* operator= */
FeatureNumList & FeatureNumList::operator= (FeatureNumList && _features)
Definition at line 668 of file FeatureNumList.cpp.
{
  delete featureNums;
  featureNums = _features.featureNums;
  numOfFeatures = _features.numOfFeatures;
  maxFeatureNum = _features.maxFeatureNum;
  featureNumsAllocatedSize = _features.featureNumsAllocatedSize;
  _features.featureNums = NULL;
  _features.numOfFeatures = 0;
  _features.maxFeatureNum = 0;
  _features.featureNumsAllocatedSize = 0;
  return *this;
}
FeatureNumList& KKMLL::FeatureNumList::operator= (const FeatureNumList & _features)
FeatureNumList & FeatureNumList::operator= (const FeatureNumListPtr _features)
Definition at line 688 of file FeatureNumList.cpp.
References operator=().
{
  *this = *_features;
  return *this;
}
FeatureNumList& KKMLL::FeatureNumList::operator= (const FeatureNumListPtr _features)
FeatureNumList& KKMLL::FeatureNumList::operator= (const FeatureNumList & _features)
Referenced by operator=().
FeatureNumList& KKMLL::FeatureNumList::operator= (const FeatureNumListPtr _features)
bool FeatureNumList::operator== (const FeatureNumList & _features) const
Indicates if the two FeatureNumLiost instances have the same features selected.
Indicates if the two FeatureNumList instances have the same features selected.
Definition at line 723 of file FeatureNumList.cpp.
References Compare().
{
  if (numOfFeatures != _features.numOfFeatures)
  {
    // No point even comparing the list of feature numbers, if the lengths are
    // different, then they can not be equal.
    return false;
  }
  return Compare (_features) == 0;
} /* operator== */
bool KKMLL::FeatureNumList::operator== (const FeatureNumList & _features) const
Indicates if the two FeatureNumLiost instances have the same features selected.
bool KKMLL::FeatureNumList::operator== (const FeatureNumList & _features) const
Indicates if the two FeatureNumLiost instances have the same features selected.
bool FeatureNumList::operator> (const FeatureNumList & _features) const
Indicates if the Left FeatureNumList instances is greater than the right one.
Indicates if the Left FeatureNumLiost instances is greater than the right one.
See also
Compare
Definition at line 752 of file FeatureNumList.cpp.
References Compare().
{
  return Compare (_features) > 0;
} /* operator> */
bool KKMLL::FeatureNumList::operator> (const FeatureNumList & _features) const
Indicates if the Left FeatureNumList instances is greater than the right one.
bool KKMLL::FeatureNumList::operator> (const FeatureNumList & _features) const
Indicates if the Left FeatureNumList instances is greater than the right one.
kkuint16 FeatureNumList::operator[] (kkint32 idx) const
Definition at line 405 of file FeatureNumList.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), and KKB::KKStr::KKStr().
{
  if (_idx >= numOfFeatures)
  {
    KKStr errMsg (100);
    errMsg << "FeatureNumList::operator[] ***ERROR*** Invalid Index[" << _idx << "] requested.";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  else
  {
    return featureNums[_idx];
  }
}
kkuint16 KKMLL::FeatureNumList::operator[] (kkint32 idx) const
Returns back the selected feature.
A FeatureNumList instance consists of a list of selected features. It is logically like an array of selected features that is the same length as the number of selected features.
Example code that scans the FeatureNumList object 'goodFeatures'
void PrintSelectedFeatures (const FeatureNumList& goodFeatures)
{
  cout << "Selected Features: ";
  for (kkint32 x = 0; x < goodFeatures.NumOfFeatures ();
  {
    if (x > 0) cout << ",";
    cout << goodFeatures[x];
  }
  cout << endl;
}
Parameters
in _idx The position in this instance that you want to return.
Returns
Selected feature at position '_idx'.
kkuint16 KKMLL::FeatureNumList::operator[] (kkint32 idx) const
Returns back the selected feature.
A FeatureNumList instance consists of a list of selected features. It is logically like an array of selectedfeatures that is the same length as the number of selected features.
Example code that scans the FeatureNumList object 'goodFeatures'
void PrintSelectedFeatures (const FeatureNumList& goodFeatures)
{
  cout << "Selected Features: ";
  for (kkint32 x = 0; x < goodFeatures.NumOfFeatures ();
  {
    if (x > 0) cout << ",";
    cout << goodFeatures[x];
  }
  cout << endl;
}
Parameters
in _idx The position in this instance that you want to return.
Returns
Selected feature at position '_idx'.
Referenced by SVM289_MFS::Kernel::DotStatic(), SVM289_BFS::Kernel::DotStatic(), KKMLL::FeatureEncoder::FeatureEncoder(), KKMLL::FeatureEncoder2::FeatureEncoder2(), IsSubSet(), SVM289_MFS::Kernel::k_function(), SVM289_BFS::Kernel::k_function(), SVM289_MFS::Kernel::Kernel(), SVM289_BFS::Kernel::Kernel(), KKMLL::ModelParam::NumOfFeaturesAfterEncoding(), KKMLL::SVMparam::NumOfFeaturesAfterEncoding(), KKMLL::FeatureFileIOColumn::SaveFile(), KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::FeatureFileIOUCI::SaveFile(), KKMLL::FeatureFileIOC45::SaveFile(), and KKMLL::FeatureFileIOSparse::SaveFile().
void FeatureNumList::ParseToString (const KKStr & _str, bool & _valid)
Will select the features specified in `featureListStr`.
The format is a comma delimited string, where each number represents a feature, ranges can be specified with a dash(`-`). `All` will select all features that are not flagged as a 'Ignore' in the associated FileDesc instance.
ex's: String Selected Features
       "1,2,3,10,20" [1,2,3,10, 20].
       "1,4-7,9-12,23" [1,4,5,6,7,9,10,11,12,23]
       "All" Selects all features that '_fileDesc' includes accept those that are
                        flagged as 'Ignore' in the associated FileDesc instance.
Definition at line 546 of file FeatureNumList.cpp.
References KKB::KKStr::EqualIgnoreCase().
Referenced by FeatureNumList(), and ReadXML().
{
  _valid = true;
  delete featureNums;
  featureNumsAllocatedSize = 0;
  maxFeatureNum = 0;
  numOfFeatures = 0;
  featureNums = NULL;
  if (_str.EqualIgnoreCase ("NONE"))
  {
    maxFeatureNum = 1;
    AllocateArraySize (maxFeatureNum + 1);
    return;
  }
  VectorUint16* list = StrToUInt16Vetor (_str);
  if (list)
  {
    sort(list->begin (), list->end ());
    maxFeatureNum = list->back ();
    AllocateArraySize ((kkuint16)list->size ());
    for (auto idx: *list)
      AddFeature (idx);
  }
  else
  {
    _valid = false;
  }
  delete list;
  list = NULL;
} /* ParseToString */
FeatureNumListPtr KKMLL::FeatureNumList::RandomlySelectFeatures (kkint32 numToKeep) const
Generates a new FeatureNumList object that will select at random 'numToKeep' features from this instance.
Parameters
in numToKeep Number of features to select randomly from existing instance.
Returns
Dynamically allocated instance of a ImageFeaturesList with randomly selected features.
FeatureNumListPtr FeatureNumList::RandomlySelectFeatures (kkint32 numToKeep) const
Generates a new FeatureNumList object that will select at random 'numToKeep' features from this instance.
Parameters
in numToKeep Number of features to select randomly from existing instance.
Returns
Dynamically allocated instance of a ImageFeaturesList with randomly selected features.
Definition at line 933 of file FeatureNumList.cpp.
References AddFeature(), FeatureNumList(), and KKB::LRand48().
{
  if (numToKeep > numOfFeatures)
  {
    cerr << endl
         << endl
         << "FeatureNumList::RandomlySelectFeatures *** ERROR ***" << endl
         << endl
         << "NumToKeep[" << numToKeep << "] Is greater than NumOfFeatures[" << numOfFeatures << "]" <<
      endl
         << endl
         << endl;
    numToKeep = numOfFeatures;
  }
  FeatureNumListPtr randomlySelectedFeatures = new
      FeatureNumList (maxFeatureNum);
  kkint32 x, y, z;
  // Initialize Selected Features to the currently selected features in featureNums
  kkuint16* selectedFeatures = new kkuint16[numOfFeatures];
  for (x = 0; x < numOfFeatures; x++)
    selectedFeatures[x] = featureNums[x];
  // Randomize the order of the selected featured
  //for (x = 0; x < numOfFeatures; x++)
  for (x = 0; x < numToKeep; x++)
  {
    y = LRand48() % numOfFeatures;
    z = selectedFeatures[x];
    selectedFeatures[x] = selectedFeatures[y];
    selectedFeatures[y] = z;
  }
  // Assign the first 'numToKeep' featured from the random order of selected features
  for (x = 0; x < numToKeep; x++)
    randomlySelectedFeatures->AddFeature (selectedFeatures[x]);
  delete [] selectedFeatures;
  return randomlySelectedFeatures;
} /* RandomlySelectFeatures */
FeatureNumListPtr KKMLL::FeatureNumList::RandomlySelectFeatures (kkint32 numToKeep) const
Generates a new FeatureNumList object that will select at random 'numToKeep' features from this instance.
Parameters
in numToKeep Number of features to select randomly from existing instance.
Returns
Dynamically allocated instance of a ImageFeaturesList with randomly selected features.
void FeatureNumList::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 605 of file FeatureNumList.cpp.
References KKB::XmlTag::AttributeValueInt32(), KKB::XmlContent::Content(), KKB::XmlStream::GetNextToken(), and ParseToString().
{
  maxFeatureNum = tag->AttributeValueInt32 ("MaxFeatureNum");
  kkuint32 expectedNumOfFeatures = tag->AttributeValueInt32 ("NumOfFeatures");
  numOfFeatures = 0;
  kkuint32 featureCountRead = 0;
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (typeid (*t) == typeid(XmlContent))
    {
      XmlContentPtr c = dynamic_cast<XmlContentPtr> (t);
      if (c && (c->Content ()))
      {
        bool valid = false;
        ParseToString (*(c->Content ()), valid);
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
  if (expectedNumOfFeatures != numOfFeatures)
  {
    log.Level (-1) << endl
      << "FeatureNumList::ReadXML ***ERROR*** expectedNumOfFeatures[" << expectedNumOfFeatures << "]
       not equal numOfFeatures[" << numOfFeatures << "]" << endl
      << endl;
  }
} /* ReadXML */
void FeatureNumList::Save (const KKStr & fileName)
Definition at line 659 of file FeatureNumList2.cpp.
{
  ofstream outFile (fileName.Str ());
  outFile << "MaxFeatureNum" << "\t" << maxFeatureNum << endl;
  outFile << "NumOfFeatures" << "\t" << numOfFeatures << endl;
  outFile << "FeatureNums" << "\t" << ToString () << endl;
  outFile.close ();
} /* Save */
void FeatureNumList::Save (const KKStr & _fileName, bool & _successful, RunLog & _log)
Definition at line 682 of file FeatureNumList_Old.cpp.
{
  _log.Level (20) << "FeatureNumList::Save - File["
                  << _fileName << "]."
                  << endl;
  _successful = true;
  ofstream outFile (_fileName.Str ());
  outFile << fileDesc->NumOfFields () << endl;
  outFile << ToString () << endl;
  outFile.close ();
} /* Save */
void KKMLL::FeatureNumList::Save (std::ostream & o)
void FeatureNumList::SaveXML (std::ostream & o)
Definition at line 671 of file FeatureNumList2.cpp.
{
  o << "<FeatureNumList>" << "\t"
    << "MaxFeatureNum" << "\t" << maxFeatureNum << "\t"
    << "NumOfFeatures" << "\t" << numOfFeatures << "\t"
    << "FeatureNums" << "\t" << ToString ()
    << "</FeatureNumList>";
} /* Save */
void KKMLL::FeatureNumList::SetAllFeatures (FileDescPtr fileDesc)
Selects all features except those flagged as 'IgnoreAttribute' in the associated FileDesc.
Referenced by KKMLL::SVMparam::SelectedFeatures(), and KKMLL::TrainingConfiguration2::TrainingConfiguration2().
void FeatureNumList::SetAllFeatures (FileDescPtr fileDesc)
Selects all features except those flagged as 'Ignore' in the associated FileDesc.
Using 'fileDesc' as the guide as to how many features there are and which ones are to be ignored will set all features that are not 'Ignore' to on.
Using 'fileDesc' as the guide as to how many features there are and which ones are to be ignored will set all features that are not 'IgnoreAttribute' to on.
Definition at line 349 of file FeatureNumList.cpp.
References AddFeature(), KKMLL::Ignore, and KKMLL::FileDesc::Type().
{
  for (kkuint16 x = 0; x <= maxFeatureNum; ++x)
  {
    if (fileDesc->Type (x) != AttributeType::Ignore)
      AddFeature (kkuint16 (x));
  }
  return;
} /* SetAllFeatures */
void FeatureNumList::SetAllFeatures ()
Selects all features except those flagged as 'IgnoreAttribute' in the associated FileDesc.
Definition at line 408 of file FeatureNumList_Old.cpp.
Referenced by ExtractFeatureNumsFromStr().
{
  for (kkuint16 x = 0; x < fileDesc->NumOfFields (); ++x)
  {
    if (fileDesc->Type (x) != IgnoreAttribute)
      AddFeature (kkuint16 (x));
  }
  return;
} /* SetAllFeatures */
bool KKMLL::FeatureNumList::Test (kkuint16 _featureNum) const
Indicates whether feature '_featureNum' is selected.
bool FeatureNumList::Test (kkuint16 _featureNum) const
Indicates whether feature '_featureNum' is selected.
Definition at line 398 of file FeatureNumList.cpp.
References InList().
{
  return InList (_featureNum);
} /* Test */
bool KKMLL::FeatureNumList::Test (kkuint16 _featureNum) const
Indicates whether feature '_featureNum' is selected.
void KKMLL::FeatureNumList::ToBitString (BitString & bitStr) const
void FeatureNumList::ToBitString (BitString & bitStr) const
Definition at line 185 of file FeatureNumList.cpp.
References NumOfFeatures(), KKB::BitString::ReSet(), and KKB::BitString::Set().
{
  bitStr.ReSet ();
  kkint32 x;
  for (x = 0; x < NumOfFeatures (); x++)
    bitStr.Set (featureNums[x]);
} /* ToBitString */
void KKMLL::FeatureNumList::ToBitString (BitString & bitStr) const
Referenced by ToHexString().
KKStr KKMLL::FeatureNumList::ToCommaDelStr () const [inline]
Definition at line 191 of file FeatureNumList2.h.
References ToString().
{return ToString ();}
KKStr KKMLL::FeatureNumList::ToCommaDelStr () const [inline]
Definition at line 201 of file FeatureNumList.h.
References ToString().
{return ToString ();}
KKStr KKMLL::FeatureNumList::ToCommaDelStr () const [inline]
Definition at line 233 of file FeatureNumList_Old.h.
References ToString().
Referenced by KKMLL::ModelParam::ToCmdLineStr().
{return ToString ();}
KKStr KKMLL::FeatureNumList::ToHexString () const
Uses 'maxFeatureNum to determine length of hex string.
KKStr KKMLL::FeatureNumList::ToHexString (FileDescPtr fileDesc) const
Uses 'fileDesc' to determine length of hex string.
KKStr FeatureNumList::ToHexString () const
Uses 'maxFeatureNum to determine length of hex string.
Definition at line 468 of file FeatureNumList.cpp.
References KKB::BitString::BitString(), KKB::BitString::HexStr(), and ToBitString().
{
  BitString bs (maxFeatureNum + 1);
  ToBitString (bs);
  return bs.HexStr ();
} /* ToHexString */
KKStr FeatureNumList::ToHexString (FileDescPtr fileDesc) const
Uses 'fileDesc' to determine length of hex string.
Definition at line 477 of file FeatureNumList.cpp.
References KKB::BitString::BitString(), KKB::BitString::HexStr(), KKMLL::FileDesc::NumOfFields(), and ToBitString().
{
  BitString bs (fileDesc->NumOfFields ());
  ToBitString (bs);
  return bs.HexStr ();
} /* ToHexString */
KKStr KKMLL::FeatureNumList::ToHexString () const
KKStr KKMLL::FeatureNumList::ToString () const
Returns comma delimited list of all features selected; will make use of range specification.
KKStr FeatureNumList::ToString () const
Returns comma delimited list of all features selected; will make use of range specification.
Definition at line 422 of file FeatureNumList.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), and KKB::KKStr::KKStr().
{
  KKStr featureNumStr (numOfFeatures * 6);
  
  if (numOfFeatures <= 0)
    return featureNumStr;
  kkint32 nextIdx = 0;
  while (nextIdx < numOfFeatures)
  {
    kkint32 startOfGroup = nextIdx;
    kkint32 endOfGroup = nextIdx;
    while ((endOfGroup < (numOfFeatures - 1)) &&
            (featureNums[endOfGroup] == (featureNums[endOfGroup + 1] - 1))
           )
    {
      endOfGroup++;
    }
    if ((endOfGroup - startOfGroup) < 3)
    {
      kkint32 x;
      for (x = startOfGroup; x <= endOfGroup; x++)
      {
        if (!featureNumStr.Empty ())
          featureNumStr << ",";
        featureNumStr << featureNums[x];
      }
    }
    else
    {
      if (!featureNumStr.Empty ())
        featureNumStr << ",";
      featureNumStr << featureNums[startOfGroup] << "-" << featureNums[endOfGroup];
    }
    nextIdx = endOfGroup + 1;
  }
  return featureNumStr;
} /* ToString */
KKStr KKMLL::FeatureNumList::ToString () const
Returns comma delimited list of all features selected; will make use of range specification.
Referenced by KKMLL::operator<<(), ToCommaDelStr(), KKMLL::BinaryClassParms::ToTabDelString(), WriteXML(), KKMLL::SVMparam::WriteXML(), and KKMLL::SVMModel::WriteXML().
void KKMLL::FeatureNumList::UnSet ()
Turns off all features so that no feature is selected.
void KKMLL::FeatureNumList::UnSet (kkuint16 featureNum)
Turns off specified feature 'featureNum'; if 'featureNum' is not turned on then nothing happens; same as using 'operator-='.
void FeatureNumList::UnSet ()
Turns off all features so that no feature is selected.
Definition at line 215 of file FeatureNumList.cpp.
{
  if (featureNums)
  {
    kkint32 x;
    for (x = 0; x < featureNumsAllocatedSize; x++)
      featureNums[x] = 0;
    numOfFeatures = 0;
  }
  numOfFeatures = 0;
} /* UnSet */
void FeatureNumList::UnSet (kkuint16 featureNum)
Turns off specified feature 'featureNum'; if 'featureNum' is not turned on then nothing happens; same as using 'operator-='.
Definition at line 229 of file FeatureNumList.cpp.
{
  if (!featureNums)
    return;
  kkint32 indexToDel = numOfFeatures - 1; // Starting with last index
  while ((indexToDel >= 0) && (featureNums[indexToDel] > featureNum))
    indexToDel--;
  if (indexToDel >= 0)
  {
    if (featureNums[indexToDel] == featureNum)
    {
      // We found the index to delete.
      kkint32 x;
      for (x = indexToDel; x < (numOfFeatures - 1); x++)
        featureNums[x] = featureNums[x + 1];
    }
 
    numOfFeatures--;
    featureNums[numOfFeatures] = 0;
  }
} /* UnSet */
void KKMLL::FeatureNumList::UnSet ()
Turns off all features so that no feature is selected.
void KKMLL::FeatureNumList::UnSet (kkuint16 featureNum)
Turns off specified feature 'featureNum'; if 'featureNum' is not turned on then nothing happens; same as using 'operator-='.
Referenced by operator-(), and operator-=().
void FeatureNumList::WriteXML (const KKStr & varName, std::ostream & o) const
summary> Returns back selected feature. A FeatureNumList instance consists of a list of selected features. It is logically like an array of selected features that is the same length as the number of selected features. /summary> param name=`idx`> The position in this instance that you want to return.
returns> Selected feature at position "_idx".
Definition at line 585 of file FeatureNumList.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::operator<<(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, ToString(), KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::FeatureEncoder::WriteXML(), SVM289_MFS::Svm_Model::WriteXML(), and KKMLL::ModelParam::WriteXMLFields().
{
  XmlTag startTag ("FeatureNumList", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.AddAtribute ("MaxFeatureNum", maxFeatureNum);
  startTag.AddAtribute ("NumOfFeatures", numOfFeatures);
  startTag.WriteXML (o);
  o << ToString ();
  XmlTag endTag ("FeatureNumList", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureNumList.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureNumList2.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureNumList_Old.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureNumList.cpp
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureNumList2.cpp
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureNumList_Old.cpp