KKMLL::ModelParamDual Class Reference
#include <ModelParamDual.h>
Public Types
typedef ModelParamDual * ModelParamDualPtr
enum ProbFusionMethod { ProbFusionMethod::Null,
ProbFusionMethod::Or,
ProbFusionMethod::And
 }
Public Member Functions
ModelParamDual ()
ModelParamDual (const KKStr &_configFileName1, const KKStr &_configFileName2, bool _fullHierarchyMustMatch)
ModelParamDual (const ModelParamDual &_param)
virtual ~ModelParamDual ()
const KKStr & ConfigFileName1 () const
const KKStr & ConfigFileName2 () const
virtual ModelParamDualPtr Duplicate () const
bool FullHierarchyMustMatch () const
virtual ModelParamTypes ModelParamType () const
MLClassPtr OtherClass () const
void OtherClass (MLClassPtr _otherClass)
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
virtual KKStr ToCmdLineStr () const
Creates a Command Line String that represents these parameters.
virtual void WriteXML (const KKStr &varName, ostream &o) const
Static Public Member Functions
static ProbFusionMethod ProbFusionMethodFromStr (const KKStr &s)
static KKStr ProbFusionMethodToStr (ProbFusionMethod pfm)
Detailed Description
Parameters used for the Dual Classifier. *
See also
Model
Definition at line 17 of file ModelParamDual.h.
Member Typedef Documentation
typedef ModelParamDual* KKMLL::ModelParamDual::ModelParamDualPtr
Definition at line 20 of file ModelParamDual.h.
Member Enumeration Documentation
enum KKMLL::ModelParamDual::ProbFusionMethod [strong]
Enumerator
Null
Or
And
Definition at line 22 of file ModelParamDual.h.
    {
      Null,
      Or,
      And
    };
Constructor & Destructor Documentation
ModelParamDual::ModelParamDual ()
Definition at line 31 of file ModelParamDual.cpp.
References KKB::KKStr::KKStr(), KKMLL::ModelParam::ModelParam(), and Or.
                                :
  ModelParam (),
  configFileName1 (),
  configFileName2 (),
  fullHierarchyMustMatch (false),
  otherClass (NULL),
  probFusionMethod (ProbFusionMethod::Or)
{
}
ModelParamDual::ModelParamDual (const KKStr & _configFileName1, const KKStr & _configFileName2, bool _fullHierarchyMustMatch)
Definition at line 44 of file ModelParamDual.cpp.
References KKB::KKStr::KKStr(), KKMLL::ModelParam::ModelParam(), and Or.
                                 :
  ModelParam (),
  configFileName1 (_configFileName1),
  configFileName2 (_configFileName2),
  fullHierarchyMustMatch (_fullHierarchyMustMatch),
  otherClass (NULL),
  probFusionMethod (ProbFusionMethod::Or)
{
}
ModelParamDual::ModelParamDual (const ModelParamDual & _param)
Definition at line 65 of file ModelParamDual.cpp.
References KKB::KKStr::KKStr(), and KKMLL::ModelParam::ModelParam().
Referenced by Duplicate().
                                                             :
  ModelParam (_param),
  configFileName1 (_param.configFileName1),
  configFileName2 (_param.configFileName2),
  fullHierarchyMustMatch (_param.fullHierarchyMustMatch),
  otherClass (_param.otherClass),
  probFusionMethod (_param.probFusionMethod)
{
}
ModelParamDual::~ModelParamDual () [virtual]
Definition at line 77 of file ModelParamDual.cpp.
{
}
Member Function Documentation
const KKStr& KKMLL::ModelParamDual::ConfigFileName1 () const [inline]
Definition at line 49 of file ModelParamDual.h.
Referenced by KKMLL::ModelDual::TrainModel().
{return configFileName1;}
const KKStr& KKMLL::ModelParamDual::ConfigFileName2 () const [inline]
Definition at line 50 of file ModelParamDual.h.
Referenced by KKMLL::ModelDual::TrainModel().
{return configFileName2;}
ModelParamDualPtr ModelParamDual::Duplicate () const [virtual]
Implements KKMLL::ModelParam.
Definition at line 117 of file ModelParamDual.cpp.
References ModelParamDual().
{
  return new ModelParamDual (*this);
} /* Duplicate */
bool KKMLL::ModelParamDual::FullHierarchyMustMatch () const [inline]
Definition at line 51 of file ModelParamDual.h.
Referenced by KKMLL::ModelDual::ReconcilePredictions().
{return fullHierarchyMustMatch;}
virtual ModelParamTypes KKMLL::ModelParamDual::ModelParamType () const [inline], [virtual]
Implements KKMLL::ModelParam.
Definition at line 54 of file ModelParamDual.h.
References KKMLL::ModelParam::Dual.
{return ModelParamTypes::Dual;}
MLClassPtr KKMLL::ModelParamDual::OtherClass () const [inline]
Definition at line 52 of file ModelParamDual.h.
Referenced by KKMLL::ModelDual::ReconcilePredictions().
{return otherClass;}
void KKMLL::ModelParamDual::OtherClass (MLClassPtr _otherClass) [inline]
Definition at line 56 of file ModelParamDual.h.
{otherClass = _otherClass;}
ModelParamDual::ProbFusionMethod ModelParamDual::ProbFusionMethodFromStr (const KKStr & s) [static]
Definition at line 82 of file ModelParamDual.cpp.
References And, KKB::KKStr::EqualIgnoreCase(), Null, and Or.
{
  if (s.EqualIgnoreCase ("And"))
    return ProbFusionMethod::And;
  else if (s.EqualIgnoreCase ("Or"))
    return ProbFusionMethod::Or;
  else
    return ProbFusionMethod::Null;
}
KKStr ModelParamDual::ProbFusionMethodToStr (ProbFusionMethod pfm) [static]
Definition at line 95 of file ModelParamDual.cpp.
References And, KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), Null, and Or.
Referenced by ToCmdLineStr(), and WriteXML().
{
  if ((pfm < ProbFusionMethod::Null) || (pfm >
      ProbFusionMethod::And))
    return KKStr::EmptyStr ();
  switch (pfm)
  {
  case ProbFusionMethod::And:
      return "And";
      break;
    case ProbFusionMethod::Or:
     return "Or";
     break;
  }
  return KKStr::EmptyStr ();
}
void ModelParamDual::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) [virtual]
Implements KKMLL::ModelParam.
Definition at line 278 of file ModelParamDual.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EqualIgnoreCase(), KKB::XmlStream::GetNextToken(), KKMLL::ModelParam::ReadXMLModelParamToken(), KKB::XmlElementBool::Value(), KKMLL::XmlElementMLClass::Value(), and KKB::XmlToken::VarName().
{
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    t = ReadXMLModelParamToken (t);
    if (t)
    {
      const KKStr& varName = t->VarName ();
      if (varName.EqualIgnoreCase ("ConfigFileName1"))
        configFileName1 = *(dynamic_cast<XmlElementKKStrPtr> (t)->Value ());
      else if (varName.EqualIgnoreCase ("ConfigFileName2"))
        configFileName2 = *(dynamic_cast<XmlElementKKStrPtr> (t)->Value ());
      else if (varName.EqualIgnoreCase ("FullHierarchyMustMatch"))
        fullHierarchyMustMatch = dynamic_cast<XmlElementBoolPtr> (t)->Value ();
      else if ((varName.EqualIgnoreCase ("OtherClass")) && (typeid (*t) == typeid (
      XmlElementMLClass)))
        otherClass = dynamic_cast<XmlElementMLClassPtr> (t)->Value ();
      else if (varName.EqualIgnoreCase ("ProbFusionMethod"))
        probFusionMethod = ProbFusionMethodFromStr (*(
      dynamic_cast<XmlElementKKStrPtr> (t)->Value ()));
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
} /* ReadXML */
KKStr ModelParamDual::ToCmdLineStr () const [virtual]
Creates a Command Line String that represents these parameters.
Convert all parameters to a command line string.
All derived classes should implement this method. They should first call this method and then append there own parameters that are specific to their implementation.
Reimplemented from KKMLL::ModelParam.
Definition at line 222 of file ModelParamDual.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::KKStr::KKStr(), KKMLL::MLClass::Name(), KKB::KKStr::operator=(), ProbFusionMethodToStr(), and KKMLL::ModelParam::ToCmdLineStr().
{
  KKStr cmdStr (300);
  cmdStr = ModelParam::ToCmdLineStr ();
  if (!configFileName1.Empty ())
    cmdStr << " " << "-Classifier1" << " " << configFileName1;
  if (!configFileName2.Empty ())
    cmdStr << " " << "-Classifier2" << " " << configFileName2;
  if (fullHierarchyMustMatch)
    cmdStr << " " << "-FullHierarchyMustMatch" << " " << "Yes";
  if (otherClass)
    cmdStr << " " << "-OtherClass" << " " << otherClass->Name ();
  cmdStr << " " << "-ProbFusionMethod" << " " << ProbFusionMethodToStr (this->
      probFusionMethod);
  return cmdStr;
} /* ToCmdLineStr */
void ModelParamDual::WriteXML (const KKStr & varName, ostream & o) const [virtual]
Definition at line 247 of file ModelParamDual.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), ProbFusionMethodToStr(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKMLL::MLClass::WriteXML(), KKB::XmlTag::WriteXML(), KKB::XmlElementBool::WriteXML(), KKB::KKStr::WriteXML(), KKMLL::ModelParam::WriteXMLFields(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("ModelParamDual", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  WriteXMLFields (o);
  configFileName1.WriteXML ("ConfigFileName1", o);
  configFileName2.WriteXML ("ConfigFileName1", o);
  XmlElementBool::WriteXML (fullHierarchyMustMatch, "FullHierarchyMustMatch", o);
  if (otherClass)
    otherClass->WriteXML ("OtherClass", o);
  ProbFusionMethodToStr (probFusionMethod).WriteXML ("ProbFusionMethod", o);
  XmlTag endTag ("ModelParamDual", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelParamDual.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelParamDual.cpp