KKLSC::ScannerFileEntry Class Reference
Class that keeps track of parameter details of a single scanner file.
#include <ScannerFileEntry.h>
Public Types
typedef ScannerFileEntry * ScannerFileEntryPtr
Public Member Functions
ScannerFileEntry (const KKStr &_rootName)
ScannerFileEntry (const ScannerFileEntry &entry)
~ScannerFileEntry ()
void Assign (const ScannerFileEntry &sf)
const KKStr & Description () const
void Description (const KKStr &_description)
const KKStr & FullName () const
void FullName (const KKStr &_fullName)
kkint32 MemoryConsumedEstimated ()
void ParseTabDelStr (KKStr parser)
kkuint32 PixelsPerScanLine () const
void PixelsPerScanLine (kkuint32 _pixelsPerScanLine)
const KKStr & RootName () const
void RootName (const KKStr &_rootName)
float ScanRate () const
void ScanRate (float _scanRate)
KKStr ToTabDelStr () const
Static Public Member Functions
static void CleanUp ()
static ScannerFileEntryPtr GetOrCreateScannerFileEntry (const KKStr &rootName)
static ScannerFileEntryPtr GetOrCreateScannerFileEntry (KKLSC::ScannerFilePtr scannerFile)
Detailed Description
Class that keeps track of parameter details of a single scanner file.
Definition at line 26 of file ScannerFileEntry.h.
Member Typedef Documentation
typedef ScannerFileEntry* KKLSC::ScannerFileEntry::ScannerFileEntryPtr
Definition at line 29 of file ScannerFileEntry.h.
Constructor & Destructor Documentation
ScannerFileEntry::ScannerFileEntry (const KKStr & _rootName)
Definition at line 29 of file ScannerFileEntry.cpp.
References KKB::KKStr::KKStr().
Referenced by GetOrCreateScannerFileEntry().
                                                          :
     description (),
     fullName (),
     pixelsPerScanLine (0),
     rootName (_rootName),
     scanRate (0.0f)
{
}
ScannerFileEntry::ScannerFileEntry (const ScannerFileEntry & entry)
Definition at line 41 of file ScannerFileEntry.cpp.
References KKB::KKStr::KKStr().
                                                                 :
     description (entry.description),
     fullName (entry.fullName),
     pixelsPerScanLine (entry.pixelsPerScanLine),
     rootName (entry.rootName),
     scanRate (entry.scanRate)
{
}
ScannerFileEntry::~ScannerFileEntry ()
Definition at line 53 of file ScannerFileEntry.cpp.
{
}
Member Function Documentation
void ScannerFileEntry::Assign (const ScannerFileEntry & sf)
Definition at line 121 of file ScannerFileEntry.cpp.
References KKB::KKStr::operator=().
{
  description = entry.description;
  fullName = entry.fullName;
  pixelsPerScanLine = entry.pixelsPerScanLine;
  rootName = entry.rootName;
  scanRate = entry.scanRate;
} /* ReFresh */
void ScannerFileEntry::CleanUp () [static]
Definition at line 73 of file ScannerFileEntry.cpp.
{
  delete globalList;
  globalList = NULL;
}
const KKStr& KKLSC::ScannerFileEntry::Description () const [inline]
Definition at line 40 of file ScannerFileEntry.h.
{return description;}
void KKLSC::ScannerFileEntry::Description (const KKStr & _description) [inline]
Definition at line 46 of file ScannerFileEntry.h.
References KKB::KKStr::operator=().
{description = _description;}
const KKStr& KKLSC::ScannerFileEntry::FullName () const [inline]
Definition at line 41 of file ScannerFileEntry.h.
{return fullName;}
void KKLSC::ScannerFileEntry::FullName (const KKStr & _fullName) [inline]
Definition at line 47 of file ScannerFileEntry.h.
References KKB::KKStr::operator=().
Referenced by GetOrCreateScannerFileEntry(), and KKLSC::ScannerFile::ScannerFile().
{fullName = _fullName;}
ScannerFileEntryPtr ScannerFileEntry::GetOrCreateScannerFileEntry (const KKStr & rootName) [static]
Definition at line 132 of file ScannerFileEntry.cpp.
References KKLSC::ScannerFileEntryList::AddEntry(), KKB::GlobalGoalKeeper::EndBlock(), KKLSC::ScannerFileEntryList::LookUpByRootName(), ScannerFileEntry(), KKLSC::ScannerFileEntryList::ScannerFileEntryList(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKLSC::ScannerFile::ScannerFile().
{
  ScannerFileEntryPtr entry = NULL;
  KKB::GlobalGoalKeeper::StartBlock ();
  if (globalList == NULL)
  {
    globalList = new ScannerFileEntryList ();
    atexit (CleanUp);
  }
  entry = globalList->LookUpByRootName (rootName);
  if (entry == NULL)
  {
    entry = new ScannerFileEntry (rootName);
    globalList->AddEntry (entry);
  }
  KKB::GlobalGoalKeeper::EndBlock ();
  return entry;
}
ScannerFileEntryPtr ScannerFileEntry::GetOrCreateScannerFileEntry (KKLSC::ScannerFilePtr scannerFile) [static]
Definition at line 157 of file ScannerFileEntry.cpp.
References KKLSC::ScannerFileEntryList::AddEntry(), KKB::KKStr::Concat(), KKB::GlobalGoalKeeper::EndBlock(), KKLSC::ScannerFile::FileName(), FullName(), KKLSC::ScannerFileEntryList::LookUpByRootName(), KKB::osGetRootName(), PixelsPerScanLine(), KKLSC::ScannerFile::PixelsPerScanLine(), ScannerFileEntry(), KKLSC::ScannerFileEntryList::ScannerFileEntryList(), ScanRate(), KKLSC::ScannerFile::ScanRate(), and KKB::GlobalGoalKeeper::StartBlock().
{
  ScannerFileEntryPtr entry = NULL;
  KKB::GlobalGoalKeeper::StartBlock ();
  if (globalList == NULL)
  {
    globalList = new ScannerFileEntryList ();
    atexit (CleanUp);
  }
  KKStr rootName = osGetRootName (scannerFile->FileName ());
  entry = globalList->LookUpByRootName (rootName);
  if (entry == NULL)
  {
    entry = new ScannerFileEntry (rootName);
    entry->FullName (scannerFile->FileName ());
    entry->PixelsPerScanLine (scannerFile->PixelsPerScanLine ());
    entry->ScanRate (scannerFile->ScanRate ());
    globalList->AddEntry (entry);
  }
  KKB::GlobalGoalKeeper::EndBlock ();
  return entry;
}
kkint32 ScannerFileEntry::MemoryConsumedEstimated ()
Definition at line 59 of file ScannerFileEntry.cpp.
References KKB::KKStr::MemoryConsumedEstimated().
Referenced by KKLSC::ScannerFile::MemoryConsumedEstimated(), and KKLSC::ScannerFileEntryList::MemoryConsumedEstimated().
{
  kkint32 mem = sizeof (*this) +
               description.MemoryConsumedEstimated () +
               fullName.MemoryConsumedEstimated () +
               rootName.MemoryConsumedEstimated ();
  return mem;
}
void ScannerFileEntry::ParseTabDelStr (KKStr parser)
Definition at line 93 of file ScannerFileEntry.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::KKStr::EqualIgnoreCase(), KKB::KKStr::ExtractToken2(), KKB::KKStr::ExtractTokenDouble(), KKB::KKStr::ExtractTokenUint(), and KKB::KKStr::operator=().
{
  KKStr fieldName = ln.ExtractToken2 ("\t");
  while (!ln.Empty ())
  {
    KKStr fieldName = ln.ExtractToken2 ("\t");
    if (fieldName.EqualIgnoreCase ("Description"))
      description = ln.ExtractToken2 ("\t");
    else if (fieldName.EqualIgnoreCase ("FullName"))
      fullName = ln.ExtractToken2 ("\t");
    else if (fieldName.EqualIgnoreCase ("PixelsPerScanLine"))
      pixelsPerScanLine = ln.ExtractTokenUint ("\t");
    else if (fieldName.EqualIgnoreCase ("RootName"))
      rootName = ln.ExtractToken2 ("\t");
    else if (fieldName.EqualIgnoreCase ("scanRate"))
      scanRate = (float)ln.ExtractTokenDouble ("\t");
  }
  return;
} /* ParseTabDelStr */
kkuint32 KKLSC::ScannerFileEntry::PixelsPerScanLine () const [inline]
Definition at line 42 of file ScannerFileEntry.h.
{return pixelsPerScanLine;}
void KKLSC::ScannerFileEntry::PixelsPerScanLine (kkuint32 _pixelsPerScanLine) [inline]
Definition at line 48 of file ScannerFileEntry.h.
Referenced by GetOrCreateScannerFileEntry(), and KKLSC::ScannerFile::ScannerFile().
{pixelsPerScanLine = _pixelsPerScanLine;}
const KKStr& KKLSC::ScannerFileEntry::RootName () const [inline]
Definition at line 43 of file ScannerFileEntry.h.
{return rootName;}
void KKLSC::ScannerFileEntry::RootName (const KKStr & _rootName) [inline]
Definition at line 49 of file ScannerFileEntry.h.
References KKB::KKStr::operator=().
{rootName = _rootName;}
float KKLSC::ScannerFileEntry::ScanRate () const [inline]
Definition at line 44 of file ScannerFileEntry.h.
{return scanRate;}
void KKLSC::ScannerFileEntry::ScanRate (float _scanRate) [inline]
Definition at line 50 of file ScannerFileEntry.h.
Referenced by GetOrCreateScannerFileEntry(), and KKLSC::ScannerFile::ScannerFile().
{scanRate = _scanRate;}
KKStr ScannerFileEntry::ToTabDelStr () const
Definition at line 80 of file ScannerFileEntry.cpp.
References KKB::KKStr::Concat(), and KKB::KKStr::KKStr().
{
  KKStr r (256);
  r << "Description" << "\t" << description << "\t"
    << "FullName" << "\t" << fullName << "\t"
    << "PixelsPerScanLine" << "\t" << pixelsPerScanLine << "\t"
    << "RootName" << "\t" << rootName << "\t"
    << "ScanRate" << "\t" << scanRate;
  return r;
} /* ToTabDelStr */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFileEntry.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFileEntry.cpp