KKMLL::BinaryClassParms Class Reference
Similar to SVMparam except it is specialized for two classes.
#include <BinaryClassParms.h>
Public Types
typedef BinaryClassParms * BinaryClassParmsPtr
typedef SVM233::svm_parameter svm_parameter
Public Member Functions
BinaryClassParms (MLClassPtr _class1, MLClassPtr _class2, const svm_parameter &_param, FeatureNumListConstPtr _selectedFeatures, float _weight)
Constructor for 'BinaryClassParms' where caller supplies the two classes and parameters for that specific class pair.
BinaryClassParms (const BinaryClassParms &binaryClassParms)
~BinaryClassParms ()
double AParam () const
void AParam (float _A)
double C () const
void C (double _c)
MLClassPtr Class1 () const
KKStr Class1Name () const
MLClassPtr Class2 () const
KKStr Class2Name () const
void Gamma (double _gamma)
kkint32 MemoryConsumedEstimated () const
kkuint16 NumOfFeatures (FileDescPtr fileDesc) const
const svm_parameter & Param () const
void Param (const svm_parameter &_param)
FeatureNumListConstPtr SelectedFeatures () const
void SelectedFeatures (const FeatureNumListConst &_selectedFeatures)
void SelectedFeatures (FeatureNumListConstPtr _selectedFeatures)
FeatureNumListConstPtr SelectedFeaturesFD (FileDescPtr fileDesc) const
KKStr ToTabDelString () const
float Weight () const
void Weight (float _weight)
Static Public Member Functions
static BinaryClassParmsPtr CreateFromTabDelStr (const KKStr &_str, RunLog &_log)
Detailed Description
Similar to SVMparam except it is specialized for two classes.
Machine Learning parameters to be used by a pair of classes.
See also
SVMparam
SVM233
Author
Kurt Kramer
 Written by: Kurt Kramer *
        For: Research Work, Plankton recognition System *
-------------------------------------------------------------------*
  History *
                                                                   *
    date Programmer Description *
                                                                   *
  May-2004 Kurt Kramer Original Development. *
-------------------------------------------------------------------*
 Was developed to support Feature Selection for each binary class *
 combination. This way each two class combination can have SVM *
 and feature parameters that are specific to them. *
See also
KKMLL::SVMparam, KKMLL::ModelParamOldSVM, KKMLL::SVM233
Definition at line 46 of file BinaryClassParms.h.
Member Typedef Documentation
typedef BinaryClassParms* KKMLL::BinaryClassParms::BinaryClassParmsPtr
Definition at line 49 of file BinaryClassParms.h.
typedef SVM233::svm_parameter KKMLL::BinaryClassParms::svm_parameter
Definition at line 51 of file BinaryClassParms.h.
Constructor & Destructor Documentation
BinaryClassParms::BinaryClassParms (MLClassPtr _class1, MLClassPtr _class2, const svm_parameter & _param, FeatureNumListConstPtr _selectedFeatures, float _weight)
Constructor for 'BinaryClassParms' where caller supplies the two classes and parameters for that specific class pair.
Parameters
in _class1
in _class2
in _param
in _selectedFeatures Will create a duplicate instance; caller will still have same ownership status.
in _weight
Definition at line 25 of file BinaryClassParms.cpp.
References KKMLL::FeatureNumList::FeatureNumList(), and SVM233::svm_parameter::svm_parameter().
Referenced by KKMLL::SVMparam::AddBinaryClassParms(), CreateFromTabDelStr(), and KKMLL::SVMparam::GetParamtersToUseFor2ClassCombo().
                                    :
    class1 (_class1),
    class2 (_class2),
    param (_param),
    selectedFeatures (NULL),
    weight (_weight)
{
  if (_selectedFeatures)
    selectedFeatures = new FeatureNumList (*_selectedFeatures);
}
BinaryClassParms::BinaryClassParms (const BinaryClassParms & binaryClassParms)
Definition at line 44 of file BinaryClassParms.cpp.
References KKMLL::FeatureNumList::FeatureNumList(), and SVM233::svm_parameter::svm_parameter().
Referenced by KKMLL::BinaryClassParmsList::DuplicateListAndContents().
                                                                            :
    class1 (binaryClassParms.class1),
    class2 (binaryClassParms.class2),
    param (binaryClassParms.param),
    selectedFeatures (NULL),
    weight (binaryClassParms.weight)
{
  if (binaryClassParms.selectedFeatures)
    selectedFeatures = new FeatureNumList (*binaryClassParms.selectedFeatures);
}
BinaryClassParms::~BinaryClassParms ()
Definition at line 57 of file BinaryClassParms.cpp.
{
  delete selectedFeatures;
  selectedFeatures = NULL;
}
Member Function Documentation
double KKMLL::BinaryClassParms::AParam () const [inline]
Definition at line 79 of file BinaryClassParms.h.
References SVM233::svm_parameter::A.
{return param.A;}
void KKMLL::BinaryClassParms::AParam (float _A) [inline]
Definition at line 92 of file BinaryClassParms.h.
References SVM233::svm_parameter::A.
{param.A = _A;}
double KKMLL::BinaryClassParms::C () const [inline]
Definition at line 82 of file BinaryClassParms.h.
References SVM233::svm_parameter::C.
Referenced by KKMLL::ModelParamOldSVM::C_Param(), and KKMLL::SVMparam::C_Param().
{return param.C;}
void KKMLL::BinaryClassParms::C (double _c) [inline]
Definition at line 93 of file BinaryClassParms.h.
References SVM233::svm_parameter::C.
Referenced by KKMLL::ModelParamOldSVM::C_Param(), and KKMLL::SVMparam::C_Param().
{param.C = _c;}
MLClassPtr KKMLL::BinaryClassParms::Class1 () const [inline]
Definition at line 80 of file BinaryClassParms.h.
Referenced by KKMLL::SVMModel::FindWorstSupportVectors(), KKMLL::SVMModel::FindWorstSupportVectors2(), KKMLL::BinaryClassParmsList::PushOnBack(), KKMLL::BinaryClassParmsList::PushOnFront(), and KKMLL::SVMModel::SupportVectorNames().
{return class1;}
KKStr BinaryClassParms::Class1Name () const
Definition at line 87 of file BinaryClassParms.cpp.
References KKMLL::MLClass::Name().
Referenced by ToTabDelString(), and KKMLL::SVMModel::WriteXML().
{
  if (class1)
    return class1->Name ();
  else
    return "";
} /* Class1Name */
MLClassPtr KKMLL::BinaryClassParms::Class2 () const [inline]
Definition at line 81 of file BinaryClassParms.h.
Referenced by KKMLL::SVMModel::FindWorstSupportVectors(), KKMLL::SVMModel::FindWorstSupportVectors2(), KKMLL::BinaryClassParmsList::PushOnBack(), KKMLL::BinaryClassParmsList::PushOnFront(), and KKMLL::SVMModel::SupportVectorNames().
{return class2;}
KKStr BinaryClassParms::Class2Name () const
Definition at line 97 of file BinaryClassParms.cpp.
References KKMLL::MLClass::Name().
Referenced by ToTabDelString(), and KKMLL::SVMModel::WriteXML().
{
  if (class2)
    return class2->Name ();
  else
    return "";
} /* Class2Name */
BinaryClassParmsPtr BinaryClassParms::CreateFromTabDelStr (const KKStr & _str, RunLog & _log) [static]
Definition at line 132 of file BinaryClassParms.cpp.
References BinaryClassParms(), KKB::KKStr::Concat(), KKMLL::MLClass::CreateNewMLClass(), KKB::KKStr::Empty(), KKB::KKStr::ExtractQuotedStr(), KKMLL::FeatureNumList::FeatureNumList(), KKB::KKStr::KKStr(), KKB::KKStr::operator==(), SVM233::svm_parameter::svm_parameter(), and KKB::KKStr::Upper().
Referenced by KKMLL::BinaryClassParmsList::ReadXML().
{
  MLClassPtr class1 = NULL;
  MLClassPtr class2 = NULL;
  svm_parameter* svm_param = NULL;
  FeatureNumListPtr selectedFeatures = NULL;
  float weight = 0.0f;
  KKStr str (_str);
  while (!str.Empty())
  {
    KKStr field = str.ExtractQuotedStr ("\n\r\t", true);
    field.Upper ();
    KKStr value = str.ExtractQuotedStr ("\n\r\t", true);
    if (field == "CLASS1")
    {
      class1 = MLClass::CreateNewMLClass (value);
    }
    else if (field == "CLASS2")
    {
      class2 = MLClass::CreateNewMLClass (value);
    }
    else if (field == "SVM_PARAMETER")
    {
      svm_param = new svm_parameter (value);
    }
    else if (field == "SELECTEDFEATURES")
    {
      bool valid = false;
      selectedFeatures = new FeatureNumList (value, valid);
    }
    else if (field == "WEIGHT")
      weight = float (atof (value.Str ()));
  }
  BinaryClassParmsPtr binaryClassParms = (svm_param == NULL) ? NULL :new
      BinaryClassParms (class1, class2, *svm_param, selectedFeatures, weight);
  delete selectedFeatures; selectedFeatures = NULL;
  delete svm_param; svm_param = NULL;
  return binaryClassParms;
} /* CreateFromTabDelStr */
void KKMLL::BinaryClassParms::Gamma (double _gamma) [inline]
Definition at line 94 of file BinaryClassParms.h.
References SVM233::svm_parameter::gamma.
{param.gamma = _gamma;}
kkint32 BinaryClassParms::MemoryConsumedEstimated () const
Definition at line 185 of file BinaryClassParms.cpp.
References SVM233::svm_parameter::MemoryConsumedEstimated(), and KKMLL::FeatureNumList::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = sizeof (*this) + param.
      MemoryConsumedEstimated ();
  if (selectedFeatures)
    memoryConsumedEstimated += selectedFeatures->MemoryConsumedEstimated ();
  return memoryConsumedEstimated;
}
kkuint16 BinaryClassParms::NumOfFeatures (FileDescPtr fileDesc) const
Definition at line 64 of file BinaryClassParms.cpp.
References KKMLL::FeatureNumList::NumOfFeatures(), and SelectedFeaturesFD().
Referenced by KKMLL::BinaryClassParmsList::FeatureCountNet().
{
  return SelectedFeaturesFD (fileDesc)->NumOfFeatures ();
}
const svm_parameter& KKMLL::BinaryClassParms::Param () const [inline]
Definition at line 83 of file BinaryClassParms.h.
Referenced by KKMLL::SVMModel::FindWorstSupportVectors(), and KKMLL::SVMModel::FindWorstSupportVectors2().
{return param;}
void KKMLL::BinaryClassParms::Param (const svm_parameter & _param) [inline]
Definition at line 95 of file BinaryClassParms.h.
References SVM233::svm_parameter::operator=().
Referenced by KKMLL::SVMparam::SetBinaryClassFields().
{param = _param;}
FeatureNumListConstPtr KKMLL::BinaryClassParms::SelectedFeatures () const [inline]
Definition at line 84 of file BinaryClassParms.h.
{return selectedFeatures;}
void KKMLL::BinaryClassParms::SelectedFeatures (const FeatureNumListConst & _selectedFeatures)
void BinaryClassParms::SelectedFeatures (FeatureNumListConstPtr _selectedFeatures)
Will make copy of instance; caller will retain ownership status.
Definition at line 77 of file BinaryClassParms.cpp.
References KKMLL::FeatureNumList::FeatureNumList().
Referenced by KKMLL::SVMparam::SetBinaryClassFields(), and KKMLL::SVMparam::SetFeatureNums().
{
   delete selectedFeatures;
   selectedFeatures = new FeatureNumList (*_selectedFeatures);
}
FeatureNumListConstPtr BinaryClassParms::SelectedFeaturesFD (FileDescPtr fileDesc) const
Definition at line 106 of file BinaryClassParms.cpp.
References KKMLL::FeatureNumList::FeatureNumList().
Referenced by KKMLL::SVMparam::GetFeatureNums(), and NumOfFeatures().
{
  if (!selectedFeatures)
    selectedFeatures = new FeatureNumList (fileDesc);
  return selectedFeatures;
}
KKStr BinaryClassParms::ToTabDelString () const
Definition at line 115 of file BinaryClassParms.cpp.
References Class1Name(), Class2Name(), KKB::KKStr::Concat(), SVM233::svm_parameter::ToCmdLineStr(), and KKMLL::FeatureNumList::ToString().
{
  KKStr result;
  result << "Class1" << "\t" << Class1Name () << "\t"
         << "Class2" << "\t" << Class2Name () << "\t"
         << "Svm_Parameter" << "\t" << param.ToCmdLineStr () << "\t";
  if (selectedFeatures)
      result << "SelectedFeatures" << "\t" << selectedFeatures->ToString () << "\t";
  result << "Weight" << "\t" << weight;
  return result;
} /* ToTabDelString */
float KKMLL::BinaryClassParms::Weight () const [inline]
Definition at line 85 of file BinaryClassParms.h.
Referenced by KKMLL::SVMparam::SetFeatureNums().
{return weight;}
void KKMLL::BinaryClassParms::Weight (float _weight) [inline]
Definition at line 98 of file BinaryClassParms.h.
Referenced by KKMLL::SVMparam::SetBinaryClassFields().
{weight = _weight;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/BinaryClassParms.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/BinaryClassParms.cpp