KKB::XmlElementDateTime Class Reference
#include <XmlStream.h>
Public Member Functions
XmlElementDateTime (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
virtual ~XmlElementDateTime ()
virtual bool ToBool () const
virtual double ToDouble () const
virtual float ToFloat () const
virtual kkint32 ToInt32 () const
virtual KKStr ToKKStr () const
DateTime Value () const
Static Public Member Functions
static void WriteXML (const DateTime &d, const KKStr &varName, std::ostream &o)
Additional Inherited Members
Detailed Description
Definition at line 532 of file XmlStream.h.
Constructor & Destructor Documentation
XmlElementDateTime::XmlElementDateTime (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log)
Definition at line 1096 of file XmlStream.cpp.
References KKB::XmlTag::AttributeValueDateTime(), KKB::DateTime::DateTime(), KKB::DateTime::operator=(), and KKB::XmlElement::XmlElement().
                                        :
    XmlElement (tag, s, log),
    value ()
{
  value = tag->AttributeValueDateTime ("Value");
}
XmlElementDateTime::~XmlElementDateTime () [virtual]
Definition at line 1108 of file XmlStream.cpp.
{
}
Member Function Documentation
virtual bool KKB::XmlElementDateTime::ToBool () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 551 of file XmlStream.h.
References KKB::DateTime::Seconds().
{return (value.Seconds () > 0);}
virtual double KKB::XmlElementDateTime::ToDouble () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 553 of file XmlStream.h.
References KKB::DateTime::Seconds().
{return (double)value.Seconds ();}
virtual float KKB::XmlElementDateTime::ToFloat () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 554 of file XmlStream.h.
References KKB::DateTime::Seconds().
{return (float)value.Seconds ();}
virtual kkint32 KKB::XmlElementDateTime::ToInt32 () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 555 of file XmlStream.h.
References KKB::DateTime::ToDays().
{return (kkint32)value.ToDays ();}
virtual KKStr KKB::XmlElementDateTime::ToKKStr () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 552 of file XmlStream.h.
References KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
{return value.YYYY_MM_DD_HH_MM_SS ();}
DateTime KKB::XmlElementDateTime::Value () const [inline]
Definition at line 543 of file XmlStream.h.
Referenced by KKMLL::TrainingProcess2::ReadXML().
{return value;}
void XmlElementDateTime::WriteXML (const DateTime & d, const KKStr & varName, std::ostream & o) [static]
Definition at line 1113 of file XmlStream.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEmpty, KKB::XmlTag::WriteXML(), KKB::XmlTag::XmlTag(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
Referenced by KKMLL::TrainingProcess2::WriteXML().
{
  XmlTag startTag ("DateTime", XmlTag::TagTypes::tagEmpty);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.AddAtribute ("Value", d.YYYY_MM_DD_HH_MM_SS ());
  startTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp