KKMLL::ModelOldSVM Class Reference
A specialization of 'Model'; meant to Wrap the original version of 'SvmModel' class. It will allow us to use the original implementation using version 2.39 of LibSVM.
#include <ModelOldSVM.h>
Public Types
typedef ModelOldSVM * ModelOldSVMPtr
Public Member Functions
ModelOldSVM ()
ModelOldSVM (FactoryFVProducerPtr _factoryFVProducer)
ModelOldSVM (const KKStr &_name, const ModelParamOldSVM &_param, FactoryFVProducerPtr _factoryFVProducer)
Creates a new svm model from the provided example (example) data.
ModelOldSVM (const ModelOldSVM &_madel)
virtual ~ModelOldSVM ()
const ClassAssignments & Assignments () const
virtual KKStr Description () const
virtual ModelOldSVMPtr Duplicate () const
std::vector< ProbNamePair > FindWorstSupportVectors (FeatureVectorPtr example, kkint32 numToFind, MLClassPtr c1, MLClassPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
std::vector< ProbNamePair > FindWorstSupportVectors2 (FeatureVectorPtr example, kkint32 numToFind, MLClassPtr c1, MLClassPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
FeatureNumListConstPtr GetFeatureNums () const
FeatureNumListConstPtr GetFeatureNums (FileDescPtr filedesc, MLClassPtr class1, MLClassPtr class2)
virtual kkint32 MemoryConsumedEstimated () const
virtual ModelTypes ModelType () const
virtual bool NormalizeNominalAttributes () const
kkint32 NumOfSupportVectors () const
ModelParamOldSVMPtr Param () const
virtual MLClassPtr Predict (FeatureVectorPtr image, RunLog &log)
virtual void Predict (FeatureVectorPtr example, MLClassPtr knownClass, MLClassPtr &predClass1, MLClassPtr &predClass2, kkint32 &predClass1Votes, kkint32 &predClass2Votes, double &probOfKnownClass, double &predClass1Prob, double &predClass2Prob, kkint32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie, RunLog &log)
virtual void PredictRaw (FeatureVectorPtr example, MLClassPtr &predClass, double &dist)
virtual FeatureVectorPtr PrepExampleForPrediction (FeatureVectorPtr fv, bool &newExampleCreated)
ModelOldSVM Specific 'PrepExampleForPrediction' will only normalize data.
virtual ClassProbListPtr ProbabilitiesByClass (FeatureVectorPtr example, RunLog &log)
virtual void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassList &_mlClasses, kkint32 *_votes, double *_probabilities, RunLog &log)
Will get the probabilities assigned to each class.
virtual void ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassList &_mlClasses, double *_probabilities, RunLog &_log)
Retrieves probabilities assigned to each class.
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
To be implemented by derived classes; the parent classes fields will be updated by the derived class calling ReadXMLModelToken.
void RetrieveCrossProbTable (MLClassList &classes, double **crossProbTable, RunLog &log)
SVM_SelectionMethod SelectionMethod () const
std::vector< KKStr > SupportVectorNames () const
std::vector< KKStr > SupportVectorNames (MLClassPtr c1, MLClassPtr c2) const
void SupportVectorStatistics (kkint32 &numSVs, kkint32 &totalNumSVs)
SVMModelPtr SvmModel () const
virtual void TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership, VolConstBool &_cancelFlag, RunLog &_log)
Use given training data to create a trained Model that can be used for classifying examples.
virtual void WriteXML (const KKStr &varName, std::ostream &o) const
Additional Inherited Members
Detailed Description
A specialization of 'Model'; meant to Wrap the original version of 'SvmModel' class. It will allow us to use the original implementation using version 2.39 of LibSVM.
Definition at line 34 of file ModelOldSVM.h.
Member Typedef Documentation
typedef ModelOldSVM* KKMLL::ModelOldSVM::ModelOldSVMPtr
Definition at line 37 of file ModelOldSVM.h.
Constructor & Destructor Documentation
ModelOldSVM::ModelOldSVM ()
Definition at line 41 of file ModelOldSVM.cpp.
References KKMLL::Model::Model(), KKMLL::ModelParamOldSVM::ModelParamOldSVM(), and KKMLL::Model::param.
                         :
  Model (),
  assignments (NULL),
  svmModel (NULL)
{
  Model::param = new ModelParamOldSVM ();
}
ModelOldSVM::ModelOldSVM (FactoryFVProducerPtr _factoryFVProducer)
Definition at line 52 of file ModelOldSVM.cpp.
References KKMLL::Model::Model(), KKMLL::ModelParamOldSVM::ModelParamOldSVM(), and KKMLL::Model::param.
                                                                 :
  Model (_factoryFVProducer),
  assignments (NULL),
  svmModel (NULL)
{
  Model::param = new ModelParamOldSVM ();
}
ModelOldSVM::ModelOldSVM (const KKStr & _name, const ModelParamOldSVM & _param, FactoryFVProducerPtr _factoryFVProducer)
Creates a new svm model from the provided example (example) data.
Parameters
in _name
in _param The parameters for the svm, and for creating the model.
in _factoryFVProducer Describes the FeactureVectorProducer, FileDesc, and FeatureVectorList derived classes needed.
Definition at line 62 of file ModelOldSVM.cpp.
References KKMLL::Model::Model().
Referenced by KKMLL::Model::CreateAModel().
:
  Model (_name, _param, _factoryFVProducer),
  assignments (NULL),
  svmModel (NULL)
{
}
ModelOldSVM::ModelOldSVM (const ModelOldSVM & _madel)
Definition at line 75 of file ModelOldSVM.cpp.
References KKMLL::Model::Model().
Referenced by Duplicate().
:
  Model (_model),
  assignments (NULL),
  svmModel (NULL)
{
}
ModelOldSVM::~ModelOldSVM () [virtual]
Definition at line 87 of file ModelOldSVM.cpp.
{
  delete svmModel;
  svmModel = NULL;
  delete assignments;
  assignments = NULL;
}
Member Function Documentation
const ClassAssignments & ModelOldSVM::Assignments () const
Definition at line 132 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::Assignments().
{
  return svmModel->Assignments ();
}
KKStr ModelOldSVM::Description () const [virtual]
Return short user readable description of model.
Reimplemented from KKMLL::Model.
Definition at line 117 of file ModelOldSVM.cpp.
References KKB::KKStr::Concat(), KKMLL::SVMparam::MachineType(), KKMLL::MachineTypeToStr(), KKMLL::Model::Name(), KKB::KKStr::operator+(), KKB::operator+(), KKMLL::SVMparam::SelectionMethod(), KKMLL::SelectionMethodToStr(), and KKMLL::SVMModel::SVMParameters().
{
  KKStr result = "SVM(" + Name () + ")";
  if (svmModel)
  {
    SVMparam const * p = svmModel->SVMParameters ();
    result << " " << MachineTypeToStr (p->MachineType ())
           << " " << SelectionMethodToStr (p->
      SelectionMethod ());
  }
  return result;
}
ModelOldSVMPtr ModelOldSVM::Duplicate () const [virtual]
Implements KKMLL::Model.
Definition at line 111 of file ModelOldSVM.cpp.
References ModelOldSVM(), and SupportVectorNames().
{
  return new ModelOldSVM (*this);
}
vector< ProbNamePair > ModelOldSVM::FindWorstSupportVectors (FeatureVectorPtr example, kkint32 numToFind, MLClassPtr c1, MLClassPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and re-compute the decision boundary and probability. It will then return the S/V's that when removed improve the probability in 'c1's the most.
Parameters
in example Example that was classified incorrectly.
in numToFind The number of the worst examples you are looking for.
in c1 Class that the 'example; parameter should have been classed as.
in c2 Class that it was classified as.
Definition at line 386 of file ModelOldSVM.cpp.
{
  return svmModel->FindWorstSupportVectors (example, numToFind, c1, c2);
} /* FindWorstSupportVectors */
vector< ProbNamePair > ModelOldSVM::FindWorstSupportVectors2 (FeatureVectorPtr example, kkint32 numToFind, MLClassPtr c1, MLClassPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and retraining a new SVM and then comparing with the new prediction results.
Parameters
in example Example that was classified incorrectly.
in numToFind The number of the worst examples you are looking for.
in c1 Class that the 'example; parameter should have been classed as.
in c2 Class that it was classified as.
Definition at line 400 of file ModelOldSVM.cpp.
{
  return svmModel->FindWorstSupportVectors2 (example, numToFind, c1, c2);
} /* FindWorstSupportVectors2 */
FeatureNumListConstPtr ModelOldSVM::GetFeatureNums () const [virtual]
Reimplemented from KKMLL::Model.
Definition at line 150 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::GetFeatureNums().
{
  return svmModel->GetFeatureNums ();
}
FeatureNumListConstPtr ModelOldSVM::GetFeatureNums (FileDescPtr filedesc, MLClassPtr class1, MLClassPtr class2)
Definition at line 139 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::GetFeatureNums().
{
  return svmModel->GetFeatureNums (filedesc, class1, class2);
} /* GetFeatureNums */
kkint32 ModelOldSVM::MemoryConsumedEstimated () const [virtual]
Reimplemented from KKMLL::Model.
Definition at line 97 of file ModelOldSVM.cpp.
References KKMLL::ClassAssignments::MemoryConsumedEstimated(), KKMLL::SVMModel::MemoryConsumedEstimated(), and KKMLL::Model::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = Model::MemoryConsumedEstimated ()
       +
                                 sizeof (ClassAssignmentsPtr) +
                                 sizeof (SVMModelPtr);
  if (assignments) memoryConsumedEstimated += assignments->
      MemoryConsumedEstimated ();
  if (svmModel) memoryConsumedEstimated += svmModel->
      MemoryConsumedEstimated ();
  return memoryConsumedEstimated;
}
virtual ModelTypes KKMLL::ModelOldSVM::ModelType () const [inline], [virtual]
Implements KKMLL::Model.
Definition at line 62 of file ModelOldSVM.h.
References KKMLL::Model::OldSVM.
{return ModelTypes::OldSVM;}
bool ModelOldSVM::NormalizeNominalAttributes () const [virtual]
Return true, if nominal fields need to be normalized.
Reimplemented from KKMLL::Model.
Definition at line 413 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::NormalizeNominalAttributes().
{
  return svmModel->NormalizeNominalAttributes ();
} /* NormalizeNominalAttributes */
kkint32 ModelOldSVM::NumOfSupportVectors () const
Definition at line 157 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::NumOfSupportVectors().
Referenced by KKMLL::TrainingProcess2::NumOfSupportVectors().
{
  return svmModel->NumOfSupportVectors ();
}
ModelParamOldSVMPtr ModelOldSVM::Param () const
Definition at line 172 of file ModelOldSVM.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKMLL::ModelParam::ModelParamType(), KKMLL::ModelParam::OldSVM, and KKMLL::Model::param.
Referenced by TrainModel().
{
  if (param == NULL)
  {
    KKStr errMsg = "ModelOldSVM::Param ***ERROR*** param not defined (param == NULL).";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  if (param->ModelParamType () !=
      ModelParam::ModelParamTypes::OldSVM)
  {
    KKStr errMsg = "ModelOldSVM::Param ***ERROR*** param variable of wrong type.";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  return dynamic_cast<ModelParamOldSVMPtr> (param);
}
MLClassPtr ModelOldSVM::Predict (FeatureVectorPtr image, RunLog & log) [virtual]
Implements KKMLL::Model.
Definition at line 239 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::Predict(), and PrepExampleForPrediction().
{
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      example, newExampleCreated);
  MLClassPtr c = svmModel->Predict (example);
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  return c;
} /* Predict */
[Predict(FeatureVectorPtr example, MLClassPtr knownClass, MLClassPtr predClass1, MLClassPtr predClass2, kkint32 predClass1Votes, kkint32 predClass2Votes, double probOfKnownClass, double predClass1Prob, double predClass2Prob, kkint32 numOfWinners, bool knownClassOneOfTheWinners, double breakTie, RunLog log)]void ModelOldSVM::Predict (FeatureVectorPtr example, MLClassPtr knownClass, MLClassPtr & predClass1, MLClassPtr & predClass2, kkint32 & predClass1Votes, kkint32 & predClass2Votes, double & probOfKnownClass, double & predClass1Prob, double & predClass2Prob, kkint32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie, RunLog & log) [virtual]
Implements KKMLL::Model.
Definition at line 201 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::Predict(), and PrepExampleForPrediction().
{
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      example, newExampleCreated);
  svmModel->Predict (encodedExample, knownClass, predClass1, predClass2,
                     predClass1Votes, predClass2Votes,
                     probOfKnownClass,
                     predClass1Prob, predClass2Prob,
                     numOfWinners,
                     knownClassOneOfTheWinners,
                     breakTie
                    );
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  
  return;
} /* Predict */
void ModelOldSVM::PredictRaw (FeatureVectorPtr example, MLClassPtr & predClass, double & dist) [virtual]
Reimplemented from KKMLL::Model.
Definition at line 261 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::PredictRaw().
{
  svmModel->PredictRaw (example, predClass, dist);
} /* PredictRaw */
FeatureVectorPtr ModelOldSVM::PrepExampleForPrediction (FeatureVectorPtr fv, bool & newExampleCreated) [virtual]
ModelOldSVM Specific 'PrepExampleForPrediction' will only normalize data.
Parameters
in fv Feature vector of example that needs to be prepared.
out newExampleCreated Indicates if either Feature Encoding and/or Normalization needed to be done. If neither then the original instance is returned. If Yes then a new instance which the caller will have to be delete will be returned.
Reimplemented from KKMLL::Model.
Definition at line 506 of file ModelOldSVM.cpp.
References KKMLL::Model::alreadyNormalized, KKMLL::Model::normParms, and KKMLL::NormalizationParms::ToNormalized().
Referenced by Predict(), and ProbabilitiesByClass().
{
  FeatureVectorPtr oldFV = NULL;
  newExampleCreated = false;
  if ((!alreadyNormalized) && (normParms))
  {
    oldFV = fv;
    fv = normParms->ToNormalized (fv);
    if (newExampleCreated)
    {
      delete oldFV;
      oldFV = NULL;
    }
    newExampleCreated = true;
  }
  // Since 'SvmModel' will be doing the encoding we do not need to do it here.
  return fv;
} /* PrepExampleForPrediction */
ClassProbListPtr ModelOldSVM::ProbabilitiesByClass (FeatureVectorPtr example, RunLog & log) [virtual]
Implements KKMLL::Model.
Definition at line 273 of file ModelOldSVM.cpp.
References KKMLL::Model::classes, KKMLL::ClassProb::ClassProb(), KKMLL::ClassProbList::ClassProbList(), KKMLL::Model::classProbs, KKB::KKStr::Concat(), KKB::KKException::KKException(), KKMLL::Model::numOfClasses, PrepExampleForPrediction(), KKMLL::SVMModel::ProbabilitiesByClass(), KKMLL::ClassProbList::PushOnBack(), KKMLL::SVMparam::SelectionMethod(), KKMLL::ClassProbList::SortByProbability(), KKMLL::ClassProbList::SortByVotes(), KKMLL::SVMModel::SVMParameters(), KKMLL::Model::votes, and KKMLL::Voting.
{
  if (!svmModel)
  {
    KKStr errMsg = "ModelOldSVM::ProbabilitiesByClass ***ERROR*** (svmModel == NULL)";
    log.Level (-1) << endl << errMsg << endl;
    throw KKException (errMsg);
  }
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      example, newExampleCreated);
  svmModel->ProbabilitiesByClass (encodedExample, *classes,
      votes, classProbs, log);
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  
  ClassProbListPtr results = new ClassProbList ();
  kkint32 idx = 0;
  for (idx = 0; idx < numOfClasses; idx++)
  {
    MLClassPtr ic = classes->IdxToPtr (idx);
    results->PushOnBack (new ClassProb (ic, classProbs[idx], (float)
      votes[idx]));
  }
  if (svmModel->SVMParameters ()->SelectionMethod () ==
      SVM_SelectionMethod::Voting)
    results->SortByVotes (true);
  else
    results->SortByProbability (true);
  return results;
} /* ProbabilitiesByClass */
void ModelOldSVM::ProbabilitiesByClass (FeatureVectorPtr example, const MLClassList & _mlClasses, kkint32 * _votes, double * _probabilities, RunLog & log) [virtual]
Will get the probabilities assigned to each class.
Parameters
in example unknown example that we want to get predicted probabilities for.
in _ImageClasses List classes that caller is aware of. This should be the same list that was used when constructing this ModelOldSVM object. The list must be the same but not necessarily in the same order as when ModelOldSVM was 1st constructed. The ordering of this instance dictates how the parameters '_votes' and '_probabilities' are populated.
out _votes Number of votes for each class
out _probabilities An array that must be as big as the number of classes in _mlClasses. The probability of class in _mlClasses[x] will be returned in _probabilities[x].
in log Logger.
Implements KKMLL::Model.
Definition at line 337 of file ModelOldSVM.cpp.
References PrepExampleForPrediction(), and KKMLL::SVMModel::ProbabilitiesByClass().
{
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      example, newExampleCreated);
  svmModel->ProbabilitiesByClass (encodedExample, _mlClasses, _votes, _probabilities,
      _log);
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  return;
} /* ProbabilitiesByClass */
void ModelOldSVM::ProbabilitiesByClass (FeatureVectorPtr _example, const MLClassList & _mlClasses, double * _probabilities, RunLog & _log) [virtual]
Retrieves probabilities assigned to each class.
Parameters
in _example unknown example that we want to get predicted probabilities for.
in _ImageClasses List classes that caller is aware of. This should be the same list that was used when constructing this ModelOldSVM object. The list must be the same but not necessarily in the same order as when ModelOldSVM was 1st constructed.
out _probabilities An array that must be as big as the number of classes in _mlClasses. The probability of class in _mlClasses[x] will be returned in _probabilities[x].
in _log Logger to send messages to.
Implements KKMLL::Model.
Definition at line 315 of file ModelOldSVM.cpp.
References PrepExampleForPrediction(), KKMLL::SVMModel::ProbabilitiesByClass(), and KKMLL::Model::votes.
{
  bool newExampleCreated = false;
  FeatureVectorPtr encodedExample = PrepExampleForPrediction (
      _example, newExampleCreated);
  svmModel->ProbabilitiesByClass (encodedExample, _mlClasses,
      votes, _probabilities, _log);
  if (newExampleCreated)
  {
    delete encodedExample;
    encodedExample = NULL;
  }
  return;
}
void ModelOldSVM::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) [virtual]
To be implemented by derived classes; the parent classes fields will be updated by the derived class calling ReadXMLModelToken.
Implements KKMLL::Model.
Definition at line 561 of file ModelOldSVM.cpp.
References KKMLL::Model::AddErrorMsg(), KKMLL::ClassAssignments::ClassAssignments(), KKB::KKStr::Concat(), KKB::KKStr::EqualIgnoreCase(), KKB::XmlStream::GetNextToken(), KKB::KKStr::KKStr(), KKMLL::ModelParam::ModelParamTypeStr(), KKMLL::Model::param, KKMLL::Model::ReadXMLModelPost(), KKMLL::Model::ReadXMLModelToken(), KKMLL::SVMModel::ValidModel(), and KKB::XmlToken::VarName().
{
  delete svmModel;
  svmModel = NULL;
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    t = ReadXMLModelToken (t, log); // 1st see if the base class has this data field.
    if (t)
    {
      if ((t->VarName ().EqualIgnoreCase ("Assignments")) && (typeid(*t) == typeid
      (XmlElementKKStr)))
      {
        XmlElementKKStrPtr s = dynamic_cast<XmlElementKKStrPtr> (t);
        delete assignments;
        assignments = new ClassAssignments ();
        assignments->ParseToString (*(s->Value ()), log);
      }
      else if ((t->VarName ().EqualIgnoreCase ("SvmModel")) && (typeid(*t) ==
      typeid(XmlElementSVMModel)))
      {
        delete svmModel;
        svmModel = dynamic_cast<XmlElementSVMModelPtr> (t)->TakeOwnership ();
      }
      else
      {
        KKStr errMsg (128);
        errMsg << "ModelOldSVM::ReadXML ***ERROR*** Unexpected Token; Section:" << t->
      SectionName () << " VarName: " << t->VarName ();
        AddErrorMsg (errMsg, 0);
        log.Level (-1) << endl << errMsg << endl << endl;
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
  if (cancelFlag)
    AddErrorMsg ("ModelOldSVM::ReadXML ***CANCELED***", 0);
  if (!param)
    param = dynamic_cast<ModelParamOldSVMPtr> (
      Model::param);
  if (Model::param == NULL)
  {
    KKStr errMsg (128);
    errMsg << "ModelOldSVM::ReadXML ***ERROR*** Base class 'Model' does not have 'param' defined.";
    AddErrorMsg (errMsg, 0);
    log.Level (-1) << endl << errMsg << endl << endl;
  }
  else if (typeid (*Model::param) != typeid(ModelParamOldSVM))
  {
    KKStr errMsg (128);
    errMsg << "ModelOldSVM::ReadXML ***ERROR*** Base class 'Model' param parameter is of the wrong type;
       found: " << Model::param->ModelParamTypeStr ();
    AddErrorMsg (errMsg, 0);
    log.Level (-1) << endl << errMsg << endl << endl;
  }
  if ((!svmModel) || (!svmModel->ValidModel ()))
  {
    KKStr errMsg (128);
    errMsg << "ModelOldSVM::ReadXML ***ERROR*** 'SvmModel' was not defined or is not valid.";
    AddErrorMsg (errMsg, 0);
    log.Level (-1) << endl << errMsg << endl << endl;
  }
  else
  {
    param = dynamic_cast<ModelParamOldSVMPtr> (
      Model::param);
  }
  ReadXMLModelPost (log);
} /* ReadXML */
void ModelOldSVM::RetrieveCrossProbTable (MLClassList & classes, double ** crossProbTable, RunLog & log) [virtual]
Parameters
crossProbTable two dimension matrix that needs to be classes.QueueSize () squared.
Reimplemented from KKMLL::Model.
Definition at line 421 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::RetrieveCrossProbTable().
{
  svmModel->RetrieveCrossProbTable (classes, crossProbTable, log);
  return;
} /* RetrieveCrossProbTable */
SVM_SelectionMethod ModelOldSVM::SelectionMethod () const
Definition at line 193 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::SelectionMethod().
Referenced by KKMLL::Classifier2::SelectionMethod().
{
  return svmModel->SelectionMethod ();
}
vector< KKStr > ModelOldSVM::SupportVectorNames () const
Definition at line 375 of file ModelOldSVM.cpp.
{
  return svmModel->SupportVectorNames ();
} /* SupportVectorNames */
vector< KKStr > ModelOldSVM::SupportVectorNames (MLClassPtr c1, MLClassPtr c2) const
Definition at line 362 of file ModelOldSVM.cpp.
Referenced by KKMLL::Model::CreateAModel(), and Duplicate().
{
  return svmModel->SupportVectorNames (c1, c2);
} /* SupportVectorNames */
void ModelOldSVM::SupportVectorStatistics (kkint32 & numSVs, kkint32 & totalNumSVs)
Definition at line 164 of file ModelOldSVM.cpp.
References KKMLL::SVMModel::SupportVectorStatistics().
Referenced by KKMLL::TrainingProcess2::SupportVectorStatistics().
{
  return svmModel->SupportVectorStatistics (numSVs, totalNumSVs);
}
SVMModelPtr KKMLL::ModelOldSVM::SvmModel () const [inline]
Definition at line 92 of file ModelOldSVM.h.
Referenced by KKMLL::Classifier2::Classifier2(), and KKMLL::TrainingProcess2::Model3().
{return svmModel;}
void ModelOldSVM::TrainModel (FeatureVectorListPtr _trainExamples, bool _alreadyNormalized, bool _takeOwnership, VolConstBool & _cancelFlag, RunLog & _log) [virtual]
Use given training data to create a trained Model that can be used for classifying examples.
Parameters
in _trainExamples The example data we will be building the model from.
in _alreadyNormalized Specifies weather the training data has already been normalized.
in _takeOwnership If true this instance will take ownership of '_trainExamples' and delete it when done with it.
in _cancelFlag Monitored; when set to True will end processing and return to caller.
in _log Logger to send messages to.
Parameters
_takeOwnership Model will take ownership of these examples
Reimplemented from KKMLL::Model.
Definition at line 433 of file ModelOldSVM.cpp.
References KKMLL::ClassAssignments::ClassAssignments(), KKMLL::Model::classes, KKB::KKStr::Concat(), KKMLL::FeatureVectorList::ExtractListOfClasses(), KKMLL::FeatureVectorList::FileDesc(), KKMLL::Model::fileDesc, KKB::KKException::KKException(), Param(), KKMLL::MLClassList::SortByName(), KKMLL::SVMModel::SupportVectorNames(), KKMLL::SVMModel::SVMModel(), KKMLL::ModelParamOldSVM::SvmParameters(), KKMLL::Model::trainExamples, KKMLL::Model::TrainingTimeEnd(), KKMLL::Model::TrainingTimeStart(), KKMLL::Model::TrainModel(), KKMLL::Model::validModel, and KKMLL::Model::weOwnTrainExamples.
{
  _log.Level (20) << "ModelOldSVM::TrainModel - Constructing From Training Data, Model[" <<
      rootFileName << "]" << endl;
  // We do not bother with the base class 'TrainModel' like we do with other models.
  // 'ModelOldSVM' is a special case. All we are trying to do is create a pass through
  // for 'svmModel'.
  delete svmModel;
  svmModel = NULL;
  Model::TrainModel (_trainExamples, _alreadyNormalized, _takeOwnership, _cancelFlag, _log
      );
  // The "Model::TrainModel" may have manipulated the '_trainExamples'. It will have also
  // updated 'Model::trainExamples. So from this point forward we use 'trainExamples'.
  _trainExamples = NULL;
  if (trainExamples == NULL)
  {
    validModel = false;
    KKStr errMsg = " ModelOldSVM::TrainModel ***ERROR*** (trainExamples == NULL).";
    _log.Level (-1) << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  if ((!fileDesc) && trainExamples)
    fileDesc = trainExamples->FileDesc ();
  SVMparamPtr svmParam = Param ()->SvmParameters ();
  if (!svmParam)
  {
    validModel = false;
    KKStr errMsg = " ModelOldSVM::TrainModel ***ERROR*** (svmParam == NULL).";
    _log.Level (-1) << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  {
    delete classes;
    classes = trainExamples->ExtractListOfClasses ();
    classes->SortByName ();
    numOfClasses = classes->QueueSize ();
    delete assignments;
    assignments = new ClassAssignments (*classes);
  }
  try
  {
    TrainingTimeStart ();
    svmModel = new SVMModel (*svmParam, *trainExamples, *assignments,
      fileDesc, _log);
    TrainingTimeEnd ();
  }
  catch (...)
  {
    _log.Level (-1) << endl << "ModelOldSVM::TrainModel Exception occurred building training model."
      << endl << endl;
    validModel = false;
    delete svmModel;
    svmModel = NULL;
  }
  if (weOwnTrainExamples)
  {
    // We are done with the training examples and since we were to take ownership, we can delete them.
    delete trainExamples;
    trainExamples = NULL;
  }
} /* TrainModel */
void ModelOldSVM::WriteXML (const KKStr & varName, std::ostream & o) const [virtual]
Implements KKMLL::Model.
Definition at line 534 of file ModelOldSVM.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKMLL::ClassAssignments::ToString(), KKMLL::Model::WriteModelXMLFields(), KKB::XmlTag::WriteXML(), KKMLL::SVMModel::WriteXML(), KKB::KKStr::WriteXML(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("ModelOldSVM", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  WriteModelXMLFields (o); // Write the PArent class fields 1st.
  if (assignments)
    assignments->ToString ().WriteXML ("Assignments", o);
  if (svmModel)
    svmModel->WriteXML ("svmModel", o);
  XmlTag endTag ("ModelOldSVM", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelOldSVM.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelOldSVM.cpp