KKB::TokenBufferStr Class Reference
#include <TokenBuffer.h>
Public Member Functions
TokenBufferStr (const KKStr &_buff)
virtual ~TokenBufferStr ()
virtual bool EndOfFile ()
virtual char GetNextChar ()
virtual char PeekNextChar ()
virtual void UnGetNextChar ()
virtual bool Valid ()
Detailed Description
Definition at line 36 of file TokenBuffer.h.
Constructor & Destructor Documentation
TokenBufferStr::TokenBufferStr (const KKStr & _buff)
Definition at line 34 of file TokenBuffer.cpp.
References KKB::KKStr::KKStr().
Referenced by KKB::Tokenizer::Tokenizer(), and KKB::XmlTokenizer::XmlTokenizer().
                                                  :
    buff (_buff),
    nextCharPos (0)
{
}
TokenBufferStr::~TokenBufferStr () [virtual]
Definition at line 42 of file TokenBuffer.cpp.
{
}
Member Function Documentation
bool TokenBufferStr::EndOfFile () [virtual]
Implements KKB::TokenBuffer.
Definition at line 84 of file TokenBuffer.cpp.
References KKB::KKStr::Len().
{
  if (nextCharPos >= buff.Len ())
    return true;
  else
    return false;
} /* EndOfFile */
char TokenBufferStr::GetNextChar () [virtual]
Implements KKB::TokenBuffer.
Definition at line 55 of file TokenBuffer.cpp.
References KKB::KKStr::Len(), and KKB::KKStr::operator[]().
{
  if (nextCharPos >= buff.Len ())
    return 0;
  char c = buff[nextCharPos];
  nextCharPos++;
  return c;
} /* GetNextChar */
char TokenBufferStr::PeekNextChar () [virtual]
Implements KKB::TokenBuffer.
Definition at line 67 of file TokenBuffer.cpp.
References KKB::KKStr::Len(), and KKB::KKStr::operator[]().
{
  if (nextCharPos >= buff.Len ())
    return 0;
  return buff[nextCharPos];
}
void TokenBufferStr::UnGetNextChar () [virtual]
Implements KKB::TokenBuffer.
Definition at line 76 of file TokenBuffer.cpp.
{
  if (nextCharPos > 0)
    --nextCharPos;
}
bool TokenBufferStr::Valid () [virtual]
Implements KKB::TokenBuffer.
Definition at line 48 of file TokenBuffer.cpp.
{
  return true;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/TokenBuffer.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/TokenBuffer.cpp