KKB::XmlElementKeyValuePairs Class Reference
#include <XmlStream.h>
Public Member Functions
XmlElementKeyValuePairs ()
Used to construct an instance that will be written out to a XML file.
XmlElementKeyValuePairs (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
virtual ~XmlElementKeyValuePairs ()
void Add (const KKStr &key, const KKStr &v)
void Add (const KKStr &key, kkint32 v)
void Add (const KKStr &key, float v)
void Add (const KKStr &key, double v)
void Add (const KKStr &key, bool v)
void Add (const KKStr &key, const KKB::DateTime &v)
std::vector< std::pair< KKStr, KKStr > > * TakeOwnership ()
std::vector< std::pair< KKStr, KKStr > > * Value () const
void WriteXML (const KKStr &varName, std::ostream &o)
Additional Inherited Members
Detailed Description
Definition at line 568 of file XmlStream.h.
Constructor & Destructor Documentation
XmlElementKeyValuePairs::XmlElementKeyValuePairs ()
Used to construct an instance that will be written out to a XML file.
summary>Used while from XmlStream while reading file; every time it comes across a new Section(Start-Tag) a new instance of this class will be instantiated.
Definition at line 1134 of file XmlStream.cpp.
References KKB::XmlTag::tagStart, KKB::XmlElement::XmlElement(), and XmlElementKeyValuePairs().
Referenced by KKMLL::SVMparam::WriteXML(), KKMLL::SVMModel::WriteXML(), and XmlElementKeyValuePairs().
                                                 :
    XmlElement ("KeyValuePairs", XmlTag::TagTypes::tagStart),
    value (new vector<pair<KKStr,KKStr> > ())
{
}
XmlElementKeyValuePairs::XmlElementKeyValuePairs (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log)
Definition at line 1141 of file XmlStream.cpp.
References KKB::KKStr::Concat(), KKB::XmlContent::Content(), KKB::KKStrParser::GetNextToken(), KKB::XmlStream::GetNextToken(), KKB::KKStrParser::KKStrParser(), KKB::KKStrParser::MoreTokens(), KKB::XmlToken::tokContent, KKB::XmlToken::TokenType(), KKB::KKStrParser::TrimWhiteSpace(), KKB::XmlElement::XmlElement(), and XmlElementKeyValuePairs().
Referenced by XmlElementKeyValuePairs().
                                                  :
    XmlElement (tag, s, log),
    value (NULL)
{
  value = new vector<pair<KKStr,KKStr> > ();
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t != NULL)
  {
    if (t->TokenType () == XmlToken::TokenTypes::tokContent)
    {
      XmlContentPtr c = dynamic_cast<XmlContentPtr> (t);
      if (c)
      {
        KKStrParser p (*(c->Content ()));
        p.TrimWhiteSpace (" ");
        
        while (p.MoreTokens ())
        {
          KKStr key = p.GetNextToken ("\t\n");
          if (p.LastDelimiter () == '\n')
            value->push_back (pair<KKStr,KKStr> (key, ""));
          else
            value->push_back (pair<KKStr,KKStr> (key, p.GetRestOfLine ()));
        }
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
}
XmlElementKeyValuePairs::~XmlElementKeyValuePairs () [virtual]
Definition at line 1178 of file XmlStream.cpp.
{
  delete value;
  value = NULL;
}
Member Function Documentation
void XmlElementKeyValuePairs::Add (const KKStr & key, const KKStr & v)
Definition at line 1193 of file XmlStream.cpp.
Referenced by Add(), KKMLL::SVMparam::WriteXML(), and KKMLL::SVMModel::WriteXML().
{
  value->push_back (pair<KKStr,KKStr> (key, v));
}
void XmlElementKeyValuePairs::Add (const KKStr & key, kkint32 v)
Definition at line 1203 of file XmlStream.cpp.
References Add(), and KKB::StrFromInt32().
Referenced by KKMLL::SVMModel::WriteXML().
{
  Add (key, KKB::StrFromInt32 (v));
}
void XmlElementKeyValuePairs::Add (const KKStr & key, float v)
Definition at line 1212 of file XmlStream.cpp.
References Add(), and KKB::StrFromFloat().
Referenced by KKMLL::SVMparam::WriteXML().
{
  Add (key, KKB::StrFromFloat (v));
}
void XmlElementKeyValuePairs::Add (const KKStr & key, double v)
Definition at line 1222 of file XmlStream.cpp.
References Add(), and KKB::StrFromDouble().
Referenced by KKMLL::SVMModel::WriteXML().
{
  Add (key, KKB::StrFromDouble (v));
}
void XmlElementKeyValuePairs::Add (const KKStr & key, bool v)
Definition at line 1232 of file XmlStream.cpp.
References Add(), KKB::KKStr::Concat(), and KKB::KKStr::operator=().
Referenced by KKMLL::SVMparam::WriteXML().
{
  KKStr vStr = "False";
  if (v) vStr = "True";
  Add (key, vStr);
}
void XmlElementKeyValuePairs::Add (const KKStr & key, const KKB::DateTime & v)
Definition at line 1243 of file XmlStream.cpp.
References Add(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
Referenced by KKMLL::SVMModel::WriteXML().
{
  Add (key, v.YYYY_MM_DD_HH_MM_SS ());
}
vector< pair< KKStr, KKStr > > * XmlElementKeyValuePairs::TakeOwnership ()
Definition at line 1185 of file XmlStream.cpp.
{
  vector<pair<KKStr,KKStr> >* v = value;
  value = NULL;
  return v;
}
std::vector<std::pair<KKStr,KKStr> >* KKB::XmlElementKeyValuePairs::Value () const [inline]
Definition at line 586 of file XmlStream.h.
{return value;}
void XmlElementKeyValuePairs::WriteXML (const KKStr & varName, std::ostream & o)
Definition at line 1252 of file XmlStream.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::operator<<(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::SVMparam::WriteXML(), and KKMLL::SVMModel::WriteXML().
{
  XmlTag startTag ("KeyValuePairs", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  vector<pair<KKStr,KKStr> >::const_iterator idx;
  for (idx = value->begin (); idx != value->end (); ++idx)
  {
    XmlContent::WriteXml (idx->first, o);
    o << "\t";
    XmlContent::WriteXml (idx->second, o);
    o << endl;
  }
  XmlTag endTag ("KeyValuePairs", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp