KKB::Configuration::ConfSection Class Reference
Public Member Functions
ConfSection (const KKStr &_name, kkint32 _lineNum)
ConfSection (const Configuration::ConfSection &cs)
void AddSetting (const KKStr &_name, const KKStr &_value, kkint32 _lineNum)
void GetSettings (kkint32 settingNum, KKStrConstPtr &name, KKStrConstPtr &value, kkint32 &lineNum)
kkint32 LineNum () const
KKStrConstPtr LookUpValue (const KKStr &_name, kkint32 &lineNum)
kkint32 MemoryConsumedEstimated () const
KKStrConstPtr Name ()
kkint32 NumOfSettings () const
KKStrConstPtr SettingName (kkint32 settingNum) const
KKStrConstPtr SettingValue (kkint32 settingNum, kkint32 &lineNum) const
Detailed Description
Definition at line 135 of file Configuration.cpp.
Constructor & Destructor Documentation
KKB::Configuration::ConfSection::ConfSection (const KKStr & _name, kkint32 _lineNum) [inline]
Definition at line 138 of file Configuration.cpp.
References ConfSection(), and KKB::KKStr::KKStr().
Referenced by ConfSection().
                 :
          lineNum (_lineNum),
          name (_name),
          settings ()
    {}
KKB::Configuration::ConfSection::ConfSection (const Configuration::ConfSection & cs) [inline]
Definition at line 146 of file Configuration.cpp.
References ConfSection(), and KKB::KKStr::KKStr().
Referenced by KKB::Configuration::Configuration(), and ConfSection().
                                                      :
           lineNum (cs.lineNum),
           name (cs.name),
           settings (cs.settings)
    {}
Member Function Documentation
void KKB::Configuration::ConfSection::AddSetting (const KKStr & _name, const KKStr & _value, kkint32 _lineNum) [inline]
Definition at line 203 of file Configuration.cpp.
    {
      settings.AddSetting (_name, _value, _lineNum);
    }
void KKB::Configuration::ConfSection::GetSettings (kkint32 settingNum, KKStrConstPtr & name, KKStrConstPtr & value, kkint32 & lineNum) [inline]
Definition at line 181 of file Configuration.cpp.
References KKB::Configuration::Setting::LineNum(), KKB::Configuration::Setting::Name(), and KKB::Configuration::Setting::Value().
Referenced by KKB::Configuration::GetSetting().
    {
      SettingPtr setting = settings.IdxToPtr (settingNum);
      if (setting)
      {
        name = setting->Name ();
        value = setting->Value ();
        lineNum = setting->LineNum ();
      }
      else
      {
        name = NULL;
        value = NULL;
        lineNum = -1;
      }
    }
kkint32 KKB::Configuration::ConfSection::LineNum () const [inline]
Definition at line 153 of file Configuration.cpp.
Referenced by KKB::Configuration::SectionLineNum().
{return lineNum;}
KKStrConstPtr KKB::Configuration::ConfSection::LookUpValue (const KKStr & _name, kkint32 & lineNum) [inline]
Definition at line 211 of file Configuration.cpp.
References KKB::Configuration::Setting::LineNum(), and KKB::Configuration::Setting::Value().
Referenced by KKB::Configuration::SettingValue(), and KKB::Configuration::SettingValueToStr().
    {
      SettingPtr setting = settings.LookUp (_name);
      if (setting)
      {
        lineNum = setting->LineNum ();
        return setting->Value ();
      }
      else
      {
        lineNum = -1;
        return NULL;
      }
    }
kkint32 KKB::Configuration::ConfSection::MemoryConsumedEstimated () const [inline]
Definition at line 157 of file Configuration.cpp.
    {
      return sizeof (lineNum) + name.MemoryConsumedEstimated () + settings.
      MemoryConsumedEstimated ();
    }
KKStrConstPtr KKB::Configuration::ConfSection::Name () [inline]
Definition at line 155 of file Configuration.cpp.
Referenced by KKB::Configuration::ConfSectionList::LookUp(), and KKB::Configuration::SectionName().
{return &name;}
kkint32 KKB::Configuration::ConfSection::NumOfSettings () const [inline]
Definition at line 163 of file Configuration.cpp.
Referenced by KKB::Configuration::NumOfSettings().
{return settings.QueueSize ();}
KKStrConstPtr KKB::Configuration::ConfSection::SettingName (kkint32 settingNum) const [inline]
Definition at line 166 of file Configuration.cpp.
Referenced by KKB::Configuration::SettingName().
    {
      if (settingNum >= (kkint32)settings.size ())
        return NULL;
      return settings[settingNum].Name ();
    }
KKStrConstPtr KKB::Configuration::ConfSection::SettingValue (kkint32 settingNum, kkint32 & lineNum) const [inline]
Definition at line 173 of file Configuration.cpp.
    {
      if (settingNum >= (kkint32)settings.size ())
        return NULL;
      lineNum = settings[settingNum].LineNum ();
      return settings[settingNum].Value ();
    }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Configuration.cpp