KKB::XmlElementArrayFloat2DVarying Class Reference
#include <XmlStream.h>
Public Member Functions
XmlElementArrayFloat2DVarying (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
virtual ~XmlElementArrayFloat2DVarying ()
kkuint32 Height () const
float ** TakeOwnership ()
kkuint32 * TakeOwnershipWidths ()
float ** Value () const
kkuint32 * Widths () const
Static Public Member Functions
static void WriteXML (kkuint32 height, const kkint32 *widths, float **const mat, const KKStr &varName, std::ostream &o)
Additional Inherited Members
Detailed Description
Definition at line 611 of file XmlStream.h.
Constructor & Destructor Documentation
XmlElementArrayFloat2DVarying::XmlElementArrayFloat2DVarying (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log)
Definition at line 1283 of file XmlStream.cpp.
References KKB::XmlTag::AttributeValueInt32(), KKB::XmlStream::GetNextToken(), and KKB::XmlElement::XmlElement().
                                                             :
    XmlElement (tag, s, log),
    height (0),
    widths (NULL),
    value (NULL)
{
  height = tag->AttributeValueInt32 ("Height");
  if (height < 1)
  {
    log.Level (-1) << endl
      << "XmlElementArrayFloat2DVarying ***ERROR*** Height[" << height << "] must be greater than 0." <
      < endl
      << endl;
    height = 0;
    return;
  }
  value = new float*[height];
  widths = new kkuint32[height];
  XmlTokenPtr tok = s.GetNextToken (cancelFlag, log);
  kkuint32 rowCount = 0;
  while (tok)
  {
    if (typeid(*tok) == typeid(XmlElementArrayFloat))
    {
      if (rowCount >= height)
      {
        log.Level (-1) << endl
          << "XmlElementArrayFloat2DVarying ***ERROR*** Number of defined rows exceeds defined Height["
       << height << "]" << endl
          << endl;
        widths[rowCount] = 0;
        value[rowCount] = NULL;
      }
      else
      {
        XmlElementArrayFloatPtr f = dynamic_cast<
      XmlElementArrayFloatPtr>(tok);
        widths[rowCount] = f->Count ();
        value[rowCount] = f->TakeOwnership ();
      }
      ++rowCount;
    }
    delete tok;
    tok = s.GetNextToken (cancelFlag, log);
  }
  while (rowCount < height)
  {
    value[rowCount] = NULL;
    ++rowCount;
  }
}
XmlElementArrayFloat2DVarying::~XmlElementArrayFloat2DVarying () [virtual]
Definition at line 1339 of file XmlStream.cpp.
{
  if (value)
  {
    for (kkuint32 x = 0; x < height; ++x)
    {
      delete value[x];
      value[x] = NULL;
    }
  }
  delete value; value = NULL;
  delete widths; widths = NULL;
}
Member Function Documentation
kkuint32 KKB::XmlElementArrayFloat2DVarying::Height () const [inline]
Definition at line 622 of file XmlStream.h.
{return height;}
float ** XmlElementArrayFloat2DVarying::TakeOwnership ()
Definition at line 1356 of file XmlStream.cpp.
{
  float** v = value;
  value = NULL;
  return v;
}
kkuint32 * XmlElementArrayFloat2DVarying::TakeOwnershipWidths ()
Definition at line 1364 of file XmlStream.cpp.
{
  kkuint32* w = widths;
  widths = NULL;
  return w;
}
float** KKB::XmlElementArrayFloat2DVarying::Value () const [inline]
Definition at line 624 of file XmlStream.h.
{return value;}
kkuint32* KKB::XmlElementArrayFloat2DVarying::Widths () const [inline]
Definition at line 626 of file XmlStream.h.
{return widths;}
void XmlElementArrayFloat2DVarying::WriteXML (kkuint32 height, const kkint32 * widths, float **const mat, const KKStr & varName, std::ostream & o) [static]
Parameters
widths Each entry in array defines the length of the corresponding row in 'mat'.
Definition at line 1374 of file XmlStream.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::operator+(), KKB::StrFormatInt(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("ArrayFloat2DVarying", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.AddAtribute ("Height", (kkint32)height);
  startTag.WriteXML (o);
  o << endl;
  for (kkuint32 r = 0; r < height; ++r)
  {
    KKStr rowName = "Row_" + StrFormatInt (r, "000");
    XmlElementArrayFloat::WriteXML (widths[r], mat[r], rowName, o);
  }
  XmlTag endTag ("ArrayFloat2DVarying", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp