KKLSC::ScannerFile2BitEncoded Class Reference
Implements a 2 bit Encoded format.
#include <ScannerFile2BitEncoded.h>
Classes
union OpRec
struct OpRecEndOfScanLine
struct OpRecRawPixelOne
struct OpRecRawPixelsTwo
struct OpRecRawPixelsVarLen12Bit
struct OpRecRawPixelsVarLen12Bit_2
struct OpRecRawPixelsVarLen4Bit
struct OpRecRunLen10Bit
struct OpRecRunLen10Bit_2
struct OpRecRunLenPVx
struct OpRecTextBlock
struct OpRecTextBlock_2
struct RawPixelRec
Public Types
typedef ScannerFile2BitEncoded * ScannerFile2BitEncodedPtr
Public Member Functions
ScannerFile2BitEncoded (const KKStr &_fileName, RunLog &_log)
ScannerFile2BitEncoded (const KKStr &_fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog &_log)
virtual ~ScannerFile2BitEncoded ()
virtual Format FileFormat () const
virtual void ScanRate (float _scanRate)
virtual void WriteTextBlock (const uchar *txtBlock, kkuint32 txtBlockLen)
Static Public Member Functions
static const uchar * CompensationTable ()
Protected Member Functions
kkuint32 ReadBufferFrame ()
Read on one Scanner File Frame.
virtual kkint64 SkipToNextFrame ()
Skip to start of next frame returning back byte offset of that frame.
virtual void WriteBufferFrame ()
Write the contents of 'frameBuffer' to he end of the scanner file.
Additional Inherited Members
Detailed Description
Implements a 2 bit Encoded format.
This is a very simple implementation of run-length compression. All pixels will be translated from 8 bit to 2 bit.
 All data will be stored in two byte records with the exception of text.
 each 2 byte record will start with a 3 bit OpCode and a one bit eol flag.
 the rest of the 12 bits will be organized depending on the opcode field.
 Bits
 =====
 0 - 2: OP-Code
 3 - 3: EOL Flag; End of ScanLine '0' = Not end of line, '1' = End of line.
Op-Code
  0: Text Block
     Bits 4 - 15 Length of text block in 4 byte groups. So number in this field
                  is multiplied by 4 to get the total number of bytes. This allows
                  for up to (4096 * 4) bytes.
  1: 3 Raw Bytes
      Pix0 Pix1 Pix2
     (4-7) (8-11) (12-15)
  2: Number of White Spaces
     Bits 4 - 15 Number of 4 pixels that are background (0). The total length of
                  this field is this number times 4 allowing for a run-length of up
                  to (4 * 4096) spaces divisible by 4.
Definition at line 45 of file ScannerFile2BitEncoded.h.
Member Typedef Documentation
typedef ScannerFile2BitEncoded* KKLSC::ScannerFile2BitEncoded::ScannerFile2BitEncodedPtr
Definition at line 48 of file ScannerFile2BitEncoded.h.
Constructor & Destructor Documentation
ScannerFile2BitEncoded::ScannerFile2BitEncoded (const KKStr & _fileName, RunLog & _log)
Definition at line 163 of file ScannerFile2BitEncoded.cpp.
References KKLSC::ScannerFile::ScannerFile().
                                                :
  ScannerFile (_fileName, _log),
  rawPixelRecBuffer (NULL),
  rawPixelRecBufferLen (0),
  rawPixelRecBufferSize (0),
  encodedBuff (NULL),
  encodedBuffLen (0),
  encodedBuffNext (NULL),
  encodedBuffSize (0),
  rawStr (NULL),
  rawStrLen (0),
  rawStrSize (0),
  runLen (0),
  runLenChar (0),
  curCompStatus (csNull)
{
  BuildConversionTables ();
}
ScannerFile2BitEncoded::ScannerFile2BitEncoded (const KKStr & _fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog & _log)
Definition at line 188 of file ScannerFile2BitEncoded.cpp.
References KKLSC::ScannerFile::ScannerFile().
                                                :
  ScannerFile (_fileName, _pixelsPerScanLine, _frameHeight, _log),
  rawPixelRecBuffer (NULL),
  rawPixelRecBufferLen (0),
  rawPixelRecBufferSize (0),
  encodedBuff (NULL),
  encodedBuffLen (0),
  encodedBuffNext (NULL),
  encodedBuffSize (0),
  rawStr (NULL),
  rawStrLen (0),
  rawStrSize (0),
  runLen (0),
  runLenChar (0),
  curCompStatus (csNull)
{
  BuildConversionTables ();
  AllocateEncodedBuff ();
  AllocateRawStr (_pixelsPerScanLine + 100);
}
ScannerFile2BitEncoded::~ScannerFile2BitEncoded (void) [virtual]
Definition at line 215 of file ScannerFile2BitEncoded.cpp.
{
  if (opened)
    Close ();
  delete encodedBuff; encodedBuff = NULL;
  delete rawPixelRecBuffer; rawPixelRecBuffer = NULL;
  delete rawStr; rawStr = NULL;
}
Member Function Documentation
const uchar * ScannerFile2BitEncoded::CompensationTable () [static]
Definition at line 331 of file ScannerFile2BitEncoded.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKLSC::ScannerFile::ConpensationTable().
{
  GlobalGoalKeeper::StartBlock ();
  if (!compensationTable)
    BuildConversionTables ();
  GlobalGoalKeeper::EndBlock ();
  return compensationTable;
} /* CompensationTable */
virtual Format KKLSC::ScannerFile2BitEncoded::FileFormat () const [inline], [virtual]
Reimplemented from KKLSC::ScannerFile.
Definition at line 65 of file ScannerFile2BitEncoded.h.
References KKLSC::ScannerFile::sf2BitEncoded.
{return Format::sf2BitEncoded;}
kkuint32 ScannerFile2BitEncoded::ReadBufferFrame () [protected], [virtual]
Read on one Scanner File Frame.
Implements KKLSC::ScannerFile.
Definition at line 368 of file ScannerFile2BitEncoded.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::frameBuffer, KKLSC::ScannerFile::frameBufferFileOffsetLast, KKLSC::ScannerFile::frameBufferFileOffsetNext, KKLSC::ScannerFile::frameBufferLen, KKLSC::ScannerFile::frameBufferNextLine, and KKB::osFTELL().
{
  frameBufferLen = 0;
  frameBufferNextLine = 0;
  if (feof (file) != 0)
  {
    memset (frameBuffer, 0, frameBufferSize);
    return 0;
  }
  frameBufferFileOffsetLast = osFTELL (file);
  kkuint32 numScanLinesReadThisFrameBuffer = 0;
  uchar* buffPtr = frameBuffer;
  while ((feof (file) == 0) && (numScanLinesReadThisFrameBuffer <
      frameHeight))
  {
    GetNextScanLine (buffPtr, pixelsPerScanLine);
    frameBufferLen += pixelsPerScanLine;
    buffPtr += pixelsPerScanLine;
    ++numScanLinesReadThisFrameBuffer;
  }
  frameBufferFileOffsetNext = osFTELL (file);
  frameBufferNextLine = 0;
  return numScanLinesReadThisFrameBuffer;
} /* ReadBufferFrame */
void ScannerFile2BitEncoded::ScanRate (float _scanRate) [virtual]
Reimplemented from KKLSC::ScannerFile.
Definition at line 356 of file ScannerFile2BitEncoded.cpp.
{
  ScannerFile::ScanRate (_scanRate);
}
kkint64 ScannerFile2BitEncoded::SkipToNextFrame () [protected], [virtual]
Skip to start of next frame returning back byte offset of that frame.
This will be called by the 'UpdateFrameOffset' and 'DetermineFrameOffsetForFrame' methods used to build the 'frameOffsets' table. It is important that the implementation of this method NOT update the frameBuffer fields; such as 'frameBuffer', 'frameBufferNextLine', etc .....
Implements KKLSC::ScannerFile.
Definition at line 396 of file ScannerFile2BitEncoded.cpp.
References KKLSC::ScannerFile::pixelsPerScanLine.
{
  uchar* scanLine = new uchar[pixelsPerScanLine];
  kkuint32 numScanLinesReadThisFrameBuffer = 0;
  while ((feof (file) == 0) && (numScanLinesReadThisFrameBuffer <
      frameHeight))
  {
    GetNextScanLine (scanLine, pixelsPerScanLine);
    ++numScanLinesReadThisFrameBuffer;
  }
  if (feof (file) != 0)
    return -1;
  else
    return osFTELL (file);
} /* SkipToNextFrame */
void ScannerFile2BitEncoded::WriteBufferFrame () [protected], [virtual]
Write the contents of 'frameBuffer' to he end of the scanner file.
Implements KKLSC::ScannerFile.
Definition at line 638 of file ScannerFile2BitEncoded.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::fileSizeInBytes, KKLSC::ScannerFile::frameBuffer, KKLSC::ScannerFile::frameBufferFileOffsetLast, KKLSC::ScannerFile::frameBufferFileOffsetNext, KKLSC::ScannerFile::frameBufferNextLine, KKB::osFTELL(), and KKLSC::ScannerFile::pixelsPerScanLine.
{
  frameBufferFileOffsetLast = osFTELL (file);
  //nextScanLineOffset = osFTELL (file);
  kkuint32 frameRow = 0;
  uchar* framePtr = frameBuffer;
  while (frameRow < frameBufferNextLine)
  {
    WriteNextScanLine (framePtr, pixelsPerScanLine);
    framePtr += pixelsPerScanLine;
    ++frameRow;
  }
  frameBufferFileOffsetNext = osFTELL (file);
  fileSizeInBytes = frameBufferFileOffsetNext;
} /* WriteBufferFrame*/
void ScannerFile2BitEncoded::WriteTextBlock (const uchar * txtBlock, kkuint32 txtBlockLen) [virtual]
Implements KKLSC::ScannerFile.
Definition at line 923 of file ScannerFile2BitEncoded.cpp.
References KKLSC::ScannerFile2BitEncoded::OpRecTextBlock::endOfText, KKLSC::ScannerFile::file, KKLSC::ScannerFile::fileSizeInBytes, KKLSC::ScannerFile2BitEncoded::OpRecTextBlock::lenHigh, KKLSC::ScannerFile2BitEncoded::OpRecTextBlock_2::lenLow, KKLSC::ScannerFile2BitEncoded::OpRecTextBlock::opCode, KKB::osFTELL(), KKLSC::ScannerFile2BitEncoded::OpRec::textBlock, and KKLSC::ScannerFile2BitEncoded::OpRec::textBlock_2.
{
  kkint32 charsLeft = txtBlockLen;
  const uchar* txtBlockPtr = txtBlock;
  while (charsLeft > 0)
  {
    kkint32 charsToWrite = Min ((kkint32)2048, charsLeft);
    OpRec rec;
    rec.textBlock.opCode = 1;
    rec.textBlock.endOfText = (charsToWrite < charsLeft) ? 0 : 1;
    rec.textBlock.lenHigh = charsToWrite / 256;
    *encodedBuffNext = rec;
    ++encodedBuffNext;
    encodedBuffNext->textBlock_2.lenLow = charsToWrite % 256;
    ++encodedBuffNext;
    memcpy (encodedBuffNext, txtBlockPtr, charsToWrite);
    charsLeft -= charsToWrite;
    txtBlockPtr += charsToWrite;
    encodedBuffNext += charsToWrite;
  }
  //nextScanLineOffset = osFTELL (file);
  fileSizeInBytes = osFTELL (file);
} /* WriteTextBlock */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFile2BitEncoded.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFile2BitEncoded.cpp