KKB::ImageDirTree Class Reference
Creates a index of all images in a specified directory structure.
#include <ImageDirTree.h>
Public Member Functions
ImageDirTree (KKStr _subDir)
Construct a Index of images for a specified SubDirectory structure. details Given a specified directory '_subDir' will scan for all images in all sub-directories below it.
~ImageDirTree ()
KKStrListPtr Directories (const KKStr &fileName) const
Returns list of directories that 'fileName' occurs in.
KKStrConstPtr LocateImage (const KKStr &fileName)
Locate image specified by 'fileName' and return the directory where it is located.
kkuint32 Size ()
returns the number of image files found the sub-directory tree.
Detailed Description
Creates a index of all images in a specified directory structure.
Given a SubDirectory Starting Point. Will create a list of all image files in the sub directory tree. This will allow us to quickly locate a image file by name. Originally developed it to help in the recalculation of feature data. Used in ImageFeaturesList.
Definition at line 22 of file ImageDirTree.h.
Constructor & Destructor Documentation
ImageDirTree::ImageDirTree (KKStr _subDir)
Construct a Index of images for a specified SubDirectory structure. details Given a specified directory '_subDir' will scan for all images in all sub-directories below it.
Parameters
in _subDir Sub Directory to search for image files.
Definition at line 27 of file ImageDirTree.cpp.
References KKB::KKStr::KKStr().
Referenced by KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
                                         :
  subDir (_subDir)
{
  Load (_subDir);
}
ImageDirTree::~ImageDirTree ()
Definition at line 35 of file ImageDirTree.cpp.
{
  kkuint32 x;
  for (x = 0; x < directories.size (); x++)
    delete directories[x];
}
Member Function Documentation
KKStrListPtr ImageDirTree::Directories (const KKStr & fileName) const
Returns list of directories that 'fileName' occurs in.
The caller will own the list of directories and be responsible for deleting. if 'fileName' does not exist in the sub-directory structure then NULL will be returned.
Parameters
in fileName Name of image file that is being searched for.
Returns
List of directories that contain a image with the name specified by 'fileName'. If the file does not exist a NULL will be returned. The caller will own the string list returned.
Definition at line 133 of file ImageDirTree.cpp.
References KKB::KKStrList::KKStrList().
{
  EntryTable::const_iterator p;
  p = entries.find (fileName);
  if (p == entries.end ())
    return NULL;
  KKStrListPtr dirList = new KKStrList (true);
  while (p != entries.end ())
  {
    if (p->first != fileName)
      break;
    dirList->PushOnBack (new KKStr ((*p->second)));
  }
  return dirList;
} /* Directories */
KKStrConstPtr ImageDirTree::LocateImage (const KKStr & fileName)
Locate image specified by 'fileName' and return the directory where it is located.
Parameters
in fileName Image File you are searching for.
Returns
Pointer to directory where 'fileName' is found.
Definition at line 116 of file ImageDirTree.cpp.
Referenced by KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
{
  EntryTable::const_iterator p;
  p = entries.find (fileName);
  if (p == entries.end ())
    return NULL;
  if (p->first == fileName)
    return p->second;
  return NULL;
} /* LocateImage */
kkuint32 KKB::ImageDirTree::Size () [inline]
returns the number of image files found the sub-directory tree.
Definition at line 43 of file ImageDirTree.h.
Referenced by KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
{return (kkuint32)entries.size ();}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/ImageDirTree.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/ImageDirTree.cpp