KKLSC::ScannerFileZLib3BitEncoded Class Reference
Implements Zlib compression on 3bit pixel data.
#include <ScannerFileZLib3BitEncoded.h>
Classes
struct FourByteRec
struct OpCodeRec1
struct OpCodeRec2
struct OpCodeRec5
struct OpCodeRec6
struct OpCodeRec7
struct ThreeByteRec
struct TwoByteRec
Public Types
typedef ScannerFileZLib3BitEncoded * ScannerFile3BitEncodedPtr
Public Member Functions
ScannerFileZLib3BitEncoded (const KKStr &_fileName, RunLog &_log)
ScannerFileZLib3BitEncoded (const KKStr &_fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog &_log)
virtual ~ScannerFileZLib3BitEncoded ()
virtual Format FileFormat () const
virtual void ScanRate (float _scanRate)
virtual void WriteTextBlock (const uchar *txtBlock, kkuint32 txtBlockLen)
Additional Inherited Members
Detailed Description
Implements Zlib compression on 3bit pixel data.
Each frame of 3bit data will be compressed using the ZLIB library.
Following the header fields at the beginning of the file there will be blocks of data
where the first byte will contain a op-code that describes how to decode the following
bytes.
All data will be stored in two byte records with the exception of text.
each 2 byte record will start with a 3 bit OpCode and a one bit eol flag.
the rest of the 12 bits will be organized depending on the opcode field.
Byte 1 : Op-Code
Bytes 2 thru 1 + x: y = Length of rest of block. High order followed by low order.
Bytes 2 + x thru 1 + x + y: Data, to decoded as specified by op-code will be y bytes long
Op-Code:
: Text block up to 255 bytes long, x = 1, will be followed by "1" byte specifying text block
      length.
: Text block up to 65,535 bytes long, x = 2, will be followed by "2" bytes (High order, low order)
      specifying
    text block length.
Op-Codes 5, 6, 7 assume that frame size recorded is the same as defined in the header.
: Zlib compressed data up to 65,535 bytes, x = 2, will be followed by "2" bytes (High order, low order)
      specifying
    compressed data length.
: ZLib compressed data up to 16,777,215, x = 3, Will be followed by "3" bytes that specify length of
      compressed data.
: ZLib compressed data up to 4,294,967,295, x = 4, Will be followed by "4" bytes that specify length of
      compressed data.
Definition at line 38 of file ScannerFileZLib3BitEncoded.h.
Member Typedef Documentation
typedef ScannerFileZLib3BitEncoded* KKLSC::ScannerFileZLib3BitEncoded::ScannerFile3BitEncodedPtr
Definition at line 41 of file ScannerFileZLib3BitEncoded.h.
Constructor & Destructor Documentation
ScannerFileZLib3BitEncoded::ScannerFileZLib3BitEncoded (const KKStr & _fileName, RunLog & _log)
Constructor for opening file for reading
Definition at line 107 of file ScannerFileZLib3BitEncoded.cpp.
References KKLSC::ScannerFile::ScannerFile().
                                                        :
  ScannerFile (_fileName, _log),
  compBuffer (NULL),
  compBufferLen (0),
  compBufferSize (0)
{
  AllocateBuffers ();
}
ScannerFileZLib3BitEncoded::ScannerFileZLib3BitEncoded (const KKStr & _fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog & _log)
Constructor for opening file for Writing
Definition at line 120 of file ScannerFileZLib3BitEncoded.cpp.
References KKLSC::ScannerFile::ScannerFile().
                                                        :
  ScannerFile (_fileName, _pixelsPerScanLine, _frameHeight, _log),
  compBuffer (NULL),
  compBufferLen (0),
  compBufferSize (0)
{
  AllocateBuffers ();
}
ScannerFileZLib3BitEncoded::~ScannerFileZLib3BitEncoded (void) [virtual]
Definition at line 137 of file ScannerFileZLib3BitEncoded.cpp.
{
  if (opened)
    Close ();
  delete compBuffer;
  compBuffer = NULL;
}
Member Function Documentation
virtual Format KKLSC::ScannerFileZLib3BitEncoded::FileFormat () const [inline], [virtual]
Reimplemented from KKLSC::ScannerFile.
Definition at line 59 of file ScannerFileZLib3BitEncoded.h.
References KKLSC::ScannerFile::sfZlib3BitEncoded.
{return Format::sfZlib3BitEncoded;}
void ScannerFileZLib3BitEncoded::ScanRate (float _scanRate) [virtual]
Reimplemented from KKLSC::ScannerFile.
Definition at line 158 of file ScannerFileZLib3BitEncoded.cpp.
{
  ScannerFile::ScanRate (_scanRate);
}
void ScannerFileZLib3BitEncoded::WriteTextBlock (const uchar * txtBlock, kkuint32 txtBlockLen) [virtual]
Implements KKLSC::ScannerFile.
Definition at line 165 of file ScannerFileZLib3BitEncoded.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::fileSizeInBytes, KKLSC::ScannerFileZLib3BitEncoded::OpCodeRec1::opCode, KKLSC::ScannerFileZLib3BitEncoded::OpCodeRec2::opCode, KKB::osFTELL(), KKLSC::ScannerFileZLib3BitEncoded::OpCodeRec1::textBlockLen, KKLSC::ScannerFileZLib3BitEncoded::OpCodeRec2::textBlockLenHi, and KKLSC::ScannerFileZLib3BitEncoded::OpCodeRec2::textBlockLenLo.
{
  kkuint32 charsLeft = txtBlockLen;
  const uchar* txtBlockPtr = txtBlock;
  while (charsLeft > 0)
  {
    if (charsLeft < 256)
    {
      OpCodeRec1 rec;
      rec.opCode = 1;
      rec.textBlockLen = (uint8)charsLeft;
      fwrite (&rec, sizeof (rec), 1, file);
      fwrite (txtBlockPtr, charsLeft, 1, file);
      txtBlockPtr += charsLeft;
      charsLeft = 0;
    }
    else
    {
      kkuint32 bytesToWrite = Min ((kkuint32)65535, charsLeft);
      OpCodeRec2 rec;
      rec.opCode = 2;
      rec.textBlockLenHi = (uint8)(bytesToWrite / 256);
      rec.textBlockLenLo = (uint8)(bytesToWrite % 256);
      fwrite (&rec, sizeof (rec), 1, file);
      fwrite (txtBlockPtr, bytesToWrite, 1, file);
      txtBlockPtr += bytesToWrite;
      charsLeft -= bytesToWrite;
    }
  }
  fileSizeInBytes = osFTELL (file);
} /* WriteTextBlock */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFileZLib3BitEncoded.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFileZLib3BitEncoded.cpp