KKB::Configuration::Setting Class Reference
Public Member Functions
Setting (const KKStr &_name, const KKStr &_value, kkint32 _lineNum)
Setting (const Configuration::Setting &s)
kkint32 LineNum () const
kkint32 MemoryConsumedEstimated () const
KKStrConstPtr Name () const
KKStrConstPtr Value () const
Detailed Description
Definition at line 31 of file Configuration.cpp.
Constructor & Destructor Documentation
KKB::Configuration::Setting::Setting (const KKStr & _name, const KKStr & _value, kkint32 _lineNum) [inline]
Definition at line 34 of file Configuration.cpp.
References KKB::KKStr::KKStr().
             :
      lineNum (_lineNum),
      name (_name),
      value (_value)
    {}
KKB::Configuration::Setting::Setting (const Configuration::Setting & s) [inline]
Definition at line 43 of file Configuration.cpp.
References KKB::KKStr::KKStr().
                                            :
        lineNum (s.lineNum),
        name (s.name),
        value (s.value)
    {}
Member Function Documentation
kkint32 KKB::Configuration::Setting::LineNum () const [inline]
Definition at line 49 of file Configuration.cpp.
Referenced by KKB::Configuration::ConfSection::GetSettings(), KKB::Configuration::SettingList::LookUpLineNum(), and KKB::Configuration::ConfSection::LookUpValue().
{return lineNum;}
kkint32 KKB::Configuration::Setting::MemoryConsumedEstimated () const [inline]
Definition at line 53 of file Configuration.cpp.
References KKB::KKStr::MemoryConsumedEstimated().
{return sizeof (Setting) + name.MemoryConsumedEstimated () + value.
      MemoryConsumedEstimated ();}
KKStrConstPtr KKB::Configuration::Setting::Name () const [inline]
Definition at line 50 of file Configuration.cpp.
Referenced by KKB::Configuration::ConfSection::GetSettings(), KKB::Configuration::SettingList::LookUp(), and KKB::Configuration::SettingList::LookUpLineNum().
{return &name;}
KKStrConstPtr KKB::Configuration::Setting::Value () const [inline]
Definition at line 51 of file Configuration.cpp.
Referenced by KKB::Configuration::ConfSection::GetSettings(), and KKB::Configuration::ConfSection::LookUpValue().
{return &value;}
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Configuration.cpp