KKMLL::FeatureFileIOC45 Class Reference
Supports the reading and writing of feature data from C45 formated feature files.
#include <FeatureFileIOC45.h>
Public Types
typedef FeatureFileIOC45 * FeatureFileIOC45Ptr
Public Member Functions
FeatureFileIOC45 ()
~FeatureFileIOC45 ()
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, istream &_in, MLClassListPtr _classList, kkint32 &_estSize, KKStr &_errorMessage, RunLog &log)
virtual FeatureVectorListPtr LoadFeatureFile (const KKStr &_fileName, MLClassList &_mlClasses, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_successful, bool &_changesMade, RunLog &_log)
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassList &_classes, istream &_in, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, FeatureNumListConst &_selFeatures, ostream &_out, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)
Static Public Member Functions
static FeatureFileIOC45Ptr Driver ()
Additional Inherited Members
Detailed Description
Supports the reading and writing of feature data from C45 formated feature files.
FeatureFileIODC45 Sub-classed from FeatureFileIO. Supports the reading and writing of *
the C45 file format. For each data set there will be two files. 'Names' and 'Data' *
http://www.cs.washington.edu/dm/vfml/appendixes/c45.htm for description *
See also
FeatureFileIO
Definition at line 21 of file FeatureFileIOC45.h.
Member Typedef Documentation
typedef FeatureFileIOC45* KKMLL::FeatureFileIOC45::FeatureFileIOC45Ptr
Definition at line 28 of file FeatureFileIOC45.h.
Constructor & Destructor Documentation
FeatureFileIOC45::FeatureFileIOC45 ()
Definition at line 33 of file FeatureFileIOC45.cpp.
References KKMLL::FeatureFileIO::FeatureFileIO().
                                   :
  FeatureFileIO ("C45", true, true)
{
}
FeatureFileIOC45::~FeatureFileIOC45 ()
Definition at line 40 of file FeatureFileIOC45.cpp.
{
}
Member Function Documentation
static FeatureFileIOC45Ptr KKMLL::FeatureFileIOC45::Driver () [inline], [static]
Definition at line 30 of file FeatureFileIOC45.h.
Referenced by KKMLL::GrayScaleImagesFVProducerFactory::DefaultFeatureFileIO().
{return &driver;}
FileDescPtr FeatureFileIOC45::GetFileDesc (const KKStr & _fileName, istream & _in, MLClassListPtr _classList, kkint32 & _estSize, KKStr & _errorMessage, RunLog & log) [virtual]
Definition at line 396 of file FeatureFileIOC45.cpp.
References KKMLL::FileDesc::AddClasses(), KKB::KKStr::ChopLastChar(), KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKMLL::FileDesc::FileDesc(), KKMLL::FeatureFileIO::GetLine(), KKMLL::MLClassList::GetMLClassPtr(), KKB::KKStr::KKStr(), KKB::KKStr::LastChar(), KKB::KKStr::Len(), KKB::KKStr::operator=(), KKB::KKStr::operator[](), KKB::KKStr::Split(), and KKB::KKStr::SubStrPart().
{
  KKStr namesFileName;
 
  bool classLineRead = false;
  KKStr ln (1024);
  bool eof = false;
  kkint32 lineNum = 0;
  GetLine (_in, ln, eof); lineNum++;
  while ((!eof) && (!classLineRead))
  {
    C45StripComments (ln);
    if (!ln.Empty ())
    {
      // We have our very first line, this should consist
      // of all the class names.
      // Eliminate any trailing period.
      if (ln.LastChar () == '.')
        ln.ChopLastChar ();
      VectorKKStr classNames = ln.Split ("\n\r\t,");
      for (kkint32 idx = 0; idx < (kkint32)classNames.size (); idx++)
      {
        KKStr className = classNames[idx];
        C45StrPreProcessName (className);
        MLClassPtr mlClass = _classes->GetMLClassPtr (className);
      }
      classLineRead = true;
    }
    else
    {
      GetLine (_in, ln, eof); lineNum++;
    }
  }
  if (!classLineRead)
  {
    _log.Level (-1) << endl
                   << "FeatureFileIOC45::GetFileDesc *** ERROR *** No class line in Names File." <<
      endl
                   << endl;
    _errorMessage = "No class line in Names File.";
    return NULL;
  }
  FileDescPtr fileDesc = new FileDesc ();
  fileDesc->AddClasses (*_classes);
  // Can now load in attribute data
  GetLine (_in, ln, eof); lineNum++;
  while (!eof)
  {
    C45StripComments (ln);
    // "ln" may consist of more than one attribute descriptor separated by periods.
    while (!ln.Empty ())
    {
      bool validStr = true;
      // Locate a period followed by white space, if not followed by
      // white space, will be part of a name.
      kkuint32 dotPos = 0;
      while (dotPos < ln.Len ())
      {
        if (ln[dotPos] == '.')
        {
          if (dotPos >= (ln.Len () - 1))
            break;
          else if (strchr (" \t\r\n", ln[dotPos + 1]))
            break;
        }
        dotPos++;
      }
      KKStr attrStr;
      if (dotPos >= ln.Len ())
      {
        attrStr = ln;
        ln = "";
      }
      else
      {
        attrStr = ln.SubStrPart (0, dotPos - 1);
        ln = ln.SubStrPart (dotPos + 1);
      }
      KKStr origAttrStr (attrStr);
      ProcessC45AttrStr (fileDesc, attrStr, validStr, _log);
      if (!validStr)
      {
        _log.Level (-1) << endl
                        << "FeatureFileIOC45::GetFileDesc ***ERROR*** Invalid AttributeStr[" <<
      origAttrStr << "]." << endl
                        << " LineNum[" << lineNum
            << "]" << endl
                        << endl;
        _errorMessage = "No class line in Names File.";
        _errorMessage << "Invalid AttributeStr[" << origAttrStr << "], LineNum[" << lineNum << "]";
        // Can not delete an instance of a 'FileDesc' class once it has been created.
        // delete fileDesc; fileDesc = NULL;
        return NULL;
      }
    }
    GetLine (_in, ln, eof); lineNum++;
  }
  return fileDesc;
} /* GetFileDesc */
FeatureVectorListPtr FeatureFileIOC45::LoadFeatureFile (const KKStr & _fileName, MLClassList & _mlClasses, kkint32 _maxCount, VolConstBool & _cancelFlag, bool & _successful, bool & _changesMade, RunLog & _log) [virtual]
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
Parameters
in _fileName Feature file that is being synchronized.
in,out _mlClasses All classes encountered during the loading of the feature file will be added to this list.
in _maxCount Maximum number of examples to load, -1 = load all
in _cancelFlag If this flag turns true the load will terminate and return to caller.
out _successful False will be returned if load failed.
out _changesMade If the routine had loaded the feature data determined that it needed to make changes this flag will be set 'true'.
in _log Where to send diagnostic messages to.
Returns
A ImageFeaturesList container object; this object will own all the examples loaded.
Parameters
_cancelFlag will be monitored, if set to True Load will terminate.
Reimplemented from KKMLL::FeatureFileIO.
Definition at line 47 of file FeatureFileIOC45.cpp.
References KKB::KKStr::Concat(), KKMLL::FileDesc::GetExistingFileDesc(), KKB::KKStr::LocateLastOccurrence(), KKB::KKStr::operator+(), KKB::KKStr::operator=(), KKB::KKStr::operator==(), KKB::osFileExists(), KKB::KKStr::SubStrPart(), and KKB::KKStr::Upper().
{
  _log.Level (10) << "FeatureFileIOC45::LoadFeatureFile File[" << _fileName << "] FileFormat[" <<
      DriverName () << "]" << endl;
  
  if (_maxCount < 0)
    _maxCount = int32_max;
  KKStr namesFileName;
  KKStr dataFileName;
  {
    // First determine the name of the names and data file.
    kkint32 lastDotPos = _fileName.LocateLastOccurrence ('.');
    if (lastDotPos < 0)
    {
      namesFileName = _fileName + ".names";
      dataFileName = _fileName;
      if (!osFileExists (dataFileName))
        dataFileName = _fileName + ".data";
    }
    else
    {
      KKStr leadingPart = _fileName.SubStrPart (0, lastDotPos - 1);
      KKStr extension = _fileName.SubStrPart (lastDotPos + 1);
      extension.Upper ();
      if (extension == "NAMES")
      {
        // The file name was already the names file, can use as is
        namesFileName = _fileName;
        dataFileName = leadingPart;
        if (!osFileExists (dataFileName))
        {
          dataFileName = leadingPart + ".data";
          if (!osFileExists (dataFileName))
            dataFileName = leadingPart + ".test";
        }
      }
      else if ((extension == "DATA") || (extension == "TEST"))
      {
        dataFileName = _fileName;
        namesFileName = leadingPart + ".names";
        if (!osFileExists (namesFileName))
        {
          namesFileName = leadingPart + ".names";
          if (!osFileExists (namesFileName))
          {
            namesFileName = _fileName + ".names";
            if (!osFileExists (namesFileName))
              namesFileName = leadingPart + ".names";
          }
        }
      }
      else
      {
        dataFileName = _fileName;
        namesFileName = _fileName + ".names";
      }
    }
  }
  _changesMade = false;
  kkint32 estimatedNumOfDataItems = -1;
  
  _successful = true;
  ifstream namesFile (namesFileName.Str (), ios_base::in);
  if (!namesFile.is_open ())
  {
    _log.Level (-1) << "FeatureFileIOC45::LoadFeatureFile ***ERROR*** Error Opening File[" <<
      dataFileName << "]." << endl;
    _successful = false;
    return NULL;
  }
  KKStr errorMessage;
  
  FileDescPtr fileDesc = GetFileDesc (namesFileName, namesFile, &_mlClasses,
      estimatedNumOfDataItems, errorMessage, _log);
  if (fileDesc == NULL)
  {
    _log.Level (-1) << endl << endl
                   << "FeatureFileIOC45::LoadFeatureFile ***ERROR*** Loading Feature File[" <<
      namesFileName << "]" << endl
                   << endl;
    _successful = false;
    return NULL;
  }
  namesFile.close ();
  fileDesc = FileDesc::GetExistingFileDesc (fileDesc);
  ifstream dataFile (dataFileName.Str (), ios_base::in);
  if (!dataFile.is_open ())
  {
    _log.Level (-1) << "FeatureFileIOC45::LoadFeatureFile ***ERROR*** Error Opening File[" <<
      dataFileName << "]." << endl;
    _successful = false;
    return NULL;
  }
  FeatureVectorListPtr examples = LoadFile (dataFileName, fileDesc, _mlClasses
      , dataFile, _maxCount, _cancelFlag, _changesMade, errorMessage, _log);
  if (examples == NULL)
  {
    _successful = false;
  }
  else
  {
    _successful = true;
  }
  dataFile.close ();
  return examples;
} /* LoadFeatureFile */
FeatureVectorListPtr FeatureFileIOC45::LoadFile (const KKStr & _fileName, const FileDescPtr _fileDesc, MLClassList & _classes, istream & _in, kkint32 _maxCount, VolConstBool & _cancelFlag, bool & _changesMade, KKStr & _errorMessage, RunLog & _log) [virtual]
Definition at line 725 of file FeatureFileIOC45.cpp.
References KKMLL::Attribute::AddANominalValue(), KKMLL::FeatureVector::AddFeatureData(), KKB::KKStr::Concat(), KKMLL::FileDesc::CreateAAttributeTable(), KKB::KKStr::Empty(), KKB::KKStr::EqualIgnoreCase(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FeatureVector::FeatureVector(), KKMLL::FeatureVectorList::FeatureVectorList(), KKMLL::Attribute::GetNominalCode(), KKMLL::Ignore, KKMLL::FileDesc::LookUpMLClassByName(), KKMLL::FileDesc::LookUpUnKnownMLClass(), KKMLL::FeatureVector::MissingData(), KKMLL::FeatureVector::MLClass(), KKMLL::Attribute::Name(), KKMLL::Nominal, KKMLL::Numeric, KKMLL::FileDesc::NumOfFields(), KKB::KKStr::operator+(), KKB::KKStr::operator=(), KKB::KKStr::operator==(), KKB::osGetRootName(), KKMLL::FeatureVectorList::PushOnBack(), KKB::StrFormatInt(), KKMLL::Symbolic, KKB::KKStr::ToFloat(), and KKMLL::Attribute::Type().
{
  _log.Level (10) << "FeatureFileIOC45::LoadFile FileName[" << _fileName << "]" <<
      endl;
  bool eof = false;
  bool eol = false;
  kkint32 numOfFeatures = _fileDesc->NumOfFields ();
  KKStr fileRootName = osGetRootName (_fileName);
  kkint32 lineCount = 0;
  const
    AttributePtr* attributeTable = _fileDesc->CreateAAttributeTable ();
      // Caller will be responsible for deleting
  bool lineIsValid = true;
  KKStr imageFileName = "";
  FeatureVectorListPtr examples = new FeatureVectorList (_fileDesc,
      true);
  while (!eof)
  {
    lineIsValid = true;
    imageFileName = "";
    KKStr field = C45ReadNextToken (_in, ",", eof, eol);
    if (eof)
      break;
    if (eol)
    {
      // We have a blank line
      continue;
    }
    FeatureVectorPtr example = new FeatureVector (numOfFeatures);
    kkint32 fieldNum = 0;
    // Process all fields for this row 'numOfFeatures'
    for (fieldNum = 0; fieldNum < numOfFeatures; fieldNum++)
    {
      if (eol || eof)
      {
        _errorMessage << "Not all Features were accounted for on Line[" << lineCount << "].";
        _log.Level (-1) << endl << endl
                        << "FeatureFileIOC45::LoadFile " << _errorMessage << endl
                        << endl;
        delete examples; examples = NULL;
        delete example; example = NULL;
        return NULL;
      }
      switch (attributeTable[fieldNum]->Type ())
      {
      case AttributeType::Ignore:
        example->AddFeatureData (fieldNum, field.ToFloat ());
        break;
              
      case AttributeType::Numeric:
        example->AddFeatureData (fieldNum, field.ToFloat ());
        break;
      case AttributeType::Nominal:
      {
        kkint32 code = -1; // Initialize to value for missing data.
        if (field == "?")
        {
          // Will flag this entry as having missing data.
          example->MissingData (true);
        }
        else
        {
          // This is not a missing data.
          code = attributeTable[fieldNum]->GetNominalCode (field);
          if (code < 0)
          {
            _errorMessage << "Invalid NominalValue[" << field << "] on line[" << lineCount << "].";
            _log.Level (-1) << endl << endl
                            << "FeatureFileIOC45::LoadFile " << _errorMessage << endl
                            << endl;
            delete examples; examples = NULL;
            delete example; example = NULL;
            return NULL;
          }
        }
        example->AddFeatureData (fieldNum, (float)code);
        break;
      }
        
      case AttributeType::Symbolic:
      {
        kkint32 code = -1; // Initialize to value for missing data.
        if (field == "?")
        {
          // Will flag this entry as having missing data.
          example->MissingData (true);
        }
        else
        {
          // This is not a missing data.
          if (attributeTable[fieldNum]->Name ().EqualIgnoreCase ("ExampleFileName"))
            imageFileName = field;
          code = attributeTable[fieldNum]->GetNominalCode (field);
          if (code < 0)
          {
            bool alreadyExists = false;
            attributeTable[fieldNum]->AddANominalValue (field, alreadyExists);
            code = attributeTable[fieldNum]->GetNominalCode (field);
          }
        }
        example->AddFeatureData (fieldNum, (float)code);
        break;
      }
      default:
        _log.Level (-1) << endl << endl
                        << "FeatureFileIOC45::LoadFile *** Undefined Field Type ***" << endl
                        << endl;
        break;
      } /* End of switch */
      field = C45ReadNextToken (_in, " ,", eof, eol);
    }
    // 'field' should have the class name in it
    if ((field.Empty ()) || eol)
    {
      _errorMessage << "Line[" << lineCount << "] Missing ClassName.";
      _log.Level (-1) << endl << endl
                      << "FeatureFileIOC45::LoadFile " << _errorMessage << endl
                      << endl;
      
      delete examples; examples = NULL;
      delete example; example = NULL;
      return NULL;
    }
    
    MLClassPtr mlClass = NULL;
    if (field == "?")
    {
      // The class is unknown
      mlClass = _fileDesc->LookUpUnKnownMLClass ();
    }
    else
    {
      mlClass = _fileDesc->LookUpMLClassByName (field);
      if (!mlClass)
      {
        lineIsValid = false;
        _errorMessage << "Line[" << lineCount << "] Invalid Class[" << field << "]";
        _log.Level (-1) << endl << endl
                        << "FeatureFileIOC45::LoadFile " << _errorMessage << endl
                        << endl;
        delete examples; examples = NULL;
        delete example; example = NULL;
        return NULL;
      }
    }
    example->MLClass (mlClass);
    if (imageFileName.Empty ())
      imageFileName = fileRootName + "_" + StrFormatInt (lineCount, "ZZZZZ0");
    example->ExampleFileName (imageFileName);
    if (lineIsValid)
      examples->PushOnBack (example);
    lineCount++;
    if (!eof)
    {
      // Consume the rest of the characters in the line so that the next pass starts at
      // the beginning of the next line.
      kkint32 ch = _in.peek ();
      while ((ch != '\n') && (ch != '\r') && (!_in.eof ()))
      {
        _in.get ();
        ch = _in.peek ();
      }
      if (!_in.eof ())
      {
        _in.get ();
        if ((ch == '\n') && (_in.peek () == '\r'))
           _in.get ();
        else if ((ch == '\r') && (_in.peek () == '\n'))
           _in.get ();
      }
    }
    if ((lineCount % 1000) == 0)
      cout << "Records Loaded " << lineCount << endl;
    if ((kkint32)examples->size () > _maxCount)
      break;
  }
  delete [] attributeTable;
  return examples;
} /* LoadFile */
void FeatureFileIOC45::SaveFile (FeatureVectorList & _data, const KKStr & _fileName, FeatureNumListConst & _selFeatures, ostream & _out, kkuint32 & _numExamplesWritten, VolConstBool & _cancelFlag, bool & _successful, KKStr & _errorMessage, RunLog & _log) [virtual]
Definition at line 1020 of file FeatureFileIOC45.cpp.
References KKMLL::Attribute::Cardinality(), KKMLL::FeatureVector::ClassName(), KKB::KKStr::Concat(), KKMLL::FileDesc::CreateAAttributeTable(), KKMLL::FeatureVectorList::ExtractListOfClasses(), KKMLL::FeatureVector::FeatureData(), KKMLL::FeatureVectorList::FileDesc(), KKMLL::FeatureVectorList::GetClassStatistics(), KKMLL::Attribute::GetNominalValue(), KKMLL::Ignore, KKMLL::Nominal, KKMLL::FeatureNumList::NumOfFeatures(), KKB::operator<<(), KKMLL::FeatureNumList::operator[](), KKMLL::Symbolic, and KKMLL::Attribute::Type().
{
  KKStr namesFileName;
  KKStr dataFileName;
  _numExamplesWritten = 0;
  
  C45ConstructFileNameForWritting (_fileName, namesFileName, dataFileName);
  FileDescPtr fileDesc = _data.FileDesc ();
  const AttributePtr* attrTable = fileDesc->CreateAAttributeTable ();
  kkint32 x;
  {
    // Write out names file
    ofstream nf (namesFileName.Str ());
    MLClassListPtr classes = _data.ExtractListOfClasses ();
    for (x = 0; x < classes->QueueSize (); x++)
    {
      if (x > 0)
        nf << ", ";
      nf << C45AdjName (classes->IdxToPtr (x)->Name ());
    }
    nf << "." << endl;
    for (x = 0; x < _selFeatures.NumOfFeatures (); x++)
    {
      kkint32 featureNum = _selFeatures[x];
      AttributePtr attr = attrTable[featureNum];
      nf << C45AdjName (attr->Name ()) << ": ";
      if (attr->Type () == AttributeType::Nominal)
      {
        kkint32 y;
        for (y = 0; y < attr->Cardinality (); y++)
        {
          if (y > 0) nf << ", ";
          nf << C45AdjName (attr->GetNominalValue (y));
        }
      }
      else if (attr->Type () == AttributeType::Symbolic)
      {
        nf << "Symbolic";
      }
      else if (attr->Type () == AttributeType::Ignore)
      {
        nf << "ignore";
      }
      else
      {
        nf << "continuous";
      }
      nf << "." << endl;
    }
    nf << "ExampleFileName" << ": " << "Symbolic" << "." << endl;
    nf.close ();
  }
  {
    // Write out class statistics as comments at top of file.
    ClassStatisticListPtr stats = _data.GetClassStatistics ();
    ClassStatisticList::iterator idx;
    _out << "| FileName [" << _fileName << "]" <<
      endl;
    _out << "| DateWritten [" << osGetLocalDateTime () << "]" <<
      endl;
    _out << "| SelectedFeatures [" << _selFeatures.ToString () << "]" <<
      endl;
    _out << "| TotalRecords [" << _data.QueueSize () << "]" <<
      endl;
    _out << "| NumAttributes [" << _selFeatures.NumOfFeatures () << "]" <<
      endl;
    _out << "|" <<
      endl;
    _out << "| Class Statistics" <<
      endl;
    _out << "| Name" << "\t" << "Count" <<
      endl;
    for (idx = stats->begin (); idx != stats->end (); idx++)
    {
      ClassStatisticPtr stat = *idx;
      _out << "| " << stat->Name () << "\t" << stat->Count () << endl;
    }
    _out << "|" << endl;
    delete stats;
  }
  kkint32 origPrecision = (kkint32)_out.precision ();
  _out.precision (9);
  FeatureVectorPtr example = NULL;
  kkint32 idx;
  for (idx = 0; (idx < _data.QueueSize ()) && (!_cancelFlag); idx++)
  {
    example = _data.IdxToPtr (idx);
    for (x = 0; x < _selFeatures.NumOfFeatures (); x++)
    {
      kkint32 featureNum = _selFeatures[x];
      if ((attrTable[featureNum]->Type () == AttributeType::Nominal) ||
           (attrTable[featureNum]->Type () == AttributeType::Symbolic)
          )
      {
        if (example->FeatureData (featureNum) == -1.0)
        {
          // Missing Data
          _out << "?";
        }
        else
        {
          _out << C45AdjName (attrTable[featureNum]->GetNominalValue ((kkint32)(example->
      FeatureData (featureNum))));
        }
      }
      else
      {
        _out << example->FeatureData (featureNum);
      }
      _out << ",";
    }
    _out << example->ExampleFileName () << ",";
    _out << example->ClassName ();
    _out << endl;
    _numExamplesWritten++;
  }
  _out.precision (origPrecision);
  if (!_cancelFlag)
    _successful = true;
  delete attrTable;
  return;
} /* SaveFile */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIOC45.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIOC45.cpp