KKB::TokenBuffer Class Reference
#include <TokenBuffer.h>
Public Member Functions
TokenBuffer ()
virtual ~TokenBuffer ()
virtual bool EndOfFile ()=0
virtual char GetNextChar ()=0
virtual char PeekNextChar ()=0
virtual void UnGetNextChar ()=0
virtual bool Valid ()=0
Detailed Description
Definition at line 12 of file TokenBuffer.h.
Constructor & Destructor Documentation
TokenBuffer::TokenBuffer ()
Definition at line 22 of file TokenBuffer.cpp.
Referenced by KKB::TokenBufferStream::TokenBufferStream().
{
}
TokenBuffer::~TokenBuffer () [virtual]
Definition at line 28 of file TokenBuffer.cpp.
{
}
Member Function Documentation
virtual bool KKB::TokenBuffer::EndOfFile () [pure virtual]
Implemented in KKB::TokenBufferStream, and KKB::TokenBufferStr.
virtual char KKB::TokenBuffer::GetNextChar () [pure virtual]
Implemented in KKB::TokenBufferStream, and KKB::TokenBufferStr.
virtual char KKB::TokenBuffer::PeekNextChar () [pure virtual]
Implemented in KKB::TokenBufferStream, and KKB::TokenBufferStr.
virtual void KKB::TokenBuffer::UnGetNextChar () [pure virtual]
Implemented in KKB::TokenBufferStream, and KKB::TokenBufferStr.
virtual bool KKB::TokenBuffer::Valid () [pure virtual]
Implemented in KKB::TokenBufferStream, and KKB::TokenBufferStr.
Referenced by KKB::Tokenizer::Tokenizer(), and KKB::XmlTokenizer::XmlTokenizer().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/TokenBuffer.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/TokenBuffer.cpp