SVM289_BFS::SVR_Q Class Reference
Public Member Functions
SVR_Q (const svm_problem &prob, const svm_parameter &param, RunLog &_log)
~SVR_Q ()
Qfloat * get_Q (kkint32 i, kkint32 len) const
Qfloat * get_QD () const
void swap_index (kkint32 i, kkint32 j)
Additional Inherited Members
Detailed Description
Definition at line 2321 of file svm289_BFS.cpp.
Constructor & Destructor Documentation
SVM289_BFS::SVR_Q::SVR_Q (const svm_problem & prob, const svm_parameter & param, RunLog & _log) [inline]
Definition at line 2324 of file svm289_BFS.cpp.
References SVM289_BFS::Cache::Cache(), SVM289_BFS::svm_parameter::cache_size, SVM289_BFS::Kernel::kernel_function, SVM289_BFS::svm_problem::l, and SVR_Q().
Referenced by SVM289_BFS::solve_epsilon_svr(), solve_nu_svr(), and SVR_Q().
          :
    Kernel (prob.x, prob.selFeatures, param, _log)
  {
    l = prob.l;
    cache = new Cache (l, (kkint32)(param.cache_size * (1 << 20)));
    QD = new Qfloat[2 * l];
    sign = new schar [2 * l];
    index = new kkint32 [2 * l];
    for (kkint32 k = 0; k < l; k++)
    {
      sign [k] = 1;
      sign [k + l] = -1;
      index [k] = k;
      index [k + l] = k;
      QD[k] = (Qfloat)(this->*kernel_function)(k, k);
      QD[k + l] = QD[k];
    }
    buffer [0] = new Qfloat [2 * l];
    buffer [1] = new Qfloat [2 * l];
    next_buffer = 0;
  }
SVM289_BFS::SVR_Q::~SVR_Q () [inline]
Definition at line 2390 of file svm289_BFS.cpp.
  {
    delete cache;
    delete[] sign;
    delete[] index;
    delete[] buffer[0];
    delete[] buffer[1];
    delete[] QD;
  }
Member Function Documentation
Qfloat* SVM289_BFS::SVR_Q::get_Q (kkint32 i, kkint32 len) const [inline], [virtual]
Implements SVM289_BFS::Kernel.
Definition at line 2362 of file svm289_BFS.cpp.
References SVM289_BFS::Cache::get_data(), and SVM289_BFS::Kernel::kernel_function.
  {
    Qfloat *data;
    kkint32 j, real_i = index[i];
    if (cache->get_data (real_i, &data, l) < l)
    {
      for (j = 0; j < l; j++)
        data[j] = (Qfloat)(this->*kernel_function)(real_i, j);
    }
    // reorder and copy
    Qfloat *buf = buffer [next_buffer];
    next_buffer = 1 - next_buffer;
    schar si = sign[i];
    for (j = 0; j < len; j++)
      buf[j] = (Qfloat) si * (Qfloat) sign[j] * data[index[j]];
    return buf;
  }
Qfloat* SVM289_BFS::SVR_Q::get_QD () const [inline], [virtual]
Implements SVM289_BFS::Kernel.
Definition at line 2384 of file svm289_BFS.cpp.
  {
    return QD;
  }
void SVM289_BFS::SVR_Q::swap_index (kkint32 i, kkint32 j) [inline], [virtual]
Reimplemented from SVM289_BFS::Kernel.
Definition at line 2353 of file svm289_BFS.cpp.
  {
    SVM289_BFS::swap (sign [i], sign [j]);
    SVM289_BFS::swap (index [i], index [j]);
    SVM289_BFS::swap (QD [i], QD [j]);
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm289_BFS.cpp