KKB::MorphOpStruct Class Reference
#include <MorphOpStruct.h>
Public Member Functions
MorphOpStruct (StructureType _structure, kkuint16 _structureSize)
virtual ~MorphOpStruct ()
void BackgroundCountTH (kkint32 _backgroundCountTH)
void ForegroundCountTH (kkint32 _foregroundCountTH)
kkint32 MemoryConsumedEstimated ()
virtual OperationType Operation () const
virtual RasterPtr PerformOperation (RasterConstPtr _image)=0
Protected Member Functions
bool Fit (kkint32 row, kkint32 col) const
bool FitBackgroundCount (kkint32 row, kkint32 col) const
uchar HitForegroundCount (kkint32 row, kkint32 col) const
Protected Attributes
kkint32 backgroundCountTH
kkint32 foregroundCountTH
StructureType structure
kkuint16 structureSize
Additional Inherited Members
Detailed Description
Definition at line 24 of file MorphOpStruct.h.
Constructor & Destructor Documentation
MorphOpStruct::MorphOpStruct (StructureType _structure, kkuint16 _structureSize)
Definition at line 21 of file MorphOpStruct.cpp.
References backgroundCountTH, foregroundCountTH, KKB::MorphOp::MorphOp(), structure, and structureSize.
Referenced by KKB::MorphOpDilation::MorphOpDilation(), and KKB::MorphOpErosion::MorphOpErosion().
                              :
  MorphOp (),
  backgroundCountTH (0),
  foregroundCountTH (1),
  structure (_structure),
  structureSize (_structureSize)
{
}
MorphOpStruct::~MorphOpStruct () [virtual]
Definition at line 34 of file MorphOpStruct.cpp.
{
}
Member Function Documentation
void KKB::MorphOpStruct::BackgroundCountTH (kkint32 _backgroundCountTH) [inline]
Definition at line 39 of file MorphOpStruct.h.
References backgroundCountTH.
Referenced by KKB::Raster::Erosion().
{backgroundCountTH = _backgroundCountTH;}
bool MorphOpStruct::Fit (kkint32 row, kkint32 col) const [protected]
Definition at line 49 of file MorphOpStruct.cpp.
References KKB::MorphOp::BackgroundPixel(), KKB::MorphOp::srcGreen, KKB::MorphOp::srcHeight, KKB::MorphOp::srcWidth, structure, structureSize, and KKB::MorphOp::stSquare.
Referenced by KKB::MorphOpErosion::PerformOperation().
{
  kkint32 r, c;
  kkint32 rStart = row - structureSize;
  kkint32 rEnd = row + structureSize;
  kkint32 cStart = col - structureSize;
  kkint32 cEnd = col + structureSize;
  if (rStart < 0) rStart = 0;
  if (rEnd >= srcHeight) rEnd = srcHeight - 1;
  if (cStart < 0) cStart = 0;
  if (cEnd >= srcWidth) cEnd = srcWidth - 1;
  if (structure == StructureType::stSquare)
  {
    for (r = rStart; r <= rEnd; r++)
    {
      uchar const* rowPtr = srcGreen[r];
      for (c = cStart; c <= cEnd; c++)
      {
        if (BackgroundPixel (rowPtr[c]))
          return false;
      }
    }
  }
  else
  {
    for (r = rStart; r <= rEnd; r++)
    {
      if (BackgroundPixel (srcGreen[r][col]))
        return false;
    }
    for (c = cStart; c <= cEnd; c++)
    {
      if (BackgroundPixel (srcGreen[row][c]))
        return false;
    }
  }
  return true;
} /* Fit */
bool MorphOpStruct::FitBackgroundCount (kkint32 row, kkint32 col) const [protected]
Definition at line 99 of file MorphOpStruct.cpp.
References backgroundCountTH, KKB::MorphOp::BackgroundPixel(), KKB::MorphOp::srcGreen, KKB::MorphOp::srcHeight, KKB::MorphOp::srcWidth, structure, structureSize, and KKB::MorphOp::stSquare.
Referenced by KKB::MorphOpErosion::PerformOperation().
{
  kkint32 r, c;
  kkint32 rStart = row - structureSize;
  kkint32 rEnd = row + structureSize;
  kkint32 cStart = col - structureSize;
  kkint32 cEnd = col + structureSize;
  if (rStart < 0) rStart = 0;
  if (rEnd >= srcHeight) rEnd = srcHeight - 1;
  if (cStart < 0) cStart = 0;
  if (cEnd >= srcWidth) cEnd = srcWidth - 1;
  int backgroundCount = 0;
  if (structure == StructureType::stSquare)
  {
    for (r = rStart; r <= rEnd; r++)
    {
      uchar const* rowPtr = srcGreen[r];
      for (c = cStart; c <= cEnd; c++)
      {
        if (BackgroundPixel (rowPtr[c]))
          ++backgroundCount;
      }
    }
  }
  else
  {
    for (r = rStart; r <= rEnd; r++)
    {
      if (BackgroundPixel (srcGreen[r][col]))
        ++backgroundCount;
    }
    for (c = cStart; c <= cEnd; c++)
    {
      if (BackgroundPixel (srcGreen[row][c]))
        ++backgroundCount;
    }
  }
  return backgroundCount < backgroundCountTH;
} /* FitBackgroundCount */
void KKB::MorphOpStruct::ForegroundCountTH (kkint32 _foregroundCountTH) [inline]
Definition at line 40 of file MorphOpStruct.h.
References foregroundCountTH.
Referenced by KKB::Raster::Dilation().
{foregroundCountTH = _foregroundCountTH;}
uchar MorphOpStruct::HitForegroundCount (kkint32 row, kkint32 col) const [protected]
Definition at line 152 of file MorphOpStruct.cpp.
References foregroundCountTH, KKB::MorphOp::ForegroundPixel(), KKB::MorphOp::srcGreen, KKB::MorphOp::srcHeight, KKB::MorphOp::srcWidth, structure, structureSize, and KKB::MorphOp::stSquare.
Referenced by KKB::MorphOpDilation::PerformOperation().
{
  kkint32 r, c;
  kkint32 rStart = row - structureSize;
  kkint32 rEnd = row + structureSize;
  kkint32 cStart = col - structureSize;
  kkint32 cEnd = col + structureSize;
  if (rStart < 0) rStart = 0;
  if (rEnd >= srcHeight) rEnd = srcHeight - 1;
  if (cStart < 0) cStart = 0;
  if (cEnd >= srcWidth) cEnd = srcWidth - 1;
  kkint32 pixelValueTotal = 0;
  kkint32 neighborCount = 0;
  if (structure == StructureType::stSquare)
  {
    for (r = rStart; r <= rEnd; r++)
    {
      uchar const* rowPtr = srcGreen[r];
      for (c = cStart; c <= cEnd; c++)
      {
        if (ForegroundPixel (rowPtr[c]))
        {
          ++neighborCount;
          pixelValueTotal += rowPtr[c];
        }
      }
    }
  }
  else
  {
    for (r = rStart; r <= rEnd; r++)
    {
      if (ForegroundPixel (srcGreen[r][col]))
      {
        ++neighborCount;
        pixelValueTotal += srcGreen[r][col];
      }
    }
    for (c = cStart; c <= cEnd; c++)
    {
      if (ForegroundPixel (srcGreen[r][c]))
      {
        ++neighborCount;
        pixelValueTotal += srcGreen[r][col];
      }
    }
  }
  if (neighborCount < foregroundCountTH)
    return (uchar)0;
  else
    return (uchar)(0.5f + (float)pixelValueTotal / (float)neighborCount);
} /* HitForegroundCount */
kkint32 MorphOpStruct::MemoryConsumedEstimated ()
Definition at line 40 of file MorphOpStruct.cpp.
{
  return sizeof (*this);
}
virtual OperationType KKB::MorphOpStruct::Operation () const [inline], [virtual]
Implements KKB::MorphOp.
Reimplemented in KKB::MorphOpDilation, and KKB::MorphOpErosion.
Definition at line 33 of file MorphOpStruct.h.
References KKB::MorphOp::Erosion.
{return OperationType::Erosion;}
virtual RasterPtr KKB::MorphOpStruct::PerformOperation (RasterConstPtr _image) [pure virtual]
Implemented in KKB::MorphOpDilation, and KKB::MorphOpErosion.
Member Data Documentation
kkint32 KKB::MorphOpStruct::backgroundCountTH [protected]
If greater than zero; then pixel must have at least that many neighbors to be considered a fit.
Definition at line 57 of file MorphOpStruct.h.
Referenced by BackgroundCountTH(), FitBackgroundCount(), MorphOpStruct(), and KKB::MorphOpErosion::PerformOperation().
kkint32 KKB::MorphOpStruct::foregroundCountTH [protected]
Definition at line 58 of file MorphOpStruct.h.
Referenced by ForegroundCountTH(), HitForegroundCount(), and MorphOpStruct().
StructureType KKB::MorphOpStruct::structure [protected]
Definition at line 56 of file MorphOpStruct.h.
Referenced by Fit(), FitBackgroundCount(), HitForegroundCount(), and MorphOpStruct().
kkuint16 KKB::MorphOpStruct::structureSize [protected]
Definition at line 59 of file MorphOpStruct.h.
Referenced by Fit(), FitBackgroundCount(), HitForegroundCount(), and MorphOpStruct().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpStruct.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpStruct.cpp