KKMLL::MLClassList Class Reference
Maintains a list of MLClass instances.
#include <MLClass.h>
Classes
class MLClassNameComparison
Public Member Functions
MLClassList ()
MLClassList (const MLClassList &_mlClasses)
Copy constructor; will copy list but not own the contents.
MLClassList (const KKStr &fileName, bool &successfull)
Construct a MLClassList object from the contents of a file.
virtual ~MLClassList ()
virtual void AddMLClass (MLClassPtr _mlClass)
virtual void Clear ()
Clears the contents of this list and updates nameIndex structure.
KKStr ExtractHTMLTableHeader () const
Will generate a HTML formatted string that can be used in a HTML table.
MLClassListPtr ExtractListOfClassesForAGivenHierarchialLevel (kkint32 level)
MLClassListPtr ExtractMandatoryClasses () const
MLClassListPtr ExtractSummarizeClasses () const
void ExtractThreeTitleLines (KKStr &titleLine1, KKStr &titleLine2, KKStr &titleLine3) const
Using the class names create three title lines where we split names by `_` characters between the three lines.
void ExtractThreeTitleLines (KKStr &titleLine1, KKStr &titleLine2, KKStr &titleLine3, kkint32 fieldWidth) const
void ExtractTwoTitleLines (KKStr &titleLine1, KKStr &titleLine2) const
Using the class names create two title lines where we split names by `_` characters between the two lines.
virtual MLClassPtr GetMLClassPtr (const KKStr &_name)
return pointer to instance with '_name'; if none exists, create one and add to list.
MLClassPtr GetNoiseClass () const
MLClassPtr GetUnKnownClass ()
Return a pointer to the MLClass object that represents the unknown Class in the list.
void Load (const KKStr &_fileName, bool &_successfull)
virtual MLClassPtr LookUpByClassId (kkint32 _classId) const
virtual MLClassPtr LookUpByName (const KKStr &_name) const
Returns a pointer of MLClass object with name (_name); if none in list will then return NULL.
kkint32 MemoryConsumedEstimated () const
KKB::kkuint16 NumHierarchialLevels () const
bool operator!= (const MLClassList &right) const
MLClassList & operator+= (const MLClassList &right)
MLClassList operator- (const MLClassList &right) const
MLClassList & operator-= (const MLClassList &right)
MLClassList & operator= (const MLClassList &right)
bool operator== (const MLClassList &right) const
virtual MLClassPtr PopFromBack ()
virtual MLClassPtr PopFromFront ()
virtual void PushOnBack (MLClassPtr mlClass)
virtual void PushOnFront (MLClassPtr mlClass)
void Save (KKStr _fileName, bool &_successfull)
void SortByName ()
KKStr ToCommaDelimitedQuotedStr () const
KKStr ToCommaDelimitedStr () const
KKStr ToString () const
KKStr ToTabDelimitedStr () const
void WriteXML (const KKStr &varName, std::ostream &o) const
Static Public Member Functions
static MLClassListPtr BuildListFromDelimtedStr (const KKStr &s, char delimiter)
static MLClassListPtr MergeClassList (const MLClassList &list1, const MLClassList &list2)
Friends
class MLClass
Additional Inherited Members
Detailed Description
Maintains a list of MLClass instances.
There will be only one instance of each MLClass by name and these instances will be owned by MLClass::existingMLClasses.
Definition at line 233 of file MLClass.h.
Constructor & Destructor Documentation
KKMLL::MLClassList::MLClassList ()
Referenced by BuildListFromDelimtedStr(), KKMLL::MLClass::BuildListOfDecendents(), KKMLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), KKMLL::TrainingConfiguration2::ExtractClassList(), KKMLL::TrainingConfiguration2::ExtractFullHierachyOfClasses(), KKMLL::FeatureVectorList::ExtractListOfClasses(), KKMLL::TrainingConfiguration2::ExtractListOfClassesForAGivenHierarchialLevel(), ExtractListOfClassesForAGivenHierarchialLevel(), ExtractMandatoryClasses(), ExtractSummarizeClasses(), KKMLL::TrainingProcess2::ExtractTrainingClassFeatures(), KKMLL::MLClass::GlobalClassList(), KKMLL::TrainingConfiguration2::Load(), KKMLL::Orderings::Orderings(), KKMLL::TrainingConfiguration2::TrainingConfiguration2(), KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList(), and XmlFactoryMacro().
MLClassList::MLClassList (const MLClassList & _mlClasses)
Copy constructor; will copy list but not own the contents.
Definition at line 570 of file MLClass.cpp.
References MLClassList().
Referenced by KKMLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), KKMLL::Classifier2::Classifier2(), KKMLL::TrainingProcess2::ExtractFullHierachyOfClasses(), MergeClassList(), KKMLL::Model::MLClassesNewInstance(), MLClassList(), KKMLL::Model::Model(), and KKMLL::TrainingConfiguration2::TrainingConfiguration2().
                                                       :
  KKQueue<MLClass> (false)
{
  MLClass::AddImageClassList (this);
  kkuint32 numOfClasses = _mlClasses.QueueSize ();
  kkuint32 x;
  
  for (x = 0; x < numOfClasses; x++)
  {
    AddMLClass (_mlClasses.IdxToPtr (x));
  }
}
MLClassList::MLClassList (const KKStr & fileName, bool & successfull)
Construct a MLClassList object from the contents of a file.
Definition at line 588 of file MLClass.cpp.
References AddMLClass(), GetMLClassPtr(), Load(), and MLClassList().
Referenced by MLClassList().
                          :
     KKQueue<MLClass> (false),
     undefinedLoaded (false)
{
  MLClass::AddImageClassList (this);
  Load (_fileName, _successfull);
  if (!undefinedLoaded)
  {
    // We have to make sure that there is a UnDefined MLClass.
    AddMLClass (MLClassList::GetMLClassPtr ("UNKNOWN"));
    undefinedLoaded = true;
  }
}
MLClassList::~MLClassList () [virtual]
Definition at line 609 of file MLClass.cpp.
{
  MLClass::DeleteImageClassList (this);
}
Member Function Documentation
void MLClassList::AddMLClass (MLClassPtr _mlClass) [virtual]
Definition at line 756 of file MLClass.cpp.
References KKB::KKStr::Empty(), and KKMLL::MLClass::Name().
Referenced by KKMLL::MLClass::CreateNewMLClass(), GetMLClassPtr(), Load(), and MLClassList().
{
  if (_mlClass->Name ().Empty ())
  {
    cerr << "MLClassList::AddMLClass Class Name Empty" << endl;
  }
  KKQueue<MLClass>::PushOnBack (_mlClass);
  AddMLClassToNameIndex (_mlClass);
}
MLClassListPtr MLClassList::BuildListFromDelimtedStr (const KKStr & s, char delimiter) [static]
Definition at line 1268 of file MLClass.cpp.
References MLClassList(), and KKB::KKStr::Split().
{
  VectorKKStr names = s.Split (',');
  MLClassListPtr classList = new MLClassList ();
  VectorKKStr::iterator idx;
  for (idx = names.begin (); idx != names.end (); idx++)
    MLClassPtr c = classList->GetMLClassPtr (*idx);
  return classList;
} /* BuildListFromCommaDelimtedStr */
void MLClassList::Clear () [virtual]
Clears the contents of this list and updates nameIndex structure.
Definition at line 623 of file MLClass.cpp.
Referenced by operator=().
{
  clear ();
  nameIndex.clear ();
}
KKStr MLClassList::ExtractHTMLTableHeader () const
Will generate a HTML formatted string that can be used in a HTML table.
Using the class name's create one header line for a HTML table. The underscore character (`_`) will be used to separate levels
Definition at line 1195 of file MLClass.cpp.
References KKB::KKStr::Concat(), KKMLL::MLClass::Name(), and KKB::KKStr::Split().
{
  KKStr header (QueueSize () * 50);
  kkuint16 x;
  MLClassList::const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    MLClassPtr ic = *idx;
    VectorKKStr parts = ic->Name ().Split ('_');
    header << "<th>";
    for (x = 0; x < parts.size (); x++)
    {
      if (x > 0)
        header << "<br />";
      header << parts[x];
    }
    header << "</th>";
  }
  return header;
} /* ExtractHTMLTableHeader */
MLClassListPtr MLClassList::ExtractListOfClassesForAGivenHierarchialLevel (kkint32 level)
Definition at line 1223 of file MLClass.cpp.
References KKMLL::MLClass::MLClassForGivenHierarchialLevel(), MLClassList(), and SortByName().
{
  MLClassListPtr newList = new MLClassList ();
  MLClassList::iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    MLClassPtr c = *idx;
    MLClassPtr classForLevel = c->MLClassForGivenHierarchialLevel
      (level);
    if (newList->PtrToIdx (classForLevel) < 0)
      newList->AddMLClass (classForLevel);
  }
  newList->SortByName ();
  return newList;
} /* ExtractListOfClassesForAGivenHierarchialLevel */
MLClassListPtr MLClassList::ExtractMandatoryClasses () const
Definition at line 1018 of file MLClass.cpp.
References MLClassList().
{
  MLClassListPtr result = new MLClassList ();
  const_iterator idx;
  for (idx = begin(); idx != end (); ++idx)
  {
    if ((*idx)->Mandatory ())
      result->PushOnBack (*idx);
  }
  return result;
} /* ExtractMandatoryClasses */
MLClassListPtr MLClassList::ExtractSummarizeClasses () const
Definition at line 1001 of file MLClass.cpp.
References MLClassList().
{
  MLClassListPtr result = new MLClassList ();
  const_iterator idx;
  for (idx = begin(); idx != end (); ++idx)
  {
    if ((*idx)->Summarize ())
      result->PushOnBack (*idx);
  }
  return result;
} /* ExtractSummarizeClasses */
void MLClassList::ExtractThreeTitleLines (KKStr & titleLine1, KKStr & titleLine2, KKStr & titleLine3) const
Using the class names create three title lines where we split names by `_` characters between the three lines.
Definition at line 1068 of file MLClass.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::KKStr::ExtractToken(), KKB::KKStr::operator=(), KKB::KKStr::TrimLeft(), and KKB::KKStr::TrimRight().
Referenced by KKMLL::ClassificationBiasMatrix::PrintAdjustedResults(), KKMLL::ClassificationBiasMatrix::PrintBiasMatrix(), and KKMLL::SizeDistribution::PrintByClassCollumns().
{
  titleLine1 = "";
  titleLine2 = "";
  titleLine3 = "";
  kkint32 x;
  for (x = 0; x < QueueSize (); x++)
  {
    if (x > 0)
    {
      titleLine1 << "\t";
      titleLine2 << "\t";
      titleLine3 << "\t";
    }
    KKStr part1, part2, part3;
    part1 = part2 = part3 = "";
    kkint32 numOfParts = 0;
    KKStr className = IdxToPtr (x)->Name ();
    className.TrimLeft ();
    className.TrimRight ();
    
    numOfParts = 1;
    part1 = className.ExtractToken ("_");
    if (!className.Empty ())
    {
      numOfParts = 2;
      part2 = className.ExtractToken ("_");
      if (!className.Empty ())
      {
        numOfParts = 3;
        part3 = className;
      }
    }
    switch (numOfParts)
    {
      case 1: titleLine3 << part1;
              break;
      case 2: titleLine2 << part1;
              titleLine3 << part2;
              break;
      case 3: titleLine1 << part1;
              titleLine2 << part2;
              titleLine3 << part3;
              break;
    }
  }
} /* ExtractThreeTitleLines */
void MLClassList::ExtractThreeTitleLines (KKStr & titleLine1, KKStr & titleLine2, KKStr & titleLine3, kkint32 fieldWidth) const
Definition at line 1130 of file MLClass.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::KKStr::ExtractToken(), KKB::KKStr::LeftPad(), KKB::KKStr::operator=(), KKB::KKStr::RightPad(), KKB::KKStr::TrimLeft(), and KKB::KKStr::TrimRight().
{
  titleLine1 = "";
  titleLine2 = "";
  titleLine3 = "";
  KKStr blankField;
  blankField.RightPad (fieldWidth);
  kkint32 x;
  for (x = 0; x < QueueSize (); x++)
  {
    KKStr part1, part2, part3;
    part1 = part2 = part3 = "";
    kkint32 numOfParts = 0;
    KKStr className = IdxToPtr (x)->Name ();
    className.TrimLeft ();
    className.TrimRight ();
    
    numOfParts = 1;
    part1 = className.ExtractToken ("_");
    if (!className.Empty ())
    {
      numOfParts = 2;
      part2 = className.ExtractToken ("_");
      if (!className.Empty ())
      {
        numOfParts = 3;
        part3 = className;
      }
    }
    part1.LeftPad (fieldWidth);
    part2.LeftPad (fieldWidth);
    part3.LeftPad (fieldWidth);
    switch (numOfParts)
    {
      case 1: titleLine1 << blankField;
              titleLine2 << blankField;
              titleLine3 << part1;
              break;
      case 2: titleLine1 << blankField;
              titleLine2 << part1;
              titleLine3 << part2;
              break;
      case 3: titleLine1 << part1;
              titleLine2 << part2;
              titleLine3 << part3;
              break;
    }
  }
} /* ExtractThreeTitleLines */
void MLClassList::ExtractTwoTitleLines (KKStr & titleLine1, KKStr & titleLine2) const
Using the class names create two title lines where we split names by `_` characters between the two lines.
Definition at line 1035 of file MLClass.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::LocateCharacter(), KKB::KKStr::operator=(), and KKB::KKStr::SubStrPart().
{
  titleLine1 = "";
  titleLine2 = "";
  kkint32 x;
  for (x = 0; x < QueueSize (); x++)
  {
    if (x > 0)
    {
      titleLine1 << "\t";
      titleLine2 << "\t";
    }
    KKStr className = IdxToPtr (x)->Name ();
    kkint32 y = className.LocateCharacter ('_');
    if (y < 0)
    {
      titleLine2 << className;
    }
    else
    {
      titleLine1 << className.SubStrPart (0, y - 1);
      titleLine2 << className.SubStrPart (y + 1);
    }
  }
} /* ExtractTwoTitleLines */
MLClassPtr MLClassList::GetMLClassPtr (const KKStr & _name) [virtual]
return pointer to instance with '_name'; if none exists, create one and add to list.
Definition at line 861 of file MLClass.cpp.
References AddMLClass(), KKMLL::MLClass::CreateNewMLClass(), and LookUpByName().
Referenced by KKMLL::FeatureFileIODstWeb::GetFileDesc(), KKMLL::FeatureFileIOColumn::GetFileDesc(), KKMLL::FeatureFileIOC45::GetFileDesc(), KKMLL::FeatureFileIOUCI::GetFileDesc(), KKMLL::FeatureFileIOSparse::GetFileDesc(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOColumn::LoadFile(), KKMLL::FeatureFileIOUCI::LoadFile(), KKMLL::FeatureFileIO::LoadInSubDirectoryTree(), MLClassList(), and KKMLL::TrainingClass::TrainingClass().
{
  MLClassPtr ic = LookUpByName (_name);
  if (ic == NULL)
  {
    ic = MLClass::CreateNewMLClass (_name);
    AddMLClass (ic);
  }
  return ic;
} /* GetMLClassPtr */
MLClassPtr MLClassList::GetNoiseClass () const
Definition at line 875 of file MLClass.cpp.
Referenced by KKMLL::Classifier2::Classifier2().
{
  MLClassPtr noiseClass = NULL;
  for (auto idx: *this)
  {
    if (idx->UnDefined ())
    {
     noiseClass = idx;
     break;
    }
  }
  return noiseClass;
} /* GetNoiseClass */
MLClassPtr MLClassList::GetUnKnownClass ()
Return a pointer to the MLClass object that represents the unknown Class in the list.
That is the one with the name 'UNKNOWN'. If none is found then one will be created and added to the list.
Definition at line 893 of file MLClass.cpp.
References KKMLL::MLClass::CreateNewMLClass(), LookUpByName(), and PushOnBack().
Referenced by KKMLL::Classifier2::Classifier2(), and KKMLL::FeatureFileIO::LoadInSubDirectoryTree().
{
  MLClassPtr unKnownClass = LookUpByName ("UNKNOWN");
  if (!unKnownClass)
  {
    unKnownClass = MLClass::CreateNewMLClass ("UNKNOWN");
    PushOnBack (unKnownClass);
  }
  return unKnownClass;
} /* GetUnKnownClass */
void MLClassList::Load (const KKStr & _fileName, bool & _successfull)
Definition at line 681 of file MLClass.cpp.
References AddMLClass(), KKMLL::MLClass::CreateNewMLClass(), KKB::osFOPEN(), KKB::osReadRestOfLine(), KKB::KKStr::Str(), KKB::KKStr::TrimRight(), and KKMLL::MLClass::UnDefined().
Referenced by MLClassList().
{
  kkint32 lineCount = 0;
  FILE* inputFile = osFOPEN (_fileName.Str (), "r");
  if (!inputFile)
  {
    cerr << "MLClassList::ReadInData *** ERROR ***" << endl
         << " Input File[" << _fileName << "] not Valid." << endl;
    _successfull = false;
    return;
  }
  bool eof = false;
  KKStrPtr dataRow = KKB::osReadRestOfLine (inputFile, eof);
  while (!eof)
  {
    dataRow->TrimRight ();
    MLClassPtr oneRow = MLClass::CreateNewMLClass (*dataRow);
    AddMLClass (oneRow);
    if (oneRow->UnDefined ())
      undefinedLoaded = true;
    lineCount++;
    delete dataRow;
    dataRow = KKB::osReadRestOfLine (inputFile, eof);
  }
  delete dataRow;
  dataRow = NULL;
  fclose (inputFile);
  _successfull = true;
} /* ReadInData */
MLClassPtr MLClassList::LookUpByClassId (kkint32 _classId) const [virtual]
Definition at line 843 of file MLClass.cpp.
References KKMLL::MLClass::ClassId().
Referenced by KKMLL::MLClass::GetByClassId().
{
  MLClassList::const_iterator idx;
  MLClassPtr mlClass;
  for (idx = begin (); idx != end (); idx++)
  {
    mlClass = *idx;
    if (mlClass->ClassId () == _classId)
      return mlClass;
  }
  return NULL;
} /* LookUpClassId */
MLClassPtr MLClassList::LookUpByName (const KKStr & _name) const [virtual]
Returns a pointer of MLClass object with name (_name); if none in list will then return NULL.
Parameters
in _name Name of MLClass to search for.
Returns
Pointer to MLClass or NULL if not Found.
Definition at line 830 of file MLClass.cpp.
Referenced by KKMLL::MLClass::CreateNewMLClass(), GetMLClassPtr(), GetUnKnownClass(), operator==(), and KKMLL::MLClass::ResetAllParentsToAllClasses().
{
  NameIndex::const_iterator idx;
  idx = nameIndex.find (_name.ToUpper ());
  if (idx == nameIndex.end ())
    return NULL;
  else
    return idx->second;
} /* LookUpByName */
kkint32 MLClassList::MemoryConsumedEstimated () const
Definition at line 616 of file MLClass.cpp.
Referenced by KKMLL::Classifier2::MemoryConsumedEstimated(), KKMLL::Model::MemoryConsumedEstimated(), and KKMLL::TrainingProcess2::MemoryConsumedEstimated().
{
  return sizeof (MLClassList) + sizeof (MLClassPtr) * size ();
}
MLClassListPtr MLClassList::MergeClassList (const MLClassList & list1, const MLClassList & list2) [static]
Definition at line 1245 of file MLClass.cpp.
References MLClassList().
{
  MLClassListPtr result = new MLClassList (list1);
  MLClassList::const_iterator idx;
  for (idx = list2.begin (); idx != list2.end (); idx++)
  {
    MLClassPtr ic = *idx;
    if (result->PtrToIdx (ic) < 0)
    {
      // This entry (*idx) from list2 was not in list 1
      result->AddMLClass (ic);
    }
  }
  return result;
} /* MergeClassList */
kkuint16 MLClassList::NumHierarchialLevels () const
Definition at line 668 of file MLClass.cpp.
{
  kkuint16 numHierarchialLevels = 0;
  MLClassList::const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
    numHierarchialLevels = Max (numHierarchialLevels, (*idx)->NumHierarchialLevels ());
  return numHierarchialLevels;
} /* NumHierarchialLevels*/
bool MLClassList::operator!= (const MLClassList & right) const
Definition at line 1332 of file MLClass.cpp.
References operator==().
Referenced by KKMLL::TrainingProcess2::ReadXML().
{
  return (!operator== (right));
} /* operator== */
MLClassList & MLClassList::operator+= (const MLClassList & right)
add all classes that are in the 'right' parameter
Definition at line 1362 of file MLClass.cpp.
{
  if (this == &right)
    return *this;
  MLClassList::const_iterator idx;
  for (idx = right.begin (); idx != right.end (); idx++)
  {
    MLClassPtr ic = *idx;
    if (PtrToIdx (ic) < 0)
      PushOnBack (ic);
  }
  return *this;
}
MLClassList MLClassList::operator- (const MLClassList & right) const
remove all classes that in the 'right' parameter
Definition at line 1400 of file MLClass.cpp.
{
  MLClassList result;
  MLClassList::const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    MLClassPtr ic = *idx;
    if (right.PtrToIdx (ic) < 0)
       result.PushOnBack (ic);
  }
  return result;
} /* operator- */
MLClassList & MLClassList::operator-= (const MLClassList & right)
remove all classes that in the 'right' parameter
Definition at line 1340 of file MLClass.cpp.
{
  if (&right == this)
  {
    while (QueueSize () > 0)
      PopFromBack ();
    return *this;
  }
  MLClassList::const_iterator idx;
  for (idx = right.begin (); idx != right.end (); idx++)
  {
    MLClassPtr ic = *idx;
    DeleteEntry (ic); // if 'ic' exists in our list it will be deleted.
  }
  return *this;
} /* operator=- */
MLClassList & MLClassList::operator= (const MLClassList & right)
Definition at line 1381 of file MLClass.cpp.
References Clear(), and PushOnBack().
{
  if (&right == this)
    return *this;
  Clear ();
  MLClassList::const_iterator idx;
  for (idx = right.begin (); idx != right.end (); idx++)
  {
    MLClassPtr ic = *idx;
    PushOnBack (ic);
  }
  return *this;
} /* operator= */
bool MLClassList::operator== (const MLClassList & right) const
Definition at line 1313 of file MLClass.cpp.
References LookUpByName(), and KKMLL::MLClass::Name().
Referenced by operator!=().
{
  if (QueueSize () != right.QueueSize ())
    return false;
  for (kkint32 i = 0; i < QueueSize (); i++)
  {
    MLClassPtr mlClass = IdxToPtr (i);
    if (right.LookUpByName (mlClass->Name ()) == NULL)
      return false;
  }
  return true;
} /* operator== */
MLClassPtr MLClassList::PopFromBack () [virtual]
Removes the last element in the container and returns its pointer. If the container is empty will return NULL.
Reimplemented from KKB::KKQueue< MLClass >.
Definition at line 768 of file MLClass.cpp.
{
  NameIndex::iterator idx;
  MLClassPtr ic = KKQueue<MLClass>::PopFromBack ();
  if (!ic)
    return NULL;
  idx = nameIndex.find (ic->UpperName ());
  if (idx != nameIndex.end ())
    nameIndex.erase (idx);
  return ic;
} /* PopFromBack*/
MLClassPtr MLClassList::PopFromFront () [virtual]
Removes the first element in the container and returns its pointer. If the container is empty will return NULL.
Reimplemented from KKB::KKQueue< MLClass >.
Definition at line 783 of file MLClass.cpp.
{
  NameIndex::iterator idx;
  MLClassPtr ic = KKQueue<MLClass>::PopFromFront ();
  if (!ic)
    return NULL;
  idx = nameIndex.find (ic->UpperName ());
  if (idx != nameIndex.end ())
    nameIndex.erase (idx);
  return ic;
} /* PopFromFront*/
void MLClassList::PushOnBack (MLClassPtr mlClass) [virtual]
Definition at line 798 of file MLClass.cpp.
References KKB::KKStr::Empty(), and KKMLL::MLClass::Name().
Referenced by KKMLL::MLClass::BuildListOfDecendents(), GetUnKnownClass(), operator=(), and KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList().
  {
  if (_mlClass->Name ().Empty ())
    {
    cerr << "MLClassList::PushOnBack Class Name Empty" << endl;
    }
  KKQueue<MLClass>::PushOnBack (_mlClass);
  AddMLClassToNameIndex (_mlClass);
  }
void MLClassList::PushOnFront (MLClassPtr mlClass) [virtual]
Definition at line 811 of file MLClass.cpp.
References KKB::KKStr::Empty(), and KKMLL::MLClass::Name().
{
  if (_mlClass->Name ().Empty ())
  {
    cerr << "MLClassList::PushOnFront Class Name Empty" << endl;
  }
  KKQueue<MLClass>::PushOnBack (_mlClass);
  AddMLClassToNameIndex (_mlClass);
}
void MLClassList::Save (KKStr _fileName, bool & _successfull)
Definition at line 723 of file MLClass.cpp.
{
  ofstream outFile (_fileName.Str ());
  kkint32 idx;
  kkint32 qSize = QueueSize ();
  MLClassPtr mlClass = NULL;
  for (idx = 0; idx < qSize; idx++)
  {
    mlClass = IdxToPtr (idx);
    outFile << mlClass->ToString ().Str () << endl;
  }
  _successfull = true;
  return;
} /* WriteOutData */
void MLClassList::SortByName ()
Definition at line 926 of file MLClass.cpp.
References KKMLL::MLClassList::MLClassNameComparison::MLClassNameComparison().
Referenced by KKMLL::TrainingConfiguration2::CreateFromFeatureVectorList(), KKMLL::FeatureVectorList::CreateListForAGivenLevel(), KKMLL::TrainingConfiguration2::ExtractClassList(), KKMLL::TrainingConfiguration2::ExtractFullHierachyOfClasses(), ExtractListOfClassesForAGivenHierarchialLevel(), KKMLL::FeatureVectorList::ExtractRandomSampling(), KKMLL::FeatureFileIORoberts::SaveFile(), KKMLL::ModelOldSVM::TrainModel(), and KKMLL::Model::TrainModel().
{
  MLClassNameComparison* c = new MLClassNameComparison ();
  sort (begin (), end (), *c);
  delete c;
} /* SortByName */
KKStr MLClassList::ToCommaDelimitedQuotedStr () const
Definition at line 985 of file MLClass.cpp.
References KKB::KKStr::Concat().
Referenced by KKMLL::XmlElementMLClassNameList::WriteXML().
{
  KKStr s (10 * QueueSize ());
  for (kkint32 i = 0; i < QueueSize (); i++)
  {
    if (i > 0) s << ",";
    s << IdxToPtr (i)->Name ().QuotedStr ();
  }
  return s;
} /* ToCommaDelimitedQuotedStr */
KKStr MLClassList::ToCommaDelimitedStr () const
Definition at line 970 of file MLClass.cpp.
References KKB::KKStr::Concat().
{
  KKStr s (10 * QueueSize ());
  for (kkint32 i = 0; i < QueueSize (); i++)
  {
    if (i > 0) s << ",";
    s << IdxToPtr (i)->Name ();
  }
  return s;
} /* ToCommaDelimitedStr */
KKStr MLClassList::ToString () const
Definition at line 937 of file MLClass.cpp.
References KKB::KKStr::Concat().
Referenced by KKMLL::operator<<().
{
  KKStr s (10 * QueueSize ());
  for (kkint32 i = 0; i < QueueSize (); i++)
  {
    if (i > 0)
      s << "\t";
    s << IdxToPtr (i)->Name ();
  }
  return s;
} /* ToString */
KKStr MLClassList::ToTabDelimitedStr () const
Definition at line 955 of file MLClass.cpp.
References KKB::KKStr::Concat().
{
  KKStr s (10 * QueueSize ());
  for (kkint32 i = 0; i < QueueSize (); i++)
  {
    if (i > 0) s << "\t";
    s << IdxToPtr (i)->Name ();
  }
  return s;
} /* ToTabDelimitedStr */
void MLClassList::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 1286 of file MLClass.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKMLL::MLClass::WriteXML(), KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("MLClassList", XmlTag::TagTypes::tagStart);
  if (!varName.Empty())
    startTag.AddAtribute ("VarName", varName);
  startTag.AddAtribute ("Count", (kkint32)size ());
  startTag.WriteXML (o);
  o << endl;
  MLClassList::const_iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    MLClassPtr c = *idx;
    c->WriteXML ("", o);
  }
  XmlTag endtag ("MLClassList", XmlTag::TagTypes::tagEnd);
  endtag.WriteXML (o);
  o << endl;
} /* WriteXML */
Friends And Related Function Documentation
friend class MLClass [friend]
Definition at line 397 of file MLClass.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.cpp