SVM233::SVC_Q Class Reference
Public Member Functions
SVC_Q (const svm_problem &prob, const svm_parameter &param, const schar *y_)
~SVC_Q ()
Qfloat * get_Q (kkint32 i, kkint32 len) const
void swap_index (kkint32 i, kkint32 j) const
Additional Inherited Members
Detailed Description
Definition at line 2650 of file svm.cpp.
Constructor & Destructor Documentation
SVM233::SVC_Q::SVC_Q (const svm_problem & prob, const svm_parameter & param, const schar * y_) [inline]
Definition at line 2653 of file svm.cpp.
References SVM233::Cache::Cache(), SVM233::svm_parameter::cache_size, SVM233::Kernel::Kernel(), SVM233::svm_problem::l, and SVM233::svm_problem::x.
Referenced by SVM233::solve_c_svc(), and SVM233::solve_nu_svc().
    :Kernel (prob.l, prob.x, param)
  {
    clone(y,y_,prob.l);
    cache = new Cache(prob.l,(kkint32)(param.cache_size*(1<<20)));
  }
SVM233::SVC_Q::~SVC_Q () [inline]
Definition at line 2683 of file svm.cpp.
  {
    delete[] y;
    delete cache;
  }
Member Function Documentation
Qfloat* SVM233::SVC_Q::get_Q (kkint32 i, kkint32 len) const [inline], [virtual]
Implements SVM233::Kernel.
Definition at line 2663 of file svm.cpp.
References SVM233::Cache::get_data(), and SVM233::Kernel::kernel_function.
  {
    Qfloat *data;
    kkint32 start;
    if ((start = cache->get_data (i, &data, len)) < len)
    {
      for (kkint32 j = start; j < len; j++)
        data[j] = (Qfloat)(y[i] * y[j] * (this->*kernel_function)(i,j));
      //luo add data[j] = (Qfloat)(w[i]*w[j]*y[i]*y[j]*(this->*kernel_function)(i,j));
    }
    return data;
  }
void SVM233::SVC_Q::swap_index (kkint32 i, kkint32 j) const [inline], [virtual]
Reimplemented from SVM233::Kernel.
Definition at line 2676 of file svm.cpp.
References SVM233::Cache::swap_index(), and SVM233::Kernel::swap_index().
  {
    cache->swap_index(i,j);
    Kernel::swap_index(i,j);
    Swap(y[i],y[j]);
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm.cpp