KKB::KKStrMatrix Class Reference
A two dimensional matrix of Strings.
#include <KKStrMatrix.h>
Public Types
typedef KKStrMatrix * KKStrMatrixPtr
Public Member Functions
KKStrMatrix (kkuint32 _numCols)
KKStrMatrix (kkuint32 _numCols, kkuint32 _numRows)
~KKStrMatrix ()
void AddRow (KKStrListPtr newRowData)
Adds a list of Strings to the end of the Matrix.
void AddRow ()
Adds a row of empty string to the end of the matrix.
kkuint32 NumCols () const
kkuint32 NumRows () const
KKStrList & operator() (kkuint32 row)
KKStr & operator() (kkuint32 row, kkuint32 col)
KKStrList & operator[] (kkuint32 row)
Detailed Description
A two dimensional matrix of Strings.
Definition at line 30 of file KKStrMatrix.h.
Member Typedef Documentation
typedef KKStrMatrix* KKB::KKStrMatrix::KKStrMatrixPtr
Definition at line 33 of file KKStrMatrix.h.
Constructor & Destructor Documentation
KKB::KKStrMatrix::KKStrMatrix (kkuint32 _numCols) [inline]
Definition at line 36 of file KKStrMatrix.h.
References KKStrMatrix().
Referenced by KKStrMatrix().
                                   :
        data (),
        numCols (_numCols)
    {
    }
KKB::KKStrMatrix::KKStrMatrix (kkuint32 _numCols, kkuint32 _numRows) [inline]
Definition at line 43 of file KKStrMatrix.h.
                 :
        numCols (_numCols)
    {
      while ((kkuint32)data.QueueSize () < _numRows)
        AddRow ();
    }
KKB::KKStrMatrix::~KKStrMatrix () [inline]
Definition at line 53 of file KKStrMatrix.h.
    {
    }
Member Function Documentation
void KKStrMatrix::AddRow (KKStrListPtr newRowData)
Adds a list of Strings to the end of the Matrix.
Will add another row to the matrix and populate its contents with the String List being passed in.
Parameters
in newRowData Will take ownership of this String list.
Definition at line 81 of file KKStrMatrix.cpp.
{
  while ((kkuint32)newRowData->QueueSize () < numCols)
    newRowData->PushOnBack (new KKStr ());
  data.PushOnBack (newRowData);
}
void KKStrMatrix::AddRow ()
Adds a row of empty string to the end of the matrix.
Definition at line 90 of file KKStrMatrix.cpp.
References KKB::KKStrList::KKStrList().
{
  KKStrListPtr newRowData = new KKStrList (true);
  while ((kkuint32)newRowData->QueueSize () < numCols)
    newRowData->PushOnBack (new KKStr ());
  data.PushOnBack (newRowData);
}
kkuint32 KKB::KKStrMatrix::NumCols () const [inline]
Definition at line 59 of file KKStrMatrix.h.
{return numCols;}
kkuint32 KKB::KKStrMatrix::NumRows () const [inline]
Definition at line 58 of file KKStrMatrix.h.
{return data.QueueSize ();}
KKStrList & KKStrMatrix::operator() (kkuint32 row)
Definition at line 40 of file KKStrMatrix.cpp.
{
  if (row >= (kkuint32)data.QueueSize ())
  {
    KKStr errMsg = "KKStrMatrix::operator[] Row dimension[" +
      StrFormatInt (row, "0") + "] invalid; Rows Available["
      + StrFormatInt (data.QueueSize (), "0") + "]";
    cerr << errMsg << std::endl;
    throw errMsg;
  }
  return data[row];
}
KKStr & KKStrMatrix::operator() (kkuint32 row, kkuint32 col)
Definition at line 54 of file KKStrMatrix.cpp.
{
  if (row >= (kkuint32)data.QueueSize ())
  {
    KKStr errMsg = "KKStrMatrix::operator[] Row dimension[" +
      StrFormatInt (row, "0") + "] invalid; Rows Available["
                  + StrFormatInt (data.QueueSize (), "0") + "]";
    cerr << errMsg << std::endl;
    throw errMsg;
  }
  KKStrList& rowOfData = data[row];
  if (col >= (kkuint32)rowOfData.QueueSize ())
  {
    KKStr errMsg = "KKStrMatrix::operator[] Col dimension[" +
      StrFormatInt (col, "0") + "] invalid; Rows Available["
                  + StrFormatInt (rowOfData.QueueSize (), "0") + "]";
    cerr << errMsg << std::endl;
    throw errMsg;
  }
  return rowOfData[col];
}
KKStrList & KKStrMatrix::operator[] (kkuint32 row)
Definition at line 25 of file KKStrMatrix.cpp.
{
  if (row >= (kkuint32)data.QueueSize ())
  {
    KKStr errMsg = "KKStrMatrix::operator[] Row dimension[" +
      StrFormatInt (row, "0") + "] invalid; Rows Available["
      + StrFormatInt (data.QueueSize (), "0") + "]";
    cerr << errMsg << std::endl;
    throw errMsg;
  }
  return data[row];
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStrMatrix.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStrMatrix.cpp