KKB::ConvexHull Class Reference
Operator that will create a Convex Hull of a supplied image.
#include <ConvexHull.h>
Public Member Functions
ConvexHull ()
virtual ~ConvexHull ()
kkint32 ConvexArea ()
void Draw (Raster &output)
RasterPtr Filter (const Raster &src)
Returns a image that represents the convex-hull of the 'src' image. param[in] src Source image that convex-hull is to be found for.
RasterPtr Filter (const Raster &src, RasterPtr dest)
virtual OperationType Operation () const
virtual RasterPtr PerformOperation (RasterConstPtr _image)
void Store (const Raster &input)
Build list of the upper and lower points in the image.
Additional Inherited Members
Detailed Description
Operator that will create a Convex Hull of a supplied image.
Definition at line 42 of file ConvexHull.h.
Constructor & Destructor Documentation
ConvexHull::ConvexHull ()
Definition at line 34 of file ConvexHull.cpp.
References KKB::MorphOp::MorphOp().
Referenced by KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector().
                       :
  MorphOp (),
  convexArea (0),
  upperPoints (NULL),
  lowerPoints (NULL),
  upper (NULL),
  lower (NULL)
{
  AllocateMemory ();
}
ConvexHull::~ConvexHull () [virtual]
Definition at line 46 of file ConvexHull.cpp.
{
  CleanUpMemory ();
}
Member Function Documentation
kkint32 ConvexHull::ConvexArea ()
Definition at line 189 of file ConvexHull.cpp.
Referenced by KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector().
{
  return convexArea;
}
void ConvexHull::Draw (Raster & output)
Definition at line 438 of file ConvexHull.cpp.
References KKB::Point::Col(), KKB::Point::Row(), and KKB::Raster::SetPixelValue().
Referenced by Filter().
{
  PointList::iterator it; // (*upper);
  it = upper->begin ();
  PointPtr lastPoint = NULL;
  PointPtr nextPoint = NULL;
  if (it != upper->end ())
  {lastPoint = *it; ++it;}
  if (it != upper->end ())
  {nextPoint = *it; ++it;}
  PointPtr firstPoint = lastPoint;
  if ((!nextPoint) && (!lastPoint))
    return;
  if ((nextPoint != NULL) && (lastPoint == NULL))
  {
    output.SetPixelValue (nextPoint->Row (), nextPoint->Col (), 255);
    return;
  }
    
  while (nextPoint)
  {
    DrawLine (output, *lastPoint, *nextPoint, 255);
    lastPoint = nextPoint;
    if (it == upper->end ())
      nextPoint = NULL;
    else
    {
      nextPoint = *it;
      ++it;
    }
  }
  DrawLine (output, *lastPoint, *firstPoint, 255);
} /* Draw */
RasterPtr ConvexHull::Filter (const Raster & src)
Returns a image that represents the convex-hull of the 'src' image. param[in] src Source image that convex-hull is to be found for.
Returns
A new raster that contains the convex-hull of the 'src' image; the caller will be responsible for deleting.
Definition at line 88 of file ConvexHull.cpp.
References Draw(), KKB::Raster::Height(), KKB::Raster::Raster(), KKB::MorphOp::SetSrcRaster(), Store(), and KKB::Raster::Width().
Referenced by PerformOperation().
{
  SetSrcRaster (&src);
  kkint32 w = src.Width ();
  kkint32 h = src.Height ();
        
  Store (src);
  
  RasterPtr dest = new Raster (h, w);
  if ((upperPoints->QueueSize () == 1) &&
       (lowerPoints->QueueSize () == 1))
  {
    // We must have a Vertical Line
    DrawLine (*dest, (*upperPoints)[0], (*lowerPoints)[0], 255);
    CalcConvexArea (dest);
    return dest;
  }
  else if ((upperPoints->QueueSize () < 1) || (lowerPoints->
      QueueSize () < 1))
  {
    // We have Nothing
    return dest;
  }
  BuildUpperLink ();
  BuildLowerLink ();
  Merge ();
  Draw (*dest);
  
  CalcConvexArea (dest);
  return dest;
} /* Filter */
RasterPtr ConvexHull::Filter (const Raster & src, RasterPtr dest)
Definition at line 128 of file ConvexHull.cpp.
References Draw(), KKB::Raster::Height(), KKB::Raster::ReSize(), KKB::MorphOp::SetSrcRaster(), KKB::MorphOp::srcHeight, KKB::MorphOp::srcWidth, Store(), and KKB::Raster::Width().
Referenced by KKMLL::GrayScaleImagesFVProducer::ComputeFeatureVector().
{
  SetSrcRaster (&src);
  //srcHeight = src.Height ();
  //srcWidth = src.Width ();
// kkint32 w = src.Width ();
// kkint32 h = src.Height ();
  if ((dest->Height () != srcHeight) || (dest->Width () !=
      srcWidth))
    dest->ReSize (srcHeight, srcWidth, false);
        
  Store (src);
  if ((upperPoints->QueueSize () == 1) &&
       (lowerPoints->QueueSize () == 1))
  {
    // We must have a Vertical Line
    DrawLine (*dest, (*upperPoints)[0], (*lowerPoints)[0], 255);
    CalcConvexArea (dest);
    return dest;
  }
  else if ((upperPoints->QueueSize () < 1) || (lowerPoints->
      QueueSize () < 1))
  {
    // We have Nothing
    return dest;
  }
  BuildUpperLink ();
  BuildLowerLink ();
  Merge ();
  Draw (*dest);
  
  CalcConvexArea (dest);
  return dest;
} /* Filter */
virtual OperationType KKB::ConvexHull::Operation () const [inline], [virtual]
Implements KKB::MorphOp.
Definition at line 49 of file ConvexHull.h.
References KKB::MorphOp::ConvexHull.
{return OperationType::ConvexHull;}
RasterPtr ConvexHull::PerformOperation (RasterConstPtr _image) [virtual]
Definition at line 73 of file ConvexHull.cpp.
References Filter(), KKB::MorphOp::SetSrcRaster(), and KKB::MorphOp::srcRaster.
{
  SetSrcRaster (_image);
  AllocateMemory ();
  RasterPtr result = Filter (*srcRaster);
  return result;
} /* PerformOperation */
void ConvexHull::Store (const Raster & input)
Build list of the upper and lower points in the image.
for each column in the image where there is at least one foreground pixel will add one point to 'upperPoints' for the pixel with the smallest row and one point to 'lowerPoints' for the pixel with the largest row.
Parameters
in input Source image that we are to generate a Convex Hull for.
for each column in the image where there is at least one foreground pixel will add one point to 'upperPoints' for the pixel with the smallest row and one point to 'lowerPoints' for the pixel with the largest row.
Parameters
in input Source image that we are to generate a convex-hull for.
Definition at line 738 of file ConvexHull.cpp.
References KKB::MorphOp::ForegroundPixel(), KKB::Raster::Height(), KKB::Point::Point(), KKB::Raster::Rows(), and KKB::Raster::Width().
Referenced by Filter().
{
  kkint32 w = input.Width ();
  kkint32 h = input.Height ();
  uchar** rows = input.Rows ();
        
  for (kkint32 col = 0; col < w; ++col)
  {
    kkint32 row;
    for (row = h - 1; row >= 0; --row)
    {
      if (ForegroundPixel (row, col))
      {
        PointPtr u = new Point (row, col);
        upperPoints->Add (u);
        break;
      }
    }
    if (row >= 0)
    {
      for (row = 0; row < h; row++)
      {
        if (ForegroundPixel (row, col))
        {
          PointPtr l = new Point (row, col);
          lowerPoints->AddFirst (l);
          break;
        }
      }
    }
  }
} /* Store */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/ConvexHull.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/ConvexHull.cpp