KKB::XmlElementBool Class Reference
#include <XmlStream.h>
Public Member Functions
XmlElementBool (XmlTagPtr tag, XmlStream &s, VolConstBool &cancelFlag, RunLog &log)
virtual ~XmlElementBool ()
virtual bool ToBool () const
virtual double ToDouble () const
virtual float ToFloat () const
virtual kkint32 ToInt32 () const
virtual KKStr ToKKStr () const
bool Value () const
Static Public Member Functions
static void WriteXML (const bool b, const KKStr &varName, std::ostream &o)
Additional Inherited Members
Detailed Description
Definition at line 496 of file XmlStream.h.
Constructor & Destructor Documentation
XmlElementBool::XmlElementBool (XmlTagPtr tag, XmlStream & s, VolConstBool & cancelFlag, RunLog & log)
Definition at line 998 of file XmlStream.cpp.
References KKB::XmlTag::AttributeValueByName(), KKB::XmlContent::Content(), KKB::XmlStream::GetNextToken(), KKB::KKStr::ToBool(), KKB::XmlToken::tokContent, KKB::XmlToken::TokenType(), and KKB::XmlElement::XmlElement().
                                :
    XmlElement (tag, s, log),
    value (false)
{
  KKStrConstPtr valueStr = tag->AttributeValueByName ("Value");
  if (valueStr)
    value = valueStr->ToBool ();
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t != NULL)
  {
    if (t->TokenType () == XmlToken::TokenTypes::tokContent)
    {
      XmlContentPtr c = dynamic_cast<XmlContentPtr> (t);
      value = c->Content ()->ToBool ();
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
}
XmlElementBool::~XmlElementBool () [virtual]
Definition at line 1023 of file XmlStream.cpp.
{
}
Member Function Documentation
virtual bool KKB::XmlElementBool::ToBool () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 515 of file XmlStream.h.
{return value;}
virtual double KKB::XmlElementBool::ToDouble () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 517 of file XmlStream.h.
{return (double)value;}
virtual float KKB::XmlElementBool::ToFloat () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 518 of file XmlStream.h.
{return (float)value;}
virtual kkint32 KKB::XmlElementBool::ToInt32 () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 519 of file XmlStream.h.
{return (kkint32)value;}
virtual KKStr KKB::XmlElementBool::ToKKStr () const [inline], [virtual]
Reimplemented from KKB::XmlElement.
Definition at line 516 of file XmlStream.h.
{return value ? "True" : "False";}
bool XmlElementBool::Value () const
Definition at line 1028 of file XmlStream.cpp.
Referenced by KKMLL::ModelParamUsfCasCor::ReadXML(), KKMLL::ModelParamDual::ReadXML(), and KKMLL::TrainingConfiguration2::ReadXMLBaseToken().
{
  return value;
}
void XmlElementBool::WriteXML (const bool b, const KKStr & varName, std::ostream & o) [static]
Definition at line 1035 of file XmlStream.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEmpty, KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::Model::WriteModelXMLFields(), KKMLL::ModelParamUsfCasCor::WriteXML(), KKMLL::ModelParamDual::WriteXML(), KKMLL::NormalizationParms::WriteXML(), KKMLL::TrainingProcess2::WriteXML(), KKMLL::ModelParam::WriteXMLFields(), and KKMLL::TrainingConfiguration2::WriteXMLFields().
{
  XmlTag startTag ("Bool", XmlTag::TagTypes::tagEmpty);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.AddAtribute ("Value", b);
  startTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp