KKMLL::CrossValidationVoting Class Reference
#include <CrossValidationVoting.h>
Public Member Functions
CrossValidationVoting (TrainingConfiguration2ListPtr _configs, FeatureVectorListPtr _examples, MLClassListPtr _mlClasses, kkint32 _numOfFolds, bool _featuresAreAlreadyNormalized, FileDescPtr _fileDesc)
~CrossValidationVoting ()
float Accuracy ()
double ClassificationTime () const
ConfusionMatrix2Ptr ConfussionMatrix ()
float FoldAccuracy (kkint32 foldNum) const
KKStr FoldAccuracysToStr () const
KKStr FoldStr () const
kkint32 NumOfSupportVectors () const
void RunCrossValidation (RunLog &log)
void RunValidationOnly (FeatureVectorListPtr validationData, bool *classedCorrectly, RunLog &log)
double TrainingTime () const
Detailed Description
Definition at line 55 of file CrossValidationVoting.h.
Constructor & Destructor Documentation
CrossValidationVoting::CrossValidationVoting (TrainingConfiguration2ListPtr _configs, FeatureVectorListPtr _examples, MLClassListPtr _mlClasses, kkint32 _numOfFolds, bool _featuresAreAlreadyNormalized, FileDescPtr _fileDesc)
Definition at line 31 of file CrossValidationVoting.cpp.
References KKMLL::FeatureVectorList::ExtractExamplesForClassList().
                                              :
   configs (_configs),
   featuresAreAlreadyNormalized (_featuresAreAlreadyNormalized),
   fileDesc (_fileDesc),
   foldAccuracies (NULL),
   foldCounts (NULL),
   confusionMatrix (NULL),
   cmByNumOfConflicts (NULL),
   examples (NULL),
   mlClasses (_mlClasses),
   examplesPerClass (0),
   maxNumOfConflicts (0),
   numOfFolds (_numOfFolds),
   numOfSupportVectors (0),
   numOfWinnersCounts (NULL),
   numOfWinnersCorrects (NULL),
   numOfWinnersOneOfTheWinners (NULL),
   classificationTime (0.0),
   trainingTime (0.0)
 
{
  examples = _examples->ExtractExamplesForClassList (mlClasses);
  examplesPerClass = 999999;
}
CrossValidationVoting::~CrossValidationVoting ()
Definition at line 65 of file CrossValidationVoting.cpp.
{
  DeleteAllocatedMemory ();
  delete examples; examples = NULL;
}
Member Function Documentation
float CrossValidationVoting::Accuracy ()
Definition at line 467 of file CrossValidationVoting.cpp.
References KKMLL::ConfusionMatrix2::Accuracy().
{
  if (confusionMatrix)
    return (float)confusionMatrix->Accuracy ();
  else
    return 0.0;
} /* Accuracy */
double KKMLL::CrossValidationVoting::ClassificationTime () const [inline]
Definition at line 79 of file CrossValidationVoting.h.
{return classificationTime;}
ConfusionMatrix2Ptr KKMLL::CrossValidationVoting::ConfussionMatrix () [inline]
Definition at line 76 of file CrossValidationVoting.h.
{return confusionMatrix;}
float CrossValidationVoting::FoldAccuracy (kkint32 foldNum) const
Definition at line 496 of file CrossValidationVoting.cpp.
{
  if (!foldAccuracies)
    return 0.0f;
  if ((foldNum < 0) || (foldNum >= numOfFolds))
    return 0.0f;
  return foldAccuracies[foldNum];
} /* FoldAccuracy */
KKStr CrossValidationVoting::FoldAccuracysToStr () const
Definition at line 478 of file CrossValidationVoting.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), and KKB::StrFormatDouble().
{
  KKStr foldAccuracyStr (9 * numOfFolds); // Pre Reserving enough space for all Accuracies.
  for (kkint32 foldNum = 0; foldNum < numOfFolds; foldNum++)
  {
    if (foldNum > 0)
      foldAccuracyStr << "\t";
    foldAccuracyStr << StrFormatDouble (foldAccuracies[foldNum], "ZZ,ZZ0.00%");
  }
  return foldAccuracyStr;
} /* FoldAccuracysToStr */
KKStr CrossValidationVoting::FoldStr () const
Definition at line 510 of file CrossValidationVoting.cpp.
References KKB::KKStr::Concat(), and KKB::KKStr::KKStr().
{
  if ((numOfFolds <= 0) || (!foldAccuracies))
    return "";
  kkint32 x;
  KKStr result (numOfFolds + 10);
  for (x = 0; x < numOfFolds; x++)
  {
    if (x > 0)
      result << ",";
    result << foldAccuracies[x];
  }
  return result;
} /* FoldStr */
kkint32 KKMLL::CrossValidationVoting::NumOfSupportVectors () const [inline]
Definition at line 83 of file CrossValidationVoting.h.
{return numOfSupportVectors;}
void CrossValidationVoting::RunCrossValidation (RunLog & log)
Definition at line 144 of file CrossValidationVoting.cpp.
References KKMLL::FeatureVectorList::ManufactureEmptyList(), and KKMLL::FeatureVectorList::PushOnBack().
{
  log.Level (10) << "CrossValidationVoting::RunCrossValidationVoting" <<
      endl;
  if (numOfFolds < 1)
  {
    log.Level (-1) << endl
                   << endl
                   << "CrossValidationVoting::RunCrossValidationVoting **** ERROR ****" <<
      endl
                   << endl
                   << " Invalid numOfFolds[" << numOfFolds << "]." <<
      endl
                   << endl;
    return;
  }
  DeleteAllocatedMemory ();
  AllocateMemory (log);
  kkint32 imageCount = examples->QueueSize ();
  kkint32 numImagesPerFold = (imageCount + numOfFolds - 1) / numOfFolds;
  kkint32 firstInGroup = 0;
  kkint32 foldNum;
  for (foldNum = 0; foldNum < numOfFolds; foldNum++)
  {
    kkint32 lastInGroup;
    // If We are doing the last Fold Make sure that we are including all the examples
    // that have not been tested.
    if (foldNum == (numOfFolds - 1))
      lastInGroup = imageCount;
    else
      lastInGroup = firstInGroup + numImagesPerFold - 1;
    cout << "Fold [" << (foldNum + 1) << "] of [" << numOfFolds << "]" << endl;
    FeatureVectorListPtr trainingExamples = examples->
      ManufactureEmptyList (true);
    FeatureVectorListPtr testImages = examples->
      ManufactureEmptyList (true);
    log.Level (30) << "Fold Num[" << foldNum << "] "
                   << "FirstTestImage[" << firstInGroup << "] "
                   << "LastInGroup[" << lastInGroup << "]."
                   << endl;
    for (kkint32 x = 0; x < imageCount; x++)
    {
      FeatureVectorPtr newImage = examples->IdxToPtr (x)->
      Duplicate ();
      if ((x >= firstInGroup) && (x <= lastInGroup))
        testImages->PushOnBack (newImage);
      else
        trainingExamples->PushOnBack (newImage);
    }
    cout << "Number Of Training Images : " << trainingExamples->QueueSize () <<
      endl;
    cout << "Number Of Test Images : " << testImages->QueueSize () <<
      endl;
    CrossValidate (testImages, trainingExamples, foldNum, NULL, log);
    delete trainingExamples; trainingExamples = NULL;
    delete testImages; testImages = NULL;
    firstInGroup = firstInGroup + numImagesPerFold;
  }
} /* RunCrossValidationVoting */
void CrossValidationVoting::RunValidationOnly (FeatureVectorListPtr validationData, bool * classedCorrectly, RunLog & log)
Definition at line 214 of file CrossValidationVoting.cpp.
References KKMLL::FeatureVectorList::DuplicateListAndContents().
{
  log.Level (10) << "CrossValidationVoting::RunValidationOnly" << endl;
  DeleteAllocatedMemory ();
  AllocateMemory (log);
  // We need to get a duplicate copy of each image data because the trainer and classifier
  // will normalize the data.
  FeatureVectorListPtr trainingExamples = examples->
      DuplicateListAndContents ();
  FeatureVectorListPtr testImages = validationData->
      DuplicateListAndContents ();
  CrossValidate (testImages, trainingExamples, 0, classedCorrectly, log);
  delete trainingExamples;
  delete testImages;
} /* RunValidationOnly */
double KKMLL::CrossValidationVoting::TrainingTime () const [inline]
Definition at line 84 of file CrossValidationVoting.h.
{return trainingTime;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/CrossValidationVoting.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/CrossValidationVoting.cpp