KKMLL::SizeDistribution Class Reference
Used to keep track of examples by size; typically used by 'CrossValidation'; for each example predicted it would call the ;Increment' method keeping track.
#include <SizeDistribution.h>
Classes
class ClassTotals
class ClassTotalsList
Public Member Functions
SizeDistribution (kkint32 _bucketCount, kkint32 _bucketSize, RunLog &_log)
~SizeDistribution ()
void Increment (MLClassPtr mlClass, kkint32 size)
void PrintByClassCollumns (ostream &o, VectorUlong *scanLinesPerMeter) const
void PrintCSVDistributionMatrix (ostream &_outFile) const
void PrintFormatedDistributionMatrix (ostream &_outFile) const
void PrintTabDelDistributionMatrix (ostream &_outFile) const
Detailed Description
Used to keep track of examples by size; typically used by 'CrossValidation'; for each example predicted it would call the ;Increment' method keeping track.
Definition at line 26 of file SizeDistribution.h.
Constructor & Destructor Documentation
SizeDistribution::SizeDistribution (kkint32 _bucketCount, kkint32 _bucketSize, RunLog & _log)
Definition at line 219 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotalsList::ClassTotalsList().
                                    :
  bucketCount (_bucketCount),
  bucketSize (_bucketSize),
  log (_log),
  totals (new SizeDistribution::ClassTotalsList (true))
{
  if (bucketCount < 1)
  {
    log.Level (-1) << endl << endl << endl
                   << "SizeDistribution::SizeDistribution *** Invalid Bucket Size[" << bucketSize << "]
       ***" << endl
                   << endl;
  }
}
SizeDistribution::~SizeDistribution ()
Definition at line 239 of file SizeDistribution.cpp.
{
  delete totals;
}
Member Function Documentation
void SizeDistribution::Increment (MLClassPtr mlClass, kkint32 size)
Definition at line 264 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::ClassTotals(), KKMLL::MLClass::GetUnKnownClassStatic(), KKMLL::SizeDistribution::ClassTotals::Increment(), KKMLL::SizeDistribution::ClassTotalsList::LookUp(), and KKMLL::MLClass::Name().
{
  if (mlClass == NULL)
    mlClass = MLClass::GetUnKnownClassStatic ();
  ClassTotals::ClassTotalsPtr classTotals = totals->
      LookUp (mlClass->Name ());
  if (!classTotals)
  {
    classTotals = new ClassTotals (mlClass->Name (), bucketCount, bucketSize);
    totals->PushOnBack (classTotals);
  }
  classTotals->Increment (size);
} /* Increment */
void SizeDistribution::PrintByClassCollumns (ostream & o, VectorUlong * scanLinesPerMeter) const
Definition at line 438 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::BucketCount(), KKB::KKStr::Concat(), KKMLL::MLClassList::ExtractThreeTitleLines(), KKMLL::SizeDistribution::ClassTotalsList::LookUp(), and KKMLL::MLClass::Name().
{
  KKStr hd1, hd2, hd3;
  MLClassListPtr classes = BuildMLClassList ();
  MLClassList::const_iterator cIDX;
 
  // Find the first and last buckets with activity
  
  kkint32 firstBucket = -1;
  kkint32 lastBucket = 0;
  
  for (kkint32 bucketIDX = 0; bucketIDX < bucketCount; bucketIDX++)
  {
    kkint32 bucketTotal = 0;
    for (cIDX = classes->begin (); cIDX != classes->end (); cIDX++)
    {
      MLClassPtr mlClass = *cIDX;
      ClassTotals::ClassTotalsPtr classTotals = totals->
      LookUp (mlClass->Name ());
      bucketTotal += classTotals->BucketCount (bucketIDX);
    }
    if (bucketTotal > 0)
    {
      if (firstBucket < 0)
        firstBucket = bucketIDX;
      lastBucket = bucketIDX;
    }
  }
  if (firstBucket < 0)
  {
    o << endl << endl
      << "SizeDistribution::PrintByClassCollumns *** There is no SizeDistribution Data ***" <<
      endl
      << endl;
    return;
  }
  VectorInt finalTotals (classes->size (), 0);
  kkint32 grandTotal = 0;
  classes->ExtractThreeTitleLines (hd1, hd2, hd3);
  o << "" << "\t" << "" << "\t" << hd1 << "\t" << "" << endl
    << "" << "\t" << "Scan" << "\t" << hd2 << "\t" << "Bucket" << endl
    << "Depth" << "\t" << "Lines" << "\t" << hd3 << "\t" << "Total" << endl;
  kkuint64 totalScanLines = 0;
  kkint32 imageSize = firstBucket * bucketSize;
  for (kkint32 bucketIDX = firstBucket; bucketIDX <= lastBucket; bucketIDX++)
  {
    kkint32 nextImageSize = imageSize + bucketSize;
    kkuint64 scanLinesDepthForThisBucket = 0;
    if (scanLinesPerMeterDepth != NULL)
    {
      for (kkint32 x = imageSize; x < Min (nextImageSize, (kkint32)
      scanLinesPerMeterDepth->size ()); x++)
        scanLinesDepthForThisBucket += (*scanLinesPerMeterDepth)[x];
    }
    o << imageSize << "\t" << scanLinesDepthForThisBucket;
    totalScanLines += scanLinesDepthForThisBucket;
    kkint32 bucketTotal = 0;
    kkint32 intIDX = 0;
    for (cIDX = classes->begin (); cIDX != classes->end (); cIDX++)
    {
      MLClassPtr mlClass = *cIDX;
      ClassTotals::ClassTotalsPtr classTotals = totals->
      LookUp (mlClass->Name ());
      kkint32 qtyThisBucket = classTotals->BucketCount (bucketIDX);
      o << "\t" << qtyThisBucket;
      bucketTotal += qtyThisBucket;
      finalTotals[intIDX] += qtyThisBucket;
      grandTotal += qtyThisBucket;
      intIDX++;
    }
    imageSize = nextImageSize;
    o << "\t" << bucketTotal << endl;
  }
  {
    o << endl
      << "FinalTotals" << "\t" << totalScanLines;
    for (kkuint32 x = 0; x < classes->size (); x++)
    {
      o << "\t" << finalTotals[x];
    }
    o << "\t" << grandTotal << endl
      << endl;
  }
  delete classes; classes = NULL;
} /* ReportByClassCollumns */
void SizeDistribution::PrintCSVDistributionMatrix (ostream & _outFile) const
Definition at line 311 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::AddIn(), KKMLL::SizeDistribution::ClassTotals::ClassTotals(), and KKMLL::SizeDistribution::ClassTotals::PrintCSVLine().
{
  PrintCSVHeader (o);
  ClassTotals::ClassTotalsPtr classTotals = NULL;
  ClassTotals grandTotals ("Grand Totals", bucketCount, bucketSize);
  kkint32 idx;
  for (idx = 0; idx < totals->QueueSize (); idx++)
  {
    classTotals = totals->IdxToPtr (idx);
    classTotals->PrintCSVLine (o);
    grandTotals.AddIn (classTotals);
  }
  o << endl;
  grandTotals.PrintCSVLine (o);
} /* PrintCSVDistributionMatrix */
void SizeDistribution::PrintFormatedDistributionMatrix (ostream & _outFile) const
Definition at line 285 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::AddIn(), KKMLL::SizeDistribution::ClassTotals::ClassTotals(), and KKMLL::SizeDistribution::ClassTotals::PrintFormatedLine().
{
  PrintFormatedHeader (o);
  ClassTotals::ClassTotalsPtr classTotals = NULL;
  ClassTotals grandTotals ("Grand Totals", bucketCount, bucketSize);
  kkint32 idx;
  for (idx = 0; idx < totals->QueueSize (); idx++)
  {
    classTotals = totals->IdxToPtr (idx);
    classTotals->PrintFormatedLine (o);
    grandTotals.AddIn (classTotals);
  }
  o << endl;
  grandTotals.PrintFormatedLine (o);
} /* PrintFormatedDistributionMatrix */
void SizeDistribution::PrintTabDelDistributionMatrix (ostream & _outFile) const
Definition at line 335 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::AddIn(), KKMLL::SizeDistribution::ClassTotals::ClassTotals(), and KKMLL::SizeDistribution::ClassTotals::PrintTabDelLine().
{
  PrintTabDelHeader (o);
  ClassTotals::ClassTotalsPtr classTotals = NULL;
  ClassTotals grandTotals ("Grand Totals", bucketCount, bucketSize);
  kkint32 idx;
  for (idx = 0; idx < totals->QueueSize (); idx++)
  {
    classTotals = totals->IdxToPtr (idx);
    classTotals->PrintTabDelLine (o);
    grandTotals.AddIn (classTotals);
  }
  o << endl;
  grandTotals.PrintTabDelLine (o);
} /* PrintTabDelDistributionMatrix */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/SizeDistribution.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/SizeDistribution.cpp