KKB::Matrix Class Reference
Supports two dimensional matrices.
#include <Matrix.h>
Public Types
typedef Matrix * MatrixPtr
Public Member Functions
Matrix ()
Matrix (kkint32 _numOfRows, kkint32 _numOfCols)
Matrix (const Matrix &_matrix)
Matrix (const VectorDouble &_v)
~Matrix ()
MatrixPtr CalcCoFactorMatrix ()
MatrixPtr Covariance () const
Returns a Covariance matrix.
double **const Data () const
double Determinant ()
double DeterminantSlow ()
Recursive Implementation.
void EigenVectors (MatrixPtr &eigenVectors, VectorDouble *&eigenValues) const
Will derive the Eigen vectors and values of the matrix.
void FindMaxValue (double &maxVal, kkint32 &row, kkint32 &col)
Locates the maximum value in a matrix along with the row and column that is located.
VectorDouble GetCol (kkint32 col) const
Matrix Inverse ()
kkint32 NumOfCols () const
kkint32 NumOfRows () const
Matrix operator* (const Matrix &right)
Matrix operator* (double right)
Matrix & operator*= (double right)
Matrix operator+ (const Matrix &right)
Matrix operator+ (double right)
Matrix & operator+= (double right)
Matrix & operator+= (const Matrix &right)
Matrix operator- (const Matrix &right)
Matrix operator- (double right)
Matrix & operator= (const Matrix &right)
Matrix & operator= (const VectorDouble &right)
Row & operator[] (kkint32 rowIDX) const
void ReSize (kkint32 _numOfRows, kkint32 _numOfCols)
bool Symmetric () const
Matrix Transpose ()
Static Public Member Functions
template<typename T >
static MatrixPtr BuildFromArray (kkint32 numOfRows, kkint32 numOfCols, T **data)
Will create a new matrix using the 2dArray `data` for source.
Friends
Matrix operator- (double left, const Matrix &right)
std::ostream & operator<< (std::ostream &os, const Matrix &matrix)
Detailed Description
Supports two dimensional matrices.
Developed for Machine Learning Project for support of Import Vector Machine. Handles two dimensional matrices. Functions supported are matrix addition, subtraction multiplication, transpose, determinant, and inversion. Where appropriate arithmetic arithmetic operators +, -, * were overloaded. Addition, Subtraction and Multiplication can be done against either another matrix or scaler. Also Transpose and Determinant operations are supported.
Definition at line 46 of file Matrix.h.
Member Typedef Documentation
typedef Matrix* KKB::Matrix::MatrixPtr
Definition at line 49 of file Matrix.h.
Constructor & Destructor Documentation
Matrix::Matrix ()
Definition at line 94 of file Matrix.cpp.
               :
  data (NULL),
  dataArea (NULL),
  numOfCols (0),
  numOfRows (0),
  rows (NULL),
  totNumCells (0)
{
}
Matrix::Matrix (kkint32 _numOfRows, kkint32 _numOfCols)
Definition at line 108 of file Matrix.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), and KKB::KKStr::KKStr().
Referenced by KKB::Raster::BuildGaussian2dKernel(), CalcCoFactorMatrix(), Covariance(), KKB::Raster::CreateGrayScaleKLT(), KKB::Raster::CreateGrayScaleKLTOnMaskedArea(), operator*(), KKB::operator-(), KKMLL::ClassificationBiasMatrix::PerformAdjustmnts(), and Transpose().
                :
  data (NULL),
  dataArea (NULL),
  numOfCols (_numOfCols),
  numOfRows (_numOfRows),
  rows (NULL),
  totNumCells (0)
{
  if (_numOfRows < 0)
  {
    KKStr msg(80);
    msg << "Matrix::Matrix **** ERROR ****, Row Dimension[" << _numOfRows << "] Invalid.";
    cerr << std::endl << msg <<std::endl << std::endl;
    throw KKException (msg);
  }
  if (_numOfCols < 0)
  {
    KKStr msg(80);
    msg << "Matrix::Matrix **** ERROR ****, Col Dimension[" << _numOfCols << "] Invalid.";
    cerr << std::endl << msg <<std::endl << std::endl;
    throw KKException (msg);
  }
  AllocateStorage ();
} /* Matrix::Matrix */
Matrix::Matrix (const Matrix & _matrix)
Definition at line 142 of file Matrix.cpp.
Referenced by KKMLL::ClassificationBiasMatrix::ClassificationBiasMatrix(), EigenVectors(), operator*(), operator+(), and operator-().
                                     :
  data (NULL),
  dataArea (NULL),
  numOfCols (_matrix.numOfCols),
  numOfRows (_matrix.numOfRows),
  rows (NULL),
  totNumCells (0)
{
  AllocateStorage ();
  memcpy (dataArea, _matrix.dataArea, totNumCells * sizeof (double));
} /* Matrix::Matrix */
Matrix::Matrix (const VectorDouble & _v)
Definition at line 157 of file Matrix.cpp.
References Matrix().
Referenced by Matrix().
                                      :
  data (NULL),
  dataArea (NULL),
  numOfCols (1),
  numOfRows (kkint32 (_v.size ())),
  rows (NULL)
{
  AllocateStorage ();
  kkint32 row;
  for (row = 0; row < numOfRows; ++row)
    dataArea[row] = _v[row];
} /* Matrix::Matrix */
Matrix::~Matrix ()
Definition at line 173 of file Matrix.cpp.
{
  Destroy ();
}
Member Function Documentation
template<typename T > MatrixPtr Matrix::BuildFromArray (kkint32 numOfRows, kkint32 numOfCols, T ** data) [static]
Will create a new matrix using the 2dArray `data` for source.
If any row in `data` is equal to NULL then the corresponding row in the returned matrix will be initialized to zeros.
Parameters
in numOfRows Number of rows in resultant matrix.
in numOfCols Number of cols if resultant matrix.
in data A two dimensional array.
Returns
A matrix that is initialized with the contents of `data`.
Definition at line 190 of file Matrix.cpp.
{
  if ((numOfRows < 1) || (numOfCols < 1))
  {
    cerr << std::endl << std::endl << "Matrix::BuildFromArray ***ERROR*** NumOfRows[
      " << numOfRows << "] or NumOfCols[" << numOfCols << "] is invalid." <<
      std::endl << std::endl;
    return NULL;
  }
  if (!data)
  {
    cerr << std::endl << std::endl << "Matrix::BuildFromArray ***ERROR*** No source
       data (data == NULL)." << std::endl << std::endl;
    return NULL;
  }
  MatrixPtr m = new Matrix (numOfRows, numOfCols);
  for (kkint32 row = 0; row < numOfRows; ++row)
  {
    T* srcRow = data[row];
    double* destRow = m->data[row];
    if (srcRow)
    {
      for (kkint32 col = 0; col < numOfCols; ++col)
        destRow[col] = (double)(srcRow[col]);
    }
  }
  return m;
} /* BuildFromArray */
MatrixPtr Matrix::CalcCoFactorMatrix ()
Definition at line 606 of file Matrix.cpp.
References Determinant(), Matrix(), operator[](), KKB::Row::operator[](), and KKB::osWaitForEnter().
Referenced by Inverse().
{
  if (numOfCols != numOfRows)
  {
    cerr << std::endl
         << "Matrix::CalcCoFactors **** ERROR ****, Matrix not a Square["
         << numOfRows << "," << numOfCols << "]."
         << std::endl
         << std::endl;
    osWaitForEnter ();
    exit (1);
  }
  MatrixPtr result = new Matrix (numOfRows, numOfCols);
  kkint32 newSize = numOfCols - 1;
  kkint32* colMap = new kkint32 [newSize];
  kkint32* rowMap = new kkint32 [newSize];
  kkint32 row;
  kkint32 col;
  kkint32 x;
  kkint32 sign;
  for (row = 0; row < numOfRows; row++)
  {
    // Create a map of all rows except row we are calculating
    // CoFactors for.
    kkint32 newRow = 0;
    for (x = 0; x < numOfRows; x++)
    {
      if (x != row)
      {
        rowMap[newRow] = x;
        newRow++;
      }
    }
    for (col = 0; col < numOfCols; col++)
    {
      // Create a map of all cells except row we are calculating
      // CoFactor for.
      kkint32 newCol = 0;
      for (x = 0; x < numOfCols; x++)
      {
        if (x != col)
        {
          colMap[newCol] = x;
          newCol++;
        }
      }
      if (((row + col) % 2) == 0)
        sign = 1;
      else
        sign = -1;
      Matrix temp (newSize, newSize);
      for (kkint32 r = 0; r < newSize; r++)
      {
        kkint32 tempR = rowMap[r];
        for (kkint32 c = 0; c < newSize; c++)
          temp[r][c] = data[tempR][colMap[c]];
      }
      result->data[row][col] = temp.Determinant () * sign;
    }
  }
  return result;
} /* CalcCoFactor */
MatrixPtr Matrix::Covariance () const
Returns a Covariance matrix.
Each column represents a variable and each row represents an instance of each variable.
Returns
Returns a symmetric matrix that will be (numOfRows x numOfRows) where each element will represent the covariance between their respective variables.
Definition at line 1004 of file Matrix.cpp.
References Matrix(), operator[](), and KKB::Row::operator[]().
{
  if ((data == NULL) || (numOfRows < 1))
  {
    cerr << std::endl << "Matrix::Covariance ***ERROR*** 'data' not defined in Matrix." <<
      std::endl << std::endl;
    return NULL;
  }
  // Used web site below to help with Covariance calculations
  // http://www.itl.nist.gov/div898/handbook/pmc/section5/pmc541.htm
  kkint32 col = 0;
  kkint32 row = 0;
  double* totals = new double[numOfCols];
  double* means = new double[numOfCols];
  double** centeredVals = new double*[numOfCols];
  for (col = 0; col < numOfCols; ++col)
  {
    totals[col] = 0.0;
    centeredVals[col] = new double[numOfRows];
  }
  for (row = 0; row < numOfRows; ++row)
  {
    double* rowData = data[row];
    for (col = 0; col < numOfCols; ++col)
      totals[col] += rowData[col];
  }
  for (col = 0; col < numOfCols; ++col)
    means[col] = totals[col] / numOfRows;
  for (row = 0; row < numOfRows; ++row)
  {
    double* rowData = data[row];
    for (col = 0; col < numOfCols; ++col)
      centeredVals[col][row] = rowData[col] - means[col];
  }
 
  MatrixPtr covariances = new Matrix (numOfCols, numOfCols);
  for (kkint32 varIdxX = 0; varIdxX < numOfCols; ++varIdxX)
  {
    double* varXs = centeredVals[varIdxX];
    for (kkint32 varIdxY = varIdxX; varIdxY < numOfCols; ++varIdxY)
    {
      // Calculate the covariance between chanIdx0 and chanIdx1
      double* varYs = centeredVals[varIdxY];
      double total = 0.0f;
      for (row = 0; row < numOfRows; ++row)
        total += varXs[row] * varYs[row];
      (*covariances)[varIdxX][varIdxY] = total / (numOfRows - 1);
      (*covariances)[varIdxY][varIdxX] = (*covariances)[varIdxX][varIdxY];
    }
  }
  for (col = 0; col < numOfCols; col++)
  {
    delete[] centeredVals[col];
    centeredVals[col] = NULL;
  }
  delete[] centeredVals; centeredVals = NULL;
  delete[] means; means = NULL;
  delete[] totals; totals = NULL;
  return covariances;
} /* Covariance */
double** const KKB::Matrix::Data () const [inline]
Definition at line 106 of file Matrix.h.
{return data;}
double Matrix::Determinant ()
Returns
the determinant of mat
Definition at line 945 of file Matrix.cpp.
Referenced by CalcCoFactorMatrix(), and Inverse().
{
  if (numOfCols != numOfRows)
    return -999999.99;
  kkint32 r, c;
  double** mat = new double*[numOfRows];
  for (r = 0; r < numOfRows; r++)
  {
    mat[r] = new double[numOfCols];
    for (c = 0; c < numOfCols; c++)
    {
      mat[r][c] = data[r][c];
    }
  }
    double det = 1.0;
    unsigned short i = 0;
    for (i = 0; i < numOfRows; i++)
    {
        const double Aii = DeterminantSwap (mat, i);
        unsigned short j = 0;
        if (fabs (Aii) < DBL_EPSILON)
        {
            det = 0.0;
            break;
        }
        det *= Aii;
        
        //Do elimination
        for (j = i + 1; j < numOfRows; j++)
        {
            const double pivot = mat[j][i] / Aii;
            for (ushort k = i; k < numOfRows; k++)
                mat[j][k] -= pivot * mat[i][k];
        }
    }
  for (r = 0; r < numOfRows; r++)
  {
    delete mat[r];
    mat[r] = NULL;
  }
  delete[] mat;
  mat = NULL;
    return (det);
} /* Determinant */
double Matrix::DeterminantSlow ()
Recursive Implementation.
Definition at line 286 of file Matrix.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), and KKB::KKStr::KKStr().
{
  if (numOfCols != numOfRows)
  {
    KKStr msg (80);
    msg << "Matrix::Determinant *** ERROR *** Dimensions are not Square[" << numOfRows << "," <<
      numOfCols << "] Invalid.";
    cerr << std::endl << msg << std::endl << std::endl;
    throw KKException (msg);
  }
  if (numOfCols == 1)
  {
    // return rows[0]->cells[0];
    return data[0][0];
  }
  kkint32 x;
  kkint32* rowMap = new kkint32[numOfRows];
  for (x = 0; x < numOfRows; x++)
    rowMap[x] = x;
  kkint32* colMap = new kkint32[numOfCols];
  for (x = 0; x < numOfCols; x++)
    colMap[x] = x;
  double det = CalcDeterminent (rowMap, colMap, numOfCols);
  delete[] colMap;
  return det;
} /* Determinant */
void Matrix::EigenVectors (MatrixPtr & eigenVectors, VectorDouble *& eigenValues) const
Will derive the Eigen vectors and values of the matrix.
Will make use of routines from Numerical Recipes for c++, ex: Tred2 and Tqli.
Definition at line 768 of file Matrix.cpp.
References Matrix(), and Symmetric().
Referenced by KKB::Raster::CreateGrayScaleKLT(), and KKB::Raster::CreateGrayScaleKLTOnMaskedArea().
{
  eigenVectors = NULL;
  eigenValues = NULL;
  if ((data == NULL) || (numOfRows < 1))
  {
    cerr << std::endl << "Matrix::EigenVectors ***ERROR*** 'data' not defined in Matrix." <<
      std::endl << std::endl;
    return;
  }
  
  if (numOfRows != numOfCols)
  {
    cerr << std::endl << "Matrix::EigenVectors ***ERROR*** Not a square matrix NumOfRows[" <<
       numOfRows << "] NumOfCols[" << numOfCols << "]." << std::endl <<
      std::endl;
    return;
  }
  eigenVectors = new Matrix (*this);
  if (Symmetric ())
  {
    double* d = new double[numOfRows];
    double* e = new double[numOfRows];
    for (kkint32 x = 0; x < numOfRows; ++x)
    {
      d[x] = 0.0;
      e[x] = 0.0;
    }
    Tred2 (eigenVectors->data, numOfRows, d, e);
    kkint32 successful = Tqli (d, e, numOfRows, eigenVectors->data);
    if (successful != 1)
    {
      delete eigenVectors; eigenVectors = NULL;
      delete[] d; d = NULL;
      delete[] e; e = NULL;
      return;
    }
    eigenValues = new VectorDouble ();
    for (kkint32 x = 0; x < numOfRows; ++x)
      eigenValues->push_back (d[x]);
    delete[] d; d = NULL;
    delete[] e; e = NULL;
  }
} /* GetEigenVectors */
void Matrix::FindMaxValue (double & maxVal, kkint32 & row, kkint32 & col)
Locates the maximum value in a matrix along with the row and column that is located.
Definition at line 818 of file Matrix.cpp.
Referenced by KKB::SegmentorOTSU::SegmentImage(), and KKB::SegmentorOTSU::SegmentMaskedImage().
{
  rowIdx = -1;
  colIdx = -1;
  maxVal = DBL_MIN;
  if (!data)
    return;
  maxVal = data[0][0];
  rowIdx = colIdx = 0;
  for (kkint32 row = 0; row < numOfRows; ++row)
  {
    double* dataRow = data[row];
    for (kkint32 col = 0; col < numOfCols; ++col)
    {
      if (dataRow[col] > maxVal)
      {
        maxVal = dataRow[col];
        colIdx = col;
        rowIdx = row;
      }
    }
  }
  return;
} /* FindMaxValue */
VectorDouble Matrix::GetCol (kkint32 col) const
Definition at line 891 of file Matrix.cpp.
Referenced by KKB::Raster::CreateGrayScaleKLT(), and KKB::Raster::CreateGrayScaleKLTOnMaskedArea().
{
  VectorDouble colResult (numOfRows, 0.0);
  for (kkint32 r = 0; r < numOfRows; r++)
    colResult[r] = data[r][col];
  return colResult;
} /* GetCol */
Matrix Matrix::Inverse ()
Definition at line 731 of file Matrix.cpp.
References CalcCoFactorMatrix(), KKB::KKStr::Concat(), Determinant(), KKB::KKException::KKException(), KKB::KKStr::KKStr(), operator*=(), and Transpose().
Referenced by KKMLL::ClassificationBiasMatrix::PerformAdjustmnts().
{
  if (numOfCols != numOfRows)
  {
    KKStr msg (80);
    msg << "Matrix::Inverse *** ERROR *** Dimensions are not Square[" << numOfRows << "," << numOfCols
       << "] Invalid.";
    cerr << std::endl << msg << std::endl << std::endl;
    throw KKException (msg);
  }
  double det = Determinant ();
  if (det == 0)
  {
    cerr << std::endl << "Matrix::Inverse *** ERROR *** Determinant of Matrix is Zero." <<
      std::endl << std::endl;
  }
  MatrixPtr coFactors = CalcCoFactorMatrix ();
  Matrix result = coFactors->Transpose ();
  delete coFactors;
  if (det == 0.0)
    result *= 0.0;
  else
    result *= (1.0 / det);
  return result;
} /* Inverse */
kkint32 KKB::Matrix::NumOfCols () const [inline]
Definition at line 126 of file Matrix.h.
Referenced by KKB::operator-(), and operator<<().
{return numOfCols;}
kkint32 KKB::Matrix::NumOfRows () const [inline]
Definition at line 128 of file Matrix.h.
Referenced by KKB::operator-(), and operator<<().
{return numOfRows;}
Matrix Matrix::operator* (const Matrix & right)
Definition at line 478 of file Matrix.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKB::KKStr::KKStr(), and Matrix().
Referenced by KKMLL::ClassificationBiasMatrix::PerformAdjustmnts().
{
  if (numOfCols != right.numOfRows)
  {
    KKStr msg (100);
    msg << "Matrix::operator* **** ERROR ****, Dimension Mismatch Left[" << numOfRows << "," <<
      numOfCols << "] Right[" << right.numOfRows << "," << right.numOfCols << "].";
    cerr << std::endl << msg << std::endl << std::endl;
    throw KKException (msg);
  }
  kkint32 col;
  kkint32 row;
  kkint32 rRows = numOfRows;
  kkint32 rCols = right.numOfCols;
  Matrix result (rRows, rCols);
  double** resultData = result.data;
  double** rightData = right.data;
  kkint32 innerDim = numOfCols;
  for (row = 0; row < rRows; row++)
  {
    for (col = 0; col < rCols; col++)
    {
       double val = 0;
       kkint32 x = 0;
       for (x = 0; x < innerDim; x++)
         val = val + data[row][x] * rightData[x][col];
       resultData[row][col] = val;
    }
  }
  return result;
} /* Matrix::operator */
Matrix Matrix::operator* (double right)
Definition at line 530 of file Matrix.cpp.
References Matrix().
{
  Matrix result (*this);
  double* resultDataArea = result.dataArea;
  for (kkint32 x = 0; x < totNumCells; ++x)
    resultDataArea[x] = dataArea[x] * right;
  return result;
} /* operator* */
Matrix & Matrix::operator*= (double right)
Definition at line 349 of file Matrix.cpp.
Referenced by Inverse().
{
  kkint32 x = 0;
  for (x = 0; x < totNumCells; ++x)
    dataArea[x] *= right;
  return *this;
}
Matrix Matrix::operator+ (const Matrix & right)
Definition at line 369 of file Matrix.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKB::KKStr::KKStr(), and Matrix().
Referenced by KKB::SegmentorOTSU::SegmentImage(), and KKB::SegmentorOTSU::SegmentMaskedImage().
{
  if ((numOfRows != right.numOfRows) ||
       (numOfCols != right.numOfCols))
  {
    KKStr msg (100);
    msg << "Matrix::operator+ **** ERROR ****, Dimensions Don't Match [" << numOfRows << "," <<
      numOfCols << "] + [" << right.numOfRows << "," << right.numOfCols << "].";
    cerr << std::endl << msg << std::endl << std::endl;
    throw KKException (msg);
  }
  Matrix result (*this);
  double* resultDataArea = result.dataArea;
  double* rightDataArea = right.dataArea;
  for (kkint32 x = 0; x < totNumCells; ++x)
    resultDataArea[x] = dataArea[x] + rightDataArea[x];
  return result;
} /* Matrix::operator+ */
Matrix Matrix::operator+ (double right)
Definition at line 519 of file Matrix.cpp.
References Matrix().
{
  Matrix result (*this);
  double* resultDataArea = result.dataArea;
  for (kkint32 x = 0; x < totNumCells; ++x)
    resultDataArea[x] = dataArea[x] + right;
  return result;
} /* operator+ */
Matrix & Matrix::operator+= (double right)
Definition at line 359 of file Matrix.cpp.
{
  kkint32 x = 0;
  for (x = 0; x < totNumCells; ++x)
    dataArea[x] += right;
  return *this;
}
Matrix & Matrix::operator+= (const Matrix & right)
Definition at line 396 of file Matrix.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), and KKB::KKStr::KKStr().
{
  if ((numOfRows != right.numOfRows) ||
       (numOfCols != right.numOfCols))
  {
    KKStr msg (100);
    msg << "Matrix::operator+= **** ERROR ****, Dimensions Don't Match [" << numOfRows << "," <<
      numOfCols << "] + [" << right.numOfRows << "," << right.numOfCols << "].";
    cerr << std::endl << msg << std::endl << std::endl;
    throw KKException (msg);
  }
  double* rightDataArea = right.dataArea;
  for (kkint32 x = 0; x < totNumCells; ++x)
    dataArea[x] += rightDataArea[x];
  return *this;
} /* Matrix::operator+ */
Matrix Matrix::operator- (const Matrix & right)
Definition at line 419 of file Matrix.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKB::KKStr::KKStr(), and Matrix().
Referenced by KKB::SegmentorOTSU::SegmentImage(), and KKB::SegmentorOTSU::SegmentMaskedImage().
{
  if ((numOfRows != right.numOfRows) ||
       (numOfCols != right.numOfCols))
  {
    KKStr msg (100);
    msg << "Matrix::operator- **** ERROR ****, Dimensions Don't Match [" << numOfRows << "," <<
      numOfCols << "] + [" << right.numOfRows << "," << right.numOfCols << "].";
    cerr << std::endl << msg << std::endl << std::endl;
    throw KKException (msg);
  }
  Matrix result (*this);
  double* resultDataArea = result.dataArea;
  double* rightDataArea = right.dataArea;
  for (kkint32 x = 0; x < totNumCells; ++x)
    resultDataArea[x] = dataArea[x] - rightDataArea[x];
  return result;
} /* operator- */
Matrix Matrix::operator- (double right)
Definition at line 443 of file Matrix.cpp.
References Matrix().
Referenced by KKB::SegmentorOTSU::SegmentImage(), and KKB::SegmentorOTSU::SegmentMaskedImage().
{
  Matrix result (*this);
  double* resultDataArea = result.dataArea;
  for (kkint32 x = 0; x < totNumCells; ++x)
    resultDataArea[x] = dataArea[x] - right;
  return result;
}
Matrix & Matrix::operator= (const Matrix & right)
Definition at line 329 of file Matrix.cpp.
References ReSize().
{
  ReSize (right.numOfRows, right.numOfCols);
  memcpy (dataArea, right.dataArea, totNumCells * sizeof (double));
  return *this;
}
Matrix & Matrix::operator= (const VectorDouble & right)
Definition at line 337 of file Matrix.cpp.
{
  ReSize ((kkuint32)right.size (), 1);
  for (kkint32 row = 0; row < numOfRows; row++)
    dataArea[row] = right[row];
  return *this;
} /* operator= */
Row & Matrix::operator[] (kkint32 rowIDX) const
Definition at line 270 of file Matrix.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), and KKB::KKStr::KKStr().
Referenced by KKB::Raster::BuildGaussian2dKernel(), CalcCoFactorMatrix(), Covariance(), KKB::Raster::CreateGrayScaleKLT(), KKB::Raster::CreateGrayScaleKLTOnMaskedArea(), KKMLL::ClassificationBiasMatrix::PerformAdjustmnts(), and KKMLL::ClassificationBiasMatrix::PrintBiasMatrix().
{
  if ((rowIDX < 0) || (rowIDX >= numOfRows))
  {
    KKStr msg (80);
    msg << "Matrix::operator[] **** ERROR ****, Row Index[" << rowIDX << "] Invalid.";
    cerr << std::endl << msg << std::endl << std::endl;
    throw KKException (msg);
  }
  return (rows[rowIDX]);
} /* Matrix::operator[] */
void Matrix::ReSize (kkint32 _numOfRows, kkint32 _numOfCols)
Definition at line 224 of file Matrix.cpp.
Referenced by operator=().
{
  Destroy ();
  numOfRows = _numOfRows;
  numOfCols = _numOfCols;
  AllocateStorage ();
} /* ReSize */
bool Matrix::Symmetric () const
Returns true is the matrix is Symmetric
Definition at line 688 of file Matrix.cpp.
Referenced by EigenVectors().
{
  if ((data == NULL) || (numOfRows != numOfCols))
    return false;
  for (kkint32 row = 0; row < numOfRows; ++row)
  {
    for (kkint32 col = row + 1; col < numOfCols; ++col)
    {
      if (data[row][col] != data[col][row])
        return false;
    }
  }
  return true;
} /* Symmetric */
Matrix Matrix::Transpose ()
Definition at line 707 of file Matrix.cpp.
References Matrix().
Referenced by Inverse(), and KKMLL::ClassificationBiasMatrix::PerformAdjustmnts().
{
  kkint32 col;
  kkint32 row;
  Matrix result (numOfCols, numOfRows);
  double** resultData = result.data;
  for (row = 0; row < numOfRows; row++)
  {
    for (col = 0; col < numOfCols; col++)
    {
      resultData[col][row] = data[row][col];
    }
  }
  return result;
} /* Transpose */
Friends And Related Function Documentation
Matrix operator- (double left, const Matrix & right) [friend]
std::ostream& operator<< (std::ostream & os, const Matrix & matrix) [friend]
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Matrix.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Matrix.cpp