KKMLL::DuplicateImage Class Reference
#include <DuplicateImages.h>
Public Member Functions
DuplicateImage (FileDescPtr _fileDesc, FeatureVectorPtr _image1, FeatureVectorPtr _image2, RunLog &_log)
~DuplicateImage ()
void AddADuplicate (FeatureVectorPtr example)
bool AllTheSameClass ()
bool AlreadyHaveExample (FeatureVectorPtr example)
const FeatureVectorListPtr DuplicatedImages ()
FeatureVectorPtr ExampleWithSmallestScanLine ()
FeatureVectorPtr FirstExampleAdded ()
Detailed Description
Definition at line 124 of file DuplicateImages.h.
Constructor & Destructor Documentation
DuplicateImage::DuplicateImage (FileDescPtr _fileDesc, FeatureVectorPtr _image1, FeatureVectorPtr _image2, RunLog & _log)
Parameters
_image1 image1, will be the one that we was already in the index structures.
Definition at line 369 of file DuplicateImages.cpp.
References DuplicateImage().
Referenced by KKMLL::DuplicateImages::AddSingleExample(), and DuplicateImage().
                                :
   fileDesc (_fileDesc),
   duplicatedImages (_fileDesc, false),
   firstImageAdded (_image1)
{
  duplicatedImages.PushOnBack (_image1);
  duplicatedImages.PushOnBack (_image2);
}
DuplicateImage::~DuplicateImage ()
Definition at line 383 of file DuplicateImages.cpp.
{
}
Member Function Documentation
void DuplicateImage::AddADuplicate (FeatureVectorPtr example)
Definition at line 388 of file DuplicateImages.cpp.
Referenced by KKMLL::DuplicateImages::AddSingleExample().
{
  duplicatedImages.PushOnBack (example);
} /* AddADuplicate */
bool DuplicateImage::AllTheSameClass ()
Definition at line 397 of file DuplicateImages.cpp.
Referenced by KKMLL::DuplicateImages::ListOfExamplesToDelete(), and KKMLL::DuplicateImages::PurgeDuplicates().
{
  bool allTheSameClass = true;
  
  MLClassPtr mlClass = duplicatedImages.IdxToPtr (0)->MLClass ();
  FeatureVectorList::iterator iIDX = duplicatedImages.begin ();
  while ((iIDX != duplicatedImages.end ()) && (allTheSameClass))
  {
    allTheSameClass = (*iIDX)->MLClass () == mlClass;
    iIDX++;
  }
  return allTheSameClass;
} /* AllTheSameClass */
bool DuplicateImage::AlreadyHaveExample (FeatureVectorPtr example)
Definition at line 418 of file DuplicateImages.cpp.
Referenced by KKMLL::DuplicateImageList::LocateByImage().
{
  return (duplicatedImages.PtrToIdx (example) >= 0);
}
const FeatureVectorListPtr KKMLL::DuplicateImage::DuplicatedImages () [inline]
Definition at line 142 of file DuplicateImages.h.
Referenced by KKMLL::DuplicateImages::ListOfExamplesToDelete(), and KKMLL::DuplicateImages::PurgeDuplicates().
{return &duplicatedImages;}
FeatureVectorPtr DuplicateImage::ExampleWithSmallestScanLine ()
Definition at line 426 of file DuplicateImages.cpp.
References KKB::KKStr::Concat(), KKMLL::FeatureVector::ExampleFileName(), KKB::KKStr::LocateLastOccurrence(), KKB::KKStr::operator==(), KKB::osGetRootName(), KKB::KKStr::SubStrPart(), and KKB::KKStr::Upper().
Referenced by KKMLL::DuplicateImages::ListOfExamplesToDelete(), and KKMLL::DuplicateImages::PurgeDuplicates().
{
  kkint32 smallestScanLine = 99999999;
  FeatureVectorPtr imageWithSmallestScanLine = NULL;
  for (FeatureVectorList::iterator iIDX = duplicatedImages.begin (); iIDX !=
      duplicatedImages.end (); iIDX++)
  {
    FeatureVectorPtr i = *iIDX;
    // First lets derive scan line from example file name
   
    KKStr rootName = osGetRootName (i->ExampleFileName ());
    rootName.Upper ();
    kkint32 scanLine = 9999999;
    if (rootName.SubStrPart (0, 4) == "FRAME")
    {
      // Scan line will be last seq number in name.
      kkint32 x = rootName.LocateLastOccurrence ('_');
      if (x > 0)
      {
        KKStr scanLineStr = rootName.SubStrPart (x + 1);
        scanLine = atoi (scanLineStr.Str ());
      }
    }
    else
    {
      // Scan should be 2nd to last seq number in name.
      kkint32 x = rootName.LocateLastOccurrence ('_');
      if (x > 0)
      {
        KKStr workStr = rootName.SubStrPart (0, x - 1);
        kkint32 x = workStr.LocateLastOccurrence ('_');
        KKStr scanLineStr = workStr.SubStrPart (x + 1);
        scanLine = atoi (scanLineStr.Str ());
      }
    }
    if ((scanLine < smallestScanLine) ||
         (imageWithSmallestScanLine == NULL)
        )
    {
      smallestScanLine = scanLine;
      imageWithSmallestScanLine = i;
    }
  }
  return imageWithSmallestScanLine;
} /* ImageWithSmallestScalLine */
FeatureVectorPtr KKMLL::DuplicateImage::FirstExampleAdded () [inline]
Definition at line 144 of file DuplicateImages.h.
{return firstImageAdded;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/DuplicateImages.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/DuplicateImages.cpp