KKB::XmlElement Class Reference
#include <XmlStream.h>
Public Types
typedef XmlElement * XmlElementPtr
Public Member Functions
XmlElement (const KKStr &sectionName, XmlTag::TagTypes tagType)
XmlElement (XmlTagPtr _nameTag, XmlStream &s, RunLog &log)
virtual ~XmlElement ()
KKStrConstPtr AttributeValue (const char *attributeName)
KKStrConstPtr AttributeValue (const KKStr &attributeName)
XmlTagConstPtr NameTag () const
KKStr NameTagStr () const
virtual const KKStr & SectionName () const
virtual bool ToBool () const
virtual double ToDouble () const
virtual float ToFloat () const
virtual kkint32 ToInt32 () const
virtual TokenTypes TokenType ()
virtual KKStr ToKKStr () const
virtual const KKStr & VarName () const
Detailed Description
Definition at line 283 of file XmlStream.h.
Member Typedef Documentation
typedef XmlElement* KKB::XmlElement::XmlElementPtr
Definition at line 286 of file XmlStream.h.
Constructor & Destructor Documentation
XmlElement::XmlElement (const KKStr & sectionName, XmlTag::TagTypes tagType)
Definition at line 750 of file XmlStream.cpp.
References KKB::XmlTag::XmlTag().
Referenced by KKB::XmlElementKeyValuePairs::XmlElementKeyValuePairs().
                        :
  nameTag (new XmlTag (sectionName, tagType))
{}
XmlElement::XmlElement (XmlTagPtr _nameTag, XmlStream & s, RunLog & log)
Definition at line 758 of file XmlStream.cpp.
Referenced by KKB::XmlElementArrayFloat2DVarying::XmlElementArrayFloat2DVarying(), KKB::XmlElementBool::XmlElementBool(), KKB::XmlElementDateTime::XmlElementDateTime(), KKMLL::XmlElementFileDesc::XmlElementFileDesc(), KKB::XmlElementKeyValuePairs::XmlElementKeyValuePairs(), KKMLL::XmlElementMLClass::XmlElementMLClass(), KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList(), KKMLL::XmlElementModel::XmlElementModel(), KKMLL::XmlElementModelParam::XmlElementModelParam(), and KKB::XmlElementUnKnown::XmlElementUnKnown().
                        :
  nameTag (_nameTag)
{}
XmlElement::~XmlElement () [virtual]
Definition at line 767 of file XmlStream.cpp.
{
  delete nameTag;
  nameTag = NULL;
}
Member Function Documentation
KKStrConstPtr XmlElement::AttributeValue (const char * attributeName)
Definition at line 818 of file XmlStream.cpp.
References KKB::XmlTag::AttributeValueByName().
{
  if (nameTag)
    return nameTag->AttributeValueByName (attributeName);
  else
    return NULL;
}
KKStrConstPtr XmlElement::AttributeValue (const KKStr & attributeName)
Definition at line 809 of file XmlStream.cpp.
References KKB::XmlTag::AttributeValueByName().
{
  if (nameTag)
    return nameTag->AttributeValueByName (attributeName);
  else
    return NULL;
}
XmlTagConstPtr KKB::XmlElement::NameTag () const [inline]
Definition at line 299 of file XmlStream.h.
{return nameTag;}
KKStr XmlElement::NameTagStr () const
The initial start tag with its attributes that started the element.
Definition at line 775 of file XmlStream.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), and KKB::XmlTag::ToString().
{
  if (!nameTag)
    return KKStr::EmptyStr ();
  else
    return nameTag->ToString ();
}
const KKStr & XmlElement::SectionName () const [virtual]
If derived class is from the XmlElement family will be the name from the StartTag(XmlTag::Name ()) otherwise KKStr::EmptyStr()
Reimplemented from KKB::XmlToken.
Definition at line 785 of file XmlStream.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), and KKB::XmlTag::Name().
Referenced by KKMLL::NormalizationParms::ReadXML(), SVM233::SvmModel233::ReadXML(), KKMLL::ModelDual::ReadXML(), KKMLL::FileDesc::ReadXML(), and KKMLL::TrainingProcess2::ReadXML().
{
  if (nameTag)
    return nameTag->Name ();
  else
    return KKStr::EmptyStr ();
}
virtual bool KKB::XmlElement::ToBool () const [inline], [virtual]
Reimplemented in KKB::XmlElementDouble, KKB::XmlElementFloat, KKB::XmlElementInt64, KKB::XmlElementInt32, KKB::XmlElementKKStr, KKB::XmlElementDateTime, and KKB::XmlElementBool.
Definition at line 313 of file XmlStream.h.
Referenced by KKMLL::NormalizationParms::ReadXML(), KKMLL::TrainingProcess2::ReadXML(), and KKMLL::ModelParam::ReadXMLModelParamToken().
{return false;}
virtual double KKB::XmlElement::ToDouble () const [inline], [virtual]
Reimplemented in KKB::XmlElementDouble, KKB::XmlElementFloat, KKB::XmlElementInt64, KKB::XmlElementInt32, KKB::XmlElementKKStr, KKB::XmlElementDateTime, and KKB::XmlElementBool.
Definition at line 315 of file XmlStream.h.
Referenced by KKMLL::FeatureEncoder::ReadXML().
{return 0.0;}
virtual float KKB::XmlElement::ToFloat () const [inline], [virtual]
Reimplemented in KKB::XmlElementDouble, KKB::XmlElementFloat, KKB::XmlElementInt64, KKB::XmlElementInt32, KKB::XmlElementKKStr, KKB::XmlElementDateTime, and KKB::XmlElementBool.
Definition at line 316 of file XmlStream.h.
Referenced by KKMLL::NormalizationParms::ReadXML().
{return 0.0f;}
virtual kkint32 KKB::XmlElement::ToInt32 () const [inline], [virtual]
Reimplemented in KKB::XmlElementDouble, KKB::XmlElementFloat, KKB::XmlElementInt64, KKB::XmlElementInt32, KKB::XmlElementKKStr, KKB::XmlElementDateTime, and KKB::XmlElementBool.
Definition at line 317 of file XmlStream.h.
Referenced by KKMLL::NormalizationParms::ReadXML(), KKMLL::FeatureEncoder::ReadXML(), SVM233::SvmModel233::ReadXML(), and KKMLL::ModelParam::ReadXMLModelParamToken().
{return 0;}
virtual TokenTypes KKB::XmlElement::TokenType () [inline], [virtual]
Implements KKB::XmlToken.
Definition at line 305 of file XmlStream.h.
References KKB::XmlToken::tokElement.
{return TokenTypes::tokElement;}
virtual KKStr KKB::XmlElement::ToKKStr () const [inline], [virtual]
Reimplemented in KKB::XmlElementDouble, KKB::XmlElementFloat, KKB::XmlElementInt64, KKB::XmlElementInt32, KKB::XmlElementKKStr, KKB::XmlElementDateTime, and KKB::XmlElementBool.
Definition at line 314 of file XmlStream.h.
References KKB::XmlTag::ToString().
Referenced by KKMLL::FeatureEncoder::ReadXML(), KKMLL::ModelParamOldSVM::ReadXML(), KKMLL::TrainingProcess2::ReadXML(), KKMLL::ModelParam::ReadXMLModelParamToken(), and KKMLL::Model::ReadXMLModelToken().
{return nameTag->ToString ();}
const KKStr & XmlElement::VarName () const [virtual]
If the derived class is form the 'XmlElement' line will return the 'VarName' from that derived class otherwise it will return back a empty string.
Reimplemented from KKB::XmlToken.
Definition at line 794 of file XmlStream.cpp.
References KKB::XmlTag::AttributeValueByName(), KKB::KKStr::Concat(), and KKB::KKStr::EmptyStr().
Referenced by KKMLL::ModelParamUsfCasCor::ReadXML(), KKMLL::NormalizationParms::ReadXML(), KKMLL::FeatureEncoder::ReadXML(), KKMLL::TrainingClassList::ReadXML(), SVM233::SvmModel233::ReadXML(), KKMLL::ModelDual::ReadXML(), KKMLL::FileDesc::ReadXML(), KKMLL::SVMModel::ReadXML(), KKMLL::TrainingProcess2::ReadXML(), KKMLL::TrainingConfiguration2::ReadXMLBaseToken(), and KKMLL::Model::ReadXMLModelToken().
{
  if (!nameTag)
    return KKStr::EmptyStr ();
  KKStrConstPtr nameStr = nameTag->AttributeValueByName ("VarName");
  if (nameStr)
    return *nameStr;
  else
    return KKStr::EmptyStr ();
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp