KKLSC::ScannerHeaderFields Class Reference
Represents a list of header fields from a Scanner File.
#include <ScannerHeaderFields.h>
Public Types
typedef map< KKStr, KKStr >::iterator iterator
typedef ScannerHeaderFields * ScannerHeaderFieldsPtr
Public Member Functions
ScannerHeaderFields ()
ScannerHeaderFields (const ScannerHeaderFields &fields)
~ScannerHeaderFields ()
void Add (ScannerHeaderFieldsPtr fields)
void Add (const KKB::KKStr &fieldName, const KKB::KKStr &fieldValue)
void Add (const KKB::KKStr &fieldName, bool fieldValue)
void Add (const KKStr &fieldName, kkint32 fieldValue)
void Add (const KKStr &fieldName, kkint64 fieldValue)
void Add (const KKStr &fieldName, double fieldValue)
void Add (const KKStr &fieldName, KKB::DateTime fieldValue)
void Clear ()
void EndBlock ()
bool FieldExists (const KKStr &fieldName) const
const KKStr & GetValue (const KKStr &fieldName) const
float GetValueFloat (const KKStr &fieldName) const
kkint32 GetValueInt32 (const KKStr &fieldName) const
kkint32 MemoryConsumedEstimated ()
void StartBlock ()
Detailed Description
Represents a list of header fields from a Scanner File.
All ScannerFiles will start with a Header section that consists of text with each line consisting of a `FieldName` allowed by a `FieldValue` separated by the tab character.
Definition at line 17 of file ScannerHeaderFields.h.
Member Typedef Documentation
typedef map<KKStr,KKStr>::iterator KKLSC::ScannerHeaderFields::iterator
Definition at line 69 of file ScannerHeaderFields.h.
typedef ScannerHeaderFields* KKLSC::ScannerHeaderFields::ScannerHeaderFieldsPtr
Definition at line 20 of file ScannerHeaderFields.h.
Constructor & Destructor Documentation
ScannerHeaderFields::ScannerHeaderFields ()
Definition at line 25 of file ScannerHeaderFields.cpp.
References KKB::GoalKeeper::Create(), and ScannerHeaderFields().
Referenced by KKLSC::ScannerFile::AddHeaderField(), KKLSC::ScannerFile::ReadHeader(), and ScannerHeaderFields().
                                         :
  map<KKStr,KKStr> (),
  goalie (NULL)
{
  GoalKeeper::Create ("ScannerHeaderFields", goalie);
}
ScannerHeaderFields::ScannerHeaderFields (const ScannerHeaderFields & fields)
Definition at line 34 of file ScannerHeaderFields.cpp.
References KKB::GoalKeeper::Create(), and ScannerHeaderFields().
Referenced by KKLSC::ScannerFile::GetScannerFileParameters(), and ScannerHeaderFields().
                                                                           :
  map<KKStr,KKStr> (),
  goalie (NULL)
{
  GoalKeeper::Create ("ScannerHeaderFields", goalie);
  ScannerHeaderFields::const_iterator idx;
  for (idx = fields.begin (); idx != fields.end (); ++idx)
    Add (idx->first, idx->second);
}
ScannerHeaderFields::~ScannerHeaderFields ()
Definition at line 46 of file ScannerHeaderFields.cpp.
References KKB::GoalKeeper::Destroy().
{
  GoalKeeper::Destroy (goalie);
  goalie = NULL;
}
Member Function Documentation
void ScannerHeaderFields::Add (ScannerHeaderFieldsPtr fields)
Definition at line 74 of file ScannerHeaderFields.cpp.
{
  if (!fields)
    return;
  ScannerHeaderFields::const_iterator idx;
  for (idx = fields->begin (); idx != fields->end (); ++idx)
    Add (idx->first, idx->second);
}
void ScannerHeaderFields::Add (const KKB::KKStr & fieldName, const KKB::KKStr & fieldValue)
Definition at line 85 of file ScannerHeaderFields.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by Add(), KKLSC::ScannerFile::AddHeaderField(), and KKLSC::ScannerFile::ReadHeader().
{
  goalie->StartBlock ();
  
  idx1 = this->find (fieldName);
  if (idx1 == end ())
    insert (pair<KKStr,KKStr>(fieldName, fieldValue));
  else
    idx1->second = fieldValue;
  goalie->EndBlock ();
}
void ScannerHeaderFields::Add (const KKB::KKStr & fieldName, bool fieldValue)
Definition at line 101 of file ScannerHeaderFields.cpp.
References Add(), and KKB::KKStr::Concat().
{
  KKStr fieldValueStr = (fieldValue ? "Yes" : "No");
  Add (fieldName, fieldValueStr);
}
void KKLSC::ScannerHeaderFields::Add (const KKStr & fieldName, kkint32 fieldValue)
void KKLSC::ScannerHeaderFields::Add (const KKStr & fieldName, kkint64 fieldValue)
void KKLSC::ScannerHeaderFields::Add (const KKStr & fieldName, double fieldValue)
void KKLSC::ScannerHeaderFields::Add (const KKStr & fieldName, KKB::DateTime fieldValue)
void ScannerHeaderFields::Clear ()
Erases contents
Definition at line 154 of file ScannerHeaderFields.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
{
  goalie->StartBlock ();
  clear ();
  goalie->EndBlock ();
}
void ScannerHeaderFields::EndBlock ()
Definition at line 216 of file ScannerHeaderFields.cpp.
References KKB::GoalKeeper::EndBlock().
Referenced by KKLSC::ScannerFile::AddHeaderFields().
{
  goalie->EndBlock ();
}
bool ScannerHeaderFields::FieldExists (const KKStr & fieldName) const
Definition at line 163 of file ScannerHeaderFields.cpp.
References KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
{
  bool exists = false;
  goalie->StartBlock ();
  idx2 = this->find (fieldName);
  exists = (idx2 != end ());
  goalie->EndBlock ();
  return exists;
}
const KKStr & ScannerHeaderFields::GetValue (const KKStr & fieldName) const
Definition at line 175 of file ScannerHeaderFields.cpp.
References KKB::KKStr::Concat(), KKB::GoalKeeper::EndBlock(), and KKB::GoalKeeper::StartBlock().
Referenced by KKLSC::ScannerFile::GetValue(), GetValueFloat(), and GetValueInt32().
{
  const KKStr* value = NULL;
  goalie->StartBlock ();
  idx2 = this->find (fieldName);
  if (idx2 == end ())
    value = &(KKStr::EmptyStr ());
  else
    value = &(idx2->second);
  goalie->EndBlock ();
  return *value;
}
float ScannerHeaderFields::GetValueFloat (const KKStr & fieldName) const
Definition at line 192 of file ScannerHeaderFields.cpp.
References KKB::KKStr::Concat(), GetValue(), and KKB::KKStr::ToFloat().
Referenced by KKLSC::ScannerFile::GetValueFloat().
{
  KKStr s = GetValue (fieldName);
  return s.ToFloat ();
}
kkint32 ScannerHeaderFields::GetValueInt32 (const KKStr & fieldName) const
Definition at line 200 of file ScannerHeaderFields.cpp.
References KKB::KKStr::Concat(), GetValue(), and KKB::KKStr::ToInt32().
{
  KKStr s = GetValue (fieldName);
  return s.ToInt32 ();
}
kkint32 ScannerHeaderFields::MemoryConsumedEstimated ()
Definition at line 54 of file ScannerHeaderFields.cpp.
References KKB::GoalKeeper::EndBlock(), KKB::GoalKeeper::MemoryConsumedEstimated(), and KKB::GoalKeeper::StartBlock().
Referenced by KKLSC::ScannerFile::MemoryConsumedEstimated().
{
  goalie->StartBlock ();
  kkint32 mem = sizeof (*this);
  if (goalie) mem += goalie->MemoryConsumedEstimated ();
  
  for (idx2 = begin (); idx2 != end (); ++idx2)
  {
    mem = mem + (idx2->first.MemoryConsumedEstimated () + idx2->second.MemoryConsumedEstimated ());
  }
  goalie->EndBlock ();
  return mem;
}
void ScannerHeaderFields::StartBlock ()
Definition at line 209 of file ScannerHeaderFields.cpp.
References KKB::GoalKeeper::StartBlock().
Referenced by KKLSC::ScannerFile::AddHeaderFields().
{
  goalie->StartBlock ();
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerHeaderFields.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerHeaderFields.cpp