KKB::BlobList Class Reference
Maintains a list of blobs.
#include <Blob.h>
Public Member Functions
BlobList (bool _owner)
~BlobList ()
void DeleteEntry (BlobPtr b)
BlobPtr LocateLargestBlob ()
Will return Blob with largest pixel count.
BlobPtr LocateMostComplete ()
Locates the blob that covers the greatest part of the raster; that is the one who has the largest (Height x Width)
BlobPtr LookUpByBlobId (kkint32 blobId)
Will return pointer to blob with 'blobId'; if not found will return NULL.
void MergeBlobIds (BlobPtr blob, kkint32 blobId, kkint32 **blobIds)
Used by the Connected component analysis to merge two blobs together.
BlobPtr MergeIntoSingleBlob (BlobPtr blob1, kkint32 blob2Id, kkint32 **blobIds)
BlobPtr NewBlob (kkuint32 rowTop, kkuint32 colLeft)
void PushOnBack (BlobPtr blob)
void PushOnFront (BlobPtr blob)
Detailed Description
Maintains a list of blobs.
Definition at line 77 of file Blob.h.
Constructor & Destructor Documentation
BlobList::BlobList (bool _owner)
Definition at line 64 of file Blob.cpp.
References BlobList().
Referenced by BlobList(), KKB::Raster::ConnectedComponent8Conected(), and KKB::Raster::ExtractBlobs().
                               :
  availableBlobs (),
  nextBlobId (0)
{
}
BlobList::~BlobList ()
Definition at line 72 of file Blob.cpp.
{
  while (availableBlobs.size () > 0)
  {
    BlobPtr b = availableBlobs.back ();
    availableBlobs.pop_back ();
    delete b;
  }
  iterator idx2;
  iterator endIdx = end ();
  for (idx2 = begin (); idx2 != endIdx; ++idx2)
  {
    BlobPtr b = idx2->second;
    delete b;
  }
}
Member Function Documentation
void KKB::BlobList::DeleteEntry (BlobPtr b)
BlobPtr BlobList::LocateLargestBlob ()
Will return Blob with largest pixel count.
Definition at line 230 of file Blob.cpp.
References KKB::Blob::pixelCount.
Referenced by KKB::Raster::ConnectedComponent(), and KKB::Raster::ConnectedComponent8Conected().
{
  BlobPtr blob = NULL;
  BlobPtr tempBlob = NULL;
  kkint32 largestSize = 0;
  const_iterator idx;
  const_iterator endIdx = end ();
  for (idx = begin (); idx != endIdx; ++idx)
  {
    tempBlob = idx->second;
    if (tempBlob->pixelCount > largestSize)
    {
      largestSize = tempBlob->pixelCount;
      blob = tempBlob;
    }
  }
  return blob;
} /* LocateLargestBlob */
BlobPtr BlobList::LocateMostComplete ()
Locates the blob that covers the greatest part of the raster; that is the one who has the largest (Height x Width)
Definition at line 253 of file Blob.cpp.
References KKB::Blob::Height(), and KKB::Blob::Width().
Referenced by KKB::Raster::ReduceToMostCompleteBlob().
{
  BlobPtr blob = NULL;
  BlobPtr tempBlob = NULL;
  kkint32 largestSize = 0;
  const_iterator idx;
  const_iterator endIdx = end ();
  for (idx = begin (); idx != endIdx; ++idx)
  {
    tempBlob = idx->second;
    kkint32 size = tempBlob->Height () * tempBlob->Width ();
    if (size > largestSize)
    {
      largestSize = size;
      blob = tempBlob;
    }
  }
  return blob;
} /* LocateMostComplete */
BlobPtr BlobList::LookUpByBlobId (kkint32 blobId)
Will return pointer to blob with 'blobId'; if not found will return NULL.
Definition at line 53 of file Blob.cpp.
Referenced by KKB::Raster::ConnectedComponent8Conected(), and KKB::Raster::ExtractBlobs().
{
  const_iterator idx;
  idx = find (blobId);
  if (idx == end ())
    return NULL;
  return idx->second;
} /* LookUpByBlobId */
void BlobList::MergeBlobIds (BlobPtr blob, kkint32 blobId, kkint32 ** blobIds)
Used by the Connected component analysis to merge two blobs together.
When the connected component discovers that two separate blobs are actually connected if will call this method to merge them together into a single blob.
Definition at line 122 of file Blob.cpp.
References KKB::Blob::colLeft, KKB::Blob::colRight, KKB::Blob::Id(), KKB::Blob::pixelCount, KKB::Blob::rowBot, and KKB::Blob::rowTop.
Referenced by KKB::Raster::ConnectedComponent8Conected().
{
  kkint32 newId = blob->Id ();
  
  iterator idx;
  idx = find (blobId);
  if (idx == end ())
    return;
  BlobPtr blobToMerge = idx->second;
  kkint32 col;
  kkint32 row;
  kkint32 rowBot = blobToMerge->rowBot;
  kkint32 colRight = blobToMerge->colRight;
  for (row = blobToMerge->rowTop; row <= rowBot; row++)
  {
    for (col = blobToMerge->colLeft; col <= colRight; col++)
    {
      if (blobIds[row][col] == blobId)
        blobIds[row][col] = newId;
    }
  }
  blob->rowTop = Min (blob->rowTop, blobToMerge->rowTop);
  blob->rowBot = Max (blob->rowBot, blobToMerge->rowBot);
  blob->colLeft = Min (blob->colLeft, blobToMerge->colLeft);
  blob->colRight = Max (blob->colRight, blobToMerge->colRight);
  blob->pixelCount = blob->pixelCount + blobToMerge->
      pixelCount;
  erase (idx);
  availableBlobs.push_back (blobToMerge);
} /* MergeBlobIds */
BlobPtr BlobList::MergeIntoSingleBlob (BlobPtr blob1, kkint32 blob2Id, kkint32 ** blobIds)
Definition at line 163 of file Blob.cpp.
References KKB::Blob::colLeft, KKB::Blob::colRight, KKB::Blob::Id(), KKB::Blob::PixelCount(), KKB::Blob::pixelCount, KKB::Blob::rowBot, and KKB::Blob::rowTop.
Referenced by KKB::Raster::ExtractBlobs().
{
  kkint32 blob1Id = blob1->Id ();
  iterator idx;
  idx = find (blob2Id);
  if (idx == end ())
    return blob1;
  BlobPtr blob2 = idx->second;
  if ((blob1Id == blob2Id) || (blob1 == blob2))
  {
    return blob1;
  }
  BlobPtr srcBlob = NULL;
  BlobPtr destBlob = NULL;
  if (blob1->PixelCount () > blob2->PixelCount ())
  {
    srcBlob = blob2;
    destBlob = blob1;
  }
  else
  {
    srcBlob = blob1;
    destBlob = blob2;
  }
  kkint32 destBlobId = destBlob->Id ();
  kkint32 srcBlobId = srcBlob->Id ();
  kkint32 col = 0;
  kkint32 row = 0;
  kkint32 rowBot = srcBlob->rowBot;
  kkint32 colRight = srcBlob->colRight;
  for (row = srcBlob->rowTop; row <= rowBot; ++row)
  {
    for (col = srcBlob->colLeft; col <= colRight; ++col)
    {
      if (blobIds[row][col] == srcBlobId)
        blobIds[row][col] = destBlobId;
    }
  }
  destBlob->rowTop = Min (destBlob->rowTop, srcBlob->rowTop);
  destBlob->rowBot = Max (destBlob->rowBot, srcBlob->rowBot);
  destBlob->colLeft = Min (destBlob->colLeft, srcBlob->
      colLeft);
  destBlob->colRight = Max (destBlob->colRight, srcBlob->
      colRight);
  destBlob->pixelCount = destBlob->pixelCount + srcBlob->
      pixelCount;
  idx = find (srcBlobId);
  if (idx != end ())
    erase (idx);
  availableBlobs.push_back (srcBlob);
  return destBlob;
} /* MergeIntoSingleBlob */
BlobPtr BlobList::NewBlob (kkuint32 rowTop, kkuint32 colLeft)
Definition at line 93 of file Blob.cpp.
References KKB::Blob::colLeft, KKB::Blob::colRight, PushOnBack(), KKB::Blob::rowBot, and KKB::Blob::rowTop.
Referenced by KKB::Raster::ConnectedComponent8Conected(), and KKB::Raster::ExtractBlobs().
{
  BlobPtr blob = NULL;
  if (availableBlobs.size () > 0)
  {
    blob = availableBlobs.back ();
    blob->InitialzieAsNew (nextBlobId);
    availableBlobs.pop_back ();
  }
  else
  {
    blob = new Blob (nextBlobId);
  }
  
  blob->rowTop = rowTop;
  blob->rowBot = rowTop;
  blob->colLeft = colLeft;
  blob->colRight = colLeft;
  
  nextBlobId++;
  PushOnBack (blob);
  return blob;
}
void BlobList::PushOnBack (BlobPtr blob)
Definition at line 280 of file Blob.cpp.
Referenced by NewBlob().
{
  insert (BlobIndexPair (blob->Id (), blob));
} /* PushOnBack */
void BlobList::PushOnFront (BlobPtr blob)
Definition at line 287 of file Blob.cpp.
{
  insert (BlobIndexPair (blob->Id (), blob));
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Blob.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Blob.cpp