KKMLL::SVMModel Class Reference
#include <SVMModel.h>
Public Member Functions
SVMModel ()
Default constructor used by XmlElementSVMModel to create and load a new instance from a XML Stream.
SVMModel (const SVMparam &_svmParam, FeatureVectorList &_examples, ClassAssignments &_assignments, FileDescPtr _fileDesc, RunLog &_log)
Constructor that will create a svmlib training model using the features and classes for training purposes.
virtual ~SVMModel ()
Frees any memory allocated by, and owned by the SVMModel.
const ClassAssignments & Assignments () const
virtual void CancelFlag (bool _cancelFlag)
double DistanceFromDecisionBoundary (FeatureVectorPtr example, MLClassPtr class1, MLClassPtr class2)
std::vector< ProbNamePair > FindWorstSupportVectors (FeatureVectorPtr example, kkint32 numToFind, MLClassPtr c1, MLClassPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
std::vector< ProbNamePair > FindWorstSupportVectors2 (FeatureVectorPtr example, kkint32 numToFind, MLClassPtr c1, MLClassPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
FeatureNumListConstPtr GetFeatureNums () const
FeatureNumListConstPtr GetFeatureNums (FileDescPtr fileDesc) const
FeatureNumListConstPtr GetFeatureNums (FileDescPtr fileDesc, MLClassPtr class1, MLClassPtr class2) const
kkint32 MemoryConsumedEstimated () const
virtual bool NormalizeNominalAttributes ()
kkint32 NumOfClasses () const
kkint32 NumOfSupportVectors () const
MLClassPtr Predict (FeatureVectorPtr example)
void Predict (FeatureVectorPtr example, MLClassPtr knownClass, MLClassPtr &predClass1, MLClassPtr &predClass2, kkint32 &predClass1Votes, kkint32 &predClass2Votes, double &probOfKnownClass, double &predClass1Prob, double &predClass2Prob, kkint32 &numOfWinners, bool &knownClassOneOfTheWinners, double &breakTie)
Will predict the two most likely classes of 'example'.
void PredictRaw (FeatureVectorPtr example, MLClassPtr &predClass, double &dist)
Returns the distance from the decision border of the SVM.
void ProbabilitiesByClass (FeatureVectorPtr example, const MLClassList &_mlClasses, kkint32 *_votes, double *_probabilities, RunLog &_log)
Will get the probabilities assigned to each class.
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
void RetrieveCrossProbTable (MLClassList &classes, double **crossProbTable, RunLog &log)
Will return the probabilities for all pairs of the classes listed in 'classes'.
const KKStr & RootFileName () const
SVM_SelectionMethod SelectionMethod () const
std::vector< KKStr > SupportVectorNames () const
std::vector< KKStr > SupportVectorNames (MLClassPtr c1, MLClassPtr c2) const
void SupportVectorStatistics (kkint32 &numSVs, kkint32 &totalNumSVs)
SVMparam const * SVMParameters () const
double TrainingTime () const
bool ValidModel () const
virtual void WriteXML (const KKStr &varName, std::ostream &o) const
Detailed Description
Definition at line 77 of file SVMModel.h.
Constructor & Destructor Documentation
SVMModel::SVMModel ()
Default constructor used by XmlElementSVMModel to create and load a new instance from a XML Stream.
Definition at line 169 of file SVMModel.cpp.
References KKMLL::AttributeTypeVector::AttributeTypeVector(), KKMLL::ClassAssignments::ClassAssignments(), KKB::KKStr::KKStr(), and KKMLL::SVMparam::SVMparam().
                   :
  assignments (),
  binaryFeatureEncoders (NULL),
  binaryParameters (NULL),
  cardinality_table (),
  cancelFlag (false),
  classIdxTable (NULL),
  crossClassProbTable (NULL),
  crossClassProbTableSize (0),
  featureEncoder (NULL),
  fileDesc (NULL),
  models (NULL),
  numOfClasses (0),
  numOfModels (0),
  oneVsAllAssignment (),
  oneVsAllClassAssignments (NULL),
  predictXSpace (NULL),
  predictXSpaceWorstCase (0),
  probabilities (NULL),
  rootFileName (),
  selectedFeatures (NULL),
  svmParam (NULL),
  trainingTime (0.0),
  type_table (),
  validModel (true),
  votes (NULL),
  xSpaces (NULL),
  xSpacesTotalAllocated (0)
{
  svmParam = new SVMparam ();
}
SVMModel::SVMModel (const SVMparam & _svmParam, FeatureVectorList & _examples, ClassAssignments & _assignments, FileDescPtr _fileDesc, RunLog & _log)
Constructor that will create a svmlib training model using the features and classes for training purposes.
Parameters
in _svmParam Specifies the parameters to be used for training. These are the same parameters that you would specify in the command line to svm_train. Plus the feature numbers to be used.
in _examples Training data for the classifier.
in _assignments List of classes and there associated number ti be used by the SVM. You can merge 1 or more classes by assigning them the same number. This number will be used by the SVM. When predictions are done by SVM it return a number, _assignments will then be used to map back-to the correct class.
in _fileDesc File-Description that describes the training data.
out _log Log file to log messages to.
Definition at line 203 of file SVMModel.cpp.
References KKMLL::AttributeTypeVector::AttributeTypeVector(), KKMLL::BinaryCombos, KKMLL::FileDesc::CreateAttributeTypeTable(), KKMLL::FileDesc::CreateCardinalityTable(), KKB::KKStr::KKStr(), KKMLL::SVMparam::MachineType(), KKMLL::OneVsAll, KKMLL::OneVsOne, KKMLL::SVMparam::SelectedFeatures(), and KKMLL::SVMparam::SVMparam().
Referenced by KKMLL::ModelOldSVM::TrainModel().
:
  assignments (_assignmnets),
  binaryFeatureEncoders (NULL),
  binaryParameters (NULL),
  cancelFlag (false),
  cardinality_table (),
  classIdxTable (NULL),
  crossClassProbTable (NULL),
  crossClassProbTableSize (0),
  featureEncoder (NULL),
  fileDesc (_fileDesc),
  models (NULL),
  numOfClasses (0),
  numOfModels (0),
  oneVsAllAssignment (),
  oneVsAllClassAssignments (NULL),
  predictXSpace (NULL),
  predictXSpaceWorstCase (0),
  probabilities (NULL),
  rootFileName (),
  selectedFeatures (NULL),
  svmParam (new SVMparam (_svmParam)),
  trainingTime (0.0),
  type_table (),
  validModel (true),
  votes (NULL),
  xSpaces (NULL),
  xSpacesTotalAllocated (0)
{
  if (_examples.QueueSize () < 2)
  {
    _log.Level (-1) << endl
                    << "SVMModel **** ERROR **** NO EXAMPLES TO TRAIN WITH." <<
      endl
                    << endl;
    validModel = false;
    return;
  }
  SetSelectedFeatures (_svmParam.SelectedFeatures (), _log);
  type_table = fileDesc->CreateAttributeTypeTable ();
  cardinality_table = fileDesc->CreateCardinalityTable ();
  
  struct svm_problem prob;
  numOfClasses = (kkint32)assignments.size ();
  _log.Level (20) << "SVMModel::SVMModel - Constructing From Training Data." <<
      endl;
  try
  {
    if (svmParam->MachineType () == SVM_MachineType::OneVsOne)
    {
      ConstructOneVsOneModel (&_examples, prob, _log);
    }
    else if (svmParam->MachineType () == SVM_MachineType::OneVsAll)
    {
      ConstructOneVsAllModel (&_examples, prob, _log);
    }
    else if (svmParam->MachineType () ==
      SVM_MachineType::BinaryCombos)
    {
      ConstructBinaryCombosModel (&_examples, _log);
    }
  }
  catch (const exception& e)
  {
    _log.Level (-1) << endl
      << "SVMModel ***ERROR*** Exception occurred constructing model." <<
      endl
      << e.what () << endl
      << endl;
    validModel = false;
  }
  catch (...)
  {
    _log.Level (-1) << endl
      << "SVMModel ***ERROR*** Exception occurred constructing model." <<
      endl
      << endl;
    validModel = false;
  }
  if (cancelFlag)
    validModel = false;
  if (!validModel)
    return;
  BuildClassIdxTable ();
  BuildCrossClassProbTable ();
}
SVMModel::~SVMModel () [virtual]
Frees any memory allocated by, and owned by the SVMModel.
Definition at line 303 of file SVMModel.cpp.
{
  kkint32 x;
  DeleteModels ();
  DeleteXSpaces ();
  if (oneVsAllClassAssignments)
  {
    for (kkint32 x = 0; x < numOfModels; x++)
    {
      if (oneVsAllClassAssignments[x])
      {
        delete oneVsAllClassAssignments[x];
        oneVsAllClassAssignments[x] = NULL;
      }
    }
    delete oneVsAllClassAssignments;
    oneVsAllClassAssignments = NULL;
  }
  delete featureEncoder; featureEncoder = NULL;
  if (binaryParameters)
  {
    // We don't own the binaryParametres them self, only the
    // array pointing to them, they are owned by svmParam.
    // so we don't want to delete the contents.
    delete[] binaryParameters;
    binaryParameters = NULL;
  }
  if (binaryFeatureEncoders)
  {
    for (x = 0; x < numOfModels; x++)
    {
      delete binaryFeatureEncoders[x];
      binaryFeatureEncoders[x] = NULL;
    }
    delete[] binaryFeatureEncoders;
    binaryFeatureEncoders = NULL;
  }
  if (crossClassProbTable)
  {
    for (x = 0; x < crossClassProbTableSize; x++)
    {
      delete [] crossClassProbTable[x];
      crossClassProbTable[x] = NULL;
    }
    delete[] crossClassProbTable;
    crossClassProbTable = NULL;
  }
  delete [] classIdxTable; classIdxTable = NULL;
  delete [] predictXSpace; predictXSpace = NULL;
  delete [] probabilities; probabilities = NULL;
  delete [] votes; votes = NULL;
  delete selectedFeatures; selectedFeatures = NULL;
  delete svmParam; svmParam = NULL;
}
Member Function Documentation
const ClassAssignments& KKMLL::SVMModel::Assignments () const [inline]
Definition at line 126 of file SVMModel.h.
Referenced by KKMLL::ModelOldSVM::Assignments().
{return assignments;}
void SVMModel::CancelFlag (bool _cancelFlag) [virtual]
Definition at line 515 of file SVMModel.cpp.
{
  cancelFlag = _cancelFlag;
}
double SVMModel::DistanceFromDecisionBoundary (FeatureVectorPtr example, MLClassPtr class1, MLClassPtr class2)
Definition at line 728 of file SVMModel.cpp.
References KKMLL::BinaryCombos, KKMLL::FeatureEncoder::Class1(), KKMLL::FeatureEncoder::Class2(), KKMLL::FeatureEncoder::EncodeAExample(), KKMLL::SVMparam::MachineType(), and SVM233::svm_predictTwoClasses().
{
  if (svmParam->MachineType () != SVM_MachineType::BinaryCombos)
  {
    cerr << endl << "SVMModel::DistanceFromDecisionBoundary ***ERROR*** This method only works
       with BinaryCombos." << endl << endl;
    return 0.0;
  }
  kkint32 modelIDX = 0;
  bool revClassOrder = false;
  FeatureEncoderPtr encoder = NULL;
  while (modelIDX < numOfModels)
  {
    encoder = binaryFeatureEncoders[modelIDX];
    if ((encoder->Class1 () == class1) && (encoder->Class2 () == class2))
    {
      revClassOrder = false;
      break;
    }
    else if ((encoder->Class1 () == class2) && (encoder->Class2 () == class1))
    {
      revClassOrder = true;
      break;
    }
    encoder = NULL;
    modelIDX++;
  }
  if (encoder == NULL)
  {
    return 0.0;
  }
  kkint32 xSpaceUsed;
  encoder->EncodeAExample (example, predictXSpace, xSpaceUsed);
  double distance = 0.0;
  svm_predictTwoClasses (models[modelIDX][0], predictXSpace, distance, -1);
  if (revClassOrder)
    distance = 0.0 - distance;
  return distance;
} /* DistanceFromDecisionBoundary */
vector< ProbNamePair > SVMModel::FindWorstSupportVectors (FeatureVectorPtr example, kkint32 numToFind, MLClassPtr c1, MLClassPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and re-compute the decision boundary and probability. It will then return the S/V's that when removed improve the probability in 'c1's the most.
Parameters
in example The Example that was classified incorrectly.
in numToFind The number of the worst examples you are looking for.
in c1 Class that the 'example; parameter should have been classed as.
in c2 Class that it was classified as.
Definition at line 1653 of file SVMModel.cpp.
References SVM233::svm_parameter::A, AdjProb(), KKMLL::BinaryClassParms::Class1(), KKMLL::BinaryClassParms::Class2(), KKB::KKStr::Concat(), KKMLL::FeatureEncoder::EncodeAExample(), KKB::KKException::KKException(), SVM233::SvmModel233::l, KKMLL::BinaryClassParms::Param(), SVM233::SvmModel233::SupportVectorName(), and SVM233::svm_predictTwoClasses().
{
  vector<ProbNamePair> results;
  if (svmParam->MachineType () != SVM_MachineType::BinaryCombos)
    return results;
  // Locate the binary parms in question.
  bool c1RevFlag = false;
  kkint32 modelIDX = 0;
  BinaryClassParmsPtr parms = NULL;
  for (modelIDX = 0; modelIDX < numOfModels; modelIDX++)
  {
    parms = binaryParameters[modelIDX];
    if ((parms->Class1 () == c1) && (parms->Class2 () == c2))
    {
      c1RevFlag = false;
      break;
    }
    else if ((parms->Class2 () == c1) && (parms->Class1 () == c2))
    {
      c1RevFlag = true;
      break;
    }
  }
  if (modelIDX >= numOfModels)
  {
    // Binary Combo not found.
    cerr << endl
         << "SVMModel::FindWorstSupportVectors ***ERROR*** Class1[" << c1->Name () << "] Class2[" << c2
      ->Name () << "] not part of model." << endl
         << endl;
    return results;
  }
  if (binaryFeatureEncoders[modelIDX] == NULL)
  {
    KKStr errMsg;
    errMsg << "SVMModel::FindWorstSupportVectors ***ERROR*** No feature encoder for model[" << modelIDX
       << "]";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  kkint32 xSpaceUsed;
  binaryFeatureEncoders[modelIDX]->EncodeAExample (example, predictXSpace, xSpaceUsed);
  kkint32 svIDX = 0;
  //kkint32 numSVs = models[modelIDX][0]->l;
  kkint32 numSVs = models[modelIDX][0]->l;
  double origProbabilityC1 = 0.0;
  double probabilityC1 = 0.0;
  double distance = 0.0;
  svm_predictTwoClasses (models[modelIDX][0], predictXSpace, distance, -1);
  origProbabilityC1 = ((1.0 / (1.0 + exp (-1.0 * (parms->Param ().A) * distance))));
  origProbabilityC1 = AdjProb (origProbabilityC1); // KAK 2011-06-10
  if (c1RevFlag)
    origProbabilityC1 = 1.0f - origProbabilityC1;
  vector<ProbNamePair> candidates;
  for (svIDX = 0; svIDX < numSVs; svIDX++)
  {
    svm_predictTwoClasses (models[modelIDX][0], predictXSpace, distance, svIDX);
    probabilityC1 = ((1.0 / (1.0 + exp (-1.0 * (parms->Param ().A) * distance))));
    probabilityC1 = AdjProb (probabilityC1); // KAK 2011-06-10
    if (c1RevFlag)
      probabilityC1 = 1.0f - probabilityC1;
    double deltaProb = probabilityC1 - origProbabilityC1;
    KKStr svName = models[modelIDX][0]->SupportVectorName (svIDX);
    candidates.push_back (ProbNamePair (svName, deltaProb));
  }
  sort (candidates.begin (), candidates.end (), PairCompareOperator);
  kkint32 zed = 0;
  for (zed = 0; (zed < (kkint32)candidates.size ()) && (zed < numToFind); zed++)
    results.push_back (candidates[zed]);
  return results;
} /* FindWorstSupportVectors */
vector< ProbNamePair > SVMModel::FindWorstSupportVectors2 (FeatureVectorPtr example, kkint32 numToFind, MLClassPtr c1, MLClassPtr c2)
For a given two class pair return the names of the 'numToFind' worst S/V's.
This method will iterate through all the S/V's removing them one at a time and retraining a new SVM and then comparing with the new prediction results.
Parameters
in example The Example that was classified incorrectly.
in numToFind The number of the worst examples you are looking for.
in c1 Class that the 'example; parameter should have been classed as.
in c2 Class that it was classified as.
Definition at line 1745 of file SVMModel.cpp.
References SVM233::svm_parameter::A, AdjProb(), KKMLL::BinaryClassParms::Class1(), KKMLL::BinaryClassParms::Class2(), KKB::KKStr::Concat(), KKMLL::FeatureEncoder::EncodeAExample(), KKB::KKException::KKException(), SVM233::SvmModel233::l, SVM233::svm_parameter::nr_class, KKMLL::BinaryClassParms::Param(), SVM233::SvmModel233::param, SVM233::SvmModel233::SupportVectorName(), SVM233::svm_BuildProbFromTwoClassModel(), SVM233::svm_predictTwoClasses(), and SVM233::svm_train().
{
  vector<ProbNamePair> results;
  if (svmParam->MachineType () != SVM_MachineType::BinaryCombos)
    return results;
  // Locate the binary parms in question.
  bool c1RevFlag = false;
  kkint32 modelIDX = 0;
  BinaryClassParmsPtr parms = NULL;
  for (modelIDX = 0; modelIDX < numOfModels; modelIDX++)
  {
    parms = binaryParameters[modelIDX];
    if ((parms->Class1 () == c1) && (parms->Class2 () == c2))
    {
      c1RevFlag = false;
      break;
    }
    else if ((parms->Class2 () == c1) && (parms->Class1 () == c2))
    {
      c1RevFlag = true;
      break;
    }
  }
  if (modelIDX >= numOfModels)
  {
    // Binary Combo not found.
    cerr << endl
         << "SVMModel::FindWorstSupportVectors ***ERROR*** Class1[" << c1->Name () << "] Class2[" << c2
      ->Name () << "] not part of model." << endl
         << endl;
    return results;
  }
  if (binaryFeatureEncoders[modelIDX] == NULL)
  {
    KKStr errMsg;
    errMsg << "SVMModel::FindWorstSupportVectors2 ***ERROR*** No feature encoder for model[" <<
      modelIDX << "]";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  kkint32 xSpaceUsed;
  binaryFeatureEncoders[modelIDX]->EncodeAExample (example, predictXSpace, xSpaceUsed);
  kkint32 svIDX = 0;
  //kkint32 numSVs = models[modelIDX][0]->l;
  kkint32 numSVs = models[modelIDX][0]->l;
  double origProbabilityC1 = 0.0;
  double probabilityC1 = 0.0;
  double distance = 0.0;
  svm_predictTwoClasses (models[modelIDX][0], predictXSpace, distance, -1);
  origProbabilityC1 = ((1.0 / (1.0 + exp (-1.0 * (parms->Param ().A) * distance))));
  origProbabilityC1 = AdjProb (origProbabilityC1);
  if (c1RevFlag)
    origProbabilityC1 = 1.0 - origProbabilityC1;
  vector<ProbNamePair> candidates;
  {
    svm_problem* subSetProb = svm_BuildProbFromTwoClassModel (
      models[modelIDX][0], -1);
    svm_parameter parameters = models[modelIDX][0]->param;
    parameters.nr_class = 2;
    SvmModel233* subSetModel = svm_train (subSetProb, &parameters);
    svm_predictTwoClasses (subSetModel, predictXSpace, distance, -1);
    probabilityC1 = ((1.0 / (1.0 + exp (-1.0 * (parms->Param ().A) * distance))));
    probabilityC1 = AdjProb (probabilityC1);
    if (c1RevFlag)
      probabilityC1 = 1.0f - probabilityC1;
    kkint32 zed = 100;
  }
  for (svIDX = 0; svIDX < numSVs; svIDX++)
  {
    svm_problem* subSetProb = svm_BuildProbFromTwoClassModel (
      models[modelIDX][0], svIDX);
    svm_parameter parameters = models[modelIDX][0]->param;
    parameters.nr_class = 2;
    SvmModel233* subSetModel = svm_train (subSetProb, &parameters);
    svm_predictTwoClasses (subSetModel, predictXSpace, distance, -1);
    probabilityC1 = ((1.0 / (1.0 + exp (-1.0 * (parms->Param ().A) * distance))));
    probabilityC1 = AdjProb (probabilityC1);
    if (c1RevFlag)
      probabilityC1 = 1.0f - probabilityC1;
    double deltaProb = probabilityC1 - origProbabilityC1;
    KKStr svName = models[modelIDX][0]->SupportVectorName (svIDX);
    candidates.push_back (ProbNamePair (svName, deltaProb));
    delete subSetModel; subSetModel = NULL;
    delete subSetProb; subSetProb = NULL;
  }
  sort (candidates.begin (), candidates.end (), PairCompareOperator);
  kkint32 zed = 0;
  for (zed = 0; (zed < (kkint32)candidates.size ()) && (zed < numToFind); zed++)
    results.push_back (candidates[zed]);
  return results;
} /* FindWorstSupportVectors2 */
FeatureNumListConstPtr SVMModel::GetFeatureNums () const
Definition at line 701 of file SVMModel.cpp.
References KKMLL::SVMparam::GetFeatureNums().
Referenced by KKMLL::ModelOldSVM::GetFeatureNums().
{
  return svmParam->GetFeatureNums ();
}
FeatureNumListConstPtr SVMModel::GetFeatureNums (FileDescPtr fileDesc) const
Definition at line 708 of file SVMModel.cpp.
References KKMLL::SVMparam::GetFeatureNums().
{
  return svmParam->GetFeatureNums (fileDesc);
}
FeatureNumListConstPtr SVMModel::GetFeatureNums (FileDescPtr fileDesc, MLClassPtr class1, MLClassPtr class2) const
Definition at line 715 of file SVMModel.cpp.
References KKMLL::SVMparam::GetFeatureNums().
Referenced by KKMLL::ModelOldSVM::GetFeatureNums().
{
  return svmParam->GetFeatureNums (fileDesc, class1, class2);
} /* GetFeatureNums */
kkint32 SVMModel::MemoryConsumedEstimated () const
Definition at line 437 of file SVMModel.cpp.
References KKMLL::ClassAssignments::MemoryConsumedEstimated(), KKMLL::FeatureEncoder::MemoryConsumedEstimated(), and SVM233::SvmModel233::MemoryConsumedEstimated().
Referenced by KKMLL::ModelOldSVM::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = sizeof (SVMModel)
       + assignments.MemoryConsumedEstimated ()
       + sizeof (kkint16) * oneVsAllAssignment.size ()
       + sizeof (kkint32) * cardinality_table.size ()
       + rootFileName.MemoryConsumedEstimated ()
       + svmParam->MemoryConsumedEstimated ()
       + sizeof (AttributeType) * type_table.size ();
  if (binaryFeatureEncoders)
  {
    memoryConsumedEstimated += sizeof (FeatureEncoderPtr) * numOfModels;
    for (kkint32 x = 0; x < numOfModels; x++)
    {
      if (binaryFeatureEncoders[x])
        memoryConsumedEstimated += binaryFeatureEncoders[x]->
      MemoryConsumedEstimated ();
    }
  }
  if (binaryParameters)
    memoryConsumedEstimated += numOfModels * sizeof (BinaryClassParmsPtr);
  if (classIdxTable)
    memoryConsumedEstimated += numOfClasses * sizeof (MLClassPtr);
  if (crossClassProbTable)
    memoryConsumedEstimated += crossClassProbTableSize * crossClassProbTableSize * sizeof (double);
  if (featureEncoder)
    memoryConsumedEstimated += featureEncoder->MemoryConsumedEstimated ();
  // fileDesc We do not own 'filedesc'.
  if (models)
  {
    memoryConsumedEstimated += numOfModels * sizeof (ModelPtr);
    for (kkint32 x = 0; x < numOfModels; ++x)
    {
      if (models[x])
      if (models[x][0])
       memoryConsumedEstimated += models[x][0]->MemoryConsumedEstimated ();
    }
  }
  if (oneVsAllClassAssignments)
  {
    memoryConsumedEstimated += numOfModels * sizeof (ClassAssignmentsPtr);
    for (kkint32 x = 0; x < numOfModels; ++x)
    {
      if (oneVsAllClassAssignments[x])
        memoryConsumedEstimated += oneVsAllClassAssignments[x]->
      MemoryConsumedEstimated ();
    }
  }
  if (predictXSpace)
     memoryConsumedEstimated += sizeof (svm_node) * predictXSpaceWorstCase;
  if (probabilities)
     memoryConsumedEstimated += sizeof (double) * numOfClasses;
  if (votes)
     memoryConsumedEstimated += sizeof (kkint32) * numOfClasses;
  if (xSpaces)
    memoryConsumedEstimated += xSpacesTotalAllocated * sizeof (svm_node) + numOfModels * sizeof (
      XSpacePtr);
  return memoryConsumedEstimated;
} /* MemoryConsumedEstimated */
bool SVMModel::NormalizeNominalAttributes () [virtual]
Return true, if nominal fields need to be normalized.
Definition at line 2246 of file SVMModel.cpp.
References KKMLL::SVMparam::EncodingMethod(), and KKMLL::NoEncoding.
Referenced by KKMLL::ModelOldSVM::NormalizeNominalAttributes().
{
  if (svmParam->EncodingMethod () ==
      SVM_EncodingMethod::NoEncoding)
    return true;
  else
    return false;
} /* NormalizeNominalAttributes */
kkint32 KKMLL::SVMModel::NumOfClasses () const [inline]
Definition at line 135 of file SVMModel.h.
{return numOfClasses;}
kkint32 SVMModel::NumOfSupportVectors () const
Definition at line 1304 of file SVMModel.cpp.
References KKMLL::BinaryCombos, SVM233::SvmModel233::l, and KKMLL::SVMparam::MachineType().
Referenced by KKMLL::ModelOldSVM::NumOfSupportVectors(), and SupportVectorStatistics().
{
  kkint32 numOfSupportVectors = 0;
  if (models == NULL)
    return 0;
  if (svmParam->MachineType () == SVM_MachineType::BinaryCombos)
  {
    vector<KKStr> svNames = SupportVectorNames ();
    numOfSupportVectors = (kkint32)svNames.size ();
  }
  else
  {
    for (kkint32 x = 0; x < numOfModels; x++)
      numOfSupportVectors += models[x][0]->l;
  }
  return numOfSupportVectors;
} /* NumOfSupportVectors */
MLClassPtr SVMModel::Predict (FeatureVectorPtr example)
Definition at line 1131 of file SVMModel.cpp.
References Predict().
Referenced by KKMLL::ModelOldSVM::Predict().
{
  double breakTie = -1.0f;
  bool knownClassOneOfTheWinners = false;
  kkint32 numOfWinners = -1;
  MLClassPtr pred1 = NULL;
  MLClassPtr pred2 = NULL;
  double predClass1Prob = -1.0;
  double predClass2Prob = -1.0;
  double probOfKnownClass = -1.0;
  kkint32 predClass1Votes = -1;
  kkint32 predClass2Votes = -1;
  
  InializeProbClassPairs ();
  Predict (example,
           NULL,
           pred1,
           pred2,
           predClass1Votes,
           predClass2Votes,
           probOfKnownClass,
           predClass1Prob,
           predClass2Prob,
           numOfWinners,
           knownClassOneOfTheWinners,
           breakTie
          );
  return pred1;
} /* Predict */
[Predict(FeatureVectorPtr example, MLClassPtr knownClass, MLClassPtr predClass1, MLClassPtr predClass2, kkint32 predClass1Votes, kkint32 predClass2Votes, double probOfKnownClass, double predClass1Prob, double predClass2Prob, kkint32 numOfWinners, bool knownClassOneOfTheWinners, double breakTie)]void SVMModel::Predict (FeatureVectorPtr example, MLClassPtr knownClass, MLClassPtr & predClass1, MLClassPtr & predClass2, kkint32 & predClass1Votes, kkint32 & predClass2Votes, double & probOfKnownClass, double & predClass1Prob, double & predClass2Prob, kkint32 & numOfWinners, bool & knownClassOneOfTheWinners, double & breakTie)
Will predict the two most likely classes of 'example'.
Parameters
in example The Example to predict on.
in knownClass Class that we already no the example to be; can be pointing to NULL indicating that you do not know.
out predClass1 Most likely class; depending on classifier parameters this could be by number of votes or probability.
out predClass2 Second most likely class.
out predClass1Votes Number votes 'predClass1' received.
out predClass2Votes Number votes 'predClass2' received.
out probOfKnownClass Probability of 'knownClass' if specified.
out predClass1Prob Probability of 'predClass1' if specified.
out predClass2Prob Probability of 'predClass2' if specified.
out numOfWinners Number of classes that had the same number of votes as the winning class.
out knownClassOneOfTheWinners Will return true if the known class was one of the classes that had the highest number of votes.
out breakTie The difference in probability between the classes with the two highest probabilities.
Definition at line 792 of file SVMModel.cpp.
References KKMLL::BinaryCombos, KKB::KKStr::Concat(), KKMLL::ClassAssignments::GetMLClass(), KKMLL::ClassAssignments::GetNumForClass(), KKB::KKException::KKException(), KKMLL::SVMparam::MachineType(), KKMLL::OneVsAll, and KKMLL::OneVsOne.
Referenced by KKMLL::ModelOldSVM::Predict(), and Predict().
{
  InializeProbClassPairs ();
  breakTie = 0.0f; // experiments.
  knownClassOneOfTheWinners = false;
  predClass1 = NULL;
  predClass2 = NULL;
  predClass1Votes = -1;
  predClass2Votes = -1;
  probOfKnownClass = 0.0;
  predClass1Prob = 0.0;
  predClass2Prob = -1.0f;
  numOfWinners = 0;
  if (svmParam->MachineType () == SVM_MachineType::OneVsAll)
  {
    EncodeExample (example, predictXSpace);
    PredictOneVsAll (predictXSpace, // used to be xSpace,
                     knownClass,
                     predClass1,
                     predClass2,
                     probOfKnownClass,
                     predClass1Prob,
                     predClass2Prob,
                     numOfWinners,
                     knownClassOneOfTheWinners,
                     breakTie
                    );
    predClass1Votes = 1;
    predClass2Votes = 1;
    // free (xSpace); // We are now allocating only once.
  }
  else if (svmParam->MachineType () == SVM_MachineType::OneVsOne)
  {
    EncodeExample (example, predictXSpace);
    kkint32 knownClassNum = -1;
    kkint32 prediction = -1;
    kkint32 prediction2 = -1;
    if (knownClass)
      knownClassNum = assignments.GetNumForClass (knownClass);
    vector<kkint32> winners;
    SvmPredictClass (*svmParam,
                     models[0],
                     predictXSpace,
                     votes,
                     probabilities,
                     knownClassNum,
                     prediction,
                     prediction2,
                     predClass1Votes,
                     predClass2Votes,
                     predClass1Prob,
                     predClass2Prob,
                     probOfKnownClass,
                     winners,
                     crossClassProbTable,
                     breakTie
                    );
    numOfWinners = (kkint32)winners.size ();
    for (kkint32 idx = 0; idx < (kkint32)winners.size (); idx++)
    {
      if (winners[idx] == knownClassNum)
      {
        knownClassOneOfTheWinners = true;
        break;
      }
    }
    predClass1 = assignments.GetMLClass (prediction);
    predClass2 = assignments.GetMLClass (prediction2);
    //free (xSpace);
  }
  
  else if (svmParam->MachineType () == SVM_MachineType::BinaryCombos
      )
  {
    PredictByBinaryCombos (example,
                           knownClass,
                           predClass1,
                           predClass2,
                           predClass1Votes,
                           predClass2Votes,
                           probOfKnownClass,
                           predClass1Prob,
                           predClass2Prob,
                           breakTie,
                           numOfWinners,
                           knownClassOneOfTheWinners
                          );
  }
    
  else
  {
    KKStr errMsg = "***ERROR*** SVMModel::Predict Invalid Machine Type Specified.";
    cerr << endl << errMsg << endl << endl;
    throw KKException (errMsg);
  }
  return;
} /* Predict */
void SVMModel::PredictRaw (FeatureVectorPtr example, MLClassPtr & predClass, double & dist)
Returns the distance from the decision border of the SVM.
Definition at line 921 of file SVMModel.cpp.
References KKMLL::ClassAssignments::GetMLClass(), and KKMLL::SvmPredictRaw().
Referenced by KKMLL::ModelOldSVM::PredictRaw().
{
  InializeProbClassPairs ();
  dist = 0.0;
  double label = 0.0;
  EncodeExample (example, predictXSpace);
  SvmPredictRaw (models[0], predictXSpace, label, dist);
  predClass = assignments.GetMLClass ((kkint16)label);
  return;
} /* PredictRaw */
void SVMModel::ProbabilitiesByClass (FeatureVectorPtr example, const MLClassList & _mlClasses, kkint32 * _votes, double * _probabilities, RunLog & _log)
Will get the probabilities assigned to each class.
Parameters
in example unknown example that we want to get predicted probabilities for.
in _mlClasses List classes that caller is aware of. This should be the same list that was used when constructing this SVMModel object. The list must be the same but not necessarily in the same order as when SVMModel was 1st constructed.
out _votes An array that must be as big as the number of classes in _mlClasses.
out _probabilities An array that must be as big as the number of classes in _mlClasses. The probability of class in _mlClasses[x] will be returned in _probabilities[x].
in _log Logging file.
Definition at line 1354 of file SVMModel.cpp.
References KKMLL::BinaryCombos, KKMLL::FeatureEncoder::EncodeAExample(), KKMLL::ClassAssignments::GetMLClass(), and KKMLL::SVMparam::MachineType().
Referenced by KKMLL::ModelOldSVM::ProbabilitiesByClass().
{
  InializeProbClassPairs ();
  if (svmParam->MachineType () == SVM_MachineType::BinaryCombos)
  {
    PredictProbabilitiesByBinaryCombos (example, _mlClasses, _votes, _probabilities, _log);
    return;
  }
  kkint32 predClass1Votes = -1;
  kkint32 predClass2Votes = -1;
  double predClass1Prob = 0.0;
  double predClass2Prob = 0.0;
  double probOfKnownClass = 0.0;
  double smallestDistOfPredClass = 0.0;
  double breakTie = 0.0f;
  MLClassPtr predictedClass = NULL;
  XSpacePtr xSpace = NULL;
  kkint32 x, y;
  xSpace = featureEncoder->EncodeAExample (example);
  kkint32 knownClassNum = 0;
  kkint32 prediction = 0;
  kkint32 prediction2 = 0;
  for (x = 0; x < numOfClasses; x++)
  {
    probabilities [x] = 0.0;
    _probabilities[x] = 0.0;
    _votes [x] = 0;
  }
  vector<kkint32> winners;
  SvmPredictClass (*svmParam,
                   models[0],
                   xSpace,
                   votes,
                   probabilities,
                   knownClassNum,
                   prediction,
                   prediction2,
                   predClass1Votes,
                   predClass2Votes,
                   predClass1Prob,
                   predClass2Prob,
                   probOfKnownClass,
                   winners,
                   crossClassProbTable,
                   breakTie
                  );
  // We have to do it this way, so that we pass back the probabilities in the
  // same order that the user indicated with mlClasses being passed in.
  for (x = 0; x < numOfClasses; x++)
  {
    predictedClass = assignments.GetMLClass (x);
    if (predictedClass)
    {
      y = _mlClasses.PtrToIdx (predictedClass);
      if ((y < 0) || (y >= numOfClasses))
      {
        _log.Level (-1) << endl
                << "SVMModel::ProbabilitiesByClass ***ERROR***"
                 << endl
                << " Invalid classIdx[" << y << "]
       Specified." << endl
                << " ClassName [" << predictedClass->Name () << "]"
                 << endl
                << endl;
      }
      else
      {
        _votes [y] = votes [x];
        _probabilities[y] = probabilities[x];
      }
    }
  }
  delete xSpace;
  xSpace = NULL;
  return;
} /* ProbabilitiesByClass */
void SVMModel::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) [virtual]
Definition at line 2421 of file SVMModel.cpp.
References KKMLL::SVMparam::C_Param(), KKB::KKStr::Concat(), KKMLL::FileDesc::CreateAttributeTypeTable(), KKMLL::FileDesc::CreateCardinalityTable(), KKMLL::SVMparam::EncodingMethod(), KKB::KKStr::EqualIgnoreCase(), KKMLL::FeatureEncoder::FeatureEncoder(), KKB::XmlStream::GetNextToken(), KKMLL::SVMparam::MachineType(), KKMLL::OneVsAll, KKMLL::OneVsOne, KKB::XmlToken::tokElement, KKB::XmlToken::TokenType(), KKMLL::XmlElementFileDesc::Value(), and KKB::XmlElement::VarName().
{
  kkint32 numModeLoaded = 0;
  KKStr lastBinaryClass1Name = "";
  KKStr lastBinaryClass2Name = "";
  kkint32 lastModelIdx = -1;
  DeleteModels ();
  DeleteXSpaces ();
  delete binaryParameters; binaryParameters = NULL;
  delete models; models = NULL;
  delete binaryFeatureEncoders; binaryFeatureEncoders = NULL;
  numOfClasses = 0;
  numOfModels = 0;
  DateTime timeSaved;
  bool errorsFound = false;
  XmlTokenPtr t = NULL;
  while (!errorsFound)
  {
    delete t;
    t = s.GetNextToken (cancelFlag, log);
    if ((!t) || cancelFlag)
      break;
    if (t->TokenType () == XmlToken::TokenTypes::tokElement)
    {
      XmlElementPtr e = dynamic_cast<XmlElementPtr> (t);
      if (!e)
        continue;
      const KKStr& varName = e->VarName ();
      if (varName.EqualIgnoreCase ("FileDesc") && (typeid (*e) == typeid (
      XmlElementFileDesc)))
      {
        fileDesc = dynamic_cast<XmlElementFileDescPtr> (e)->Value ();
      }
      else if (varName.EqualIgnoreCase ("HeaderFields") && (typeid (*e) == typeid (
      XmlElementKeyValuePairs)))
      {
        XmlElementKeyValuePairsPtr hf = dynamic_cast<
      XmlElementKeyValuePairsPtr> (e);
        if (!hf)
          continue;
        for (auto idx: *hf->Value ())
        {
          if (idx.first.EqualIgnoreCase ("RootFileName"))
            rootFileName = idx.second;
          else if (idx.first.EqualIgnoreCase ("Time"))
            timeSaved = DateTime (idx.second);
          else if (idx.first.EqualIgnoreCase ("NumOfModels"))
            numOfModels = idx.second.ToInt32 ();
          else if (idx.first.EqualIgnoreCase ("SelectedFeatures"))
          {
            delete selectedFeatures;
            bool validFeatures = false;
            selectedFeatures = new FeatureNumList (idx.second, validFeatures);
          }
          else if (idx.first.EqualIgnoreCase ("TrainingTime"))
            trainingTime = idx.second.ToDouble ();
          else if (idx.first.EqualIgnoreCase ("Assignments") || idx.first.EqualIgnoreCase ("
      ClassAssignments"))
            assignments.ParseToString (idx.second, log);
          else
          {
            log.Level (-1) << endl
              << "SVMModel::ReadXM ***ERROR*** Unrecognized Header Field: " << idx.first <<
      endl
              << endl;
            errorsFound = true;
          }
        }
        if (numOfModels < 1)
        {
          log.Level (-1) << endl
            << "SVMModel::ReadXM ***ERROR*** numOfModels: " << numOfModels << " Is invalid." <<
      endl
            << endl;
          errorsFound = true;
        }
        else
        {
          DeleteModels ();
          AllocateModels ();
          binaryParameters = new BinaryClassParmsPtr [numOfModels];
          binaryFeatureEncoders = new FeatureEncoderPtr [numOfModels];
          for (kkint32 x = 0; x < numOfModels; x++)
          {
            binaryParameters [x] = NULL;
            binaryFeatureEncoders [x] = NULL;
          }
        }
      }
      else if (varName.EqualIgnoreCase ("SvmParam") && (typeid (*e) == typeid (
      XmlElementSVMparam)))
      {
        XmlElementSVMparamPtr xmlSvmParam = dynamic_cast<
      XmlElementSVMparamPtr> (e);
        if (xmlSvmParam)
        {
          delete svmParam;
          svmParam = xmlSvmParam->TakeOwnership ();
        }
      }
      else if (varName.EqualIgnoreCase ("RootFileName"))
      {
        rootFileName = e->ToKKStr ();
      }
      else if (varName.EqualIgnoreCase ("OneVsOneModel") && (typeid (*e) == typeid (
      XmlElementSvmModel233)))
      {
        XmlElementSvmModel233Ptr xmlElementModel = dynamic_cast<
      XmlElementSvmModel233Ptr> (e);
        SvmModel233* m = xmlElementModel->Value ();
        if (m)
        {
          if (!m->valid)
          {
            log.Level (-1) << endl
              << "SVMModel::ReadXM ***ERROR*** 'OneVsOneModel' is invalid." <<
      endl
              << endl;
          }
          else
          {
            if (!models)
            {
              log.Level (-1) << endl
                << "SVMModel::ReadXM ***ERROR*** 'OneVsOneModel' models was not defined/allocated." <
      < endl
                << endl;
            }
            else
            {
              models[0][0] = xmlElementModel->TakeOwnership ();
              ++numModeLoaded;
            }
          }
        }
      }
      else if (varName.EqualIgnoreCase ("BinaryCombo") && (typeid (*e) == typeid (
      XmlElementKKStr)))
      {
        KKStr s = *(dynamic_cast<XmlElementKKStrPtr> (e)->Value ());
        lastModelIdx = s.ExtractTokenInt ("\t");
        lastBinaryClass1Name = s.ExtractToken2 ("\t");
        lastBinaryClass2Name = s.ExtractToken2 ("\t");
      }
      else if (varName.StartsWith ("BinaryComboModel_") && (typeid (*e) == typeid (
      XmlElementSvmModel233)))
      {
        XmlElementSvmModel233Ptr xmlElementModel = dynamic_cast<
      XmlElementSvmModel233Ptr> (e);
        SvmModel233* m = xmlElementModel->Value ();
        if ((!m) || (!m->valid))
        {
          log.Level (-1) << endl
            << "SVMModel::ReadXM ***ERROR*** SvmModel233[" << varName << "] is invalid." <<
      endl
            << endl;
          errorsFound = true;
        }
        else if (numModeLoaded >= numOfModels)
        {
          log.Level (-1) << endl
            << "SVMModel::ReadXM ***ERROR*** Number of models being loaded exceeds what was expected."
      << endl
            << endl;
          errorsFound = true;
        }
        else
        {
          MLClassPtr class1 = MLClass::CreateNewMLClass (
      lastBinaryClass1Name);
          MLClassPtr class2 = MLClass::CreateNewMLClass (
      lastBinaryClass2Name);
          log.Level (10) << "SVMModel::ReadXM Class1[" << lastBinaryClass1Name << "] Class2[" <<
      lastBinaryClass2Name << "]" << endl;
          BinaryClassParmsPtr binClassParms = svmParam->
      GetParamtersToUseFor2ClassCombo (class1, class2);
          if (!binClassParms)
          {
            log.Level (-1) << endl
              << "SVMModel::ReadXM ***ERROR*** Binary Class Parms are missing for classes " <<
      lastBinaryClass1Name << " and " << lastBinaryClass2Name << endl
              << endl;
            errorsFound = true;
          }
          else
          {
            models[numModeLoaded][0] = dynamic_cast<XmlElementSvmModel233Ptr> (e)->
      TakeOwnership ();
            binaryParameters[numModeLoaded] = binClassParms;
            binaryFeatureEncoders[numModeLoaded]
                = new FeatureEncoder (fileDesc,
                                      binClassParms->Class1 (),
                                      binClassParms->Class2 (),
                                      *(binClassParms->SelectedFeatures ()),
                                      svmParam->EncodingMethod (),
                                      binClassParms->C ()
                                     );
            ++numModeLoaded;
          }
        }
      }
    }
  }
  delete t;
  t = NULL;
  if (cancelFlag)
    errorsFound = true;
  if (assignments.size () < 2)
  {
   log.Level (-1) << endl
     << "SVMModel::ReadXM ***ERROR*** 'assignments is not properly defined." << endl
     << endl;
    errorsFound = true;
  }
  if (!fileDesc)
  {
   log.Level (-1) << endl
     << "SVMModel::ReadXM ***ERROR*** 'fileDesc' is not defined." << endl
     << endl;
    errorsFound = true;
  }
  if (!svmParam)
  {
   log.Level (-1) << endl
     << "SVMModel::ReadXM ***ERROR*** 'svmParam' is not defined." << endl
     << endl;
    errorsFound = true;
  }
  if (!errorsFound)
  {
    type_table = fileDesc->CreateAttributeTypeTable ();
    cardinality_table = fileDesc->CreateCardinalityTable ();
    numOfClasses = (kkint32)assignments.size ();
    BuildClassIdxTable ();
    BuildCrossClassProbTable ();
    CalculatePredictXSpaceNeeded (log);
    if ((svmParam->MachineType () == SVM_MachineType::OneVsOne) ||
      (svmParam->MachineType () == SVM_MachineType::OneVsAll))
    {
      delete featureEncoder;
      featureEncoder = new FeatureEncoder (fileDesc,
                                           NULL, // class1, set to NULL because we are dealing
       with all classes
                                           NULL, // class2, "" "" ""
                ""
                                           *selectedFeatures,
                                           svmParam->EncodingMethod (),
                                           svmParam->C_Param ()
                                          );
    }
  }
  validModel = !errorsFound;
} /* ReadXML */
void SVMModel::RetrieveCrossProbTable (MLClassList & classes, double ** crossProbTable, RunLog & log)
Will return the probabilities for all pairs of the classes listed in 'classes'.
Parameters
in classes The Classes that you wish to get class pair probabilities for; the order will dictate how the two dimensional matrix 'crossProbTable' will be populated.
out crossProbTable Will contain the probabilities of all the class pairs that can be formed from the list of classes in 'classes'. 'crossProbTable' will be a two dimension square matrix size will be dictated by the number of classes in 'classes'. Ex: Entry[3][2] will have the contain the probability between classes[3] and classes[2].
in log Logging file.
Definition at line 2279 of file SVMModel.cpp.
Referenced by KKMLL::ModelOldSVM::RetrieveCrossProbTable().
{
  if (classes.QueueSize () != crossClassProbTableSize)
  {
    // There Class List does not have the same number of entries as our 'CrossProbTable'
    log.Level (-1) << endl
                   << "SVMModel::RetrieveCrossProbTable ***ERROR***" << endl
                   << " classes.QueueSize ()[" << classes.QueueSize () << "] !=
       crossClassProbTableSize[" << crossClassProbTableSize << "]" << endl
                   << endl;
    return;
  }
  kkint32* indexTable = new kkint32[classes.QueueSize ()];
  kkint32 x, y;
  for (x = 0; x < classes.QueueSize (); x++)
  {
    for (y = 0; y < classes.QueueSize (); y++)
       crossProbTable[x][y] = 0.0;
    indexTable[x] = assignments.GetNumForClass (classes.IdxToPtr (x));
    if (indexTable[x] < 0)
    {
      log.Level (-1) << endl << endl
                     << "SVMModel::RetrieveCrossProbTable ***WARNING***" <<
      endl
                     << endl
                     << " Class Index[" << x << "] Name[" << classes[x].Name () << "]" <<
      endl
                     << " will populate this index with zeros." <<
      endl
                     << endl;
    }
  }
  if (classes.QueueSize () != crossClassProbTableSize)
  {
    log.Level (-1) << endl
                   << "SVMModel::RetrieveCrossProbTable ***ERROR***"
           << endl
                   << " 'classes.QueueSize () !=
       crossClassProbTableSize'" << endl
                   << endl;
    return;
  }
  // x,y = 'Callers' Class Indexes..
  // xIdx, yIdx = 'SVMNodel' Class Indexed.
  for (x = 0; x < classes.QueueSize (); x++)
  {
    kkint32 xIdx = indexTable[x];
    if (xIdx >= 0)
    {
      for (y = 0; y < classes.QueueSize (); y++)
      {
        kkint32 yIdx = indexTable[y];
        if (yIdx >= 0)
        {
          if ((x != xIdx) || (y != yIdx))
          {
            //kak I just added this check to see when this situation actually occurs.
            kkint32 zed = 111;
          }
          crossProbTable[x][y] = this->crossClassProbTable[xIdx][yIdx];
        }
      }
    }
  }
  delete[] indexTable; indexTable = NULL;
  return;
} /* RetrieveCrossProbTable */
const KKStr& KKMLL::SVMModel::RootFileName () const [inline]
Definition at line 145 of file SVMModel.h.
{return rootFileName;}
SVM_SelectionMethod KKMLL::SVMModel::SelectionMethod () const [inline]
Definition at line 148 of file SVMModel.h.
References KKMLL::SVMparam::SelectionMethod().
Referenced by KKMLL::ModelOldSVM::SelectionMethod().
{return svmParam->SelectionMethod ();}
vector< KKStr > SVMModel::SupportVectorNames () const
Definition at line 1618 of file SVMModel.cpp.
References KKB::KKStr::Concat(), SVM233::SvmModel233::l, and SVM233::SvmModel233::SupportVectorName().
{
  vector<KKStr> results;
  if (svmParam->MachineType () != SVM_MachineType::BinaryCombos)
    return results;
  map<KKStr,KKStr> names;
  map<KKStr,KKStr>::iterator svnIDX;
  // Locate the binary parms in question.
  kkint32 modelIDX = 0;
  BinaryClassParmsPtr parms = NULL;
  for (modelIDX = 0; modelIDX < numOfModels; modelIDX++)
  {
    parms = binaryParameters[modelIDX];
  
    kkint32 numSVs = models[modelIDX][0]->l;
    kkint32 svIDX = 0;
    for (svIDX = 0; svIDX < numSVs; svIDX++)
    {
      KKStr svName = models[modelIDX][0]->SupportVectorName (svIDX);
      svnIDX = names.find (svName);
      if (svnIDX == names.end ())
      {
        names.insert (pair<KKStr,KKStr>(svName, svName));
        results.push_back (svName);
      }
    }
  }
  return results;
} /* SupportVectorNames */
vector< KKStr > SVMModel::SupportVectorNames (MLClassPtr c1, MLClassPtr c2) const
Definition at line 1576 of file SVMModel.cpp.
References KKMLL::BinaryClassParms::Class1(), KKMLL::BinaryClassParms::Class2(), KKB::KKStr::Concat(), SVM233::SvmModel233::l, and SVM233::SvmModel233::SupportVectorName().
Referenced by KKMLL::ModelOldSVM::TrainModel().
{
  vector<KKStr> results;
  if (svmParam->MachineType () != SVM_MachineType::BinaryCombos)
    return results;
  // Locate the binary parms in question.
  kkint32 modelIDX = 0;
  BinaryClassParmsPtr parms = NULL;
  for (modelIDX = 0; modelIDX < numOfModels; modelIDX++)
  {
    parms = binaryParameters[modelIDX];
    if ((parms->Class1 () == c1) && (parms->Class2 () == c2))
      break;
    else if ((parms->Class2 () == c1) && (parms->Class1 () == c2))
      break;
  }
  if (modelIDX >= numOfModels)
  {
    // Binary Combo not found.
    cerr << endl
         << "SVMModel::SupportVectorNames ***ERROR*** Class1[" << c1->Name () << "] Class2[" << c2->
      Name () << "] not part of model." << endl
         << endl;
    return results;
  }
  kkint32 numSVs = models[modelIDX][0]->l;
  kkint32 svIDX = 0;
  for (svIDX = 0; svIDX < numSVs; svIDX++)
  {
    KKStr svName = models[modelIDX][0]->SupportVectorName (svIDX);
    results.push_back (svName);
  }
  return results;
} /* SupportVectorNames */
void SVMModel::SupportVectorStatistics (kkint32 & numSVs, kkint32 & totalNumSVs)
Definition at line 1328 of file SVMModel.cpp.
References KKMLL::BinaryCombos, SVM233::SvmModel233::l, KKMLL::SVMparam::MachineType(), NumOfSupportVectors(), and SVM233::svm_GetSupportVectorStatistics().
Referenced by KKMLL::ModelOldSVM::SupportVectorStatistics().
{
  numSVs = 0;
  totalNumSVs = 0;
  if (models == NULL)
    return;
  if (svmParam->MachineType () == SVM_MachineType::BinaryCombos)
  {
    numSVs = NumOfSupportVectors ();
    for (kkint32 modelIDX = 0; modelIDX < numOfModels; modelIDX++)
    {
      totalNumSVs += models[modelIDX][0]->l;
    }
  }
  else
  {
    svm_GetSupportVectorStatistics (models[0][0], numSVs, totalNumSVs);
  }
} /* SupportVectorStatistics */
SVMparam const* KKMLL::SVMModel::SVMParameters () const [inline]
Definition at line 143 of file SVMModel.h.
Referenced by KKMLL::ModelOldSVM::Description(), and KKMLL::ModelOldSVM::ProbabilitiesByClass().
{return svmParam;}
double KKMLL::SVMModel::TrainingTime () const [inline]
Definition at line 150 of file SVMModel.h.
{return trainingTime;}
bool KKMLL::SVMModel::ValidModel () const [inline]
Definition at line 152 of file SVMModel.h.
Referenced by KKMLL::ModelOldSVM::ReadXML().
{return validModel;}
void SVMModel::WriteXML (const KKStr & varName, std::ostream & o) const [virtual]
Definition at line 2354 of file SVMModel.cpp.
References KKB::XmlElementKeyValuePairs::Add(), KKB::XmlTag::AddAtribute(), KKMLL::BinaryCombos, KKMLL::BinaryClassParms::Class1Name(), KKMLL::BinaryClassParms::Class2Name(), KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKB::KKStr::KKStr(), KKMLL::SVMparam::MachineType(), KKMLL::OneVsAll, KKMLL::OneVsOne, KKB::operator+(), KKB::osGetLocalDateTime(), KKB::StrFormatInt(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKMLL::ClassAssignments::ToString(), KKMLL::FeatureNumList::ToString(), SVM233::SvmModel233::WriteXML(), KKB::XmlTag::WriteXML(), KKMLL::SVMparam::WriteXML(), KKMLL::FileDesc::WriteXML(), KKB::KKStr::WriteXML(), KKB::XmlElementKeyValuePairs::WriteXML(), KKB::XmlElementKeyValuePairs::XmlElementKeyValuePairs(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::ModelOldSVM::WriteXML().
{
  XmlTag startTag ("SVMModel", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  if (fileDesc)
    fileDesc->WriteXML ("FileDesc", o);
  {
    XmlElementKeyValuePairs* headerFields = new
      XmlElementKeyValuePairs ();
    headerFields->Add ("RootFileName", rootFileName);
    headerFields->Add ("Time", osGetLocalDateTime ());
    headerFields->Add ("NumOfModels", numOfModels);
    if (selectedFeatures)
      headerFields->Add ("SelectedFeatures", selectedFeatures->ToString ());
    headerFields->Add ("TrainingTime", trainingTime);
    headerFields->Add ("Assignments", assignments.ToString ());
    headerFields->WriteXML ("HeaderFields", o);
    delete headerFields;
    headerFields = NULL;
  }
  svmParam->WriteXML ("svmParam", o);
  if (svmParam->MachineType () == SVM_MachineType::OneVsOne)
  {
    // "<OneVsOne>"
    rootFileName.WriteXML ("RootFileName", o);
    if (models && (models[0]) && models[0][0])
      models[0][0]->WriteXML ("OneVsOneModel", o);
  }
  else if (svmParam->MachineType () == SVM_MachineType::OneVsAll)
  {
    // Not Supported
  }
  else if (svmParam->MachineType () == SVM_MachineType::BinaryCombos
      )
  {
    kkint32 modelsIDX = 0;
    for (modelsIDX = 0; modelsIDX < numOfModels; modelsIDX++)
    {
      BinaryClassParmsPtr binClassParms = binaryParameters[modelsIDX];
      KKStr binaryClassNames (256);
      binaryClassNames << modelsIDX << "\t" << binClassParms->Class1Name () << "\t" <<
      binClassParms->Class2Name ();
      binaryClassNames.WriteXML ("BinaryCombo", o);
      KKStr binaryComboModelName = "BinaryComboModel_" + StrFormatInt (modelsIDX, "000");
      models[modelsIDX][0]->WriteXML (binaryComboModelName, o);
    }
  }
  XmlTag endTag ("SVMModel", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/SVMModel.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/SVMModel.cpp