KKB::XmlContent Class Reference
#include <XmlStream.h>
Public Types
typedef XmlContent * XmlContentPtr
Public Member Functions
XmlContent (KKStrPtr _content)
virtual ~XmlContent ()
KKStrPtr const Content () const
KKStrPtr TakeOwnership ()
virtual TokenTypes TokenType ()
Static Public Member Functions
static void WriteXml (const KKStr &s, std::ostream &o)
Detailed Description
Definition at line 328 of file XmlStream.h.
Member Typedef Documentation
typedef XmlContent* KKB::XmlContent::XmlContentPtr
Definition at line 331 of file XmlStream.h.
Constructor & Destructor Documentation
XmlContent::XmlContent (KKStrPtr _content)
Definition at line 829 of file XmlStream.cpp.
References KKB::XmlToken::XmlToken().
Referenced by KKB::XmlStream::GetNextContent(), and KKB::XmlStream::GetNextToken().
                                         :
      XmlToken (),
      content (_content)
{
}
XmlContent::~XmlContent () [virtual]
Definition at line 837 of file XmlStream.cpp.
{
  delete content;
  content = NULL;
}
Member Function Documentation
KKStrPtr const KKB::XmlContent::Content () const [inline]
Definition at line 338 of file XmlStream.h.
Referenced by KKMLL::AttributeTypeVector::ReadXML(), KKB::VectorKKStr::ReadXML(), KKMLL::ClassProbList::ReadXML(), KKB::BitString::ReadXML(), KKMLL::FeatureNumList::ReadXML(), KKMLL::BinaryClassParmsList::ReadXML(), SVM233::SvmModel233::ReadXML(), KKB::KKStr::ReadXML(), KKMLL::MLClassIndexList::ReadXML(), KKB::KKStrList::ReadXML(), KKB::KKStrListIndexed::ReadXML(), KKB::XmlElementBool::XmlElementBool(), KKB::XmlElementKeyValuePairs::XmlElementKeyValuePairs(), and KKMLL::XmlElementMLClassNameList::XmlElementMLClassNameList().
{return content;}
KKStrPtr XmlContent::TakeOwnership ()
Definition at line 845 of file XmlStream.cpp.
{
  KKStrPtr c = content;
  content = NULL;
  return c;
}
virtual TokenTypes KKB::XmlContent::TokenType () [inline], [virtual]
Implements KKB::XmlToken.
Definition at line 336 of file XmlStream.h.
References KKB::XmlToken::tokContent.
{return TokenTypes::tokContent;}
void XmlContent::WriteXml (const KKStr & s, std::ostream & o) [static]
Definition at line 853 of file XmlStream.cpp.
References KKB::KKStr::Len(), KKB::operator<<(), and KKB::KKStr::Str().
Referenced by KKB::BitString::WriteXML(), KKMLL::MLClassIndexList::WriteXML(), KKB::KKStr::WriteXML(), KKMLL::XmlElementMLClassNameList::WriteXML(), KKB::KKStrList::WriteXML(), and KKB::KKStrListIndexed::WriteXML().
{
  const char* str = s.Str ();
  kkuint32 len = s.Len ();
  for (kkuint32 x = 0; x < len; ++x)
  {
    char ch = str[x];
    switch (ch)
    {
    case '&': o << "&amp;"; break;
    case '<': o << "&lt;"; break;
    case '>': o << "&gt;"; break;
    default: o << ch; break;
    }
  }
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/XmlStream.cpp