KKMLL::CrossValidation Class Reference
A class that is meant to manage a n-Fold Cross Validation.
#include <CrossValidation.h>
Public Member Functions
CrossValidation (TrainingConfiguration2Ptr _config, FeatureVectorListPtr _examples, MLClassListPtr _mlClasses, kkint32 _numOfFolds, bool _featuresAreAlreadyNormalized, FileDescPtr _fileDesc, RunLog &_log, bool &_cancelFlag)
~CrossValidation ()
const VectorFloat & Accuracies () const
float Accuracy ()
float AccuracyMean () const
float AccuracyNorm ()
float AccuracyStdDev () const
double AvgPredProb () const
const ConfusionMatrix2Ptr ConfussionMatrix () const
kkint32 DuplicateTrainDataCount () const
const VectorFloat & FoldAccuracies () const
float FoldAccuracy (kkint32 foldNum) const
KKStr FoldAccuracysToStr () const
ConfusionMatrix2Ptr GiveMeOwnershipOfConfusionMatrix ()
void NumOfFolds (kkint32 _numOfFolds)
kkint32 NumOfSupportVectors () const
kkint32 NumSVs () const
void RunCrossValidation (RunLog &log)
void RunValidationOnly (FeatureVectorListPtr validationData, bool *classedCorrectly, RunLog &log)
const VectorFloat & SupportPoints () const
double SupportPointsMean () const
double SupportPointsStdDev () const
kkint32 SupportPointsTotal () const
double TestTimeMean () const
const VectorDouble & TestTimes () const
double TestTimeStdDev () const
double TestTimeTotal () const
kkint32 TotalNumSVs () const
double TrainTimeMean () const
const VectorDouble & TrainTimes () const
double TrainTimeStdDev () const
double TrainTimeTotal () const
Detailed Description
A class that is meant to manage a n-Fold Cross Validation.
Author
Kurt Kramer
                           CrossValidation *
                                                                   *
                                                                   *
                                                                   *
-------------------------------------------------------------------*
  History *
                                                                   *
    Date Programmer Description *
  ---------- ----------- -----------------------------------------*
  2004 Kurt Kramer Original Development. *
                                                                   *
                                                                   *
  2005-01-07 Kurt Kramer Added classedCorrectly parameter to *
                          CrossValidate. If not null it should *
                          point to an array of bool that has as *
                          many elements as there are in the *
                          testImages list. Each element represents *
                          weather the corresponding element in *
                          testImages was classified correctly. *
Definition at line 82 of file CrossValidation.h.
Constructor & Destructor Documentation
CrossValidation::CrossValidation (TrainingConfiguration2Ptr _config, FeatureVectorListPtr _examples, MLClassListPtr _mlClasses, kkint32 _numOfFolds, bool _featuresAreAlreadyNormalized, FileDescPtr _fileDesc, RunLog & _log, bool & _cancelFlag)
Definition at line 32 of file CrossValidation.cpp.
References KKMLL::TrainingConfiguration2::ExamplesPerClass(), KKMLL::FeatureVectorList::ExtractExamplesForClassList(), and KKMLL::TrainingConfiguration2::FvFactoryProducer().
Referenced by KKMLL::CrossValidationMxN::RunTrainAndTest(), and KKMLL::CrossValidationMxN::RunValidations().
                                  :
   cancelFlag (_cancelFlag),
   config (_config),
   duplicateTrainDataCount (0),
   featuresAreAlreadyNormalized (_featuresAreAlreadyNormalized),
   fileDesc (_fileDesc),
   foldAccuracies (),
   foldCounts (),
   fvProducerFactory (NULL),
   confusionMatrix (NULL),
   cmByNumOfConflicts (NULL),
   examples (NULL),
   mlClasses (_mlClasses),
   imagesPerClass (0),
   maxNumOfConflicts (0),
   numOfFolds (_numOfFolds),
   numSVs (0),
   totalNumSVs (0),
   numOfWinnersCounts (NULL),
   numOfWinnersCorrects (NULL),
   numOfWinnersOneOfTheWinners (NULL),
   testTime (0.0),
   trainingTime (0.0),
   accuracyMean (0.0f),
   accuracyStdDev (0.0f),
   avgPredProb (0.0),
   totalPredProb (0.0),
   supportPointsMean (0.0f),
   supportPointsStdDev (0.0f),
   supportPoints (),
   testTimeMean (0.0),
   testTimeStdDev (0.0),
   testTimes (),
   trainTimeMean (0.0),
   trainTimeStdDev (0.0),
   trainTimes (),
   weOwnConfusionMatrix (false)
{
  fvProducerFactory = config->FvFactoryProducer (_log);
  examples = _examples->ExtractExamplesForClassList (mlClasses);
  if (config)
    imagesPerClass = config->ExamplesPerClass ();
  else
     imagesPerClass = -1;
}
CrossValidation::~CrossValidation ()
Definition at line 96 of file CrossValidation.cpp.
{
  DeleteAllocatedMemory ();
  delete examples; examples = NULL;
}
Member Function Documentation
const VectorFloat& KKMLL::CrossValidation::Accuracies () const [inline]
Definition at line 127 of file CrossValidation.h.
{return foldAccuracies;}
float CrossValidation::Accuracy ()
Definition at line 456 of file CrossValidation.cpp.
References KKMLL::ConfusionMatrix2::Accuracy().
{
  if (confusionMatrix)
    return (float)confusionMatrix->Accuracy ();
  else
    return 0.0f;
} /* Accuracy */
float KKMLL::CrossValidation::AccuracyMean () const [inline]
Definition at line 128 of file CrossValidation.h.
{return accuracyMean;}
float CrossValidation::AccuracyNorm ()
Definition at line 466 of file CrossValidation.cpp.
References KKMLL::ConfusionMatrix2::AccuracyNorm().
{
  if (confusionMatrix)
    return (float)confusionMatrix->AccuracyNorm ();
  else
    return 0.0f;
} /* Accuracy */
float KKMLL::CrossValidation::AccuracyStdDev () const [inline]
Definition at line 129 of file CrossValidation.h.
{return accuracyStdDev;}
double KKMLL::CrossValidation::AvgPredProb () const [inline]
Definition at line 131 of file CrossValidation.h.
{return avgPredProb;}
const ConfusionMatrix2Ptr KKMLL::CrossValidation::ConfussionMatrix () const [inline]
Definition at line 105 of file CrossValidation.h.
Referenced by KKMLL::CrossValidationMxN::RunTrainAndTest(), and KKMLL::CrossValidationMxN::RunValidations().
{return confusionMatrix;}
kkint32 KKMLL::CrossValidation::DuplicateTrainDataCount () const [inline]
Definition at line 109 of file CrossValidation.h.
{return duplicateTrainDataCount;}
const VectorFloat& KKMLL::CrossValidation::FoldAccuracies () const [inline]
Definition at line 115 of file CrossValidation.h.
{return foldAccuracies;}
float CrossValidation::FoldAccuracy (kkint32 foldNum) const
Definition at line 495 of file CrossValidation.cpp.
{
  if ((foldNum < 0) || (foldNum >= (kkint32)foldAccuracies.size ()))
  {
    return 0.0f;
  }
  return foldAccuracies[foldNum];
} /* FoldAccuracy */
KKStr CrossValidation::FoldAccuracysToStr () const
Definition at line 477 of file CrossValidation.cpp.
References KKB::KKStr::Concat(), and KKB::KKStr::KKStr().
{
  KKStr foldAccuracyStr (9 * numOfFolds); // Pre Reserving enough space for all Accuracies.
  for (kkuint32 foldNum = 0; foldNum < foldAccuracies.size (); foldNum++)
  {
    if (foldNum > 0)
      foldAccuracyStr << "\t";
    foldAccuracyStr << StrFormatDouble (foldAccuracies[foldNum], "ZZ,ZZ0.00%");
  }
  return foldAccuracyStr;
} /* FoldAccuracysToStr */
ConfusionMatrix2Ptr CrossValidation::GiveMeOwnershipOfConfusionMatrix ()
Definition at line 508 of file CrossValidation.cpp.
{
  weOwnConfusionMatrix = false;
  return confusionMatrix;
}
void KKMLL::CrossValidation::NumOfFolds (kkint32 _numOfFolds) [inline]
Definition at line 112 of file CrossValidation.h.
{numOfFolds = _numOfFolds;}
kkint32 KKMLL::CrossValidation::NumOfSupportVectors () const [inline]
Definition at line 121 of file CrossValidation.h.
{return numSVs;}
kkint32 KKMLL::CrossValidation::NumSVs () const [inline]
Definition at line 122 of file CrossValidation.h.
{return numSVs;}
void CrossValidation::RunCrossValidation (RunLog & log)
Definition at line 166 of file CrossValidation.cpp.
References KKMLL::FeatureVectorList::ManufactureEmptyList(), and KKMLL::FeatureVectorList::PushOnBack().
Referenced by KKMLL::CrossValidationMxN::RunValidations().
{
  log.Level (10) << "CrossValidation::RunCrossValidation numOfFolds[" << numOfFolds << "]" <<
      endl;
  if (numOfFolds < 1)
  {
    log.Level (-1) << endl
                   << "CrossValidation::RunCrossValidation **** ERROR ****" << endl
                   << endl
                   << " Invalid numOfFolds[" << numOfFolds << "]." <<
      endl
                   << endl;
    return;
  }
  DeleteAllocatedMemory ();
  AllocateMemory ();
  kkint32 imageCount = examples->QueueSize ();
  kkint32 numImagesPerFold = (imageCount + numOfFolds - 1) / numOfFolds;
  kkint32 firstInGroup = 0;
  totalPredProb = 0.0;
  kkint32 foldNum;
  for (foldNum = 0; foldNum < numOfFolds; foldNum++)
  {
    kkint32 lastInGroup;
    // If We are doing the last Fold Make sure that we are including all the examples
    // that have not been tested.
    if (foldNum == (numOfFolds - 1))
      lastInGroup = imageCount;
    else
      lastInGroup = firstInGroup + numImagesPerFold - 1;
    log.Level (20) << "Fold [" << (foldNum + 1) << "] of [" << numOfFolds << "]" << endl;
    FeatureVectorListPtr trainingExamples = examples->
      ManufactureEmptyList (true);
    FeatureVectorListPtr testImages = examples->
      ManufactureEmptyList (true);
    log.Level (30) << "Fold Num[" << foldNum << "] "
                   << "FirstTestImage[" << firstInGroup << "] "
                   << "LastInGroup[" << lastInGroup << "]."
                   << endl;
    for (kkint32 x = 0; (x < imageCount) && (!cancelFlag); x++)
    {
      FeatureVectorPtr newImage = examples->IdxToPtr (x)->
      Duplicate ();
      if ((x >= firstInGroup) && (x <= lastInGroup))
      {
        testImages->PushOnBack (newImage);
      }
      else
      {
        trainingExamples->PushOnBack (newImage);
      }
    }
    log.Level (20) << "Number Of Training Images : " << trainingExamples->
      QueueSize () << endl;
    log.Level (20) << "Number Of Test Images : " << testImages->
      QueueSize () << endl;
    if (cancelFlag)
      break;
    
    CrossValidate (testImages, trainingExamples, foldNum, NULL, log);
    delete trainingExamples; trainingExamples = NULL;
    delete testImages; testImages = NULL;
    firstInGroup = firstInGroup + numImagesPerFold;
  }
  if (!cancelFlag)
  {
    avgPredProb = totalPredProb / imageCount;
    CalcMeanAndStdDev (foldAccuracies, accuracyMean, accuracyStdDev);
    CalcMeanAndStdDev (supportPoints, supportPointsMean, supportPointsStdDev);
    CalcMeanAndStdDev (testTimes, testTimeMean, testTimeStdDev);
    CalcMeanAndStdDev (trainTimes, trainTimeMean, trainTimeStdDev);
  }
} /* RunCrossValidation */
void CrossValidation::RunValidationOnly (FeatureVectorListPtr validationData, bool * classedCorrectly, RunLog & log)
Definition at line 256 of file CrossValidation.cpp.
References KKMLL::FeatureVectorList::DuplicateListAndContents().
Referenced by KKMLL::CrossValidationMxN::RunTrainAndTest().
{
  log.Level (10) << "CrossValidation::RunValidationOnly" << endl;
  DeleteAllocatedMemory ();
  AllocateMemory ();
  totalPredProb = 0.0;
  // We need to get a duplicate copy of each image data because the trainer and classifier
  // will normalize the data.
  FeatureVectorListPtr trainingExamples = examples->
      DuplicateListAndContents ();
  FeatureVectorListPtr testImages = validationData->
      DuplicateListAndContents ();
  CrossValidate (testImages, trainingExamples, 0, classedCorrectly, log);
  if (testImages->QueueSize () > 0)
    avgPredProb = totalPredProb / testImages->QueueSize ();
  else
    avgPredProb = 0.0f;
  delete trainingExamples; trainingExamples = NULL;
  delete testImages; testImages = NULL;
  if (!cancelFlag)
  {
    CalcMeanAndStdDev (foldAccuracies, accuracyMean, accuracyStdDev);
    CalcMeanAndStdDev (supportPoints, supportPointsMean, supportPointsStdDev);
    CalcMeanAndStdDev (testTimes, testTimeMean, testTimeStdDev);
    CalcMeanAndStdDev (trainTimes, trainTimeMean, trainTimeStdDev);
  }
} /* RunValidationOnly */
const VectorFloat& KKMLL::CrossValidation::SupportPoints () const [inline]
Definition at line 133 of file CrossValidation.h.
{return supportPoints;}
double KKMLL::CrossValidation::SupportPointsMean () const [inline]
Definition at line 134 of file CrossValidation.h.
{return supportPointsMean;}
double KKMLL::CrossValidation::SupportPointsStdDev () const [inline]
Definition at line 135 of file CrossValidation.h.
{return supportPointsStdDev;}
kkint32 KKMLL::CrossValidation::SupportPointsTotal () const [inline]
Definition at line 125 of file CrossValidation.h.
{return numSVs;}
double KKMLL::CrossValidation::TestTimeMean () const [inline]
Definition at line 138 of file CrossValidation.h.
{return testTimeMean;}
const VectorDouble& KKMLL::CrossValidation::TestTimes () const [inline]
Definition at line 137 of file CrossValidation.h.
{return testTimes;}
double KKMLL::CrossValidation::TestTimeStdDev () const [inline]
Definition at line 139 of file CrossValidation.h.
{return testTimeStdDev;}
double KKMLL::CrossValidation::TestTimeTotal () const [inline]
Definition at line 140 of file CrossValidation.h.
{return testTime;}
kkint32 KKMLL::CrossValidation::TotalNumSVs () const [inline]
Definition at line 123 of file CrossValidation.h.
{return totalNumSVs;}
double KKMLL::CrossValidation::TrainTimeMean () const [inline]
Definition at line 143 of file CrossValidation.h.
{return trainTimeMean;}
const VectorDouble& KKMLL::CrossValidation::TrainTimes () const [inline]
Definition at line 142 of file CrossValidation.h.
{return trainTimes;}
double KKMLL::CrossValidation::TrainTimeStdDev () const [inline]
Definition at line 144 of file CrossValidation.h.
{return trainTimeStdDev;}
double KKMLL::CrossValidation::TrainTimeTotal () const [inline]
Definition at line 145 of file CrossValidation.h.
{return trainingTime;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/CrossValidation.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/CrossValidation.cpp