KKB::TimeType Class Reference
Represents a Time, consisting of three fields, Hour, Minute, and Second.
summary>Represents Date and Time, consists of two member classes DateType and TimeType.
#include <DateTime.h>
Public Member Functions
TimeType ()
TimeType (const TimeType &time)
TimeType (uchar _hour, uchar _minute, uchar _second)
TimeType (kkint32 seconds)
TimeType (KKStr s)
KKStr HH_MM_SS () const
KKStr HHMMSS () const
uchar Hour () const
void Hour (uchar _hour)
uchar Minute () const
void Minute (uchar _minute)
bool operator!= (const TimeType &right) const
TimeType operator+ (const TimeType &right) const
TimeType operator- (const TimeType &right) const
bool operator< (const TimeType &right) const
bool operator<= (const TimeType &right) const
TimeType & operator= (const TimeType &right)
bool operator== (const TimeType &right) const
bool operator> (const TimeType &right) const
bool operator>= (const TimeType &right) const
uchar Second () const
void Second (uchar _second)
kkuint32 Seconds () const
double ToHours () const
double ToMinutes () const
Friends
class DateTime
Detailed Description
Represents a Time, consisting of three fields, Hour, Minute, and Second.
summary>Represents Date and Time, consists of two member classes DateType and TimeType.
Definition at line 149 of file DateTime.h.
Constructor & Destructor Documentation
TimeType::TimeType ()
Definition at line 757 of file DateTime.cpp.
Referenced by KKB::DateTime::DateTime().
                   :
   hour (0),
   minute (0),
   second (0)
{}
TimeType::TimeType (const TimeType & time)
Definition at line 766 of file DateTime.cpp.
Referenced by KKB::DateTime::DateTime().
                                         :
   hour (_time.hour),
   minute (_time.minute),
   second (_time.second)
{}
TimeType::TimeType (uchar _hour, uchar _minute, uchar _second)
Definition at line 774 of file DateTime.cpp.
Referenced by KKB::DateTime::DateTime().
                    :
   hour (_hour),
   minute (_minute),
   second (_second)
{}
TimeType::TimeType (kkint32 seconds)
Definition at line 785 of file DateTime.cpp.
Referenced by operator+(), KKB::DateTime::operator+(), operator-(), and KKB::DateTime::operator-().
{
  kkint32 hours = seconds / 3600;
      seconds = seconds % 3600;
  kkint32 minutes = seconds / 60;
      seconds = seconds % 60;
  hour = (uchar)hours;
  minute = (uchar)minutes;
  second = (uchar)seconds;
}
TimeType::TimeType (KKStr s)
Definition at line 802 of file DateTime.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::ExtractToken(), KKB::KKStr::Len(), KKB::KKStr::operator=(), and KKB::KKStr::SubStrPart().
Referenced by KKB::Application::BuildDate(), and KKB::DateTime::DateTime().
                           :
   hour (0),
   minute (0),
   second (0)
{
  KKStr field1, field2, field3;
  if (s.Len () == 6)
  {
    field1 = s.SubStrPart (0, 1);
    field2 = s.SubStrPart (2, 3);
    field3 = s.SubStrPart (4, 5);
  }
  else
  {
    field1 = s.ExtractToken ("\n\r\t: ");
    field2 = s.ExtractToken ("\n\r\t: ");
    field3 = s.ExtractToken ("\n\r\t: ");
  }
  kkint32 f1 = atoi (field1.Str ());
  kkint32 f2 = atoi (field2.Str ());
  kkint32 f3 = atoi (field3.Str ());
 
  if (((f1 >= 0) && (f1 <= 24)) &&
       ((f2 >= 0) && (f2 <= 59)) &&
       ((f3 >= 0) && (f3 <= 59))
      )
  {
    hour = (uchar)f1;
    minute = (uchar)f2;
    second = (uchar)f3;
  }
}
Member Function Documentation
KKStr TimeType::HH_MM_SS () const
Definition at line 841 of file DateTime.cpp.
References KKB::KKStr::operator+(), and KKB::StrFormatInt().
Referenced by KKB::Application::BuildDate(), KKB::operator<<(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
 {
   return StrFormatInt (hour, "00") + ":" + StrFormatInt (minute, "00") + ":" +
      StrFormatInt (second, "00");
 }
KKStr TimeType::HHMMSS () const
Definition at line 847 of file DateTime.cpp.
References KKB::KKStr::operator+(), and KKB::StrFormatInt().
Referenced by KKB::DateTime::YYYYMMDDHHMMSS().
{
  return StrFormatInt (hour, "00") + StrFormatInt (minute, "00") +
      StrFormatInt (second, "00");
}
uchar KKB::TimeType::Hour () const [inline]
Definition at line 165 of file DateTime.h.
Referenced by KKB::DateTime::AddHours(), KKB::DateTime::HH_MM_SS(), and KKB::operator<<().
{return hour;}
void KKB::TimeType::Hour (uchar _hour) [inline]
Definition at line 173 of file DateTime.h.
Referenced by KKB::DateTime::AddHours().
{hour = _hour;}
uchar KKB::TimeType::Minute () const [inline]
Definition at line 166 of file DateTime.h.
Referenced by KKB::DateTime::AddMinutes(), KKB::DateTime::HH_MM_SS(), and KKB::operator<<().
{return minute;}
void KKB::TimeType::Minute (uchar _minute) [inline]
Definition at line 174 of file DateTime.h.
Referenced by KKB::DateTime::AddMinutes().
{minute = _minute;}
bool TimeType::operator!= (const TimeType & right) const
Definition at line 897 of file DateTime.cpp.
{
  return (Compare (right) == 0);
}
TimeType TimeType::operator+ (const TimeType & right) const
Add one day
Definition at line 946 of file DateTime.cpp.
References Seconds(), and TimeType().
{
  kkint32 totSeconds = Seconds () + right.Seconds ();
  return TimeType (totSeconds);
}
TimeType TimeType::operator- (const TimeType & right) const
Subtract one day
Definition at line 953 of file DateTime.cpp.
References Seconds(), and TimeType().
{
  kkint32 totSeconds = Seconds () - right.Seconds ();
  return TimeType (totSeconds);
}
bool TimeType::operator< (const TimeType & right) const
Definition at line 919 of file DateTime.cpp.
{
  return (Compare (right) < 0);
}
bool TimeType::operator<= (const TimeType & right) const
Definition at line 961 of file DateTime.cpp.
{
  return (Compare (right) <= 0);
}
TimeType & TimeType::operator= (const TimeType & right)
Definition at line 879 of file DateTime.cpp.
Referenced by KKB::DateTime::DateTime(), and KKB::DateTime::operator=().
{
  hour = right.hour;
  minute = right.minute;
  second = right.second;
  return *this;
}
bool TimeType::operator== (const TimeType & right) const
Definition at line 890 of file DateTime.cpp.
{
  return (Compare (right) == 0);
}
bool TimeType::operator> (const TimeType & right) const
Definition at line 905 of file DateTime.cpp.
{
  return (Compare (right) > 0);
}
bool TimeType::operator>= (const TimeType & right) const
Definition at line 912 of file DateTime.cpp.
{
  return (Compare (right) >= 0);
}
uchar KKB::TimeType::Second () const [inline]
Definition at line 167 of file DateTime.h.
Referenced by KKB::DateTime::AddSeconds(), KKB::DateTime::HH_MM_SS(), and KKB::operator<<().
{return second;}
void KKB::TimeType::Second (uchar _second) [inline]
Definition at line 175 of file DateTime.h.
Referenced by KKB::DateTime::AddSeconds().
{second = _second;}
kkuint32 TimeType::Seconds () const
Definition at line 925 of file DateTime.cpp.
Referenced by operator+(), KKB::DateTime::operator+(), operator-(), KKB::DateTime::operator-(), KKB::DateTime::Seconds(), and KKB::DateTime::ToSeconds().
{
  return hour * 3600 + minute * 60 + second;
}
double TimeType::ToHours () const
Definition at line 931 of file DateTime.cpp.
Referenced by KKB::DateTime::ToHours().
{
  return (double)hour + (double)(minute * 60 + second) / 3600.0;
}
double TimeType::ToMinutes () const
Definition at line 937 of file DateTime.cpp.
{
  return (double)hour + (double)(minute * 60 + second) / 60.0;
}
Friends And Related Function Documentation
friend class DateTime [friend]
Definition at line 192 of file DateTime.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/DateTime.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/DateTime.cpp