SVM289_MFS::QMatrix Class Reference
Public Member Functions
virtual ~QMatrix ()
virtual Qfloat * get_Q (kkint32 column, kkint32 len) const =0
virtual Qfloat * get_QD () const =0
virtual void swap_index (kkint32 i, kkint32 j)=0
Detailed Description
Definition at line 813 of file svm2.cpp.
Constructor & Destructor Documentation
virtual SVM289_MFS::QMatrix::~QMatrix () [inline], [virtual]
Definition at line 819 of file svm2.cpp.
{}
Member Function Documentation
virtual Qfloat* SVM289_MFS::QMatrix::get_Q (kkint32 column, kkint32 len) const [pure virtual]
Implemented in SVM289_MFS::SVR_Q, SVM289_MFS::ONE_CLASS_Q, SVM289_MFS::SVC_Q, and SVM289_MFS::Kernel.
Referenced by SVM289_MFS::Solver::reconstruct_gradient(), SVM289_MFS::Solver::select_working_set(), and SVM289_MFS::Solver::Solve().
virtual Qfloat* SVM289_MFS::QMatrix::get_QD () const [pure virtual]
Implemented in SVM289_MFS::SVR_Q, SVM289_MFS::ONE_CLASS_Q, SVM289_MFS::SVC_Q, and SVM289_MFS::Kernel.
Referenced by SVM289_MFS::Solver::Solve().
virtual void SVM289_MFS::QMatrix::swap_index (kkint32 i, kkint32 j) [pure virtual]
Implemented in SVM289_MFS::SVR_Q, SVM289_MFS::ONE_CLASS_Q, SVM289_MFS::SVC_Q, and SVM289_MFS::Kernel.
Referenced by SVM289_MFS::Solver::swap_index().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm2.cpp