KKLSC::ScannerFile3BitEncoded Class Reference
Implements a 3 bit Encoded format.
#include <ScannerFile3BitEncoded.h>
Classes
union OpRec
struct OpRec4RawPixels
struct OpRecBlackOuts
struct OpRecRunLen
struct OpRecSpaces
struct OpRecTextBlock
Public Types
typedef ScannerFile3BitEncoded * ScannerFile3BitEncodedPtr
Public Member Functions
ScannerFile3BitEncoded (const KKStr &_fileName, RunLog &_log)
ScannerFile3BitEncoded (const KKStr &_fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog &_log)
virtual ~ScannerFile3BitEncoded ()
virtual Format FileFormat () const
virtual void ScanRate (float _scanRate)
virtual void WriteTextBlock (const uchar *txtBlock, kkuint32 txtBlockLen)
Static Public Member Functions
static const uchar * CompensationTable ()
Protected Member Functions
kkuint32 ReadBufferFrame ()
Read on one Scanner File Frame.
virtual kkint64 SkipToNextFrame ()
Skip to start of next frame returning back byte offset of that frame.
virtual void WriteBufferFrame ()
Write the contents of 'frameBuffer' to he end of the scanner file.
Additional Inherited Members
Detailed Description
Implements a 3 bit Encoded format.
This is a very simple implementation of run-length compression only background pixels (0) and Foreground Pixels(7/255) will be compressed by groups of 4. All pixels will be translated from 8 bit to 3 bit.
All data will be stored in two byte records with the exception of text. each 2 byte record will start with a 3 bit OpCode and a one bit eol flag. the rest of the 12 bits will be organized depending on the opcode field.
 Bits
 ======
 0 - 2: OP-Code
 3 - 3: EOL Flag; End of ScanLine '0' = Not end of line, '1' = End of line.
Op-Code
  0: Text Block
     Bits 4 - 15 Length of text block in 4 byte groups. So number in this field
                  is multiplied by 4 to get the total number of bytes. This allows
                  for up to (4096 * 4) bytes.
  1: 4 Raw Bytes
     Pix0 Pix1 Pix2 Pix
     (4-6) (7-9) (10-12) (13-15)
  2: Number of White Spaces
     Bits 4 - 15 Number of 4 pixels that are background (0). The total length of
                  this field is this number times 4 allowing for a run-length of up
                  to (4 * 4096) spaces divisible by 4.
  3: Number of Black Spaces
     Bits 4 - 15 Number of 4 pixels that are foreground (7/255). The total length of
                  this field is this number times 4 allowing for a run-length of up
                  to (4 * 4096) Foreground pixels (7/255) divisible by 4.
  4: Instrument Data
     Bits 3 - 6
-Bit to 8-bit Translation
  0: 0
  1: 36
  2: 73
  3: 109
  4: 145
  5: 181
  6: 218
  7: 255
-Bit to 3-bit Translation
   0 -> 31: 0
  32 -> 63: 1
  64 -> 95: 2
  96 -> 127: 3
 128 -> 158: 4
 159 -> 190: 5
 191 -> 222: 6
 223 -> 255; 7
Definition at line 70 of file ScannerFile3BitEncoded.h.
Member Typedef Documentation
typedef ScannerFile3BitEncoded* KKLSC::ScannerFile3BitEncoded::ScannerFile3BitEncodedPtr
Definition at line 73 of file ScannerFile3BitEncoded.h.
Constructor & Destructor Documentation
ScannerFile3BitEncoded::ScannerFile3BitEncoded (const KKStr & _fileName, RunLog & _log)
Definition at line 97 of file ScannerFile3BitEncoded.cpp.
References KKLSC::ScannerFile::ScannerFile().
                                                :
  ScannerFile (_fileName, _log),
  outputBuff (NULL),
  outputBuffLen (0),
  workLine (NULL),
  workLineLen (0)
{
  BuildConversionTables ();
  AllocateWorkLineAndOutputBuf ();
  memset (fourSpaces, 0, sizeof (fourSpaces));
  memset (fourBlackOuts, 7, sizeof (fourBlackOuts)); // In 3bit world '7' = 255
}
ScannerFile3BitEncoded::ScannerFile3BitEncoded (const KKStr & _fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog & _log)
Definition at line 115 of file ScannerFile3BitEncoded.cpp.
References KKLSC::ScannerFile::ScannerFile().
                                                :
  ScannerFile (_fileName, _pixelsPerScanLine, _frameHeight, _log),
  outputBuff (NULL),
  outputBuffLen (0),
  workLine (NULL),
  workLineLen (0)
{
  BuildConversionTables ();
  AllocateWorkLineAndOutputBuf ();
  memset (fourSpaces, 0, sizeof (fourSpaces));
  memset (fourBlackOuts, 7, sizeof (fourBlackOuts));
}
ScannerFile3BitEncoded::~ScannerFile3BitEncoded (void) [virtual]
Definition at line 135 of file ScannerFile3BitEncoded.cpp.
{
  if (opened)
    Close ();
  delete outputBuff; outputBuff = NULL;
  delete workLine; workLine = NULL;
}
Member Function Documentation
const uchar * ScannerFile3BitEncoded::CompensationTable () [static]
Definition at line 183 of file ScannerFile3BitEncoded.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKLSC::ScannerFile::ConpensationTable().
{
  GlobalGoalKeeper::StartBlock ();
  if (!compensationTable)
    BuildConversionTables ();
  GlobalGoalKeeper::EndBlock ();
  return compensationTable;
}
virtual Format KKLSC::ScannerFile3BitEncoded::FileFormat () const [inline], [virtual]
Reimplemented from KKLSC::ScannerFile.
Definition at line 91 of file ScannerFile3BitEncoded.h.
References KKLSC::ScannerFile::sf3BitEncoded.
{return Format::sf3BitEncoded;}
kkuint32 ScannerFile3BitEncoded::ReadBufferFrame () [protected], [virtual]
Read on one Scanner File Frame.
Implements KKLSC::ScannerFile.
Definition at line 230 of file ScannerFile3BitEncoded.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::frameBuffer, KKLSC::ScannerFile::frameBufferFileOffsetLast, KKLSC::ScannerFile::frameBufferFileOffsetNext, KKLSC::ScannerFile::frameBufferLen, KKLSC::ScannerFile::frameBufferNextLine, and KKB::osFTELL().
{
  frameBufferLen = 0;
  frameBufferNextLine = 0;
  if (feof (file) != 0)
  {
    memset (frameBuffer, 0, frameBufferSize);
    return 0;
  }
  frameBufferFileOffsetLast = osFTELL (file);
  kkuint32 numScanLinesReadThisFrameBuffer = 0;
  uchar* buffPtr = frameBuffer;
  while ((feof (file) == 0) && (numScanLinesReadThisFrameBuffer <
      frameHeight))
  {
    GetNextScanLine (buffPtr, pixelsPerScanLine);
    frameBufferLen += pixelsPerScanLine;
    buffPtr += pixelsPerScanLine;
    ++numScanLinesReadThisFrameBuffer;
  }
  bool endOfFileFound = (feof (file) != 0);
  if (endOfFileFound)
    cerr << "end of file was found." << endl;
  frameBufferFileOffsetNext = osFTELL (file);
  frameBufferNextLine = 0;
  return numScanLinesReadThisFrameBuffer;
} /* ReadBufferFrame */
void ScannerFile3BitEncoded::ScanRate (float _scanRate) [virtual]
Reimplemented from KKLSC::ScannerFile.
Definition at line 222 of file ScannerFile3BitEncoded.cpp.
{
  ScannerFile::ScanRate (_scanRate);
}
kkint64 ScannerFile3BitEncoded::SkipToNextFrame () [protected], [virtual]
Skip to start of next frame returning back byte offset of that frame.
This will be called by the 'UpdateFrameOffset' and 'DetermineFrameOffsetForFrame' methods used to build the 'frameOffsets' table. It is important that the implementation of this method NOT update the frameBuffer fields; such as 'frameBuffer', 'frameBufferNextLine', etc .....
Implements KKLSC::ScannerFile.
Definition at line 263 of file ScannerFile3BitEncoded.cpp.
References KKLSC::ScannerFile::pixelsPerScanLine.
{
  uchar* scanLine = new uchar[pixelsPerScanLine];
  kkuint32 numScanLinesReadThisFrameBuffer = 0;
  while ((feof (file) == 0) && (numScanLinesReadThisFrameBuffer <
      frameHeight))
  {
    GetNextScanLine (scanLine, pixelsPerScanLine);
    ++numScanLinesReadThisFrameBuffer;
  }
  delete[] scanLine;
  scanLine = NULL;
  if (feof (file) != 0)
    return -1;
  else
    return osFTELL (file);
} /* SkipToNextFrame */
void ScannerFile3BitEncoded::WriteBufferFrame () [protected], [virtual]
Write the contents of 'frameBuffer' to he end of the scanner file.
Todo
Todo We need to implement a 64 bit ftell function for non windows; this will involve implementation of '#define _FILE_OFFSET_BITS 64' and ftell; probably thru macros in the `FirstIncludes.h` file.
Implements KKLSC::ScannerFile.
Definition at line 458 of file ScannerFile3BitEncoded.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::fileSizeInBytes, KKLSC::ScannerFile::frameBuffer, KKLSC::ScannerFile::frameBufferFileOffsetLast, KKLSC::ScannerFile::frameBufferFileOffsetNext, KKLSC::ScannerFile::frameBufferNextLine, KKB::osFTELL(), and KKLSC::ScannerFile::pixelsPerScanLine.
{
  frameBufferFileOffsetLast = osFTELL (file);
  //nextScanLineOffset = osFTELL (file);
  kkuint32 frameRow = 0;
  uchar* framePtr = frameBuffer;
  while (frameRow < frameBufferNextLine)
  {
    WriteNextScanLine (framePtr, pixelsPerScanLine);
    framePtr += pixelsPerScanLine;
    ++frameRow;
  }
 
  #if defined(OS_WINDOWS)
    frameBufferFileOffsetNext = osFTELL (file);
  #else
    /**
     *@todo We need to implement a 64 bit ftell function for non windows; this will involve
     * implementation of '#define _FILE_OFFSET_BITS 64' and ftell; probably thru macros
     * in the "FirstIncludes.h" file.
     */
  #endif
  fileSizeInBytes = frameBufferFileOffsetNext;
} /* WriteBufferFrame*/
void ScannerFile3BitEncoded::WriteTextBlock (const uchar * txtBlock, kkuint32 txtBlockLen) [virtual]
Implements KKLSC::ScannerFile.
Definition at line 683 of file ScannerFile3BitEncoded.cpp.
References KKLSC::ScannerFile3BitEncoded::OpRecTextBlock::endOfTextBlock, KKLSC::ScannerFile::file, KKLSC::ScannerFile::fileSizeInBytes, KKLSC::ScannerFile3BitEncoded::OpRecTextBlock::length, KKLSC::ScannerFile3BitEncoded::OpRecTextBlock::opCode, KKB::osFTELL(), and KKLSC::ScannerFile3BitEncoded::OpRec::textBlock.
{
  kkint32 charsLeft = txtBlockLen;
  const uchar* txtBlockPtr = txtBlock;
  while (charsLeft > 0)
  {
    kkint32 charsToWrite = Min (4096, charsLeft);
    OpRec rec;
    rec.textBlock.opCode = 0;
    rec.textBlock.endOfTextBlock = (charsToWrite < charsLeft) ? 0 : 1;
    rec.textBlock.length = charsToWrite;
    fwrite (&rec, sizeof (rec), 1, file);
    fwrite (txtBlockPtr, 1, charsToWrite, file);
    charsLeft -= charsToWrite;
    txtBlockPtr += charsToWrite;
  }
  //nextScanLineOffset = osFTELL (file);
  fileSizeInBytes = osFTELL (file);
} /* WriteTextBlock */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFile3BitEncoded.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFile3BitEncoded.cpp