KKB::MorphOpBmiFiltering Class Reference
#include <MorphOpBmiFiltering.h>
Public Member Functions
MorphOpBmiFiltering ()
virtual ~MorphOpBmiFiltering ()
kkint32 BeltWidth () const
kkint32 BoundingLength () const
kkint32 BoundingWidth () const
float EigenRatio () const
float EstimatedBmi () const
kkint32 FirstQtrWeight () const
kkint32 ForthQtrWeight () const
float HeadTailRatio () const
float LengthVsWidth () const
kkint32 MemoryConsumedEstimated () const
virtual OperationType Operation () const
float OrientationAngle () const
virtual RasterPtr PerformOperation (RasterConstPtr _image)
Additional Inherited Members
Detailed Description
Definition at line 25 of file MorphOpBmiFiltering.h.
Constructor & Destructor Documentation
MorphOpBmiFiltering::MorphOpBmiFiltering ()
Definition at line 23 of file MorphOpBmiFiltering.cpp.
References KKB::MorphOp::MorphOp().
                                         :
  MorphOp ()
{
}
MorphOpBmiFiltering::~MorphOpBmiFiltering () [virtual]
Definition at line 30 of file MorphOpBmiFiltering.cpp.
{
}
Member Function Documentation
kkint32 KKB::MorphOpBmiFiltering::BeltWidth () const [inline]
Definition at line 44 of file MorphOpBmiFiltering.h.
{return beltWidth;}
kkint32 KKB::MorphOpBmiFiltering::BoundingLength () const [inline]
Definition at line 45 of file MorphOpBmiFiltering.h.
{return boundingLength;}
kkint32 KKB::MorphOpBmiFiltering::BoundingWidth () const [inline]
Definition at line 46 of file MorphOpBmiFiltering.h.
{return boundingWidth;}
float KKB::MorphOpBmiFiltering::EigenRatio () const [inline]
Definition at line 38 of file MorphOpBmiFiltering.h.
{return eigenRatio;}
float KKB::MorphOpBmiFiltering::EstimatedBmi () const [inline]
Definition at line 52 of file MorphOpBmiFiltering.h.
{return estimatedBmi;}
kkint32 KKB::MorphOpBmiFiltering::FirstQtrWeight () const [inline]
Definition at line 41 of file MorphOpBmiFiltering.h.
{return firstQtrWeight;}
kkint32 KKB::MorphOpBmiFiltering::ForthQtrWeight () const [inline]
Definition at line 42 of file MorphOpBmiFiltering.h.
{return forthQtrWeight;}
float KKB::MorphOpBmiFiltering::HeadTailRatio () const [inline]
Definition at line 50 of file MorphOpBmiFiltering.h.
{return headTailRatio;}
float KKB::MorphOpBmiFiltering::LengthVsWidth () const [inline]
Definition at line 48 of file MorphOpBmiFiltering.h.
{return lengthVsWidth;}
kkint32 MorphOpBmiFiltering::MemoryConsumedEstimated () const
Definition at line 36 of file MorphOpBmiFiltering.cpp.
{
  return sizeof (*this);
}
virtual OperationType KKB::MorphOpBmiFiltering::Operation () const [inline], [virtual]
Implements KKB::MorphOp.
Definition at line 32 of file MorphOpBmiFiltering.h.
References KKB::MorphOp::Binarize.
{return OperationType::Binarize;}
float KKB::MorphOpBmiFiltering::OrientationAngle () const [inline]
Definition at line 39 of file MorphOpBmiFiltering.h.
{return orientationAngle;}
RasterPtr MorphOpBmiFiltering::PerformOperation (RasterConstPtr _image) [virtual]
Definition at line 193 of file MorphOpBmiFiltering.cpp.
References KKB::Raster::BackgroundPixelTH(), KKB::MorphOp::SetSrcRaster(), and KKB::MorphOp::srcRaster.
{
  SetSrcRaster (_image);
  RasterPtr rotatedImage = NULL;
  // 1) Remove Appendages.
  // 2) Perform Length vs Width
  uchar binarizeTHmin = srcRaster->BackgroundPixelTH () + 1;
  uchar binarizeTHmax = 125;
  rotatedImage = ProcessBmi (binarizeTHmax);
  kkint32 rectangularAreaMax = boundingLength * boundingWidth;
  delete rotatedImage; rotatedImage = NULL;
  rotatedImage = ProcessBmi (binarizeTHmin);
  kkint32 rectangularAreaMin = boundingLength * boundingWidth;
  if ((rectangularAreaMin > 0) && (rectangularAreaMax > 0))
  {
    if ((rectangularAreaMax / rectangularAreaMin) > 0.90)
    {
      // Not a significant amount of low intensity foreground pixels.
      delete rotatedImage;
      rotatedImage = ProcessBmi (binarizeTHmin);
      return rotatedImage;
    }
  }
  kkint32 rectangularAreaTH = (kkint32)(0.5f + (float)(rectangularAreaMax +
      rectangularAreaMin) * (1.0f / 2.0f));
  uchar binarizeTHminLast = binarizeTHmin;
  while (binarizeTHmin < binarizeTHmax)
  {
    if (boundingWidth < 5)
      break;
    delete rotatedImage;
    rotatedImage = ProcessBmi (binarizeTHmin);
    rectangularAreaMin = boundingLength * boundingWidth;
    if (boundingWidth < 3)
    {
      binarizeTHmin = binarizeTHminLast;
      delete rotatedImage;
      rotatedImage = ProcessBmi (binarizeTHmin);
      break;
    }
    binarizeTHminLast = binarizeTHmin;
    if (rectangularAreaMin < rectangularAreaTH)
      break;
    binarizeTHmin += 5;
  }
  return rotatedImage;
} /* PerformOperation */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpBmiFiltering.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/MorphOpBmiFiltering.cpp