KKB::Application Class Reference
The base class for all standalone application.
#include <Application.h>
Public Member Functions
Application ()
Constructor for Application class that will start with a default logger(RunLog),.
Application (const Application &_application)
Copy Constructor for Application class.
Application (RunLog &_log)
Constructor for Application class where we already have an existing logger '_log'.
virtual ~Application ()
bool Abort ()
Returns 'true' if application has been aborted.
void Abort (bool _abort)
Used to specify that the application is been aborted.
virtual const char * ApplicationName ()
void AssignLog (RunLog &_log)
Replaces the Log file to write to.
virtual KKStr BuildDate () const
virtual void InitalizeApplication (kkint32 argc, char **argv)
Initialized Application Instance; 1st method to be called after instance construction.
Public Attributes
RunLog & log
Protected Member Functions
virtual void DisplayCommandLineParameters ()
Will display Command Lone parameters that the 'Application' class will manage.
virtual bool ProcessCmdLineParameter (const KKStr &parmSwitch, const KKStr &parmValue)
This method will get called once for each parameter specified in the command line.
Detailed Description
The base class for all standalone application.
This class is meant to be a general class that all standalone applications should be inherited from. It supports command line processing, and logging facilities. Derived classes will need to override the virtual methods `ApplicationName`, `DisplayCommandLineParameters`, and `ProcessCmdLineParameter`. Right after an instance is created you need to call the `InitalizeApplication` method; this will start the processing of any encountered parameters. For each set of parameters encountered a call to `ProcessCmdLineParameter` will be made; this is where you can intercept and process parameters that are specific to your application. Any parameters that you do not recognized should be passed onto the base-class by calling `Application::ProcessCmdLineParameter`.
Definition at line 29 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Constructor for Application class that will start with a default logger(RunLog),.
After creating an instance of this class you initialize it by calling InitalizeApplication.
Definition at line 39 of file Application.cpp.
References KKB::KKStr::KKStr(), log, and KKB::RunLog::RunLog().
                         :
  abort (false),
  log (*(new RunLog ())),
  logFileName (),
  ourLog (NULL)
{
  ourLog = &log;
}
Application::Application (const Application & _application)
Copy Constructor for Application class.
Parameters
in _application Application instance to copy.
Definition at line 51 of file Application.cpp.
References KKB::KKStr::KKStr(), and log.
                                                         :
  abort (_application.abort),
  log (_application.log),
  logFileName (_application.logFileName),
  ourLog (_application.ourLog)
{
}
Application::Application (RunLog & _log)
Constructor for Application class where we already have an existing logger '_log'.
After creating an instance of this class you initialize it by calling InitalizeApplication.
Parameters
in _log A reference to a RunLog object.
Definition at line 29 of file Application.cpp.
References KKB::KKStr::KKStr(), and log.
                                      :
  abort (false),
  log (_log),
  logFileName (),
  ourLog (NULL)
{
}
Application::~Application () [virtual]
Definition at line 61 of file Application.cpp.
{
  delete ourLog;
  ourLog = NULL;
}
Member Function Documentation
bool KKB::Application::Abort () [inline]
Returns 'true' if application has been aborted.
You would typically call this method after you are done processing the command line to make sure that the application is to keep on running.
Definition at line 62 of file Application.h.
{return abort;}
void KKB::Application::Abort (bool _abort) [inline]
Used to specify that the application is been aborted.
If you have a reason to abort the processing of this application you would call this method to set the 'abort' flag to true. It will be the responsibility of the derived class to monitor the 'Abort' flag. If is set to true they should terminate as quickly as they can; they should also release any resources they have taken.
Parameters
in _abort Abort status to set; if set to true you are telling the application that the program needs to be terminated.
Definition at line 71 of file Application.h.
{abort = _abort;}
const char * Application::ApplicationName () [virtual]
Specify the name of the application
Definition at line 80 of file Application.cpp.
{
  return "No-Application-Name-Provided";
} /* ApplicationName */
void Application::AssignLog (RunLog & _log)
Replaces the Log file to write to.
Definition at line 87 of file Application.cpp.
References log.
{
  log = _log;
  if (ourLog)
  {
    delete ourLog;
    ourLog = NULL;
  }
} /* AssignRunLog */
KKStr Application::BuildDate () const [virtual]
Definition at line 162 of file Application.cpp.
References KKB::DateType::DateType(), KKB::TimeType::HH_MM_SS(), KKB::KKStr::operator+(), KKB::TimeType::TimeType(), and KKB::DateType::YYYY_MM_DD().
{
  DateType buildDate (__DATE__);
  TimeType buildTime (__TIME__);
  return buildDate.YYYY_MM_DD () + "-" + buildTime.HH_MM_SS ();
} /* BuildDate */
void Application::DisplayCommandLineParameters () [protected], [virtual]
Will display Command Lone parameters that the 'Application' class will manage.
Derived classes that implement this method need to call their immediate base class version of this method to include these parameters.
Definition at line 134 of file Application.cpp.
{
  cout << ApplicationName () << endl
       << endl
       << " -LogFile <FileName> File that logging messages will be written to; if left will" <
      < endl
       << " be written to Standard-Out (cout)." <
      < endl
       << endl
       << " -CmdFile <File-Name> Filename where additional command line options are stored;" <
      < endl
       << " This file can also specify additional '-CmdFile parameters." <
      < endl
       << endl;
}
void Application::InitalizeApplication (kkint32 argc, char ** argv) [virtual]
Initialized Application Instance; 1st method to be called after instance construction.
This method will scan the command line parameters for the log file options (-L, -Log, or -LogFile) and use its parameter as the LogFile name. If none is provided it will assume the stdout as the Log File to write to. It will take ownership of this log file and delete it in its destructor. Right after calling this constructor you will need to call the method ProcessCmdLineParameters.
See also
RunLog
ProcessCmdLineParameters
Parameters
in argc Number of arguments in argv.
in argv List of asciiz strings; one string for each argument.
Definition at line 69 of file Application.cpp.
References KKB::RunLog::AttachFile(), KKB::KKStr::Empty(), and log.
{
  ProcessCmdLineParameters (argc, argv);
  if (!logFileName.Empty ())
    log.AttachFile (logFileName);
}
bool Application::ProcessCmdLineParameter (const KKStr & parmSwitch, const KKStr & parmValue) [protected], [virtual]
This method will get called once for each parameter specified in the command line.
Derived classes should define this method to intercept parameters that they are interested in. Parameters are treated as pairs, Switch and Values where switches have a leading dash(`-`). The CmdLineExpander class will be used to expand any `-CmdFile` parameters.
Parameters
in parmSwitch The fill switch parameter.
in parmValue Any value parameter that followed the switch parameter.
Definition at line 149 of file Application.cpp.
{
  log.Level (-1) << endl
    << "Application::ProcessCmdLineParameter ***ERROR*** Unrecognized Parameter [" << parmSwitch << "]
        Value [" << parmValue << "]" << endl
    << endl;
  return false;
}
Member Data Documentation
RunLog& KKB::Application::log
Definition at line 143 of file Application.h.
Referenced by Application(), AssignLog(), and InitalizeApplication().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Application.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Application.cpp