KKB::Configuration Class Reference
General purpose Configuration File manager class.
#include <Configuration.h>
Classes
class ConfSection
class ConfSectionList
class Setting
class SettingList
Public Member Functions
Configuration (const KKB::KKStr &_fileName, RunLog &_log)
Configuration ()
Configuration (const Configuration &c)
virtual ~Configuration ()
const KKB::KKStr & FileName () const
const VectorKKStr & FormatErrors () const
void FormatErrorsAdd (kkint32 lineNum, const KKStr &error)
void FormatErrorsClear ()
Call this to clear all format error messages.
const VectorInt & FormatErrorsLineNums () const
VectorKKStr FormatErrorsWithLineNumbers () const
bool FormatGood () const
void FormatGood (bool _formatGood)
void GetSetting (const char *sectiopnName, kkint32 settingNum, KKStrConstPtr &name, KKStrConstPtr &value, kkint32 &lineNum)
virtual void Load (const KKB::KKStr &_fileName, RunLog &_log)
void LoadFile (RunLog &log)
virtual kkint32 MemoryConsumedEstimated () const
kkint32 NumOfSections ()
kkint32 NumOfSettings (const KKB::KKStr &sectionName) const
kkint32 NumOfSettings (kkint32 sectionNum) const
Returns number of settings for the specified section,.
void PrintFormatErrors (std::ostream &o)
bool SectionDefined (const KKB::KKStr &sectionName) const
Returns true if the section is defined.
kkint32 SectionLineNum (kkint32 sectionNum) const
KKStrConstPtr SectionName (kkint32 sectionNum) const
Returns the name of the section for specified index, if index not defined will return NULL.
kkint32 SectionNum (const KKB::KKStr &sectionName) const
KKStrConstPtr SettingName (const KKB::KKStr &sectionName, kkint32 settingNum) const
KKStrConstPtr SettingName (kkint32 sectionNum, kkint32 settingNum) const
KKStrConstPtr SettingValue (const KKB::KKStr &sectionName, const KKB::KKStr &settingName, kkint32 &lineNum) const
KKStrConstPtr SettingValue (kkint32 sectionNum, const KKB::KKStr &settingName, kkint32 &lineNum) const
KKStrConstPtr SettingValue (kkint32 sectionNum, kkint32 settingNum, kkint32 &lineNum) const
KKStr SettingValueToStr (const KKB::KKStr &sectionName, const KKB::KKStr &settingName, kkint32 &lineNum) const
KKStr SettingValueToStr (kkint32 sectionNum, const KKB::KKStr &settingName, kkint32 &lineNum) const
Detailed Description
General purpose Configuration File manager class.
This class will read and write configuration files. It understands the concept of Logical Sections and Variables. You will be able to pragmatically define Sections and Settings in these sections. Each Setting will have a related value stored with it.
*Example Configuration File
 ===========================================================
  [Header]
  ClassifierType = SVM
  Parameters = -K RBF -S SVC -G 1.76 -C 12
  RootDir = ${LarcosHmeDir}\\Classifier\\TrainingLibraries\\
 
  [Class]
  Name = Shrimp_01
 
  [Class]
  Name = Shrimp_02
 ===========================================================
There are three sections defined in the example above; Header, Class, and Class. Note that Section names do not have to be unique. You can access sections by name or index. If the name is not unique the first instance will be returned. Index values start at the top of the file, that is the first section to appear in the file is section index 0. The Setting names are of the format `SettingName = Value`. Again you will be able to access Setting by either name or index.
Definition at line 45 of file Configuration.h.
Constructor & Destructor Documentation
Configuration::Configuration (const KKB::KKStr & _fileName, RunLog & _log)
Definition at line 286 of file Configuration.cpp.
References KKB::Configuration::ConfSectionList::ConfSectionList(), KKB::KKStr::KKStr(), LoadFile(), and KKB::VectorKKStr::VectorKKStr().
                              :
  curSectionName (),
  fileName (_fileName),
  formatGood (true),
  formatErrors (),
  formatErrorsLineNums (),
  sections (NULL)
{
  sections = new ConfSectionList ();
  LoadFile (_log);
}
Configuration::Configuration ()
Definition at line 301 of file Configuration.cpp.
References KKB::Configuration::ConfSectionList::ConfSectionList(), KKB::KKStr::KKStr(), and KKB::VectorKKStr::VectorKKStr().
Referenced by KKMLL::TrainingConfiguration2::TrainingConfiguration2().
                             :
  curSectionName (),
  fileName (),
  formatGood (true),
  formatErrors (),
  formatErrorsLineNums (),
  sections (NULL)
{
  sections = new ConfSectionList ();
}
Configuration::Configuration (const Configuration & c)
Definition at line 314 of file Configuration.cpp.
References KKB::Configuration::ConfSectionList::AddConfSection(), KKB::Configuration::ConfSection::ConfSection(), KKB::Configuration::ConfSectionList::ConfSectionList(), KKB::KKStr::KKStr(), and KKB::VectorKKStr::VectorKKStr().
                                                    :
  
  curSectionName (c.curSectionName),
  fileName (c.fileName),
  formatGood (c.formatGood),
  formatErrors (c.formatErrors),
  formatErrorsLineNums (c.formatErrorsLineNums),
  sections (NULL)
{
  sections = new ConfSectionList ();
  kkint32 x;
  for (x = 0; x < sections->QueueSize (); x++)
  {
    const ConfSectionPtr cs = sections->IdxToPtr (x);
    sections->AddConfSection (new ConfSection (*cs));
  }
}
Configuration::~Configuration () [virtual]
Definition at line 336 of file Configuration.cpp.
{
  delete sections;
}
Member Function Documentation
const KKB::KKStr& KKB::Configuration::FileName () const [inline]
Definition at line 96 of file Configuration.h.
{return fileName;}
const VectorKKStr& KKB::Configuration::FormatErrors () const [inline]
Definition at line 68 of file Configuration.h.
{return formatErrors;}
void Configuration::FormatErrorsAdd (kkint32 lineNum, const KKStr & error)
Definition at line 772 of file Configuration.cpp.
{
  formatErrors.push_back (error);
  formatErrorsLineNums.push_back (lineNum);
}
void Configuration::FormatErrorsClear ()
Call this to clear all format error messages.
Definition at line 783 of file Configuration.cpp.
{
  formatErrors.clear ();
  formatErrorsLineNums.clear ();
}
const VectorInt& KKB::Configuration::FormatErrorsLineNums () const [inline]
Definition at line 69 of file Configuration.h.
{return formatErrorsLineNums;}
VectorKKStr Configuration::FormatErrorsWithLineNumbers () const
Definition at line 791 of file Configuration.cpp.
References KKB::KKStr::Concat().
{
  VectorKKStr errorMsgs;
  for (kkuint32 i = 0; i < formatErrors.size (); i++)
  {
    KKStr lineNumStr = " ";
    if (i < formatErrorsLineNums.size ())
      lineNumStr = StrFormatInt (formatErrorsLineNums[i], "0000");
    errorMsgs.push_back (lineNumStr + ":" + formatErrors[i]);
  }
  return errorMsgs;
} /* FormatErrorsWithLineNumbers */
bool KKB::Configuration::FormatGood () const [inline]
Definition at line 64 of file Configuration.h.
{return formatGood;}
void KKB::Configuration::FormatGood (bool _formatGood) [inline]
Definition at line 66 of file Configuration.h.
Referenced by LoadFile().
{formatGood = _formatGood;}
void Configuration::GetSetting (const char * sectiopnName, kkint32 settingNum, KKStrConstPtr & name, KKStrConstPtr & value, kkint32 & lineNum)
Definition at line 749 of file Configuration.cpp.
References KKB::Configuration::ConfSection::GetSettings(), and KKB::Configuration::ConfSectionList::LookUp().
{
  ConfSectionPtr section = sections->LookUp (sectionName);
  if (section)
  {
    section->GetSettings (settingNum, name, value, lineNum);
  }
  else
  {
    name = NULL;
    value = NULL;
    lineNum = -1;
  }
}
void Configuration::Load (const KKB::KKStr & _fileName, RunLog & _log) [virtual]
Definition at line 401 of file Configuration.cpp.
References LoadFile(), and KKB::KKStr::operator=().
{
  fileName = _fileName;
  LoadFile (_log);
}
void Configuration::LoadFile (RunLog & log)
Definition at line 411 of file Configuration.cpp.
References FormatGood(), KKB::KKStr::operator=(), KKB::KKStr::operator==(), KKB::osFOPEN(), and KKB::KKStr::Str().
Referenced by Configuration(), and Load().
{
  log.Level (10) << "Configuration::LoadFile: " << fileName << endl;
  kkint32 lastLineNum = 0;
  if (fileName == "")
  {
    log.Level (-1) << endl
                   << "Configuration::LoadFile ***ERROR*** File-Name is blank" << endl
                   << endl;
    FormatGood (false);
    return;
  }
  FILE* inFile = osFOPEN (fileName.Str (), "r");
  if (!inFile)
  {
    log.Level (-1) << endl
                   << "Configuration::LoadFile ***ERROR*** Opening File: " << fileName << endl
                   << endl;
    FormatGood (false);
    return;
  }
  char buff[10240];
  kkint32 lineCount = 0;
  curSectionName = "";
  ConfSectionPtr curSection = NULL;
  while (fgets (buff, sizeof (buff), inFile))
  {
    lastLineNum++;
    KKStr line (buff);
    line.TrimRight ();
    line.TrimLeft ();
    StripOutAnyComments (line);
    log.Level (70) << line << endl;
    
    StripOutAnyComments (line);
    if (line.Empty ())
    {
      // If we have a blank line, we do nothing.
    }
    else if (line.FirstChar () == '[')
    {
      // Looks like definition of new section.
      if (line.LastChar () == ']')
      {
        curSectionName = line.SubStrPart (1, line.Len () - 2);
        curSectionName.TrimLeft ();
        curSectionName.TrimRight ();
        curSectionName.Upper ();
        curSection = new ConfSection (curSectionName, lastLineNum);
        sections->AddConfSection (curSection);
        log.Level (30) << "LoadFile SectionName[" << curSectionName << "]." <<
      endl;
      }
      else
      {
        log.Level (-1) << endl
                       << "Configuration::LoadFile ***ERROR*** LineNumber[" << lastLineNum << "]
       Improper Section Name[" << line << "]." << endl
                       << endl;
        formatGood = false;
      }
    }
    else
    {
      if (!curSection)
      {
        log.Level (-1) << endl
                       << "Configuration::LoadFile ***ERROR*** Format Error LineNumber[" << lastLineNum
      << "]" << endl
                       << " No Section Defined." << endl
                       << endl;
     
        formatGood = false;
        curSectionName = "GLOBAL";
        curSection = new ConfSection (curSectionName, lastLineNum);
        sections->AddConfSection (curSection);
      }
      kkint32 equalIdx = line.LocateCharacter ('=');
      if (equalIdx < 0)
      {
        // We have a improperly formated line.
        log.Level (-1) << endl
                       << "Configuration::LoadFile ***ERROR*** LineNumber[" << lastLineNum << "]
       Improperly Formated Line[" << line << "]."
                       << endl;
        formatGood = false;
      }
      else
      {
        KKStr settingName (line.SubStrPart (0, equalIdx - 1));
        settingName.TrimLeft ();
        settingName.TrimRight ();
        settingName.Upper ();
        KKStr settingValue (line.SubStrPart (equalIdx + 1));
        settingValue.TrimLeft ();
        settingValue.TrimRight ();
        log.Level (30) << "LoadFile SectionName[" << curSectionName << "], "
                       << "Setting[" << settingName << "], Value[" << settingValue << "]."
                       << endl;
        curSection->AddSetting (settingName, settingValue, lastLineNum);
      }
      lineCount++;
    }
  }
  fclose (inFile);
} /* LoadFile */
kkint32 Configuration::MemoryConsumedEstimated () const [virtual]
Definition at line 343 of file Configuration.cpp.
References KKB::Configuration::ConfSectionList::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = sizeof (Configuration)
    + curSectionName.MemoryConsumedEstimated ()
    + fileName.MemoryConsumedEstimated ()
    + (kkint32)formatErrors.size () * 100
    + (kkint32)formatErrorsLineNums.size () * sizeof (kkint32);
  if (sections)
    memoryConsumedEstimated += sections->MemoryConsumedEstimated ();
  return memoryConsumedEstimated;
} /* MemoryConsumedEstimated */
kkint32 Configuration::NumOfSections ()
Definition at line 541 of file Configuration.cpp.
{
  return sections->QueueSize ();
}
kkint32 Configuration::NumOfSettings (const KKB::KKStr & sectionName) const
Definition at line 548 of file Configuration.cpp.
References KKB::Configuration::ConfSectionList::LookUp(), and KKB::Configuration::ConfSection::NumOfSettings().
{
  ConfSectionPtr section = sections->LookUp (sectionName);
  if (!section)
    return (-1);
  return section->NumOfSettings ();
}
kkint32 Configuration::NumOfSettings (kkint32 sectionNum) const
Returns number of settings for the specified section,.
Definition at line 561 of file Configuration.cpp.
{
  if ((sectionNum < 0) || (sectionNum >= sections->QueueSize ()))
    return -1;
  return sections->IdxToPtr (sectionNum) ->NumOfSettings ();
}
void Configuration::PrintFormatErrors (std::ostream & o)
Definition at line 387 of file Configuration.cpp.
{
  o << endl
    << "Num" << "\t" << "LineNum" << "\t" << "Description" << endl;
  for (kkuint32 idx = 0; idx < formatErrors.size (); ++idx)
  {
    o << idx << "\t" << formatErrorsLineNums[idx] << "\t" << formatErrors[idx] <<
      endl;
  }
} /* PrintFormatErrors */
bool Configuration::SectionDefined (const KKB::KKStr & sectionName) const
Returns true if the section is defined.
Definition at line 574 of file Configuration.cpp.
References KKB::Configuration::ConfSectionList::LookUp().
{
  ConfSectionPtr section = sections->LookUp (sectionName);
  return (section != NULL);
}
kkint32 Configuration::SectionLineNum (kkint32 sectionNum) const
Definition at line 610 of file Configuration.cpp.
References KKB::Configuration::ConfSection::LineNum().
{
  ConfSectionPtr section = sections->IdxToPtr (sectionNum);
  if (!section)
    return -1;
  else
    return section->LineNum ();
}
KKStrConstPtr Configuration::SectionName (kkint32 sectionNum) const
Returns the name of the section for specified index, if index not defined will return NULL.
Definition at line 582 of file Configuration.cpp.
References KKB::Configuration::ConfSection::Name().
{
  ConfSectionPtr section = sections->IdxToPtr (sectionNum);
  if (!section)
    return NULL;
  else
    return section->Name ();
}
kkint32 Configuration::SectionNum (const KKB::KKStr & sectionName) const
Definition at line 593 of file Configuration.cpp.
Referenced by SettingValue(), and SettingValueToStr().
{
  if (!sections)
    return -1;
  kkuint32 idx = 0;
  while (idx < sections->size ())
  {
    if (sections->IdxToPtr(idx)->Name ()->EqualIgnoreCase (sectionName))
      return (kkint32)idx;
    idx++;
  }
  return -1;
}
KKStrConstPtr Configuration::SettingName (const KKB::KKStr & sectionName, kkint32 settingNum) const
Definition at line 622 of file Configuration.cpp.
References KKB::Configuration::ConfSectionList::LookUp(), and KKB::Configuration::ConfSection::SettingName().
{
  ConfSectionPtr section = sections->LookUp (sectionName);
  if (!section)
    return NULL;
  return section->SettingName (settingNum);
}
KKStrConstPtr Configuration::SettingName (kkint32 sectionNum, kkint32 settingNum) const
Definition at line 636 of file Configuration.cpp.
{
  if ((sectionNum < 0) || (sectionNum >= sections->QueueSize ()))
    return NULL;
  if ((settingNum < 0) || (settingNum >= (*sections)[sectionNum].NumOfSettings ()))
    return NULL;
  return sections->IdxToPtr (sectionNum)->SettingName (settingNum);
}
KKStrConstPtr Configuration::SettingValue (const KKB::KKStr & sectionName, const KKB::KKStr & settingName, kkint32 & lineNum) const
Definition at line 719 of file Configuration.cpp.
References SectionNum(), and SettingValue().
{
  kkint32 sectionNum = SectionNum (sectionName);
  if (sectionNum < 0)
    return NULL;
  return SettingValue (sectionNum, settingName, lineNum);
}
KKStrConstPtr Configuration::SettingValue (kkint32 sectionNum, const KKB::KKStr & settingName, kkint32 & lineNum) const
Definition at line 652 of file Configuration.cpp.
References KKB::Configuration::ConfSection::LookUpValue().
Referenced by SettingValue().
{
  KKStrConstPtr result = NULL;
  ConfSectionPtr section = sections->IdxToPtr (sectionNum);
  if (!section)
  {
    lineNum = -1;
  }
  else
  {
    result = section->LookUpValue (settingName, lineNum);
  }
  return result;
}
KKStrConstPtr Configuration::SettingValue (kkint32 sectionNum, kkint32 settingNum, kkint32 & lineNum) const
Definition at line 701 of file Configuration.cpp.
{
  if ((sectionNum < 0) || (sectionNum >= sections->QueueSize ()))
    return NULL;
  if ((settingNum < 0) || (settingNum >= (*sections)[sectionNum].NumOfSettings ()))
    return NULL;
  return sections->IdxToPtr (sectionNum)->SettingValue (settingNum, lineNum);
}
KKStr Configuration::SettingValueToStr (const KKB::KKStr & sectionName, const KKB::KKStr & settingName, kkint32 & lineNum) const
Definition at line 733 of file Configuration.cpp.
References SectionNum(), and SettingValueToStr().
{
  kkint32 sectionNum = SectionNum (sectionName);
  if (sectionNum < 0)
    return NULL;
  return SettingValueToStr (sectionNum, settingName, lineNum);
}
KKStr Configuration::SettingValueToStr (kkint32 sectionNum, const KKB::KKStr & settingName, kkint32 & lineNum) const
Definition at line 672 of file Configuration.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), KKB::KKStr::KKStr(), and KKB::Configuration::ConfSection::LookUpValue().
Referenced by SettingValueToStr().
{
  KKStrConstPtr result = NULL;
  ConfSectionPtr section = sections->IdxToPtr (sectionNum);
  if (!section)
  {
    lineNum = -1;
  }
  else
  {
    result = section->LookUpValue (settingName, lineNum);
  }
  if (result == NULL)
    return KKStr::EmptyStr ();
  else
    return KKStr (*result);
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Configuration.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Configuration.cpp