KKMLL::FeatureVectorList::RootNameComparrison Class Reference
Public Member Functions
RootNameComparrison ()
bool operator() (FeatureVectorPtr p1, FeatureVectorPtr p2)
Detailed Description
Definition at line 1963 of file FeatureVector.cpp.
Constructor & Destructor Documentation
KKMLL::FeatureVectorList::RootNameComparrison::RootNameComparrison () [inline]
Definition at line 1966 of file FeatureVector.cpp.
{}
Member Function Documentation
bool KKMLL::FeatureVectorList::RootNameComparrison::operator() (FeatureVectorPtr p1, FeatureVectorPtr p2) [inline]
Definition at line 1968 of file FeatureVector.cpp.
References KKB::KKStr::Concat(), KKMLL::FeatureVector::ExampleFileName(), KKB::KKStr::operator<(), and KKB::osGetRootNameWithExtension().
  {
    KKStr root1 = osGetRootNameWithExtension (p1->
      ExampleFileName ());
    KKStr root2 = osGetRootNameWithExtension (p2->
      ExampleFileName ());
    return (root1 < root2);
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureVector.cpp