KKMLL::FeatureFileIO Class Reference
Base class for all FeatureFileIO classes.
#include <FeatureFileIO.h>
Public Types
typedef FeatureFileIO * FeatureFileIOPtr
Public Member Functions
FeatureFileIO (const KKStr &_driverName, bool _canRead, bool _canWrite)
virtual ~FeatureFileIO ()
void AppendToFile (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, RunLog &log)
bool CanRead ()
bool CanWrite ()
const KKStr & DriverName ()
virtual FeatureVectorListPtr FeatureDataReSink (FactoryFVProducerPtr _fvProducerFactory, const KKStr &_dirName, const KKStr &_fileName, MLClassPtr _unknownClass, bool _useDirectoryNameForClassName, MLClassList &_mlClasses, VolConstBool &_cancelFlag, bool &_changesMade, KKB::DateTime &_timeStamp, RunLog &_log)
Synchronizes the contents of a feature data file with a directory of images.
virtual FileDescPtr GetFileDesc (const KKStr &_fileName, std::istream &_in, MLClassListPtr _classes, kkint32 &_estSize, KKStr &_errorMessage, RunLog &_log)=0
Create a FileDesc object from the input stream '_in'.
virtual FeatureVectorListPtr LoadFeatureFile (const KKStr &_fileName, MLClassList &_mlClasses, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_successful, bool &_changesMade, RunLog &_log)
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
virtual FeatureVectorListPtr LoadFile (const KKStr &_fileName, const FileDescPtr _fileDesc, MLClassList &_classes, std::istream &_in, kkint32 _maxCount, VolConstBool &_cancelFlag, bool &_changesMade, KKStr &_errorMessage, RunLog &_log)=0
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
FeatureVectorListPtr LoadInSubDirectoryTree (FactoryFVProducerPtr _fvProducerFactory, KKStr _rootDir, MLClassList &_mlClasses, bool _useDirectoryNameForClassName, VolConstBool &_cancelFlag, bool _rewiteRootFeatureFile, RunLog &_log)
Creates a feature vector list of all images located in the specified sub-directory tree.
virtual void SaveFeatureFile (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, RunLog &_log)
Save examples to 'fileName'.
void SaveFeatureFileMultipleParts (const KKStr &_fileName, FeatureNumListConst &_selFeatures, FeatureVectorList &_examples, VolConstBool &_cancelFlag, bool &_successful, RunLog &_log)
Saves the feature file in multiple parts with no one single part larger that 64k examples.
virtual void SaveFile (FeatureVectorList &_data, const KKStr &_fileName, FeatureNumListConst &_selFeatures, std::ostream &_out, kkuint32 &_numExamplesWritten, VolConstBool &_cancelFlag, bool &_successful, KKStr &_errorMessage, RunLog &_log)=0
To be implemented by derived classes; save examples to output stream '_out'.
Static Public Member Functions
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr)
static FeatureFileIOPtr FileFormatFromStr (const KKStr &_fileFormatStr, bool _canRead, bool _canWrite)
static KKStr FileFormatsReadAndWriteOptionsStr ()
static KKStr FileFormatsReadOptionsStr ()
static KKStr FileFormatsWrittenOptionsStr ()
static void FinalCleanUp ()
Before you terminate your application and after all FeatureFileIO activity is done call this method to destroy statically dynamically allocated data structures.
static VectorKKStr RegisteredDriverNames (bool canRead, bool canWrite)
static void RegisterFeatureFileIODriver (FeatureFileIOPtr _driver)
For each feature file format register the appropriate driver through this static method.
Protected Member Functions
void GetLine (std::istream &_in, KKStr &_line, bool &_eof)
void GetToken (std::istream &_in, const char *_delimiters, KKStr &_token, bool &_eof, bool &_eol)
Will retrieve the next token from the input stream.
Static Protected Member Functions
static void RegisterDriver (FeatureFileIOPtr driver)
Detailed Description
Base class for all FeatureFileIO classes.
This is a abstract class. For each type of FeatureFile you will need to implement a separate class derived from this class that supports the specific file format. You only need to implement the pure virtual functions.
If you create a new FeatureFileIO class you will need to modify 'RegisterAllDrivers' method in FeatureFileIO.cpp.
Definition at line 48 of file FeatureFileIO.h.
Member Typedef Documentation
typedef FeatureFileIO* KKMLL::FeatureFileIO::FeatureFileIOPtr
Definition at line 51 of file FeatureFileIO.h.
Constructor & Destructor Documentation
FeatureFileIO::FeatureFileIO (const KKStr & _driverName, bool _canRead, bool _canWrite)
Definition at line 322 of file FeatureFileIO.cpp.
References KKB::KKStr::KKStr(), and KKB::KKStr::ToLower().
Referenced by KKMLL::FeatureFileIOArff::FeatureFileIOArff(), KKMLL::FeatureFileIOC45::FeatureFileIOC45(), KKMLL::FeatureFileIOColumn::FeatureFileIOColumn(), KKMLL::FeatureFileIODstWeb::FeatureFileIODstWeb(), KKMLL::FeatureFileIORoberts::FeatureFileIORoberts(), KKMLL::FeatureFileIOSparse::FeatureFileIOSparse(), and KKMLL::FeatureFileIOUCI::FeatureFileIOUCI().
                              :
   canRead (_canRead),
   canWrite (_canWrite),
   driverName (_driverName),
   driverNameLower (_driverName.ToLower ())
{
}
FeatureFileIO::~FeatureFileIO () [virtual]
Definition at line 335 of file FeatureFileIO.cpp.
{
}
Member Function Documentation
void FeatureFileIO::AppendToFile (const KKStr & _fileName, FeatureNumListConst & _selFeatures, FeatureVectorList & _examples, kkuint32 & _numExamplesWritten, VolConstBool & _cancelFlag, bool & _successful, RunLog & log)
Definition at line 523 of file FeatureFileIO.cpp.
References KKB::KKStr::Concat(), and KKMLL::FeatureVectorList::FileDesc().
{
  _log.Level (10) << "FeatureFileIO::AppendToFile - File[" << _fileName << "]." <<
      endl;
  _successful = true;
  FileDescPtr fileDesc = _examples.FileDesc ();
  ofstream out (_fileName.Str (), ios::app);
  if (!out.is_open())
  {
    KKStr err;
    err << "AppendToFile Error Opening File[" << _fileName << "]";
    _log.Level (-1) << endl
                     << "FeatureFileIO::AppendToFile ***ERROR***" << endl
                     << endl
                     << " " << err << endl
                     << endl;
    osDisplayWarning (err);
    _successful = false;
    return;
  }
  KKStr errorMessage;
  SaveFile (_examples, _fileName, _selFeatures, out, _numExamplesWritten, _cancelFlag, _successful
      , errorMessage, _log);
  out.close ();
  return;
} /* AppendToFile */
bool KKMLL::FeatureFileIO::CanRead () [inline]
Definition at line 60 of file FeatureFileIO.h.
Referenced by FileFormatFromStr(), FileFormatsReadOptionsStr(), and RegisteredDriverNames().
{return canRead;}
bool KKMLL::FeatureFileIO::CanWrite () [inline]
Definition at line 61 of file FeatureFileIO.h.
Referenced by FileFormatFromStr(), FileFormatsReadAndWriteOptionsStr(), FileFormatsWrittenOptionsStr(), and RegisteredDriverNames().
{return canWrite;}
const KKStr& KKMLL::FeatureFileIO::DriverName () [inline]
Definition at line 284 of file FeatureFileIO.h.
Referenced by FileFormatsReadAndWriteOptionsStr(), FileFormatsReadOptionsStr(), and FileFormatsWrittenOptionsStr().
{return driverName;}
[FeatureDataReSink(FactoryFVProducerPtr _fvProducerFactory, const KKStr _dirName, const KKStr _fileName, MLClassPtr _unknownClass, bool _useDirectoryNameForClassName, MLClassList _mlClasses, VolConstBool _cancelFlag, bool _changesMade, KKB::DateTime _timeStamp, RunLog _log)]FeatureVectorListPtr FeatureFileIO::FeatureDataReSink (FactoryFVProducerPtr _fvProducerFactory, const KKStr & _dirName, const KKStr & _fileName, MLClassPtr _unknownClass, bool _useDirectoryNameForClassName, MLClassList & _mlClasses, VolConstBool & _cancelFlag, bool & _changesMade, KKB::DateTime & _timeStamp, RunLog & _log) [virtual]
Synchronizes the contents of a feature data file with a directory of images.
FeatureDataReSink
Used with applications to verify that feature file is up-to-date. Was specifically meant to work with training libraries, to account for images being added and deleted from training library. If there are no changes, then function will run very quickly.
Parameters
in _fvProducerFactory Factory that specifies the FeatureVector's we want to produce.
in _dirName,Directory where source images are located.
in _fileName,Feature file that is being synchronized.
in _unknownClass,Class to be used when class is unknown
in _useDirectoryNameForClassName,if true then class name of each entry will be set to directory name.
in _mlClasses,list of classes
in _cancelFlag Will be monitored; if it goes to 'true' will exit as soon as possible.
out _changesMade,If returns as true then there were changes made to the feature file 'fileName'. If set to false, then no changes were made.
out _timeStamp of feature file.
in _log where to send diagnostic messages to.
Returns
A FeatureVectorList derived instance ; This object will own all the examples loaded
A change in feature file version number would also cause all entries in the feature file to be recomputed. The feature file version number gets incremented whenever we change the feature file computation routine.
Definition at line 799 of file FeatureFileIO.cpp.
References KKMLL::FeatureNumList::AllFeatures(), KKMLL::FeatureVectorList::BinarySearchByName(), KKMLL::FeatureVectorProducer::ComputeFeatureVector(), KKB::KKStr::Concat(), KKB::DateTime::DateTime(), KKB::KKStr::Empty(), KKMLL::FeatureVector::ExampleFileName(), KKMLL::FactoryFVProducer::FeatureVectorListTypeId(), KKMLL::FactoryFVProducer::FileDesc(), KKMLL::FeatureVectorList::FileDesc(), KKMLL::MLClass::GetUnKnownClassStatic(), LoadFeatureFile(), KKMLL::FactoryFVProducer::ManufactureInstance(), KKMLL::FactoryFVProducer::ManufacturFeatureVectorList(), KKMLL::FeatureVector::MLClass(), KKMLL::MLClass::Name(), KKB::KKStr::operator+(), KKB::KKStr::operator=(), KKB::DateTime::operator=(), KKMLL::FileDesc::operator==(), KKB::osAddSlash(), KKB::osGetFileDateTime(), KKB::osGetListOfFiles(), KKB::osGetLocalDateTime(), KKB::osGetRootName(), KKMLL::FeatureVectorList::PushOnBack(), KKB::ReadImage(), SaveFeatureFile(), KKB::KKStrList::Sort(), KKMLL::FeatureVectorList::SortByRootName(), KKB::SupportedImageFileFormat(), KKMLL::MLClass::UnDefined(), KKMLL::FeatureVectorProducer::Version(), and KKMLL::FeatureVectorList::Version().
Referenced by LoadInSubDirectoryTree(), and KKMLL::TrainingConfiguration2::LoadOtherClasssExamples().
{
  _changesMade = false;
  _timeStamp = DateTime ();
  FileDescPtr fileDesc = _fvProducerFactory->FileDesc ();
  if (_unknownClass == NULL)
    _unknownClass = MLClass::GetUnKnownClassStatic ();
  KKStr className = _unknownClass->Name ();
  _log.Level (10) << "FeatureFileIO::FeatureDataReSink dirName: " << _dirName <<
      endl
                  << " fileName: " << _fileName << " UnKnownClass: " << className <<
      endl;
  KKStr fullFeatureFileName = osAddSlash (_dirName) + _fileName;
  bool successful = true;
  KKStr fileNameToOpen;
  if (_dirName.Empty ())
    fileNameToOpen = _fileName;
  else
    fileNameToOpen = osAddSlash (_dirName) + _fileName;
  bool versionsAreSame = false;
  FeatureVectorListPtr origFeatureVectorData
        = LoadFeatureFile (fileNameToOpen, _mlClasses, -1, _cancelFlag, successful,
      _changesMade, _log);
  if (origFeatureVectorData == NULL)
  {
    successful = false;
    origFeatureVectorData = _fvProducerFactory->ManufacturFeatureVectorList (
      true, _log);
  }
  if (_cancelFlag)
  {
    delete origFeatureVectorData; origFeatureVectorData = NULL;
    return _fvProducerFactory->ManufacturFeatureVectorList (true, _log);
  }
  FeatureVectorListPtr origFeatureData = NULL;
  if (successful &&
       (&typeid (*origFeatureVectorData) == _fvProducerFactory->
      FeatureVectorListTypeId ()) &&
       ((*(origFeatureVectorData->FileDesc ())) == (*(_fvProducerFactory->
      FileDesc ())))
      )
  {
     origFeatureData = origFeatureVectorData;
  }
  else
  {
    origFeatureData = _fvProducerFactory->ManufacturFeatureVectorList (true,
      _log);
    delete origFeatureVectorData;
    origFeatureVectorData = NULL;
  }
  KKStr fileSpec = osAddSlash (_dirName) + "*.*";
  KKStrListPtr fileNameList = osGetListOfFiles (fileSpec);
  if (!fileNameList)
  {
    // There are no Image Files, so we need to return a Empty List of Image Features.
    if (origFeatureData->QueueSize () > 0)
      _changesMade = true;
    delete origFeatureData; origFeatureData = NULL;
    return _fvProducerFactory->ManufacturFeatureVectorList (true, _log);
  }
  FeatureVectorProducerPtr fvProducer = _fvProducerFactory->
      ManufactureInstance (_log);
  if (successful)
  {
    if (origFeatureData->Version () == fvProducer->Version ())
    {
      versionsAreSame = true;
      _timeStamp = osGetFileDateTime (fileNameToOpen);
    }
    else
    {
      _changesMade = true;
    }
  }
  else
  {
    delete origFeatureData;
    origFeatureData = _fvProducerFactory->ManufacturFeatureVectorList (true,
      _log);
  }
  origFeatureData->SortByRootName (false);
  FeatureVectorListPtr extractedFeatures = _fvProducerFactory->
      ManufacturFeatureVectorList (true, _log);
  extractedFeatures->Version (fvProducer->Version ());
  fileNameList->Sort (false);
  KKStrList::iterator fnIDX;
  fnIDX = fileNameList->begin (); // fileNameList
  KKStrPtr imageFileName;
  kkint32 numImagesFoundInOrigFeatureData = 0;
  kkint32 numOfNewFeatureExtractions = 0;
  for (fnIDX = fileNameList->begin (); (fnIDX != fileNameList->end ()) && (!_cancelFlag); ++fnIDX)
  {
    imageFileName = *fnIDX;
    // pv414-_002_20140414-162243_02068814-1261.bmp
    KKStr rootName = osGetRootName (*imageFileName);
    if (rootName == "pv414-_002_20140414-162243_02068814-1261")
      cout << "Stop Here." << endl;
    bool validImageFileFormat = SupportedImageFileFormat (*imageFileName);
    
    if (!validImageFileFormat)
      continue;
    bool featureVectorCoputaionSuccessful = false;
    FeatureVectorPtr origFV = origFeatureData->
      BinarySearchByName (*imageFileName);
    if (origFV)
      numImagesFoundInOrigFeatureData++;
    if (origFV && versionsAreSame)
    {
      featureVectorCoputaionSuccessful = true;
      if (_useDirectoryNameForClassName)
      {
        if (origFV->MLClass () != _unknownClass)
        {
          _changesMade = true;
          origFV->MLClass (_unknownClass);
        }
      }
      else if ((origFV->MLClass ()->UnDefined ()) && (origFV->MLClass () != _unknownClass)
      )
      {
        _changesMade = true;
        origFV->MLClass (_unknownClass);
      }
      extractedFeatures->PushOnBack (origFV);
      origFeatureData->DeleteEntry (origFV);
    }
    else
    {
      // We either DON'T have an original image or versions are not the same.
      KKStr fullFileName = osAddSlash (_dirName) + (*imageFileName);
      FeatureVectorPtr fv = NULL;
      try
      {
        RasterPtr image = ReadImage (fullFileName);
        if (image)
          fv = fvProducer->ComputeFeatureVector (*image, _unknownClass, NULL, 1.0f,
      _log);
        delete image;
        image = NULL;
        if (fv)
          featureVectorCoputaionSuccessful = true;
        else
          featureVectorCoputaionSuccessful = false;
      }
      catch (...)
      {
        _log.Level (-1) << endl << endl
          << "FeatureDataReSink ***ERROR***" << endl
          << " Exception occurred calling constructor 'ComputeFeatureVector'." << endl
          << endl;
        featureVectorCoputaionSuccessful = false;
        fv = NULL;
      }
      if (!featureVectorCoputaionSuccessful)
      {
        _log.Level (-1) << " FeatureFileIOKK::FeatureDataReSink *** ERROR ***, Processing Image File[
      "
                       << imageFileName << "]."
                       << endl;
        delete fv;
        fv = NULL;
      }
      else
      {
        _changesMade = true;
        fv->ExampleFileName (*imageFileName);
        _log.Level (30) << fv->ExampleFileName () << " " << fv->
      OrigSize () << endl;
        extractedFeatures->PushOnBack (fv);
        numOfNewFeatureExtractions++;
        if ((numOfNewFeatureExtractions % 100) == 0)
          cout << numOfNewFeatureExtractions << " Images Extracted." << endl;
      }
    }
  }
  if (numImagesFoundInOrigFeatureData != extractedFeatures->QueueSize ())
    _changesMade = true;
  
  extractedFeatures->Version (fvProducer->Version ());
  if ((_changesMade) && (!_cancelFlag))
  {
    //extractedFeatures->WriteImageFeaturesToFile (fullFeatureFileName, RawFormat,
       FeatureNumList::AllFeatures (extractedFeatures->FileDesc ()));
    kkuint32 numExamplesWritten = 0;
    SaveFeatureFile (fullFeatureFileName,
                     FeatureNumList::AllFeatures (extractedFeatures->
      FileDesc ()),
                     *extractedFeatures,
                     numExamplesWritten,
                     _cancelFlag,
                     successful,
                     _log
                    );
    _timeStamp = osGetLocalDateTime ();
  }
  delete fvProducer; fvProducer = NULL;
  delete fileNameList; fileNameList = NULL;
  delete origFeatureData; origFeatureData = NULL;
  _log.Level (10) << "FeatureDataReSink Exiting Dir: " << _dirName <<
      endl;
  return extractedFeatures;
} /* FeatureDataReSink */
FeatureFileIOPtr FeatureFileIO::FileFormatFromStr (const KKStr & _fileFormatStr) [static]
Definition at line 197 of file FeatureFileIO.cpp.
{
  return LookUpDriver (_fileFormatStr);
}
FeatureFileIOPtr FeatureFileIO::FileFormatFromStr (const KKStr & _fileFormatStr, bool _canRead, bool _canWrite) [static]
Definition at line 205 of file FeatureFileIO.cpp.
References CanRead(), and CanWrite().
{
  FeatureFileIOPtr driver = LookUpDriver (_fileFormatStr);
  if (!driver)
    return NULL;
  if (_canRead && (!driver->CanRead ()))
    return NULL;
  if (_canWrite && (!driver->CanWrite ()))
    return NULL;
  return driver;
} /* FileFormatFromStr */
KKStr FeatureFileIO::FileFormatsReadAndWriteOptionsStr () [static]
Definition at line 272 of file FeatureFileIO.cpp.
References CanWrite(), KKB::KKStr::Concat(), DriverName(), KKB::KKStr::Empty(), and KKB::KKStr::KKStr().
{
  KKStr driversThatCanReadAndWrite (128);
  vector<FeatureFileIOPtr>* drivers = RegisteredDrivers ();
  vector<FeatureFileIOPtr>::const_iterator idx;
  for (idx = drivers->begin (); idx != drivers->end (); idx++)
  {
    FeatureFileIOPtr driver = *idx;
    if (driver->CanWrite () && driver->CanWrite ())
    {
      if (!driversThatCanReadAndWrite.Empty ())
        driversThatCanReadAndWrite << ", ";
      driversThatCanReadAndWrite << driver->DriverName ();
    }
  }
  return driversThatCanReadAndWrite;
} /* FileFormatsReadAndWriteOptionsStr */
KKStr FeatureFileIO::FileFormatsReadOptionsStr () [static]
Definition at line 227 of file FeatureFileIO.cpp.
References CanRead(), KKB::KKStr::Concat(), DriverName(), KKB::KKStr::Empty(), and KKB::KKStr::KKStr().
{
  vector<FeatureFileIOPtr>* drivers = RegisteredDrivers ();
  KKStr driversThatCanRead (128);
  vector<FeatureFileIOPtr>::const_iterator idx;
  for (idx = drivers->begin (); idx != drivers->end (); idx++)
  {
    FeatureFileIOPtr driver = *idx;
    if (driver->CanRead ())
    {
      if (!driversThatCanRead.Empty ())
        driversThatCanRead << ", ";
      driversThatCanRead << driver->DriverName ();
    }
  }
  return driversThatCanRead;
} /* FileFormatsReadOptionsStr */
KKStr FeatureFileIO::FileFormatsWrittenOptionsStr () [static]
Definition at line 249 of file FeatureFileIO.cpp.
References CanWrite(), KKB::KKStr::Concat(), DriverName(), KKB::KKStr::Empty(), and KKB::KKStr::KKStr().
{
  vector<FeatureFileIOPtr>* drivers = RegisteredDrivers ();
  KKStr driversThatCanWrite (128);
  vector<FeatureFileIOPtr>::const_iterator idx;
  for (idx = drivers->begin (); idx != drivers->end (); idx++)
  {
    FeatureFileIOPtr driver = *idx;
    if (driver->CanWrite ())
    {
      if (!driversThatCanWrite.Empty ())
        driversThatCanWrite << ", ";
      driversThatCanWrite << driver->DriverName ();
    }
  }
  return driversThatCanWrite;
} /* FileFormatsWrittenOptionsStr */
void FeatureFileIO::FinalCleanUp () [static]
Before you terminate your application and after all FeatureFileIO activity is done call this method to destroy statically dynamically allocated data structures.
This method undoes everything that 'RegisterAllDrivers' does. Its primary usefulness is aid in tracking down memory leaks. This way the '_CrtSetDbgFlag' debugging functionality will not report the memory allocated by the different feature FileIO drivers.
Definition at line 157 of file FeatureFileIO.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
{
  GlobalGoalKeeper::StartBlock ();
  if (registeredDrivers)
  {
    while (registeredDrivers->size () > 0)
    {
      FeatureFileIOPtr f = registeredDrivers->back ();
      registeredDrivers->pop_back ();
      delete f;
    }
    delete registeredDrivers;
    registeredDrivers = NULL;
  }
  GlobalGoalKeeper::EndBlock ();
} /* CleanUpFeatureFileIO */
virtual FileDescPtr KKMLL::FeatureFileIO::GetFileDesc (const KKStr & _fileName, std::istream & _in, MLClassListPtr _classes, kkint32 & _estSize, KKStr & _errorMessage, RunLog & _log) [pure virtual]
Create a FileDesc object from the input stream '_in'.
All derived classes must implement this method. It is called by 'LoadFeatureFile' before it starts reading in the feature data.
Parameters
in _fileName Name of file to read top get FileDesc data from. Ex in c45 this would be the names file.
in _in Input Stream t read from.
out _classes Must be pointing to a valid MLClassList object. As class names are encountered add them to this list.
out _estSize If you can drive the number of examples in the feature file populate this parameter.
out _errorMessage If a error in processing occurs; place a description of the error in this parameter.
   _log
void FeatureFileIO::GetLine (std::istream & _in, KKStr & _line, bool & _eof) [protected]
Definition at line 341 of file FeatureFileIO.cpp.
References KKB::KKStr::operator=().
Referenced by KKMLL::FeatureFileIODstWeb::GetFileDesc(), KKMLL::FeatureFileIOC45::GetFileDesc(), KKMLL::FeatureFileIOUCI::GetFileDesc(), KKMLL::FeatureFileIODstWeb::LoadFile(), and KKMLL::FeatureFileIOUCI::LoadFile().
{
  _line = "";
  if (_in.eof ())
  {
    _eof = true;
    return;
  }
  kkint32 ch = _in.peek ();
  while ((ch != '\n') && (ch != '\r') && (!_in.eof ()))
  {
    ch = _in.get ();
    _line.Append (ch);
    ch = _in.peek ();
  }
  if (!_in.eof ())
  {
    _in.get (); // Skip over end of line character.
    if (ch == '\n')
    {
      ch = _in.peek ();
      if (ch == '\r')
        _in.get (); // line is terminated by LineFeed + CarrageReturn; we need to skip over both.
    }
    else if (ch == '\r')
    {
      ch = _in.peek ();
      if (ch == '\n')
        _in.get (); // line is terminated by CarrageReturn + LineFeed; we need to skip over both.
    }
  }
  _eof = false;
  return;
} /* GetLine */
void FeatureFileIO::GetToken (std::istream & _in, const char * _delimiters, KKStr & _token, bool & _eof, bool & _eol) [protected]
Will retrieve the next token from the input stream.
Leading and trailing blank characters will be skipped. A token will be separated by any character in '_delimiters' or 'EndOfLine', or 'EndOfFile'. If a 'EndOfLine' or 'EndOfFile' occur while reading in a token the respective flags '_eol' and '_eof' will be set to false but the following call to this function will set the respective flag to true and return a empty token.
Parameters
in _in Stream to read from,
in _delimiters List of valid delimiter characters.
out _token token extracted from '_in'. If either '_eof' or '_eol' are set to true; then token will be empty.
out _eof Set true if at end of file;
out _eol Set true if at end of line.
Definition at line 385 of file FeatureFileIO.cpp.
References KKB::KKStr::operator=().
Referenced by KKMLL::FeatureFileIOColumn::GetFileDesc(), KKMLL::FeatureFileIOSparse::GetFileDesc(), and KKMLL::FeatureFileIOColumn::LoadFile().
{
  _token = "";
  _eof = false;
  _eol = false;
  if (_in.eof ())
  {
    _eof = true;
    _eol = true;
    return;
  }
  kkint32 ch;
  // Skip past any leading white space.
  ch = _in.peek ();
  while ((ch == ' ') && (!_in.eof ()))
  {
    _in.get ();
    ch = _in.peek ();
  }
  if (_in.eof ())
  {
    _eof = true;
    _eol = true;
    return;
  }
  if (ch == '\n')
  {
    _eol = true;
    _in.get ();
    if (_in.peek () == '\r')
      _in.get ();
    return;
  }
  if (ch == '\r')
  {
    _eol = true;
    _in.get ();
    if (_in.peek () == '\n')
      _in.get ();
    return;
  }
  while ((!_in.eof ()) && (ch != '\n') && (ch != '\r') && (strchr (_delimiters, ch) == NULL))
  {
    _in.get ();
    _token.Append ((char)ch);
    ch = _in.peek ();
  }
  if (strchr (_delimiters, ch) != NULL)
  {
    // the next character was a delimiter; in this case we want to remove from stream.
    _in.get ();
  }
  return;
} /* GetToken */
FeatureVectorListPtr FeatureFileIO::LoadFeatureFile (const KKStr & _fileName, MLClassList & _mlClasses, kkint32 _maxCount, VolConstBool & _cancelFlag, bool & _successful, bool & _changesMade, RunLog & _log) [virtual]
Loads the contents of a feature data file and returns a ImageFeaturesList container object.
Parameters
in _fileName Feature file that is being synchronized.
in,out _mlClasses All classes encountered during the loading of the feature file will be added to this list.
in _maxCount Maximum number of examples to load, -1 = load all
in _cancelFlag If this flag turns true the load will terminate and return to caller.
out _successful False will be returned if load failed.
out _changesMade If the routine had loaded the feature data determined that it needed to make changes this flag will be set 'true'.
in _log Where to send diagnostic messages to.
Returns
A ImageFeaturesList container object; this object will own all the examples loaded.
Reimplemented in KKMLL::FeatureFileIOC45.
Definition at line 463 of file FeatureFileIO.cpp.
References KKB::KKStr::Concat(), and KKMLL::FileDesc::GetExistingFileDesc().
Referenced by FeatureDataReSink(), and KKMLL::Orderings::Orderings().
{
  _log.Level (10) << "LoadFeatureFile File[" << _fileName << "] FileFormat[" << driverName << "]" <<
       endl;
  
  _changesMade = false;
  kkint32 estimatedNumOfDataItems = -1;
  
  _successful = true;
  ifstream in (_fileName.Str (), ios_base::in);
  if (!in.is_open ())
  {
    _log.Level (-1) << "LoadFeatureFile ***ERROR*** Error Opening File[" << _fileName << "]." <
      < endl;
    _successful = false;
    return NULL;
  }
  KKStr errorMessage;
  
  FileDescPtr fileDescFromFile = GetFileDesc (_fileName, in, &_mlClasses,
      estimatedNumOfDataItems, errorMessage, _log);
  if (fileDescFromFile == NULL)
  {
    _log.Level (-1) << endl << endl
                   << "FeatureFileIO::LoadFeatureFile ***ERROR*** Loading Feature File[" <<
      _fileName << "]" << endl
                   << endl;
    _successful = false;
    return NULL;
  }
  FileDescPtr fileDesc = FileDesc::GetExistingFileDesc (
      fileDescFromFile);
  in.clear ();
  in.seekg (0, ios::beg);
  FeatureVectorListPtr examples = LoadFile (_fileName, fileDesc, _mlClasses,
      in, _maxCount, _cancelFlag, _changesMade, errorMessage, _log);
  if (examples == NULL)
  {
    _successful = false;
  }
  else
  {
    _successful = true;
  }
  in.close ();
  return examples;
} /* LoadFeatureFile */
virtual FeatureVectorListPtr KKMLL::FeatureFileIO::LoadFile (const KKStr & _fileName, const FileDescPtr _fileDesc, MLClassList & _classes, std::istream & _in, kkint32 _maxCount, VolConstBool & _cancelFlag, bool & _changesMade, KKStr & _errorMessage, RunLog & _log) [pure virtual]
To be implemented by derived classes; loads the contents of a feature data file and returns a ImageFeaturesList container object.
Parameters
in _fileName Feature file that is being loaded.
in _fileDesc Description of feature data that is to be loaded.
in,out _classes All classes encountered during the loading of the feature file will be added to this list.
in _in input stream that feature data is to be loaded/read from.
in _maxCount Maximum number of examples to load, -1 = load all
in _cancelFlag If this flag turns true the load will terminate and return to caller.
out _changesMade If the routine had loaded the feature data determined that it needed to make changes this flag will be set 'true'.
out _errorMessage If an error occurs during the loading a description of this error will be placed here.
in _log Where to send diagnostic messages to.
Returns
A ImageFeaturesList container object; this object will own all the examples loaded; if an error occurs NULL will be returned.
Parameters
_maxCount Maximum # images to load.
FeatureVectorListPtr FeatureFileIO::LoadInSubDirectoryTree (FactoryFVProducerPtr _fvProducerFactory, KKStr _rootDir, MLClassList & _mlClasses, bool _useDirectoryNameForClassName, VolConstBool & _cancelFlag, bool _rewiteRootFeatureFile, RunLog & _log)
Creates a feature vector list of all images located in the specified sub-directory tree.
LoadInSubDirectoryTree
Meant to work with images, it starts at a specified sub-directory and processes all sub-directories. It makes use of FeatureDataReSink for each specific sub-directory. Will make use of FeatureData files that already exist in any of the sub-directories.
Parameters
in _fvProducerFactory Factory that specifies the FeatureVector's we want to produce.
in _rootDir Starting directory.
in,out _mlClasses,List of classes, any new classes in fileName will be added.
in _useDirectoryNameForClassName,if true set class names to sub-directory name. This happens because the user may manually move images between directories using the sub-directory name as the class name.
in _cancelFlag If turns to 'true' method is to exit asap.
in _rewiteRootFeatureFile,If true rewrite the feature file in the specified 'rootDir'. This feature file will contain all entries from all sub-directories below it.
in _log,where to send diagnostic messages to.
Returns
- A PostLarvaeFVList container object. This object will own all the examples loaded.
Parameters
_cancelFlag will be monitored, if set to True Load will terminate.
Definition at line 649 of file FeatureFileIO.cpp.
References KKMLL::FeatureVectorList::AddQueue(), KKMLL::FeatureVectorList::AllFeatures(), KKB::KKStr::Concat(), KKB::KKStr::Empty(), KKMLL::FeatureVector::ExampleFileName(), FeatureDataReSink(), KKMLL::FactoryFVProducer::FileDesc(), KKMLL::MLClass::GetClassNameFromDirName(), KKMLL::MLClassList::GetMLClassPtr(), KKMLL::MLClassList::GetUnKnownClass(), KKB::KKStr::KKStr(), LoadInSubDirectoryTree(), KKMLL::FactoryFVProducer::ManufacturFeatureVectorList(), KKB::KKStr::operator+(), KKB::KKStr::operator=(), KKB::KKStr::operator==(), KKB::osAddLastSlash(), KKB::osAddSlash(), KKB::osGetListOfDirectories(), KKB::osGetRootNameOfDirectory(), and SaveFeatureFile().
Referenced by LoadInSubDirectoryTree().
{
  _log.Level (10) << "FeatureFileIO::LoadInSubDirectoryTree rootDir[" << _rootDir << "]." <<
      endl;
  osAddLastSlash (_rootDir);
  KKStr featureFileName ("");
  KKStr fullFeatureFileName ("");
  if (!_rootDir.Empty ())
  {
    featureFileName = osGetRootNameOfDirectory (_rootDir) + ".data";
    fullFeatureFileName = _rootDir + featureFileName;
  }
  else
  {
    featureFileName = "Root.data";
    fullFeatureFileName = "Root.data";
  }
  MLClassPtr unKnownClass = _mlClasses.GetUnKnownClass ();
  if (_useDirectoryNameForClassName)
  {
    KKStr className = MLClass::GetClassNameFromDirName (_rootDir);
    unKnownClass = _mlClasses.GetMLClassPtr (className);
  }
  bool changesMade = false;
  FeatureVectorListPtr dirImages = NULL;
  FileDescPtr fileDesc = _fvProducerFactory->FileDesc ();
  if (_rewiteRootFeatureFile)
  {
    DateTime timeStamp;
    dirImages = FeatureDataReSink (_fvProducerFactory,
                                   _rootDir,
                                   featureFileName,
                                   unKnownClass,
                                   _useDirectoryNameForClassName,
                                   _mlClasses,
                                   _cancelFlag,
                                   changesMade,
                                   timeStamp,
                                   _log
                                  );
    if (_useDirectoryNameForClassName)
    {
      FeatureVectorList::iterator idx;
      for (idx = dirImages->begin (); idx != dirImages->end (); idx++)
      {
        if ((*idx)->MLClass () != unKnownClass)
        {
          (*idx)->MLClass (unKnownClass);
          changesMade = true;
        }
      }
      if (changesMade)
      {
        KKStr fullFileName = osAddSlash (_rootDir) + featureFileName;
        kkuint32 numExamplesWritten = 0;
        bool cancel = false;
        bool successful = false;
        SaveFeatureFile (fullFileName,
                         dirImages->AllFeatures (),
                         *dirImages,
                         numExamplesWritten,
                         cancel,
                         successful,
                         _log
                        );
      }
    }
  }
  else
  {
    dirImages = _fvProducerFactory->ManufacturFeatureVectorList (true, _log);
  }
  // Now that we have processed all image files in "rootDir",
  // lets process any sub-directories.
  KKStr dirSearchPath = osAddSlash (_rootDir) + "*.*";
  KKStrListPtr subDirectories = osGetListOfDirectories (dirSearchPath);
  if (subDirectories)
  {
    KKStrList::iterator idx;
    for (idx = subDirectories->begin (); (idx != subDirectories->end () && (!_cancelFlag)); idx++)
    {
      KKStr subDirName (**idx);
      if (subDirName == "BorderImages")
      {
        // We ignore this director
        continue;
      }
      KKStr newDirPath = osAddSlash (_rootDir) + subDirName;
      FeatureVectorListPtr subDirImages =
      LoadInSubDirectoryTree (_fvProducerFactory,
                                                                   newDirPath,
                                                                   _mlClasses,
                                                                   _useDirectoryNameForClassName,
                                                                   _cancelFlag,
                                                                   true, // true =
       ReWriteRootFeatureFile
                                                                   _log
                                                                  );
      FeatureVectorPtr fv = NULL;
      osAddLastSlash (subDirName);
      // We want to add the directory path to the ExampleFileName so that we can later locate the source
       image.
      FeatureVectorList::iterator idx = subDirImages->begin ();
      for (idx = subDirImages->begin (); idx != subDirImages->end (); idx++)
      {
        fv = *idx;
        KKStr newImageFileName = subDirName + fv->ExampleFileName ();
        fv->ExampleFileName (newImageFileName);
      }
      dirImages->AddQueue (*subDirImages);
      subDirImages->Owner (false);
      delete subDirImages;
    }
    delete subDirectories; subDirectories = NULL;
  }
  _log.Level (10) << "LoadInSubDirectoryTree - Done" << endl;
  return dirImages;
} /* LoadInSubDirectoryTree */
void FeatureFileIO::RegisterDriver (FeatureFileIOPtr driver) [static], [protected]
Definition at line 120 of file FeatureFileIO.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
{
  GlobalGoalKeeper::StartBlock ();
  FeatureFileIOPtr existingDriver = LookUpDriver (_driver->driverName);
  if (existingDriver)
  {
    // We are trying to register two drivers with the same name; we can not do that.
    cerr << endl << endl
         << "FeatureFileIO::RegisterDriver ***ERROR***" << endl
         << endl
         << " trying to register more than one FeatureFileIO driver with " <<
      endl
         << " the same name[" << _driver->driverName << "]." << endl
         << endl;
  }
  else
  {
    registeredDrivers->push_back (_driver);
  }
  GlobalGoalKeeper::EndBlock ();
} /* RegisterDriver */
VectorKKStr FeatureFileIO::RegisteredDriverNames (bool canRead, bool canWrite) [static]
Definition at line 295 of file FeatureFileIO.cpp.
References CanRead(), and CanWrite().
{
  vector<FeatureFileIOPtr>* drivers = RegisteredDrivers ();
  VectorKKStr names;
  vector<FeatureFileIOPtr>::iterator idx;
  for (idx = drivers->begin (); idx != drivers->end (); idx++)
  {
    FeatureFileIOPtr driver = *idx;
    if (canRead && (!driver->CanRead ()))
      continue;
    if (canWrite && (!driver->CanWrite ()))
      continue;
    names.push_back (driver->DriverName ());
  }
  return names;
} /* RegisteredDriverNames */
void FeatureFileIO::RegisterFeatureFileIODriver (FeatureFileIOPtr _driver) [static]
For each feature file format register the appropriate driver through this static method.
You will be giving ownership of the driver to this class; it will call the destructor when the application shutdown.
Definition at line 79 of file FeatureFileIO.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
{
  GlobalGoalKeeper::StartBlock ();
  if (!registeredDrivers)
  {
    RegisterAllDrivers ();
    registeredDrivers = new std::vector<FeatureFileIOPtr> ();
  }
  registeredDrivers->push_back (_driver);
  GlobalGoalKeeper::EndBlock ();
} /* RegisterFeatureFileIODriver */
void FeatureFileIO::SaveFeatureFile (const KKStr & _fileName, FeatureNumListConst & _selFeatures, FeatureVectorList & _examples, kkuint32 & _numExamplesWritten, VolConstBool & _cancelFlag, bool & _successful, RunLog & _log) [virtual]
Save examples to 'fileName'.
SaveFeatureFile
Parameters
in _fileName Name of file top same examples/images to.
in _selFeatures Specify specific features to save, typically all features.
in _examples Examples that are to be saved.
in _numExamplesWritten Will reflect the number of examples written, caller will be able to monitor.
in _cancelFlag If this flag turns true the writing of data will terminate and return to caller.
out _successful False will be returned if the save failed.
in _log log file to send messages to.
Parameters
_numExamplesWritten caller will be able to monitor this variable.
Definition at line 565 of file FeatureFileIO.cpp.
References KKB::KKStr::Concat(), and KKMLL::FeatureVectorList::FileDesc().
Referenced by FeatureDataReSink(), LoadInSubDirectoryTree(), and SaveFeatureFileMultipleParts().
{
  _log.Level (10) << "FeatureFileIO::SaveFeatureFile - File[" << _fileName << "]." <<
      endl;
  ofstream out (_fileName.Str ());
  if (!out.is_open())
  {
    _log.Level (-1) << "***ERROR***, SaveFeatureFile, Opening File[" << _fileName << "]" <<
      endl;
    _successful = false;
  }
  out.precision (9);
  FileDescPtr fileDesc = _examples.FileDesc ();
  KKStr errorMessage;
  SaveFile (_examples, _fileName, _selFeatures, out, _numExamplesWritten, _cancelFlag, _successful,
       errorMessage, _log);
  out.close ();
} /* SaveFeatureFile */
void FeatureFileIO::SaveFeatureFileMultipleParts (const KKStr & _fileName, FeatureNumListConst & _selFeatures, FeatureVectorList & _examples, VolConstBool & _cancelFlag, bool & _successful, RunLog & _log)
Saves the feature file in multiple parts with no one single part larger that 64k examples.
Same as 'SaveFeatureFile', if more than 64k examples will break into multiple files. If there are more than 64k examples, will save all images into 'fileName', but also a second copy of them into files with same name plus seq number with max of 64k samples in each one.
Parameters
in _fileName Name of file top same examples/images to.
in _selFeatures Specify specific features to save, typically all features.
in _examples Examples that are to be saved.
in _cancelFlag If this flag turns true the writing of data will terminate and return to caller.
out _successful False will be returned if the save failed.
in _log log file to send messages to.
Definition at line 597 of file FeatureFileIO.cpp.
References SaveFeatureFile().
{
  kkuint32 numExamplesWritten = 0;
  SaveFeatureFile (_fileName, _selFeatures, _examples, numExamplesWritten, _cancelFlag,
      _successful, _log);
  if (_cancelFlag || (!_successful))
    return;
  if (_examples.QueueSize () > 64000)
  {
    kkint32 numPartsNeeded = (_examples.QueueSize () / 64000);
    if ((_examples.QueueSize () % 64000) > 0)
      numPartsNeeded++;
    kkint32 maxPartSize = (_examples.QueueSize () / numPartsNeeded) + 1;
    kkint32 partNum = 0;
    FeatureVectorList::const_iterator idx = _examples.begin ();
    while ((idx != _examples.end ()) && (_successful) && (!_cancelFlag))
    {
      FeatureVectorListPtr part = _examples.
      ManufactureEmptyList (false);
      while ((idx != _examples.end ()) && (part->QueueSize () < maxPartSize))
      {
        part->PushOnBack (*idx);
        idx++;
      }
      KKStr partFileName = osRemoveExtension (_fileName) + "-" +
                            StrFormatInt (partNum, "00") + "." +
                            osGetFileExtension (_fileName);
      SaveFeatureFile (partFileName, _selFeatures, *part, numExamplesWritten, _cancelFlag,
      _successful, _log);
      partNum++;
      delete part; part = NULL;
    }
  }
} /* SaveFeatureFileMultipleParts */
virtual void KKMLL::FeatureFileIO::SaveFile (FeatureVectorList & _data, const KKStr & _fileName, FeatureNumListConst & _selFeatures, std::ostream & _out, kkuint32 & _numExamplesWritten, VolConstBool & _cancelFlag, bool & _successful, KKStr & _errorMessage, RunLog & _log) [pure virtual]
To be implemented by derived classes; save examples to output stream '_out'.
Parameters
in _data Examples that are to be written to saved to the output stream.
in _fileName Name of file top same examples/images to.
in _selFeatures Specify specific features to save, typically all features.
out _out Output stream to save feature data to.
out _numExamplesWritten Will reflect the number examples written, caller will be able to monitor.
in _cancelFlag If this flag turns true the writing of data will terminate and return to caller.
out _successful False will be returned if the save failed.
out _errorMessage If the save fails (_successful == false) then a description of the error will be placed here.
in _log log file to send messages to.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIO.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIO.cpp