KKB::KKException Class Reference
#include <KKException.h>
Public Member Functions
KKException ()
KKException (const KKException &_exception)
KKException (const KKStr &_exceptionStr)
KKException (const char *_exceptionStr)
KKException (const KKStr &_exceptionStr, const std::exception &_innerException)
KKException (const char *_exceptionStr, const std::exception &_innerException)
KKException (const char *_exceptionStr, const KKException &_innerException)
KKException (const KKStr &_exceptionStr, const KKException &_innerException)
virtual ~KKException () throw ()
virtual const KKStr & ToString () const
virtual const char * what () const throw ()
Detailed Description
Definition at line 27 of file KKException.h.
Constructor & Destructor Documentation
KKException::KKException ()
Definition at line 25 of file KKException.cpp.
References KKException().
Referenced by KKException().
                         :
  std::exception ()
{
}
KKException::KKException (const KKException & _exception)
Definition at line 31 of file KKException.cpp.
References KKException(), and KKB::KKStr::KKStr().
Referenced by KKException().
                                                       :
  std::exception (),
  exceptionStr (_exception.exceptionStr)
{
}
KKException::KKException (const KKStr & _exceptionStr)
Definition at line 45 of file KKException.cpp.
References KKException(), and KKB::KKStr::KKStr().
Referenced by KKMLL::FileDesc::AddANominalValue(), KKMLL::FeatureVector::AddFeatureData(), KKB::MsgQueue::AddMsg(), KKB::RasterBuffer::AddRaster(), KKB::KKStr::Append(), KKMLL::GrayScaleImagesFVList::BackOfQueue(), KKB::KKStrList::BinarySearch(), KKB::BitString::BitString(), KKB::BmpImage::BlueRow(), KKMLL::FileDesc::Cardinality(), KKMLL::Classifier2::Classifier2(), KKMLL::Model::CreateAModel(), KKMLL::FeatureEncoder::CreateEncodedFileDesc(), KKB::BmpImage::CodedPixels::CreatePixelDataStructure8Bit(), KKB::Matrix::DeterminantSlow(), KKMLL::FeatureEncoder::EncodeAExample(), KKB::GoalKeeperSimple::EndBlock(), KKB::Raster::ExtractBlobs(), KKMLL::FeatureVectorList::FeatureVectorList(), KKMLL::SVMModel::FindWorstSupportVectors(), KKMLL::SVMModel::FindWorstSupportVectors2(), KKB::KKStr::FreeUpUnUsedSpace(), KKMLL::FileDesc::GetExistingFileDesc(), KKMLL::GrayScaleImagesFVList::GrayScaleImagesFVList(), KKB::Raster::Histogram(), KKB::BmpImage::ImageRow(), KKB::Matrix::Inverse(), KKException(), KKB::KKStr::KKStr(), KKB::KKStr::LeftPad(), KKB::BitString::ListOfSetBits16(), KKB::Matrix::Matrix(), KKB::Matrix::operator*(), KKB::Matrix::operator+(), KKB::Matrix::operator+=(), KKB::Matrix::operator-(), KKB::KKStr::operator=(), KKB::Matrix::operator[](), KKMLL::FeatureNumList::operator[](), KKMLL::ModelOldSVM::Param(), KKMLL::GrayScaleImagesFVList::PopFromBack(), KKMLL::ModelSvmBase::Predict(), KKMLL::ModelUsfCasCor::Predict(), KKMLL::SVMModel::Predict(), KKMLL::ClassificationBiasMatrix::PrintAdjustedResults(), KKMLL::ClassificationBiasMatrix::PrintBiasMatrix(), KKMLL::ModelKnn::ProbabilitiesByClass(), KKMLL::ModelSvmBase::ProbabilitiesByClass(), KKMLL::ModelUsfCasCor::ProbabilitiesByClass(), KKMLL::ModelOldSVM::ProbabilitiesByClass(), KKMLL::ClassProbList::PushOnBack(), KKMLL::BinaryClassParmsList::PushOnBack(), KKMLL::FeatureVectorList::PushOnBack(), KKMLL::ClassProbList::PushOnFront(), KKMLL::BinaryClassParmsList::PushOnFront(), KKMLL::FeatureVectorList::PushOnFront(), KKB::Raster::Raster(), KKB::BmpImage::RedRow(), KKB::XmlFactoryManager::RegisterFactory(), KKB::XmlFactory::RegisterFactory(), KKMLL::FeatureVectorList::ResetFileDesc(), KKMLL::FeatureVector::ResetNumOfFeatures(), KKMLL::FeatureVectorList::ReSyncSymbolicData(), KKB::KKStr::RightPad(), KKB::Row::Row(), KKB::BmpImage::Save(), KKB::BmpImage::SaveGrayscaleInverted4Bit(), KKB::BmpImage::SaveGrayscaleInverted8Bit(), KKB::SaveImage(), KKB::SaveImageGrayscaleInverted4Bit(), KKB::SaveImageGrayscaleInverted8Bit(), KKB::SaveImagePNG(), KKB::SaveImagePPM(), SVM233::svm_GetSupportVectorStatistics(), SVM289_BFS::svm_train_one(), SVM289_MFS::svm_train_one(), KKMLL::TrainingConfiguration2::SVMparamREF(), KKMLL::FeatureVectorList::SynchronizeSymbolicData(), KKB::tqli(), KKMLL::ModelUsfCasCor::TrainModel(), KKMLL::ModelSvmBase::TrainModel(), KKMLL::ModelDual::TrainModel(), KKMLL::ModelOldSVM::TrainModel(), KKMLL::Model::TrainModel(), and KKB::Tred2().
                                                    :
  std::exception (),
  exceptionStr (_exceptionStr)
{
}
KKException::KKException (const char * _exceptionStr)
Definition at line 38 of file KKException.cpp.
References KKException(), and KKB::KKStr::KKStr().
Referenced by KKB::BmpImage::BlueRow(), KKMLL::Classifier2::Classifier2(), KKMLL::Model::CreateAModel(), KKMLL::Model::Encoder(), KKB::Raster::ExtractBlobs(), KKMLL::Model::GetFeatureNums(), KKB::BmpImage::ImageRow(), KKB::Raster::Initialize(), KKException(), KKB::KKStr::KKStr(), KKMLL::Model::NormalizeNominalAttributes(), KKB::KKStr::operator<<(), KKB::KKStr::operator=(), KKJobManagment::KKJob::ProcessNode(), KKB::Raster::Raster(), KKB::BmpImage::RedRow(), KKMLL::Model::SelectedFeatures(), KKB::KKThread::Start(), and SVM233::SvmModel233::SvmModel233().
                                                   :
  std::exception (),
  exceptionStr (_exceptionStr)
{
}
KKException::KKException (const KKStr & _exceptionStr, const std::exception & _innerException)
Definition at line 52 of file KKException.cpp.
References KKException(), and KKB::KKStr::KKStr().
Referenced by KKException(), KKMLL::ClassificationBiasMatrix::PrintAdjustedResults(), KKMLL::ModelUsfCasCor::TrainModel(), KKMLL::ModelSvmBase::TrainModel(), and KKMLL::ModelDual::TrainModel().
                          :
  std::exception (_innerException),
  exceptionStr ()
{
  exceptionStr << _exceptionStr << endl
               << _innerException.what ();
}
KKException::KKException (const char * _exceptionStr, const std::exception & _innerException)
Definition at line 64 of file KKException.cpp.
{
  exceptionStr << _exceptionStr << endl
               << _innerException.what ();
}
KKException::KKException (const char * _exceptionStr, const KKException & _innerException)
Definition at line 74 of file KKException.cpp.
References KKException(), and KKB::KKStr::KKStr().
Referenced by KKMLL::Model::CreateAModel(), and KKException().
                          :
  std::exception (_innerException),
  exceptionStr (_exceptionStr)
{
}
KKException::KKException (const KKStr & _exceptionStr, const KKException & _innerException)
Definition at line 83 of file KKException.cpp.
References KKException(), and KKB::KKStr::KKStr().
Referenced by KKException(), KKMLL::ClassificationBiasMatrix::PrintAdjustedResults(), KKB::SaveImage(), KKB::SaveImageGrayscaleInverted4Bit(), KKB::SaveImageGrayscaleInverted8Bit(), KKMLL::ModelUsfCasCor::TrainModel(), KKMLL::ModelSvmBase::TrainModel(), and KKMLL::ModelDual::TrainModel().
                          :
  std::exception (_innerException),
  exceptionStr (_exceptionStr)
{
}
KKException::~KKException () throw) [virtual]
Definition at line 93 of file KKException.cpp.
{
}
Member Function Documentation
const KKStr & KKException::ToString () const [virtual]
Definition at line 98 of file KKException.cpp.
Referenced by KKB::ThreadStartCallBack().
{
  return exceptionStr;
}
const char * KKException::what () const throw) [virtual]
Definition at line 104 of file KKException.cpp.
References KKB::KKStr::Str().
{
  return exceptionStr.Str ();
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKException.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKException.cpp