KKMLL::ImageFeaturesNodeKey Class Reference
#include <ImageFeaturesDataIndexed.h>
Public Member Functions
ImageFeaturesNodeKey (FeatureVectorPtr _example)
kkint32 CompareTwoExamples (const FeatureVectorPtr i1, const FeatureVectorPtr i2) const
bool operator< (const ImageFeaturesNodeKey &rightNode) const
bool operator== (const ImageFeaturesNodeKey &rightNode) const
bool operator> (const ImageFeaturesNodeKey &rightNode) const
Public Attributes
FeatureVectorPtr example
Detailed Description
Definition at line 54 of file ImageFeaturesDataIndexed.h.
Constructor & Destructor Documentation
ImageFeaturesNodeKey::ImageFeaturesNodeKey (FeatureVectorPtr _example)
Definition at line 90 of file ImageFeaturesDataIndexed.cpp.
References example.
Referenced by KKMLL::ImageDataTreeEntry::ImageDataTreeEntry().
                                                                     :
  example (_example)
{
}
Member Function Documentation
kkint32 ImageFeaturesNodeKey::CompareTwoExamples (const FeatureVectorPtr i1, const FeatureVectorPtr i2) const
Definition at line 115 of file ImageFeaturesDataIndexed.cpp.
References KKMLL::FeatureVector::FeatureDataConst(), and KKMLL::FeatureVector::NumOfFeatures().
Referenced by operator<(), operator==(), and operator>().
{
  const float* f1 = i1->FeatureDataConst ();
  const float* f2 = i2->FeatureDataConst ();
  for (kkint32 x = 0; x < i1->NumOfFeatures (); x++)
  {
    if (f1[x] < f2[x])
      return -1;
    else if (f1[x] > f2[x])
      return 1;
  }
  return 0;
} /* CompareTwoImageFeaturesObjects */
bool ImageFeaturesNodeKey::operator< (const ImageFeaturesNodeKey & rightNode) const
Definition at line 103 of file ImageFeaturesDataIndexed.cpp.
References CompareTwoExamples(), and example.
{
  return (CompareTwoExamples (example, rightNode.
      example) < 0);
}
bool ImageFeaturesNodeKey::operator== (const ImageFeaturesNodeKey & rightNode) const
Definition at line 98 of file ImageFeaturesDataIndexed.cpp.
References CompareTwoExamples(), and example.
{
  return (CompareTwoExamples (example, rightNode.
      example) == 0);
}
bool ImageFeaturesNodeKey::operator> (const ImageFeaturesNodeKey & rightNode) const
Definition at line 108 of file ImageFeaturesDataIndexed.cpp.
References CompareTwoExamples(), and example.
{
  return (CompareTwoExamples (example, rightNode.
      example) > 0);
}
Member Data Documentation
FeatureVectorPtr KKMLL::ImageFeaturesNodeKey::example
Definition at line 67 of file ImageFeaturesDataIndexed.h.
Referenced by ImageFeaturesNodeKey(), operator<(), operator==(), and operator>().
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ImageFeaturesDataIndexed.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ImageFeaturesDataIndexed.cpp