KKMLL::GrayScaleImagesFVProducer Class Reference
#include <GrayScaleImagesFVProducer.h>
Public Member Functions
GrayScaleImagesFVProducer (FactoryFVProducerPtr factory)
virtual ~GrayScaleImagesFVProducer ()
virtual FeatureVectorPtr ComputeFeatureVector (const Raster &srcImage, const MLClassPtr knownClass, RasterListPtr intermediateImages, float priorReductionFactor, RunLog &runLog)
Compute a FeatureVector for the supplied 'image'.
virtual const type_info * FeatureVectorListTypeId () const
Returns the 'type_info' of the FeatureVectorList derived class that can contain instances in 'FeatureVector' instances created by this producer.
virtual const type_info * FeatureVectorTypeId () const
Returns the 'type_info' of the Feature Vector that this instance of 'FeatureComputer' creates.
virtual FeatureVectorListPtr ManufacturFeatureVectorList (bool owner, RunLog &runLog) const
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors by this FeatureVectorProducer.
virtual kkint16 Version () const
Static Public Member Functions
static FileDescPtr DefineFileDescStatic ()
static kkint32 MaxNumOfFeatures ()
Protected Member Functions
virtual FileDescPtr DefineFileDesc () const
Additional Inherited Members
Detailed Description
Definition at line 19 of file GrayScaleImagesFVProducer.h.
Constructor & Destructor Documentation
GrayScaleImagesFVProducer::GrayScaleImagesFVProducer (FactoryFVProducerPtr factory)
Definition at line 173 of file GrayScaleImagesFVProducer.cpp.
References KKMLL::FeatureVectorProducer::FeatureVectorProducer().
Referenced by KKMLL::GrayScaleImagesFVProducerFactory::ManufactureInstance().
                                                                                  :
    FeatureVectorProducer ("GrayScaleImages",
                           factory
                          ),
    totPixsForMorphOps (4000000),
    workRaster1Area (NULL),
    workRaster2Area (NULL),
    workRaster3Area (NULL),
    workRaster1Rows (NULL),
    workRaster2Rows (NULL),
    workRaster3Rows (NULL)
{
  workRaster1Area = new uchar[totPixsForMorphOps];
  workRaster2Area = new uchar[totPixsForMorphOps];
  workRaster3Area = new uchar[totPixsForMorphOps];
}
GrayScaleImagesFVProducer::~GrayScaleImagesFVProducer () [virtual]
Definition at line 193 of file GrayScaleImagesFVProducer.cpp.
{
  delete workRaster1Area; workRaster1Area = NULL;
  delete workRaster2Area; workRaster2Area = NULL;
  delete workRaster3Area; workRaster3Area = NULL;
  delete workRaster1Rows; workRaster1Rows = NULL;
  delete workRaster2Rows; workRaster2Rows = NULL;
  delete workRaster3Rows; workRaster3Rows = NULL;
}
Member Function Documentation
FeatureVectorPtr GrayScaleImagesFVProducer::ComputeFeatureVector (const Raster & image, const MLClassPtr knownClass, RasterListPtr intermediateImages, float priorReductionFactor, RunLog & runLog) [virtual]
Compute a FeatureVector for the supplied 'image'.
Parameters
in image
in knownClass The class label that will be assigned to this Feature vector.
in,out intermediateImages If not NULL will save a copy of the intermediate images created during Feature Computation; the call will own the list and its contents.
in priorReductionFactor The reduction that was done to the image prior to calling this routine; if no size change was made then set this field to 1.0. The FeaureVector computation routines will use this field to adjust SizeDependent features appropriately. the value of this parameter represents the number of pixels that were reduced to 1 pixel. A value of 3 indicates (3 x 3) pixels were reduced to 1 pixel.
in log Logging file.
Returns
The resultant Feature vector computed.
Implements KKMLL::FeatureVectorProducer.
Definition at line 316 of file GrayScaleImagesFVProducer.cpp.
References KKB::Raster::CalcAreaAndIntensityFeatures(), KKB::Raster::CentralMoments(), KKB::Raster::ComputeCentralMoments(), KKB::KKStr::Concat(), KKB::ConvexHull::ConvexArea(), KKB::ConvexHull::ConvexHull(), KKB::Raster::Dilation(), KKB::Raster::Edge(), KKB::Raster::Erosion(), KKB::Raster::ExtractBlobs(), KKMLL::FeatureVector::FeatureDataAlter(), KKMLL::FeatureVector::FeatureVector(), KKB::Raster::FillHole(), KKB::ConvexHull::Filter(), KKB::Raster::ForegroundPixelCount(), KKB::Raster::Height(), KKMLL::FeatureVector::MLClass(), KKB::operator+(), KKMLL::FeatureVector::OrigSize(), KKB::Blob::PixelCount(), KKB::Raster::Raster(), KKB::MorphOp::SQUARE3, KKB::MorphOp::SQUARE5, KKB::MorphOp::SQUARE7, KKB::MorphOp::SQUARE9, KKB::StrFormatInt(), KKB::Raster::ThinContour(), Version(), KKMLL::FeatureVector::Version(), and KKB::Raster::Width().
{
  FeatureVectorPtr fv = new FeatureVector (maxNumOfFeatures);
  fv->MLClass (knownClass);
  float* featureData = fv->FeatureDataAlter ();
  fv->Version (Version ());
  kkint32 areaBeforeReduction = 0;
  float weighedSizeBeforeReduction = 0.0f;
  kkint32 row = 0;
  kkint32 col = 0;
  kkuint32 intensityHistBuckets[8];
  srcImage.CalcAreaAndIntensityFeatures (areaBeforeReduction,
                                         weighedSizeBeforeReduction,
                                         intensityHistBuckets
                                        );
  kkint32 srcHeight = srcImage.Height ();
  kkint32 srcWidth = srcImage.Width ();
  kkint32 reducedHeight = srcHeight;
  kkint32 reducedWidth = srcWidth;
  kkint32 reducedSquareArea = reducedHeight * reducedWidth;
  kkint32 reductionMultiple = 1;
  while (reducedSquareArea > totPixsForMorphOps)
  {
    ++reductionMultiple;
    reducedHeight = (srcHeight + reductionMultiple - 1) / reductionMultiple;
    reducedWidth = (srcWidth + reductionMultiple - 1) / reductionMultiple;
    reducedSquareArea = reducedHeight * reducedWidth;
  }
  kkint32 reductionMultipleSquared = reductionMultiple * reductionMultiple;
  float totalReductionMultiple = priorReductionFactor * reductionMultiple;
  float totalReductionMultipleSquared = totalReductionMultiple * totalReductionMultiple;
  delete workRaster1Rows; workRaster1Rows = new uchar*[reducedHeight];
  delete workRaster2Rows; workRaster2Rows = new uchar*[reducedHeight];
  delete workRaster3Rows; workRaster3Rows = new uchar*[reducedHeight];
  uchar* wp1 = workRaster1Area;
  uchar* wp2 = workRaster2Area;
  uchar* wp3 = workRaster3Area;
  for (row = 0; row < reducedHeight; ++row)
  {
    workRaster1Rows[row] = wp1;
    workRaster2Rows[row] = wp2;
    workRaster3Rows[row] = wp3;
    wp1 += reducedWidth;
    wp2 += reducedWidth;
    wp3 += reducedWidth;
  }
  Raster workRaster1 (reducedHeight, reducedWidth, workRaster1Area, workRaster1Rows);
  Raster workRaster2 (reducedHeight, reducedWidth, workRaster2Area, workRaster2Rows);
  Raster workRaster3 (reducedHeight, reducedWidth, workRaster3Area, workRaster3Rows);
  Raster const * initRaster = NULL;
  RasterPtr wr1 = NULL;
  RasterPtr wr2 = NULL;
  if (reductionMultiple > 1)
  {
    try
    {
      ReductionByMultiple (reductionMultiple, srcImage, workRaster1);
    }
    catch (...)
    {
      runLog.Level (-1) << endl << "GrayScaleImagesFVProducer::ComputeFeatureVector ***ERROR***
       Exception calling 'ReductionByMultiple'." << endl << endl;
      return NULL;
    }
    initRaster = &workRaster1;
    wr1 = &workRaster2;
    wr2 = &workRaster3;
  }
  else
  {
    initRaster = &srcImage;
    wr1 = &workRaster1;
    wr2 = &workRaster2;
  }
  if (areaBeforeReduction < 20)
  {
    for (kkint32 tp = 0; tp < maxNumOfFeatures; tp++)
      featureData[tp] = 9999999;
    return fv;
  }
  
  float convexf = 0.0;
  float centralMoments[9];
  float centralMomentsWeighted[9];
  kkint32 pixelCountReduced = 0;
  float pixelCountWeightedReduced = 0.0f;
  initRaster->ComputeCentralMoments (pixelCountReduced, pixelCountWeightedReduced,
      centralMoments, centralMomentsWeighted);
  float edgeMomentf[9];
  initRaster->Dilation (wr1);
  wr1->Dilation (wr2);
  wr2->FillHole (wr1);
  wr1->Erosion (wr2);
  wr2->Edge (wr1);
  wr1->CentralMoments (edgeMomentf);
  if (intermediateImages)
  {
    kkint32 numEdgePixelsFound = (kkint32)(edgeMomentf[0]);
    SaveIntermediateImage (*wr2, "Edge_Image_" + StrFormatInt (numEdgePixelsFound, "ZZZZ0"),
      intermediateImages);
  }
  kkint32 area = (kkint32)(centralMoments[0] + 0.5f); // Moment-0 is the same as the number
       of foreground pixels in example.
  {
    ConvexHullPtr ch = new ConvexHull ();
    ch->Filter (*initRaster, wr1);
    convexf = (float)ch->ConvexArea ();
    if (intermediateImages)
    {
      KKStr convexImageFileName = "ConvexHull_" +
                                   StrFormatInt ((kkint32)convexf, "ZZZZZ0");
      SaveIntermediateImage (*wr1, convexImageFileName, intermediateImages);
    }
    //delete convexImage;
    //convexImage = NULL;
    delete ch;
    ch = NULL;
  }
  initRaster->Erosion (wr1);
  wr1->Dilation (wr2);
  float areaOpen3 = (float)(wr2->ForegroundPixelCount());
  if (intermediateImages)
    SaveIntermediateImage (*wr2, "Opening3_" + StrFormatInt ((
      kkint32)areaOpen3, "ZZZZZZ0"), intermediateImages);
  initRaster->Erosion (wr1, MorphOp::MaskTypes::SQUARE5);
  wr1->Dilation (wr2, MorphOp::MaskTypes::SQUARE5);
  float areaOpen5 = (float)(wr2->ForegroundPixelCount ());
  if (intermediateImages)
    SaveIntermediateImage (*wr2, "Opening5_" + StrFormatInt ((
      kkint32)areaOpen5, "ZZZZZZ0"), intermediateImages);
  initRaster->Erosion (wr1, MorphOp::MaskTypes::SQUARE7);
  wr1->Dilation (wr2, MorphOp::MaskTypes::SQUARE7);
  float areaOpen7 = (float)(wr2->ForegroundPixelCount ());
  if (intermediateImages)
    SaveIntermediateImage (*wr2, "Opening7_" + StrFormatInt ((
      kkint32)areaOpen7, "ZZZZZZ0"), intermediateImages);
  
  wr2->Erosion (wr1, MorphOp::MaskTypes::SQUARE9);
  wr1->Dilation (wr2, MorphOp::MaskTypes::SQUARE9);
  float areaOpen9 = (float)(wr2->ForegroundPixelCount ());
  if (intermediateImages)
    SaveIntermediateImage (*wr2, "Opening9_" + StrFormatInt ((
      kkint32)areaOpen9, "ZZZZZZ0"), intermediateImages);
  initRaster->Dilation (wr1);
  wr1->Erosion (wr2);
  float areaClose3 = (float)(wr2->ForegroundPixelCount ());
  if (intermediateImages)
    SaveIntermediateImage (*wr2, "Close3_" + StrFormatInt ((kkint32)areaClose3, "ZZZZZZ0
      "), intermediateImages);
  wr2->FillHole (wr1);
  float tranf = (float)(wr2->ForegroundPixelCount ());
  if (intermediateImages)
    SaveIntermediateImage (*wr2, "FillHole_" + StrFormatInt ((
      kkint32)tranf, "ZZZZZZ0"), intermediateImages);
  initRaster->Dilation (wr1, MorphOp::MaskTypes::SQUARE5);
  wr1->Erosion (wr2, MorphOp::MaskTypes::SQUARE5);
  float areaClose5 = (float)(wr2->ForegroundPixelCount ());
  if (intermediateImages)
    SaveIntermediateImage (*wr2, "Close5_" + StrFormatInt ((kkint32)areaClose5, "ZZZZZZ0
      "), intermediateImages);
  
  initRaster->Dilation (wr1, MorphOp::MaskTypes::SQUARE7);
  wr1->Erosion (wr2, MorphOp::MaskTypes::SQUARE7);
  float areaClose7 = float (wr2->ForegroundPixelCount ());
  if (intermediateImages)
    SaveIntermediateImage (*wr2, "Close7_" + StrFormatInt ((kkint32)areaClose7, "ZZZZZZ0
      "), intermediateImages);
  {
    featureData[SizeIndex] = float (areaBeforeReduction * priorReductionFactor);
    featureData[Moment1Index] = float (centralMoments[1]);
    featureData[Moment2Index] = float (centralMoments[2]);
    featureData[Moment3Index] = float (centralMoments[3]);
    featureData[Moment4Index] = float (centralMoments[4]);
    featureData[Moment5Index] = float (centralMoments[5]);
    featureData[Moment6Index] = float (centralMoments[6]);
    featureData[Moment7Index] = float (centralMoments[7]);
    featureData[Moment8Index] = float (centralMoments[8]);
    featureData[WeighedMoment0Index] = centralMomentsWeighted[0] * totalReductionMultiple;
    featureData[WeighedMoment1Index] = centralMomentsWeighted[1];
    featureData[WeighedMoment2Index] = centralMomentsWeighted[2];
    featureData[WeighedMoment3Index] = centralMomentsWeighted[3];
    featureData[WeighedMoment4Index] = centralMomentsWeighted[4];
    featureData[WeighedMoment5Index] = centralMomentsWeighted[5];
    featureData[WeighedMoment6Index] = centralMomentsWeighted[6];
    featureData[WeighedMoment7Index] = centralMomentsWeighted[7];
    featureData[WeighedMoment8Index] = centralMomentsWeighted[8];
    featureData[EdgeSizeIndex] = (float)edgeMomentf[0] * totalReductionMultiple;
    featureData[EdgeMoment1Index] = (float)edgeMomentf[1];
    featureData[EdgeMoment2Index] = (float)edgeMomentf[2];
    featureData[EdgeMoment3Index] = (float)edgeMomentf[3];
    featureData[EdgeMoment4Index] = (float)edgeMomentf[4];
    featureData[EdgeMoment5Index] = (float)edgeMomentf[5];
    featureData[EdgeMoment6Index] = (float)edgeMomentf[6];
    featureData[EdgeMoment7Index] = (float)edgeMomentf[7];
    featureData[EdgeMoment8Index] = (float)edgeMomentf[8];
    // Need to adjust for any reduction in Image Size
    //featureData[SizeIndex] = float (areaBeforeReduction);
    //featureData[EdgeSizeIndex] = float (edgeMomentf[0] * (float)(reductionMultipleSquared));
    //featureData[WeighedMoment0Index] = weighedSizeBeforeReduction;
  }
  if ((area > convexf) && (convexf > 0))
     featureData[TransparancyConvexHullIndex] = 1.0;
  else
     featureData[TransparancyConvexHullIndex] = (float)area / (float)convexf;
  featureData[TransparancyPixelCountIndex] = (float)area / (float)tranf;
  featureData[TransparancyOpen3Index] = (float)(area - areaOpen3) / (float)area;
  featureData[TransparancyOpen5Index] = (float)(area - areaOpen5) / (float)area;
  featureData[TransparancyOpen7Index] = (float)(area - areaOpen7) / (float)area;
  featureData[TransparancyOpen9Index] = (float)(area - areaOpen9) / (float)area;
  featureData[TransparancyClose3Index] = (float)(area - areaClose3) / (float)area;
  featureData[TransparancyClose5Index] = (float)(area - areaClose5) / (float)area;
  featureData[TransparancyClose7Index] = (float)(area - areaClose7) / (float)area;
 
  {
    // This part has to be done after 'CalcOrientationAndEigerRatio' is called. That is where the example
       centroid is calculated.
    //fv->CentroidCol (initRaster->CentroidCol () * reductionMultiple);
    //fv->CentroidRow (initRaster->CentroidRow () * reductioqnMultiple);
  }
  featureData[ConvexAreaIndex] = convexf * totalReductionMultipleSquared;
  featureData[TransparancySizeIndex] = (float)(centralMoments[0] / convexf);
  featureData[TransparancyWtdIndex] = (float)(centralMomentsWeighted[0] / convexf);
  float areaD = float (areaBeforeReduction);
  featureData[IntensityHist1Index] = ((float)intensityHistBuckets[1] / areaD);
  featureData[IntensityHist2Index] = ((float)intensityHistBuckets[2] / areaD);
  featureData[IntensityHist3Index] = ((float)intensityHistBuckets[3] / areaD);
  featureData[IntensityHist4Index] = ((float)intensityHistBuckets[4] / areaD);
  featureData[IntensityHist5Index] = ((float)intensityHistBuckets[5] / areaD);
  featureData[IntensityHist6Index] = ((float)intensityHistBuckets[6] / areaD);
  featureData[IntensityHist7Index] = ((float)intensityHistBuckets[7] / areaD);
  {
    RasterPtr darkSpots = NULL;
    BinarizeImageByThreshold (200, 255, *initRaster, *wr1);
   
    wr1->Erosion (wr2, MorphOp::MaskTypes::SQUARE3);
    wr2->Erosion (wr1, MorphOp::MaskTypes::SQUARE3);
    KKB::BlobListPtr blobs = wr1->ExtractBlobs (3);
    int darkSpotFreq[10];
    int x;
    for (x = 0; x < 10; ++x)
      darkSpotFreq[x] = 0;
    KKB::BlobList::iterator idx;
    for (idx = blobs->begin (); idx != blobs->end (); ++idx)
    {
      KKB::BlobPtr b = idx->second;
      double l = ::log ((double)(b->PixelCount ()));
      double logOfThree = ::log (3.0);
      int index = (int)floor (l / logOfThree);
      index = Min (Max (0, index), 9);
      ++(darkSpotFreq[index]);
    }
    featureData[DarkSpotCount0] = (float)darkSpotFreq[0];
    featureData[DarkSpotCount1] = (float)darkSpotFreq[1];
    featureData[DarkSpotCount2] = (float)darkSpotFreq[2];
    featureData[DarkSpotCount3] = (float)darkSpotFreq[3];
    featureData[DarkSpotCount4] = (float)darkSpotFreq[4];
    featureData[DarkSpotCount5] = (float)darkSpotFreq[5];
    featureData[DarkSpotCount6] = (float)darkSpotFreq[6];
    featureData[DarkSpotCount7] = (float)darkSpotFreq[7];
    featureData[DarkSpotCount8] = (float)darkSpotFreq[8];
    featureData[DarkSpotCount9] = (float)darkSpotFreq[9];
    delete blobs;
    blobs = NULL;
  }
  if (intermediateImages)
  {
    RasterPtr thinnedImage = initRaster->ThinContour ();
    SaveIntermediateImage (*thinnedImage, "_Thinned", intermediateImages);
    delete thinnedImage;
    thinnedImage = NULL;
  }
  featureData[0] = (float)areaBeforeReduction; // In case the example was reduced.
  fv->OrigSize ((float)areaBeforeReduction);
 
  return fv;
} /* ComputeFeatureVector */
FileDescPtr GrayScaleImagesFVProducer::DefineFileDesc () const [protected], [virtual]
Implements KKMLL::FeatureVectorProducer.
Definition at line 659 of file GrayScaleImagesFVProducer.cpp.
References DefineFileDescStatic().
{
  return DefineFileDescStatic ();
} /* DefineFileDesc */
FileDescPtr GrayScaleImagesFVProducer::DefineFileDescStatic () [static]
Definition at line 668 of file GrayScaleImagesFVProducer.cpp.
References KKMLL::FileDesc::AddAAttribute(), KKMLL::EncodeProblem(), KKB::GlobalGoalKeeper::EndBlock(), KKMLL::FileDesc::FileDesc(), KKMLL::FileDesc::GetExistingFileDesc(), KKMLL::Numeric, KKB::GlobalGoalKeeper::StartBlock(), and KKMLL::FileDesc::Version().
Referenced by DefineFileDesc(), KKMLL::GrayScaleImagesFVProducerFactory::FileDesc(), and KKMLL::GrayScaleImagesFVProducerFactory::ManufacturFeatureVectorList().
{
  if (existingFileDesc)
    return existingFileDesc;
  GlobalGoalKeeper::StartBlock ();
  if (!existingFileDesc)
  {
    bool alreadyExists = false;
    FileDescPtr tempFileDesc = new KKMLL::FileDesc ();
    for (kkint32 fieldNum = 0; fieldNum < maxNumOfFeatures; ++fieldNum)
    {
      tempFileDesc->AddAAttribute (featureNames[fieldNum],
      AttributeType::Numeric, alreadyExists);
    }
    tempFileDesc->Version (_GrayScaleImagesFVProducer_VersionNum_
      );
    existingFileDesc = FileDesc::GetExistingFileDesc (tempFileDesc);
    tempFileDesc = NULL;
  }
  GlobalGoalKeeper::EndBlock ();
  // Lets make sure that one was already created by opening up a data file.
  return existingFileDesc;
}
const type_info * GrayScaleImagesFVProducer::FeatureVectorListTypeId () const [virtual]
Returns the 'type_info' of the FeatureVectorList derived class that can contain instances in 'FeatureVector' instances created by this producer.
Implements KKMLL::FeatureVectorProducer.
Definition at line 652 of file GrayScaleImagesFVProducer.cpp.
{
  return &(typeid (FeatureVectorList));
}
const type_info * GrayScaleImagesFVProducer::FeatureVectorTypeId () const [virtual]
Returns the 'type_info' of the Feature Vector that this instance of 'FeatureComputer' creates.
Implements KKMLL::FeatureVectorProducer.
Definition at line 646 of file GrayScaleImagesFVProducer.cpp.
{
  return &(typeid (FeatureVector));
}
FeatureVectorListPtr GrayScaleImagesFVProducer::ManufacturFeatureVectorList (bool owner, RunLog & runLog) const [virtual]
Manufactures a instance of a derived 'FeatureVectorList' class that is appropriate for containing instances of FeatureVectors by this FeatureVectorProducer.
Implements KKMLL::FeatureVectorProducer.
Definition at line 696 of file GrayScaleImagesFVProducer.cpp.
References KKMLL::FeatureVectorList::FeatureVectorList(), and KKMLL::FeatureVectorProducer::FileDesc().
{
  return new FeatureVectorList (FileDesc (), owner);
}
static kkint32 KKMLL::GrayScaleImagesFVProducer::MaxNumOfFeatures () [inline], [static]
Definition at line 51 of file GrayScaleImagesFVProducer.h.
{return maxNumOfFeatures;}
virtual kkint16 KKMLL::GrayScaleImagesFVProducer::Version () const [inline], [virtual]
The version number of the FeatureVector that is going to be computed.
Implements KKMLL::FeatureVectorProducer.
Definition at line 49 of file GrayScaleImagesFVProducer.h.
Referenced by ComputeFeatureVector().
{return _GrayScaleImagesFVProducer_VersionNum_;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFVProducer.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFVProducer.cpp