KKLSC::ScannerFileEntryList Class Reference
#include <ScannerFileEntry.h>
Public Types
typedef map< KKStr, ScannerFileEntryPtr >::iterator Iterator
typedef pair< KKStr, ScannerFileEntryPtr > KeyPair
typedef ScannerFileEntryList * ScannerFileEntryListPtr
Public Member Functions
ScannerFileEntryList ()
~ScannerFileEntryList ()
void AddEntry (ScannerFileEntryPtr enytry)
ScannerFileEntryPtr LookUpByRootName (const KKStr &rootName)
kkint32 MemoryConsumedEstimated ()
Detailed Description
Definition at line 78 of file ScannerFileEntry.h.
Member Typedef Documentation
typedef map<KKStr, ScannerFileEntryPtr>::iterator KKLSC::ScannerFileEntryList::Iterator
Definition at line 83 of file ScannerFileEntry.h.
typedef pair<KKStr, ScannerFileEntryPtr> KKLSC::ScannerFileEntryList::KeyPair
Definition at line 85 of file ScannerFileEntry.h.
typedef ScannerFileEntryList* KKLSC::ScannerFileEntryList::ScannerFileEntryListPtr
Definition at line 81 of file ScannerFileEntry.h.
Constructor & Destructor Documentation
ScannerFileEntryList::ScannerFileEntryList ()
Definition at line 189 of file ScannerFileEntry.cpp.
References ScannerFileEntryList().
Referenced by KKLSC::ScannerFileEntry::GetOrCreateScannerFileEntry(), and ScannerFileEntryList().
                                           :
    map<KKStr, ScannerFileEntryPtr> ()
{
}
ScannerFileEntryList::~ScannerFileEntryList ()
Definition at line 195 of file ScannerFileEntry.cpp.
{
  for (idx = begin (); idx != end (); ++idx)
  {
    ScannerFileEntryPtr sfe = idx->second;
    delete sfe;
  }
}
Member Function Documentation
void ScannerFileEntryList::AddEntry (ScannerFileEntryPtr enytry)
Definition at line 221 of file ScannerFileEntry.cpp.
Referenced by KKLSC::ScannerFileEntry::GetOrCreateScannerFileEntry().
{
  insert (KeyPair (entry->RootName (), entry));
}
ScannerFileEntryPtr ScannerFileEntryList::LookUpByRootName (const KKStr & rootName)
Definition at line 228 of file ScannerFileEntry.cpp.
Referenced by KKLSC::ScannerFileEntry::GetOrCreateScannerFileEntry().
{
  idx = find (rootName);
  if (idx == end ())
    return NULL;
  else
    return idx->second;
}
kkint32 ScannerFileEntryList::MemoryConsumedEstimated ()
Definition at line 205 of file ScannerFileEntry.cpp.
References KKLSC::ScannerFileEntry::MemoryConsumedEstimated().
{
  kkint32 mem = sizeof (*this);
  for (idx = begin (); idx != end (); ++idx)
  {
    ScannerFileEntryPtr sfe = idx->second;
    mem += sfe->MemoryConsumedEstimated ();
  }
  return mem;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFileEntry.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFileEntry.cpp