KKMLL::Attribute Class Reference
describes a single Feature, Type and possible values.
#include <Attribute.h>
Public Member Functions
Attribute ()
Attribute (const KKStr &_name, AttributeType _type, kkint32 _fieldNum)
Attribute (const Attribute &a)
~Attribute ()
void AddANominalValue (const KKStr &nominalValue, bool &alreadyExists)
Adds a allowable Nominal value to the Nominal or Symbolic field that this attribute represents.
kkint32 Cardinality () const
Returns back the cardinality of the attribute; the number of possible values it can take.
kkint32 FieldNum () const
kkint32 GetNominalCode (const KKStr &nominalValue) const
const KKStr & GetNominalValue (kkint32 code) const
Returns the nominal value for the given ordinal value.
kkint32 MemoryConsumedEstimated () const
const KKStr & Name () const
const KKStr & NameUpper () const
bool operator!= (const Attribute &rightSide) const
Attribute & operator= (const Attribute &right)
bool operator== (const Attribute &rightSide) const
void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
AttributeType Type () const
KKStr TypeStr () const
void WriteXML (const KKStr &varName, std::ostream &o) const
Detailed Description
describes a single Feature, Type and possible values.
Author
Kurt Kramer
Used to support 'FileDesc', 'FeatureVector', and is derived classes classes. FileDesc will maintain a list of 'Attribute' objects to describe each separate field in a given FeatureFile. A given Feature can be one of several types, Numeric, Nominal, Ordinal, and Symbolic.
Numeric - Any floating point value.
Nominal - Feature must be one of a specified possible values. The Attribute class will
           maintain a list of possible values. This will be saved as a integer value from
           in the FeatureVector object. When training a classifier it would be best to
           bit encode these features. See the FeatureEncoder class.
Ordinal - Similar to Nominal except there is a definite ordering of value.
Symbolic - Similar to Nominal except you do not know all the possible values this attribute
           can take on.
See also
KKMLL::FeatureEncoder, KKMLL::FeatureVector, KKMLL::FeatureFileIO
Definition at line 74 of file Attribute.h.
Constructor & Destructor Documentation
Attribute::Attribute ()
Definition at line 33 of file Attribute.cpp.
References KKB::KKStr::KKStr(), and KKMLL::NULLAttribute.
                     :
    fieldNum (-1),
    name (),
    nameUpper (),
    nominalValuesUpper (NULL),
    type (AttributeType::NULLAttribute)
{
}
Attribute::Attribute (const KKStr & _name, AttributeType _type, kkint32 _fieldNum)
Definition at line 44 of file Attribute.cpp.
References KKB::KKStr::KKStr(), KKB::KKStrListIndexed::KKStrListIndexed(), KKMLL::Nominal, KKMLL::Symbolic, and KKB::KKStr::Upper().
                      :
    fieldNum (_fieldNum),
    name (_name),
    nameUpper (_name),
    nominalValuesUpper (NULL),
    type (_type)
{
  nameUpper.Upper ();
  if ((type == AttributeType::Nominal) ||
       (type == AttributeType::Symbolic)
      )
  {
    nominalValuesUpper = new KKStrListIndexed (true, // true == nominalValuesUpper will
       own its contents.
                                               false // false = Not Case Sensitive.
                                              );
  }
}
Attribute::Attribute (const Attribute & a)
Definition at line 67 of file Attribute.cpp.
References KKB::KKStr::KKStr(), KKB::KKStrListIndexed::KKStrListIndexed(), KKMLL::Nominal, and KKMLL::Symbolic.
                                        :
    fieldNum (a.fieldNum),
    name (a.name),
    nameUpper (a.nameUpper),
    nominalValuesUpper (NULL),
    type (a.type)
{
  if ((type == AttributeType::Nominal) ||
       (type == AttributeType::Symbolic)
      )
  {
    nominalValuesUpper = new KKStrListIndexed (*(a.nominalValuesUpper));
  }
}
Attribute::~Attribute ()
Definition at line 86 of file Attribute.cpp.
{
  delete nominalValuesUpper;
}
Member Function Documentation
void Attribute::AddANominalValue (const KKStr & nominalValue, bool & alreadyExists)
Adds a allowable Nominal value to the Nominal or Symbolic field that this attribute represents.
To only be used by instances of 'Attribute' that represent Nominal or Symbolic type attributes. If the Attribute type is not s 'Nominal' or 'Symbolic' then this method will throw am exception
Parameters
in nominalValue A possible value that this instance of 'Attribute' could represent.
out alreadyExists Indicates if this instance of 'Attribute' already contains a nominal value called 'nominalValue'.
Definition at line 123 of file Attribute.cpp.
References KKB::KKStrListIndexed::Add(), KKB::KKStr::Concat(), GetNominalCode(), and KKB::KKStr::KKStr().
Referenced by KKMLL::FileDesc::AddANominalValue(), and KKMLL::FeatureFileIOC45::LoadFile().
{
  ValidateNominalType ("AddANominalValue");
  kkint32 code = GetNominalCode (nominalValue);
  if (code >= 0)
  {
    alreadyExists = true;
    return;
  }
  alreadyExists = false;
  nominalValuesUpper->Add (new KKStr (nominalValue));
} /* AddANominalValue */
kkint32 Attribute::Cardinality () const
Returns back the cardinality of the attribute; the number of possible values it can take.
Only attributes with type Nominal or Symbolic have a fixed number of possible values all others will return 999999999.
Definition at line 173 of file Attribute.cpp.
References KKMLL::Nominal, KKB::KKStrListIndexed::size(), and KKMLL::Symbolic.
Referenced by KKMLL::FileDesc::Cardinality(), KKMLL::FileDesc::DisplayAttributeMappings(), KKMLL::FeatureEncoder::FeatureEncoder(), and KKMLL::FeatureFileIOC45::SaveFile().
{
  if ((type == AttributeType::Nominal) ||
       (type == AttributeType::Symbolic)
      )
    return nominalValuesUpper->size ();
  else
    return 999999999;
} /* Cardinality */
kkint32 KKMLL::Attribute::FieldNum () const [inline]
Definition at line 106 of file Attribute.h.
Referenced by KKMLL::FileDesc::GetFieldNumFromAttributeName().
{return fieldNum;}
kkint32 Attribute::GetNominalCode (const KKStr & nominalValue) const
Definition at line 185 of file Attribute.cpp.
References KKB::KKStrListIndexed::LookUp().
Referenced by AddANominalValue(), KKMLL::FileDesc::DisplayAttributeMappings(), KKMLL::FeatureFileIODstWeb::LoadFile(), KKMLL::FeatureFileIOC45::LoadFile(), and KKMLL::FileDesc::LookUpNominalCode().
{
  ValidateNominalType ("GetNominalCode");
  kkint32 code = nominalValuesUpper->LookUp (nominalValue);
  return code;
} /* GetNominalCode */
const KKStr & Attribute::GetNominalValue (kkint32 code) const
Returns the nominal value for the given ordinal value.
For example: you could have a Attribute called DayOfTheWeek that would be type 'Nominal' where its possible values are `Sun`, `Mon`, `Tue`, `Wed`, `Thur`, `Fri`, and `Sat`. In this case a call to this method where 'code' == 3 would return `Wed`.
Definition at line 143 of file Attribute.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EmptyStr(), and KKB::KKStrListIndexed::LookUp().
Referenced by KKMLL::FileDesc::DisplayAttributeMappings(), KKMLL::FeatureEncoder::FeatureEncoder(), KKMLL::FeatureFileIORoberts::SaveFile(), and KKMLL::FeatureFileIOC45::SaveFile().
{
  ValidateNominalType ("GetNominalValue");
  static KKStr missingDataValue = "?";
  if (code == -1)
  {
    // Missing Value Flag.
    return missingDataValue;
  }
  if (!nominalValuesUpper)
    return KKStr::EmptyStr ();
  KKStrConstPtr result = nominalValuesUpper->LookUp (code);
  if (result == NULL)
  {
    cerr << endl << endl
      << "Attribute::GetNominalValue ***ERROR*** Code[" << code << "] Does not exist." <<
      endl
      << " Attribute::Name[" << name << "]" << endl
      << endl;
    return KKStr::EmptyStr ();
  }
  return *result;
} /* GetNominalValue */
kkint32 Attribute::MemoryConsumedEstimated () const
Definition at line 92 of file Attribute.cpp.
References KKB::KKStr::MemoryConsumedEstimated(), and KKB::KKStrListIndexed::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = sizeof (Attribute) +
           name.MemoryConsumedEstimated () +
           nameUpper.MemoryConsumedEstimated ();
  if (nominalValuesUpper)
    memoryConsumedEstimated += nominalValuesUpper->MemoryConsumedEstimated ();
  return memoryConsumedEstimated;
}
const KKStr& KKMLL::Attribute::Name () const [inline]
Definition at line 122 of file Attribute.h.
Referenced by KKMLL::FeatureEncoder::FeatureEncoder(), and KKMLL::FeatureFileIOC45::LoadFile().
{return name;}
const KKStr& KKMLL::Attribute::NameUpper () const [inline]
Definition at line 125 of file Attribute.h.
{return nameUpper;}
bool Attribute::operator!= (const Attribute & rightSide) const
Definition at line 213 of file Attribute.cpp.
References operator==().
{
  return !(*this == rightSide);
} /* operator== */
Attribute & Attribute::operator= (const Attribute & right)
Definition at line 222 of file Attribute.cpp.
References KKB::KKStrListIndexed::KKStrListIndexed(), and KKB::KKStr::operator=().
{
  fieldNum = right.fieldNum;
  name = right.name;
  nameUpper = right.nameUpper;
  delete nominalValuesUpper;
  if (nominalValuesUpper)
    nominalValuesUpper = new KKStrListIndexed (*right.nominalValuesUpper);
  else
    nominalValuesUpper = NULL;
  type = right.type;
  return *this;
} /* operator= */
bool Attribute::operator== (const Attribute & rightSide) const
Definition at line 194 of file Attribute.cpp.
References KKMLL::Nominal, KKB::KKStr::operator!=(), KKB::KKStrListIndexed::operator!=(), KKMLL::Symbolic, and Type().
Referenced by operator!=().
{
  if ((nameUpper != rightSide.nameUpper) || (Type () != rightSide.Type ()))
    return false;
  if ((type == AttributeType::Nominal) ||
       (type == AttributeType::Symbolic)
      )
  {
    // Lets make sure that the nominal values are equal. Not Case sensitive.
    if ((*nominalValuesUpper) != (*rightSide.nominalValuesUpper))
      return false;
  }
  return true;
} /* operator== */
void Attribute::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 283 of file Attribute.cpp.
References KKMLL::AttributeTypeFromStr(), KKB::XmlTag::AttributeValueInt32(), KKB::XmlTag::AttributeValueKKStr(), KKB::XmlStream::GetNextToken(), KKB::KKStr::operator=(), and KKB::KKStr::ToUpper().
{
  delete nominalValuesUpper;
  nominalValuesUpper = NULL;
  type = AttributeTypeFromStr (tag->AttributeValueKKStr ("Type"));
  fieldNum = tag->AttributeValueInt32 ("FieldNum");
  name = tag->AttributeValueKKStr ("Name");
  nameUpper = name.ToUpper ();
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if ((t->SectionName ().EqualIgnoreCase ("NominalValues")) && (typeid(*t) =
      = typeid(XmlElementVectorKKStr)))
    {
      delete nominalValuesUpper;
      nominalValuesUpper = new KKStrListIndexed (true, // true == nominalValuesUpper will
       own its contents.
                                                 false // false = Not Case Sensitive.
                                                );
      XmlElementVectorKKStrPtr v = dynamic_cast<
      XmlElementVectorKKStrPtr>(t);
      if ((v != NULL) && (v->Value () != NULL))
      {
        VectorKKStr::const_iterator idx;
        bool alreadyEixists = false;
        for (idx = v->Value ()->begin (); idx != v->Value ()->end (); ++idx)
          AddANominalValue (*idx, alreadyEixists);
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
}
AttributeType KKMLL::Attribute::Type () const [inline]
Definition at line 133 of file Attribute.h.
Referenced by KKMLL::FileDesc::AddAAttribute(), KKMLL::FileDesc::Cardinality(), KKMLL::FileDesc::DisplayAttributeMappings(), KKMLL::FeatureEncoder::FeatureEncoder(), KKMLL::FeatureFileIOC45::LoadFile(), KKMLL::FileDesc::LookUpNominalCode(), operator==(), KKMLL::FeatureFileIORoberts::SaveFile(), and KKMLL::FeatureFileIOC45::SaveFile().
{return type;}
KKStr Attribute::TypeStr () const
Definition at line 241 of file Attribute.cpp.
References KKMLL::AttributeTypeToStr().
Referenced by WriteXML().
{
  return AttributeTypeToStr (type);
} /* TypeStr */
void Attribute::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 249 of file Attribute.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKMLL::EncodeProblem(), KKMLL::Nominal, KKMLL::Symbolic, KKB::XmlTag::tagEmpty, KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, TypeStr(), KKB::VectorKKStr::WriteXML(), KKB::XmlTag::WriteXML(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::AttributeList::WriteXML().
{
  XmlTag::TagTypes startTagType = XmlTag::TagTypes::tagEmpty;
  if ((type == KKMLL::AttributeType::Nominal) ||
       (type == KKMLL::AttributeType::Symbolic)
      )
    startTagType = XmlTag::TagTypes::tagStart;
  XmlTag startTag ("Attribute", startTagType);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.AddAtribute ("Name", name);
  startTag.AddAtribute ("Type", TypeStr ());
  startTag.AddAtribute ("FieldNum", fieldNum);
  startTag.WriteXML (o);
  o << endl;
  if (startTagType == XmlTag::TagTypes::tagStart)
  {
    VectorKKStr nominalValues;
    for (kkint32 nominalIdx = 0; nominalIdx < Cardinality (); ++nominalIdx)
      nominalValues.push_back (GetNominalValue (nominalIdx));
    nominalValues.WriteXML ("NominalValues", o);
    XmlTag endTag ("Attribute", XmlTag::TagTypes::tagEnd);
    endTag.WriteXML (o);
    o << endl;
  }
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/Attribute.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/Attribute.cpp