KKMLL::MLClassList::MLClassNameComparison Class Reference
Public Member Functions
MLClassNameComparison ()
bool operator() (MLClassPtr p1, MLClassPtr p2)
Detailed Description
Definition at line 909 of file MLClass.cpp.
Constructor & Destructor Documentation
KKMLL::MLClassList::MLClassNameComparison::MLClassNameComparison () [inline]
Definition at line 912 of file MLClass.cpp.
Referenced by KKMLL::MLClassList::SortByName().
{}
Member Function Documentation
bool KKMLL::MLClassList::MLClassNameComparison::operator() (MLClassPtr p1, MLClassPtr p2) [inline]
Definition at line 914 of file MLClass.cpp.
References KKB::KKStr::operator<(), and KKMLL::MLClass::UpperName().
  {
    return (p1->UpperName () < p2->UpperName ());
  }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/MLClass.cpp