KKB::KKStrList::StringComparison Class Reference
Public Member Functions
StringComparison (bool _reversedOrder)
bool operator() (KKStrPtr p1, KKStrPtr p2)
Detailed Description
Definition at line 4740 of file KKStr.cpp.
Constructor & Destructor Documentation
KKB::KKStrList::StringComparison::StringComparison (bool _reversedOrder) [inline]
Definition at line 4743 of file KKStr.cpp.
Referenced by KKB::KKStrList::Sort().
   {
     reversedOrder = _reversedOrder;
   }
Member Function Documentation
bool KKB::KKStrList::StringComparison::operator() (KKStrPtr p1, KKStrPtr p2) [inline]
Definition at line 4749 of file KKStr.cpp.
References KKB::KKStr::CompareStrings(), and KKB::KKStr::Concat().
   {
     if (reversedOrder)
     {
       return (KKStr::CompareStrings (*p2, *p1) > 0);
     }
     else
     {
       return (KKStr::CompareStrings (*p1, *p2) < 0);
     }
   }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/KKStr.cpp