KKB::Configuration::ConfSectionList Class Reference
Public Member Functions
ConfSectionList ()
void AddConfSection (ConfSectionPtr section)
void AddConfSection (const KKStr &_name, kkint32 _lineNum)
ConfSectionPtr LookUp (const KKStr &_name)
kkint32 MemoryConsumedEstimated () const
Additional Inherited Members
Detailed Description
Definition at line 234 of file Configuration.cpp.
Constructor & Destructor Documentation
KKB::Configuration::ConfSectionList::ConfSectionList () [inline]
Definition at line 237 of file Configuration.cpp.
Referenced by KKB::Configuration::Configuration().
: KKQueue<ConfSection> (true) {}
Member Function Documentation
void KKB::Configuration::ConfSectionList::AddConfSection (ConfSectionPtr section) [inline]
Definition at line 269 of file Configuration.cpp.
Referenced by KKB::Configuration::Configuration().
    {
      PushOnBack (section);
    }
void KKB::Configuration::ConfSectionList::AddConfSection (const KKStr & _name, kkint32 _lineNum) [inline]
Definition at line 275 of file Configuration.cpp.
    {
      PushOnBack (new ConfSection (_name, _lineNum));
    }
ConfSectionPtr KKB::Configuration::ConfSectionList::LookUp (const KKStr & _name) [inline]
Definition at line 250 of file Configuration.cpp.
References KKB::KKStr::EqualIgnoreCase(), and KKB::Configuration::ConfSection::Name().
Referenced by KKB::Configuration::GetSetting(), KKB::Configuration::NumOfSettings(), KKB::Configuration::SectionDefined(), and KKB::Configuration::SettingName().
    {
      ConfSectionPtr tempSection = NULL;
      ConfSectionPtr section = NULL;
      ConfSectionList::const_iterator idx;
      for (idx = begin (); idx != end (); ++idx)
      {
        tempSection = *idx;
        if (_name.EqualIgnoreCase (tempSection->Name ()))
        {
          section = tempSection;
          break;
        }
      }
      return section;
    } /* LookUp */
kkint32 KKB::Configuration::ConfSectionList::MemoryConsumedEstimated () const [inline]
Definition at line 240 of file Configuration.cpp.
Referenced by KKB::Configuration::MemoryConsumedEstimated().
    {
      kkint32 memoryConsumedEstimated = sizeof (ConfSectionList);
      ConfSectionList::const_iterator idx;
      for (idx = begin (); idx != end (); ++idx)
        memoryConsumedEstimated += (*idx)->MemoryConsumedEstimated ();
      return memoryConsumedEstimated;
    }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Configuration.cpp