KKMLL::ClassStatisticList Class Reference
#include <ClassStatistic.h>
Classes
class ClassStatisticSortComparrison
class ClassStatSortByCount
Public Member Functions
ClassStatisticList (bool _owner)
ClassStatisticPtr LookUpByMLClass (MLClassPtr mlClass) const
const ClassStatisticList & operator+= (const ClassStatisticList &right)
kkint32 operator[] (MLClassPtr mlClass)
void PrintReport (std::ostream &r)
void PushOnBack (ClassStatisticPtr stat)
void PushOnFront (ClassStatisticPtr stat)
void SortByClassName ()
void SortByCount ()
Additional Inherited Members
Detailed Description
Definition at line 41 of file ClassStatistic.h.
Constructor & Destructor Documentation
ClassStatisticList::ClassStatisticList (bool _owner)
Definition at line 67 of file ClassStatistic.cpp.
References ClassStatisticList().
Referenced by ClassStatisticList(), and KKMLL::FeatureVectorList::GetClassStatistics().
                                                   :
   KKQueue<ClassStatistic> (_owner)
{
}
Member Function Documentation
ClassStatisticPtr ClassStatisticList::LookUpByMLClass (MLClassPtr mlClass) const
Definition at line 112 of file ClassStatistic.cpp.
Referenced by KKMLL::FeatureVectorList::GetClassStatistics(), and operator+=().
{
  map<MLClassPtr, ClassStatisticPtr>::const_iterator idx;
  idx = imageClassIndex.find (mlClass);
  if (idx == imageClassIndex.end ())
    return NULL;
  else
    return idx->second;
}
const ClassStatisticList & ClassStatisticList::operator+= (const ClassStatisticList & right)
Definition at line 91 of file ClassStatistic.cpp.
References KKMLL::ClassStatistic::ClassStatistic(), LookUpByMLClass(), KKMLL::ClassStatistic::MLClass(), KKMLL::ClassStatistic::operator+=(), and PushOnBack().
{
  ClassStatisticList::const_iterator idx;
  for (idx = right.begin (); idx != right.end (); idx++)
  {
    ClassStatisticPtr rightStat = *idx;
    ClassStatisticPtr leftStat = LookUpByMLClass (rightStat->
      MLClass ());
    if (leftStat)
      (*leftStat) += (*rightStat);
    else
      PushOnBack (new ClassStatistic (*rightStat));
  }
  return *this;
} /* operator+= */
kkint32 ClassStatisticList::operator[] (MLClassPtr mlClass)
Definition at line 198 of file ClassStatistic.cpp.
{
  std::map<MLClassPtr, ClassStatisticPtr>::const_iterator idx;
  idx = imageClassIndex.find (mlClass);
  if (idx == imageClassIndex.end ())
    return -1;
  else
    return idx->second->Count ();
}
void ClassStatisticList::PrintReport (std::ostream & r)
Definition at line 182 of file ClassStatistic.cpp.
References SortByClassName().
{
  r << endl
    << "Class Name" << "\t" << "Count" << endl;
  SortByClassName ();
  iterator idx;
  for (idx = begin (); idx != end (); idx++)
  {
    ClassStatisticPtr cs = *idx;
    r << cs->Name () << "\t" << cs->Count () << endl;
  }
  r << endl;
}
void ClassStatisticList::PushOnBack (ClassStatisticPtr stat)
Definition at line 74 of file ClassStatistic.cpp.
Referenced by KKMLL::FeatureVectorList::GetClassStatistics(), and operator+=().
{
  KKQueue<ClassStatistic>::PushOnBack (stat);
  imageClassIndex.insert (pair<MLClassPtr, ClassStatisticPtr> (stat->MLClass (), stat));
}
void ClassStatisticList::PushOnFront (ClassStatisticPtr stat)
Definition at line 82 of file ClassStatistic.cpp.
{
  KKQueue<ClassStatistic>::PushOnFront (stat);
  imageClassIndex.insert (pair<MLClassPtr, ClassStatisticPtr> (stat->MLClass (), stat));
}
void ClassStatisticList::SortByClassName ()
Definition at line 163 of file ClassStatistic.cpp.
Referenced by KKMLL::FeatureVectorList::GetClassStatistics(), and PrintReport().
{
  ClassStatisticSortComparrison c;
  //KKQueue<ClassStatistic>::Sort (&c);
  sort (begin (), end (), c);
} /* Sort */
void ClassStatisticList::SortByCount ()
Definition at line 173 of file ClassStatistic.cpp.
{
  ClassStatSortByCount c;
  //KKQueue<ClassStatistic>::Sort (&c);
  sort (begin (), end (), c);
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ClassStatistic.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ClassStatistic.cpp