KKMLL::FeatureFileIODstWeb::AttrDescLine Class Reference
Public Member Functions
AttrDescLine (KKStr desc)
Public Attributes
KKStr code
KKStr root
KKStr title
Detailed Description
Definition at line 32 of file FeatureFileIODstWeb.cpp.
Constructor & Destructor Documentation
KKMLL::FeatureFileIODstWeb::AttrDescLine::AttrDescLine (KKStr desc) [inline]
Definition at line 35 of file FeatureFileIODstWeb.cpp.
References KKB::KKStr::ChopLastChar(), KKMLL::FeatureFileIODstWeb::AttrDescLine::code, KKB::KKStr::Concat(), KKB::KKStr::ExtractToken(), KKB::KKStr::FirstChar(), KKB::KKStr::LastChar(), KKB::KKStr::operator=(), KKMLL::FeatureFileIODstWeb::AttrDescLine::root, KKB::KKStr::SubStrPart(), KKMLL::FeatureFileIODstWeb::AttrDescLine::title, KKB::KKStr::TrimLeft(), and KKB::KKStr::TrimRight().
Referenced by KKMLL::FeatureFileIODstWeb::GetFileDesc().
    {
      KKStr aStr = desc.ExtractToken (",\n\r\t");
      code = desc.ExtractToken (",\n\r\t");
      code.TrimLeft ();
      code.TrimRight ();
      KKStr oneStr = desc.ExtractToken (",\n\r\t");
     
      title = desc.ExtractToken (",\n\r\t");
      if (title.FirstChar () == '"')
        title = title.SubStrPart (1);
      if (title.LastChar () == '"')
        title.ChopLastChar ();
      root = desc.ExtractToken ();
      if (root.FirstChar () == '"')
        root = root.SubStrPart (1);
      if (root.LastChar () == '"')
        root.ChopLastChar ();
    }
Member Data Documentation
KKStr KKMLL::FeatureFileIODstWeb::AttrDescLine::code
Definition at line 58 of file FeatureFileIODstWeb.cpp.
Referenced by KKMLL::FeatureFileIODstWeb::AttrDescLine::AttrDescLine(), KKMLL::FeatureFileIODstWeb::GetFileDesc(), and KKMLL::FeatureFileIODstWeb::AttrDescLineComparator::operator()().
KKStr KKMLL::FeatureFileIODstWeb::AttrDescLine::root
Definition at line 60 of file FeatureFileIODstWeb.cpp.
Referenced by KKMLL::FeatureFileIODstWeb::AttrDescLine::AttrDescLine().
KKStr KKMLL::FeatureFileIODstWeb::AttrDescLine::title
Definition at line 59 of file FeatureFileIODstWeb.cpp.
Referenced by KKMLL::FeatureFileIODstWeb::AttrDescLine::AttrDescLine().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/FeatureFileIODstWeb.cpp