KKMLL::ModelParamUsfCasCor Class Reference
This class encapsulates are the information necessary to build a UsfCasCor class.
#include <ModelParamUsfCasCor.h>
Public Types
typedef ModelParamUsfCasCor * ModelParamUsfCasCorPtr
Public Member Functions
ModelParamUsfCasCor ()
ModelParamUsfCasCor (int _in_limit, int _out_limit, int _number_of_rounds, int _number_of_trials, kkint64 _random_seed, bool _useCache)
virtual ~ModelParamUsfCasCor ()
virtual ModelParamUsfCasCorPtr Duplicate () const
int In_limit () const
void In_limit (int _in_limit)
virtual ModelParamTypes ModelParamType () const
int Number_of_rounds () const
void Number_of_rounds (int _number_of_rounds)
int Number_of_trials () const
void Number_of_trials (int _number_of_trials)
int Out_limit () const
void Out_limit (int _out_limit)
kkint64 Random_seed () const
void Random_seed (kkint64 _random_seed)
virtual void ReadXML (XmlStream &s, XmlTagConstPtr tag, VolConstBool &cancelFlag, RunLog &log)
virtual KKStr ToCmdLineStr () const
Creates a Command Line String that represents these parameters.
bool UseCache () const
void UseCache (bool _useCache)
virtual void WriteXML (const KKStr &varName, ostream &o) const
Additional Inherited Members
Detailed Description
This class encapsulates are the information necessary to build a UsfCasCor class.
Definition at line 15 of file ModelParamUsfCasCor.h.
Member Typedef Documentation
typedef ModelParamUsfCasCor* KKMLL::ModelParamUsfCasCor::ModelParamUsfCasCorPtr
Definition at line 18 of file ModelParamUsfCasCor.h.
Constructor & Destructor Documentation
ModelParamUsfCasCor::ModelParamUsfCasCor ()
Definition at line 24 of file ModelParamUsfCasCor.cpp.
References KKMLL::ModelParam::ModelParam().
                                          :
  ModelParam (),
  in_limit (500),
  out_limit (500),
  number_of_rounds (-1),
  number_of_trials (1),
  random_seed (0),
  useCache (false)
{
}
ModelParamUsfCasCor::ModelParamUsfCasCor (int _in_limit, int _out_limit, int _number_of_rounds, int _number_of_trials, kkint64 _random_seed, bool _useCache)
Definition at line 38 of file ModelParamUsfCasCor.cpp.
References KKMLL::ModelParam::ModelParam().
                                           :
      ModelParam (),
      in_limit (_in_limit),
      out_limit (_out_limit),
      number_of_rounds (_number_of_rounds),
      number_of_trials (_number_of_trials),
      random_seed (_random_seed),
      useCache (_useCache)
{}
ModelParamUsfCasCor::~ModelParamUsfCasCor () [virtual]
Definition at line 57 of file ModelParamUsfCasCor.cpp.
{
}
Member Function Documentation
ModelParamUsfCasCorPtr ModelParamUsfCasCor::Duplicate () const [virtual]
Implements KKMLL::ModelParam.
Definition at line 62 of file ModelParamUsfCasCor.cpp.
{
  return new ModelParamUsfCasCor (*this);
} /* Duplicate */
int KKMLL::ModelParamUsfCasCor::In_limit () const [inline]
Definition at line 38 of file ModelParamUsfCasCor.h.
Referenced by KKMLL::ModelUsfCasCor::TrainModel().
{return in_limit;}
void KKMLL::ModelParamUsfCasCor::In_limit (int _in_limit) [inline]
Definition at line 47 of file ModelParamUsfCasCor.h.
{in_limit = _in_limit;}
virtual ModelParamTypes KKMLL::ModelParamUsfCasCor::ModelParamType () const [inline], [virtual]
Implements KKMLL::ModelParam.
Definition at line 34 of file ModelParamUsfCasCor.h.
References KKMLL::ModelParam::UsfCasCor.
{return ModelParamTypes::UsfCasCor;}
int KKMLL::ModelParamUsfCasCor::Number_of_rounds () const [inline]
Definition at line 40 of file ModelParamUsfCasCor.h.
Referenced by KKMLL::TrainingConfiguration2::Number_of_rounds(), and KKMLL::ModelUsfCasCor::TrainModel().
{return number_of_rounds;}
void KKMLL::ModelParamUsfCasCor::Number_of_rounds (int _number_of_rounds) [inline]
Definition at line 49 of file ModelParamUsfCasCor.h.
Referenced by KKMLL::TrainingConfiguration2::Number_of_rounds().
{number_of_rounds = _number_of_rounds;}
int KKMLL::ModelParamUsfCasCor::Number_of_trials () const [inline]
Definition at line 41 of file ModelParamUsfCasCor.h.
Referenced by KKMLL::ModelUsfCasCor::TrainModel().
{return number_of_trials;}
void KKMLL::ModelParamUsfCasCor::Number_of_trials (int _number_of_trials) [inline]
Definition at line 50 of file ModelParamUsfCasCor.h.
{number_of_trials = _number_of_trials;}
int KKMLL::ModelParamUsfCasCor::Out_limit () const [inline]
Definition at line 39 of file ModelParamUsfCasCor.h.
Referenced by KKMLL::ModelUsfCasCor::TrainModel().
{return out_limit;}
void KKMLL::ModelParamUsfCasCor::Out_limit (int _out_limit) [inline]
Definition at line 48 of file ModelParamUsfCasCor.h.
{out_limit = _out_limit;}
kkint64 KKMLL::ModelParamUsfCasCor::Random_seed () const [inline]
Definition at line 42 of file ModelParamUsfCasCor.h.
Referenced by KKMLL::ModelUsfCasCor::TrainModel().
{return random_seed;}
void KKMLL::ModelParamUsfCasCor::Random_seed (kkint64 _random_seed) [inline]
Definition at line 51 of file ModelParamUsfCasCor.h.
{random_seed = _random_seed;}
void ModelParamUsfCasCor::ReadXML (XmlStream & s, XmlTagConstPtr tag, VolConstBool & cancelFlag, RunLog & log) [virtual]
Implements KKMLL::ModelParam.
Definition at line 189 of file ModelParamUsfCasCor.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::EqualIgnoreCase(), KKB::XmlStream::GetNextToken(), KKMLL::ModelParam::ReadXMLModelParamToken(), KKB::XmlToken::tokElement, KKB::XmlToken::TokenType(), KKB::XmlElementBool::Value(), and KKB::XmlElement::VarName().
{
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    t = ReadXMLModelParamToken (t);
    if ((t != NULL) && (t->TokenType () == XmlToken::TokenTypes::tokElement))
    {
      XmlElementPtr e = dynamic_cast<XmlElementPtr> (t);
      const KKStr& varName = e->VarName ();
      if (varName.EqualIgnoreCase ("in_limit"))
        in_limit = dynamic_cast<XmlElementInt32Ptr> (e)->Value ();
      else if (varName.EqualIgnoreCase ("number_of_rounds"))
        number_of_rounds = dynamic_cast<XmlElementInt32Ptr> (e)->Value ();
      else if (varName.EqualIgnoreCase ("number_of_trials"))
        number_of_trials = dynamic_cast<XmlElementInt32Ptr> (e)->Value ();
      else if (varName.EqualIgnoreCase ("random_seed"))
        random_seed = dynamic_cast<XmlElementInt64Ptr> (e)->Value ();
      else if (varName.EqualIgnoreCase ("useCache"))
        useCache = dynamic_cast<XmlElementBoolPtr> (e)->Value ();
      else
      {
        log.Level (-1) << endl
          << "ModelParamUsfCasCor::ReadXM ***ERROR*** Unexpected Element: " << e->
      NameTag ()->ToString () << endl
          << endl;
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
  bool validFormat = false;
} /* ReadXML */
KKStr ModelParamUsfCasCor::ToCmdLineStr () const [virtual]
Creates a Command Line String that represents these parameters.
Convert all parameters to a command line string.
All derived classes should implement this method. They should first call this method and then append there own parameters that are specific to their implementation.
Reimplemented from KKMLL::ModelParam.
Definition at line 139 of file ModelParamUsfCasCor.cpp.
References KKB::KKStr::Concat(), and KKB::KKStr::KKStr().
{
  KKStr cmdStr (300);
  cmdStr << "-InLimit " << in_limit << " "
         << "-OutLimit " << out_limit;
  if (number_of_rounds > 0)
    cmdStr << " -R " << number_of_rounds;
  cmdStr << " -T " << number_of_trials;
  if (random_seed > 0)
    cmdStr << " -S " << random_seed;
  cmdStr << " -UseCache " << (useCache ? "Yes" : "No");
  return cmdStr;
} /* ToCmdLineStr */
bool KKMLL::ModelParamUsfCasCor::UseCache () const [inline]
Definition at line 43 of file ModelParamUsfCasCor.h.
Referenced by KKMLL::ModelUsfCasCor::TrainModel().
{return useCache;}
void KKMLL::ModelParamUsfCasCor::UseCache (bool _useCache) [inline]
Definition at line 52 of file ModelParamUsfCasCor.h.
{useCache = _useCache;}
void ModelParamUsfCasCor::WriteXML (const KKStr & varName, ostream & o) const [virtual]
Definition at line 162 of file ModelParamUsfCasCor.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), KKB::XmlElementBool::WriteXML(), KKMLL::ModelParam::WriteXMLFields(), and KKB::XmlTag::XmlTag().
{
  XmlTag startTag ("ModelParamUsfCasCor", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  WriteXMLFields (o);
  XmlElementInt32::WriteXML (in_limit, "in_limit", o);
  XmlElementInt32::WriteXML (number_of_rounds, "number_of_rounds", o);
  XmlElementInt32::WriteXML (number_of_trials, "number_of_trials", o);
  XmlElementInt64::WriteXML (random_seed, "random_seed", o);
  XmlElementBool::WriteXML (useCache, "useCache", o);
  
  XmlTag endTag ("ModelParamUsfCasCor", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
} /* WriteXML */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelParamUsfCasCor.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ModelParamUsfCasCor.cpp