KKJobManagment::KKJobManager Class Reference
Responsable for keeping track of a list of jobs.
#include <KKJobManager.h>
Public Types
typedef KKJobManager * JobManagerPtr
Public Member Functions
KKJobManager (const KKJobManager &j)
KKJobManager (JobManagerPtr _manager, kkint32 _jobId, kkint32 _parentId, kkint32 _numPorcessesAllowed, const KKStr &_managerName, kkint32 _numJobsAtATime, RunLog &_log)
~KKJobManager ()
kkint32 AllocateNextJobId ()
bool AreAllJobsDone ()
void Block ()
double CpuTimeTotalUsed () const
virtual KKJobPtr Duplicate () const =0
void EndBlock ()
kkint32 ExpansionCount () const
kkint32 GetNextJobId ()
void InitilizeJobManager (bool &successful)
Initialize the KKJobManager object.
KKJobListPtr Jobs () const
virtual const char * JobType () const
const KKStr & ManagerName () const
kkint32 NextJobId () const
bool QuitRunning () const
void Restart ()
void Run ()
void SetQuitRunningFlag ()
bool SupportCompletedJobData () const
void SupportCompletedJobData (bool _supportCompletedJobData)
void Update (JobManagerPtr p)
Protected Member Functions
virtual void StatusFileProcessLine (const KKStr &ln, istream &statusFile)
virtual void StatusFileProcessLineJobStatusChange (KKStr &statusLineStr)
virtual KKStr ToStatusStr ()
Additional Inherited Members
Detailed Description
Responsable for keeping track of a list of jobs.
See the application called RandomSplitsJobManager. It is the first alplication to use this library; any class that is derived from this class are required to implement these method `StatusFileProcessLine`, `StatusFileProcessLineJobStatusChange`, `ToStatusStr`
Definition at line 29 of file KKJobManager.h.
Member Typedef Documentation
typedef KKJobManager* KKJobManagment::KKJobManager::JobManagerPtr
Definition at line 32 of file KKJobManager.h.
Constructor & Destructor Documentation
KKJobManager::KKJobManager (const KKJobManager & j)
Definition at line 43 of file KKJobManager.cpp.
References KKJobManagment::KKJob::AddPrerequisites(), KKB::DateTime::DateTime(), KKJobManagment::KKJob::KKJob(), KKJobManagment::KKJobList::KKJobList(), and KKB::KKStr::KKStr().
                                                :
  KKJob (j),
  cpuTimeLastReported (j.cpuTimeLastReported),
  cpuTimeTotalUsed (j.cpuTimeTotalUsed),
  dateTimeStarted (j.dateTimeStarted),
  dateTimeEnded (j.dateTimeEnded),
  dateTimeFirstOneFound (j.dateTimeFirstOneFound),
  jobs (NULL),
  
  blockLevel (j.blockLevel),
  lockFile (j.lockFile),
  lockFileName (j.lockFileName),
  lockFileOpened (j.lockFileOpened),
  managerName (j.managerName),
  expansionCount (j.expansionCount),
  expansionFirstJobId (j.expansionFirstJobId),
  nextJobId (j.nextJobId),
  numJobsAtATime (j.numJobsAtATime),
  procId (j.procId),
  quitRunning (j.quitRunning),
  restart (j.restart),
  statusFileName (j.statusFileName),
  statusFileNextByte (j.statusFileNextByte),
  supportCompletedJobData (j.supportCompletedJobData)
{
  jobs = new KKJobList (*j.jobs);
}
KKJobManagment::KKJobManager::KKJobManager (JobManagerPtr _manager, kkint32 _jobId, kkint32 _parentId, kkint32 _numPorcessesAllowed, const KKStr & _managerName, kkint32 _numJobsAtATime, RunLog & _log)
Parameters
_manager Ptr to job that is managing this 'KKJobManager'
_managerName Name of this 'KKJobManager' ; status and lock file will be based on it.
_numJobsAtATime The number of jobs that can be allocatd at one time for a single process to execute.
KKJobManager::~KKJobManager ()
Definition at line 126 of file KKJobManager.cpp.
{
  delete jobs;
  //EndBlock ();
}
Member Function Documentation
kkint32 KKJobManager::AllocateNextJobId ()
Definition at line 709 of file KKJobManager.cpp.
{
  kkint32 jobId = nextJobId;
  nextJobId++;
  return jobId;
}
bool KKJobManager::AreAllJobsDone ()
Definition at line 954 of file KKJobManager.cpp.
References KKJobManagment::KKJobList::AreAllJobsDone().
{
  if (jobs)
  {
    return jobs->AreAllJobsDone ();
  }
  else
  {
    // Will assume false for now.
    return false;
  }
} /* AreAllJobsAreDone */
void KKJobManager::Block ()
Definition at line 191 of file KKJobManager.cpp.
References KKB::osSleep().
Referenced by InitilizeJobManager(), Run(), and SetQuitRunningFlag().
{
  blockLevel++;
  log.Level (20) << "KKJobManager::Block blockLevel[" << blockLevel << "]" <<
      endl;
  if (blockLevel > 1)
  {
    // We already have a Block established; so there is no need to establish it now.
    return;
  }
  if (lockFileOpened)
  {
    // We have out Lock and EndLock calls out of order.
    log.Level (-1) << endl << endl
                    << "KKJobManager::Block *** WE ALREADY HAVE A BLOCK ESTABLISHED ***." << endl
                    << endl;
    return;
  }
  
  kkint32 count = 0;
  do {
    lockFile = open (lockFileName.Str (), O_WRONLY | O_CREAT | O_EXCL);
    if (lockFile < 0)
    {
      count++;
      float zed = (float)((procId + rand ()) % 10) + 2.0f;
      log.Level (10) << "KKJobManager::Block - We are locked out[" << count << "] for [" << zed <<
       "] secs." << endl;
      osSleep (zed);
    }
  } while (lockFile < 0);
  if (count > 0)
    log.Level (10) << "KKJobManager::Block Lock has been established." <<
      endl;
  lockFileOpened = true;
  log.Level (20) << "KKJobManager::Block - Lock is Established." << endl;
} /* Block */
double KKJobManagment::KKJobManager::CpuTimeTotalUsed () const [inline]
Definition at line 65 of file KKJobManager.h.
{return cpuTimeTotalUsed;}
virtual KKJobPtr KKJobManagment::KKJobManager::Duplicate () const [pure virtual]
Create a duplicate instance.
Reimplemented from KKJobManagment::KKJob.
void KKJobManager::EndBlock ()
Definition at line 235 of file KKJobManager.cpp.
Referenced by InitilizeJobManager(), Run(), SetQuitRunningFlag(), and StatusFileProcessLineJobStatusChange().
{
  blockLevel--;
  #ifndef WIN32
  kkint32 returnCd;
  #endif
  
 
  log.Level (20) << "KKJobManager::EndBlock - Ending Block blockLevel[" << blockLevel << "]" <<
      endl;
  if (blockLevel > 0)
  {
    // We are still nested in Block Levels. must reach 'blockLevel == 0' before we can UnBlock.
    return;
  }
  if (!lockFileOpened)
  {
    log.Level (-1) << endl << endl << endl
                   << "KKJobManager::EndBlock *** Lock file is not opened ***" <<
      endl;
    return;
  }
  close (lockFile);
  lockFileOpened = false;
  #ifdef WIN32
  if (!DeleteFile (lockFileName.Str ()))
  {
     DWORD fileAttributes = GetFileAttributes (lockFileName.Str ());
     fileAttributes = FILE_ATTRIBUTE_NORMAL;
     if (!SetFileAttributes (lockFileName.Str (), fileAttributes))
     {
       DWORD lastErrorNum = GetLastError ();
       log.Level (-1) << "KKJobManager::EndBlock - *** ERROR *** Could not set Lock File to
       Normal." << endl;
     }
     else
     {
       if (!DeleteFile (lockFileName.Str ()))
       {
         DWORD lastErrorNum = GetLastError ();
         log.Level (-1) << "KKJobManager::EndBlock - Error[" << (
      kkuint32)lastErrorNum << "] deleting Lock File." << endl;
       }
     }
  }
  #else
  returnCd = unlink (lockFileName.Str ());
  #endif
  log.Level (20) << "EndBlock - Unlocking" << endl;
  return;
} /* EndBlock */
kkint32 KKJobManagment::KKJobManager::ExpansionCount () const [inline]
Definition at line 66 of file KKJobManager.h.
{return expansionCount;}
kkint32 KKJobManager::GetNextJobId ()
Definition at line 292 of file KKJobManager.cpp.
{
  kkint32 jobIdToReturn = nextJobId;
  nextJobId++;
  return jobIdToReturn;
}
void KKJobManager::InitilizeJobManager (bool & successful)
Initialize the KKJobManager object.
This is the first Method that needs to be called right after the object is constructed.
Definition at line 134 of file KKJobManager.cpp.
References Block(), KKB::KKStr::Concat(), EndBlock(), KKB::osFileExists(), and KKB::osGetSystemTimeUsed().
{
  successful = true;
  Block ();
  cpuTimeLastReported = osGetSystemTimeUsed ();
  if (!osFileExists (statusFileName))
  {
    try
    {
      LoadRunTimeData ();
    }
    catch (KKStr errorMsg)
    {
      log.Level (-1) << endl << endl
                     << "KKJobManager::InitilizeJobManager ***ERROR*** Load of 'LoadRunTimeData'
       Failed." << endl
                     << endl
                     << errorMsg << endl
                     << endl;
      successful = false;
      return;
    }
    StatusFileInitialize ();
  }
  else
  {
    StatusFileLoad ();
    try
    {
      LoadRunTimeData ();
    }
    catch (KKStr errorMsg)
    {
      log.Level (-1) << endl << endl
                     << "KKJobManager::InitilizeJobManager ***ERROR*** Load of 'LoadRunTimeData'
       Failed." << endl
                     << endl
                     << errorMsg << endl
                     << endl;
      successful = false;
      return;
    }
  }
  EndBlock ();
} /* InitilizeJobManager */
KKJobListPtr KKJobManagment::KKJobManager::Jobs () const [inline]
Definition at line 67 of file KKJobManager.h.
{return jobs;}
const char * KKJobManager::JobType () const [virtual]
Allows us to know which specific implementaion of 'KKJob' an instance really is.
Reimplemented from KKJobManagment::KKJob.
Definition at line 184 of file KKJobManager.cpp.
{
  return "KKJobManager";
}
const KKStr& KKJobManagment::KKJobManager::ManagerName () const [inline]
Definition at line 68 of file KKJobManager.h.
{return managerName;}
kkint32 KKJobManagment::KKJobManager::NextJobId () const [inline]
Definition at line 69 of file KKJobManager.h.
{return nextJobId;}
bool KKJobManagment::KKJobManager::QuitRunning () const [inline]
Definition at line 70 of file KKJobManager.h.
{return quitRunning;}
void KKJobManagment::KKJobManager::Restart ()
void KKJobManager::Run ()
Definition at line 970 of file KKJobManager.cpp.
References KKJobManagment::KKJob::AddPrerequisites(), Block(), KKJobManagment::KKJob::Duplicate(), EndBlock(), KKJobManagment::KKJobList::JobsStillRunning(), KKJobManagment::KKJob::jsDone, KKJobManagment::KKJobList::KKJobList(), KKJobManagment::KKJob::ProcessNode(), KKJobManagment::KKJobList::PushOnBack(), and KKJobManagment::KKJob::status.
{
  log.Level (10) << "KKJobManager::Run." << endl;
  bool keepOnRunning = true;
  KKJobListPtr executedJobs = NULL;
  KKJobListPtr jobsToExecute = GetNextSetOfJobs (NULL);
  while (keepOnRunning && (!quitRunning))
  {
    if (jobsToExecute)
    {
      delete executedJobs; executedJobs = NULL;
      executedJobs = new KKJobList (this);
      executedJobs->Owner (true);
      KKJobList::iterator idx;
      for (idx = jobsToExecute->begin (); idx != jobsToExecute->end (); idx++)
      {
        KKJobPtr j = *idx;
        j->ProcessNode ();
        executedJobs->PushOnBack (j->Duplicate ());
      }
      delete jobsToExecute; jobsToExecute = NULL;
    }
    else
    {
      if (!(jobs->JobsStillRunning ()))
      {
        keepOnRunning = false;
      }
      else
      {
        // We will sleep for a bit until there are more jobs to run
        log.Level (10) << "KKJobManager::Run No jobs avaialble to run; will sleep a bit." <<
      endl;
        osSleep ((float)(30 + rand () % 10));
      }
    }
    if (keepOnRunning)
      jobsToExecute = GetNextSetOfJobs (executedJobs);
    delete executedJobs; executedJobs = NULL;
  }
  Block ();
  StatusFileRefresh ();
  if ((!quitRunning) && (status != KKJob::jsDone))
  {
    if (status != KKJob::jsDone)
    {
      GenerateFinalResultsReport ();
      
      status = KKJob::jsDone;
    
      ofstream* statusFile = StatusFileOpen (ios::app);
      *statusFile << "Status" << "\t" << StatusStr () << endl;
      ReportCpuTimeUsed (statusFile);
      statusFile->close ();
      delete statusFile;
    }
  }
  EndBlock ();
  log.Level (10) << "KKJobManager::Run Exiting." << endl;
} /* Run */
void KKJobManager::SetQuitRunningFlag ()
Definition at line 785 of file KKJobManager.cpp.
References Block(), and EndBlock().
{
  Block ();
  ofstream* statusFile = StatusFileOpen (ios::app);
  *statusFile << "QuitRunning" << endl;
  quitRunning = true;
  statusFile->flush ();
  statusFile->close ();
  delete statusFile; statusFile = NULL;
  EndBlock ();
} /* SetQuitRunningFlag */
void KKJobManager::StatusFileProcessLine (const KKStr & ln, istream & statusFile) [protected], [virtual]
Definition at line 341 of file KKJobManager.cpp.
References KKJobManagment::KKJob::AddPrerequisites(), KKJobManagment::KKJob::CallAppropriateConstructor(), KKB::KKStr::CompareIgnoreCase(), KKB::KKStr::Concat(), KKB::DateTime::DateTime(), KKB::KKStr::Empty(), KKB::KKStr::EqualIgnoreCase(), KKB::KKStr::ExtractToken2(), KKB::KKStr::ExtractTokenDouble(), KKB::KKStr::ExtractTokenInt(), KKJobManagment::KKJob::JobId(), KKJobManagment::KKJob::JobStatusFromStr(), KKB::KKStr::KKStr(), KKJobManagment::KKJobList::LookUpByJobId(), KKB::KKStr::operator=(), KKB::DateTime::operator=(), KKB::KKStr::operator==(), KKJobManagment::KKJobList::PushOnBack(), KKJobManagment::KKJob::ReFresh(), KKJobManagment::KKJob::status, StatusFileProcessLineJobStatusChange(), KKB::KKStr::SubStrPart(), KKB::KKStr::ToInt(), KKB::KKStr::TrimLeft(), and KKB::KKStr::TrimRight().
{
  if (ln.SubStrPart (0, 1) == "//")
  {
    // A coment line; we can ignore it.
    return;
  }
  KKStr statusStr (ln);
  KKStr fieldName = statusStr.ExtractToken2 ("\t");
  if (fieldName.Empty ())
  {
    // A empty line we will ignore it.
    return;
  }
  statusStr.TrimLeft ("\n\r\t ");
  statusStr.TrimRight ("\n\r\t ");
  if (fieldName.CompareIgnoreCase ("JOB") == 0)
  {
    // We have a KKJob entr line; the next field determines JobType fllowed by parameters for that JobType
       constructor.
    KKStr jobTypeName = fieldName = statusStr.ExtractToken2 ("\t");
    KKJobPtr j = KKJob::CallAppropriateConstructor (this,
      jobTypeName, statusStr);
    KKJobPtr existingJob = jobs->LookUpByJobId (j->JobId ());
    if (existingJob)
    {
      existingJob->ReFresh (*j);
      delete j; j = NULL;
    }
    else
    {
      jobs->PushOnBack (j);
    }
  }
  else if (fieldName.EqualIgnoreCase ("CPUTIMEUSED"))
  {
    double cpuTimeUsed = statusStr.ExtractTokenDouble ("\t");
    cpuTimeTotalUsed += cpuTimeUsed;
  }
  else if (fieldName.EqualIgnoreCase ("CURRENTDATETIME"))
  {
    KKB::DateTime dateTime = KKB::DateTime (statusStr);
    if (!dateTimeFirstOneFound)
    {
      dateTimeFirstOneFound = true;
      dateTimeStarted = dateTime;
    }
    dateTimeEnded = dateTime;
  }
  else if (fieldName.EqualIgnoreCase ("ExpansionCount"))
    expansionCount = statusStr.ToInt ();
  else if (fieldName.EqualIgnoreCase ("ExpansionFirstJobId"))
    expansionFirstJobId = statusStr.ToInt ();
  else if (fieldName.EqualIgnoreCase ("JobStatusChange"))
    StatusFileProcessLineJobStatusChange (statusStr);
  else if (fieldName.EqualIgnoreCase ("NextJobId"))
    nextJobId = statusStr.ExtractTokenInt ("\t");
  else if (fieldName.EqualIgnoreCase ("QuitRunning"))
    quitRunning = true;
  else if (fieldName.EqualIgnoreCase ("Restart"))
    restart = false;
  else if (fieldName.EqualIgnoreCase ("Status"))
    status = KKJob::JobStatusFromStr (statusStr);
  else
  {
    log.Level (-1) << "KKJobManager::StatusFileProcessLine Invalid Field Name[" << fieldName << "
      ]." << endl;
  }
} /* StatusFileProcessLine */
void KKJobManager::StatusFileProcessLineJobStatusChange (KKStr & statusLineStr) [protected], [virtual]
Definition at line 302 of file KKJobManager.cpp.
References KKJobManagment::KKJob::AddPrerequisites(), KKB::KKStr::Concat(), EndBlock(), KKB::KKStr::ExtractToken2(), KKB::KKStr::ExtractTokenInt(), KKJobManagment::KKJob::JobStatusFromStr(), KKJobManagment::KKJob::jsNULL, KKJobManagment::KKJobList::LookUpByJobId(), KKB::osWaitForEnter(), KKJobManagment::KKJob::Status(), KKB::KKStr::TrimLeft(), and KKB::KKStr::TrimRight().
Referenced by StatusFileProcessLine().
{
  kkint32 expandedJobId = statusLineStr.ExtractTokenInt ("\t");
  KKJobPtr j = jobs->LookUpByJobId (expandedJobId);
  if (!j)
  {
    log.Level (-1) << endl << endl << endl
                   << "ProcessStatusLineJobStatusChange ***Error*** Could not locate Expanded" <<
      endl
                   << endl
                   << " JobId[" << expandedJobId << "]" <<
      endl
                   << endl;
    EndBlock ();
    osWaitForEnter ();
    exit (-1);
  }
  KKStr statusStr = statusLineStr.ExtractToken2 ("\t");
  statusStr.TrimLeft ();
  statusStr.TrimRight ();
  KKJob::JobStatus status = KKJob::JobStatusFromStr (
      statusStr);
  if (status == jsNULL)
  {
    log.Level (-1) << endl << endl << endl
                   << "ProcessStatusLineJobStatusChange ***Error*** Invalid Status Specified" <<
      endl
                   << endl
                   << " JobId[" << expandedJobId << "]" <<
      endl
                   << " Status[" << statusStr << "]" <<
      endl
                   << endl;
    EndBlock ();
    osWaitForEnter ();
    exit (-1);
  }
  
  j->Status (status);
} /* ProcessStatusLineJobStatusChange */
bool KKJobManagment::KKJobManager::SupportCompletedJobData () const [inline]
Definition at line 60 of file KKJobManager.h.
{return supportCompletedJobData;}
void KKJobManagment::KKJobManager::SupportCompletedJobData (bool _supportCompletedJobData) [inline]
Definition at line 62 of file KKJobManager.h.
{supportCompletedJobData = _supportCompletedJobData;}
KKStr KKJobManager::ToStatusStr () [protected], [virtual]
derived classes should implement this method. They need to return a tab delimietd string with all there parameters <FieldName1> <> <FieldValue1> <> <fieldName2> <> <FieldValue2> etc etc etc ... They should call the base Class version of this method and return that string first. ex: return KKJobManager::ToStatusStr () + `\t` + `FieldName1` + `\t` + `Value1` + `\t` + `FieldName2` + `\t` + `Value2`;
Reimplemented from KKJobManagment::KKJob.
Definition at line 728 of file KKJobManager.cpp.
References KKJobManagment::KKJob::AddPrerequisites(), KKB::KKStr::Concat(), KKJobManagment::KKJob::JobStatusToStr(), KKB::KKStr::KKStr(), KKJobManagment::KKJob::status, and KKJobManagment::KKJob::ToStatusStr().
{
  KKStr statusStr (200); // PreAllocate 200 bytes
  statusStr << KKJob::ToStatusStr () << "\t"
            << "Status" << "\t" << KKJob::JobStatusToStr (
      status) << "\t"
            << "NextJobId" << "\t" << nextJobId << "\t"
            << "ExpansionCount" << "\t" << expansionCount << "\t"
            << "ExpansionFirstJobId" << "\t" << expansionFirstJobId;
  return statusStr;
} /* ToStatusStr */
void KKJobManager::Update (JobManagerPtr p)
Definition at line 719 of file KKJobManager.cpp.
References KKJobManagment::KKJob::status.
{
  status = p->status;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/JobManager/KKJobManager.h
C:/Users/Kurt/GitHub/KSquareLibraries/JobManager/KKJobManager.cpp