KKB::GlobalGoalKeeper Class Reference
Maintains one instance of a GoalKeeper object that can be used anywhere in the application.
#include <GlobalGoalKeeper.h>
Static Public Member Functions
static void EndBlock ()
static void StartBlock ()
Detailed Description
Maintains one instance of a GoalKeeper object that can be used anywhere in the application.
It is meant to be used for simple cases.
Definition at line 23 of file GlobalGoalKeeper.h.
Member Function Documentation
void GlobalGoalKeeper::EndBlock () [static]
Definition at line 51 of file GlobalGoalKeeper.cpp.
References KKB::GoalKeeper::EndBlock().
Referenced by KKB::RunLog::Append(), KKLSC::ScannerFileSimple::CompensationTable(), KKLSC::ScannerFile2BitEncoded::CompensationTable(), KKLSC::ScannerFile3BitEncoded::CompensationTable(), KKLSC::ScannerFile4BitEncoded::CompensationTable(), KKB::Compressor::Decompress(), KKMLL::GrayScaleImagesFVProducer::DefineFileDescStatic(), KKMLL::GrayScaleImagesFVProducerFactory::Factory(), KKMLL::TrainingConfiguration2::FactoryInstace(), XmlFactoryTrainingClass::FactoryInstance(), XmlFactoryModelOldSVM::FactoryInstance(), KKB::XmlFactoryManager::FactoryLookUp(), KKB::XmlFactory::FactoryLookUp(), KKMLL::FeatureVectorProducer::FileDesc(), KKMLL::FeatureFileIO::FinalCleanUp(), KKLSC::ScannerFileEntry::GetOrCreateScannerFileEntry(), KKMLL::FactoryFVProducer::LookUpFactory(), KKMLL::TrainingConfiguration2::Manufacture(), KKMLL::FeatureFileIO::RegisterDriver(), KKMLL::FactoryFVProducer::RegisterFactory(), KKB::XmlFactoryManager::RegisterFactory(), KKB::XmlFactory::RegisterFactory(), KKMLL::TrainingConfiguration2::RegisterFatory(), KKMLL::FeatureFileIO::RegisterFeatureFileIODriver(), KKB::KKObservable::RegisterObserver(), KKB::KKObservable::UnRegisterObserver(), KKB::RunLog::WriteLine(), and KKB::KKObserver::~KKObserver().
{
  if (!globalGoalie)
    CreateGlobalGoalie ();
  globalGoalie->EndBlock ();
}
void GlobalGoalKeeper::StartBlock () [static]
Definition at line 42 of file GlobalGoalKeeper.cpp.
References KKB::GoalKeeper::StartBlock().
Referenced by KKB::RunLog::Append(), KKLSC::ScannerFileSimple::CompensationTable(), KKLSC::ScannerFile2BitEncoded::CompensationTable(), KKLSC::ScannerFile3BitEncoded::CompensationTable(), KKLSC::ScannerFile4BitEncoded::CompensationTable(), KKB::Compressor::Decompress(), KKMLL::GrayScaleImagesFVProducer::DefineFileDescStatic(), KKMLL::GrayScaleImagesFVProducerFactory::Factory(), KKMLL::TrainingConfiguration2::FactoryInstace(), XmlFactoryTrainingClass::FactoryInstance(), XmlFactoryModelOldSVM::FactoryInstance(), KKB::XmlFactoryManager::FactoryLookUp(), KKB::XmlFactory::FactoryLookUp(), KKMLL::FeatureVectorProducer::FileDesc(), KKMLL::FeatureFileIO::FinalCleanUp(), KKLSC::ScannerFileEntry::GetOrCreateScannerFileEntry(), KKMLL::FactoryFVProducer::LookUpFactory(), KKMLL::TrainingConfiguration2::Manufacture(), KKMLL::FeatureFileIO::RegisterDriver(), KKMLL::FactoryFVProducer::RegisterFactory(), KKB::XmlFactoryManager::RegisterFactory(), KKB::XmlFactory::RegisterFactory(), KKMLL::TrainingConfiguration2::RegisterFatory(), KKMLL::FeatureFileIO::RegisterFeatureFileIODriver(), KKB::KKObservable::RegisterObserver(), KKB::KKObservable::UnRegisterObserver(), KKB::RunLog::WriteLine(), and KKB::KKObserver::~KKObserver().
{
  if (!globalGoalie)
    CreateGlobalGoalie ();
  globalGoalie->StartBlock ();
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/GlobalGoalKeeper.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/GlobalGoalKeeper.cpp