KKB::BmpImage Class Reference
Used to encode and decode BMP Images.
#include <BMPImage.h>
Classes
struct Bmp1BitRec
struct Bmp4BitRecs
struct BMP_24BitPixel
class CodedPixels
This object is used to help encode the data stored in BMPImage::image into 8 or 4 bit compressed formats used by BMP files. *.
struct CodePair
class PalletBuilder
Public Types
typedef CodePair * CodePairPtr
Public Member Functions
BmpImage (kkint32 _height, kkint32 _width, kkint32 _numOfColors)
BmpImage (const KKStr &_fileName, bool &successful)
Constructs a BMP image from the file specified by '_fileName'.
BmpImage (const Raster &raster)
Constructs a BMPImage instance from a Raster image; this is one way to save a Raster image to disk.
~BmpImage ()
void AddPixel (kkuint32 row, kkuint32 col, uchar pixValue)
bool AreThereEdgePixels ()
void Binarize ()
const uchar * BlueRow (kkint32 row) const
Returns the specified Row from the Blue Channel.
void ClearImage ()
bool Color () const
Returns true if a Color image.
void DoubleSize ()
void DownSize ()
void EliminateVerticalLines ()
const KKStr & FileName () const
bool FourBitUncompressed ()
kkuint32 Height () const
uchar ** Image ()
Returns back two dimension matrix of image; if color it will be the green channel.
const uchar * ImageRow (kkint32 row) const
Returns the specified Row from the Green Channel.
void InitializeFields (kkint32 _height, kkint32 _width)
uchar MaxPixVal () const
uchar & Pixel (kkint32 row, kkint32 col)
void Print ()
void ReAllocateForBiggerScreen ()
Used to expand dimensions of image by 6 pixels so as to make sure that no image is along the edge.
const uchar * RedRow (kkint32 row) const
Returns the specified Row from the Red Channel.
void Save (const KKStr &fileName)
void SaveGrayscaleInverted4Bit (const KKStr &_fileName)
Saves image using 4 bit compressed gray-scale where Background = 255 and foreground = 0.
void SaveGrayscaleInverted8Bit (const KKStr &_fileName)
Saves image using compressed gray-scale where Background = 255 and foreground = 0.
void Set16Colors ()
void Set256Colors ()
void SetPaletteEntry (kkint32 palletIndex, const PixelValue &pixValue)
void SetPixelValue (kkint32 row, kkint32 col, kkint32 pixel)
Will set the pixel value of the specified row and col to 'pixel'.
kkuint32 Width () const
Detailed Description
Used to encode and decode BMP Images.
Purpose of this class it to facilitate the loading and saving of BMP Image files. Not all formats are supported, but the compressed version is, which most others don't support. As a result this class will write considerably smaller BMP files than other utilities that I have tried. This results in faster writing images due to less disk-io.
This object was originally designed to work in conjunction with Image Extraction. It requires no other libraries and can read and write BMP files.
When ImageExtraction creates a Bmp file it will provide pixel values between 0 and 7, where 0 is the background and 7 is the foreground. This is a result of the SIPPER 2 and 3 Formats and may change in the future. When saving the BMP file BMPImage will map these values through the palette to 0=255, 1=219, 2=182, 3=146, 4=109, 5=73, 6=36, 7=0 resulting in a white background and a Black foreground.
Definition at line 49 of file BMPImage.h.
Member Typedef Documentation
typedef CodePair* KKB::BmpImage::CodePairPtr
Definition at line 214 of file BMPImage.h.
Constructor & Destructor Documentation
BmpImage::BmpImage (kkint32 _height, kkint32 _width, kkint32 _numOfColors)
Definition at line 687 of file BMPImage.cpp.
References InitializeFields(), and KKB::KKStr::KKStr().
                    :
   
   color (false),
   fileName (),
   red (NULL),
   image (NULL),
   blue (NULL),
   numOfColors (_numOfColors),
   palette (NULL)
{
  InitializeFields (_height, _width);
}
BmpImage::BmpImage (const KKStr & _fileName, bool & successful)
Constructs a BMP image from the file specified by '_fileName'.
Parameters
in _fileName Name of file to load BMP image from.
out successful Returns true if file successful in loading.
Definition at line 449 of file BMPImage.cpp.
References KKB::KKStr::KKStr(), KKB::osFOPEN(), and KKB::KKStr::Str().
Referenced by KKB::ReadImage().
                    :
  color (false),
  fileName (_fileName),
  red (NULL),
  image (NULL),
  blue (NULL),
  numOfColors (16),
  palette (NULL),
  paletteEntries (0)
{
  FILE* inFile = osFOPEN (fileName.Str (), "rb");
  if (!inFile)
  {
    successfull = false;
    return;
  }
  successfull = true;
  size_t x;
  kkint32 y;
  x = fread (&hdr, sizeof (hdr), 1, inFile);
  if (x <= 0)
  {
    successfull = false;
    fclose (inFile);
    return;
  }
  uchar buff[4];
  memcpy (buff, &hdr, sizeof (buff));
  if ((buff[0] == 'B') && (buff[1] == 'M'))
  {
    // We have a Bit Map file.
  }
  else if ((buff[0] == 137) && (buff[1] == 'P') && (buff[2] == 'N') && (buff[3] == 'G'))
  {
    // We are looking at a PNG (Portable Network Graphics) file.
    cerr << std::endl
         << "File[" << _fileName << "] is a PNG formatted file." << std::endl
         << std::endl;
    successfull = false;
    fclose (inFile);
    return;
  }
  else
  {
    cerr << std::endl
         << "File[" << _fileName << "] is of a unknown file format." <<
      std::endl
         << std::endl;
    successfull = false;
    fclose (inFile);
    return;
  }
  x = fread (&bmh, sizeof (bmh), 1, inFile);
  if (x <= 0)
  {
    successfull = false;
    fclose (inFile);
    return;
  }
  if ((bmh.biCompression == BI_RGB) && (bmh.biBitCount == 24))
  {
    numOfColors = 16777216;
    color = true;
    delete palette;
    palette = NULL;
    Load24BitColor (inFile, successfull);
    fclose (inFile);
    return;
  }
  if ((bmh.biCompression == BI_RGB) && (bmh.biBitCount == 8))
  {
    Load8BitColor (inFile, successfull);
    fclose (inFile);
    return;
  }
  else if ((bmh.biCompression == BI_RGB) || (bmh.biCompression == BI_RLE4))
    numOfColors = 16;
  else if (bmh.biBitCount == 1)
    numOfColors = 16;
  else
    numOfColors = 256;
  paletteEntries = BMIcolorArraySize (bmh);
  if (paletteEntries < 0)
  {
    successfull = false;
    fclose (inFile);
    return;
  }
  bool imageIsRevGrayscale = false;
  if (paletteEntries)
  {
    palette = new RGBQUAD[paletteEntries];
    x = fread (palette, sizeof (RGBQUAD), paletteEntries, inFile);
    imageIsRevGrayscale = ReversedGrayscaleImage ();
  }
  else
  {
    numOfColors = 256;
    paletteEntries = 256;
    palette = new RGBQUAD[paletteEntries];
    SetUp256BitPalette (palette);
  }
  // Lets Build Palette Map
  for (x = 0; x < 256; x++)
    paletteMap[x] = 0;
  if (numOfColors == 16)
  {
    for (kkint32 palletIdx = 0; palletIdx < paletteEntries; palletIdx++)
    {
      if (imageIsRevGrayscale)
        y = 255 - palette[palletIdx].rgbGreen;
      else
        y = palette[palletIdx].rgbGreen;
      if (y < 0) y = 0; else if (y > 255) y = 255;
      paletteMap[palletIdx] = y;
    }
  }
  else
  {
    for (kkint32 palletIdx = 0; palletIdx < paletteEntries; palletIdx++)
    {
      if (imageIsRevGrayscale)
        y = 255 - palette[palletIdx].rgbGreen;
      else
        y = palette[palletIdx].rgbGreen;
      if (y < 0) y = 0; else if (y > 255) y = 255;
      paletteMap[palletIdx] = y;
    }
  }
  delete palette;
  paletteEntries = 256;
  palette = new RGBQUAD[paletteEntries];
  SetUp256BitPalette (palette);
  kkint32 row;
  image = new uchar*[bmh.biHeight];
  for (row = 0; row < bmh.biHeight; row++)
  {
    image[row] = new uchar[bmh.biWidth];
    memset (image[row], 0, bmh.biWidth);
  }
  x = fseek (inFile, hdr.bfOffBits, SEEK_SET);
  if (bmh.biBitCount == 1)
  {
    Load1BitColor (inFile, successfull);
  }
  else if (bmh.biBitCount == 4)
  {
    if (bmh.biCompression == BI_RGB)
    {
      Load4BitColor (inFile, successfull);
    }
    else if (bmh.biCompression == BI_RLE4)
    {
      Load4BitColorCompressed (inFile, successfull);
    }
    else
    {
      cerr << "***ERROR*** Invalid Compression Mode[" << bmh.biCompression
           << "] Specified for 4 bit File["
           << fileName << "]."
           << std::endl;
      successfull = false;
      // WaitForEnter ();
    }
  }
  else if (bmh.biBitCount == 8)
  {
    if (bmh.biCompression == BI_RGB)
    {
      Load8BitColor (inFile, successfull);
    }
    else if (bmh.biCompression == BI_RLE8)
    {
      Load8BitColorCompressed (inFile, successfull);
    }
    else
    {
      cerr << "***ERROR*** Invalid Compression Mode[" << bmh.biCompression
           << "] Specified for 8 bit File["
           << fileName << "]."
           << std::endl;
      successfull = false;
    }
  }
  else if (bmh.biBitCount == 16)
  {
    cerr << "***ERROR*** 16 Bit Not Supported. File[" << fileName << "]." <<
      std::endl;
    // WaitForEnter ();
  }
  else if (bmh.biBitCount == 24)
  {
    cerr << "***ERROR*** 24 Bit Not Supported. File[" << fileName << "]." <<
      std::endl;
  }
  else if (bmh.biBitCount == 32)
  {
    cerr << "***ERROR*** 32 Bit Not Supported. File[" << fileName << "]." <<
      std::endl;
    // WaitForEnter ();
  }
  fclose (inFile);
}
BmpImage::BmpImage (const Raster & raster)
Constructs a BMPImage instance from a Raster image; this is one way to save a Raster image to disk.
Definition at line 706 of file BMPImage.cpp.
References KKB::Raster::Blue(), KKB::Raster::Color(), KKB::Raster::Height(), InitializeFields(), KKB::KKStr::operator=(), KKB::Raster::Red(), KKB::Raster::Rows(), and KKB::Raster::Width().
Referenced by KKB::SaveImage(), KKB::SaveImageGrayscaleInverted4Bit(), and KKB::SaveImageGrayscaleInverted8Bit().
                                        :
  color (false),
  red (NULL),
  image (NULL),
  blue (NULL),
  palette (NULL)
{
  numOfColors = 256; // kk 2005-03-10
  color = raster.Color ();
  InitializeFields (raster.Height (), raster.Width ());
  fileName = "";
  kkint32 row;
  kkint32 col;
  uchar** rasterData = raster.Rows ();
  uchar** rasterRed = raster.Red ();
  uchar** rasterBlue = raster.Blue ();
  for (row = 0; row < bmh.biHeight; row++)
  {
    for (col = 0; col < bmh.biWidth; col++)
    {
      image[row][col] = rasterData[row][col];
      if (color)
      {
        red[row][col] = rasterRed [row][col];
        blue[row][col] = rasterBlue[row][col];
      }
    }
  }
}
BmpImage::~BmpImage ()
Definition at line 743 of file BMPImage.cpp.
{
  CleanUpMemory ();
}
Member Function Documentation
void BmpImage::AddPixel (kkuint32 row, kkuint32 col, uchar pixValue)
Definition at line 2630 of file BMPImage.cpp.
{
  image[row][col] = pixValue;
}
bool BmpImage::AreThereEdgePixels ()
Definition at line 2004 of file BMPImage.cpp.
References Height(), and Width().
{
  kkint32 row;
  kkint32 col;
  kkint32 height = Height ();
  kkint32 width = Width ();
  if (height < 6)
    return true;
  if (width < 6)
    return true;
  uchar* row0 = image[0];
  uchar* row1 = image[1];
  uchar* row2 = image[2];
  uchar* rowL0 = image[height - 3];
  uchar* rowL1 = image[height - 2];
  uchar* rowL2 = image[height - 1];
  for (col = 0; col < width; col++)
  {
    if ((row0[col] > 0) ||
         (row1[col] > 0) ||
         (row2[col] > 0) ||
         (rowL0[col] > 0) ||
         (rowL1[col] > 0) ||
         (rowL2[col] > 0)
        )
      return true;
  }
  kkint32 lastCol0 = width - 3;
  kkint32 lastCol1 = width - 2;
  kkint32 lastCol2 = width - 1;
  kkint32 lastRowToCheck = height - 3;
  for (row = 3; row < lastRowToCheck; row++)
  {
    if ((image[row][0] > 0) ||
         (image[row][1] > 0) ||
         (image[row][2] > 0) ||
         (image[row][lastCol0] > 0) ||
         (image[row][lastCol1] > 0) ||
         (image[row][lastCol2] > 0)
        )
      return true;
  }
  return false;
} /* EdgePixels */
void BmpImage::Binarize ()
Definition at line 2189 of file BMPImage.cpp.
{
  kkint32 row;
  kkint32 col;
  for (row = 0; row < bmh.biHeight; row++)
  {
    for (col = 0; col < bmh.biWidth; col++)
    {
      if (image[row][col] < 7)
        image[row][col] = 0;
    }
  }
} /* Binarize */
const uchar * BmpImage::BlueRow (kkint32 row) const
Returns the specified Row from the Blue Channel.
Definition at line 2652 of file BMPImage.cpp.
References Height(), KKB::KKException::KKException(), KKB::KKStr::operator+(), KKB::operator+(), and KKB::StrFromInt32().
Referenced by KKB::Raster::Raster().
{
  if (blue == NULL)
    throw KKException("BmpImage::BlueRow 'blue' channel is set to NULL.");
  if ((row < 0) || (row >= (kkint32)Height ()))
  {
    cerr << std::endl
         << std::endl
         << "BmpImage::BlueRow *** ERROR *** Invalid Row[" << row << "]." <<
      std::endl
         << std::endl;
    //osWaitForEnter ();
    throw KKException("BmpImage::BlueRow row:" + StrFromInt32(row) + " is out of
       range where Height:" + StrFromInt32(row));
  }
  return blue[row];
} /* BlueRow */
void BmpImage::ClearImage ()
Definition at line 2640 of file BMPImage.cpp.
{
    kkint32 row;
    for (row = 0; row < bmh.biHeight; row++)
    {
        memset (image[row], 0, bmh.biWidth);
    }
}
bool KKB::BmpImage::Color () const [inline]
Returns true if a Color image.
Definition at line 118 of file BMPImage.h.
Referenced by KKB::Raster::Raster().
void KKB::BmpImage::DoubleSize ()
void BmpImage::DownSize ()
Definition at line 1917 of file BMPImage.cpp.
{
  kkint32 newCol;
  kkint32 newHeight = bmh.biHeight / 2;
  kkint32 newWidth = bmh.biWidth / 2;
  kkint32 newRow;
  kkint32 oldCol;
  kkint32 oldRow;
  uchar** newImage = new uchar*[newHeight];
  for (newRow = 0; newRow < newHeight; newRow++)
  {
    oldRow = newRow * 2;
    newImage[newRow] = new uchar[newWidth];
   
    for (newCol = 0; newCol < newWidth; newCol++)
    {
      oldCol = newCol * 2;
      newImage[newRow][newCol] = image[oldRow][oldCol];
    }
  }
  for (oldRow = 0; oldRow < bmh.biHeight; oldRow++)
  {
    delete image[oldRow];
    image[oldRow] = NULL;
  }
  delete image;
  image = newImage;
  bmh.biHeight = newHeight;
  bmh.biWidth = newWidth;
} /* DownSize */
void BmpImage::EliminateVerticalLines ()
Definition at line 2063 of file BMPImage.cpp.
{
  kkint32 col = 0;
  kkint32 row = 0;
  kkint32 x;
  bool* potVertLine = new bool[bmh.biWidth];
  bool* pvl = potVertLine;
  for (col = 0; col < bmh.biWidth; col++)
  {
    *pvl = true;
    for (row = 0; ((row < bmh.biHeight) && (*pvl)); row++)
    {
      if (image[row][col] == 7)
        *pvl = false;
    }
    
    pvl++;
  }
  col = 0;
  while (col < bmh.biWidth)
  {
    if (potVertLine[col])
    {
      kkint32 firstCol = col;
      kkint32 lastCol = col;
      if (col < (bmh.biWidth - 1))
      {
        while ((col < bmh.biWidth) && (potVertLine[col]))
        {
          col++;
        }
      }
      if (!potVertLine[col])
      {
        // We terminated loop because there were no more potentialVertLine's not
        // because we ran out of columns.
        lastCol = col - 1;
      }
      // Scan down vertically, and any place that we are not in contact both left and right
      // with other pixels erase from picture,
      bool leftSideIsClear = true;
      bool rightSizeIsClear = true;
      uchar leftPixel = 0;
      uchar rightPixel = 0;
      for (row = 0; row < bmh.biHeight; row++)
      {
        if (firstCol > 0)
        {
          leftPixel = image[row][firstCol - 1];
          if (leftPixel != 0)
             leftSideIsClear = false;
        }
        else
        {
          leftPixel = 0;
        }
        
        if (lastCol < (bmh.biWidth - 1))
        {
          rightPixel = image[row][lastCol + 1];
          if (rightPixel != 0)
             rightSizeIsClear = false;
        }
        if (leftSideIsClear && rightSizeIsClear)
        {
          for (x = firstCol; x <= lastCol; x++)
            image[row][x] = 0;
        }
        else
        {
          for (x = firstCol; x <= lastCol; x++)
            image[row][x] = (leftPixel + rightPixel) / 2;
          // Set up boolean for next loop around.
          leftSideIsClear = true;
          rightSizeIsClear = true;
        }
      }
    }
    col++;
  }
  delete[] potVertLine;
} /* EliminateVerticalLines */
const KKStr& KKB::BmpImage::FileName () const [inline]
Definition at line 121 of file BMPImage.h.
Referenced by KKB::Raster::Raster().
{return fileName;}
bool BmpImage::FourBitUncompressed ()
Definition at line 2709 of file BMPImage.cpp.
{
  return ((bmh.biBitCount == 4) && (bmh.biCompression == BI_RGB));
}
kkuint32 KKB::BmpImage::Height () const [inline]
Definition at line 125 of file BMPImage.h.
Referenced by AreThereEdgePixels(), BlueRow(), KKB::Raster::CreatePaddedRaster(), ImageRow(), KKB::Raster::Raster(), and RedRow().
{return bmh.biHeight;}
uchar** KKB::BmpImage::Image () [inline]
Returns back two dimension matrix of image; if color it will be the green channel.
Definition at line 130 of file BMPImage.h.
const uchar * BmpImage::ImageRow (kkint32 row) const
Returns the specified Row from the Green Channel.
Definition at line 2672 of file BMPImage.cpp.
References Height(), KKB::KKException::KKException(), KKB::KKStr::operator+(), KKB::operator+(), and KKB::StrFromInt32().
Referenced by KKB::Raster::CreatePaddedRaster(), and KKB::Raster::Raster().
{
  if (image == NULL)
    throw KKException("::ImageRow 'image' set to NULL.");
  if ((row < 0) || (row >= (kkint32)Height ()))
  {
    cerr << std::endl
         << std::endl
         << "BmpImage *** ERROR *** Invalid Row[" << row << "]." << std::endl
         << std::endl;
    throw KKException("BmpImage::ImageRow row:" + StrFromInt32(row) + " is out of
       range where Height:" + StrFromInt32(row));
  }
  return image[row];
} /* ImageRow */
void BmpImage::InitializeFields (kkint32 _height, kkint32 _width)
Definition at line 1011 of file BMPImage.cpp.
Referenced by BmpImage().
{
  hdr.bfType = 19778;
  hdr.bfReserved1 = 0;
  hdr.bfReserved2 = 0;
  // hdr.bfOffBits = sizeof (bmh)
  bmh.biSize = sizeof (bmh);
  bmh.biWidth = _width;
  bmh.biHeight = _height;
  bmh.biPlanes = 1;
  paletteEntries = 0;
  AllocateRaster ();
  if (numOfColors <= 16)
  {
    delete palette; palette = NULL;
    bmh.biBitCount = 4;
    paletteEntries = 16;
    bmh.biCompression = BI_RLE4; // BI_RGB;
    palette = new RGBQUAD[paletteEntries];
    SetUp16BitPallet (palette);
  }
  else
  {
    delete palette; palette = NULL;
    bmh.biBitCount = 8;
    paletteEntries = 256;
    bmh.biCompression = BI_RLE8; // BI_RGB;
    palette = new RGBQUAD[paletteEntries];
    SetUp256BitPalette (palette);
  }
  bmh.biSizeImage = 0;
  bmh.biXPelsPerMeter = 2835;
  bmh.biYPelsPerMeter = 2835;
  bmh.biClrUsed = 0;
  bmh.biClrImportant = 0;
  // BITMAPFILEHEADER hdr;
  // BITMAPINFOHEADER bmh;
  hdr.bfOffBits = sizeof (bmh) + sizeof (RGBQUAD) * paletteEntries;
} /* InitializeFields */
uchar KKB::BmpImage::MaxPixVal () const [inline]
Definition at line 138 of file BMPImage.h.
{return uchar (maxPixVal);}
uchar & BmpImage::Pixel (kkint32 row, kkint32 col)
Definition at line 1958 of file BMPImage.cpp.
{
  return image[row][col];
}
void BmpImage::Print ()
Definition at line 2168 of file BMPImage.cpp.
References KKB::operator<<().
{
  kkint32 x;
  kkint32 y;
  for (x = 0; x < bmh.biHeight; x++)
  {
    for (y = 0; y < Min ((long)bmh.biWidth, 76L); y++)
    {
      if (image[x][y])
        cout << " ";
      else
        cout << "*";
    }
    cout << std::endl;
  }
} /* Print */
void BmpImage::ReAllocateForBiggerScreen ()
Used to expand dimensions of image by 6 pixels so as to make sure that no image is along the edge.
Definition at line 1318 of file BMPImage.cpp.
{
  kkint32 oldRow;
  kkint32 newRow;
  kkint32 newHeight = bmh.biHeight + 6;
  kkint32 newWidth = bmh.biWidth + 6;
  uchar** newImage = new uchar*[newHeight];
  uchar** newRed = NULL;
  uchar** newBlue = NULL;
  if (color)
  {
     newRed = new uchar*[newHeight];
     newBlue = new uchar*[newHeight];
  }
  for (newRow = 0; newRow < newHeight; newRow++)
  {
    newImage[newRow] = new uchar[newWidth];
    memset (newImage[newRow], 0, newWidth);
    if (color)
    {
      newRed [newRow] = new uchar[newWidth];
      newBlue[newRow] = new uchar[newWidth];
      memset (newRed [newRow], 0, newWidth);
      memset (newBlue [newRow], 0, newWidth);
    }
  }
  newRow = 3;
  for (oldRow = 0; oldRow < bmh.biHeight; oldRow++)
  {
    memcpy ((newImage[newRow] + 3), image[oldRow], bmh.biWidth);
    if (color)
    {
      memcpy ((newRed[newRow] + 3), red [oldRow], bmh.biWidth);
      memcpy ((newBlue[newRow] + 3), blue[oldRow], bmh.biWidth);
    }
    newRow++;
  }
  for (oldRow = 0; oldRow < bmh.biHeight; oldRow++)
  {
    delete image[oldRow];
    image[oldRow] = NULL;
    if (color)
    {
      delete red [oldRow]; red [oldRow] = NULL;
      delete blue[oldRow]; blue[oldRow] = NULL;
    }
  }
  delete image;
  delete red;
  delete blue;
  image = newImage;
  if (color)
  {
    red = newRed; newRed = NULL;
    blue = newBlue; newBlue = NULL;
  }
  bmh.biHeight = newHeight;
  bmh.biWidth = newWidth;
} /* RealocateForBiggerScreen */
const uchar * BmpImage::RedRow (kkint32 row) const
Returns the specified Row from the Red Channel.
Definition at line 2690 of file BMPImage.cpp.
References Height(), KKB::KKException::KKException(), KKB::KKStr::operator+(), KKB::operator+(), and KKB::StrFromInt32().
Referenced by KKB::Raster::Raster().
{
  if (blue == NULL)
    throw KKException("BmpImage::RedRow 'red' channel is set to NULL.");
  if ((row < 0) || (row >= (kkint32)Height()))
  {
    cerr << std::endl
      << std::endl
      << "BmpImage::RedRow *** ERROR *** Invalid Row[" << row << "]." <<
      std::endl
      << std::endl;
    //osWaitForEnter ();
    throw KKException("BmpImage::BlueRed row:" + StrFromInt32(row) + " is out of
       range where Height:" + StrFromInt32(row));
  }
  return red[row];
} /* RedRow */
void BmpImage::Save (const KKStr & fileName)
Definition at line 2331 of file BMPImage.cpp.
References KKB::KKStr::Concat(), KKB::KKException::KKException(), KKB::KKStr::operator+(), KKB::operator+(), KKB::KKStr::operator=(), KKB::osFOPEN(), and KKB::KKStr::Str().
Referenced by KKB::SaveImage().
{
  fileName = _fileName;
  FILE* outFile = osFOPEN (fileName.Str (), "wb");
  if (!outFile)
  {
    KKStr errMsg = "BmpImage::Save, Error opening BMP File[" + fileName + "].";
    cerr << errMsg << std::endl;
    throw KKException (errMsg);
  }
  if (color)
  {
    SaveColor (outFile);
  }
  else
  {
    SaveGrayScale (outFile);
  }
  fclose (outFile);
} /* Save */
void BmpImage::SaveGrayscaleInverted4Bit (const KKStr & _fileName)
Saves image using 4 bit compressed gray-scale where Background = 255 and foreground = 0.
If image is color will convert to gray-scale 1st. Palette will be set to 0 = 255, 1 = 238, 2 = 221, 3 = 204... 255 = 0.
Definition at line 2207 of file BMPImage.cpp.
References KKB::BmpImage::CodedPixels::AddPixel(), KKB::KKStr::Concat(), KKB::BmpImage::CodedPixels::CreatePixelDataStructure4Bit(), KKB::BmpImage::CodedPixels::EOL(), KKB::KKException::KKException(), KKB::KKStr::operator+(), KKB::operator+(), KKB::KKStr::operator=(), KKB::osFOPEN(), and KKB::KKStr::Str().
Referenced by KKB::SaveImageGrayscaleInverted4Bit().
{
  fileName = _fileName;
  FILE* outFile = osFOPEN (fileName.Str (), "wb");
  if (!outFile)
  {
    KKStr errMsg = "BmpImage::SaveGrayscaleInverted4Bit, Error opening BMP File[" + fileName + "].";
    cerr << errMsg << std::endl;
    throw KKException (errMsg);
  }
  kkint32 x = 0;
  kkint32 y = 0;
  CodedPixels pixelData (bmh.biHeight, bmh.biWidth);
  for (x = (kkint32)bmh.biHeight - 1; x >= 0; x--)
  {
    for (y = 0; y < bmh.biWidth; y++)
    {
      if (color)
      {
        kkint32 gsVal = (kkint32)((float)(0.5f + red[x][y]) * 0.30f + (float)(image[x][y]) *
       0.59f + (float)(blue[x][y]) * 0.11f);
        pixelData.AddPixel ((uchar)(gsVal >> 4));
      }
      else
      {
        pixelData.AddPixel (image[x][y] >> 4);
      }
    }
    pixelData.EOL ();
  }
  kkint32 imageBuffLen = 0;
  uchar* imageBuff = NULL;
  numOfColors = 16;
  imageBuff = pixelData.CreatePixelDataStructure4Bit (imageBuffLen);
  bmh.biBitCount = 4;
  bmh.biCompression = BI_RLE4; // BI_RGB;
  SetUp4BitPallet ();
  bmh.biSizeImage = imageBuffLen;
  bmh.biClrUsed = numOfColors;
  bmh.biClrImportant = numOfColors;
  hdr.bfSize = 14 + 40 + paletteEntries * 4 + bmh.biSizeImage;
  hdr.bfOffBits = 40 + 14 + paletteEntries * 4;
  x = (kkint32)fwrite (&hdr, sizeof (hdr), 1, outFile);
  x = (kkint32)fwrite (&bmh, sizeof (bmh), 1, outFile);
  x = (kkint32)fwrite (palette, sizeof (RGBQUAD), paletteEntries, outFile);
  x = (kkint32)fwrite (imageBuff, 1, imageBuffLen, outFile);
  delete imageBuff;
  fclose (outFile);
} /* SaveGrayscaleInverted4Bit */
void BmpImage::SaveGrayscaleInverted8Bit (const KKStr & _fileName)
Saves image using compressed gray-scale where Background = 255 and foreground = 0.
If image is color will convert to gray-scale 1st. Palette will be set to 0 = 255, 1 = 254, 2 = 253, ... 255 = 0.
Definition at line 2268 of file BMPImage.cpp.
References KKB::BmpImage::CodedPixels::AddPixel(), KKB::KKStr::Concat(), KKB::BmpImage::CodedPixels::CreatePixelDataStructure8Bit(), KKB::BmpImage::CodedPixels::EOL(), KKB::KKException::KKException(), KKB::KKStr::operator+(), KKB::operator+(), KKB::KKStr::operator=(), KKB::osFOPEN(), and KKB::KKStr::Str().
Referenced by KKB::SaveImageGrayscaleInverted8Bit().
{
  fileName = _fileName;
  FILE* outFile = osFOPEN (fileName.Str (), "wb");
  if (!outFile)
  {
    KKStr errMsg = "BmpImage::SaveGrayscaleInverted8Bit, Error opening BMP File[" + fileName + "].";
    cerr << errMsg << std::endl;
    throw KKException (errMsg);
  }
  kkint32 x = 0;
  kkint32 y = 0;
  CodedPixels pixelData (bmh.biHeight, bmh.biWidth);
  for (x = (kkint32)bmh.biHeight - 1; x >= 0; x--)
  {
    for (y = 0; y < bmh.biWidth; y++)
    {
      if (color)
      {
        kkint32 gsVal = (kkint32)((float)(0.5f + red[x][y]) * 0.30f + (float)(image[x][y]) *
       0.59f + (float)(blue[x][y]) * 0.11f);
        pixelData.AddPixel ((uchar)(gsVal));
      }
      else
      {
        pixelData.AddPixel (image[x][y]);
      }
    }
    pixelData.EOL ();
  }
  kkint32 imageBuffLen = 0;
  uchar* imageBuff = NULL;
  numOfColors = 256;
  imageBuff = pixelData.CreatePixelDataStructure8Bit (imageBuffLen);
  bmh.biBitCount = 8;
  bmh.biCompression = BI_RLE8; // BI_RGB;
  SetUp8BitPallet ();
  bmh.biSizeImage = imageBuffLen;
  bmh.biClrUsed = numOfColors;
  bmh.biClrImportant = numOfColors;
  hdr.bfSize = 14 + 40 + paletteEntries * 4 + bmh.biSizeImage;
  hdr.bfOffBits = 40 + 14 + paletteEntries * 4;
  x = (kkint32)fwrite (&hdr, sizeof (hdr), 1, outFile);
  x = (kkint32)fwrite (&bmh, sizeof (bmh), 1, outFile);
  x = (kkint32)fwrite (palette, sizeof (RGBQUAD), paletteEntries, outFile);
  x = (kkint32)fwrite (imageBuff, 1, imageBuffLen, outFile);
  delete imageBuff;
  fclose (outFile);
} /* SaveGrayscaleInverted8Bit */
void BmpImage::Set16Colors ()
Definition at line 1194 of file BMPImage.cpp.
{
  if (palette)
    delete palette;
  numOfColors = 16;
  paletteEntries = 16;
  palette = new RGBQUAD[paletteEntries];
  SetUp16BitPallet (palette);
}
void BmpImage::Set256Colors ()
Definition at line 1208 of file BMPImage.cpp.
{
  if (palette)
    delete palette;
  numOfColors = 256;
  paletteEntries = 256;
  palette = new RGBQUAD[paletteEntries];
  SetUp256BitPalette (palette);
}
void BmpImage::SetPaletteEntry (kkint32 palletIndex, const PixelValue & pixValue)
Definition at line 935 of file BMPImage.cpp.
{
  if ((palletIndex < 0) || (palletIndex > 255))
  {
    // Invalid Entry specified
    cerr << std::endl << std::endl << std::endl
         << "BmpImage::SetPaletteEntry Invalid PalletIndex[" << palletIndex << "]" <<
      std::endl
         << std::endl;
    return;
  }
  if (!palette)
  {
    cerr << std::endl << std::endl << std::endl
         << "BmpImage::SetPaletteEntry The palette is not defined!" <<
      std::endl
         << std::endl;
    return;
  }
  palette[palletIndex].rgbBlue = pixValue.b;
  palette[palletIndex].rgbGreen = pixValue.g;
  palette[palletIndex].rgbRed = pixValue.r;
} /* SetPaletteEntry */
void BmpImage::SetPixelValue (kkint32 row, kkint32 col, kkint32 pixel)
Will set the pixel value of the specified row and col to 'pixel'.
Definition at line 1967 of file BMPImage.cpp.
{
  if (pixel < 0)
  {
    cerr << "BmpImage::SetPixelValue ***ERROR*** pixel[" << pixel << "] out of range. Needs to be in
       range of 0..255." << std::endl;
    pixel = 0;
  }
  else if (pixel > 255)
  {
    cerr << "BmpImage::SetPixelValue ***ERROR*** pixel[" << pixel << "] out of range. Needs to be in
       range of 0..255." << std::endl;
    pixel = 255;
  }
  if ((row < 0) || (row >= bmh.biHeight))
  {
    cerr << "BmpImage::SetPixelValue *** Error ***, Row[" << row
         << "] out of range[0-" << bmh.biHeight << "]."
         << std::endl;
    return;
  }
  if ((col < 0) || (col >= bmh.biWidth))
  {
    cerr << "BmpImage::SetPixelValue *** Error ***, Col[" << col
         << "] out of range[0-" << bmh.biWidth << "]."
         << std::endl;
    return;
  }
  image[row][col] = (uchar)pixel;
} /* SetPixelValue */
kkuint32 KKB::BmpImage::Width () const [inline]
Definition at line 140 of file BMPImage.h.
Referenced by AreThereEdgePixels(), KKB::Raster::CreatePaddedRaster(), and KKB::Raster::Raster().
{return bmh.biWidth;}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/BMPImage.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/BMPImage.cpp