KKMLL::ClassStatisticList::ClassStatisticSortComparrison Class Reference
Public Member Functions
ClassStatisticSortComparrison ()
bool operator() (ClassStatisticPtr p1, ClassStatisticPtr p2)
Detailed Description
Definition at line 125 of file ClassStatistic.cpp.
Constructor & Destructor Documentation
KKMLL::ClassStatisticList::ClassStatisticSortComparrison::ClassStatisticSortComparrison () [inline]
Definition at line 128 of file ClassStatistic.cpp.
{}
Member Function Documentation
bool KKMLL::ClassStatisticList::ClassStatisticSortComparrison::operator() (ClassStatisticPtr p1, ClassStatisticPtr p2) [inline]
Definition at line 130 of file ClassStatistic.cpp.
References KKMLL::ClassStatistic::MLClass(), KKB::KKStr::operator<(), and KKMLL::MLClass::UpperName().
   {
     return (p1->MLClass ()->UpperName () < p2->MLClass ()->
      UpperName ());
   }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ClassStatistic.cpp