KKMLL::ImageFeaturesDataIndexed Class Reference
#include <ImageFeaturesDataIndexed.h>
Public Member Functions
ImageFeaturesDataIndexed ()
ImageFeaturesDataIndexed (const FeatureVectorList &examples)
FeatureVectorPtr GetEqual (FeatureVectorPtr example)
void RBInsert (FeatureVectorPtr example)
Additional Inherited Members
Detailed Description
Definition at line 31 of file ImageFeaturesDataIndexed.h.
Constructor & Destructor Documentation
ImageFeaturesDataIndexed::ImageFeaturesDataIndexed ()
Definition at line 31 of file ImageFeaturesDataIndexed.cpp.
References ImageFeaturesDataIndexed().
Referenced by KKMLL::DuplicateImages::DuplicateImages(), and ImageFeaturesDataIndexed().
                                                   :
   RBTree<ImageDataTreeEntry, ExtractFeatureData, ImageFeaturesNodeKey>
       (extractFeatureData, true)
{
}
ImageFeaturesDataIndexed::ImageFeaturesDataIndexed (const FeatureVectorList & examples)
Definition at line 38 of file ImageFeaturesDataIndexed.cpp.
References ImageFeaturesDataIndexed().
Referenced by ImageFeaturesDataIndexed().
                                                                                     :
   RBTree<ImageDataTreeEntry, ExtractFeatureData, ImageFeaturesNodeKey>
       (extractFeatureData, true)
{
  FeatureVectorPtr example = NULL;
  for (auto idx: examples)
  {
    example = idx;
    RBInsert (example);
  }
}
Member Function Documentation
FeatureVectorPtr ImageFeaturesDataIndexed::GetEqual (FeatureVectorPtr example)
Definition at line 62 of file ImageFeaturesDataIndexed.cpp.
References KKMLL::ImageDataTreeEntry::Example(), and KKMLL::ImageDataTreeEntry::ImageDataTreeEntry().
Referenced by KKMLL::DuplicateImages::AddSingleExample(), and KKMLL::DuplicateImages::ExampleInDetector().
{
  ImageDataTreeEntryPtr entry = new ImageDataTreeEntry (example);
  ImageDataTreeEntryPtr newEntry =
      RBTree<ImageDataTreeEntry, ExtractFeatureData, ImageFeaturesNodeKey>::GetEqual
       (entry->NodeKey ());
  FeatureVectorPtr exampleFound = NULL;
  if (newEntry)
    exampleFound = newEntry->Example ();
  delete entry; entry = NULL;
                                                                                                          
  return exampleFound;
}
void ImageFeaturesDataIndexed::RBInsert (FeatureVectorPtr example)
Definition at line 53 of file ImageFeaturesDataIndexed.cpp.
Referenced by KKMLL::DuplicateImages::AddSingleExample().
{
  RBTree<ImageDataTreeEntry, ExtractFeatureData, ImageFeaturesNodeKey>::RBInsert
       (new ImageDataTreeEntry (example));
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ImageFeaturesDataIndexed.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ImageFeaturesDataIndexed.cpp