KKMLL::GrayScaleImagesFVList::iterator Class Reference
#include <GrayScaleImagesFV.h>
Public Member Functions
iterator ()
iterator (const iterator &idx)
iterator (const FeatureVectorList::iterator &idx)
bool operator!= (const iterator &right) const
GrayScaleImagesFVPtr operator* ()
iterator & operator++ (int x)
iterator & operator= (const iterator &right)
bool operator== (const iterator &right) const
Detailed Description
Definition at line 395 of file GrayScaleImagesFV.h.
Constructor & Destructor Documentation
KKMLL::GrayScaleImagesFVList::iterator::iterator () [inline]
Definition at line 401 of file GrayScaleImagesFV.h.
References iterator().
Referenced by iterator().
                 :
          idx ()
      {
      }
KKMLL::GrayScaleImagesFVList::iterator::iterator (const iterator & idx) [inline]
Definition at line 406 of file GrayScaleImagesFV.h.
References iterator().
Referenced by iterator().
                                     :
          idx (idx.idx)
      {
      }
KKMLL::GrayScaleImagesFVList::iterator::iterator (const FeatureVectorList::iterator & idx) [inline]
Definition at line 412 of file GrayScaleImagesFV.h.
References iterator().
Referenced by iterator(), and KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
                                                      :
          idx (idx)
      {
      }
Member Function Documentation
bool KKMLL::GrayScaleImagesFVList::iterator::operator!= (const iterator & right) const [inline]
Definition at line 429 of file GrayScaleImagesFV.h.
      {
        return idx != right.idx;
      }
GrayScaleImagesFVPtr KKMLL::GrayScaleImagesFVList::iterator::operator* () [inline]
Definition at line 418 of file GrayScaleImagesFV.h.
Referenced by KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
      {
        return (GrayScaleImagesFVPtr)*idx;
      }
iterator& KKMLL::GrayScaleImagesFVList::iterator::operator++ (int x) [inline]
Definition at line 439 of file GrayScaleImagesFV.h.
Referenced by KKMLL::GrayScaleImagesFVList::RecalcFeatureValuesFromImagesInDirTree().
      {
        idx++;
        return *this;
      }
iterator& KKMLL::GrayScaleImagesFVList::iterator::operator= (const iterator & right) [inline]
Definition at line 423 of file GrayScaleImagesFV.h.
      {
        idx = right.idx;
        return *this;
      }
bool KKMLL::GrayScaleImagesFVList::iterator::operator== (const iterator & right) const [inline]
Definition at line 434 of file GrayScaleImagesFV.h.
      {
        return idx == right.idx;
      }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/GrayScaleImagesFV.h