KKMLL::NormalizationParms Class Reference
Normalization Parameters; calculation and implementation.
#include <NormalizationParms.h>
Public Types
typedef NormalizationParms * NormalizationParmsPtr
Public Member Functions
NormalizationParms ()
NormalizationParms (bool _normalizeNominalFeatures, FeatureVectorList &_examples, RunLog &_log)
NormalizationParms (const ModelParam &_param, FeatureVectorList &_examples, RunLog &_log)
NormalizationParms (TrainingConfiguration2Ptr _config, FeatureVectorList &_examples, RunLog &_log)
~NormalizationParms ()
FileDescPtr FileDesc () const
double Mean (kkint32 i, RunLog &log)
const double * Mean () const
kkint32 MemoryConsumedEstimated () const
void NormalizeAExample (FeatureVectorPtr example)
void NormalizeExamples (FeatureVectorListPtr examples, RunLog &log)
bool NormalizeNominalFeatures () const
float NumOfExamples () const
kkint32 NumOfFeatures () const
void ReadXML (XmlStream &s, XmlTagPtr tag, VolConstBool &cancelFlag, RunLog &log)
double Sigma (kkint32 i, RunLog &log)
const double * Sigma () const
FeatureVectorPtr ToNormalized (FeatureVectorPtr example) const
void WriteToFile (const KKStr &_fileName, bool &_successfull, RunLog &_log) const
void WriteXML (const KKStr &varName, std::ostream &o) const
Static Public Member Functions
static NormalizationParmsPtr ReadFromFile (const KKStr &fileName, RunLog &log)
Detailed Description
Normalization Parameters; calculation and implementation.
Normalization parameters will be calculated for all features but when individual examples are normalized, only the ones specified by _featuresToNormalize' will be normalized.
Definition at line 56 of file NormalizationParms.h.
Member Typedef Documentation
typedef NormalizationParms* KKMLL::NormalizationParms::NormalizationParmsPtr
Definition at line 59 of file NormalizationParms.h.
Constructor & Destructor Documentation
NormalizationParms::NormalizationParms ()
Definition at line 27 of file NormalizationParms.cpp.
References KKB::KKStr::KKStr().
                                       :
  fileDesc (NULL),
  fileName (),
  mean (NULL),
  normalizeFeature (NULL),
  normalizeNominalFeatures (false),
  numOfFeatures (0),
  numOfExamples (0),
  sigma (NULL)
{
} /* NormalizationParms */
NormalizationParms::NormalizationParms (bool _normalizeNominalFeatures, FeatureVectorList & _examples, RunLog & _log)
Definition at line 41 of file NormalizationParms.cpp.
References KKMLL::FileDesc::CreateAttributeTypeTable(), KKMLL::FeatureVectorList::FileDesc(), KKB::KKStr::KKStr(), and KKMLL::FeatureVectorList::NumOfFeatures().
                                        :
  fileDesc (NULL),
  fileName (),
  mean (NULL),
  normalizeFeature (NULL),
  normalizeNominalFeatures (_normalizeNominalFeatures),
  numOfFeatures (0),
  numOfExamples (0),
  sigma (NULL)
{
  _log.Level (20) << "FeatureNormalization - Creating instance from[" << _examples.
      FileName () << "]." << endl;
  fileDesc = _examples.FileDesc ();
  attriuteTypes = fileDesc->CreateAttributeTypeTable ();
  numOfFeatures = _examples.NumOfFeatures ();
  DeriveNormalizationParameters (_examples);
} /* NormalizationParms */
NormalizationParms::NormalizationParms (const ModelParam & _param, FeatureVectorList & _examples, RunLog & _log)
Definition at line 66 of file NormalizationParms.cpp.
References KKMLL::FileDesc::CreateAttributeTypeTable(), KKMLL::FeatureVectorList::FileDesc(), KKB::KKStr::KKStr(), KKMLL::ModelParam::NormalizeNominalFeatures(), and KKMLL::FeatureVectorList::NumOfFeatures().
Referenced by KKMLL::Model::TrainModel().
                                        :
  fileDesc (NULL),
  fileName (),
  mean (NULL),
  normalizeFeature (NULL),
  normalizeNominalFeatures (false),
  numOfFeatures (0),
  numOfExamples (0),
  sigma (NULL)
{
  _log.Level (20) << "FeatureNormalization - Creating instance from[" << _examples.
      FileName () << "]." << endl;
  fileDesc = _examples.FileDesc ();
  numOfFeatures = _examples.NumOfFeatures ();
  attriuteTypes = fileDesc->CreateAttributeTypeTable ();
  normalizeNominalFeatures = _param.NormalizeNominalFeatures ();
  DeriveNormalizationParameters (_examples);
}
NormalizationParms::NormalizationParms (TrainingConfiguration2Ptr _config, FeatureVectorList & _examples, RunLog & _log)
Definition at line 91 of file NormalizationParms.cpp.
References KKMLL::FileDesc::CreateAttributeTypeTable(), KKMLL::TrainingConfiguration2::FileDesc(), KKB::KKStr::KKStr(), KKMLL::TrainingConfiguration2::NormalizeNominalFeatures(), and KKMLL::FeatureVectorList::NumOfFeatures().
                                        :
  fileDesc (NULL),
  fileName (),
  mean (NULL),
  normalizeFeature (NULL),
  normalizeNominalFeatures (false),
  numOfFeatures (0),
  numOfExamples (0),
  sigma (NULL)
{
  _log.Level (20) << "FeatureNormalization - Creating instance from[" << _examples.
      FileName () << "]." << endl;
  fileDesc = _config->FileDesc ();
  attriuteTypes = fileDesc->CreateAttributeTypeTable ();
  normalizeNominalFeatures = _config->NormalizeNominalFeatures ();
  numOfFeatures = _examples.NumOfFeatures ();
  DeriveNormalizationParameters (_examples);
} /* NormalizationParms */
NormalizationParms::~NormalizationParms ()
Definition at line 120 of file NormalizationParms.cpp.
{
  delete [] mean; mean = NULL;
  delete [] sigma; sigma = NULL;
  delete [] normalizeFeature; normalizeFeature = NULL;
}
Member Function Documentation
FileDescPtr KKMLL::NormalizationParms::FileDesc () const [inline]
Definition at line 82 of file NormalizationParms.h.
{return fileDesc;}
double NormalizationParms::Mean (kkint32 i, RunLog & log)
Definition at line 378 of file NormalizationParms.cpp.
{
  if ((i < 0) || (i > numOfFeatures))
  {
    log.Level (-1) << "NormalizationParms::Mean ***ERROR*** Feature Number[" << i << "] out of
       bounds." << endl;
    return -99999.99;
  }
  else
  {
    return mean[i];
  }
} /* Mean */
const double* KKMLL::NormalizationParms::Mean () const [inline]
Definition at line 126 of file NormalizationParms.h.
{return mean;}
kkint32 NormalizationParms::MemoryConsumedEstimated () const
Definition at line 128 of file NormalizationParms.cpp.
Referenced by KKMLL::Model::MemoryConsumedEstimated().
{
  kkint32 memoryConsumedEstimated = sizeof (NormalizationParms)
    + attriuteTypes.size () * sizeof (AttributeType)
    + fileName.MemoryConsumedEstimated ()
    + numOfFeatures * (sizeof (bool) + sizeof (double) + sizeof (double)); // mean + sigma
  return memoryConsumedEstimated;
}
void NormalizationParms::NormalizeAExample (FeatureVectorPtr example)
Definition at line 439 of file NormalizationParms.cpp.
References KKMLL::FeatureVector::FeatureDataAlter().
{
  float* featureData = example->FeatureDataAlter ();
  for (kkint32 i = 0; i < numOfFeatures; i++)
  {
    if (normalizeFeature[i])
    {
      double normValue = 0.0;
      if (sigma[i] != 0.0)
        normValue = ((double)featureData[i] - mean[i]) / sigma[i];
      featureData[i] = (float)normValue;
    }
  }
} /* NormalizeAExample */
void NormalizationParms::NormalizeExamples (FeatureVectorListPtr examples, RunLog & log)
Definition at line 457 of file NormalizationParms.cpp.
References KKMLL::FeatureVectorList::NumOfFeatures(), and KKB::osWaitForEnter().
Referenced by KKMLL::Model::TrainModel().
{
  if (numOfFeatures != examples->NumOfFeatures ())
  {
    log.Level (-1) << "NormalizationParms::NoralizeImage **** ERROR **** Mismatched Feature
       Count." << endl
                   << " NormalizationParms [" << numOfFeatures << "]" <<
      endl
                   << " ImageFeatiresList [" << examples->
      NumOfFeatures () << "]." << endl
                   << endl;
    osWaitForEnter ();
    exit (-1);
    return;
  }
  FeatureVectorList::iterator idx;
  for (idx = examples->begin (); idx != examples->end (); ++idx)
    NormalizeAExample (*idx);
  return;
} /* NoralizeImage */
bool KKMLL::NormalizationParms::NormalizeNominalFeatures () const [inline]
Definition at line 90 of file NormalizationParms.h.
{return normalizeNominalFeatures;}
float KKMLL::NormalizationParms::NumOfExamples () const [inline]
Definition at line 96 of file NormalizationParms.h.
{return numOfExamples;}
kkint32 KKMLL::NormalizationParms::NumOfFeatures () const [inline]
Definition at line 94 of file NormalizationParms.h.
{return numOfFeatures;}
NormalizationParmsPtr NormalizationParms::ReadFromFile (const KKStr & fileName, RunLog & log) [static]
Definition at line 255 of file NormalizationParms.cpp.
References KKB::XmlStream::GetNextToken(), and KKB::XmlStream::XmlStream().
{
  NormalizationParmsPtr n = NULL;
  XmlStreamPtr stream = new XmlStream (fileName, log);
  bool cancelFlag = false;
  XmlTokenPtr t = stream->GetNextToken (cancelFlag, log);
  while (t && (!n))
  {
    if (typeid (*t) != typeid (XmlElementNormalizationParms))
      n = dynamic_cast<XmlElementNormalizationParmsPtr> (t)->Value ();
    delete t;
    t = stream->GetNextToken (cancelFlag, log);
  }
  delete t; t = NULL;
  delete stream; stream = NULL;
  return n;
}
void NormalizationParms::ReadXML (XmlStream & s, XmlTagPtr tag, VolConstBool & cancelFlag, RunLog & log)
Definition at line 302 of file NormalizationParms.cpp.
References KKB::KKStr::Concat(), KKMLL::FileDesc::CreateAttributeTypeTable(), KKB::KKStr::EqualIgnoreCase(), KKB::XmlStream::GetNextToken(), KKB::XmlElement::SectionName(), KKB::XmlElement::ToBool(), KKB::XmlElement::ToFloat(), KKB::XmlElement::ToInt32(), KKB::XmlToken::tokElement, KKB::XmlToken::TokenType(), KKMLL::XmlElementFileDesc::Value(), and KKB::XmlElement::VarName().
{
  XmlTokenPtr t = s.GetNextToken (cancelFlag, log);
  while (t && (!cancelFlag))
  {
    if (t->TokenType () == XmlToken::TokenTypes::tokElement)
    {
      XmlElementPtr e = dynamic_cast<XmlElementPtr> (t);
      const KKStr& className = e->SectionName ();
      const KKStr& varName = e->VarName ();
      if (varName.EqualIgnoreCase ("NumOfFeatures"))
        numOfFeatures = e->ToInt32 ();
      else if (varName.EqualIgnoreCase ("NumOfExamples"))
        numOfExamples = e->ToFloat ();
      else if (varName.EqualIgnoreCase ("NormalizeNominalFeatures"))
        normalizeNominalFeatures = e->ToBool ();
      else if (varName.EqualIgnoreCase ("FileDesc"))
      {
        XmlElementFileDescPtr fd = dynamic_cast<
      XmlElementFileDescPtr>(e);
        fileDesc = fd->Value ();
      }
      else if (varName.EqualIgnoreCase ("Mean"))
      {
        XmlElementArrayDoublePtr m = dynamic_cast<
      XmlElementArrayDoublePtr>(e);
        if (m->Count () == numOfFeatures)
        {
          delete mean;
          mean = m->TakeOwnership ();
        }
        else
        {
          log.Level (-1) << endl
            << "XmlElementNormalizationParms ***ERROR*** mean->Count[" << m->
      Count () << "] does not agree with NumOfFeatures[" << numOfFeatures << "]." <<
      endl
            << endl;
        }
      }
      else if (varName.EqualIgnoreCase ("Sigma"))
      {
        XmlElementArrayDoublePtr s = dynamic_cast<
      XmlElementArrayDoublePtr>(e);
        if (s->Count () == numOfFeatures)
        {
          delete sigma;
          sigma = s->TakeOwnership ();
        }
        else
        {
          log.Level (-1) << endl
            << "XmlElementNormalizationParms ***ERROR*** sigma->Count[" << s->
      Count () << "] does not agree with NumOfFeatures[" << numOfFeatures << "]." <<
      endl
            << endl;
        }
      }
    }
    delete t;
    t = s.GetNextToken (cancelFlag, log);
  }
  delete t;
  t = NULL;
  if (fileDesc)
  {
    attriuteTypes = fileDesc->CreateAttributeTypeTable ();
    ConstructNormalizeFeatureVector ();
  }
} /* ReadXML */
double NormalizationParms::Sigma (kkint32 i, RunLog & log)
Definition at line 394 of file NormalizationParms.cpp.
{
  if ((i < 0) || (i > numOfFeatures))
  {
    log.Level (-1) << "NormalizationParms::Mean ***ERROR*** Feature Number[" << i << "] out of
       bounds." << endl;
    return (float)-99999.99;
  }
  else
  {
    return sigma[i];
  }
} /* Sigma */
const double* KKMLL::NormalizationParms::Sigma () const [inline]
Definition at line 127 of file NormalizationParms.h.
{return sigma;}
FeatureVectorPtr NormalizationParms::ToNormalized (FeatureVectorPtr example) const
Definition at line 483 of file NormalizationParms.cpp.
References KKMLL::FeatureVector::FeatureDataAlter(), and KKMLL::FeatureVector::FeatureVector().
Referenced by KKMLL::ModelOldSVM::PrepExampleForPrediction(), and KKMLL::Model::PrepExampleForPrediction().
{
  FeatureVectorPtr result = new FeatureVector (*example);
  float* featureData = result->FeatureDataAlter ();
  for (kkint32 i = 0; i < numOfFeatures; ++i)
  {
    if (normalizeFeature[i])
    {
      double normValue = 0.0;
      if (sigma[i] != 0.0)
        normValue = ((double)featureData[i] - mean[i]) / sigma[i];
      featureData[i] = (float)normValue;
    }
  }
  return result;
} /* ToNormalized */
void NormalizationParms::WriteToFile (const KKStr & _fileName, bool & _successfull, RunLog & _log) const
Definition at line 236 of file NormalizationParms.cpp.
References KKB::KKStr::operator=().
{
  _log.Level (20) << "NormalizationParms::WriteToFile FileName[" << _fileName << "]." <<
      endl;
  fileName = _fileName;
  _successfull = true;
  ofstream outFile (fileName.Str ());
  if (!outFile.is_open ())
  {
    _log.Level (-1) << endl << "NormalizationParms::WriteToFile ***EROR*** writing to file["<<
      _fileName << "]." << endl << endl;
    _successfull = false;
    return;
  }
  WriteXML ("NormalizationParms", outFile);
  outFile.close ();
  return;
} /* Save */
void NormalizationParms::WriteXML (const KKStr & varName, std::ostream & o) const
Definition at line 277 of file NormalizationParms.cpp.
References KKB::XmlTag::AddAtribute(), KKB::KKStr::Empty(), KKB::XmlTag::tagEnd, KKB::XmlTag::tagStart, KKB::XmlTag::WriteXML(), KKMLL::XmlElementFileDesc::WriteXML(), KKB::XmlElementBool::WriteXML(), and KKB::XmlTag::XmlTag().
Referenced by KKMLL::Model::WriteModelXMLFields().
{
  XmlTag startTag ("NormalizationParms", XmlTag::TagTypes::tagStart);
  if (!varName.Empty ())
    startTag.AddAtribute ("VarName", varName);
  startTag.WriteXML (o);
  o << endl;
  XmlElementInt32::WriteXML (numOfFeatures, "NumOfFeatures", o);
  XmlElementFloat::WriteXML (numOfExamples, "NumOfExamples", o);
  XmlElementBool::WriteXML (normalizeNominalFeatures, "NormalizeNominalFeatures", o);
  if (fileDesc) XmlElementFileDesc::WriteXML (*fileDesc, "
      FileDesc", o);
  if (mean) XmlElementArrayDouble::WriteXML (numOfFeatures, mean, "Mean", o);
  if (sigma) XmlElementArrayDouble::WriteXML (numOfFeatures, sigma, "sigma", o);
  XmlTag endTag ("NormalizationParms", XmlTag::TagTypes::tagEnd);
  endTag.WriteXML (o);
  o << endl;
}
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/NormalizationParms.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/NormalizationParms.cpp