KKLSC::ScannerFileSimple Class Reference
#include <A>
Public Member Functions
ScannerFileSimple (const KKStr &_fileName, RunLog &_log)
ScannerFileSimple (const KKStr &_fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog &_log)
virtual ~ScannerFileSimple ()
virtual Format FileFormat () const
virtual void WriteTextBlock (const uchar *txtBlock, kkuint32 txtBlockLen)
Static Public Member Functions
static const uchar * CompensationTable ()
Protected Member Functions
virtual kkuint32 ReadBufferFrame ()
Read in one Scanner File Frame return number of actual scan-lines read.
virtual kkint64 SkipToNextFrame ()
Skip to start of next frame returning back byte offset of that frame.
virtual void WriteBufferFrame ()
Write the contents of 'frameBuffer' to he end of the scanner file.
Additional Inherited Members
Detailed Description
simple format where each scan line is stored without any encoding or compression.
Definition at line 11 of file ScannerFileSimple.h.
Constructor & Destructor Documentation
KKLSC::ScannerFileSimple::ScannerFileSimple (const KKStr & _fileName, RunLog & _log)
Constructor for opening file for reading
KKLSC::ScannerFileSimple::ScannerFileSimple (const KKStr & _fileName, kkuint32 _pixelsPerScanLine, kkuint32 _frameHeight, RunLog & _log)
Constructor for opening file for Writing
ScannerFileSimple::~ScannerFileSimple () [virtual]
Definition at line 54 of file ScannerFileSimple.cpp.
{
  if (opened)
    Close ();
}
Member Function Documentation
const uchar * ScannerFileSimple::CompensationTable () [static]
Definition at line 137 of file ScannerFileSimple.cpp.
References KKB::GlobalGoalKeeper::EndBlock(), and KKB::GlobalGoalKeeper::StartBlock().
Referenced by KKLSC::ScannerFile::ConpensationTable().
{
  GlobalGoalKeeper::StartBlock ();
  uchar* cs = new uchar[256];
  for (kkuint32 x = 0; x < 256; ++x)
    cs[x] = x;
  GlobalGoalKeeper::EndBlock ();
  return cs;
}
virtual Format KKLSC::ScannerFileSimple::FileFormat () const [inline], [virtual]
Reimplemented from KKLSC::ScannerFile.
Definition at line 30 of file ScannerFileSimple.h.
References KKLSC::ScannerFile::sfSimple.
{return Format::sfSimple;}
kkuint32 ScannerFileSimple::ReadBufferFrame () [protected], [virtual]
Read in one Scanner File Frame return number of actual scan-lines read.
Unless end of file is reached this method will read in 'framHeight' scan-lines.
Implements KKLSC::ScannerFile.
Definition at line 63 of file ScannerFileSimple.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::frameBufferFileOffsetLast, KKLSC::ScannerFile::frameBufferFileOffsetNext, KKLSC::ScannerFile::frameBufferLen, KKLSC::ScannerFile::frameBufferNextLine, KKB::osFTELL(), and KKLSC::ScannerFile::pixelsPerScanLine.
{
  frameBufferLen = 0;
  frameBufferNextLine = 0;
  if (feof (file) != 0)
  {
    memset (frameBuffer, 0, frameBufferSize);
    return 0;
  }
  frameBufferFileOffsetLast = osFTELL (file);
  frameBufferLen = fread (frameBuffer, 1,
      frameBufferSize, file);
  frameBufferFileOffsetNext = osFTELL (file);
  frameBufferNextLine = 0;
  return (frameBufferLen / pixelsPerScanLine);
} /* ReadBufferFrame */
kkint64 ScannerFileSimple::SkipToNextFrame () [protected], [virtual]
Skip to start of next frame returning back byte offset of that frame.
This will be called by the 'UpdateFrameOffset' and 'DetermineFrameOffsetForFrame' methods used to build the 'frameOffsets' table. It is important that the implementation of this method NOT update the frameBuffer fields; such as 'frameBuffer', 'frameBufferNextLine', etc .....
Implements KKLSC::ScannerFile.
Definition at line 82 of file ScannerFileSimple.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::frameBufferSize, and KKB::osFTELL().
{
  //int64 byteOffset = osFTELL (file);
  kkint64 byteOffset = osFTELL (file);
  kkint64 nextFrameByteOffset = byteOffset + frameBufferSize;
  kkint32 returnCd = osFSEEK (file, nextFrameByteOffset - 1, SEEK_SET);
  char buff[10];
  returnCd = fread (buff, 1, 1, file);
  if (returnCd < 1)
    return -1;
  else
    return nextFrameByteOffset;
} /* SkipToNextFrame */
void ScannerFileSimple::WriteBufferFrame () [protected], [virtual]
Write the contents of 'frameBuffer' to he end of the scanner file.
Will write the entire contents of 'frameBuffer' to the end of the scanner file.
Implements KKLSC::ScannerFile.
Definition at line 100 of file ScannerFileSimple.cpp.
References KKLSC::ScannerFile::file, KKLSC::ScannerFile::fileSizeInBytes, KKLSC::ScannerFile::frameBufferFileOffsetLast, KKLSC::ScannerFile::frameBufferFileOffsetNext, KKLSC::ScannerFile::frameBufferNextLine, KKLSC::ScannerFile::frameBufferSize, KKB::osFTELL(), and KKLSC::ScannerFile::pixelsPerScanLine.
{
  frameBufferFileOffsetLast = osFTELL (file);
  kkuint32 frameBufferSpaceUsed = frameBufferNextLine *
      pixelsPerScanLine;
  fwrite (frameBuffer, 1, frameBufferSpaceUsed, file);
  kkuint32 paddingNeeded = frameBufferSize - frameBufferSpaceUsed;
  if (paddingNeeded > 0)
  {
    uchar* buff = new uchar[paddingNeeded];
    memset (buff, 0, paddingNeeded);
    fwrite (buff, 1, paddingNeeded, file);
    delete[] buff;
  }
  frameBufferNextLine = 0;
  frameBufferFileOffsetNext = osFTELL (file);
  fileSizeInBytes = frameBufferFileOffsetNext;
} /* WriteBufferFrame */
void ScannerFileSimple::WriteTextBlock (const uchar * txtBlock, kkuint32 txtBlockLen) [virtual]
Definition at line 125 of file ScannerFileSimple.cpp.
{
  log.Level (-1) << endl
    << "ScannerFileSimple::WriteTextBlock ***ERROR*** The SimpleFormat does not support TextBlocks" <<
      endl
    << endl;
} /* WriteTextBlock */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFileSimple.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKLineScanner/ScannerFileSimple.cpp