KKMLL::SizeDistribution::ClassTotals Class Reference
Public Types
typedef ClassTotals * ClassTotalsPtr
Public Member Functions
ClassTotals (KKStr _name, kkint32 _bucketCount, kkint32 _bucketSize)
~ClassTotals ()
void AddIn (ClassTotalsPtr classTotals)
kkint32 BucketCount (kkint32 idx)
void Increment (kkint32 size)
void PrintCSVLine (ostream &_outFile)
void PrintFormatedLine (ostream &_outFile)
void PrintTabDelLine (ostream &_outFile)
Public Attributes
kkint32 bucketCount
kkint32 bucketSize
kkint32 count
KKStr name
KKStr nameUpper
kkint32 * sizeBuckets
Detailed Description
Definition at line 33 of file SizeDistribution.cpp.
Member Typedef Documentation
typedef ClassTotals* KKMLL::SizeDistribution::ClassTotals::ClassTotalsPtr
Definition at line 36 of file SizeDistribution.cpp.
Constructor & Destructor Documentation
KKMLL::SizeDistribution::ClassTotals::ClassTotals (KKStr _name, kkint32 _bucketCount, kkint32 _bucketSize) [inline]
Definition at line 38 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::bucketCount, KKMLL::SizeDistribution::ClassTotals::bucketSize, KKMLL::SizeDistribution::ClassTotals::count, KKB::KKStr::KKStr(), KKMLL::SizeDistribution::ClassTotals::name, KKMLL::SizeDistribution::ClassTotals::nameUpper, KKMLL::SizeDistribution::ClassTotals::sizeBuckets, and KKB::KKStr::Upper().
Referenced by KKMLL::SizeDistribution::Increment(), KKMLL::SizeDistribution::PrintCSVDistributionMatrix(), KKMLL::SizeDistribution::PrintFormatedDistributionMatrix(), and KKMLL::SizeDistribution::PrintTabDelDistributionMatrix().
               :
      bucketCount (_bucketCount),
      bucketSize (_bucketSize),
      count (0),
      name (_name),
      nameUpper (_name),
      sizeBuckets (NULL)
  {
    nameUpper.Upper ();
    sizeBuckets = new kkint32[bucketCount];
    for (kkint32 x = 0; x < bucketCount; x++)
       sizeBuckets[x] = 0;
    count = 0;
  }
KKMLL::SizeDistribution::ClassTotals::~ClassTotals () [inline]
Definition at line 60 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::sizeBuckets.
  {
    delete[] sizeBuckets;
  }
Member Function Documentation
void KKMLL::SizeDistribution::ClassTotals::AddIn (ClassTotalsPtr classTotals)
Definition at line 203 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::bucketCount, KKMLL::SizeDistribution::ClassTotals::count, and KKMLL::SizeDistribution::ClassTotals::sizeBuckets.
Referenced by KKMLL::SizeDistribution::PrintCSVDistributionMatrix(), KKMLL::SizeDistribution::PrintFormatedDistributionMatrix(), and KKMLL::SizeDistribution::PrintTabDelDistributionMatrix().
{
  kkint32 idx;
  count = count + classTotals->count;
  for (idx = 0; idx < bucketCount; idx++)
  {
    sizeBuckets[idx] = sizeBuckets[idx] + classTotals->sizeBuckets[idx];
  }
} /* AddIn */
kkint32 KKMLL::SizeDistribution::ClassTotals::BucketCount (kkint32 idx) [inline]
Definition at line 83 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::bucketCount, and KKMLL::SizeDistribution::ClassTotals::sizeBuckets.
Referenced by KKMLL::SizeDistribution::PrintByClassCollumns().
  {
    if ((idx < 0) && (idx >= bucketCount))
      return 0;
    return sizeBuckets[idx];
  }
void KKMLL::SizeDistribution::ClassTotals::Increment (kkint32 size) [inline]
Definition at line 68 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::bucketCount, KKMLL::SizeDistribution::ClassTotals::bucketSize, KKMLL::SizeDistribution::ClassTotals::count, and KKMLL::SizeDistribution::ClassTotals::sizeBuckets.
Referenced by KKMLL::SizeDistribution::Increment().
  {
    kkint32 bucket = (kkint32)(size / bucketSize);
    if (bucket >= bucketCount)
      bucket = bucketCount - 1;
    sizeBuckets[bucket]++;
    count++;
  }
void KKMLL::SizeDistribution::ClassTotals::PrintCSVLine (ostream & _outFile)
Definition at line 169 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::bucketCount.
Referenced by KKMLL::SizeDistribution::PrintCSVDistributionMatrix().
{
  o << "\"" << name << "\"," << count;
  kkint32 bucket;
  for (bucket = 0; bucket < bucketCount; bucket++)
  {
    o << "," << sizeBuckets[bucket];
  }
  o << endl;
}
void KKMLL::SizeDistribution::ClassTotals::PrintFormatedLine (ostream & _outFile)
Definition at line 142 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::bucketCount, KKB::KKStr::Concat(), KKMLL::SizeDistribution::ClassTotals::count, KKB::KKStr::KKStr(), KKB::KKStr::LeftPad(), KKMLL::SizeDistribution::ClassTotals::name, KKB::operator<<(), KKB::KKStr::operator=(), KKB::KKStr::RightPad(), and KKMLL::SizeDistribution::ClassTotals::sizeBuckets.
Referenced by KKMLL::SizeDistribution::PrintFormatedDistributionMatrix().
{
  KKStr s (name);
  s.RightPad (20);
  o << s;
  s = count;
  s.LeftPad (9);
  o << s;
  kkint32 bucket;
  for (bucket = 0; bucket < bucketCount; bucket++)
  {
    s = sizeBuckets [bucket];
    s.LeftPad (8);
    o << s;
  }
  o << endl;
} /* PrintFormatedLine */
void KKMLL::SizeDistribution::ClassTotals::PrintTabDelLine (ostream & _outFile)
Definition at line 185 of file SizeDistribution.cpp.
References KKMLL::SizeDistribution::ClassTotals::bucketCount.
Referenced by KKMLL::SizeDistribution::PrintTabDelDistributionMatrix().
{
  o << "\"" << name << "\"" << "\t" << count;
  kkint32 bucket;
  for (bucket = 0; bucket < bucketCount; bucket++)
  {
    o << "\t" << sizeBuckets[bucket];
  }
  o << endl;
}
Member Data Documentation
kkint32 KKMLL::SizeDistribution::ClassTotals::bucketCount
Definition at line 98 of file SizeDistribution.cpp.
Referenced by KKMLL::SizeDistribution::ClassTotals::AddIn(), KKMLL::SizeDistribution::ClassTotals::BucketCount(), KKMLL::SizeDistribution::ClassTotals::ClassTotals(), KKMLL::SizeDistribution::ClassTotals::Increment(), KKMLL::SizeDistribution::ClassTotals::PrintCSVLine(), KKMLL::SizeDistribution::ClassTotals::PrintFormatedLine(), and KKMLL::SizeDistribution::ClassTotals::PrintTabDelLine().
kkint32 KKMLL::SizeDistribution::ClassTotals::bucketSize
Definition at line 99 of file SizeDistribution.cpp.
Referenced by KKMLL::SizeDistribution::ClassTotals::ClassTotals(), and KKMLL::SizeDistribution::ClassTotals::Increment().
kkint32 KKMLL::SizeDistribution::ClassTotals::count
Definition at line 100 of file SizeDistribution.cpp.
Referenced by KKMLL::SizeDistribution::ClassTotals::AddIn(), KKMLL::SizeDistribution::ClassTotals::ClassTotals(), KKMLL::SizeDistribution::ClassTotals::Increment(), and KKMLL::SizeDistribution::ClassTotals::PrintFormatedLine().
KKStr KKMLL::SizeDistribution::ClassTotals::name
Definition at line 101 of file SizeDistribution.cpp.
Referenced by KKMLL::SizeDistribution::ClassTotals::ClassTotals(), and KKMLL::SizeDistribution::ClassTotals::PrintFormatedLine().
KKStr KKMLL::SizeDistribution::ClassTotals::nameUpper
Definition at line 102 of file SizeDistribution.cpp.
Referenced by KKMLL::SizeDistribution::ClassTotals::ClassTotals().
kkint32* KKMLL::SizeDistribution::ClassTotals::sizeBuckets
Definition at line 103 of file SizeDistribution.cpp.
Referenced by KKMLL::SizeDistribution::ClassTotals::AddIn(), KKMLL::SizeDistribution::ClassTotals::BucketCount(), KKMLL::SizeDistribution::ClassTotals::ClassTotals(), KKMLL::SizeDistribution::ClassTotals::Increment(), KKMLL::SizeDistribution::ClassTotals::PrintFormatedLine(), and KKMLL::SizeDistribution::ClassTotals::~ClassTotals().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/SizeDistribution.cpp