KKB::TokenBufferStream Class Reference
#include <TokenBuffer.h>
Public Member Functions
TokenBufferStream (std::istream *_in)
TokenBufferStream (const KKStr &_fileName)
virtual ~TokenBufferStream ()
virtual bool EndOfFile ()
virtual char GetNextChar ()
virtual char PeekNextChar ()
virtual void UnGetNextChar ()
virtual bool Valid ()
Detailed Description
Definition at line 59 of file TokenBuffer.h.
Constructor & Destructor Documentation
KKB::TokenBufferStream::TokenBufferStream (std::istream * _in)
TokenBufferStream::TokenBufferStream (const KKStr & _fileName)
Definition at line 107 of file TokenBuffer.cpp.
References KKB::KKStr::KKStr(), and KKB::TokenBuffer::TokenBuffer().
Referenced by KKB::Tokenizer::Tokenizer(), and KKB::XmlTokenizer::XmlTokenizer().
                                                            :
    TokenBuffer (),
    endOfFile (false),
    fileName (_fileName),
    fileStream (NULL),
    in (NULL)
{
  fileStream = new ifstream (fileName.Str ());
  if (!fileStream->is_open ())
  {
    delete fileStream;
    fileStream = NULL;
  }
  else
  {
    in = fileStream;
  }
}
TokenBufferStream::~TokenBufferStream () [virtual]
Definition at line 128 of file TokenBuffer.cpp.
{
  if (fileStream)
  {
    in = NULL;
    delete fileStream;
    fileStream = NULL;
  }
}
Member Function Documentation
bool TokenBufferStream::EndOfFile () [virtual]
Implements KKB::TokenBuffer.
Definition at line 189 of file TokenBuffer.cpp.
{
  return endOfFile;
}
char TokenBufferStream::GetNextChar () [virtual]
Implements KKB::TokenBuffer.
Definition at line 155 of file TokenBuffer.cpp.
{
  char c;
  if (endOfFile)
    return 0;
  c = in->get ();
  if (in->eof())
  {
    endOfFile = true;
    c = 0;
  }
  return c;
} /* GetNextChar */
char TokenBufferStream::PeekNextChar () [virtual]
Implements KKB::TokenBuffer.
Definition at line 172 of file TokenBuffer.cpp.
{
  if (in->eof ())
    return 0;
  return in->peek ();
}
void TokenBufferStream::UnGetNextChar () [virtual]
Implements KKB::TokenBuffer.
Definition at line 182 of file TokenBuffer.cpp.
{
  in->unget ();
}
bool TokenBufferStream::Valid () [virtual]
Implements KKB::TokenBuffer.
Definition at line 142 of file TokenBuffer.cpp.
{
  if (fileStream)
  {
    return fileStream->is_open ();
  }
  return (in != NULL);
} /* Valid */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/TokenBuffer.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/TokenBuffer.cpp