SVM289_BFS::Kernel Class Reference
Public Member Functions
Kernel (const FeatureVectorList &_x, const FeatureNumList &_selFeatures, const svm_parameter &_param, RunLog &_log)
virtual ~Kernel ()
virtual Qfloat * get_Q (kkint32 column, kkint32 len) const =0
virtual Qfloat * get_QD () const =0
virtual void swap_index (kkint32 i, kkint32 j)
Static Public Member Functions
static double DotStatic (const FeatureVector &px, const FeatureVector &py, const FeatureNumList &selFeatures)
static double k_function (const FeatureVector &x, const FeatureVector &y, const svm_parameter &param, const FeatureNumList &selFeatures)
Kernel evaluation.
Protected Attributes
double(Kernel::* kernel_function)(kkint32 i, kkint32 j) const
Detailed Description
Definition at line 848 of file svm289_BFS.cpp.
Constructor & Destructor Documentation
SVM289_BFS::Kernel::Kernel (const FeatureVectorList & _x, const FeatureNumList & _selFeatures, const svm_parameter & _param, RunLog & _log)
Definition at line 945 of file svm289_BFS.cpp.
References SVM289_BFS::svm_parameter::coef0, SVM289_BFS::svm_parameter::degree, KKMLL::FeatureVectorList::FeatureVectorList(), SVM289_BFS::svm_parameter::gamma, Kernel(), kernel_function, SVM289_BFS::svm_parameter::kernel_type, SVM289_BFS::LINEAR, KKMLL::FeatureNumList::NumSelFeatures(), KKMLL::FeatureNumList::operator[](), SVM289_BFS::POLY, SVM289_BFS::PRECOMPUTED, SVM289_BFS::RBF, and SVM289_BFS::SIGMOID.
Referenced by Kernel().
                        :
   coef0 (_param.coef0),
   degree (_param.degree),
   gamma (_param.gamma),
   kernel_type (_param.kernel_type),
   l (_x.QueueSize ()),
   numSelFeatures (0),
   preComputed (NULL),
   selFeatures (NULL),
   x (NULL)
{
  x = new FeatureVectorList (_x, false);
  numSelFeatures = _selFeatures.NumSelFeatures ();
  selFeatures = new kkint32[numSelFeatures];
  for (kkint32 zed = 0; zed < numSelFeatures; zed++)
    selFeatures[zed] = _selFeatures[zed];
  switch (kernel_type)
  {
    case LINEAR:
      kernel_function = &Kernel::kernel_linear;
      break;
    case POLY:
      kernel_function = &Kernel::kernel_poly;
      break;
    case RBF:
      kernel_function = &Kernel::kernel_rbf;
      break;
    case SIGMOID:
      kernel_function = &Kernel::kernel_sigmoid;
      break;
    case PRECOMPUTED:
      {
        kkint32 z1 = 0;
        kkint32 z2 = 0;
        kernel_function = &Kernel::kernel_precomputed;
        preComputed = new float*[l];
        for (z1 = 0; z1 < l; z1++)
        {
          preComputed[z1] = new float[l];
          for (z2 = 0; z2 < l; z2++)
            preComputed[z1][z2] = 0.0f;
        }
      }
      break;
  }
  if (kernel_type == RBF)
  {
    x_square = new double[l];
    for (kkint32 i = 0; i < l; i++)
      x_square[i] = dot ((*x)[i], (*x)[i]);
  }
  else
  {
    x_square = 0;
  }
}
SVM289_BFS::Kernel::~Kernel () [virtual]
Definition at line 1019 of file svm289_BFS.cpp.
{
  delete[] selFeatures; selFeatures = NULL;
  delete[] x_square; x_square = NULL;
  if (preComputed)
  {
    kkint32 n = x->QueueSize ();
    kkint32 z1 = 0;
    for (z1 = 0; z1 < l; z1++)
      delete preComputed[z1];
    delete preComputed;
    preComputed = NULL;
  }
  delete x;
  x = NULL;
}
Member Function Documentation
double SVM289_BFS::Kernel::DotStatic (const FeatureVector & px, const FeatureVector & py, const FeatureNumList & selFeatures) [static]
Definition at line 1063 of file svm289_BFS.cpp.
References KKMLL::FeatureVector::FeatureData(), KKMLL::FeatureNumList::NumSelFeatures(), and KKMLL::FeatureNumList::operator[]().
Referenced by k_function().
{
  kkint32 numFeatures = selFeatures.NumSelFeatures ();
  double sum = 0;
  kkint32 fn = 0;
  kkint32 idx = 0;
  const float* fvX = px.FeatureData ();
  const float* fvY = py.FeatureData ();
  for (idx = 0; idx < numFeatures; idx++)
  {
    fn = selFeatures[idx];
    sum += fvX[fn] * fvY[fn];
  }
  return sum;
} /* dot */
virtual Qfloat* SVM289_BFS::Kernel::get_Q (kkint32 column, kkint32 len) const [pure virtual]
Implements SVM289_BFS::QMatrix.
Implemented in SVM289_BFS::SVR_Q, SVM289_BFS::ONE_CLASS_Q, and SVM289_BFS::SVC_Q.
virtual Qfloat* SVM289_BFS::Kernel::get_QD () const [pure virtual]
Implements SVM289_BFS::QMatrix.
Implemented in SVM289_BFS::SVR_Q, SVM289_BFS::ONE_CLASS_Q, and SVM289_BFS::SVC_Q.
double SVM289_BFS::Kernel::k_function (const FeatureVector & x, const FeatureVector & y, const svm_parameter & param, const FeatureNumList & selFeatures) [static]
Kernel evaluation.
The static method k_function is for doing single kernel evaluation the constructor of Kernel prepares to calculate the l*l kernel matrix the member function get_Q is for getting one column from the Q Matrix
Definition at line 1092 of file svm289_BFS.cpp.
References SVM289_BFS::svm_parameter::coef0, SVM289_BFS::svm_parameter::degree, DotStatic(), KKMLL::FeatureVector::FeatureData(), SVM289_BFS::svm_parameter::gamma, SVM289_BFS::svm_parameter::kernel_type, SVM289_BFS::LINEAR, KKMLL::FeatureNumList::NumSelFeatures(), KKMLL::FeatureNumList::operator[](), SVM289_BFS::POLY, SVM289_BFS::powi(), SVM289_BFS::PRECOMPUTED, SVM289_BFS::RBF, and SVM289_BFS::SIGMOID.
{
  switch (param.kernel_type)
  {
    case LINEAR:
      return DotStatic(x, y, selFeatures);
    case POLY:
      return powi (param.gamma * DotStatic (x, y, selFeatures) + param.
      coef0,param.degree);
    case RBF:
    {
      kkint32 numSelFeatures = selFeatures.NumSelFeatures ();
      kkint32 fn = 0;
      kkint32 idx = 0;
      const float* fvX = x.FeatureData ();
      const float* fvY = y.FeatureData ();
      double sum = 0;
      for (idx = 0; idx < numSelFeatures; idx++)
      {
        fn = selFeatures[idx];
        double d = fvX[fn] - fvY[fn];
        sum += d * d;
      }
      
      return exp (-param.gamma * sum);
    }
    case SIGMOID:
      return tanh(param.gamma * DotStatic (x, y, selFeatures) + param.
      coef0);
    case PRECOMPUTED: //x: test (validation), y: SV
      {
        cerr << endl
             << "SVM289_BFS::Kernel::k_function ***ERROR*** does not support 'PRECOMPUTED'." <<
      endl
             << endl;
        return 0;
      }
    default:
      return 0; // Unreachable
  }
} /* k_function */
virtual void SVM289_BFS::Kernel::swap_index (kkint32 i, kkint32 j) [inline], [virtual]
Implements SVM289_BFS::QMatrix.
Reimplemented in SVM289_BFS::SVR_Q, SVM289_BFS::ONE_CLASS_Q, and SVM289_BFS::SVC_Q.
Definition at line 878 of file svm289_BFS.cpp.
Referenced by SVM289_BFS::SVC_Q::swap_index(), and SVM289_BFS::ONE_CLASS_Q::swap_index().
  {
    //swap (x[i], x[j]);
    x->SwapIndexes (i, j);
    if (x_square)
      swap (x_square[i], x_square[j]);
  }
Member Data Documentation
double(Kernel::* SVM289_BFS::Kernel::kernel_function) (kkint32 i, kkint32 j) const [protected]
Definition at line 887 of file svm289_BFS.cpp.
Referenced by SVM289_BFS::SVC_Q::get_Q(), SVM289_BFS::ONE_CLASS_Q::get_Q(), SVM289_BFS::SVR_Q::get_Q(), Kernel(), SVM289_BFS::ONE_CLASS_Q::ONE_CLASS_Q(), SVM289_BFS::SVC_Q::SVC_Q(), and SVM289_BFS::SVR_Q::SVR_Q().
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm289_BFS.cpp