KKMLL::ClassStatisticList::ClassStatSortByCount Class Reference
Public Member Functions
ClassStatSortByCount ()
bool operator() (ClassStatisticPtr p1, ClassStatisticPtr p2)
Detailed Description
Definition at line 140 of file ClassStatistic.cpp.
Constructor & Destructor Documentation
KKMLL::ClassStatisticList::ClassStatSortByCount::ClassStatSortByCount () [inline]
Definition at line 143 of file ClassStatistic.cpp.
{}
Member Function Documentation
bool KKMLL::ClassStatisticList::ClassStatSortByCount::operator() (ClassStatisticPtr p1, ClassStatisticPtr p2) [inline]
Definition at line 145 of file ClassStatistic.cpp.
References KKMLL::ClassStatistic::Count(), KKMLL::ClassStatistic::MLClass(), KKB::KKStr::operator<(), and KKMLL::MLClass::UpperName().
   {
     if (p1->Count () > p2->Count ())
       return true;
     else if (p1->Count () < p2->Count ())
       return false;
     return p1->MLClass ()->UpperName () < p2->MLClass ()->
      UpperName ();
   }
The documentation for this class was generated from the following file:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/ClassStatistic.cpp