KKB::DateType Class Reference
Represents a calendar date consisting of three fields, Year, Month, and Day.
#include <DateTime.h>
Public Member Functions
DateType ()
DateType (const DateType &_date)
DateType (short _year, uchar _month, uchar _day)
summary> Constructs a date from an integer that represents the total number of days since 1/1/0000 */
DateType (kkint32 days)
DateType (KKStr s)
void AddDays (kkint32 _days)
void AddMonths (kkint32 _months)
uchar Day () const
kkint32 Days () const
uchar DaysThisMonth () const
returns the number of days in 'month' and if leapYear and February returns 29.
KKStr MM_DD_YY () const
KKStr MMM_DD_YYYY () const
Convert into displayable string; ex: May/02/2010.
uchar Month () const
bool operator!= (const DateType &right) const
DateType operator+ (const DateType &right) const
DateType operator+ (kkint32 right) const
DateType & operator++ ()
DateType operator- (kkint32 right) const
DateType operator- (const DateType &right) const
bool operator< (const DateType &right) const
bool operator<= (const DateType &right) const
DateType & operator= (const DateType &right)
bool operator== (const DateType &right) const
bool operator> (const DateType &right) const
bool operator>= (const DateType &right) const
kkuint64 Seconds () const
void SubtractDays (kkint32 _days)
kkuint32 ToDays () const
kkuint32 ToHours () const
kkuint64 ToSeconds () const
short Year () const
KKStr YY_MM_DD () const
Convert into displayable string; ex: 11/05/17.
KKStr YYYY_MM_DD () const
Convert into displayable string; ex: 20011/05/17.
KKStr YYYY_MMM_DD () const
Convert into displayable string; ex: 20011/May/17.
KKStr YYYYMMDD () const
Convert into displayable string; ex: 20110517.
Static Public Member Functions
static uchar DaysInTheMonth (kkint32 year, uchar month)
static kkint32 DaysYTDforMonth (kkint32 year, uchar month)
static uchar MonthFromStr (const KKStr &monthStr)
Friends
class DateTime
Detailed Description
Represents a calendar date consisting of three fields, Year, Month, and Day.
remarks> This date format will support operations that will allow you to determine the number of days between two dates; derive a new date by adding or subtracting Days, Months, or Years from an existing date, etc; and convert date into one of several displayable formats. /remarks>
Definition at line 28 of file DateTime.h.
Constructor & Destructor Documentation
DateType::DateType ()
Definition at line 157 of file DateTime.cpp.
Referenced by KKB::DateTime::DateTime().
                   :
     year (0),
     month (0),
     day (0)
{
}
DateType::DateType (const DateType & _date)
Definition at line 166 of file DateTime.cpp.
Referenced by KKB::DateTime::DateTime().
                                         :
     year (_date.year),
     month (_date.month),
     day (_date.day)
{
}
DateType::DateType (short _year, uchar _month, uchar _day)
summary> Constructs a date from an integer that represents the total number of days since 1/1/0000 */
Definition at line 175 of file DateTime.cpp.
Referenced by KKB::DateTime::DateTime().
                    :
   year (_year),
   month (_month),
   day (_day)
{
}
DateType::DateType (kkint32 days)
summary> Constructs a date from a displayable string; the year, month, and days fields are detertmie3d from context.
remarks> Strings can be both all numeric or combination of alpha numeric. Each part of the date, (Year, Month, Day) can be separated by " ", "/", tab, line-feed, or carriage-return. Examples of valid strings are "1997/02/25", "02/25/1997", "Feb 02 1997", "02/Feb/1997", "1997 February 02". The ordering of the numeric fields will be determined by context with one of three possible formats, mm/dd/yyyy, yyyy/mm/dd, and dd/mm/yyyy.
A flaw in this schema is that if the day of the month is in the range of (1 thru 12), an all numeric format is used, and the ordering is supposed to be "dd/mm/yyyy" this routine will assume that it is looking at "mm/dd/yyyy" with the result of swapping the "Month" and "Day" fields. As a rule I try to always use the alpha numeric version of the month. /remarks>
Definition at line 311 of file DateTime.cpp.
Referenced by operator+(), KKB::DateTime::operator+(), operator-(), and KKB::DateTime::operator-().
{
  SetFromNumOfDaysInTime (days);
}
DateType::DateType (KKStr s)
summary> Adds a number of days to the date.
example> Example: Date d ("April 14 1962"); // Sets the instance of "d" to the date "1962-04-14". d.AddDays (12); // "d" now contains the date "1962-04-24". d.AddDays (-25); // "d" now contains the date "1962-03-30". /example>
Definition at line 187 of file DateTime.cpp.
References KKB::KKStr::Concat(), DaysInTheMonth(), KKB::KKStr::ExtractToken(), and MonthFromStr().
Referenced by KKB::Application::BuildDate(), and KKB::DateTime::DateTime().
                           :
   year (0),
   month (0),
   day (0)
{
  KKStr field1 = s.ExtractToken ("\n\r\t/- ");
  KKStr field2 = s.ExtractToken ("\n\r\t/- ");
  KKStr field3 = s.ExtractToken ("\n\r\t/- ");
  uchar m;
  uchar d;
  short y;
  m = MonthFromStr (field1);
  if ((m > 0) && (m < 13))
  {
    // The first field is a month, assume mmm/dd/yyyy
    d = (uchar)atoi (field2.Str ());
    y = (short)atoi (field3.Str ());
    if ((d < 1) || (d > DaysInTheMonth (y, m)))
      d = 1;
    year = y;
    month = m;
    day = d;
    return;
  }
  m = MonthFromStr (field2);
  if ((m > 0) && (m < 13))
  {
    // Second field is a month field, assuming yyyy/mmm/dd
    kkint32 f3 = atoi (field3.Str ());
    kkint32 f1 = atoi (field1.Str ());
    
    if (f3 > 1900)
    {
      y = (short)f3;
      d = (uchar)f1;
    }
    else
    {
      y = (short)f1;
      d = (uchar)f3;
    }
    if (d < 1)
      d = 1;
    else if (d > DaysInTheMonth (y, m))
      d = DaysInTheMonth (y, m);
    year = y;
    month = m;
    day = d;
    AdjustYear ();
    return;
  }
  kkint32 f1 = atoi (field1.Str ());
  kkint32 f2 = atoi (field2.Str ());
  kkint32 f3 = atoi (field3.Str ());
  if (((f1 >= 1) && (f1 <= 12)) &&
       ((f2 >= 1) && (f2 <= 31)) &&
       ((f3 >= 0) && (f3 <= 9999))
      )
  {
    // mm/dd/yyyy
    year = short (f3);
    month = uchar (f1);
    day = uchar (f2);
    AdjustYear ();
    return;
  }
  if (((f1 >= 0) && (f1 <= 9999)) &&
       ((f2 >= 1) && (f2 <= 12)) &&
       ((f3 >= 1) && (f3 <= 31))
      )
  {
    // yyyy/mm/dd
    year = short (f1);
    month = uchar (f2);
    day = uchar (f3);
    AdjustYear ();
    return;
  }
  if (((f1 >= 0) && (f1 <= 31)) &&
       ((f2 >= 1) && (f2 <= 12)) &&
       ((f3 >= 1) && (f3 <= 9999))
      )
  {
    // dd/mm/yyyy
    year = short (f3);
    month = uchar (f2);
    day = uchar (f1);
    AdjustYear ();
    return;
  }
  year = 0;
  month = 1;
  day = 1;
}
Member Function Documentation
void DateType::AddDays (kkint32 _days)
Definition at line 381 of file DateTime.cpp.
References Days(), DaysThisMonth(), and SubtractDays().
Referenced by KKB::DateTime::AddDays(), and SubtractDays().
{
  if (_days < 0)
  {
    SubtractDays (0 - _days);
    return;
  }
  if (_days > 365)
  {
    kkint32 numDays = Days () + _days;
    SetFromNumOfDaysInTime (numDays);
    return;
  }
  kkint32 newDay = day + _days;
  while (newDay > DaysThisMonth ())
  {
    newDay = newDay - DaysThisMonth ();
    month++;
    if (month > 12)
    {
      month = 1;
      year++;
    }
  }
  day = (uchar)newDay;
} /* AddDays */
void DateType::AddMonths (kkint32 _months)
Definition at line 446 of file DateTime.cpp.
{
  kkint32 newMonth = month + _months;
  year = year + (short)(newMonth / 12);
  newMonth = newMonth % 12;
  if (newMonth == 0)
  {
    year--;
    newMonth += 12;
  }
} /* AddMonths */
uchar KKB::DateType::Day () const [inline]
summary> Returns back the number of days since "1/1/0000".
remarks> This can be used to determine the number of days between two different dates. For example you have two instances of "DateType" "d1" and "d2". The number of days between the two dates can be determined by "int deltaDays = d1.Days () - d2.Days ();". /remarks>
Definition at line 72 of file DateTime.h.
Referenced by KKB::DateTime::Day(), MM_DD_YY(), and MMM_DD_YYYY().
kkint32 DateType::Days () const
Definition at line 475 of file DateTime.cpp.
References DaysYTDforMonth().
Referenced by AddDays(), operator+(), KKB::DateTime::operator+(), operator-(), KKB::DateTime::operator-(), Seconds(), SubtractDays(), ToDays(), KKB::DateTime::ToDays(), ToHours(), KKB::DateTime::ToHours(), ToSeconds(), and KKB::DateTime::ToSeconds().
{
  if ((month < 1) || (month > 12))
    return 0;
  
  kkint32 totDays = 0;
  if (year < 0)
  {
    kkint32 x = 0 - year;
    totDays = totDays - ((x * 365) + (x / 4));
  }
  else if (year > 0)
  {
    totDays += (year * 365) + ((year - 1) / 4) + 1; // The "+ 1" is for year 0 which is a leap year
  }
  totDays += day + DaysYTDforMonth (year, month);
  return totDays;
} /* Days */
uchar DateType::DaysInTheMonth (kkint32 year, uchar month) [static]
Definition at line 114 of file DateTime.cpp.
Referenced by DateType(), DaysThisMonth(), and operator++().
{
  if ((month < 1) || (month > 12))
    return 0;
  if (month == 2)
  {
    if ((year % 4) == 0)
      return 29;
  }
  return daysInEachMonth[month];
}
uchar DateType::DaysThisMonth () const
returns the number of days in 'month' and if leapYear and February returns 29.
Definition at line 317 of file DateTime.cpp.
References DaysInTheMonth().
Referenced by AddDays(), and SubtractDays().
{
  return DaysInTheMonth (year, month);
}
kkint32 DateType::DaysYTDforMonth (kkint32 year, uchar month) [static]
Definition at line 132 of file DateTime.cpp.
Referenced by Days().
{
  if ((month < 1) || (month > 12))
    return 0;
  if (month < 3)
    return daysYTDforMonth[month - 1];
  if ((year % 4) == 0)
  {
    return daysYTDforMonth[month - 1] + 1;
  }
  else
  {
    return daysYTDforMonth[month - 1];
  }
} /* DaysYTDforMonth */
KKStr DateType::MM_DD_YY () const
Definition at line 665 of file DateTime.cpp.
References KKB::KKStr::Concat(), Day(), KKB::KKStr::KKStr(), Month(), KKB::StrFormatInt(), and Year().
{
  KKStr s (9);
  s << StrFormatInt (Month (), "00") << "/"
    << StrFormatInt (Day (), "00") << "/"
    << StrFormatInt (Year () % 100, "00");
  return s;
} /* MM_DD_YY */
KKStr DateType::MMM_DD_YYYY () const
Convert into displayable string; ex: May/02/2010.
Definition at line 676 of file DateTime.cpp.
References KKB::KKStr::Concat(), Day(), KKB::KKStr::KKStr(), KKB::StrFormatInt(), and Year().
{
  KKStr s (12);
  if ((month < 1) || (month > 12))
    s << "***";
  else
    s << monthlyShortNames[month];
  s << StrFormatInt (Day (), "00") << "/"
    << StrFormatInt (Year (), "0000");
  return s;
} /* MMM_DD_YYYY */
uchar KKB::DateType::Month () const [inline]
Definition at line 71 of file DateTime.h.
Referenced by MM_DD_YY(), and KKB::DateTime::Month().
{return month;}
uchar DateType::MonthFromStr (const KKStr & monthStr) [static]
Definition at line 95 of file DateTime.cpp.
References KKB::KKStr::CompareIgnoreCase().
Referenced by DateType().
{
  uchar month = 0;
  for (month = 1; month < 13; month++)
  {
    if (monthStr.CompareIgnoreCase (monthlyShortNames[month]) == 0)
      break;
    if (monthStr.CompareIgnoreCase (monthlyNames[month]) == 0)
      break;
  }
  return month;
} /* MonthFromStr */
bool DateType::operator!= (const DateType & right) const
Definition at line 548 of file DateTime.cpp.
{
  return (Compare (right) != 0);
}
DateType DateType::operator+ (const DateType & right) const
Definition at line 621 of file DateTime.cpp.
References DateType(), and Days().
{
  return DateType (Days () + right.Days ());
}
DateType DateType::operator+ (kkint32 right) const
Definition at line 628 of file DateTime.cpp.
References DateType(), and Days().
Referenced by KKB::DateTime::AddHours().
{
  return DateType (Days () + right);
}
DateType & DateType::operator++ ()
Definition at line 647 of file DateTime.cpp.
References DaysInTheMonth().
{
  day++;
  if (day > DaysInTheMonth (year, month))
  {
    day = 1;
    month++;
    if (month > 12)
    {
      month = 1;
      year++;
    }
  }
  return *this;
}
DateType DateType::operator- (kkint32 right) const
Definition at line 634 of file DateTime.cpp.
References DateType(), and Days().
Referenced by KKB::DateTime::AddHours().
{
  return DateType (Days () - right);
}
DateType DateType::operator- (const DateType & right) const
Definition at line 641 of file DateTime.cpp.
References DateType(), and Days().
{
  return DateType (Days () - right.Days ());
}
bool DateType::operator< (const DateType & right) const
Definition at line 569 of file DateTime.cpp.
{
  return (Compare (right) < 0);
}
bool DateType::operator<= (const DateType & right) const
Definition at line 577 of file DateTime.cpp.
{
  return (Compare (right) <= 0);
}
DateType & DateType::operator= (const DateType & right)
Definition at line 462 of file DateTime.cpp.
Referenced by KKB::DateTime::AddHours(), KKB::DateTime::DateTime(), and KKB::DateTime::operator=().
{
  year = right.year;
  month = right.month;
  day = right.day;
  return *this;
}
bool DateType::operator== (const DateType & right) const
Definition at line 542 of file DateTime.cpp.
{
  return (Compare (right) == 0);
}
bool DateType::operator> (const DateType & right) const
Definition at line 555 of file DateTime.cpp.
{
  return (Compare (right) > 0);
}
bool DateType::operator>= (const DateType & right) const
Definition at line 562 of file DateTime.cpp.
{
  return (Compare (right) >= 0);
}
kkuint64 DateType::Seconds () const
Definition at line 502 of file DateTime.cpp.
References Days().
Referenced by KKB::DateTime::Seconds().
{
  kkuint64 numDays = (kkuint64)Days ();
  kkuint64 numSecs = numDays * (kkuint64)86400;
  return numSecs;
}
void DateType::SubtractDays (kkint32 _days)
Definition at line 414 of file DateTime.cpp.
References AddDays(), Days(), and DaysThisMonth().
Referenced by AddDays().
{
  if (_days < 0)
  {
    AddDays (0 - _days);
    return;
  }
  if (_days > 365)
  {
    kkint32 numDays = Days () - _days;
    SetFromNumOfDaysInTime (numDays);
    return;
  }
  kkint32 newDay = day - _days;
  while (newDay < 1)
  {
    month--;
    while (month < 1)
    {
      month += 12;
      year--;
    }
    newDay = newDay + DaysThisMonth ();
  }
  day = (uchar)newDay;
} /* SubtractDays */
kkuint32 DateType::ToDays () const
Definition at line 510 of file DateTime.cpp.
References Days().
{return Days ();}
kkuint32 DateType::ToHours () const
Definition at line 511 of file DateTime.cpp.
References Days().
Referenced by KKB::DateTime::HH_MM_SS().
{return Days () * 24;}
kkuint64 DateType::ToSeconds () const
Definition at line 512 of file DateTime.cpp.
References Days().
{return (kkuint64)(Days ()) * (kkuint64)86400;}
short KKB::DateType::Year () const [inline]
Definition at line 70 of file DateTime.h.
Referenced by MM_DD_YY(), MMM_DD_YYYY(), and KKB::DateTime::Year().
{return year;}
KKStr DateType::YY_MM_DD () const
Convert into displayable string; ex: 11/05/17.
Definition at line 691 of file DateTime.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), and KKB::StrFormatInt().
{
  KKStr s (9);
  s << StrFormatInt (year % 100, "00") << "/"
    << StrFormatInt (month, "00") << "/"
    << StrFormatInt (day, "00");
  return s;
} /* YY_MM_DD */
KKStr DateType::YYYY_MM_DD () const
Convert into displayable string; ex: 20011/05/17.
Definition at line 701 of file DateTime.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), and KKB::StrFormatInt().
Referenced by KKB::Application::BuildDate(), KKB::operator<<(), and KKB::DateTime::YYYY_MM_DD_HH_MM_SS().
{
  KKStr s (11);
  s << StrFormatInt (year, "0000") << "/"
    << StrFormatInt (month, "00") << "/"
    << StrFormatInt (day, "00");
  return s;
} /* YYYY_MM_DD */
KKStr DateType::YYYY_MMM_DD () const
Convert into displayable string; ex: 20011/May/17.
Definition at line 712 of file DateTime.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), and KKB::StrFormatInt().
Referenced by KKB::operator<<().
{
  const char* monthStr = "***";
  if ((month >= 1) && (month <= 12))
    monthStr = monthlyShortNames[month];
  KKStr s (12);
  s << StrFormatInt (year, "0000") << "/"
    << monthStr << "/"
    << StrFormatInt (day, "00");
  return s;
} /* YYYY_MM_DD */
KKStr DateType::YYYYMMDD () const
Convert into displayable string; ex: 20110517.
Definition at line 727 of file DateTime.cpp.
References KKB::KKStr::Concat(), KKB::KKStr::KKStr(), and KKB::StrFormatInt().
Referenced by KKB::DateTime::YYYYMMDDHHMMSS().
{
  KKStr s (8);
  s << StrFormatInt (year, "0000")
    << StrFormatInt (month, "00")
    << StrFormatInt (day, "00");
  return s;
}
Friends And Related Function Documentation
friend class DateTime [friend]
Definition at line 138 of file DateTime.h.
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/DateTime.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/DateTime.cpp