KKB::PointList Class Reference
Container object used to maintaining a list of pixel locations.
#include <Point.h>
Public Types
typedef PointList * PointListPtr
Public Member Functions
PointList (const PointList &pointList)
PointList (bool _owner)
void BoxCoordinites (kkint32 &minRow, kkint32 &minCol, kkint32 &maxRow, kkint32 &maxCol)
Point CalculateCenterPoint ()
float ComputeSegmentLens (float heightFactor, float widthFactor) const
KKStr ToDelStr (char del) const
Static Public Member Functions
static PointListPtr FromDelStr (const KKStr &s)
Additional Inherited Members
Detailed Description
Container object used to maintaining a list of pixel locations.
Definition at line 75 of file Point.h.
Member Typedef Documentation
typedef PointList* KKB::PointList::PointListPtr
Definition at line 78 of file Point.h.
Constructor & Destructor Documentation
PointList::PointList (const PointList & pointList)
Definition at line 93 of file Point.cpp.
References PointList().
Referenced by PointList().
                                                :
    KKQueue<Point> (true)
{
  PointList::const_iterator idx;
  for (idx = pointList.begin (); idx != pointList.end (); idx++)
  {
    PushOnBack (new Point (*(*idx)));
  }
}
PointList::PointList (bool _owner)
Definition at line 105 of file Point.cpp.
References PointList().
Referenced by KKB::ContourFollower::CreateFourierDescriptorBySampling(), KKB::ContourFollower::CreatePointListFromFourier(), KKB::Raster::DeriveImageLength(), FromDelStr(), KKB::ContourFollower::GenerateContourList(), PointList(), and KKB::Raster::ThinContour().
                                :
    KKQueue<Point> (_owner)
{
}
Member Function Documentation
void PointList::BoxCoordinites (kkint32 & minRow, kkint32 & minCol, kkint32 & maxRow, kkint32 & maxCol)
Definition at line 111 of file Point.cpp.
References KKB::Point::Col(), and KKB::Point::Row().
Referenced by KKB::ContourFollower::CreatePointListFromFourier().
{
  minRow = minCol = 999999;
  maxRow = maxCol = -1;
  for (iterator x = begin (); x != end (); x++)
  {
    PointPtr p = *x;
    if (p->Row () < minRow)
      minRow = p->Row ();
    if (p->Row () > maxRow)
      maxRow = p->Row ();
    if (p->Col () < minCol)
      minCol = p->Col ();
    if (p->Col () > maxCol)
      maxCol = p->Col ();
  }
}
Point PointList::CalculateCenterPoint ()
Definition at line 138 of file Point.cpp.
References KKB::Point::Col(), KKB::Point::Point(), and KKB::Point::Row().
{
  kkint32 totalRow = 0;
  kkint32 totalCol = 0;
  for (iterator x = begin (); x != end (); x++)
  {
    PointPtr p = *x;
    totalRow += p->Row ();
    totalCol += p->Col ();
  }
  kkint32 centerRow = (kkint32)((double)totalRow / (double)size () + 0.5);
  kkint32 centerCol = (kkint32)((double)totalCol / (double)size () + 0.5);
  return Point (centerRow, centerCol);
}
float PointList::ComputeSegmentLens (float heightFactor, float widthFactor) const
Definition at line 233 of file Point.cpp.
{
  if (QueueSize () < 1)
    return 0.0f;
  float totalLen = 0.0f;
  const_iterator idx;
  idx = begin ();
  PointPtr lastPoint = *idx;
  ++idx;
  while (idx != end ())
  {
    PointPtr nextPoint = *idx; ++idx;
    float deltaHeight = (float)(nextPoint->Row () - lastPoint->Row ()) * heightFactor;
    float deltaWidth = (float)(nextPoint->Col () - lastPoint->Col ()) * widthFactor;
    float segmentLen = sqrt (deltaHeight * deltaHeight + deltaWidth * deltaWidth);
    totalLen += segmentLen;
    lastPoint = nextPoint;
  }
  return totalLen;
} /* ComputeSegmentLens */
PointListPtr PointList::FromDelStr (const KKStr & s) [static]
Definition at line 176 of file Point.cpp.
References KKB::KKStr::ChopFirstChar(), KKB::KKStr::Concat(), KKB::KKStr::ExtractTokenInt(), KKB::KKStr::Find(), KKB::KKStr::FirstChar(), KKB::KKStr::KKStr(), KKB::KKStr::Len(), KKB::KKStr::operator=(), PointList(), KKB::KKStr::SubStrPart(), and KKB::KKStr::TrimLeft().
{
  PointListPtr result = new PointList (true);
  KKStr s (_s);
  s.TrimLeft ();
  while (s.Len () > 0)
  {
    char nextCh = s.FirstChar ();
    char endPairChar = 0;
    if (nextCh == '[')
      endPairChar = ']';
    else if (nextCh == '(')
      endPairChar = ')';
    else
    {
      // Not Bracketed.
      endPairChar = 0;
      kkint16 row = (kkint16)s.ExtractTokenInt (",\t\n\t");
      kkint16 col = (kkint16)s.ExtractTokenInt (",\t\n\t");
      result->PushOnBack (new Point (row, col));
    }
    if (endPairChar != 0)
    {
      KKStr pairStr = "";
      kkint32 idx = s.Find (endPairChar);
      if (idx >= 0)
      {
        pairStr = s.SubStrPart (0, idx - 1);
        s = s.SubStrPart (idx + 1);
      }
      else
      {
        pairStr = s;
        s = "";
      }
      kkint16 row = (kkint16)pairStr.ExtractTokenInt (",");
      kkint16 col = (kkint16) pairStr.ExtractTokenInt (",");
      result->PushOnBack (new Point (row, col));
      nextCh = s.FirstChar ();
      if ((nextCh == ',') || (nextCh == '\n') || (nextCh == '\r') || (nextCh == '\t'))
        s.ChopFirstChar ();
    }
    s.TrimLeft ();
  }
  return result;
} /* FromDelStr */
KKStr PointList::ToDelStr (char del) const
Definition at line 156 of file Point.cpp.
References KKB::Point::Col(), KKB::KKStr::Concat(), and KKB::Point::Row().
{
  if (QueueSize () < 1)
    return "[]";
  KKStr result (QueueSize () * 10);
  int count = 0;
  PointList::const_iterator idx;
  for (idx = begin (); idx != end (); ++idx, ++count)
  {
    PointPtr p = *idx;
    if (count > 0)
      result << del;
    result << p->Row () << del << p->Col ();
  }
  return result;
} /* ToDelStr */
The documentation for this class was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Point.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKBase/Point.cpp