KKMLL Namespace Reference
Namespace for all K^2 Machine Learning code.
Classes
class Attribute
describes a single Feature, Type and possible values.
class AttributeList
class AttributeTypeVector
class BinaryClassParms
Similar to SVMparam except it is specialized for two classes.
class BinaryClassParmsList
class ClassAssignments
Binds MLClass objects to the appropriate number that the Learning Algorithm expects.
class ClassificationBiasMatrix
Assists in adjusting a Classifiers output for bias of a classifier.
class Classifier2
class Classifier2List
class ClassProb
Used to record probability for a specified class; and a list of classes.
class ClassProbList
class ClassStatistic
Used by routines that retrieve Class statistics from FeatureVectorList instances.
class ClassStatisticList
class ConfusionMatrix2
A confusion matrix object that is used to record the results from a CrossValidation. <see also cref=`CrossValidation`
class ConfussionMatrix2List
class CrossValidation
A class that is meant to manage a n-Fold Cross Validation.
class CrossValidationMxN
class CrossValidationVoting
class DuplicateImage
class DuplicateImageList
class DuplicateImages
Detects duplicate images in a given FeaureVectorList objects.
class ExtractExampleFileName
class ExtractFeatureData
class FactoryFVProducer
Responsible for creating a FeatureFectorProducer instance.
class FeatureEncoder
class FeatureEncoder2
class FeatureFileIO
Base class for all FeatureFileIO classes.
class FeatureFileIOArff
Support the writing of ARFF Formatted Feature Files.
class FeatureFileIOC45
Supports the reading and writing of feature data from C45 formated feature files.
class FeatureFileIOColumn
Supports a simple Feature File format where each column represents a example and each row a feature value.
class FeatureFileIODstWeb
class FeatureFileIORoberts
Supports the writing of Feature Data to a file that can then be read by OpenDT.
class FeatureFileIOSparse
Supports the reading and writing of Sparse feature files similar to the ones libSVM use.
class FeatureFileIOUCI
Supports the reading and writing of Feature data from a file format commonly used by many dataset's in the UCI repository.
class FeatureNumList
Keeps track of selected features.
class FeatureVector
Represents a Feature Vector of a single example, labeled or unlabeled.
class FeatureVectorList
Container class for FeatureVector derived objects.
class FeatureVectorProducer
A abstract class that is meant to compute a FeatureVector from a source image.
class FileDesc
Provides a detailed description of the attributes of a dataset.
class FileDescList
Container class file 'FileDesc' instances.
class GrayScaleImagesFV
Specialized version of KKMLL::FeatureVector that will be used to represent the features of a Shrimp.
class GrayScaleImagesFVList
class GrayScaleImagesFVProducer
class GrayScaleImagesFVProducerFactory
class ImageDataTreeEntry
class ImageFeaturesDataIndexed
class ImageFeaturesNameIndexed
class ImageFeaturesNodeKey
class KKMLVariables
class MLClass
Represents a `Class` in the Machine Learning Sense.
class MLClassIndexList
Maintains a list of classes and their associated integer index.
class MLClassList
Maintains a list of MLClass instances.
class Model
Base class to all Learning Algorithms.
class ModelDual
Will implement the Dual Classifier Model.
class ModelKnn
class ModelOldSVM
A specialization of 'Model'; meant to Wrap the original version of 'SvmModel' class. It will allow us to use the original implementation using version 2.39 of LibSVM.
class ModelParam
Abstract Base class for Machine Learning parameters.
class ModelParamDual
class ModelParamKnn
class ModelParamOldSVM
class ModelParamSvmBase
class ModelParamUsfCasCor
This class encapsulates are the information necessary to build a UsfCasCor class.
class ModelSvmBase
class ModelUsfCasCor
class NormalizationParms
Normalization Parameters; calculation and implementation.
class Orderings
Used to maintain multiple orderings of a single list of FeatureVector objects.
class ProbNamePair
class SizeDistribution
Used to keep track of examples by size; typically used by 'CrossValidation'; for each example predicted it would call the ;Increment' method keeping track.
class SVMModel
class SVMparam
This class encapsulates are the information necessary to build a SVMModel class.
class TrainingClass
Specify where training examples and other related data for a MLClass that is needed to train a classifier.
class TrainingClassList
class TrainingConfiguration2
class TrainingConfiguration2List
class TrainingProcess2
class TrainingProcess2List
class XmlElementFileDesc
class XmlElementMLClass
class XmlElementMLClassNameList
Will only write the ClassName rather than complete MLClass instances.
class XmlElementModel
The base class to be used for the manufacturing if `Model` derived classes.
class XmlElementModelParam
Base class to be used by all ModelParam derived objects.
class XmlElementModelParamTemplate
ModelParam derived classes will implement their `XmlElement` helper class via this template.
class XmlElementModelTemplate
Typedefs
typedef AttributeList const * AttributeListConstPtr
typedef AttributeList * AttributeListPtr
typedef Attribute * AttributePtr
typedef AttributeTypeVector * AttributeTypeVectorPtr
typedef BinaryClassParmsList::BinaryClassParmsListPtr BinaryClassParmsListPtr
typedef BinaryClassParms::BinaryClassParmsPtr BinaryClassParmsPtr
typedef ClassAssignments * ClassAssignmentsPtr
typedef ClassificationBiasMatrix::ClassificationBiasMatrixPtr ClassificationBiasMatrixPtr
typedef Classifier2List * Classifier2ListPtr
typedef Classifier2 * Classifier2Ptr
typedef ClassProbList * ClassProbListPtr
typedef ClassProb * ClassProbPtr
typedef ClassStatisticList * ClassStatisticListPtr
typedef ClassStatistic * ClassStatisticPtr
typedef ConfusionMatrix2::ConfusionMatrix2Ptr ConfusionMatrix2Ptr
typedef ConfussionMatrix2List * ConfussionMatrix2ListPtr
typedef CrossValidation * CrossValidationPtr
typedef CrossValidationVoting * CrossValidationVotingPtr
typedef DuplicateImageList * DuplicateImageListPtr
typedef DuplicateImage * DuplicateImagePtr
typedef DuplicateImages * DuplicateImagesPtr
typedef std::vector< double > Dvector
typedef FactoryFVProducer * FactoryFVProducerPtr
typedef FeatureEncoder2 * FeatureEncoder2Ptr
typedef FeatureEncoder * FeatureEncoderPtr
typedef FeatureFileIOC45::FeatureFileIOC45Ptr FeatureFileIOC45Ptr
typedef FeatureFileIO * FeatureFileIOPtr
typedef FeatureNumList const FeatureNumListConst
typedef FeatureNumListConst * FeatureNumListConstPtr
typedef FeatureNumList * FeatureNumListPtr
typedef FeatureVectorList * FeatureVectorListPtr
typedef FeatureVectorProducer * FeatureVectorProducerPtr
typedef FeatureVector * FeatureVectorPtr
typedef FeWhatToDo * FeWhatToDoPtr
typedef FileDesc::FileDescConstPtr FileDescConstPtr
typedef FileDescList * FileDescListPtr
typedef FileDesc * FileDescPtr
typedef std::vector< float > Fvector
typedef GrayScaleImagesFVList::GrayScaleImagesFVListPtr GrayScaleImagesFVListPtr
typedef GrayScaleImagesFVProducer * GrayScaleImagesFVProducerPtr
typedef GrayScaleImagesFV::GrayScaleImagesFVPtr GrayScaleImagesFVPtr
typedef ImageFeaturesDataIndexed * ImageFeaturesDataIndexedPtr
typedef ImageFeaturesNameIndexed * ImageFeaturesNameIndexedPtr
typedef std::vector< kkint32 > Ivector
typedef MLClassIndexList::MLClassIndexListPtr MLClassIndexListPtr
typedef MLClassList * MLClassListPtr
typedef MLClass * MLClassPtr
typedef ModelDual::ModelDualPtr ModelDualPtr
typedef ModelKnn::ModelKnnPtr ModelKnnPtr
typedef ModelOldSVM::ModelOldSVMPtr ModelOldSVMPtr
typedef ModelParamDual * ModelParamDualPtr
typedef ModelParamKnn::ModelParamKnnPtr ModelParamKnnPtr
typedef ModelParamOldSVM * ModelParamOldSVMPtr
typedef ModelParam::ModelParamPtr ModelParamPtr
typedef ModelParamSvmBase::ModelParamSvmBasePtr ModelParamSvmBasePtr
typedef ModelParamUsfCasCor * ModelParamUsfCasCorPtr
typedef Model::ModelPtr ModelPtr
typedef ModelSvmBase::ModelSvmBasePtr ModelSvmBasePtr
typedef ModelUsfCasCor::ModelUsfCasCorPtr ModelUsfCasCorPtr
typedef NormalizationParms * NormalizationParmsPtr
typedef Orderings * OrderingsPtr
typedef RunLog * RunLogPtr
typedef SizeDistribution * SizeDistributionPtr
typedef SVMModel * SVMModelPtr
typedef SVMparam * SVMparamPtr
typedef TrainingClassList * TrainingClassListPtr
typedef TrainingClass * TrainingClassPtr
typedef TrainingConfiguration2::TrainingConfiguration2Const TrainingConfiguration2Const
typedef TrainingConfiguration2::TrainingConfiguration2ConstPtr TrainingConfiguration2ConstPtr
typedef TrainingConfiguration2List * TrainingConfiguration2ListPtr
typedef TrainingConfiguration2 * TrainingConfiguration2Ptr
typedef TrainingProcess2List * TrainingProcess2ListPtr
typedef TrainingProcess2 * TrainingProcess2Ptr
typedef XmlElementTemplate< Attribute > XmlElementAttribute
typedef XmlElementTemplate< AttributeList > XmlElementAttributeList
typedef XmlElementAttributeList * XmlElementAttributeListPtr
typedef XmlElementAttribute * XmlElementAttributePtr
typedef XmlElementTemplate< AttributeTypeVector > XmlElementAttributeTypeVector
typedef XmlElementAttributeTypeVector * XmlElementAttributeTypeVectorPtr
typedef XmlElementTemplate< BinaryClassParmsList > XmlElementBinaryClassParmsList
typedef XmlElementBinaryClassParmsList * XmlElementBinaryClassParmsListPtr
typedef XmlElementTemplate< ClassProbList > XmlElementClassProbList
typedef XmlElementClassProbList * XmlElementClassProbListPtr
typedef XmlElementTemplate< FeatureNumList > XmlElementFeatureNumList
typedef XmlElementFeatureNumList * XmlElementFeatureNumListPtr
typedef XmlElementFileDesc * XmlElementFileDescPtr
typedef XmlElementTemplate< MLClassIndexList > XmlElementMLClassIndexList
typedef XmlElementMLClassIndexList * XmlElementMLClassIndexListPtr
typedef XmlElementMLClassNameList * XmlElementMLClassNameListPtr
typedef XmlElementMLClass * XmlElementMLClassPtr
typedef XmlElementModelTemplate< ModelDual > XmlElementModelDual
typedef XmlElementModelDual * XmlElementModelDualPtr
typedef XmlElementModelTemplate< ModelKnn > XmlElementModelKnn
typedef XmlElementModelKnn * XmlElementModelKnnPtr
typedef XmlElementModelTemplate< ModelOldSVM > XmlElementModelOldSVM
typedef XmlElementModelOldSVM * XmlElementModelOldSVMPtr
typedef XmlElementModelParamTemplate< ModelParamDual > XmlElementModelParamDual
typedef XmlElementModelParamDual * XmlElementModelParamDualPtr
typedef XmlElementModelParamTemplate< ModelParamKnn > XmlElementModelParamKnn
typedef XmlElementModelParamKnn * XmlElementModelParamKnnPtr
typedef XmlElementModelParamTemplate< ModelParamOldSVM > XmlElementModelParamOldSVM
typedef XmlElementModelParamOldSVM * XmlElementModelParamOldSVMPtr
typedef XmlElementModelParam * XmlElementModelParamPtr
typedef XmlElementModelParamTemplate< ModelParamSvmBase > XmlElementModelParamSvmBase
typedef XmlElementModelParamSvmBase * XmlElementModelParamSvmBasePtr
typedef XmlElementModelParamTemplate< ModelParamUsfCasCor > XmlElementModelParamUsfCasCor
typedef XmlElementModelParamUsfCasCor * XmlElementModelParamUsfCasCorPtr
typedef XmlElementModel * XmlElementModelPtr
typedef XmlElementModelTemplate< ModelSvmBase > XmlElementModelSvmBase
typedef XmlElementModelSvmBase * XmlElementModelSvmBasePtr
typedef XmlElementModelTemplate< ModelUsfCasCor > XmlElementModelUsfCasCor
typedef XmlElementModelUsfCasCor * XmlElementModelUsfCasCorPtr
typedef XmlElementTemplate< NormalizationParms > XmlElementNormalizationParms
typedef XmlElementNormalizationParms * XmlElementNormalizationParmsPtr
typedef XmlElementTemplate< SVMModel > XmlElementSVMModel
typedef XmlElementSVMModel * XmlElementSVMModelPtr
typedef XmlElementTemplate< SVMparam > XmlElementSVMparam
typedef XmlElementSVMparam * XmlElementSVMparamPtr
typedef XmlElementTemplate< TrainingClass > XmlElementTrainingClass
typedef XmlElementTemplate< TrainingClassList > XmlElementTrainingClassList
typedef XmlElementTrainingClassList * XmlElementTrainingClassListPtr
typedef XmlElementTrainingClass * XmlElementTrainingClassPtr
typedef XmlElementTemplate< TrainingConfiguration2 > XmlElementTrainingConfiguration2
typedef XmlElementTrainingConfiguration2 * XmlElementTrainingConfiguration2Ptr
typedef XmlElementTemplate< TrainingProcess2 > XmlElementTrainingProcess2
typedef XmlElementTrainingProcess2 * XmlElementTrainingProcess2Ptr
typedef struct svm_node * XSpacePtr
Enumerations
enum AttributeType : int {
*
AttributeType::NULLAttribute,
AttributeType::Ignore,
AttributeType::Numeric,
AttributeType::Nominal,
*
AttributeType::Ordinal,
AttributeType::Symbolic
 }
enum FeWhatToDo { FeWhatToDo::FeAsIs,
FeWhatToDo::FeBinary,
FeWhatToDo::FeScale
 }
enum LearnType {
*
LearnType::NORMAL,
LearnType::BAGGING,
LearnType::BOOSTING,
LearnType::SUBSPACE,
*
LearnType::SAMPLESV
 }
enum SVM_EncodingMethod : int { SVM_EncodingMethod::Null,
SVM_EncodingMethod::NoEncoding,
SVM_EncodingMethod::Binary,
SVM_EncodingMethod::Scaled
 }
enum SVM_KernalType : int { SVM_KernalType::Null,
SVM_KernalType::Linear,
SVM_KernalType::Polynomial,
SVM_KernalType::RBF
 }
enum SVM_MachineType : int {
*
SVM_MachineType::Null,
SVM_MachineType::OneVsOne,
SVM_MachineType::OneVsAll,
SVM_MachineType::BinaryCombos,
*
SVM_MachineType::BoostSVM
 }
enum SVM_SelectionMethod : int { SVM_SelectionMethod::Null,
SVM_SelectionMethod::Voting,
SVM_SelectionMethod::Probability
 }
Functions
AttributeType AttributeTypeFromStr (const KKStr &s)
const KKStr & AttributeTypeToStr (AttributeType type)
void EncodeProblem (const struct svm_paramater &param, struct svm_problem &prob_in, struct svm_problem &prob_out)
SVM_EncodingMethod EncodingMethodFromStr (const KKStr &encodingMethodStr)
KKStr EncodingMethodToStr (SVM_EncodingMethod encodingMethod)
SVM_KernalType KernalTypeFromStr (const KKStr &kernalTypeStr)
KKStr KernalTypeToStr (SVM_KernalType kernalType)
SVM_MachineType MachineTypeFromStr (const KKStr &machineTypeStr)
KKStr MachineTypeToStr (SVM_MachineType machineType)
AttributeType operator++ (AttributeType zed)
std::ostream & operator<< (std::ostream &os, const FeatureNumList &features)
std::ostream & operator<< (std::ostream &os, const MLClassList &classList)
KKStr & operator<< (KKStr &str, const MLClassList &classList)
KKStr & operator<< (KKStr &left, TrainingConfiguration2::ModelTypes modelingMethod)
std::ostream & operator<< (std::ostream &os, TrainingConfiguration2::ModelTypes modelingMethod)
ostream & operator<< (ostream &os, const FeatureNumList &features)
bool PairCompareOperator (ProbNamePair l, ProbNamePair r)
SVM_SelectionMethod SelectionMethodFromStr (const KKStr &selectionMethodStr)
KKStr SelectionMethodToStr (SVM_SelectionMethod selectionMethod)
void SvmDestroyModel (struct SvmModel233 **subModel)
struct SvmModel233 ** SvmLoadModel (istream &f, RunLog &log)
void SvmPredictClass (SVMparam &svmParam, struct SvmModel233 **subModel, const struct svm_node *unknownClassFeatureData, kkint32 *votes, double *probabilities, kkint32 knownClass, kkint32 &predClass1, kkint32 &predClass2, kkint32 &predClass1Votes, kkint32 &predClass2Votes, double &predClass1Prob, double &predClass2Prob, double &probOfKnownClass, Ivector &winners, double **crossClassProbTable, double &breakTie)
void SvmPredictRaw (SvmModel233 **submodel, const svm_node *unKnownData, double &label, double &dist)
kkint32 SvmPredictTwoClass (const struct svm_parameter &param, SvmModel233 **submodel, const svm_node *unKnownData, kkint32 desired, double &dist, double &probability, kkint32 excludeSupportVectorIDX)
void SvmSaveModel (ostream &o, struct SvmModel233 **model)
struct SvmModel233 ** SvmTrainModel (const struct svm_parameter &param, struct svm_problem &subprob)
Variables
const char * FeatureDecriptions []
MLClassList globalClassList
Detailed Description
Namespace for all K^2 Machine Learning code.
This library provides data structures that support Machine Learning functionality.
A library of routines used for Machine Learning, building Classifiers, etc.
`Machine Learning Code`
`Feature Data`
There are several Feature Data formats supported. Each one has its own class that is derived from 'FeatureFileIO'. The description of the data is managed by 'FileDesc'. For each type of dataset there will exist on one instance of a FileDesc class.
See also
Attribute
FeatureNumList
FeatureFileIO
FeatureVector
FeatureVectorList
MLClass
BitReduction
FeatureEncoder
NormalizationParms
Orderings
`Learning Algorithms`
There are several learning algorithms implemented. The Learning algorithms are all sub-classed from 'Model' and their related parameters are all sub-classed from 'ModelParam'.
See also
Model
ModelKnn
ModelOldSVM
ModelSvmBase
ModelParam
TrainingClass
TrainingProcess2
`Analysis Routines`
See also
ConfusionMatrix2
CrossValidation
CrossValidationMxN
CrossValidationVoting
SizeDistribution
Author
Kurt Kramer * Date: 2009-04-16 *
There are several classes defined in this library but the central ones that should be understood are MLClass, FeatureVector, Model, FileDesc, and Attribute. there is support for reading and writing several feature Data file formats C45 probably being the most well known.
Typedef Documentation
typedef AttributeList const* KKMLL::AttributeListConstPtr
Definition at line 214 of file Attribute.h.
typedef AttributeList* KKMLL::AttributeListPtr
Definition at line 212 of file Attribute.h.
typedef Attribute* KKMLL::AttributePtr
Definition at line 156 of file Attribute.h.
typedef AttributeTypeVector* KKMLL::AttributeTypeVectorPtr
Definition at line 72 of file Attribute.h.
typedef BinaryClassParmsList * KKMLL::BinaryClassParmsListPtr
Definition at line 220 of file BinaryClassParms.h.
typedef BinaryClassParms * KKMLL::BinaryClassParmsPtr
Definition at line 120 of file BinaryClassParms.h.
typedef ClassAssignments * KKMLL::ClassAssignmentsPtr
Definition at line 90 of file ClassAssignments.h.
typedef ClassificationBiasMatrix::ClassificationBiasMatrixPtr KKMLL::ClassificationBiasMatrixPtr
Definition at line 148 of file ClassificationBiasMatrix.h.
typedef Classifier2List * KKMLL::Classifier2ListPtr
Definition at line 72 of file Classifier2.h.
typedef Classifier2 * KKMLL::Classifier2Ptr
Definition at line 284 of file Classifier2.h.
typedef ClassProbList::ClassProbListPtr KKMLL::ClassProbListPtr
Definition at line 30 of file Classifier2.h.
typedef ClassProb * KKMLL::ClassProbPtr
Definition at line 28 of file Classifier2.h.
typedef ClassStatisticList* KKMLL::ClassStatisticListPtr
Definition at line 67 of file ClassStatistic.h.
typedef ClassStatistic* KKMLL::ClassStatisticPtr
Definition at line 38 of file ClassStatistic.h.
typedef ConfusionMatrix2 * KKMLL::ConfusionMatrix2Ptr
Definition at line 326 of file ConfusionMatrix2.h.
typedef ConfussionMatrix2List* KKMLL::ConfussionMatrix2ListPtr
Definition at line 343 of file ConfusionMatrix2.h.
typedef CrossValidation * KKMLL::CrossValidationPtr
Definition at line 213 of file CrossValidation.h.
typedef CrossValidationVoting* KKMLL::CrossValidationVotingPtr
Definition at line 120 of file CrossValidationVoting.h.
typedef DuplicateImageList * KKMLL::DuplicateImageListPtr
Definition at line 25 of file DuplicateImages.h.
typedef DuplicateImage * KKMLL::DuplicateImagePtr
Definition at line 28 of file DuplicateImages.h.
typedef DuplicateImages* KKMLL::DuplicateImagesPtr
Definition at line 119 of file DuplicateImages.h.
typedef std::vector<double> KKMLL::Dvector
Definition at line 20 of file SvmWrapper.h.
typedef FactoryFVProducer * KKMLL::FactoryFVProducerPtr
Definition at line 75 of file Model.h.
typedef FeatureEncoder2::FeatureEncoder2Ptr KKMLL::FeatureEncoder2Ptr
Definition at line 30 of file Model.h.
typedef FeatureEncoder * KKMLL::FeatureEncoderPtr
Definition at line 37 of file SVMModel.h.
typedef FeatureFileIOC45::FeatureFileIOC45Ptr KKMLL::FeatureFileIOC45Ptr
Definition at line 113 of file FeatureFileIOC45.h.
typedef FeatureFileIO * KKMLL::FeatureFileIOPtr
Definition at line 45 of file FileDesc.h.
typedef FeatureNumList const KKMLL::FeatureNumListConst
Definition at line 253 of file FeatureNumList.h.
typedef FeatureNumListConst * KKMLL::FeatureNumListConstPtr
Definition at line 254 of file FeatureNumList.h.
typedef FeatureNumList * KKMLL::FeatureNumListPtr
Definition at line 51 of file FeatureNumList.h.
typedef FeatureVectorList * KKMLL::FeatureVectorListPtr
Definition at line 46 of file Model.h.
typedef FeatureVectorProducer::FeatureVectorProducerPtr KKMLL::FeatureVectorProducerPtr
Definition at line 24 of file FactoryFVProducer.h.
typedef FeatureVector * KKMLL::FeatureVectorPtr
Definition at line 44 of file Model.h.
typedef FeWhatToDo* KKMLL::FeWhatToDoPtr
Definition at line 41 of file FeatureEncoder.h.
typedef FileDesc *const KKMLL::FileDescConstPtr
Definition at line 307 of file FileDesc.h.
typedef FileDescList * KKMLL::FileDescListPtr
Definition at line 41 of file FileDesc.h.
typedef FileDesc * KKMLL::FileDescPtr
Definition at line 46 of file FeatureNumList.h.
typedef std::vector<float> KKMLL::Fvector
Definition at line 19 of file SvmWrapper.h.
typedef GrayScaleImagesFVList::GrayScaleImagesFVListPtr KKMLL::GrayScaleImagesFVListPtr
Definition at line 459 of file GrayScaleImagesFV.h.
typedef GrayScaleImagesFVProducer* KKMLL::GrayScaleImagesFVProducerPtr
Definition at line 160 of file GrayScaleImagesFVProducer.h.
typedef GrayScaleImagesFV::GrayScaleImagesFVPtr KKMLL::GrayScaleImagesFVPtr
Definition at line 106 of file GrayScaleImagesFV.h.
typedef ImageFeaturesDataIndexed * KKMLL::ImageFeaturesDataIndexedPtr
Definition at line 33 of file DuplicateImages.h.
typedef ImageFeaturesNameIndexed * KKMLL::ImageFeaturesNameIndexedPtr
Definition at line 46 of file DuplicateImages.h.
typedef std::vector<kkint32> KKMLL::Ivector
Definition at line 18 of file SvmWrapper.h.
typedef MLClassIndexList * KKMLL::MLClassIndexListPtr
Definition at line 534 of file MLClass.h.
typedef MLClassList * KKMLL::MLClassListPtr
Definition at line 49 of file MLClass.h.
typedef MLClass * KKMLL::MLClassPtr
Definition at line 46 of file MLClass.h.
typedef ModelDual::ModelDualPtr KKMLL::ModelDualPtr
Definition at line 233 of file ModelDual.h.
typedef ModelKnn::ModelKnnPtr KKMLL::ModelKnnPtr
Definition at line 120 of file ModelKnn.h.
typedef ModelOldSVM * KKMLL::ModelOldSVMPtr
Definition at line 266 of file ModelOldSVM.h.
typedef ModelParamDual::ModelParamDualPtr KKMLL::ModelParamDualPtr
Definition at line 56 of file ModelDual.h.
typedef ModelParamKnn::ModelParamKnnPtr KKMLL::ModelParamKnnPtr
Definition at line 66 of file ModelParamKnn.h.
typedef ModelParamOldSVM * KKMLL::ModelParamOldSVMPtr
Definition at line 24 of file ModelOldSVM.h.
typedef ModelParam * KKMLL::ModelParamPtr
Definition at line 201 of file ModelParam.h.
typedef ModelParamSvmBase::ModelParamSvmBasePtr KKMLL::ModelParamSvmBasePtr
Definition at line 85 of file ModelParamSvmBase.h.
typedef ModelParamUsfCasCor* KKMLL::ModelParamUsfCasCorPtr
Definition at line 91 of file ModelParamUsfCasCor.h.
typedef Model::ModelPtr KKMLL::ModelPtr
Definition at line 443 of file Model.h.
typedef ModelSvmBase::ModelSvmBasePtr KKMLL::ModelSvmBasePtr
Definition at line 147 of file ModelSvmBase.h.
typedef ModelUsfCasCor::ModelUsfCasCorPtr KKMLL::ModelUsfCasCorPtr
Definition at line 141 of file ModelUsfCasCor.h.
typedef NormalizationParms * KKMLL::NormalizationParmsPtr
Definition at line 68 of file Model.h.
typedef Orderings::OrderingsPtr KKMLL::OrderingsPtr
Definition at line 58 of file CrossValidationMxN.h.
typedef RunLog * KKMLL::RunLogPtr
Definition at line 44 of file SVMModel.h.
typedef SizeDistribution* KKMLL::SizeDistributionPtr
Definition at line 77 of file SizeDistribution.h.
typedef SVMModel* KKMLL::SVMModelPtr
Definition at line 557 of file SVMModel.h.
typedef SVMparam* KKMLL::SVMparamPtr
Definition at line 286 of file SVMparam.h.
typedef TrainingClassList* KKMLL::TrainingClassListPtr
Definition at line 188 of file TrainingClass.h.
typedef TrainingClass* KKMLL::TrainingClassPtr
Definition at line 139 of file TrainingClass.h.
typedef TrainingConfiguration2::TrainingConfiguration2Const KKMLL::TrainingConfiguration2Const
Definition at line 552 of file TrainingConfiguration2.h.
typedef TrainingConfiguration2::TrainingConfiguration2ConstPtr KKMLL::TrainingConfiguration2ConstPtr
Definition at line 553 of file TrainingConfiguration2.h.
typedef TrainingConfiguration2List * KKMLL::TrainingConfiguration2ListPtr
Definition at line 50 of file TrainingConfiguration2.h.
typedef TrainingConfiguration2 * KKMLL::TrainingConfiguration2Ptr
Definition at line 56 of file Classifier2.h.
typedef TrainingProcess2List * KKMLL::TrainingProcess2ListPtr
summary>Manages the creation and loading of training models.
remarks> A trained model can either be built from scratch using specified training data or a persistent instance can be loaded from a XMLStream. There are several static methods that are best used to manage the various situations such as "CreateTrainingProcess", "CreateTrainingProcessForLevel", "CreateTrainingProcessFromTrainingExamples", "LoadExistingTrainingProcess". The result of any of these methods is a TrainigProcess2 instance that you use to create a Classifier instance.
Supporting Classes:
TrainingConfiguration2 Manages defines the parameters of a classifier such as:
Type of algorithm
List Classes of and where training examples can be loaded from.
Sub-Classifiers that is for any given class another "TrainingConfiguration2" can be specified indicating another classifier to be used when that class is predicted.
Class Weights
Model Base class for all algorithms. SupportVectorMachine(SVM), USFCasCor, BFS-SVM, etc ....
Classifier2 You construct an instance from a 'TrainingProcess2' instance; this is the class that manages predictions.
Sub-Classifiers: For each sub-classifiers specified in the "TrainingConfiguration2" another instance of "TrainingProcess2" will be created. Data member "subTrainingProcesses" will keep a list of these "TrainingProcess2" instances. /remarks>
Definition at line 68 of file Classifier2.h.
typedef TrainingProcess2 * KKMLL::TrainingProcess2Ptr
Definition at line 62 of file Classifier2.h.
typedef XmlElementTemplate<Attribute> KKMLL::XmlElementAttribute
Definition at line 226 of file Attribute.h.
typedef XmlElementTemplate<AttributeList> KKMLL::XmlElementAttributeList
Definition at line 230 of file Attribute.h.
typedef XmlElementAttributeList* KKMLL::XmlElementAttributeListPtr
Definition at line 231 of file Attribute.h.
typedef XmlElementAttribute* KKMLL::XmlElementAttributePtr
Definition at line 227 of file Attribute.h.
typedef XmlElementTemplate<AttributeTypeVector> KKMLL::XmlElementAttributeTypeVector
Definition at line 222 of file Attribute.h.
typedef XmlElementAttributeTypeVector* KKMLL::XmlElementAttributeTypeVectorPtr
Definition at line 223 of file Attribute.h.
typedef XmlElementTemplate<BinaryClassParmsList> KKMLL::XmlElementBinaryClassParmsList
Definition at line 222 of file BinaryClassParms.h.
typedef XmlElementBinaryClassParmsList* KKMLL::XmlElementBinaryClassParmsListPtr
Definition at line 223 of file BinaryClassParms.h.
typedef XmlElementTemplate<ClassProbList> KKMLL::XmlElementClassProbList
Definition at line 146 of file ClassProb.h.
typedef XmlElementClassProbList* KKMLL::XmlElementClassProbListPtr
Definition at line 147 of file ClassProb.h.
typedef XmlElementTemplate<FeatureNumList> KKMLL::XmlElementFeatureNumList
Definition at line 263 of file FeatureNumList.h.
typedef XmlElementFeatureNumList* KKMLL::XmlElementFeatureNumListPtr
Definition at line 264 of file FeatureNumList.h.
typedef XmlElementFileDesc* KKMLL::XmlElementFileDescPtr
Definition at line 337 of file FileDesc.h.
typedef XmlElementTemplate<MLClassIndexList> KKMLL::XmlElementMLClassIndexList
Definition at line 606 of file MLClass.h.
typedef XmlElementMLClassIndexList* KKMLL::XmlElementMLClassIndexListPtr
Definition at line 607 of file MLClass.h.
typedef XmlElementMLClassNameList* KKMLL::XmlElementMLClassNameListPtr
Definition at line 603 of file MLClass.h.
typedef XmlElementMLClass* KKMLL::XmlElementMLClassPtr
Definition at line 572 of file MLClass.h.
typedef XmlElementModelTemplate<ModelDual> KKMLL::XmlElementModelDual
Definition at line 236 of file ModelDual.h.
typedef XmlElementModelDual* KKMLL::XmlElementModelDualPtr
Definition at line 237 of file ModelDual.h.
typedef XmlElementModelTemplate<ModelKnn> KKMLL::XmlElementModelKnn
Definition at line 123 of file ModelKnn.h.
typedef XmlElementModelKnn* KKMLL::XmlElementModelKnnPtr
Definition at line 124 of file ModelKnn.h.
typedef XmlElementModelTemplate<ModelOldSVM> KKMLL::XmlElementModelOldSVM
Definition at line 269 of file ModelOldSVM.h.
typedef XmlElementModelOldSVM* KKMLL::XmlElementModelOldSVMPtr
Definition at line 270 of file ModelOldSVM.h.
typedef XmlElementModelParamTemplate<ModelParamDual> KKMLL::XmlElementModelParamDual
Definition at line 104 of file ModelParamDual.h.
typedef XmlElementModelParamDual* KKMLL::XmlElementModelParamDualPtr
Definition at line 105 of file ModelParamDual.h.
typedef XmlElementModelParamTemplate<ModelParamKnn> KKMLL::XmlElementModelParamKnn
Definition at line 68 of file ModelParamKnn.h.
typedef XmlElementModelParamKnn* KKMLL::XmlElementModelParamKnnPtr
Definition at line 69 of file ModelParamKnn.h.
typedef XmlElementModelParamTemplate<ModelParamOldSVM> KKMLL::XmlElementModelParamOldSVM
Definition at line 185 of file ModelParamOldSVM.h.
typedef XmlElementModelParamOldSVM* KKMLL::XmlElementModelParamOldSVMPtr
Definition at line 186 of file ModelParamOldSVM.h.
typedef XmlElementModelParam* KKMLL::XmlElementModelParamPtr
Definition at line 248 of file ModelParam.h.
typedef XmlElementModelParamTemplate<ModelParamSvmBase> KKMLL::XmlElementModelParamSvmBase
Definition at line 87 of file ModelParamSvmBase.h.
typedef XmlElementModelParamSvmBase* KKMLL::XmlElementModelParamSvmBasePtr
Definition at line 88 of file ModelParamSvmBase.h.
typedef XmlElementModelParamTemplate<ModelParamUsfCasCor> KKMLL::XmlElementModelParamUsfCasCor
Definition at line 93 of file ModelParamUsfCasCor.h.
typedef XmlElementModelParamUsfCasCor* KKMLL::XmlElementModelParamUsfCasCorPtr
Definition at line 94 of file ModelParamUsfCasCor.h.
typedef XmlElementModel* KKMLL::XmlElementModelPtr
Definition at line 480 of file Model.h.
typedef XmlElementModelTemplate<ModelSvmBase> KKMLL::XmlElementModelSvmBase
Definition at line 150 of file ModelSvmBase.h.
typedef XmlElementModelSvmBase* KKMLL::XmlElementModelSvmBasePtr
Definition at line 151 of file ModelSvmBase.h.
typedef XmlElementModelTemplate<ModelUsfCasCor> KKMLL::XmlElementModelUsfCasCor
Definition at line 146 of file ModelUsfCasCor.h.
typedef XmlElementModelUsfCasCor* KKMLL::XmlElementModelUsfCasCorPtr
Definition at line 147 of file ModelUsfCasCor.h.
typedef XmlElementTemplate<NormalizationParms> KKMLL::XmlElementNormalizationParms
Definition at line 155 of file NormalizationParms.h.
typedef XmlElementNormalizationParms* KKMLL::XmlElementNormalizationParmsPtr
Definition at line 156 of file NormalizationParms.h.
typedef XmlElementTemplate<SVMModel> KKMLL::XmlElementSVMModel
Definition at line 561 of file SVMModel.h.
typedef XmlElementSVMModel* KKMLL::XmlElementSVMModelPtr
Definition at line 562 of file SVMModel.h.
typedef XmlElementTemplate<SVMparam> KKMLL::XmlElementSVMparam
Definition at line 302 of file SVMparam.h.
typedef XmlElementSVMparam* KKMLL::XmlElementSVMparamPtr
Definition at line 303 of file SVMparam.h.
typedef XmlElementTemplate<TrainingClass> KKMLL::XmlElementTrainingClass
Definition at line 192 of file TrainingClass.h.
typedef XmlElementTemplate<TrainingClassList> KKMLL::XmlElementTrainingClassList
Definition at line 196 of file TrainingClass.h.
typedef XmlElementTrainingClassList* KKMLL::XmlElementTrainingClassListPtr
Definition at line 197 of file TrainingClass.h.
typedef XmlElementTrainingClass* KKMLL::XmlElementTrainingClassPtr
Definition at line 193 of file TrainingClass.h.
typedef XmlElementTemplate<TrainingConfiguration2> KKMLL::XmlElementTrainingConfiguration2
Definition at line 587 of file TrainingConfiguration2.h.
typedef XmlElementTrainingConfiguration2* KKMLL::XmlElementTrainingConfiguration2Ptr
Definition at line 588 of file TrainingConfiguration2.h.
typedef XmlElementTemplate<TrainingProcess2> KKMLL::XmlElementTrainingProcess2
Definition at line 426 of file TrainingProcess2.h.
typedef XmlElementTrainingProcess2* KKMLL::XmlElementTrainingProcess2Ptr
Definition at line 427 of file TrainingProcess2.h.
typedef struct svm_node * KKMLL::XSpacePtr
Definition at line 58 of file SVMModel.h.
Enumeration Type Documentation
enum KKMLL::AttributeType : int [strong]
Enumerator
NULLAttribute
Ignore
Numeric
Nominal
Ordinal
Symbolic
 Same as Nominal, except the names file does not list all possible values. They have to be determined from the data file.
Definition at line 36 of file Attribute.h.
                            : int
  {
    NULLAttribute,
    Ignore,
    Numeric,
    Nominal,
    Ordinal,
    Symbolic /**< Same as Nominal, except the names file does not
                 * list all possible values. They have to be determined from
                 * the data file.
                 */
  };
enum KKMLL::FeWhatToDo [strong]
Enumerator
FeAsIs
FeBinary
FeScale
Definition at line 39 of file FeatureEncoder.h.
{FeAsIs, FeBinary, FeScale};
enum KKMLL::LearnType [strong]
Enumerator
NORMAL
BAGGING
BOOSTING
SUBSPACE
SAMPLESV
Definition at line 9 of file SvmWrapper.h.
  {
    NORMAL,
    BAGGING,
    BOOSTING,
    SUBSPACE,
    SAMPLESV
  };
enum KKMLL::SVM_EncodingMethod : int [strong]
Enumerator
Null
NoEncoding
Binary
Scaled
Definition at line 46 of file SVMparam.h.
                                 : int
                 {Null,
                  NoEncoding,
                  Binary,
                  Scaled
                 };
enum KKMLL::SVM_KernalType : int [strong]
Enumerator
Null
Linear
Polynomial
RBF
Definition at line 54 of file SVMparam.h.
                             : int
                 {Null,
                  Linear,
                  Polynomial,
                  RBF
                 };
enum KKMLL::SVM_MachineType : int [strong]
Enumerator
Null
OneVsOne
OneVsAll
BinaryCombos
BoostSVM
Definition at line 26 of file SVMparam.h.
                             : int
                 {Null,
                  OneVsOne,
                  OneVsAll,
                  BinaryCombos,
                  BoostSVM
                 };
enum KKMLL::SVM_SelectionMethod : int [strong]
Enumerator
Null
Voting
Probability
Definition at line 34 of file SVMparam.h.
                                 : int
                 {Null,
                  Voting,
                  Probability
                 };
Function Documentation
AttributeType KKMLL::AttributeTypeFromStr (const KKStr & s)
Definition at line 442 of file Attribute.cpp.
References KKB::KKStr::EqualIgnoreCase(), Ignore, Nominal, NULLAttribute, Numeric, Ordinal, and Symbolic.
Referenced by KKMLL::Attribute::ReadXML().
{
  if (s.EqualIgnoreCase ("Ignore"))
    return AttributeType::Ignore;
  else if (s.EqualIgnoreCase ("Numeric"))
    return AttributeType::Numeric;
  else if (s.EqualIgnoreCase ("Nominal"))
    return AttributeType::Nominal;
  else if (s.EqualIgnoreCase ("Ordinal"))
    return AttributeType::Ordinal;
  else if (s.EqualIgnoreCase ("Symbolic"))
    return AttributeType::Symbolic;
  else
    return AttributeType::NULLAttribute;
}
const KKStr & KKMLL::AttributeTypeToStr (AttributeType type)
Definition at line 422 of file Attribute.cpp.
Referenced by KKMLL::FeatureVectorList::FeatureTypeStr(), and KKMLL::Attribute::TypeStr().
{
  static vector<KKStr> AttributeTypeStrings =
    {
      "Null",
      "Ignore",
      "Numeric",
      "Nominal",
      "Ordinal"
    };
  if ((type < (AttributeType)0) || ((kkuint32)type >= AttributeTypeStrings.size ())
      )
    return KKStr::EmptyStr ();
  return AttributeTypeStrings[(int)type];
} /* TypeStr */
void KKMLL::EncodeProblem (const struct svm_paramater & param, struct svm_problem & prob_in, struct svm_problem & prob_out)
Referenced by KKMLL::GrayScaleImagesFVProducer::DefineFileDescStatic(), and KKMLL::Attribute::WriteXML().
SVM_EncodingMethod KKMLL::EncodingMethodFromStr (const KKStr & encodingMethodStr)
Definition at line 899 of file SVMparam.cpp.
References Binary, KKB::KKStr::Concat(), NoEncoding, Null, KKB::KKStr::operator==(), Scaled, and KKB::KKStr::ToUpper().
Referenced by KKMLL::SVMparam::ParseCmdLineParameter(), and KKMLL::FeatureEncoder::ReadXML().
{
  KKStr encodingMethodUpper = encodingMethodStr.ToUpper ();
  if ((encodingMethodUpper == "BINARY") || (encodingMethodUpper == "BIN"))
     return SVM_EncodingMethod::Binary;
  if (encodingMethodUpper == "SCALE")
     return SVM_EncodingMethod::Scaled;
  if (encodingMethodUpper == "NONE")
    return SVM_EncodingMethod::NoEncoding;
  return SVM_EncodingMethod::Null;
} /* EncodingMethodFromStr */
KKStr KKMLL::EncodingMethodToStr (SVM_EncodingMethod encodingMethod)
Referenced by KKMLL::SVMparam::ToString(), KKMLL::FeatureEncoder::WriteXML(), and KKMLL::SVMparam::WriteXML().
SVM_KernalType KKMLL::KernalTypeFromStr (const KKStr & kernalTypeStr)
Definition at line 932 of file SVMparam.cpp.
References KKB::KKStr::Concat(), Linear, KKB::KKStr::operator==(), Polynomial, RBF, and KKB::KKStr::Upper().
{
  KKStr kernalTypeUpper = kernalTypeStr;
  kernalTypeUpper.Upper ();
  if ((kernalTypeUpper == "LINEAR") ||
       (kernalTypeUpper == "LIN") ||
       (kernalTypeUpper == "L")
      )
    return SVM_KernalType::Linear;
  if ((kernalTypeUpper == "POLYNOMIAL") ||
       (kernalTypeUpper == "POLY") ||
       (kernalTypeUpper == "P") ||
       (kernalTypeUpper == "PN")
       )
    return SVM_KernalType::Polynomial;
  
  if ((kernalTypeUpper == "RBF") ||
       (kernalTypeUpper == "R") ||
       (kernalTypeUpper == "RADIALBASIS") ||
       (kernalTypeUpper == "RADIALBASISFUNC") ||
       (kernalTypeUpper == "RADIALBASISFUNCTION")
      )
    return SVM_KernalType::RBF;
  return SVM_KernalType::Linear;
} /* KernalTypeToStr */
KKStr KKMLL::KernalTypeToStr (SVM_KernalType kernalType)
Definition at line 917 of file SVMparam.cpp.
References Linear, Polynomial, and RBF.
{
  switch (kernalType)
  {
  case SVM_KernalType::Linear: return "Linear";
  case SVM_KernalType::Polynomial: return "Polynomial";
  case SVM_KernalType::RBF: return "RBF";
  default: return "UnKnown";
  }
  return "";
} /* KernalTypeToStr */
SVM_MachineType KKMLL::MachineTypeFromStr (const KKStr & machineTypeStr)
Definition at line 986 of file SVMparam.cpp.
References BinaryCombos, BoostSVM, KKB::KKStr::Concat(), Null, OneVsAll, OneVsOne, KKB::KKStr::operator==(), and KKB::KKStr::ToUpper().
Referenced by KKMLL::SVMparam::ParseCmdLineParameter().
{
  KKStr machineTypeUpper = machineTypeStr.ToUpper ();
  if (machineTypeUpper == "ONEVSONE")
    return SVM_MachineType::OneVsOne;
  else if (machineTypeUpper == "ONEVSALL")
    return SVM_MachineType::OneVsAll;
  else if (machineTypeUpper == "BINARY")
    return SVM_MachineType::BinaryCombos;
  else if (machineTypeUpper == "BOOSTSVM")
    return SVM_MachineType::BoostSVM;
  return SVM_MachineType::Null;
} /* MachineTypeFromStr */
KKStr KKMLL::MachineTypeToStr (SVM_MachineType machineType)
Definition at line 965 of file SVMparam.cpp.
References BinaryCombos, BoostSVM, OneVsAll, and OneVsOne.
Referenced by KKMLL::ModelOldSVM::Description(), KKMLL::SVMparam::ToString(), and KKMLL::SVMparam::WriteXML().
{
  if (machineType == SVM_MachineType::OneVsOne)
    return "OneVsOne";
  else if (machineType == SVM_MachineType::OneVsAll)
    return "OneVsAll";
  else if (machineType == SVM_MachineType::BinaryCombos)
    return "Binary";
  else if (machineType == SVM_MachineType::BoostSVM)
    return "BoostSVM";
  return "";
} /* MachineTypeToStr */
AttributeType KKMLL::operator++ (AttributeType zed)
Definition at line 566 of file Attribute.cpp.
{
  return (AttributeType)((int)zed + 1);
} /* operator++ */
std::ostream & KKMLL::operator<< (std::ostream & os, const FeatureNumList & features)
std::ostream& KKMLL::operator<< (std::ostream & os, const MLClassList & classList)
KKStr & KKMLL::operator<< (KKStr & str, const MLClassList & classList)
Definition at line 1427 of file MLClass.cpp.
References KKMLL::MLClassList::ToString().
{
  str << classList.ToString ();
  return str;
}
KKStr & KKMLL::operator<< (KKStr & left, TrainingConfiguration2::ModelTypes modelingMethod)
Definition at line 2002 of file TrainingConfiguration2.cpp.
References KKB::KKStr::Append(), and KKMLL::TrainingConfiguration2::ModelTypeToStr().
  {
    left.Append (TrainingConfiguration2::ModelTypeToStr (modelingMethod));
    return left;
  }
ostream & KKMLL::operator<< (std::ostream & os, TrainingConfiguration2::ModelTypes modelingMethod)
Definition at line 2012 of file TrainingConfiguration2.cpp.
References KKMLL::TrainingConfiguration2::ModelTypeToStr(), and KKB::operator<<().
  {
    os << TrainingConfiguration2::ModelTypeToStr (modelingMethod);
    return os;
  }
ostream & KKMLL::operator<< (ostream & os, const FeatureNumList & features)
Definition at line 761 of file FeatureNumList.cpp.
References KKB::operator<<(), and KKMLL::FeatureNumList::ToString().
  {
    os << features.ToString ();
    return os;
  }
bool KKMLL::PairCompareOperator (ProbNamePair l, ProbNamePair r)
Definition at line 1568 of file SVMModel.cpp.
References KKMLL::ProbNamePair::probability.
  {
    return l.probability > r.probability;
  }
SVM_SelectionMethod KKMLL::SelectionMethodFromStr (const KKStr & selectionMethodStr)
Definition at line 1022 of file SVMparam.cpp.
References KKB::KKStr::Concat(), Null, KKB::KKStr::operator==(), Probability, KKB::KKStr::ToUpper(), and Voting.
Referenced by KKMLL::SVMparam::ParseCmdLineParameter().
{
  KKStr selectionMethodUpper = selectionMethodStr.ToUpper ();
  if ((selectionMethodUpper == "VOTE") || (selectionMethodUpper == "VOTING"))
    return SVM_SelectionMethod::Voting;
  if ((selectionMethodUpper == "P") ||
       (selectionMethodUpper == "PROB") ||
       (selectionMethodUpper == "PROBABILITY")
      )
    return SVM_SelectionMethod::Probability;
  return SVM_SelectionMethod::Null;
} /* SelectionMethodFromStr */
KKStr KKMLL::SelectionMethodToStr (SVM_SelectionMethod selectionMethod)
Definition at line 1008 of file SVMparam.cpp.
References Probability, and Voting.
Referenced by KKMLL::ModelOldSVM::Description(), KKMLL::SVMparam::ToString(), and KKMLL::SVMparam::WriteXML().
{
  if (selectionMethod == SVM_SelectionMethod::Voting)
    return "Voting";
  if (selectionMethod == SVM_SelectionMethod::Probability)
    return "Probability";
  return "";
} /* SelectionMethodToStr */
void KKMLL::SvmDestroyModel (struct SvmModel233 ** subModel)
Definition at line 742 of file SvmWrapper.cpp.
References SVM233::svm_destroy_model().
{
  svm_destroy_model (subModel[0]);
}
struct SvmModel233 ** KKMLL::SvmLoadModel (istream & f, RunLog & log)
Definition at line 722 of file SvmWrapper.cpp.
References SVM233::Svm_Load_Model().
{
  SvmModel233** models = new SvmModel233*[1];
  models[0] = Svm_Load_Model (f, log);
  if (models[0] == NULL)
  {
    delete[] models;
    models = NULL;
  }
  return models;
}
[SvmPredictClass(SVMparam svmParam, struct SvmModel233 **subModel, const struct svm_node *unknownClassFeatureData, kkint32 *votes, double *probabilities, kkint32 knownClass, kkint32 predClass1, kkint32 predClass2, kkint32 predClass1Votes, kkint32 predClass2Votes, double predClass1Prob, double predClass2Prob, double probOfKnownClass, Ivector winners, double **crossClassProbTable, double breakTie)]void KKMLL::SvmPredictClass (SVMparam & svmParam, struct SvmModel233 ** subModel, const struct svm_node * unknownClassFeatureData, kkint32 * votes, double * probabilities, kkint32 knownClass, kkint32 & predClass1, kkint32 & predClass2, kkint32 & predClass1Votes, kkint32 & predClass2Votes, double & predClass1Prob, double & predClass2Prob, double & probOfKnownClass, Ivector & winners, double ** crossClassProbTable, double & breakTie)
Parameters
in svmParam Structure that has all the parameters used for building the SVM.
in subModel This is the model(classifier) returned by SvmTrainModel.
in probabilities Array that must be as big as number of classes the probability of each class will be returned where there sum is 1.0
in unknownClassFeatureData data structure you build that represents a sparse array of the feature data that is to be used for prediction.
out probabilities array that will receive the predicted probability for each class.
in knownClass If you happen to know hat the class really is you can specify it here so as to get the probability of it returned back to you.
out predClass1 The prediction will be returned back in this field.
out predClass2 The second most likely class based off either probability or number of votes.
out predClass1Votes Number votes that class 'predClass1' received.
out predClass2Votes Number votes that class 'predClass2' received.
out predClass1Prob Probability that class 'predClass1' received.
out predClass2Prob Probability that class 'predClass2' received.
out probOfKnownClass Probability that 'knownClass' class receved.
out winners If voting was specified in 'svmParam' and there was a tie between 2 or more classes; them the classes that ties will be in this vector.
in crossClassProbTable A 2 dimensional table that will have the computed probabilities between all the possible 2 class combinations.
in breakTie The difference in probability between the two most likely classes.
Definition at line 585 of file SvmWrapper.cpp.
References GreaterVotes(), SVM233::SvmModel233::nr_class, KKMLL::SVMparam::Param(), Probability, and KKMLL::SVMparam::SelectionMethod().
{
  const struct svm_parameter& param = svmParam.Param ();
  kkint32 NUMCLASS = subModel[0][0].nr_class;
  kkint32 numBinary = (NUMCLASS * (NUMCLASS - 1)) / 2;
  Dvector dist (numBinary, 0);
  svm_predict (subModel[0], unknownClassFeatureData, dist, winners, -1);
  ComputeProb (NUMCLASS,
                svmParam.ProbClassPairs (),
                dist, // Distances for each binary classifier from decision boundary.
                crossClassProbTable, // Will get Probabilities between classes.
                votes,
                probabilities, // Probabilities for Each Class
                knownClass // -1 = Don't know the class otherwise the Number of the Class.
               );
  GreaterVotes ((svmParam.SelectionMethod () == SVM_SelectionMethod::Probability
      ),
                NUMCLASS,
                votes,
                probabilities,
                predClass1,
                predClass2
               );
  if (predClass1 >= 0)
  {
    predClass1Votes = votes[predClass1];
    predClass1Prob = probabilities[predClass1];
  }
  if (predClass2 >= 0)
  {
    predClass2Votes = votes[predClass2];
    predClass2Prob = probabilities[predClass2];
  }
  if (knownClass >= 0)
    probOfKnownClass = probabilities[knownClass];
  breakTie = (predClass1Prob - predClass2Prob);
} /* SvmPredictClass */
void KKMLL::SvmPredictRaw (SvmModel233 ** submodel, const svm_node * unKnownData, double & label, double & dist)
Definition at line 684 of file SvmWrapper.cpp.
References SVM233::SvmModel233::nr_class, KKB::osWaitForEnter(), and SVM233::svm_predictTwoClasses().
Referenced by KKMLL::SVMModel::PredictRaw().
{
  if (submodel[0]->nr_class != 2)
  {
    cerr << endl
         << endl
         << "SvmPredictTwoClass *** ERROR ***" << endl
         << endl
         << "Number of classes should be equal to two." << endl
         << endl;
    osWaitForEnter ();
    exit (-1);
  }
  dist = 0.0;
  label = svm_predictTwoClasses (submodel[0], unKnownData, dist, -1);
  return;
} /* SvmPredictRaw */
kkint32 KKMLL::SvmPredictTwoClass (const struct svm_parameter & param, SvmModel233 ** submodel, const svm_node * unKnownData, kkint32 desired, double & dist, double & probability, kkint32 excludeSupportVectorIDX)
void KKMLL::SvmSaveModel (ostream & o, struct SvmModel233 ** model)
Definition at line 711 of file SvmWrapper.cpp.
References SVM233::Svm_Save_Model().
{
   Svm_Save_Model (o, model[0]);
}
struct SvmModel233 ** KKMLL::SvmTrainModel (const struct svm_parameter & param, struct svm_problem & subprob)
Definition at line 543 of file SvmWrapper.cpp.
References BAGGING, BOOSTING, SVM233::svm_parameter::boosting, SVM233::svm_parameter::dimSelect, NORMAL, SVM233::svm_parameter::numSVM, SVM233::svm_parameter::sample, SAMPLESV, SVM233::svm_parameter::sampleSV, SUBSPACE, and SVM233::svm_train().
{
  struct SvmModel233 **submodel;
  kkint32 numSVM = param.numSVM;
  kkint32 sample = (kkint32) (param.sample);
  //kkint32 numClass=param.numClass;
  kkint32 sampleSV = param.sampleSV;
  kkint32 boosting = param.boosting;
  kkint32 dimSelect = param.dimSelect;
  LearnType learnType;
  if ((numSVM == 1) && (sample == 100))
    learnType= LearnType::NORMAL;
  else if (dimSelect > 0)
    learnType = LearnType::SUBSPACE;
  else if (boosting != 0)
    learnType=LearnType::BOOSTING;
  else if(sampleSV!=0)
    learnType=LearnType::SAMPLESV;
  else
    learnType=LearnType::BAGGING;
  submodel = new SvmModel233* [numSVM];
  submodel[0] = svm_train (&subprob, &param);
  return submodel;
} /* SvmTrainModel */
Variable Documentation
const char * KKMLL::FeatureDecriptions
Definition at line 314 of file FeatureNumList_Old.h.
MLClassList KKMLL::globalClassList