SVM289_MFS::svm_problem Struct Reference
#include <svm2.h>
Public Member Functions
svm_problem (const svm_problem &_prob)
svm_problem (const FeatureVectorList &_x, const float *_y, const FeatureNumList &_selFeatures)
svm_problem (const FeatureNumList &_selFeatures, FileDescPtr _fileDesc, RunLog &_log)
~svm_problem ()
FileDescPtr FileDesc () const
const FeatureNumList & SelFeatures () const
Public Attributes
kkint32 numTrainExamples
FeatureNumList selFeatures
FeatureVectorList x
double * y
Detailed Description
Definition at line 43 of file svm2.h.
Constructor & Destructor Documentation
SVM289_MFS::svm_problem::svm_problem (const svm_problem & _prob)
Definition at line 117 of file svm2.cpp.
References KKMLL::FeatureNumList::FeatureNumList(), numTrainExamples, selFeatures, svm_problem(), and y.
Referenced by svm_problem().
                                                            :
      numTrainExamples (_prob.numTrainExamples),
      selFeatures (_prob.selFeatures),
      x (_prob.x, false),
      y (NULL)
{
  clone (y, _prob.y, numTrainExamples);
}
SVM289_MFS::svm_problem::svm_problem (const FeatureVectorList & _x, const float * _y, const FeatureNumList & _selFeatures)
Definition at line 130 of file svm2.cpp.
References KKMLL::FeatureNumList::FeatureNumList(), numTrainExamples, selFeatures, svm_problem(), and y.
Referenced by svm_binary_svc_probability(), svm_problem(), and KKMLL::ModelSvmBase::TrainModel().
                                      :
  numTrainExamples (_x.QueueSize ()),
  selFeatures (_selFeatures),
  x (_x, false),
  y (NULL)
{
  numTrainExamples = _x.QueueSize ();
  y = new double[numTrainExamples];
  kkint32 idx = 0;
  for (idx = 0; idx < numTrainExamples; idx++)
    y[idx] = _y[idx];
}
SVM289_MFS::svm_problem::svm_problem (const FeatureNumList & _selFeatures, FileDescPtr _fileDesc, RunLog & _log)
Definition at line 149 of file svm2.cpp.
References KKMLL::FeatureNumList::FeatureNumList(), numTrainExamples, selFeatures, svm_problem(), and y.
Referenced by SVM289_MFS::svm_cross_validation(), svm_problem(), and SVM289_MFS::svm_train().
                                      :
  numTrainExamples (0),
  selFeatures (_selFeatures),
  x (_fileDesc, false),
  y (NULL)
{
  kkint32 zed = 87989;
}
SVM289_MFS::svm_problem::~svm_problem ()
Definition at line 162 of file svm2.cpp.
References y.
{
  delete y;
  y = NULL;
}
Member Function Documentation
FileDescPtr SVM289_MFS::svm_problem::FileDesc () const
Definition at line 170 of file svm2.cpp.
Referenced by SVM289_MFS::svm_cross_validation(), and SVM289_MFS::svm_train().
{
  return x.FileDesc ();
}
const FeatureNumList& SVM289_MFS::svm_problem::SelFeatures () const [inline]
Definition at line 61 of file svm2.h.
References selFeatures.
Referenced by SVM289_MFS::svm_cross_validation(), and SVM289_MFS::svm_train().
{return selFeatures;}
Member Data Documentation
kkint32 SVM289_MFS::svm_problem::numTrainExamples
Definition at line 63 of file svm2.h.
Referenced by SVM289_MFS::ONE_CLASS_Q::ONE_CLASS_Q(), SVM289_MFS::solve_c_svc(), SVM289_MFS::solve_epsilon_svr(), SVM289_MFS::solve_nu_svc(), solve_nu_svr(), SVM289_MFS::solve_one_class(), SVM289_MFS::SVC_Q::SVC_Q(), svm_binary_svc_probability(), svm_check_parameter(), SVM289_MFS::svm_cross_validation(), svm_group_classes(), svm_problem(), svm_svr_probability(), SVM289_MFS::svm_train(), SVM289_MFS::svm_train_one(), and SVM289_MFS::SVR_Q::SVR_Q().
FeatureNumList SVM289_MFS::svm_problem::selFeatures
Definition at line 64 of file svm2.h.
Referenced by SelFeatures(), svm_binary_svc_probability(), and svm_problem().
FeatureVectorList SVM289_MFS::svm_problem::x
Definition at line 65 of file svm2.h.
double* SVM289_MFS::svm_problem::y
Definition at line 66 of file svm2.h.
Referenced by SVM289_MFS::solve_c_svc(), SVM289_MFS::solve_epsilon_svr(), SVM289_MFS::solve_nu_svc(), solve_nu_svr(), svm_binary_svc_probability(), svm_check_parameter(), SVM289_MFS::svm_cross_validation(), svm_group_classes(), svm_problem(), svm_svr_probability(), SVM289_MFS::svm_train(), SVM289_MFS::svm_train_one(), and ~svm_problem().
The documentation for this struct was generated from the following files:
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm2.h
C:/Users/Kurt/GitHub/KSquareLibraries/KKMachineLearning/svm2.cpp