set cmd="git describe --long  --dirty "
FOR /F "tokens=*" %%i IN (' %cmd% ') DO SET X=%%i

set cmdY="git config remote.origin.url"
FOR /F "tokens=*" %%j IN (' %cmdY% ') DO SET Y=%%j

echo #if  !defined(_KKMLLGitVersionNum_)>             KKMLLGitVersionNum.h
echo #define _KKMLLGitVersionNum_>>                   KKMLLGitVersionNum.h
echo // Generated by Pre-Build-Event>>                KKMLLGitVersionNum.h
echo namespace KKMLL>>                                KKMLLGitVersionNum.h
echo ^{>>                                             KKMLLGitVersionNum.h
echo   const char* GitVersionNum      () noexcept;>>  KKMLLGitVersionNum.h
echo   const char* GitRemoteOriginURL () noexcept;>>  KKMLLGitVersionNum.h
echo ^}>>                                             KKMLLGitVersionNum.h
echo #endif>>                                         KKMLLGitVersionNum.h
echo // Generated by Pre-Build-Event>                 KKMLLGitVersionNum.cpp
echo #include ^"KKMLLGitVersionNum.h^">>              KKMLLGitVersionNum.cpp
echo namespace KKMLL>>                                  KKMLLGitVersionNum.cpp
echo ^{>>                                             KKMLLGitVersionNum.cpp
echo   const char* GitVersionNum () noexcept>>        KKMLLGitVersionNum.cpp
echo   ^{>>                                           KKMLLGitVersionNum.cpp
echo      return ^"%X%^";>>                           KKMLLGitVersionNum.cpp
echo   ^}>>                                           KKMLLGitVersionNum.cpp
echo   //>>                                           KKMLLGitVersionNum.cpp
echo   const char* GitRemoteOriginURL () noexcept>>   KKMLLGitVersionNum.cpp
echo   ^{>>                                           KKMLLGitVersionNum.cpp
echo      return ^"%Y%^";>>                           KKMLLGitVersionNum.cpp
echo   ^}>>KKMLLGitVersionNum.cpp
echo ^}>>KKMLLGitVersionNum.cpp
