#if  !defined(_CLASSASSIGNMENTS_)
#define  _CLASSASSIGNMENTS_

/**
 *@class KKMLL::ClassAssignments
 *@author Kurt Kramer
 *@brief Binds MLClass objects to the appropriate number that the Learning Algorithm expects.
 *@details This class will bind MLClass objects to the appropriate number that the learning 
 *         algorithm knows for this class.  When originally implementing this system, this info was 
 *         kept in the MLClass object.  This would cause problems when doing multilevel
 *         classification.  The same MLClass might be known to the L.A. as one number in one level 
 *         and another number in a different level.  This caused us to have to maintain a separate
 *         instantiation of these classes on the SvmModel objects. 
 *
 *         It is sub-classed from multimap<kkint16, MLClassPtr>. This allows for fast lookup by 
 *         number.  There is also a secondary index by MLClass. This allows us to do a fast 
 *         lookup by class.
 */

#include <map>
#include "KKQueue.h"
#include "RunLog.h"
#include "KKStr.h"

namespace KKMLL
{

  #ifndef  _MLCLASS_
  class MLClass;
  typedef  MLClass*         MLClassPtr;
  typedef  MLClass const    MLClassConst;
  typedef  MLClassConst*    MLClassConstPtr;
  class MLClassList;
  typedef  MLClassList*  MLClassListPtr;
  #endif


  class  ClassAssignments: public  std::multimap<kkint16, MLClassPtr>
  {
  public:
    ClassAssignments ();


    /**
    *@brief Creates assignment for all classes in 'classes.
    *@details Constructs a list assigning a number to each class sequentially from 'classes'.
    *         Use this constructor if each class is treated uniquely by the learning algorithm.
    *@param[in] classes, List of classes to make assignments for.
    *@param[in,out] _log, Run log to write messages to
    */
    ClassAssignments (const MLClassList&  classes);


    void  AddMLClass (MLClassPtr  mlClass,
                      kkint16     num,
                      RunLog&     log
                     );

    MLClassPtr      GetMLClassByIndex (size_t idx);

    MLClassPtr      GetMLClass    (kkint16 num)  const;

    MLClassList     GetMLClasses (kkint16 num)  const;

    kkint16         GetNumForClass (MLClassPtr  mlClass)  const;

    VectorShort     GetUniqueListOfAssignments ()  const;

    void            Load (const KKStr&  fileName,
                          bool&         successful,
                          RunLog&       log
                         );

    kkint32         MemoryConsumedEstimated ()  const;

    /**
    *@brief Loads class assignments from string that was originally generated by ToString
    *@param[in] _toString,  KKStr containing class assignments info, will expect to be formated
    *                       the way ToString() creates them.
    */
    void            ParseToString (const KKStr&  _toString,
                                   RunLog&       _log
                                  );


    void            Save (const KKStr&  fileName,
                          bool&         successful
                         );

    KKStr           ToString ()  const;

  private:
    typedef  std::map<MLClassPtr, kkint16>  ClassLookUp;
    typedef  ClassLookUp::iterator          ClassLookUpIterator;

    ClassLookUp  classLookUp;
  };  /* ClassAssignments */;


  typedef  ClassAssignments*  ClassAssignmentsPtr;

}  /* namespace KKMLL */

#endif
